// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'JuFufu',
    name: 'standardDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'standardDmgBase',
      sheet: 'JuFufu',
      attribute: 'fire',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'JuFufu',
    name: 'anomalyDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_fire: {
    sheet: 'JuFufu',
    name: 'disorderDmgInst_fire',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'disorder',
      name: 'disorderDmgInst_fire',
    },
  },
  vortexDmgInst_fire: {
    sheet: 'JuFufu',
    name: 'vortexDmgInst_fire',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'vortex',
      name: 'vortexDmgInst_fire',
    },
  },
  abloomDmgInst: {
    sheet: 'JuFufu',
    name: 'abloomDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'JuFufu',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'JuFufu',
      attribute: 'fire',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'JuFufu',
    name: 'dazeInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'dazeBuildupBase',
      sheet: 'JuFufu',
      attribute: 'fire',
      name: 'dazeInst',
    },
  },
  BasicAttackTigerSevenFormsFlamingClaw_0: {
    sheet: 'JuFufu',
    name: 'BasicAttackTigerSevenFormsFlamingClaw_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'JuFufu',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackTigerSevenFormsFlamingClaw_0',
    },
  },
  BasicAttackTigerSevenFormsFlamingClaw_1: {
    sheet: 'JuFufu',
    name: 'BasicAttackTigerSevenFormsFlamingClaw_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'JuFufu',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackTigerSevenFormsFlamingClaw_1',
    },
  },
  BasicAttackTigerSevenFormsFlamingClaw_2: {
    sheet: 'JuFufu',
    name: 'BasicAttackTigerSevenFormsFlamingClaw_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTigerSevenFormsFlamingClaw_2',
    },
  },
  BasicAttackTigerSevenFormsFlamingClaw_3: {
    sheet: 'JuFufu',
    name: 'BasicAttackTigerSevenFormsFlamingClaw_3',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTigerSevenFormsFlamingClaw_3',
    },
  },
  BasicAttackHuWei_0: {
    sheet: 'JuFufu',
    name: 'BasicAttackHuWei_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackHuWei_0',
    },
  },
  DashAttackTigerSevenFormsTigerCharge_0: {
    sheet: 'JuFufu',
    name: 'DashAttackTigerSevenFormsTigerCharge_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'JuFufu',
      damageType1: 'dash',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttackTigerSevenFormsTigerCharge_0',
    },
  },
  DashAttackTigerSevenFormsMountainKingsGame_0: {
    sheet: 'JuFufu',
    name: 'DashAttackTigerSevenFormsMountainKingsGame_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'JuFufu',
      damageType1: 'dash',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttackTigerSevenFormsMountainKingsGame_0',
    },
  },
  DodgeCounterTigerSevenFormsReignitedMountain_0: {
    sheet: 'JuFufu',
    name: 'DodgeCounterTigerSevenFormsReignitedMountain_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterTigerSevenFormsReignitedMountain_0',
    },
  },
  DashAttackTigerSevenFormsMountainKingsGameMomentum_0: {
    sheet: 'JuFufu',
    name: 'DashAttackTigerSevenFormsMountainKingsGameMomentum_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackTigerSevenFormsMountainKingsGameMomentum_0',
    },
  },
  SpecialAttackTigerSevenFormsMountainDescendingTiger_0: {
    sheet: 'JuFufu',
    name: 'SpecialAttackTigerSevenFormsMountainDescendingTiger_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackTigerSevenFormsMountainDescendingTiger_0',
    },
  },
  EXSpecialAttackTigerSevenFormsAltMountainDescendingSavageTiger_0: {
    sheet: 'JuFufu',
    name: 'EXSpecialAttackTigerSevenFormsAltMountainDescendingSavageTiger_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackTigerSevenFormsAltMountainDescendingSavageTiger_0',
    },
  },
  ChainAttackTigerCauldronCollapse_0: {
    sheet: 'JuFufu',
    name: 'ChainAttackTigerCauldronCollapse_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackTigerCauldronCollapse_0',
    },
  },
  ChainAttackSuppressingTigerCauldron_0: {
    sheet: 'JuFufu',
    name: 'ChainAttackSuppressingTigerCauldron_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'chain',
      damageType2: 'aftershock',
      skillType: 'chainSkill',
      name: 'ChainAttackSuppressingTigerCauldron_0',
    },
  },
  UltimateTigerSevenFormsRagingTigerExplosion_0: {
    sheet: 'JuFufu',
    name: 'UltimateTigerSevenFormsRagingTigerExplosion_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateTigerSevenFormsRagingTigerExplosion_0',
    },
  },
  QuickAssistDecisiveStomp_0: {
    sheet: 'JuFufu',
    name: 'QuickAssistDecisiveStomp_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistDecisiveStomp_0',
    },
  },
  DefensiveAssistSteadfastCrouchingTiger_0: {
    sheet: 'JuFufu',
    name: 'DefensiveAssistSteadfastCrouchingTiger_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistSteadfastCrouchingTiger_0',
    },
  },
  DefensiveAssistSteadfastCrouchingTiger_1: {
    sheet: 'JuFufu',
    name: 'DefensiveAssistSteadfastCrouchingTiger_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistSteadfastCrouchingTiger_1',
    },
  },
  DefensiveAssistSteadfastCrouchingTiger_2: {
    sheet: 'JuFufu',
    name: 'DefensiveAssistSteadfastCrouchingTiger_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistSteadfastCrouchingTiger_2',
    },
  },
  AssistFollowUpFeralBlazingMaw_0: {
    sheet: 'JuFufu',
    name: 'AssistFollowUpFeralBlazingMaw_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpFeralBlazingMaw_0',
    },
  },
  m6_dmg: {
    sheet: 'JuFufu',
    name: 'm6_dmg',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'standardDmgBase',
      sheet: 'JuFufu',
      damageType1: 'chain',
      name: 'm6_dmg',
    },
  },
} as const
