// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'JuFufu',
    name: 'standardDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'JuFufu',
      attribute: 'fire',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'JuFufu',
    name: 'anomalyDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_fire: {
    sheet: 'JuFufu',
    name: 'disorderDmgInst_fire',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'disorder',
      name: 'disorderDmgInst_fire',
    },
  },
  anomalyBuildupInst: {
    sheet: 'JuFufu',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'JuFufu',
      attribute: 'fire',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'JuFufu',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'JuFufu',
      attribute: 'fire',
      name: 'dazeInst',
    },
  },
  BasicAttackTigerSevenFormsFlamingClaw_0_dmg: {
    sheet: 'JuFufu',
    name: 'BasicAttackTigerSevenFormsFlamingClaw_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'JuFufu',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackTigerSevenFormsFlamingClaw_0_dmg',
    },
  },
  BasicAttackTigerSevenFormsFlamingClaw_0_daze: {
    sheet: 'JuFufu',
    name: 'BasicAttackTigerSevenFormsFlamingClaw_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'JuFufu',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackTigerSevenFormsFlamingClaw_0_daze',
    },
  },
  BasicAttackTigerSevenFormsFlamingClaw_0_anomBuildup: {
    sheet: 'JuFufu',
    name: 'BasicAttackTigerSevenFormsFlamingClaw_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'JuFufu',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackTigerSevenFormsFlamingClaw_0_anomBuildup',
    },
  },
  BasicAttackTigerSevenFormsFlamingClaw_1_dmg: {
    sheet: 'JuFufu',
    name: 'BasicAttackTigerSevenFormsFlamingClaw_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'JuFufu',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackTigerSevenFormsFlamingClaw_1_dmg',
    },
  },
  BasicAttackTigerSevenFormsFlamingClaw_1_daze: {
    sheet: 'JuFufu',
    name: 'BasicAttackTigerSevenFormsFlamingClaw_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'JuFufu',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackTigerSevenFormsFlamingClaw_1_daze',
    },
  },
  BasicAttackTigerSevenFormsFlamingClaw_1_anomBuildup: {
    sheet: 'JuFufu',
    name: 'BasicAttackTigerSevenFormsFlamingClaw_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'JuFufu',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackTigerSevenFormsFlamingClaw_1_anomBuildup',
    },
  },
  BasicAttackTigerSevenFormsFlamingClaw_2_dmg: {
    sheet: 'JuFufu',
    name: 'BasicAttackTigerSevenFormsFlamingClaw_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTigerSevenFormsFlamingClaw_2_dmg',
    },
  },
  BasicAttackTigerSevenFormsFlamingClaw_2_daze: {
    sheet: 'JuFufu',
    name: 'BasicAttackTigerSevenFormsFlamingClaw_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTigerSevenFormsFlamingClaw_2_daze',
    },
  },
  BasicAttackTigerSevenFormsFlamingClaw_2_anomBuildup: {
    sheet: 'JuFufu',
    name: 'BasicAttackTigerSevenFormsFlamingClaw_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTigerSevenFormsFlamingClaw_2_anomBuildup',
    },
  },
  BasicAttackTigerSevenFormsFlamingClaw_3_dmg: {
    sheet: 'JuFufu',
    name: 'BasicAttackTigerSevenFormsFlamingClaw_3_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTigerSevenFormsFlamingClaw_3_dmg',
    },
  },
  BasicAttackTigerSevenFormsFlamingClaw_3_daze: {
    sheet: 'JuFufu',
    name: 'BasicAttackTigerSevenFormsFlamingClaw_3_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTigerSevenFormsFlamingClaw_3_daze',
    },
  },
  BasicAttackTigerSevenFormsFlamingClaw_3_anomBuildup: {
    sheet: 'JuFufu',
    name: 'BasicAttackTigerSevenFormsFlamingClaw_3_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTigerSevenFormsFlamingClaw_3_anomBuildup',
    },
  },
  BasicAttackHuWei_0_dmg: {
    sheet: 'JuFufu',
    name: 'BasicAttackHuWei_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackHuWei_0_dmg',
    },
  },
  BasicAttackHuWei_0_daze: {
    sheet: 'JuFufu',
    name: 'BasicAttackHuWei_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackHuWei_0_daze',
    },
  },
  BasicAttackHuWei_0_anomBuildup: {
    sheet: 'JuFufu',
    name: 'BasicAttackHuWei_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackHuWei_0_anomBuildup',
    },
  },
  DashAttackTigerSevenFormsTigerCharge_0_dmg: {
    sheet: 'JuFufu',
    name: 'DashAttackTigerSevenFormsTigerCharge_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'JuFufu',
      damageType1: 'dash',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttackTigerSevenFormsTigerCharge_0_dmg',
    },
  },
  DashAttackTigerSevenFormsTigerCharge_0_daze: {
    sheet: 'JuFufu',
    name: 'DashAttackTigerSevenFormsTigerCharge_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'JuFufu',
      damageType1: 'dash',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttackTigerSevenFormsTigerCharge_0_daze',
    },
  },
  DashAttackTigerSevenFormsTigerCharge_0_anomBuildup: {
    sheet: 'JuFufu',
    name: 'DashAttackTigerSevenFormsTigerCharge_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'JuFufu',
      damageType1: 'dash',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttackTigerSevenFormsTigerCharge_0_anomBuildup',
    },
  },
  DashAttackTigerSevenFormsMountainKingsGame_0_dmg: {
    sheet: 'JuFufu',
    name: 'DashAttackTigerSevenFormsMountainKingsGame_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'JuFufu',
      damageType1: 'dash',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttackTigerSevenFormsMountainKingsGame_0_dmg',
    },
  },
  DashAttackTigerSevenFormsMountainKingsGame_0_daze: {
    sheet: 'JuFufu',
    name: 'DashAttackTigerSevenFormsMountainKingsGame_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'JuFufu',
      damageType1: 'dash',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttackTigerSevenFormsMountainKingsGame_0_daze',
    },
  },
  DashAttackTigerSevenFormsMountainKingsGame_0_anomBuildup: {
    sheet: 'JuFufu',
    name: 'DashAttackTigerSevenFormsMountainKingsGame_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'JuFufu',
      damageType1: 'dash',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttackTigerSevenFormsMountainKingsGame_0_anomBuildup',
    },
  },
  DodgeCounterTigerSevenFormsReignitedMountain_0_dmg: {
    sheet: 'JuFufu',
    name: 'DodgeCounterTigerSevenFormsReignitedMountain_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterTigerSevenFormsReignitedMountain_0_dmg',
    },
  },
  DodgeCounterTigerSevenFormsReignitedMountain_0_daze: {
    sheet: 'JuFufu',
    name: 'DodgeCounterTigerSevenFormsReignitedMountain_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterTigerSevenFormsReignitedMountain_0_daze',
    },
  },
  DodgeCounterTigerSevenFormsReignitedMountain_0_anomBuildup: {
    sheet: 'JuFufu',
    name: 'DodgeCounterTigerSevenFormsReignitedMountain_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterTigerSevenFormsReignitedMountain_0_anomBuildup',
    },
  },
  DashAttackTigerSevenFormsMountainKingsGameMomentum_0_dmg: {
    sheet: 'JuFufu',
    name: 'DashAttackTigerSevenFormsMountainKingsGameMomentum_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackTigerSevenFormsMountainKingsGameMomentum_0_dmg',
    },
  },
  DashAttackTigerSevenFormsMountainKingsGameMomentum_0_daze: {
    sheet: 'JuFufu',
    name: 'DashAttackTigerSevenFormsMountainKingsGameMomentum_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackTigerSevenFormsMountainKingsGameMomentum_0_daze',
    },
  },
  DashAttackTigerSevenFormsMountainKingsGameMomentum_0_anomBuildup: {
    sheet: 'JuFufu',
    name: 'DashAttackTigerSevenFormsMountainKingsGameMomentum_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackTigerSevenFormsMountainKingsGameMomentum_0_anomBuildup',
    },
  },
  SpecialAttackTigerSevenFormsMountainDescendingTiger_0_dmg: {
    sheet: 'JuFufu',
    name: 'SpecialAttackTigerSevenFormsMountainDescendingTiger_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackTigerSevenFormsMountainDescendingTiger_0_dmg',
    },
  },
  SpecialAttackTigerSevenFormsMountainDescendingTiger_0_daze: {
    sheet: 'JuFufu',
    name: 'SpecialAttackTigerSevenFormsMountainDescendingTiger_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackTigerSevenFormsMountainDescendingTiger_0_daze',
    },
  },
  SpecialAttackTigerSevenFormsMountainDescendingTiger_0_anomBuildup: {
    sheet: 'JuFufu',
    name: 'SpecialAttackTigerSevenFormsMountainDescendingTiger_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackTigerSevenFormsMountainDescendingTiger_0_anomBuildup',
    },
  },
  EXSpecialAttackTigerSevenFormsAltMountainDescendingSavageTiger_0_dmg: {
    sheet: 'JuFufu',
    name: 'EXSpecialAttackTigerSevenFormsAltMountainDescendingSavageTiger_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackTigerSevenFormsAltMountainDescendingSavageTiger_0_dmg',
    },
  },
  EXSpecialAttackTigerSevenFormsAltMountainDescendingSavageTiger_0_daze: {
    sheet: 'JuFufu',
    name: 'EXSpecialAttackTigerSevenFormsAltMountainDescendingSavageTiger_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackTigerSevenFormsAltMountainDescendingSavageTiger_0_daze',
    },
  },
  EXSpecialAttackTigerSevenFormsAltMountainDescendingSavageTiger_0_anomBuildup:
    {
      sheet: 'JuFufu',
      name: 'EXSpecialAttackTigerSevenFormsAltMountainDescendingSavageTiger_0_anomBuildup',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'anomBuildup',
        sheet: 'JuFufu',
        attribute: 'fire',
        damageType1: 'exSpecial',
        skillType: 'specialSkill',
        name: 'EXSpecialAttackTigerSevenFormsAltMountainDescendingSavageTiger_0_anomBuildup',
      },
    },
  ChainAttackTigerCauldronCollapse_0_dmg: {
    sheet: 'JuFufu',
    name: 'ChainAttackTigerCauldronCollapse_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackTigerCauldronCollapse_0_dmg',
    },
  },
  ChainAttackTigerCauldronCollapse_0_daze: {
    sheet: 'JuFufu',
    name: 'ChainAttackTigerCauldronCollapse_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackTigerCauldronCollapse_0_daze',
    },
  },
  ChainAttackTigerCauldronCollapse_0_anomBuildup: {
    sheet: 'JuFufu',
    name: 'ChainAttackTigerCauldronCollapse_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackTigerCauldronCollapse_0_anomBuildup',
    },
  },
  ChainAttackSuppressingTigerCauldron_0_dmg: {
    sheet: 'JuFufu',
    name: 'ChainAttackSuppressingTigerCauldron_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'chain',
      damageType2: 'aftershock',
      skillType: 'chainSkill',
      name: 'ChainAttackSuppressingTigerCauldron_0_dmg',
    },
  },
  ChainAttackSuppressingTigerCauldron_0_daze: {
    sheet: 'JuFufu',
    name: 'ChainAttackSuppressingTigerCauldron_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'chain',
      damageType2: 'aftershock',
      skillType: 'chainSkill',
      name: 'ChainAttackSuppressingTigerCauldron_0_daze',
    },
  },
  ChainAttackSuppressingTigerCauldron_0_anomBuildup: {
    sheet: 'JuFufu',
    name: 'ChainAttackSuppressingTigerCauldron_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'chain',
      damageType2: 'aftershock',
      skillType: 'chainSkill',
      name: 'ChainAttackSuppressingTigerCauldron_0_anomBuildup',
    },
  },
  UltimateTigerSevenFormsRagingTigerExplosion_0_dmg: {
    sheet: 'JuFufu',
    name: 'UltimateTigerSevenFormsRagingTigerExplosion_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateTigerSevenFormsRagingTigerExplosion_0_dmg',
    },
  },
  UltimateTigerSevenFormsRagingTigerExplosion_0_daze: {
    sheet: 'JuFufu',
    name: 'UltimateTigerSevenFormsRagingTigerExplosion_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateTigerSevenFormsRagingTigerExplosion_0_daze',
    },
  },
  UltimateTigerSevenFormsRagingTigerExplosion_0_anomBuildup: {
    sheet: 'JuFufu',
    name: 'UltimateTigerSevenFormsRagingTigerExplosion_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateTigerSevenFormsRagingTigerExplosion_0_anomBuildup',
    },
  },
  QuickAssistDecisiveStomp_0_dmg: {
    sheet: 'JuFufu',
    name: 'QuickAssistDecisiveStomp_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistDecisiveStomp_0_dmg',
    },
  },
  QuickAssistDecisiveStomp_0_daze: {
    sheet: 'JuFufu',
    name: 'QuickAssistDecisiveStomp_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistDecisiveStomp_0_daze',
    },
  },
  QuickAssistDecisiveStomp_0_anomBuildup: {
    sheet: 'JuFufu',
    name: 'QuickAssistDecisiveStomp_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistDecisiveStomp_0_anomBuildup',
    },
  },
  DefensiveAssistSteadfastCrouchingTiger_0_dmg: {
    sheet: 'JuFufu',
    name: 'DefensiveAssistSteadfastCrouchingTiger_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistSteadfastCrouchingTiger_0_dmg',
    },
  },
  DefensiveAssistSteadfastCrouchingTiger_0_daze: {
    sheet: 'JuFufu',
    name: 'DefensiveAssistSteadfastCrouchingTiger_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistSteadfastCrouchingTiger_0_daze',
    },
  },
  DefensiveAssistSteadfastCrouchingTiger_0_anomBuildup: {
    sheet: 'JuFufu',
    name: 'DefensiveAssistSteadfastCrouchingTiger_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistSteadfastCrouchingTiger_0_anomBuildup',
    },
  },
  DefensiveAssistSteadfastCrouchingTiger_1_dmg: {
    sheet: 'JuFufu',
    name: 'DefensiveAssistSteadfastCrouchingTiger_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistSteadfastCrouchingTiger_1_dmg',
    },
  },
  DefensiveAssistSteadfastCrouchingTiger_1_daze: {
    sheet: 'JuFufu',
    name: 'DefensiveAssistSteadfastCrouchingTiger_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistSteadfastCrouchingTiger_1_daze',
    },
  },
  DefensiveAssistSteadfastCrouchingTiger_1_anomBuildup: {
    sheet: 'JuFufu',
    name: 'DefensiveAssistSteadfastCrouchingTiger_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistSteadfastCrouchingTiger_1_anomBuildup',
    },
  },
  DefensiveAssistSteadfastCrouchingTiger_2_dmg: {
    sheet: 'JuFufu',
    name: 'DefensiveAssistSteadfastCrouchingTiger_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistSteadfastCrouchingTiger_2_dmg',
    },
  },
  DefensiveAssistSteadfastCrouchingTiger_2_daze: {
    sheet: 'JuFufu',
    name: 'DefensiveAssistSteadfastCrouchingTiger_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistSteadfastCrouchingTiger_2_daze',
    },
  },
  DefensiveAssistSteadfastCrouchingTiger_2_anomBuildup: {
    sheet: 'JuFufu',
    name: 'DefensiveAssistSteadfastCrouchingTiger_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistSteadfastCrouchingTiger_2_anomBuildup',
    },
  },
  AssistFollowUpFeralBlazingMaw_0_dmg: {
    sheet: 'JuFufu',
    name: 'AssistFollowUpFeralBlazingMaw_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpFeralBlazingMaw_0_dmg',
    },
  },
  AssistFollowUpFeralBlazingMaw_0_daze: {
    sheet: 'JuFufu',
    name: 'AssistFollowUpFeralBlazingMaw_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpFeralBlazingMaw_0_daze',
    },
  },
  AssistFollowUpFeralBlazingMaw_0_anomBuildup: {
    sheet: 'JuFufu',
    name: 'AssistFollowUpFeralBlazingMaw_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'JuFufu',
      attribute: 'fire',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpFeralBlazingMaw_0_anomBuildup',
    },
  },
  m6_dmg: {
    sheet: 'JuFufu',
    name: 'm6_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'JuFufu',
      damageType1: 'chain',
      name: 'm6_dmg',
    },
  },
} as const
