// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Billy',
    name: 'standardDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Billy',
      attribute: 'physical',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Billy',
    name: 'anomalyDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_physical: {
    sheet: 'Billy',
    name: 'disorderDmgInst_physical',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'disorder',
      name: 'disorderDmgInst_physical',
    },
  },
  vortexDmgInst_physical: {
    sheet: 'Billy',
    name: 'vortexDmgInst_physical',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'vortex',
      name: 'vortexDmgInst_physical',
    },
  },
  abloomDmgInst: {
    sheet: 'Billy',
    name: 'abloomDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Billy',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Billy',
      attribute: 'physical',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Billy',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Billy',
      attribute: 'physical',
      name: 'dazeInst',
    },
  },
  'BasicAttackFullFirepower_0:standardDmg': {
    sheet: 'Billy',
    name: 'BasicAttackFullFirepower_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFullFirepower_0',
    },
  },
  'BasicAttackFullFirepower_0:dazeBuildup': {
    sheet: 'Billy',
    name: 'BasicAttackFullFirepower_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFullFirepower_0',
    },
  },
  'BasicAttackFullFirepower_0:anomBuildup': {
    sheet: 'Billy',
    name: 'BasicAttackFullFirepower_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFullFirepower_0',
    },
  },
  'BasicAttackFullFirepower_1:standardDmg': {
    sheet: 'Billy',
    name: 'BasicAttackFullFirepower_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFullFirepower_1',
    },
  },
  'BasicAttackFullFirepower_1:dazeBuildup': {
    sheet: 'Billy',
    name: 'BasicAttackFullFirepower_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFullFirepower_1',
    },
  },
  'BasicAttackFullFirepower_1:anomBuildup': {
    sheet: 'Billy',
    name: 'BasicAttackFullFirepower_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFullFirepower_1',
    },
  },
  'BasicAttackFullFirepower_2:standardDmg': {
    sheet: 'Billy',
    name: 'BasicAttackFullFirepower_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Billy',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackFullFirepower_2',
    },
  },
  'BasicAttackFullFirepower_2:dazeBuildup': {
    sheet: 'Billy',
    name: 'BasicAttackFullFirepower_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Billy',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackFullFirepower_2',
    },
  },
  'BasicAttackFullFirepower_2:anomBuildup': {
    sheet: 'Billy',
    name: 'BasicAttackFullFirepower_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Billy',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackFullFirepower_2',
    },
  },
  'BasicAttackFullFirepower_3:standardDmg': {
    sheet: 'Billy',
    name: 'BasicAttackFullFirepower_3:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Billy',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackFullFirepower_3',
    },
  },
  'BasicAttackFullFirepower_3:dazeBuildup': {
    sheet: 'Billy',
    name: 'BasicAttackFullFirepower_3:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Billy',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackFullFirepower_3',
    },
  },
  'BasicAttackFullFirepower_3:anomBuildup': {
    sheet: 'Billy',
    name: 'BasicAttackFullFirepower_3:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Billy',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackFullFirepower_3',
    },
  },
  'BasicAttackFullFirepower_4:standardDmg': {
    sheet: 'Billy',
    name: 'BasicAttackFullFirepower_4:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFullFirepower_4',
    },
  },
  'BasicAttackFullFirepower_4:dazeBuildup': {
    sheet: 'Billy',
    name: 'BasicAttackFullFirepower_4:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFullFirepower_4',
    },
  },
  'BasicAttackFullFirepower_4:anomBuildup': {
    sheet: 'Billy',
    name: 'BasicAttackFullFirepower_4:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFullFirepower_4',
    },
  },
  'DashAttackStarlightSanction_0:standardDmg': {
    sheet: 'Billy',
    name: 'DashAttackStarlightSanction_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackStarlightSanction_0',
    },
  },
  'DashAttackStarlightSanction_0:dazeBuildup': {
    sheet: 'Billy',
    name: 'DashAttackStarlightSanction_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackStarlightSanction_0',
    },
  },
  'DashAttackStarlightSanction_0:anomBuildup': {
    sheet: 'Billy',
    name: 'DashAttackStarlightSanction_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackStarlightSanction_0',
    },
  },
  'DashAttackStarlightSanction_1:standardDmg': {
    sheet: 'Billy',
    name: 'DashAttackStarlightSanction_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackStarlightSanction_1',
    },
  },
  'DashAttackStarlightSanction_1:dazeBuildup': {
    sheet: 'Billy',
    name: 'DashAttackStarlightSanction_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackStarlightSanction_1',
    },
  },
  'DashAttackStarlightSanction_1:anomBuildup': {
    sheet: 'Billy',
    name: 'DashAttackStarlightSanction_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackStarlightSanction_1',
    },
  },
  'DodgeCounterFairFight_0:standardDmg': {
    sheet: 'Billy',
    name: 'DodgeCounterFairFight_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterFairFight_0',
    },
  },
  'DodgeCounterFairFight_0:dazeBuildup': {
    sheet: 'Billy',
    name: 'DodgeCounterFairFight_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterFairFight_0',
    },
  },
  'DodgeCounterFairFight_0:anomBuildup': {
    sheet: 'Billy',
    name: 'DodgeCounterFairFight_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterFairFight_0',
    },
  },
  'SpecialAttackStandStill_0:standardDmg': {
    sheet: 'Billy',
    name: 'SpecialAttackStandStill_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackStandStill_0',
    },
  },
  'SpecialAttackStandStill_0:dazeBuildup': {
    sheet: 'Billy',
    name: 'SpecialAttackStandStill_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackStandStill_0',
    },
  },
  'SpecialAttackStandStill_0:anomBuildup': {
    sheet: 'Billy',
    name: 'SpecialAttackStandStill_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackStandStill_0',
    },
  },
  'SpecialAttackStandStill_1:standardDmg': {
    sheet: 'Billy',
    name: 'SpecialAttackStandStill_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackStandStill_1',
    },
  },
  'SpecialAttackStandStill_1:dazeBuildup': {
    sheet: 'Billy',
    name: 'SpecialAttackStandStill_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackStandStill_1',
    },
  },
  'SpecialAttackStandStill_1:anomBuildup': {
    sheet: 'Billy',
    name: 'SpecialAttackStandStill_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackStandStill_1',
    },
  },
  'SpecialAttackStandStill_2:standardDmg': {
    sheet: 'Billy',
    name: 'SpecialAttackStandStill_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackStandStill_2',
    },
  },
  'SpecialAttackStandStill_2:dazeBuildup': {
    sheet: 'Billy',
    name: 'SpecialAttackStandStill_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackStandStill_2',
    },
  },
  'SpecialAttackStandStill_2:anomBuildup': {
    sheet: 'Billy',
    name: 'SpecialAttackStandStill_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackStandStill_2',
    },
  },
  'EXSpecialAttackClearanceTime_0:standardDmg': {
    sheet: 'Billy',
    name: 'EXSpecialAttackClearanceTime_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackClearanceTime_0',
    },
  },
  'EXSpecialAttackClearanceTime_0:dazeBuildup': {
    sheet: 'Billy',
    name: 'EXSpecialAttackClearanceTime_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackClearanceTime_0',
    },
  },
  'EXSpecialAttackClearanceTime_0:anomBuildup': {
    sheet: 'Billy',
    name: 'EXSpecialAttackClearanceTime_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackClearanceTime_0',
    },
  },
  'ChainAttackStarlightMirage_0:standardDmg': {
    sheet: 'Billy',
    name: 'ChainAttackStarlightMirage_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackStarlightMirage_0',
    },
  },
  'ChainAttackStarlightMirage_0:dazeBuildup': {
    sheet: 'Billy',
    name: 'ChainAttackStarlightMirage_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackStarlightMirage_0',
    },
  },
  'ChainAttackStarlightMirage_0:anomBuildup': {
    sheet: 'Billy',
    name: 'ChainAttackStarlightMirage_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackStarlightMirage_0',
    },
  },
  'UltimateStarlightShineBright_0:standardDmg': {
    sheet: 'Billy',
    name: 'UltimateStarlightShineBright_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateStarlightShineBright_0',
    },
  },
  'UltimateStarlightShineBright_0:dazeBuildup': {
    sheet: 'Billy',
    name: 'UltimateStarlightShineBright_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateStarlightShineBright_0',
    },
  },
  'UltimateStarlightShineBright_0:anomBuildup': {
    sheet: 'Billy',
    name: 'UltimateStarlightShineBright_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateStarlightShineBright_0',
    },
  },
  'QuickAssistPowerOfTeamwork_0:standardDmg': {
    sheet: 'Billy',
    name: 'QuickAssistPowerOfTeamwork_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistPowerOfTeamwork_0',
    },
  },
  'QuickAssistPowerOfTeamwork_0:dazeBuildup': {
    sheet: 'Billy',
    name: 'QuickAssistPowerOfTeamwork_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistPowerOfTeamwork_0',
    },
  },
  'QuickAssistPowerOfTeamwork_0:anomBuildup': {
    sheet: 'Billy',
    name: 'QuickAssistPowerOfTeamwork_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistPowerOfTeamwork_0',
    },
  },
  'AssistFollowUpFatalShot_0:standardDmg': {
    sheet: 'Billy',
    name: 'AssistFollowUpFatalShot_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpFatalShot_0',
    },
  },
  'AssistFollowUpFatalShot_0:dazeBuildup': {
    sheet: 'Billy',
    name: 'AssistFollowUpFatalShot_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpFatalShot_0',
    },
  },
  'AssistFollowUpFatalShot_0:anomBuildup': {
    sheet: 'Billy',
    name: 'AssistFollowUpFatalShot_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpFatalShot_0',
    },
  },
} as const
