// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Billy',
    name: 'standardDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'standardDmgBase',
      sheet: 'Billy',
      attribute: 'physical',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Billy',
    name: 'anomalyDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_physical: {
    sheet: 'Billy',
    name: 'disorderDmgInst_physical',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'disorder',
      name: 'disorderDmgInst_physical',
    },
  },
  vortexDmgInst_physical: {
    sheet: 'Billy',
    name: 'vortexDmgInst_physical',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'vortex',
      name: 'vortexDmgInst_physical',
    },
  },
  abloomDmgInst: {
    sheet: 'Billy',
    name: 'abloomDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Billy',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Billy',
      attribute: 'physical',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Billy',
    name: 'dazeInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'dazeBuildupBase',
      sheet: 'Billy',
      attribute: 'physical',
      name: 'dazeInst',
    },
  },
  BasicAttackFullFirepower_0: {
    sheet: 'Billy',
    name: 'BasicAttackFullFirepower_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFullFirepower_0',
    },
  },
  BasicAttackFullFirepower_1: {
    sheet: 'Billy',
    name: 'BasicAttackFullFirepower_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFullFirepower_1',
    },
  },
  BasicAttackFullFirepower_2: {
    sheet: 'Billy',
    name: 'BasicAttackFullFirepower_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Billy',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackFullFirepower_2',
    },
  },
  BasicAttackFullFirepower_3: {
    sheet: 'Billy',
    name: 'BasicAttackFullFirepower_3',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Billy',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackFullFirepower_3',
    },
  },
  BasicAttackFullFirepower_4: {
    sheet: 'Billy',
    name: 'BasicAttackFullFirepower_4',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFullFirepower_4',
    },
  },
  DashAttackStarlightSanction_0: {
    sheet: 'Billy',
    name: 'DashAttackStarlightSanction_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackStarlightSanction_0',
    },
  },
  DashAttackStarlightSanction_1: {
    sheet: 'Billy',
    name: 'DashAttackStarlightSanction_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackStarlightSanction_1',
    },
  },
  DodgeCounterFairFight_0: {
    sheet: 'Billy',
    name: 'DodgeCounterFairFight_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterFairFight_0',
    },
  },
  SpecialAttackStandStill_0: {
    sheet: 'Billy',
    name: 'SpecialAttackStandStill_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackStandStill_0',
    },
  },
  SpecialAttackStandStill_1: {
    sheet: 'Billy',
    name: 'SpecialAttackStandStill_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackStandStill_1',
    },
  },
  SpecialAttackStandStill_2: {
    sheet: 'Billy',
    name: 'SpecialAttackStandStill_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackStandStill_2',
    },
  },
  EXSpecialAttackClearanceTime_0: {
    sheet: 'Billy',
    name: 'EXSpecialAttackClearanceTime_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackClearanceTime_0',
    },
  },
  ChainAttackStarlightMirage_0: {
    sheet: 'Billy',
    name: 'ChainAttackStarlightMirage_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackStarlightMirage_0',
    },
  },
  UltimateStarlightShineBright_0: {
    sheet: 'Billy',
    name: 'UltimateStarlightShineBright_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateStarlightShineBright_0',
    },
  },
  QuickAssistPowerOfTeamwork_0: {
    sheet: 'Billy',
    name: 'QuickAssistPowerOfTeamwork_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistPowerOfTeamwork_0',
    },
  },
  AssistFollowUpFatalShot_0: {
    sheet: 'Billy',
    name: 'AssistFollowUpFatalShot_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Billy',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpFatalShot_0',
    },
  },
} as const
