// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Lycaon',
    name: 'standardDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lycaon',
      attribute: 'ice',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Lycaon',
    name: 'anomalyDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_ice: {
    sheet: 'Lycaon',
    name: 'disorderDmgInst_ice',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'disorder',
      name: 'disorderDmgInst_ice',
    },
  },
  vortexDmgInst_ice: {
    sheet: 'Lycaon',
    name: 'vortexDmgInst_ice',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'vortex',
      name: 'vortexDmgInst_ice',
    },
  },
  abloomDmgInst: {
    sheet: 'Lycaon',
    name: 'abloomDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Lycaon',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lycaon',
      attribute: 'ice',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Lycaon',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lycaon',
      attribute: 'ice',
      name: 'dazeInst',
    },
  },
  'BasicAttackMoonHunter_0:standardDmg': {
    sheet: 'Lycaon',
    name: 'BasicAttackMoonHunter_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lycaon',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackMoonHunter_0',
    },
  },
  'BasicAttackMoonHunter_0:dazeBuildup': {
    sheet: 'Lycaon',
    name: 'BasicAttackMoonHunter_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lycaon',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackMoonHunter_0',
    },
  },
  'BasicAttackMoonHunter_0:anomBuildup': {
    sheet: 'Lycaon',
    name: 'BasicAttackMoonHunter_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lycaon',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackMoonHunter_0',
    },
  },
  'BasicAttackMoonHunter_1:standardDmg': {
    sheet: 'Lycaon',
    name: 'BasicAttackMoonHunter_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackMoonHunter_1',
    },
  },
  'BasicAttackMoonHunter_1:dazeBuildup': {
    sheet: 'Lycaon',
    name: 'BasicAttackMoonHunter_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackMoonHunter_1',
    },
  },
  'BasicAttackMoonHunter_1:anomBuildup': {
    sheet: 'Lycaon',
    name: 'BasicAttackMoonHunter_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackMoonHunter_1',
    },
  },
  'BasicAttackMoonHunter_2:standardDmg': {
    sheet: 'Lycaon',
    name: 'BasicAttackMoonHunter_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lycaon',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackMoonHunter_2',
    },
  },
  'BasicAttackMoonHunter_2:dazeBuildup': {
    sheet: 'Lycaon',
    name: 'BasicAttackMoonHunter_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lycaon',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackMoonHunter_2',
    },
  },
  'BasicAttackMoonHunter_2:anomBuildup': {
    sheet: 'Lycaon',
    name: 'BasicAttackMoonHunter_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lycaon',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackMoonHunter_2',
    },
  },
  'BasicAttackMoonHunter_3:standardDmg': {
    sheet: 'Lycaon',
    name: 'BasicAttackMoonHunter_3:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackMoonHunter_3',
    },
  },
  'BasicAttackMoonHunter_3:dazeBuildup': {
    sheet: 'Lycaon',
    name: 'BasicAttackMoonHunter_3:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackMoonHunter_3',
    },
  },
  'BasicAttackMoonHunter_3:anomBuildup': {
    sheet: 'Lycaon',
    name: 'BasicAttackMoonHunter_3:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackMoonHunter_3',
    },
  },
  'BasicAttackMoonHunter_4:standardDmg': {
    sheet: 'Lycaon',
    name: 'BasicAttackMoonHunter_4:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lycaon',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackMoonHunter_4',
    },
  },
  'BasicAttackMoonHunter_4:dazeBuildup': {
    sheet: 'Lycaon',
    name: 'BasicAttackMoonHunter_4:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lycaon',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackMoonHunter_4',
    },
  },
  'BasicAttackMoonHunter_4:anomBuildup': {
    sheet: 'Lycaon',
    name: 'BasicAttackMoonHunter_4:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lycaon',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackMoonHunter_4',
    },
  },
  'BasicAttackMoonHunter_5:standardDmg': {
    sheet: 'Lycaon',
    name: 'BasicAttackMoonHunter_5:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackMoonHunter_5',
    },
  },
  'BasicAttackMoonHunter_5:dazeBuildup': {
    sheet: 'Lycaon',
    name: 'BasicAttackMoonHunter_5:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackMoonHunter_5',
    },
  },
  'BasicAttackMoonHunter_5:anomBuildup': {
    sheet: 'Lycaon',
    name: 'BasicAttackMoonHunter_5:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackMoonHunter_5',
    },
  },
  'BasicAttackMoonHunter_6:standardDmg': {
    sheet: 'Lycaon',
    name: 'BasicAttackMoonHunter_6:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lycaon',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackMoonHunter_6',
    },
  },
  'BasicAttackMoonHunter_6:dazeBuildup': {
    sheet: 'Lycaon',
    name: 'BasicAttackMoonHunter_6:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lycaon',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackMoonHunter_6',
    },
  },
  'BasicAttackMoonHunter_6:anomBuildup': {
    sheet: 'Lycaon',
    name: 'BasicAttackMoonHunter_6:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lycaon',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackMoonHunter_6',
    },
  },
  'BasicAttackMoonHunter_7:standardDmg': {
    sheet: 'Lycaon',
    name: 'BasicAttackMoonHunter_7:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackMoonHunter_7',
    },
  },
  'BasicAttackMoonHunter_7:dazeBuildup': {
    sheet: 'Lycaon',
    name: 'BasicAttackMoonHunter_7:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackMoonHunter_7',
    },
  },
  'BasicAttackMoonHunter_7:anomBuildup': {
    sheet: 'Lycaon',
    name: 'BasicAttackMoonHunter_7:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackMoonHunter_7',
    },
  },
  'BasicAttackMoonHunter_8:standardDmg': {
    sheet: 'Lycaon',
    name: 'BasicAttackMoonHunter_8:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lycaon',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackMoonHunter_8',
    },
  },
  'BasicAttackMoonHunter_8:dazeBuildup': {
    sheet: 'Lycaon',
    name: 'BasicAttackMoonHunter_8:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lycaon',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackMoonHunter_8',
    },
  },
  'BasicAttackMoonHunter_8:anomBuildup': {
    sheet: 'Lycaon',
    name: 'BasicAttackMoonHunter_8:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lycaon',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackMoonHunter_8',
    },
  },
  'BasicAttackMoonHunter_9:standardDmg': {
    sheet: 'Lycaon',
    name: 'BasicAttackMoonHunter_9:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackMoonHunter_9',
    },
  },
  'BasicAttackMoonHunter_9:dazeBuildup': {
    sheet: 'Lycaon',
    name: 'BasicAttackMoonHunter_9:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackMoonHunter_9',
    },
  },
  'BasicAttackMoonHunter_9:anomBuildup': {
    sheet: 'Lycaon',
    name: 'BasicAttackMoonHunter_9:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackMoonHunter_9',
    },
  },
  'BasicAttackMoonHunter_10:standardDmg': {
    sheet: 'Lycaon',
    name: 'BasicAttackMoonHunter_10:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackMoonHunter_10',
    },
  },
  'BasicAttackMoonHunter_10:dazeBuildup': {
    sheet: 'Lycaon',
    name: 'BasicAttackMoonHunter_10:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackMoonHunter_10',
    },
  },
  'BasicAttackMoonHunter_10:anomBuildup': {
    sheet: 'Lycaon',
    name: 'BasicAttackMoonHunter_10:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackMoonHunter_10',
    },
  },
  'DashAttackKeepItClean_0:standardDmg': {
    sheet: 'Lycaon',
    name: 'DashAttackKeepItClean_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lycaon',
      damageType1: 'dash',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttackKeepItClean_0',
    },
  },
  'DashAttackKeepItClean_0:dazeBuildup': {
    sheet: 'Lycaon',
    name: 'DashAttackKeepItClean_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lycaon',
      damageType1: 'dash',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttackKeepItClean_0',
    },
  },
  'DashAttackKeepItClean_0:anomBuildup': {
    sheet: 'Lycaon',
    name: 'DashAttackKeepItClean_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lycaon',
      damageType1: 'dash',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttackKeepItClean_0',
    },
  },
  'DodgeCounterEtiquetteManual_0:standardDmg': {
    sheet: 'Lycaon',
    name: 'DodgeCounterEtiquetteManual_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterEtiquetteManual_0',
    },
  },
  'DodgeCounterEtiquetteManual_0:dazeBuildup': {
    sheet: 'Lycaon',
    name: 'DodgeCounterEtiquetteManual_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterEtiquetteManual_0',
    },
  },
  'DodgeCounterEtiquetteManual_0:anomBuildup': {
    sheet: 'Lycaon',
    name: 'DodgeCounterEtiquetteManual_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterEtiquetteManual_0',
    },
  },
  'SpecialAttackTimeToHunt_0:standardDmg': {
    sheet: 'Lycaon',
    name: 'SpecialAttackTimeToHunt_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackTimeToHunt_0',
    },
  },
  'SpecialAttackTimeToHunt_0:dazeBuildup': {
    sheet: 'Lycaon',
    name: 'SpecialAttackTimeToHunt_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackTimeToHunt_0',
    },
  },
  'SpecialAttackTimeToHunt_0:anomBuildup': {
    sheet: 'Lycaon',
    name: 'SpecialAttackTimeToHunt_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackTimeToHunt_0',
    },
  },
  'SpecialAttackTimeToHunt_1:standardDmg': {
    sheet: 'Lycaon',
    name: 'SpecialAttackTimeToHunt_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackTimeToHunt_1',
    },
  },
  'SpecialAttackTimeToHunt_1:dazeBuildup': {
    sheet: 'Lycaon',
    name: 'SpecialAttackTimeToHunt_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackTimeToHunt_1',
    },
  },
  'SpecialAttackTimeToHunt_1:anomBuildup': {
    sheet: 'Lycaon',
    name: 'SpecialAttackTimeToHunt_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackTimeToHunt_1',
    },
  },
  'SpecialAttackTimeToHunt_2:standardDmg': {
    sheet: 'Lycaon',
    name: 'SpecialAttackTimeToHunt_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackTimeToHunt_2',
    },
  },
  'SpecialAttackTimeToHunt_2:dazeBuildup': {
    sheet: 'Lycaon',
    name: 'SpecialAttackTimeToHunt_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackTimeToHunt_2',
    },
  },
  'SpecialAttackTimeToHunt_2:anomBuildup': {
    sheet: 'Lycaon',
    name: 'SpecialAttackTimeToHunt_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackTimeToHunt_2',
    },
  },
  'EXSpecialAttackThrillOfTheHunt_0:standardDmg': {
    sheet: 'Lycaon',
    name: 'EXSpecialAttackThrillOfTheHunt_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackThrillOfTheHunt_0',
    },
  },
  'EXSpecialAttackThrillOfTheHunt_0:dazeBuildup': {
    sheet: 'Lycaon',
    name: 'EXSpecialAttackThrillOfTheHunt_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackThrillOfTheHunt_0',
    },
  },
  'EXSpecialAttackThrillOfTheHunt_0:anomBuildup': {
    sheet: 'Lycaon',
    name: 'EXSpecialAttackThrillOfTheHunt_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackThrillOfTheHunt_0',
    },
  },
  'EXSpecialAttackThrillOfTheHunt_1:standardDmg': {
    sheet: 'Lycaon',
    name: 'EXSpecialAttackThrillOfTheHunt_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackThrillOfTheHunt_1',
    },
  },
  'EXSpecialAttackThrillOfTheHunt_1:dazeBuildup': {
    sheet: 'Lycaon',
    name: 'EXSpecialAttackThrillOfTheHunt_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackThrillOfTheHunt_1',
    },
  },
  'EXSpecialAttackThrillOfTheHunt_1:anomBuildup': {
    sheet: 'Lycaon',
    name: 'EXSpecialAttackThrillOfTheHunt_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackThrillOfTheHunt_1',
    },
  },
  'EXSpecialAttackThrillOfTheHunt_2:standardDmg': {
    sheet: 'Lycaon',
    name: 'EXSpecialAttackThrillOfTheHunt_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackThrillOfTheHunt_2',
    },
  },
  'EXSpecialAttackThrillOfTheHunt_2:dazeBuildup': {
    sheet: 'Lycaon',
    name: 'EXSpecialAttackThrillOfTheHunt_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackThrillOfTheHunt_2',
    },
  },
  'EXSpecialAttackThrillOfTheHunt_2:anomBuildup': {
    sheet: 'Lycaon',
    name: 'EXSpecialAttackThrillOfTheHunt_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackThrillOfTheHunt_2',
    },
  },
  'ChainAttackAsYouWish_0:standardDmg': {
    sheet: 'Lycaon',
    name: 'ChainAttackAsYouWish_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackAsYouWish_0',
    },
  },
  'ChainAttackAsYouWish_0:dazeBuildup': {
    sheet: 'Lycaon',
    name: 'ChainAttackAsYouWish_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackAsYouWish_0',
    },
  },
  'ChainAttackAsYouWish_0:anomBuildup': {
    sheet: 'Lycaon',
    name: 'ChainAttackAsYouWish_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackAsYouWish_0',
    },
  },
  'UltimateMissionComplete_0:standardDmg': {
    sheet: 'Lycaon',
    name: 'UltimateMissionComplete_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateMissionComplete_0',
    },
  },
  'UltimateMissionComplete_0:dazeBuildup': {
    sheet: 'Lycaon',
    name: 'UltimateMissionComplete_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateMissionComplete_0',
    },
  },
  'UltimateMissionComplete_0:anomBuildup': {
    sheet: 'Lycaon',
    name: 'UltimateMissionComplete_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateMissionComplete_0',
    },
  },
  'QuickAssistWolfPack_0:standardDmg': {
    sheet: 'Lycaon',
    name: 'QuickAssistWolfPack_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistWolfPack_0',
    },
  },
  'QuickAssistWolfPack_0:dazeBuildup': {
    sheet: 'Lycaon',
    name: 'QuickAssistWolfPack_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistWolfPack_0',
    },
  },
  'QuickAssistWolfPack_0:anomBuildup': {
    sheet: 'Lycaon',
    name: 'QuickAssistWolfPack_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistWolfPack_0',
    },
  },
  'DefensiveAssistDisruptedHunt_0:standardDmg': {
    sheet: 'Lycaon',
    name: 'DefensiveAssistDisruptedHunt_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistDisruptedHunt_0',
    },
  },
  'DefensiveAssistDisruptedHunt_0:dazeBuildup': {
    sheet: 'Lycaon',
    name: 'DefensiveAssistDisruptedHunt_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistDisruptedHunt_0',
    },
  },
  'DefensiveAssistDisruptedHunt_0:anomBuildup': {
    sheet: 'Lycaon',
    name: 'DefensiveAssistDisruptedHunt_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistDisruptedHunt_0',
    },
  },
  'DefensiveAssistDisruptedHunt_1:standardDmg': {
    sheet: 'Lycaon',
    name: 'DefensiveAssistDisruptedHunt_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistDisruptedHunt_1',
    },
  },
  'DefensiveAssistDisruptedHunt_1:dazeBuildup': {
    sheet: 'Lycaon',
    name: 'DefensiveAssistDisruptedHunt_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistDisruptedHunt_1',
    },
  },
  'DefensiveAssistDisruptedHunt_1:anomBuildup': {
    sheet: 'Lycaon',
    name: 'DefensiveAssistDisruptedHunt_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistDisruptedHunt_1',
    },
  },
  'DefensiveAssistDisruptedHunt_2:standardDmg': {
    sheet: 'Lycaon',
    name: 'DefensiveAssistDisruptedHunt_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistDisruptedHunt_2',
    },
  },
  'DefensiveAssistDisruptedHunt_2:dazeBuildup': {
    sheet: 'Lycaon',
    name: 'DefensiveAssistDisruptedHunt_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistDisruptedHunt_2',
    },
  },
  'DefensiveAssistDisruptedHunt_2:anomBuildup': {
    sheet: 'Lycaon',
    name: 'DefensiveAssistDisruptedHunt_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistDisruptedHunt_2',
    },
  },
  'AssistFollowUpVengefulCounterattack_0:standardDmg': {
    sheet: 'Lycaon',
    name: 'AssistFollowUpVengefulCounterattack_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpVengefulCounterattack_0',
    },
  },
  'AssistFollowUpVengefulCounterattack_0:dazeBuildup': {
    sheet: 'Lycaon',
    name: 'AssistFollowUpVengefulCounterattack_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpVengefulCounterattack_0',
    },
  },
  'AssistFollowUpVengefulCounterattack_0:anomBuildup': {
    sheet: 'Lycaon',
    name: 'AssistFollowUpVengefulCounterattack_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpVengefulCounterattack_0',
    },
  },
  'AssistFollowUpVengefulCounterattackGlacialWaltz_0:standardDmg': {
    sheet: 'Lycaon',
    name: 'AssistFollowUpVengefulCounterattackGlacialWaltz_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpVengefulCounterattackGlacialWaltz_0',
    },
  },
  'AssistFollowUpVengefulCounterattackGlacialWaltz_0:dazeBuildup': {
    sheet: 'Lycaon',
    name: 'AssistFollowUpVengefulCounterattackGlacialWaltz_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpVengefulCounterattackGlacialWaltz_0',
    },
  },
  'AssistFollowUpVengefulCounterattackGlacialWaltz_0:anomBuildup': {
    sheet: 'Lycaon',
    name: 'AssistFollowUpVengefulCounterattackGlacialWaltz_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lycaon',
      attribute: 'ice',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpVengefulCounterattackGlacialWaltz_0',
    },
  },
  m4_shield: {
    sheet: 'Lycaon',
    name: 'm4_shield',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'shield',
      sheet: 'Lycaon',
      name: 'm4_shield',
    },
  },
} as const
