// WARNING: Generated file, do not modify
export const formulas = {
  sheerDmgInst: {
    sheet: 'StarlightBilly',
    name: 'sheerDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'sheerDmgBase',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'sheer',
      name: 'sheerDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'StarlightBilly',
    name: 'anomalyDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_physical: {
    sheet: 'StarlightBilly',
    name: 'disorderDmgInst_physical',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'disorder',
      name: 'disorderDmgInst_physical',
    },
  },
  vortexDmgInst_physical: {
    sheet: 'StarlightBilly',
    name: 'vortexDmgInst_physical',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'vortex',
      name: 'vortexDmgInst_physical',
    },
  },
  abloomDmgInst: {
    sheet: 'StarlightBilly',
    name: 'abloomDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'StarlightBilly',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'StarlightBilly',
    name: 'dazeInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'dazeBuildupBase',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      name: 'dazeInst',
    },
  },
  BasicAttackKnightsTechnique_0: {
    sheet: 'StarlightBilly',
    name: 'BasicAttackKnightsTechnique_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackKnightsTechnique_0',
    },
  },
  BasicAttackKnightsTechnique_1: {
    sheet: 'StarlightBilly',
    name: 'BasicAttackKnightsTechnique_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackKnightsTechnique_1',
    },
  },
  BasicAttackKnightsTechnique_2: {
    sheet: 'StarlightBilly',
    name: 'BasicAttackKnightsTechnique_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackKnightsTechnique_2',
    },
  },
  BasicAttackKnightsTechnique_3: {
    sheet: 'StarlightBilly',
    name: 'BasicAttackKnightsTechnique_3',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackKnightsTechnique_3',
    },
  },
  BasicAttackFullThrottleStarlight_0: {
    sheet: 'StarlightBilly',
    name: 'BasicAttackFullThrottleStarlight_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFullThrottleStarlight_0',
    },
  },
  DashAttackStarlightRetribution_0: {
    sheet: 'StarlightBilly',
    name: 'DashAttackStarlightRetribution_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackStarlightRetribution_0',
    },
  },
  DodgeCounterDuelKing_0: {
    sheet: 'StarlightBilly',
    name: 'DodgeCounterDuelKing_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterDuelKing_0',
    },
  },
  DodgeCounterAfterfireSpin_0: {
    sheet: 'StarlightBilly',
    name: 'DodgeCounterAfterfireSpin_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterAfterfireSpin_0',
    },
  },
  SpecialAttackDriveSuppression_0: {
    sheet: 'StarlightBilly',
    name: 'SpecialAttackDriveSuppression_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackDriveSuppression_0',
    },
  },
  SpecialAttackRunWild_0: {
    sheet: 'StarlightBilly',
    name: 'SpecialAttackRunWild_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackRunWild_0',
    },
  },
  EXSpecialAttackCoolWheelie_0: {
    sheet: 'StarlightBilly',
    name: 'EXSpecialAttackCoolWheelie_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackCoolWheelie_0',
    },
  },
  EXSpecialAttackHighTractionWheels_0: {
    sheet: 'StarlightBilly',
    name: 'EXSpecialAttackHighTractionWheels_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackHighTractionWheels_0',
    },
  },
  EXSpecialAttackRockingFootwork_0: {
    sheet: 'StarlightBilly',
    name: 'EXSpecialAttackRockingFootwork_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackRockingFootwork_0',
    },
  },
  ChainAttackKnightsSwagger_0: {
    sheet: 'StarlightBilly',
    name: 'ChainAttackKnightsSwagger_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackKnightsSwagger_0',
    },
  },
  UltimateStarlightKnightFlyingKick_0: {
    sheet: 'StarlightBilly',
    name: 'UltimateStarlightKnightFlyingKick_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateStarlightKnightFlyingKick_0',
    },
  },
  QuickAssistStarlightPowerOfBonds_0: {
    sheet: 'StarlightBilly',
    name: 'QuickAssistStarlightPowerOfBonds_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistStarlightPowerOfBonds_0',
    },
  },
  DefensiveAssistHerosEntrance_0: {
    sheet: 'StarlightBilly',
    name: 'DefensiveAssistHerosEntrance_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistHerosEntrance_0',
    },
  },
  DefensiveAssistHerosEntrance_1: {
    sheet: 'StarlightBilly',
    name: 'DefensiveAssistHerosEntrance_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistHerosEntrance_1',
    },
  },
  DefensiveAssistHerosEntrance_2: {
    sheet: 'StarlightBilly',
    name: 'DefensiveAssistHerosEntrance_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistHerosEntrance_2',
    },
  },
  AssistFollowUpVillainsExit_0: {
    sheet: 'StarlightBilly',
    name: 'AssistFollowUpVillainsExit_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpVillainsExit_0',
    },
  },
} as const
