// WARNING: Generated file, do not modify
export const formulas = {
  sheerDmgInst: {
    sheet: 'StarlightBilly',
    name: 'sheerDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'sheer',
      name: 'sheerDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'StarlightBilly',
    name: 'anomalyDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_physical: {
    sheet: 'StarlightBilly',
    name: 'disorderDmgInst_physical',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'disorder',
      name: 'disorderDmgInst_physical',
    },
  },
  vortexDmgInst_physical: {
    sheet: 'StarlightBilly',
    name: 'vortexDmgInst_physical',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'vortex',
      name: 'vortexDmgInst_physical',
    },
  },
  abloomDmgInst: {
    sheet: 'StarlightBilly',
    name: 'abloomDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'StarlightBilly',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'StarlightBilly',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      name: 'dazeInst',
    },
  },
  'BasicAttackKnightsTechnique_0:sheerDmg': {
    sheet: 'StarlightBilly',
    name: 'BasicAttackKnightsTechnique_0:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackKnightsTechnique_0',
    },
  },
  'BasicAttackKnightsTechnique_0:dazeBuildup': {
    sheet: 'StarlightBilly',
    name: 'BasicAttackKnightsTechnique_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackKnightsTechnique_0',
    },
  },
  'BasicAttackKnightsTechnique_0:anomBuildup': {
    sheet: 'StarlightBilly',
    name: 'BasicAttackKnightsTechnique_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackKnightsTechnique_0',
    },
  },
  'BasicAttackKnightsTechnique_1:sheerDmg': {
    sheet: 'StarlightBilly',
    name: 'BasicAttackKnightsTechnique_1:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackKnightsTechnique_1',
    },
  },
  'BasicAttackKnightsTechnique_1:dazeBuildup': {
    sheet: 'StarlightBilly',
    name: 'BasicAttackKnightsTechnique_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackKnightsTechnique_1',
    },
  },
  'BasicAttackKnightsTechnique_1:anomBuildup': {
    sheet: 'StarlightBilly',
    name: 'BasicAttackKnightsTechnique_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackKnightsTechnique_1',
    },
  },
  'BasicAttackKnightsTechnique_2:sheerDmg': {
    sheet: 'StarlightBilly',
    name: 'BasicAttackKnightsTechnique_2:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackKnightsTechnique_2',
    },
  },
  'BasicAttackKnightsTechnique_2:dazeBuildup': {
    sheet: 'StarlightBilly',
    name: 'BasicAttackKnightsTechnique_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackKnightsTechnique_2',
    },
  },
  'BasicAttackKnightsTechnique_2:anomBuildup': {
    sheet: 'StarlightBilly',
    name: 'BasicAttackKnightsTechnique_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackKnightsTechnique_2',
    },
  },
  'BasicAttackKnightsTechnique_3:sheerDmg': {
    sheet: 'StarlightBilly',
    name: 'BasicAttackKnightsTechnique_3:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackKnightsTechnique_3',
    },
  },
  'BasicAttackKnightsTechnique_3:dazeBuildup': {
    sheet: 'StarlightBilly',
    name: 'BasicAttackKnightsTechnique_3:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackKnightsTechnique_3',
    },
  },
  'BasicAttackKnightsTechnique_3:anomBuildup': {
    sheet: 'StarlightBilly',
    name: 'BasicAttackKnightsTechnique_3:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackKnightsTechnique_3',
    },
  },
  'BasicAttackFullThrottleStarlight_0:sheerDmg': {
    sheet: 'StarlightBilly',
    name: 'BasicAttackFullThrottleStarlight_0:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFullThrottleStarlight_0',
    },
  },
  'BasicAttackFullThrottleStarlight_0:dazeBuildup': {
    sheet: 'StarlightBilly',
    name: 'BasicAttackFullThrottleStarlight_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFullThrottleStarlight_0',
    },
  },
  'BasicAttackFullThrottleStarlight_0:anomBuildup': {
    sheet: 'StarlightBilly',
    name: 'BasicAttackFullThrottleStarlight_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFullThrottleStarlight_0',
    },
  },
  'DashAttackStarlightRetribution_0:sheerDmg': {
    sheet: 'StarlightBilly',
    name: 'DashAttackStarlightRetribution_0:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackStarlightRetribution_0',
    },
  },
  'DashAttackStarlightRetribution_0:dazeBuildup': {
    sheet: 'StarlightBilly',
    name: 'DashAttackStarlightRetribution_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackStarlightRetribution_0',
    },
  },
  'DashAttackStarlightRetribution_0:anomBuildup': {
    sheet: 'StarlightBilly',
    name: 'DashAttackStarlightRetribution_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackStarlightRetribution_0',
    },
  },
  'DodgeCounterDuelKing_0:sheerDmg': {
    sheet: 'StarlightBilly',
    name: 'DodgeCounterDuelKing_0:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterDuelKing_0',
    },
  },
  'DodgeCounterDuelKing_0:dazeBuildup': {
    sheet: 'StarlightBilly',
    name: 'DodgeCounterDuelKing_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterDuelKing_0',
    },
  },
  'DodgeCounterDuelKing_0:anomBuildup': {
    sheet: 'StarlightBilly',
    name: 'DodgeCounterDuelKing_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterDuelKing_0',
    },
  },
  'DodgeCounterAfterfireSpin_0:sheerDmg': {
    sheet: 'StarlightBilly',
    name: 'DodgeCounterAfterfireSpin_0:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterAfterfireSpin_0',
    },
  },
  'DodgeCounterAfterfireSpin_0:dazeBuildup': {
    sheet: 'StarlightBilly',
    name: 'DodgeCounterAfterfireSpin_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterAfterfireSpin_0',
    },
  },
  'DodgeCounterAfterfireSpin_0:anomBuildup': {
    sheet: 'StarlightBilly',
    name: 'DodgeCounterAfterfireSpin_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterAfterfireSpin_0',
    },
  },
  'SpecialAttackDriveSuppression_0:sheerDmg': {
    sheet: 'StarlightBilly',
    name: 'SpecialAttackDriveSuppression_0:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackDriveSuppression_0',
    },
  },
  'SpecialAttackDriveSuppression_0:dazeBuildup': {
    sheet: 'StarlightBilly',
    name: 'SpecialAttackDriveSuppression_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackDriveSuppression_0',
    },
  },
  'SpecialAttackDriveSuppression_0:anomBuildup': {
    sheet: 'StarlightBilly',
    name: 'SpecialAttackDriveSuppression_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackDriveSuppression_0',
    },
  },
  'SpecialAttackRunWild_0:sheerDmg': {
    sheet: 'StarlightBilly',
    name: 'SpecialAttackRunWild_0:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackRunWild_0',
    },
  },
  'SpecialAttackRunWild_0:dazeBuildup': {
    sheet: 'StarlightBilly',
    name: 'SpecialAttackRunWild_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackRunWild_0',
    },
  },
  'SpecialAttackRunWild_0:anomBuildup': {
    sheet: 'StarlightBilly',
    name: 'SpecialAttackRunWild_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackRunWild_0',
    },
  },
  'EXSpecialAttackCoolWheelie_0:sheerDmg': {
    sheet: 'StarlightBilly',
    name: 'EXSpecialAttackCoolWheelie_0:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackCoolWheelie_0',
    },
  },
  'EXSpecialAttackCoolWheelie_0:dazeBuildup': {
    sheet: 'StarlightBilly',
    name: 'EXSpecialAttackCoolWheelie_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackCoolWheelie_0',
    },
  },
  'EXSpecialAttackCoolWheelie_0:anomBuildup': {
    sheet: 'StarlightBilly',
    name: 'EXSpecialAttackCoolWheelie_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackCoolWheelie_0',
    },
  },
  'EXSpecialAttackHighTractionWheels_0:sheerDmg': {
    sheet: 'StarlightBilly',
    name: 'EXSpecialAttackHighTractionWheels_0:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackHighTractionWheels_0',
    },
  },
  'EXSpecialAttackHighTractionWheels_0:dazeBuildup': {
    sheet: 'StarlightBilly',
    name: 'EXSpecialAttackHighTractionWheels_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackHighTractionWheels_0',
    },
  },
  'EXSpecialAttackHighTractionWheels_0:anomBuildup': {
    sheet: 'StarlightBilly',
    name: 'EXSpecialAttackHighTractionWheels_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackHighTractionWheels_0',
    },
  },
  'EXSpecialAttackRockingFootwork_0:sheerDmg': {
    sheet: 'StarlightBilly',
    name: 'EXSpecialAttackRockingFootwork_0:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackRockingFootwork_0',
    },
  },
  'EXSpecialAttackRockingFootwork_0:dazeBuildup': {
    sheet: 'StarlightBilly',
    name: 'EXSpecialAttackRockingFootwork_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackRockingFootwork_0',
    },
  },
  'EXSpecialAttackRockingFootwork_0:anomBuildup': {
    sheet: 'StarlightBilly',
    name: 'EXSpecialAttackRockingFootwork_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackRockingFootwork_0',
    },
  },
  'ChainAttackKnightsSwagger_0:sheerDmg': {
    sheet: 'StarlightBilly',
    name: 'ChainAttackKnightsSwagger_0:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackKnightsSwagger_0',
    },
  },
  'ChainAttackKnightsSwagger_0:dazeBuildup': {
    sheet: 'StarlightBilly',
    name: 'ChainAttackKnightsSwagger_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackKnightsSwagger_0',
    },
  },
  'ChainAttackKnightsSwagger_0:anomBuildup': {
    sheet: 'StarlightBilly',
    name: 'ChainAttackKnightsSwagger_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackKnightsSwagger_0',
    },
  },
  'UltimateStarlightKnightFlyingKick_0:sheerDmg': {
    sheet: 'StarlightBilly',
    name: 'UltimateStarlightKnightFlyingKick_0:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateStarlightKnightFlyingKick_0',
    },
  },
  'UltimateStarlightKnightFlyingKick_0:dazeBuildup': {
    sheet: 'StarlightBilly',
    name: 'UltimateStarlightKnightFlyingKick_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateStarlightKnightFlyingKick_0',
    },
  },
  'UltimateStarlightKnightFlyingKick_0:anomBuildup': {
    sheet: 'StarlightBilly',
    name: 'UltimateStarlightKnightFlyingKick_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateStarlightKnightFlyingKick_0',
    },
  },
  'QuickAssistStarlightPowerOfBonds_0:sheerDmg': {
    sheet: 'StarlightBilly',
    name: 'QuickAssistStarlightPowerOfBonds_0:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistStarlightPowerOfBonds_0',
    },
  },
  'QuickAssistStarlightPowerOfBonds_0:dazeBuildup': {
    sheet: 'StarlightBilly',
    name: 'QuickAssistStarlightPowerOfBonds_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistStarlightPowerOfBonds_0',
    },
  },
  'QuickAssistStarlightPowerOfBonds_0:anomBuildup': {
    sheet: 'StarlightBilly',
    name: 'QuickAssistStarlightPowerOfBonds_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistStarlightPowerOfBonds_0',
    },
  },
  'DefensiveAssistHerosEntrance_0:sheerDmg': {
    sheet: 'StarlightBilly',
    name: 'DefensiveAssistHerosEntrance_0:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistHerosEntrance_0',
    },
  },
  'DefensiveAssistHerosEntrance_0:dazeBuildup': {
    sheet: 'StarlightBilly',
    name: 'DefensiveAssistHerosEntrance_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistHerosEntrance_0',
    },
  },
  'DefensiveAssistHerosEntrance_0:anomBuildup': {
    sheet: 'StarlightBilly',
    name: 'DefensiveAssistHerosEntrance_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistHerosEntrance_0',
    },
  },
  'DefensiveAssistHerosEntrance_1:sheerDmg': {
    sheet: 'StarlightBilly',
    name: 'DefensiveAssistHerosEntrance_1:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistHerosEntrance_1',
    },
  },
  'DefensiveAssistHerosEntrance_1:dazeBuildup': {
    sheet: 'StarlightBilly',
    name: 'DefensiveAssistHerosEntrance_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistHerosEntrance_1',
    },
  },
  'DefensiveAssistHerosEntrance_1:anomBuildup': {
    sheet: 'StarlightBilly',
    name: 'DefensiveAssistHerosEntrance_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistHerosEntrance_1',
    },
  },
  'DefensiveAssistHerosEntrance_2:sheerDmg': {
    sheet: 'StarlightBilly',
    name: 'DefensiveAssistHerosEntrance_2:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistHerosEntrance_2',
    },
  },
  'DefensiveAssistHerosEntrance_2:dazeBuildup': {
    sheet: 'StarlightBilly',
    name: 'DefensiveAssistHerosEntrance_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistHerosEntrance_2',
    },
  },
  'DefensiveAssistHerosEntrance_2:anomBuildup': {
    sheet: 'StarlightBilly',
    name: 'DefensiveAssistHerosEntrance_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistHerosEntrance_2',
    },
  },
  'AssistFollowUpVillainsExit_0:sheerDmg': {
    sheet: 'StarlightBilly',
    name: 'AssistFollowUpVillainsExit_0:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpVillainsExit_0',
    },
  },
  'AssistFollowUpVillainsExit_0:dazeBuildup': {
    sheet: 'StarlightBilly',
    name: 'AssistFollowUpVillainsExit_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpVillainsExit_0',
    },
  },
  'AssistFollowUpVillainsExit_0:anomBuildup': {
    sheet: 'StarlightBilly',
    name: 'AssistFollowUpVillainsExit_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'StarlightBilly',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpVillainsExit_0',
    },
  },
} as const
