// WARNING: Generated file, do not modify
export const formulas = {
  sheerDmgInst: {
    sheet: 'Manato',
    name: 'sheerDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'sheerDmgBase',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'sheer',
      name: 'sheerDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Manato',
    name: 'anomalyDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_fire: {
    sheet: 'Manato',
    name: 'disorderDmgInst_fire',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'disorder',
      name: 'disorderDmgInst_fire',
    },
  },
  vortexDmgInst_fire: {
    sheet: 'Manato',
    name: 'vortexDmgInst_fire',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'vortex',
      name: 'vortexDmgInst_fire',
    },
  },
  abloomDmgInst: {
    sheet: 'Manato',
    name: 'abloomDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Manato',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Manato',
      attribute: 'fire',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Manato',
    name: 'dazeInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'dazeBuildupBase',
      sheet: 'Manato',
      attribute: 'fire',
      name: 'dazeInst',
    },
  },
  BasicAttackBlazingWindSlash_0: {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindSlash_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Manato',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindSlash_0',
    },
  },
  BasicAttackBlazingWindSlash_1: {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindSlash_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Manato',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindSlash_1',
    },
  },
  BasicAttackBlazingWindSlash_2: {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindSlash_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Manato',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindSlash_2',
    },
  },
  BasicAttackBlazingWindSlash_3: {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindSlash_3',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindSlash_3',
    },
  },
  BasicAttackBlazingWindSlash_4: {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindSlash_4',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindSlash_4',
    },
  },
  BasicAttackBlazingWindSlash_5: {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindSlash_5',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindSlash_5',
    },
  },
  BasicAttackBlazingWindMistySlash_0: {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindMistySlash_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindMistySlash_0',
    },
  },
  BasicAttackBlazingWindMistySlash_1: {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindMistySlash_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindMistySlash_1',
    },
  },
  BasicAttackBlazingWindMistySlash_2: {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindMistySlash_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindMistySlash_2',
    },
  },
  BasicAttackBlazingWindMistySlash_3: {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindMistySlash_3',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindMistySlash_3',
    },
  },
  DashAttackRadiantBladeZanshin_0: {
    sheet: 'Manato',
    name: 'DashAttackRadiantBladeZanshin_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Manato',
      damageType1: 'dash',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttackRadiantBladeZanshin_0',
    },
  },
  DodgeCounterRadiantBladeBattleSweep_0: {
    sheet: 'Manato',
    name: 'DodgeCounterRadiantBladeBattleSweep_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterRadiantBladeBattleSweep_0',
    },
  },
  SpecialAttackReturnToAshes_0: {
    sheet: 'Manato',
    name: 'SpecialAttackReturnToAshes_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackReturnToAshes_0',
    },
  },
  SpecialAttackReturnToAshes_1: {
    sheet: 'Manato',
    name: 'SpecialAttackReturnToAshes_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackReturnToAshes_1',
    },
  },
  EXSpecialAttackReturnToAshesFall_0: {
    sheet: 'Manato',
    name: 'EXSpecialAttackReturnToAshesFall_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackReturnToAshesFall_0',
    },
  },
  ChainAttackBlazingEruption_0: {
    sheet: 'Manato',
    name: 'ChainAttackBlazingEruption_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackBlazingEruption_0',
    },
  },
  UltimateMusouAratama_0: {
    sheet: 'Manato',
    name: 'UltimateMusouAratama_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateMusouAratama_0',
    },
  },
  QuickAssistLoneShadowRegroup_0: {
    sheet: 'Manato',
    name: 'QuickAssistLoneShadowRegroup_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistLoneShadowRegroup_0',
    },
  },
  DefensiveAssistLoneShadowMountainStand_0: {
    sheet: 'Manato',
    name: 'DefensiveAssistLoneShadowMountainStand_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistLoneShadowMountainStand_0',
    },
  },
  DefensiveAssistLoneShadowMountainStand_1: {
    sheet: 'Manato',
    name: 'DefensiveAssistLoneShadowMountainStand_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistLoneShadowMountainStand_1',
    },
  },
  DefensiveAssistLoneShadowMountainStand_2: {
    sheet: 'Manato',
    name: 'DefensiveAssistLoneShadowMountainStand_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistLoneShadowMountainStand_2',
    },
  },
  DefensiveAssistLoneShadowMountainStand_3: {
    sheet: 'Manato',
    name: 'DefensiveAssistLoneShadowMountainStand_3',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistLoneShadowMountainStand_3',
    },
  },
  AssistFollowUpLoneShadowBreakingFang_0: {
    sheet: 'Manato',
    name: 'AssistFollowUpLoneShadowBreakingFang_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpLoneShadowBreakingFang_0',
    },
  },
  AssistFollowUpLoneShadowBreakingFang_1: {
    sheet: 'Manato',
    name: 'AssistFollowUpLoneShadowBreakingFang_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpLoneShadowBreakingFang_1',
    },
  },
} as const
