// WARNING: Generated file, do not modify
export const formulas = {
  sheerDmgInst: {
    sheet: 'Manato',
    name: 'sheerDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'sheer',
      name: 'sheerDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Manato',
    name: 'anomalyDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_fire: {
    sheet: 'Manato',
    name: 'disorderDmgInst_fire',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'disorder',
      name: 'disorderDmgInst_fire',
    },
  },
  vortexDmgInst_fire: {
    sheet: 'Manato',
    name: 'vortexDmgInst_fire',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'vortex',
      name: 'vortexDmgInst_fire',
    },
  },
  abloomDmgInst: {
    sheet: 'Manato',
    name: 'abloomDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Manato',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Manato',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      name: 'dazeInst',
    },
  },
  'BasicAttackBlazingWindSlash_0:standardDmg': {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindSlash_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Manato',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindSlash_0',
    },
  },
  'BasicAttackBlazingWindSlash_0:dazeBuildup': {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindSlash_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Manato',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindSlash_0',
    },
  },
  'BasicAttackBlazingWindSlash_0:anomBuildup': {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindSlash_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Manato',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindSlash_0',
    },
  },
  'BasicAttackBlazingWindSlash_1:standardDmg': {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindSlash_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Manato',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindSlash_1',
    },
  },
  'BasicAttackBlazingWindSlash_1:dazeBuildup': {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindSlash_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Manato',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindSlash_1',
    },
  },
  'BasicAttackBlazingWindSlash_1:anomBuildup': {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindSlash_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Manato',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindSlash_1',
    },
  },
  'BasicAttackBlazingWindSlash_2:standardDmg': {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindSlash_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Manato',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindSlash_2',
    },
  },
  'BasicAttackBlazingWindSlash_2:dazeBuildup': {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindSlash_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Manato',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindSlash_2',
    },
  },
  'BasicAttackBlazingWindSlash_2:anomBuildup': {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindSlash_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Manato',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindSlash_2',
    },
  },
  'BasicAttackBlazingWindSlash_3:sheerDmg': {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindSlash_3:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindSlash_3',
    },
  },
  'BasicAttackBlazingWindSlash_3:dazeBuildup': {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindSlash_3:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindSlash_3',
    },
  },
  'BasicAttackBlazingWindSlash_3:anomBuildup': {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindSlash_3:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindSlash_3',
    },
  },
  'BasicAttackBlazingWindSlash_4:sheerDmg': {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindSlash_4:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindSlash_4',
    },
  },
  'BasicAttackBlazingWindSlash_4:dazeBuildup': {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindSlash_4:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindSlash_4',
    },
  },
  'BasicAttackBlazingWindSlash_4:anomBuildup': {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindSlash_4:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindSlash_4',
    },
  },
  'BasicAttackBlazingWindSlash_5:sheerDmg': {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindSlash_5:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindSlash_5',
    },
  },
  'BasicAttackBlazingWindSlash_5:dazeBuildup': {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindSlash_5:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindSlash_5',
    },
  },
  'BasicAttackBlazingWindSlash_5:anomBuildup': {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindSlash_5:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindSlash_5',
    },
  },
  'BasicAttackBlazingWindMistySlash_0:sheerDmg': {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindMistySlash_0:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindMistySlash_0',
    },
  },
  'BasicAttackBlazingWindMistySlash_0:dazeBuildup': {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindMistySlash_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindMistySlash_0',
    },
  },
  'BasicAttackBlazingWindMistySlash_0:anomBuildup': {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindMistySlash_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindMistySlash_0',
    },
  },
  'BasicAttackBlazingWindMistySlash_1:sheerDmg': {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindMistySlash_1:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindMistySlash_1',
    },
  },
  'BasicAttackBlazingWindMistySlash_1:dazeBuildup': {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindMistySlash_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindMistySlash_1',
    },
  },
  'BasicAttackBlazingWindMistySlash_1:anomBuildup': {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindMistySlash_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindMistySlash_1',
    },
  },
  'BasicAttackBlazingWindMistySlash_2:sheerDmg': {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindMistySlash_2:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindMistySlash_2',
    },
  },
  'BasicAttackBlazingWindMistySlash_2:dazeBuildup': {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindMistySlash_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindMistySlash_2',
    },
  },
  'BasicAttackBlazingWindMistySlash_2:anomBuildup': {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindMistySlash_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindMistySlash_2',
    },
  },
  'BasicAttackBlazingWindMistySlash_3:sheerDmg': {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindMistySlash_3:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindMistySlash_3',
    },
  },
  'BasicAttackBlazingWindMistySlash_3:dazeBuildup': {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindMistySlash_3:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindMistySlash_3',
    },
  },
  'BasicAttackBlazingWindMistySlash_3:anomBuildup': {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindMistySlash_3:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindMistySlash_3',
    },
  },
  'DashAttackRadiantBladeZanshin_0:standardDmg': {
    sheet: 'Manato',
    name: 'DashAttackRadiantBladeZanshin_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Manato',
      damageType1: 'dash',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttackRadiantBladeZanshin_0',
    },
  },
  'DashAttackRadiantBladeZanshin_0:dazeBuildup': {
    sheet: 'Manato',
    name: 'DashAttackRadiantBladeZanshin_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Manato',
      damageType1: 'dash',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttackRadiantBladeZanshin_0',
    },
  },
  'DashAttackRadiantBladeZanshin_0:anomBuildup': {
    sheet: 'Manato',
    name: 'DashAttackRadiantBladeZanshin_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Manato',
      damageType1: 'dash',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttackRadiantBladeZanshin_0',
    },
  },
  'DodgeCounterRadiantBladeBattleSweep_0:sheerDmg': {
    sheet: 'Manato',
    name: 'DodgeCounterRadiantBladeBattleSweep_0:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterRadiantBladeBattleSweep_0',
    },
  },
  'DodgeCounterRadiantBladeBattleSweep_0:dazeBuildup': {
    sheet: 'Manato',
    name: 'DodgeCounterRadiantBladeBattleSweep_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterRadiantBladeBattleSweep_0',
    },
  },
  'DodgeCounterRadiantBladeBattleSweep_0:anomBuildup': {
    sheet: 'Manato',
    name: 'DodgeCounterRadiantBladeBattleSweep_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterRadiantBladeBattleSweep_0',
    },
  },
  'SpecialAttackReturnToAshes_0:sheerDmg': {
    sheet: 'Manato',
    name: 'SpecialAttackReturnToAshes_0:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackReturnToAshes_0',
    },
  },
  'SpecialAttackReturnToAshes_0:dazeBuildup': {
    sheet: 'Manato',
    name: 'SpecialAttackReturnToAshes_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackReturnToAshes_0',
    },
  },
  'SpecialAttackReturnToAshes_0:anomBuildup': {
    sheet: 'Manato',
    name: 'SpecialAttackReturnToAshes_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackReturnToAshes_0',
    },
  },
  'SpecialAttackReturnToAshes_1:sheerDmg': {
    sheet: 'Manato',
    name: 'SpecialAttackReturnToAshes_1:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackReturnToAshes_1',
    },
  },
  'SpecialAttackReturnToAshes_1:dazeBuildup': {
    sheet: 'Manato',
    name: 'SpecialAttackReturnToAshes_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackReturnToAshes_1',
    },
  },
  'SpecialAttackReturnToAshes_1:anomBuildup': {
    sheet: 'Manato',
    name: 'SpecialAttackReturnToAshes_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackReturnToAshes_1',
    },
  },
  'EXSpecialAttackReturnToAshesFall_0:sheerDmg': {
    sheet: 'Manato',
    name: 'EXSpecialAttackReturnToAshesFall_0:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackReturnToAshesFall_0',
    },
  },
  'EXSpecialAttackReturnToAshesFall_0:dazeBuildup': {
    sheet: 'Manato',
    name: 'EXSpecialAttackReturnToAshesFall_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackReturnToAshesFall_0',
    },
  },
  'EXSpecialAttackReturnToAshesFall_0:anomBuildup': {
    sheet: 'Manato',
    name: 'EXSpecialAttackReturnToAshesFall_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackReturnToAshesFall_0',
    },
  },
  'ChainAttackBlazingEruption_0:sheerDmg': {
    sheet: 'Manato',
    name: 'ChainAttackBlazingEruption_0:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackBlazingEruption_0',
    },
  },
  'ChainAttackBlazingEruption_0:dazeBuildup': {
    sheet: 'Manato',
    name: 'ChainAttackBlazingEruption_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackBlazingEruption_0',
    },
  },
  'ChainAttackBlazingEruption_0:anomBuildup': {
    sheet: 'Manato',
    name: 'ChainAttackBlazingEruption_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackBlazingEruption_0',
    },
  },
  'UltimateMusouAratama_0:sheerDmg': {
    sheet: 'Manato',
    name: 'UltimateMusouAratama_0:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateMusouAratama_0',
    },
  },
  'UltimateMusouAratama_0:dazeBuildup': {
    sheet: 'Manato',
    name: 'UltimateMusouAratama_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateMusouAratama_0',
    },
  },
  'UltimateMusouAratama_0:anomBuildup': {
    sheet: 'Manato',
    name: 'UltimateMusouAratama_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateMusouAratama_0',
    },
  },
  'QuickAssistLoneShadowRegroup_0:sheerDmg': {
    sheet: 'Manato',
    name: 'QuickAssistLoneShadowRegroup_0:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistLoneShadowRegroup_0',
    },
  },
  'QuickAssistLoneShadowRegroup_0:dazeBuildup': {
    sheet: 'Manato',
    name: 'QuickAssistLoneShadowRegroup_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistLoneShadowRegroup_0',
    },
  },
  'QuickAssistLoneShadowRegroup_0:anomBuildup': {
    sheet: 'Manato',
    name: 'QuickAssistLoneShadowRegroup_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistLoneShadowRegroup_0',
    },
  },
  'DefensiveAssistLoneShadowMountainStand_0:sheerDmg': {
    sheet: 'Manato',
    name: 'DefensiveAssistLoneShadowMountainStand_0:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistLoneShadowMountainStand_0',
    },
  },
  'DefensiveAssistLoneShadowMountainStand_0:dazeBuildup': {
    sheet: 'Manato',
    name: 'DefensiveAssistLoneShadowMountainStand_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistLoneShadowMountainStand_0',
    },
  },
  'DefensiveAssistLoneShadowMountainStand_0:anomBuildup': {
    sheet: 'Manato',
    name: 'DefensiveAssistLoneShadowMountainStand_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistLoneShadowMountainStand_0',
    },
  },
  'DefensiveAssistLoneShadowMountainStand_1:sheerDmg': {
    sheet: 'Manato',
    name: 'DefensiveAssistLoneShadowMountainStand_1:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistLoneShadowMountainStand_1',
    },
  },
  'DefensiveAssistLoneShadowMountainStand_1:dazeBuildup': {
    sheet: 'Manato',
    name: 'DefensiveAssistLoneShadowMountainStand_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistLoneShadowMountainStand_1',
    },
  },
  'DefensiveAssistLoneShadowMountainStand_1:anomBuildup': {
    sheet: 'Manato',
    name: 'DefensiveAssistLoneShadowMountainStand_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistLoneShadowMountainStand_1',
    },
  },
  'DefensiveAssistLoneShadowMountainStand_2:sheerDmg': {
    sheet: 'Manato',
    name: 'DefensiveAssistLoneShadowMountainStand_2:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistLoneShadowMountainStand_2',
    },
  },
  'DefensiveAssistLoneShadowMountainStand_2:dazeBuildup': {
    sheet: 'Manato',
    name: 'DefensiveAssistLoneShadowMountainStand_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistLoneShadowMountainStand_2',
    },
  },
  'DefensiveAssistLoneShadowMountainStand_2:anomBuildup': {
    sheet: 'Manato',
    name: 'DefensiveAssistLoneShadowMountainStand_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistLoneShadowMountainStand_2',
    },
  },
  'DefensiveAssistLoneShadowMountainStand_3:sheerDmg': {
    sheet: 'Manato',
    name: 'DefensiveAssistLoneShadowMountainStand_3:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistLoneShadowMountainStand_3',
    },
  },
  'DefensiveAssistLoneShadowMountainStand_3:dazeBuildup': {
    sheet: 'Manato',
    name: 'DefensiveAssistLoneShadowMountainStand_3:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistLoneShadowMountainStand_3',
    },
  },
  'DefensiveAssistLoneShadowMountainStand_3:anomBuildup': {
    sheet: 'Manato',
    name: 'DefensiveAssistLoneShadowMountainStand_3:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistLoneShadowMountainStand_3',
    },
  },
  'AssistFollowUpLoneShadowBreakingFang_0:sheerDmg': {
    sheet: 'Manato',
    name: 'AssistFollowUpLoneShadowBreakingFang_0:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpLoneShadowBreakingFang_0',
    },
  },
  'AssistFollowUpLoneShadowBreakingFang_0:dazeBuildup': {
    sheet: 'Manato',
    name: 'AssistFollowUpLoneShadowBreakingFang_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpLoneShadowBreakingFang_0',
    },
  },
  'AssistFollowUpLoneShadowBreakingFang_0:anomBuildup': {
    sheet: 'Manato',
    name: 'AssistFollowUpLoneShadowBreakingFang_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpLoneShadowBreakingFang_0',
    },
  },
  'AssistFollowUpLoneShadowBreakingFang_1:sheerDmg': {
    sheet: 'Manato',
    name: 'AssistFollowUpLoneShadowBreakingFang_1:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpLoneShadowBreakingFang_1',
    },
  },
  'AssistFollowUpLoneShadowBreakingFang_1:dazeBuildup': {
    sheet: 'Manato',
    name: 'AssistFollowUpLoneShadowBreakingFang_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpLoneShadowBreakingFang_1',
    },
  },
  'AssistFollowUpLoneShadowBreakingFang_1:anomBuildup': {
    sheet: 'Manato',
    name: 'AssistFollowUpLoneShadowBreakingFang_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpLoneShadowBreakingFang_1',
    },
  },
} as const
