// WARNING: Generated file, do not modify
export const formulas = {
  sheerDmgInst: {
    sheet: 'Manato',
    name: 'sheerDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'sheer',
      name: 'sheerDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Manato',
    name: 'anomalyDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_fire: {
    sheet: 'Manato',
    name: 'disorderDmgInst_fire',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'disorder',
      name: 'disorderDmgInst_fire',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Manato',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Manato',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      name: 'dazeInst',
    },
  },
  BasicAttackBlazingWindSlash_0_dmg: {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindSlash_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindSlash_0_dmg',
    },
  },
  BasicAttackBlazingWindSlash_0_daze: {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindSlash_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindSlash_0_daze',
    },
  },
  BasicAttackBlazingWindSlash_0_anomBuildup: {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindSlash_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindSlash_0_anomBuildup',
    },
  },
  BasicAttackBlazingWindSlash_1_dmg: {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindSlash_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindSlash_1_dmg',
    },
  },
  BasicAttackBlazingWindSlash_1_daze: {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindSlash_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindSlash_1_daze',
    },
  },
  BasicAttackBlazingWindSlash_1_anomBuildup: {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindSlash_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindSlash_1_anomBuildup',
    },
  },
  BasicAttackBlazingWindSlash_2_dmg: {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindSlash_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindSlash_2_dmg',
    },
  },
  BasicAttackBlazingWindSlash_2_daze: {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindSlash_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindSlash_2_daze',
    },
  },
  BasicAttackBlazingWindSlash_2_anomBuildup: {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindSlash_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindSlash_2_anomBuildup',
    },
  },
  BasicAttackBlazingWindSlash_3_dmg: {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindSlash_3_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindSlash_3_dmg',
    },
  },
  BasicAttackBlazingWindSlash_3_daze: {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindSlash_3_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindSlash_3_daze',
    },
  },
  BasicAttackBlazingWindSlash_3_anomBuildup: {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindSlash_3_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindSlash_3_anomBuildup',
    },
  },
  BasicAttackBlazingWindSlash_4_dmg: {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindSlash_4_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindSlash_4_dmg',
    },
  },
  BasicAttackBlazingWindSlash_4_daze: {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindSlash_4_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindSlash_4_daze',
    },
  },
  BasicAttackBlazingWindSlash_4_anomBuildup: {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindSlash_4_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindSlash_4_anomBuildup',
    },
  },
  BasicAttackBlazingWindSlash_5_dmg: {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindSlash_5_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindSlash_5_dmg',
    },
  },
  BasicAttackBlazingWindSlash_5_daze: {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindSlash_5_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindSlash_5_daze',
    },
  },
  BasicAttackBlazingWindSlash_5_anomBuildup: {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindSlash_5_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindSlash_5_anomBuildup',
    },
  },
  BasicAttackBlazingWindSlash_6_dmg: {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindSlash_6_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindSlash_6_dmg',
    },
  },
  BasicAttackBlazingWindSlash_6_daze: {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindSlash_6_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindSlash_6_daze',
    },
  },
  BasicAttackBlazingWindSlash_6_anomBuildup: {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindSlash_6_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindSlash_6_anomBuildup',
    },
  },
  BasicAttackBlazingWindSlash_7_dmg: {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindSlash_7_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindSlash_7_dmg',
    },
  },
  BasicAttackBlazingWindSlash_7_daze: {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindSlash_7_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindSlash_7_daze',
    },
  },
  BasicAttackBlazingWindSlash_7_anomBuildup: {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindSlash_7_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindSlash_7_anomBuildup',
    },
  },
  BasicAttackBlazingWindMistySlash_0_dmg: {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindMistySlash_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindMistySlash_0_dmg',
    },
  },
  BasicAttackBlazingWindMistySlash_0_daze: {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindMistySlash_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindMistySlash_0_daze',
    },
  },
  BasicAttackBlazingWindMistySlash_0_anomBuildup: {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindMistySlash_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindMistySlash_0_anomBuildup',
    },
  },
  BasicAttackBlazingWindMistySlash_1_dmg: {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindMistySlash_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindMistySlash_1_dmg',
    },
  },
  BasicAttackBlazingWindMistySlash_1_daze: {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindMistySlash_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindMistySlash_1_daze',
    },
  },
  BasicAttackBlazingWindMistySlash_1_anomBuildup: {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindMistySlash_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindMistySlash_1_anomBuildup',
    },
  },
  BasicAttackBlazingWindMistySlash_2_dmg: {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindMistySlash_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindMistySlash_2_dmg',
    },
  },
  BasicAttackBlazingWindMistySlash_2_daze: {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindMistySlash_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindMistySlash_2_daze',
    },
  },
  BasicAttackBlazingWindMistySlash_2_anomBuildup: {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindMistySlash_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindMistySlash_2_anomBuildup',
    },
  },
  BasicAttackBlazingWindMistySlash_3_dmg: {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindMistySlash_3_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindMistySlash_3_dmg',
    },
  },
  BasicAttackBlazingWindMistySlash_3_daze: {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindMistySlash_3_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindMistySlash_3_daze',
    },
  },
  BasicAttackBlazingWindMistySlash_3_anomBuildup: {
    sheet: 'Manato',
    name: 'BasicAttackBlazingWindMistySlash_3_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBlazingWindMistySlash_3_anomBuildup',
    },
  },
  DashAttackRadiantBladeZanshin_0_dmg: {
    sheet: 'Manato',
    name: 'DashAttackRadiantBladeZanshin_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackRadiantBladeZanshin_0_dmg',
    },
  },
  DashAttackRadiantBladeZanshin_0_daze: {
    sheet: 'Manato',
    name: 'DashAttackRadiantBladeZanshin_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackRadiantBladeZanshin_0_daze',
    },
  },
  DashAttackRadiantBladeZanshin_0_anomBuildup: {
    sheet: 'Manato',
    name: 'DashAttackRadiantBladeZanshin_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackRadiantBladeZanshin_0_anomBuildup',
    },
  },
  DodgeCounterRadiantBladeBattleSweep_0_dmg: {
    sheet: 'Manato',
    name: 'DodgeCounterRadiantBladeBattleSweep_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterRadiantBladeBattleSweep_0_dmg',
    },
  },
  DodgeCounterRadiantBladeBattleSweep_0_daze: {
    sheet: 'Manato',
    name: 'DodgeCounterRadiantBladeBattleSweep_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterRadiantBladeBattleSweep_0_daze',
    },
  },
  DodgeCounterRadiantBladeBattleSweep_0_anomBuildup: {
    sheet: 'Manato',
    name: 'DodgeCounterRadiantBladeBattleSweep_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterRadiantBladeBattleSweep_0_anomBuildup',
    },
  },
  SpecialAttackReturnToAshes_0_dmg: {
    sheet: 'Manato',
    name: 'SpecialAttackReturnToAshes_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackReturnToAshes_0_dmg',
    },
  },
  SpecialAttackReturnToAshes_0_daze: {
    sheet: 'Manato',
    name: 'SpecialAttackReturnToAshes_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackReturnToAshes_0_daze',
    },
  },
  SpecialAttackReturnToAshes_0_anomBuildup: {
    sheet: 'Manato',
    name: 'SpecialAttackReturnToAshes_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackReturnToAshes_0_anomBuildup',
    },
  },
  SpecialAttackReturnToAshes_1_dmg: {
    sheet: 'Manato',
    name: 'SpecialAttackReturnToAshes_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackReturnToAshes_1_dmg',
    },
  },
  SpecialAttackReturnToAshes_1_daze: {
    sheet: 'Manato',
    name: 'SpecialAttackReturnToAshes_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackReturnToAshes_1_daze',
    },
  },
  SpecialAttackReturnToAshes_1_anomBuildup: {
    sheet: 'Manato',
    name: 'SpecialAttackReturnToAshes_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackReturnToAshes_1_anomBuildup',
    },
  },
  EXSpecialAttackReturnToAshesFall_0_dmg: {
    sheet: 'Manato',
    name: 'EXSpecialAttackReturnToAshesFall_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackReturnToAshesFall_0_dmg',
    },
  },
  EXSpecialAttackReturnToAshesFall_0_daze: {
    sheet: 'Manato',
    name: 'EXSpecialAttackReturnToAshesFall_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackReturnToAshesFall_0_daze',
    },
  },
  EXSpecialAttackReturnToAshesFall_0_anomBuildup: {
    sheet: 'Manato',
    name: 'EXSpecialAttackReturnToAshesFall_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackReturnToAshesFall_0_anomBuildup',
    },
  },
  ChainAttackBlazingEruption_0_dmg: {
    sheet: 'Manato',
    name: 'ChainAttackBlazingEruption_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackBlazingEruption_0_dmg',
    },
  },
  ChainAttackBlazingEruption_0_daze: {
    sheet: 'Manato',
    name: 'ChainAttackBlazingEruption_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackBlazingEruption_0_daze',
    },
  },
  ChainAttackBlazingEruption_0_anomBuildup: {
    sheet: 'Manato',
    name: 'ChainAttackBlazingEruption_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackBlazingEruption_0_anomBuildup',
    },
  },
  UltimateMusouAratama_0_dmg: {
    sheet: 'Manato',
    name: 'UltimateMusouAratama_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateMusouAratama_0_dmg',
    },
  },
  UltimateMusouAratama_0_daze: {
    sheet: 'Manato',
    name: 'UltimateMusouAratama_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateMusouAratama_0_daze',
    },
  },
  UltimateMusouAratama_0_anomBuildup: {
    sheet: 'Manato',
    name: 'UltimateMusouAratama_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateMusouAratama_0_anomBuildup',
    },
  },
  QuickAssistLoneShadowRegroup_0_dmg: {
    sheet: 'Manato',
    name: 'QuickAssistLoneShadowRegroup_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistLoneShadowRegroup_0_dmg',
    },
  },
  QuickAssistLoneShadowRegroup_0_daze: {
    sheet: 'Manato',
    name: 'QuickAssistLoneShadowRegroup_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistLoneShadowRegroup_0_daze',
    },
  },
  QuickAssistLoneShadowRegroup_0_anomBuildup: {
    sheet: 'Manato',
    name: 'QuickAssistLoneShadowRegroup_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistLoneShadowRegroup_0_anomBuildup',
    },
  },
  DefensiveAssistLoneShadowMountainStand_0_dmg: {
    sheet: 'Manato',
    name: 'DefensiveAssistLoneShadowMountainStand_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistLoneShadowMountainStand_0_dmg',
    },
  },
  DefensiveAssistLoneShadowMountainStand_0_daze: {
    sheet: 'Manato',
    name: 'DefensiveAssistLoneShadowMountainStand_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistLoneShadowMountainStand_0_daze',
    },
  },
  DefensiveAssistLoneShadowMountainStand_0_anomBuildup: {
    sheet: 'Manato',
    name: 'DefensiveAssistLoneShadowMountainStand_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistLoneShadowMountainStand_0_anomBuildup',
    },
  },
  DefensiveAssistLoneShadowMountainStand_1_dmg: {
    sheet: 'Manato',
    name: 'DefensiveAssistLoneShadowMountainStand_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistLoneShadowMountainStand_1_dmg',
    },
  },
  DefensiveAssistLoneShadowMountainStand_1_daze: {
    sheet: 'Manato',
    name: 'DefensiveAssistLoneShadowMountainStand_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistLoneShadowMountainStand_1_daze',
    },
  },
  DefensiveAssistLoneShadowMountainStand_1_anomBuildup: {
    sheet: 'Manato',
    name: 'DefensiveAssistLoneShadowMountainStand_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistLoneShadowMountainStand_1_anomBuildup',
    },
  },
  DefensiveAssistLoneShadowMountainStand_2_dmg: {
    sheet: 'Manato',
    name: 'DefensiveAssistLoneShadowMountainStand_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistLoneShadowMountainStand_2_dmg',
    },
  },
  DefensiveAssistLoneShadowMountainStand_2_daze: {
    sheet: 'Manato',
    name: 'DefensiveAssistLoneShadowMountainStand_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistLoneShadowMountainStand_2_daze',
    },
  },
  DefensiveAssistLoneShadowMountainStand_2_anomBuildup: {
    sheet: 'Manato',
    name: 'DefensiveAssistLoneShadowMountainStand_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistLoneShadowMountainStand_2_anomBuildup',
    },
  },
  DefensiveAssistLoneShadowMountainStand_3_dmg: {
    sheet: 'Manato',
    name: 'DefensiveAssistLoneShadowMountainStand_3_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistLoneShadowMountainStand_3_dmg',
    },
  },
  DefensiveAssistLoneShadowMountainStand_3_daze: {
    sheet: 'Manato',
    name: 'DefensiveAssistLoneShadowMountainStand_3_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistLoneShadowMountainStand_3_daze',
    },
  },
  DefensiveAssistLoneShadowMountainStand_3_anomBuildup: {
    sheet: 'Manato',
    name: 'DefensiveAssistLoneShadowMountainStand_3_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistLoneShadowMountainStand_3_anomBuildup',
    },
  },
  AssistFollowUpLoneShadowBreakingFang_0_dmg: {
    sheet: 'Manato',
    name: 'AssistFollowUpLoneShadowBreakingFang_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpLoneShadowBreakingFang_0_dmg',
    },
  },
  AssistFollowUpLoneShadowBreakingFang_0_daze: {
    sheet: 'Manato',
    name: 'AssistFollowUpLoneShadowBreakingFang_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpLoneShadowBreakingFang_0_daze',
    },
  },
  AssistFollowUpLoneShadowBreakingFang_0_anomBuildup: {
    sheet: 'Manato',
    name: 'AssistFollowUpLoneShadowBreakingFang_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpLoneShadowBreakingFang_0_anomBuildup',
    },
  },
  AssistFollowUpLoneShadowBreakingFang_1_dmg: {
    sheet: 'Manato',
    name: 'AssistFollowUpLoneShadowBreakingFang_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpLoneShadowBreakingFang_1_dmg',
    },
  },
  AssistFollowUpLoneShadowBreakingFang_1_daze: {
    sheet: 'Manato',
    name: 'AssistFollowUpLoneShadowBreakingFang_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpLoneShadowBreakingFang_1_daze',
    },
  },
  AssistFollowUpLoneShadowBreakingFang_1_anomBuildup: {
    sheet: 'Manato',
    name: 'AssistFollowUpLoneShadowBreakingFang_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Manato',
      attribute: 'fire',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpLoneShadowBreakingFang_1_anomBuildup',
    },
  },
} as const
