type Tag = Record<string, string>

export type IConditionalData =
  | IBoolConditionalData
  | IListConditionalData
  | INumConditionalData
export type IFormulaData = {
  src: string // entity
  name: string // formula name
  tag: Tag // tag used to access value
}

/// Conditional whose values are True (1.0) and False (0.0)
export type IBoolConditionalData = {
  type: 'bool' // type discriminator
  src: string // entity
  name: string // conditional name
  tag: Tag // tag used to access value
}
/// Conditional whose values are those in the list. When inputting the
/// entry, use the (0-based) position in the list
export type IListConditionalData = {
  type: 'list' // type discriminator
  src: string // entity
  name: string // conditional name
  tag: Tag // tag used to access value

  list: [string] // feasible values
}
/// Conditional whose values are regular numbers
export type INumConditionalData = {
  type: 'num' // type discriminator
  src: string // entity
  name: string // conditional name
  tag: Tag // tag used to access value

  int_only: boolean // whether the value must be an integer
  min?: number // smallest feasible value, if applicable
  max?: number // largest feasible value, if applicable
}

export const conditionals = {
  Argenti: {
    boolConditional: {
      src: 'Argenti',
      name: 'boolConditional',
      tag: { src: 'Argenti', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'Argenti',
      name: 'listConditional',
      tag: { src: 'Argenti', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'Argenti',
      name: 'numConditional',
      tag: { src: 'Argenti', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  Arlan: {
    boolConditional: {
      src: 'Arlan',
      name: 'boolConditional',
      tag: { src: 'Arlan', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'Arlan',
      name: 'listConditional',
      tag: { src: 'Arlan', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'Arlan',
      name: 'numConditional',
      tag: { src: 'Arlan', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  Asta: {
    boolConditional: {
      src: 'Asta',
      name: 'boolConditional',
      tag: { src: 'Asta', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'Asta',
      name: 'listConditional',
      tag: { src: 'Asta', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'Asta',
      name: 'numConditional',
      tag: { src: 'Asta', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  Bailu: {
    boolConditional: {
      src: 'Bailu',
      name: 'boolConditional',
      tag: { src: 'Bailu', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'Bailu',
      name: 'listConditional',
      tag: { src: 'Bailu', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'Bailu',
      name: 'numConditional',
      tag: { src: 'Bailu', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  Blade: {
    boolConditional: {
      src: 'Blade',
      name: 'boolConditional',
      tag: { src: 'Blade', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'Blade',
      name: 'listConditional',
      tag: { src: 'Blade', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'Blade',
      name: 'numConditional',
      tag: { src: 'Blade', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  Bronya: {
    boolConditional: {
      src: 'Bronya',
      name: 'boolConditional',
      tag: { src: 'Bronya', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'Bronya',
      name: 'listConditional',
      tag: { src: 'Bronya', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'Bronya',
      name: 'numConditional',
      tag: { src: 'Bronya', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  Clara: {
    boolConditional: {
      src: 'Clara',
      name: 'boolConditional',
      tag: { src: 'Clara', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'Clara',
      name: 'listConditional',
      tag: { src: 'Clara', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'Clara',
      name: 'numConditional',
      tag: { src: 'Clara', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  DanHeng: {
    boolConditional: {
      src: 'DanHeng',
      name: 'boolConditional',
      tag: { src: 'DanHeng', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'DanHeng',
      name: 'listConditional',
      tag: { src: 'DanHeng', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'DanHeng',
      name: 'numConditional',
      tag: { src: 'DanHeng', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  DanHengImbibitorLunae: {
    boolConditional: {
      src: 'DanHengImbibitorLunae',
      name: 'boolConditional',
      tag: { src: 'DanHengImbibitorLunae', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'DanHengImbibitorLunae',
      name: 'listConditional',
      tag: { src: 'DanHengImbibitorLunae', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'DanHengImbibitorLunae',
      name: 'numConditional',
      tag: { src: 'DanHengImbibitorLunae', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  DrRatio: {
    boolConditional: {
      src: 'DrRatio',
      name: 'boolConditional',
      tag: { src: 'DrRatio', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'DrRatio',
      name: 'listConditional',
      tag: { src: 'DrRatio', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'DrRatio',
      name: 'numConditional',
      tag: { src: 'DrRatio', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  FuXuan: {
    boolConditional: {
      src: 'FuXuan',
      name: 'boolConditional',
      tag: { src: 'FuXuan', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'FuXuan',
      name: 'listConditional',
      tag: { src: 'FuXuan', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'FuXuan',
      name: 'numConditional',
      tag: { src: 'FuXuan', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  Gepard: {
    boolConditional: {
      src: 'Gepard',
      name: 'boolConditional',
      tag: { src: 'Gepard', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'Gepard',
      name: 'listConditional',
      tag: { src: 'Gepard', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'Gepard',
      name: 'numConditional',
      tag: { src: 'Gepard', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  Guinaifen: {
    boolConditional: {
      src: 'Guinaifen',
      name: 'boolConditional',
      tag: { src: 'Guinaifen', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'Guinaifen',
      name: 'listConditional',
      tag: { src: 'Guinaifen', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'Guinaifen',
      name: 'numConditional',
      tag: { src: 'Guinaifen', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  Hanya: {
    boolConditional: {
      src: 'Hanya',
      name: 'boolConditional',
      tag: { src: 'Hanya', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'Hanya',
      name: 'listConditional',
      tag: { src: 'Hanya', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'Hanya',
      name: 'numConditional',
      tag: { src: 'Hanya', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  Herta: {
    boolConditional: {
      src: 'Herta',
      name: 'boolConditional',
      tag: { src: 'Herta', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'Herta',
      name: 'listConditional',
      tag: { src: 'Herta', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'Herta',
      name: 'numConditional',
      tag: { src: 'Herta', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  Himeko: {
    boolConditional: {
      src: 'Himeko',
      name: 'boolConditional',
      tag: { src: 'Himeko', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'Himeko',
      name: 'listConditional',
      tag: { src: 'Himeko', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'Himeko',
      name: 'numConditional',
      tag: { src: 'Himeko', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  Hook: {
    boolConditional: {
      src: 'Hook',
      name: 'boolConditional',
      tag: { src: 'Hook', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'Hook',
      name: 'listConditional',
      tag: { src: 'Hook', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'Hook',
      name: 'numConditional',
      tag: { src: 'Hook', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  Huohuo: {
    boolConditional: {
      src: 'Huohuo',
      name: 'boolConditional',
      tag: { src: 'Huohuo', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'Huohuo',
      name: 'listConditional',
      tag: { src: 'Huohuo', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'Huohuo',
      name: 'numConditional',
      tag: { src: 'Huohuo', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  JingYuan: {
    boolConditional: {
      src: 'JingYuan',
      name: 'boolConditional',
      tag: { src: 'JingYuan', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'JingYuan',
      name: 'listConditional',
      tag: { src: 'JingYuan', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'JingYuan',
      name: 'numConditional',
      tag: { src: 'JingYuan', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  Jingliu: {
    boolConditional: {
      src: 'Jingliu',
      name: 'boolConditional',
      tag: { src: 'Jingliu', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'Jingliu',
      name: 'listConditional',
      tag: { src: 'Jingliu', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'Jingliu',
      name: 'numConditional',
      tag: { src: 'Jingliu', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  Kafka: {
    boolConditional: {
      src: 'Kafka',
      name: 'boolConditional',
      tag: { src: 'Kafka', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'Kafka',
      name: 'listConditional',
      tag: { src: 'Kafka', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'Kafka',
      name: 'numConditional',
      tag: { src: 'Kafka', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  Luka: {
    boolConditional: {
      src: 'Luka',
      name: 'boolConditional',
      tag: { src: 'Luka', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'Luka',
      name: 'listConditional',
      tag: { src: 'Luka', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'Luka',
      name: 'numConditional',
      tag: { src: 'Luka', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  Luocha: {
    boolConditional: {
      src: 'Luocha',
      name: 'boolConditional',
      tag: { src: 'Luocha', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'Luocha',
      name: 'listConditional',
      tag: { src: 'Luocha', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'Luocha',
      name: 'numConditional',
      tag: { src: 'Luocha', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  Lynx: {
    boolConditional: {
      src: 'Lynx',
      name: 'boolConditional',
      tag: { src: 'Lynx', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'Lynx',
      name: 'listConditional',
      tag: { src: 'Lynx', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'Lynx',
      name: 'numConditional',
      tag: { src: 'Lynx', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  Natasha: {
    boolConditional: {
      src: 'Natasha',
      name: 'boolConditional',
      tag: { src: 'Natasha', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'Natasha',
      name: 'listConditional',
      tag: { src: 'Natasha', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'Natasha',
      name: 'numConditional',
      tag: { src: 'Natasha', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  Pela: {
    boolConditional: {
      src: 'Pela',
      name: 'boolConditional',
      tag: { src: 'Pela', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'Pela',
      name: 'listConditional',
      tag: { src: 'Pela', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'Pela',
      name: 'numConditional',
      tag: { src: 'Pela', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  Qingque: {
    boolConditional: {
      src: 'Qingque',
      name: 'boolConditional',
      tag: { src: 'Qingque', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'Qingque',
      name: 'listConditional',
      tag: { src: 'Qingque', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'Qingque',
      name: 'numConditional',
      tag: { src: 'Qingque', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  RuanMei: {
    boolConditional: {
      src: 'RuanMei',
      name: 'boolConditional',
      tag: { src: 'RuanMei', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'RuanMei',
      name: 'listConditional',
      tag: { src: 'RuanMei', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'RuanMei',
      name: 'numConditional',
      tag: { src: 'RuanMei', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  Sampo: {
    boolConditional: {
      src: 'Sampo',
      name: 'boolConditional',
      tag: { src: 'Sampo', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'Sampo',
      name: 'listConditional',
      tag: { src: 'Sampo', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'Sampo',
      name: 'numConditional',
      tag: { src: 'Sampo', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  Seele: {
    boolConditional: {
      src: 'Seele',
      name: 'boolConditional',
      tag: { src: 'Seele', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'Seele',
      name: 'listConditional',
      tag: { src: 'Seele', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'Seele',
      name: 'numConditional',
      tag: { src: 'Seele', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  Serval: {
    boolConditional: {
      src: 'Serval',
      name: 'boolConditional',
      tag: { src: 'Serval', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'Serval',
      name: 'listConditional',
      tag: { src: 'Serval', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'Serval',
      name: 'numConditional',
      tag: { src: 'Serval', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  SilverWolf: {
    boolConditional: {
      src: 'SilverWolf',
      name: 'boolConditional',
      tag: { src: 'SilverWolf', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'SilverWolf',
      name: 'listConditional',
      tag: { src: 'SilverWolf', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'SilverWolf',
      name: 'numConditional',
      tag: { src: 'SilverWolf', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  Sushang: {
    boolConditional: {
      src: 'Sushang',
      name: 'boolConditional',
      tag: { src: 'Sushang', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'Sushang',
      name: 'listConditional',
      tag: { src: 'Sushang', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'Sushang',
      name: 'numConditional',
      tag: { src: 'Sushang', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  Tingyun: {
    boolConditional: {
      src: 'Tingyun',
      name: 'boolConditional',
      tag: { src: 'Tingyun', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'Tingyun',
      name: 'listConditional',
      tag: { src: 'Tingyun', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'Tingyun',
      name: 'numConditional',
      tag: { src: 'Tingyun', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  TopazAndNumby: {
    boolConditional: {
      src: 'TopazAndNumby',
      name: 'boolConditional',
      tag: { src: 'TopazAndNumby', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'TopazAndNumby',
      name: 'listConditional',
      tag: { src: 'TopazAndNumby', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'TopazAndNumby',
      name: 'numConditional',
      tag: { src: 'TopazAndNumby', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  Welt: {
    boolConditional: {
      src: 'Welt',
      name: 'boolConditional',
      tag: { src: 'Welt', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'Welt',
      name: 'listConditional',
      tag: { src: 'Welt', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'Welt',
      name: 'numConditional',
      tag: { src: 'Welt', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  Xueyi: {
    boolConditional: {
      src: 'Xueyi',
      name: 'boolConditional',
      tag: { src: 'Xueyi', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'Xueyi',
      name: 'listConditional',
      tag: { src: 'Xueyi', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'Xueyi',
      name: 'numConditional',
      tag: { src: 'Xueyi', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  Yanqing: {
    boolConditional: {
      src: 'Yanqing',
      name: 'boolConditional',
      tag: { src: 'Yanqing', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'Yanqing',
      name: 'listConditional',
      tag: { src: 'Yanqing', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'Yanqing',
      name: 'numConditional',
      tag: { src: 'Yanqing', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  Yukong: {
    boolConditional: {
      src: 'Yukong',
      name: 'boolConditional',
      tag: { src: 'Yukong', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'Yukong',
      name: 'listConditional',
      tag: { src: 'Yukong', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'Yukong',
      name: 'numConditional',
      tag: { src: 'Yukong', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  ASecretVow: {
    boolConditional: {
      src: 'ASecretVow',
      name: 'boolConditional',
      tag: { src: 'ASecretVow', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'ASecretVow',
      name: 'listConditional',
      tag: { src: 'ASecretVow', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'ASecretVow',
      name: 'numConditional',
      tag: { src: 'ASecretVow', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  Adversarial: {
    boolConditional: {
      src: 'Adversarial',
      name: 'boolConditional',
      tag: { src: 'Adversarial', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'Adversarial',
      name: 'listConditional',
      tag: { src: 'Adversarial', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'Adversarial',
      name: 'numConditional',
      tag: { src: 'Adversarial', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  Amber: {
    boolConditional: {
      src: 'Amber',
      name: 'boolConditional',
      tag: { src: 'Amber', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'Amber',
      name: 'listConditional',
      tag: { src: 'Amber', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'Amber',
      name: 'numConditional',
      tag: { src: 'Amber', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  AnInstantBeforeAGaze: {
    boolConditional: {
      src: 'AnInstantBeforeAGaze',
      name: 'boolConditional',
      tag: { src: 'AnInstantBeforeAGaze', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'AnInstantBeforeAGaze',
      name: 'listConditional',
      tag: { src: 'AnInstantBeforeAGaze', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'AnInstantBeforeAGaze',
      name: 'numConditional',
      tag: { src: 'AnInstantBeforeAGaze', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  Arrows: {
    boolConditional: {
      src: 'Arrows',
      name: 'boolConditional',
      tag: { src: 'Arrows', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'Arrows',
      name: 'listConditional',
      tag: { src: 'Arrows', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'Arrows',
      name: 'numConditional',
      tag: { src: 'Arrows', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  BaptismOfPureThought: {
    boolConditional: {
      src: 'BaptismOfPureThought',
      name: 'boolConditional',
      tag: { src: 'BaptismOfPureThought', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'BaptismOfPureThought',
      name: 'listConditional',
      tag: { src: 'BaptismOfPureThought', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'BaptismOfPureThought',
      name: 'numConditional',
      tag: { src: 'BaptismOfPureThought', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  BeforeDawn: {
    boolConditional: {
      src: 'BeforeDawn',
      name: 'boolConditional',
      tag: { src: 'BeforeDawn', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'BeforeDawn',
      name: 'listConditional',
      tag: { src: 'BeforeDawn', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'BeforeDawn',
      name: 'numConditional',
      tag: { src: 'BeforeDawn', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  BeforeTheTutorialMissionStarts: {
    boolConditional: {
      src: 'BeforeTheTutorialMissionStarts',
      name: 'boolConditional',
      tag: { src: 'BeforeTheTutorialMissionStarts', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'BeforeTheTutorialMissionStarts',
      name: 'listConditional',
      tag: { src: 'BeforeTheTutorialMissionStarts', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'BeforeTheTutorialMissionStarts',
      name: 'numConditional',
      tag: { src: 'BeforeTheTutorialMissionStarts', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  BrighterThanTheSun: {
    boolConditional: {
      src: 'BrighterThanTheSun',
      name: 'boolConditional',
      tag: { src: 'BrighterThanTheSun', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'BrighterThanTheSun',
      name: 'listConditional',
      tag: { src: 'BrighterThanTheSun', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'BrighterThanTheSun',
      name: 'numConditional',
      tag: { src: 'BrighterThanTheSun', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  ButTheBattleIsntOver: {
    boolConditional: {
      src: 'ButTheBattleIsntOver',
      name: 'boolConditional',
      tag: { src: 'ButTheBattleIsntOver', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'ButTheBattleIsntOver',
      name: 'listConditional',
      tag: { src: 'ButTheBattleIsntOver', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'ButTheBattleIsntOver',
      name: 'numConditional',
      tag: { src: 'ButTheBattleIsntOver', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  CarveTheMoonWeaveTheClouds: {
    boolConditional: {
      src: 'CarveTheMoonWeaveTheClouds',
      name: 'boolConditional',
      tag: { src: 'CarveTheMoonWeaveTheClouds', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'CarveTheMoonWeaveTheClouds',
      name: 'listConditional',
      tag: { src: 'CarveTheMoonWeaveTheClouds', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'CarveTheMoonWeaveTheClouds',
      name: 'numConditional',
      tag: { src: 'CarveTheMoonWeaveTheClouds', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  Chorus: {
    boolConditional: {
      src: 'Chorus',
      name: 'boolConditional',
      tag: { src: 'Chorus', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'Chorus',
      name: 'listConditional',
      tag: { src: 'Chorus', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'Chorus',
      name: 'numConditional',
      tag: { src: 'Chorus', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  CollapsingSky: {
    boolConditional: {
      src: 'CollapsingSky',
      name: 'boolConditional',
      tag: { src: 'CollapsingSky', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'CollapsingSky',
      name: 'listConditional',
      tag: { src: 'CollapsingSky', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'CollapsingSky',
      name: 'numConditional',
      tag: { src: 'CollapsingSky', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  Cornucopia: {
    boolConditional: {
      src: 'Cornucopia',
      name: 'boolConditional',
      tag: { src: 'Cornucopia', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'Cornucopia',
      name: 'listConditional',
      tag: { src: 'Cornucopia', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'Cornucopia',
      name: 'numConditional',
      tag: { src: 'Cornucopia', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  CruisingInTheStellarSea: {
    boolConditional: {
      src: 'CruisingInTheStellarSea',
      name: 'boolConditional',
      tag: { src: 'CruisingInTheStellarSea', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'CruisingInTheStellarSea',
      name: 'listConditional',
      tag: { src: 'CruisingInTheStellarSea', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'CruisingInTheStellarSea',
      name: 'numConditional',
      tag: { src: 'CruisingInTheStellarSea', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  DanceDanceDance: {
    boolConditional: {
      src: 'DanceDanceDance',
      name: 'boolConditional',
      tag: { src: 'DanceDanceDance', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'DanceDanceDance',
      name: 'listConditional',
      tag: { src: 'DanceDanceDance', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'DanceDanceDance',
      name: 'numConditional',
      tag: { src: 'DanceDanceDance', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  DartingArrow: {
    boolConditional: {
      src: 'DartingArrow',
      name: 'boolConditional',
      tag: { src: 'DartingArrow', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'DartingArrow',
      name: 'listConditional',
      tag: { src: 'DartingArrow', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'DartingArrow',
      name: 'numConditional',
      tag: { src: 'DartingArrow', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  DataBank: {
    boolConditional: {
      src: 'DataBank',
      name: 'boolConditional',
      tag: { src: 'DataBank', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'DataBank',
      name: 'listConditional',
      tag: { src: 'DataBank', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'DataBank',
      name: 'numConditional',
      tag: { src: 'DataBank', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  DayOneOfMyNewLife: {
    boolConditional: {
      src: 'DayOneOfMyNewLife',
      name: 'boolConditional',
      tag: { src: 'DayOneOfMyNewLife', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'DayOneOfMyNewLife',
      name: 'listConditional',
      tag: { src: 'DayOneOfMyNewLife', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'DayOneOfMyNewLife',
      name: 'numConditional',
      tag: { src: 'DayOneOfMyNewLife', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  Defense: {
    boolConditional: {
      src: 'Defense',
      name: 'boolConditional',
      tag: { src: 'Defense', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'Defense',
      name: 'listConditional',
      tag: { src: 'Defense', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'Defense',
      name: 'numConditional',
      tag: { src: 'Defense', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  EchoesOfTheCoffin: {
    boolConditional: {
      src: 'EchoesOfTheCoffin',
      name: 'boolConditional',
      tag: { src: 'EchoesOfTheCoffin', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'EchoesOfTheCoffin',
      name: 'listConditional',
      tag: { src: 'EchoesOfTheCoffin', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'EchoesOfTheCoffin',
      name: 'numConditional',
      tag: { src: 'EchoesOfTheCoffin', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  EyesOfThePrey: {
    boolConditional: {
      src: 'EyesOfThePrey',
      name: 'boolConditional',
      tag: { src: 'EyesOfThePrey', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'EyesOfThePrey',
      name: 'listConditional',
      tag: { src: 'EyesOfThePrey', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'EyesOfThePrey',
      name: 'numConditional',
      tag: { src: 'EyesOfThePrey', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  Fermata: {
    boolConditional: {
      src: 'Fermata',
      name: 'boolConditional',
      tag: { src: 'Fermata', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'Fermata',
      name: 'listConditional',
      tag: { src: 'Fermata', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'Fermata',
      name: 'numConditional',
      tag: { src: 'Fermata', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  FineFruit: {
    boolConditional: {
      src: 'FineFruit',
      name: 'boolConditional',
      tag: { src: 'FineFruit', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'FineFruit',
      name: 'listConditional',
      tag: { src: 'FineFruit', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'FineFruit',
      name: 'numConditional',
      tag: { src: 'FineFruit', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  GeniusesRepose: {
    boolConditional: {
      src: 'GeniusesRepose',
      name: 'boolConditional',
      tag: { src: 'GeniusesRepose', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'GeniusesRepose',
      name: 'listConditional',
      tag: { src: 'GeniusesRepose', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'GeniusesRepose',
      name: 'numConditional',
      tag: { src: 'GeniusesRepose', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  GoodNightAndSleepWell: {
    boolConditional: {
      src: 'GoodNightAndSleepWell',
      name: 'boolConditional',
      tag: { src: 'GoodNightAndSleepWell', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'GoodNightAndSleepWell',
      name: 'listConditional',
      tag: { src: 'GoodNightAndSleepWell', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'GoodNightAndSleepWell',
      name: 'numConditional',
      tag: { src: 'GoodNightAndSleepWell', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  HeyOverHere: {
    boolConditional: {
      src: 'HeyOverHere',
      name: 'boolConditional',
      tag: { src: 'HeyOverHere', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'HeyOverHere',
      name: 'listConditional',
      tag: { src: 'HeyOverHere', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'HeyOverHere',
      name: 'numConditional',
      tag: { src: 'HeyOverHere', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  HiddenShadow: {
    boolConditional: {
      src: 'HiddenShadow',
      name: 'boolConditional',
      tag: { src: 'HiddenShadow', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'HiddenShadow',
      name: 'listConditional',
      tag: { src: 'HiddenShadow', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'HiddenShadow',
      name: 'numConditional',
      tag: { src: 'HiddenShadow', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  IShallBeMyOwnSword: {
    boolConditional: {
      src: 'IShallBeMyOwnSword',
      name: 'boolConditional',
      tag: { src: 'IShallBeMyOwnSword', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'IShallBeMyOwnSword',
      name: 'listConditional',
      tag: { src: 'IShallBeMyOwnSword', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'IShallBeMyOwnSword',
      name: 'numConditional',
      tag: { src: 'IShallBeMyOwnSword', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  InTheNameOfTheWorld: {
    boolConditional: {
      src: 'InTheNameOfTheWorld',
      name: 'boolConditional',
      tag: { src: 'InTheNameOfTheWorld', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'InTheNameOfTheWorld',
      name: 'listConditional',
      tag: { src: 'InTheNameOfTheWorld', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'InTheNameOfTheWorld',
      name: 'numConditional',
      tag: { src: 'InTheNameOfTheWorld', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  InTheNight: {
    boolConditional: {
      src: 'InTheNight',
      name: 'boolConditional',
      tag: { src: 'InTheNight', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'InTheNight',
      name: 'listConditional',
      tag: { src: 'InTheNight', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'InTheNight',
      name: 'numConditional',
      tag: { src: 'InTheNight', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  IncessantRain: {
    boolConditional: {
      src: 'IncessantRain',
      name: 'boolConditional',
      tag: { src: 'IncessantRain', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'IncessantRain',
      name: 'listConditional',
      tag: { src: 'IncessantRain', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'IncessantRain',
      name: 'numConditional',
      tag: { src: 'IncessantRain', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  LandausChoice: {
    boolConditional: {
      src: 'LandausChoice',
      name: 'boolConditional',
      tag: { src: 'LandausChoice', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'LandausChoice',
      name: 'listConditional',
      tag: { src: 'LandausChoice', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'LandausChoice',
      name: 'numConditional',
      tag: { src: 'LandausChoice', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  Loop: {
    boolConditional: {
      src: 'Loop',
      name: 'boolConditional',
      tag: { src: 'Loop', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'Loop',
      name: 'listConditional',
      tag: { src: 'Loop', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'Loop',
      name: 'numConditional',
      tag: { src: 'Loop', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  MakeTheWorldClamor: {
    boolConditional: {
      src: 'MakeTheWorldClamor',
      name: 'boolConditional',
      tag: { src: 'MakeTheWorldClamor', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'MakeTheWorldClamor',
      name: 'listConditional',
      tag: { src: 'MakeTheWorldClamor', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'MakeTheWorldClamor',
      name: 'numConditional',
      tag: { src: 'MakeTheWorldClamor', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  Mediation: {
    boolConditional: {
      src: 'Mediation',
      name: 'boolConditional',
      tag: { src: 'Mediation', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'Mediation',
      name: 'listConditional',
      tag: { src: 'Mediation', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'Mediation',
      name: 'numConditional',
      tag: { src: 'Mediation', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  MemoriesOfThePast: {
    boolConditional: {
      src: 'MemoriesOfThePast',
      name: 'boolConditional',
      tag: { src: 'MemoriesOfThePast', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'MemoriesOfThePast',
      name: 'listConditional',
      tag: { src: 'MemoriesOfThePast', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'MemoriesOfThePast',
      name: 'numConditional',
      tag: { src: 'MemoriesOfThePast', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  MeshingCogs: {
    boolConditional: {
      src: 'MeshingCogs',
      name: 'boolConditional',
      tag: { src: 'MeshingCogs', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'MeshingCogs',
      name: 'listConditional',
      tag: { src: 'MeshingCogs', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'MeshingCogs',
      name: 'numConditional',
      tag: { src: 'MeshingCogs', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  MomentOfVictory: {
    boolConditional: {
      src: 'MomentOfVictory',
      name: 'boolConditional',
      tag: { src: 'MomentOfVictory', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'MomentOfVictory',
      name: 'listConditional',
      tag: { src: 'MomentOfVictory', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'MomentOfVictory',
      name: 'numConditional',
      tag: { src: 'MomentOfVictory', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  Multiplication: {
    boolConditional: {
      src: 'Multiplication',
      name: 'boolConditional',
      tag: { src: 'Multiplication', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'Multiplication',
      name: 'listConditional',
      tag: { src: 'Multiplication', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'Multiplication',
      name: 'numConditional',
      tag: { src: 'Multiplication', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  MutualDemise: {
    boolConditional: {
      src: 'MutualDemise',
      name: 'boolConditional',
      tag: { src: 'MutualDemise', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'MutualDemise',
      name: 'listConditional',
      tag: { src: 'MutualDemise', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'MutualDemise',
      name: 'numConditional',
      tag: { src: 'MutualDemise', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  NightOfFright: {
    boolConditional: {
      src: 'NightOfFright',
      name: 'boolConditional',
      tag: { src: 'NightOfFright', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'NightOfFright',
      name: 'listConditional',
      tag: { src: 'NightOfFright', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'NightOfFright',
      name: 'numConditional',
      tag: { src: 'NightOfFright', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  NightOnTheMilkyWay: {
    boolConditional: {
      src: 'NightOnTheMilkyWay',
      name: 'boolConditional',
      tag: { src: 'NightOnTheMilkyWay', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'NightOnTheMilkyWay',
      name: 'listConditional',
      tag: { src: 'NightOnTheMilkyWay', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'NightOnTheMilkyWay',
      name: 'numConditional',
      tag: { src: 'NightOnTheMilkyWay', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  NowhereToRun: {
    boolConditional: {
      src: 'NowhereToRun',
      name: 'boolConditional',
      tag: { src: 'NowhereToRun', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'NowhereToRun',
      name: 'listConditional',
      tag: { src: 'NowhereToRun', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'NowhereToRun',
      name: 'numConditional',
      tag: { src: 'NowhereToRun', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  OnTheFallOfAnAeon: {
    boolConditional: {
      src: 'OnTheFallOfAnAeon',
      name: 'boolConditional',
      tag: { src: 'OnTheFallOfAnAeon', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'OnTheFallOfAnAeon',
      name: 'listConditional',
      tag: { src: 'OnTheFallOfAnAeon', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'OnTheFallOfAnAeon',
      name: 'numConditional',
      tag: { src: 'OnTheFallOfAnAeon', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  OnlySilenceRemains: {
    boolConditional: {
      src: 'OnlySilenceRemains',
      name: 'boolConditional',
      tag: { src: 'OnlySilenceRemains', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'OnlySilenceRemains',
      name: 'listConditional',
      tag: { src: 'OnlySilenceRemains', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'OnlySilenceRemains',
      name: 'numConditional',
      tag: { src: 'OnlySilenceRemains', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  Passkey: {
    boolConditional: {
      src: 'Passkey',
      name: 'boolConditional',
      tag: { src: 'Passkey', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'Passkey',
      name: 'listConditional',
      tag: { src: 'Passkey', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'Passkey',
      name: 'numConditional',
      tag: { src: 'Passkey', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  PastSelfInMirror: {
    boolConditional: {
      src: 'PastSelfInMirror',
      name: 'boolConditional',
      tag: { src: 'PastSelfInMirror', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'PastSelfInMirror',
      name: 'listConditional',
      tag: { src: 'PastSelfInMirror', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'PastSelfInMirror',
      name: 'numConditional',
      tag: { src: 'PastSelfInMirror', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  PastAndFuture: {
    boolConditional: {
      src: 'PastAndFuture',
      name: 'boolConditional',
      tag: { src: 'PastAndFuture', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'PastAndFuture',
      name: 'listConditional',
      tag: { src: 'PastAndFuture', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'PastAndFuture',
      name: 'numConditional',
      tag: { src: 'PastAndFuture', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  PatienceIsAllYouNeed: {
    boolConditional: {
      src: 'PatienceIsAllYouNeed',
      name: 'boolConditional',
      tag: { src: 'PatienceIsAllYouNeed', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'PatienceIsAllYouNeed',
      name: 'listConditional',
      tag: { src: 'PatienceIsAllYouNeed', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'PatienceIsAllYouNeed',
      name: 'numConditional',
      tag: { src: 'PatienceIsAllYouNeed', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  PerfectTiming: {
    boolConditional: {
      src: 'PerfectTiming',
      name: 'boolConditional',
      tag: { src: 'PerfectTiming', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'PerfectTiming',
      name: 'listConditional',
      tag: { src: 'PerfectTiming', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'PerfectTiming',
      name: 'numConditional',
      tag: { src: 'PerfectTiming', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  Pioneering: {
    boolConditional: {
      src: 'Pioneering',
      name: 'boolConditional',
      tag: { src: 'Pioneering', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'Pioneering',
      name: 'listConditional',
      tag: { src: 'Pioneering', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'Pioneering',
      name: 'numConditional',
      tag: { src: 'Pioneering', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  PlanetaryRendezvous: {
    boolConditional: {
      src: 'PlanetaryRendezvous',
      name: 'boolConditional',
      tag: { src: 'PlanetaryRendezvous', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'PlanetaryRendezvous',
      name: 'listConditional',
      tag: { src: 'PlanetaryRendezvous', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'PlanetaryRendezvous',
      name: 'numConditional',
      tag: { src: 'PlanetaryRendezvous', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  PostOpConversation: {
    boolConditional: {
      src: 'PostOpConversation',
      name: 'boolConditional',
      tag: { src: 'PostOpConversation', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'PostOpConversation',
      name: 'listConditional',
      tag: { src: 'PostOpConversation', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'PostOpConversation',
      name: 'numConditional',
      tag: { src: 'PostOpConversation', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  QuidProQuo: {
    boolConditional: {
      src: 'QuidProQuo',
      name: 'boolConditional',
      tag: { src: 'QuidProQuo', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'QuidProQuo',
      name: 'listConditional',
      tag: { src: 'QuidProQuo', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'QuidProQuo',
      name: 'numConditional',
      tag: { src: 'QuidProQuo', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  ResolutionShinesAsPearlsOfSweat: {
    boolConditional: {
      src: 'ResolutionShinesAsPearlsOfSweat',
      name: 'boolConditional',
      tag: { src: 'ResolutionShinesAsPearlsOfSweat', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'ResolutionShinesAsPearlsOfSweat',
      name: 'listConditional',
      tag: { src: 'ResolutionShinesAsPearlsOfSweat', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'ResolutionShinesAsPearlsOfSweat',
      name: 'numConditional',
      tag: { src: 'ResolutionShinesAsPearlsOfSweat', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  ReturnToDarkness: {
    boolConditional: {
      src: 'ReturnToDarkness',
      name: 'boolConditional',
      tag: { src: 'ReturnToDarkness', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'ReturnToDarkness',
      name: 'listConditional',
      tag: { src: 'ReturnToDarkness', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'ReturnToDarkness',
      name: 'numConditional',
      tag: { src: 'ReturnToDarkness', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  RiverFlowsInSpring: {
    boolConditional: {
      src: 'RiverFlowsInSpring',
      name: 'boolConditional',
      tag: { src: 'RiverFlowsInSpring', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'RiverFlowsInSpring',
      name: 'listConditional',
      tag: { src: 'RiverFlowsInSpring', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'RiverFlowsInSpring',
      name: 'numConditional',
      tag: { src: 'RiverFlowsInSpring', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  Sagacity: {
    boolConditional: {
      src: 'Sagacity',
      name: 'boolConditional',
      tag: { src: 'Sagacity', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'Sagacity',
      name: 'listConditional',
      tag: { src: 'Sagacity', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'Sagacity',
      name: 'numConditional',
      tag: { src: 'Sagacity', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  SharedFeeling: {
    boolConditional: {
      src: 'SharedFeeling',
      name: 'boolConditional',
      tag: { src: 'SharedFeeling', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'SharedFeeling',
      name: 'listConditional',
      tag: { src: 'SharedFeeling', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'SharedFeeling',
      name: 'numConditional',
      tag: { src: 'SharedFeeling', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  ShatteredHome: {
    boolConditional: {
      src: 'ShatteredHome',
      name: 'boolConditional',
      tag: { src: 'ShatteredHome', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'ShatteredHome',
      name: 'listConditional',
      tag: { src: 'ShatteredHome', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'ShatteredHome',
      name: 'numConditional',
      tag: { src: 'ShatteredHome', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  SheAlreadyShutHerEyes: {
    boolConditional: {
      src: 'SheAlreadyShutHerEyes',
      name: 'boolConditional',
      tag: { src: 'SheAlreadyShutHerEyes', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'SheAlreadyShutHerEyes',
      name: 'listConditional',
      tag: { src: 'SheAlreadyShutHerEyes', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'SheAlreadyShutHerEyes',
      name: 'numConditional',
      tag: { src: 'SheAlreadyShutHerEyes', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  SleepLikeTheDead: {
    boolConditional: {
      src: 'SleepLikeTheDead',
      name: 'boolConditional',
      tag: { src: 'SleepLikeTheDead', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'SleepLikeTheDead',
      name: 'listConditional',
      tag: { src: 'SleepLikeTheDead', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'SleepLikeTheDead',
      name: 'numConditional',
      tag: { src: 'SleepLikeTheDead', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  SolitaryHealing: {
    boolConditional: {
      src: 'SolitaryHealing',
      name: 'boolConditional',
      tag: { src: 'SolitaryHealing', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'SolitaryHealing',
      name: 'listConditional',
      tag: { src: 'SolitaryHealing', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'SolitaryHealing',
      name: 'numConditional',
      tag: { src: 'SolitaryHealing', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  SomethingIrreplaceable: {
    boolConditional: {
      src: 'SomethingIrreplaceable',
      name: 'boolConditional',
      tag: { src: 'SomethingIrreplaceable', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'SomethingIrreplaceable',
      name: 'listConditional',
      tag: { src: 'SomethingIrreplaceable', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'SomethingIrreplaceable',
      name: 'numConditional',
      tag: { src: 'SomethingIrreplaceable', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  SubscribeForMore: {
    boolConditional: {
      src: 'SubscribeForMore',
      name: 'boolConditional',
      tag: { src: 'SubscribeForMore', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'SubscribeForMore',
      name: 'listConditional',
      tag: { src: 'SubscribeForMore', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'SubscribeForMore',
      name: 'numConditional',
      tag: { src: 'SubscribeForMore', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  Swordplay: {
    boolConditional: {
      src: 'Swordplay',
      name: 'boolConditional',
      tag: { src: 'Swordplay', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'Swordplay',
      name: 'listConditional',
      tag: { src: 'Swordplay', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'Swordplay',
      name: 'numConditional',
      tag: { src: 'Swordplay', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  TextureOfMemories: {
    boolConditional: {
      src: 'TextureOfMemories',
      name: 'boolConditional',
      tag: { src: 'TextureOfMemories', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'TextureOfMemories',
      name: 'listConditional',
      tag: { src: 'TextureOfMemories', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'TextureOfMemories',
      name: 'numConditional',
      tag: { src: 'TextureOfMemories', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  TheBirthOfTheSelf: {
    boolConditional: {
      src: 'TheBirthOfTheSelf',
      name: 'boolConditional',
      tag: { src: 'TheBirthOfTheSelf', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'TheBirthOfTheSelf',
      name: 'listConditional',
      tag: { src: 'TheBirthOfTheSelf', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'TheBirthOfTheSelf',
      name: 'numConditional',
      tag: { src: 'TheBirthOfTheSelf', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  TheMolesWelcomeYou: {
    boolConditional: {
      src: 'TheMolesWelcomeYou',
      name: 'boolConditional',
      tag: { src: 'TheMolesWelcomeYou', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'TheMolesWelcomeYou',
      name: 'listConditional',
      tag: { src: 'TheMolesWelcomeYou', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'TheMolesWelcomeYou',
      name: 'numConditional',
      tag: { src: 'TheMolesWelcomeYou', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  TheSeriousnessOfBreakfast: {
    stackCount: {
      src: 'TheSeriousnessOfBreakfast',
      name: 'stackCount',
      tag: { src: 'TheSeriousnessOfBreakfast', name: 'stackCount' },
      type: 'num',
      int_only: true,
      min: 0,
      max: -1,
    },
  },
  TheUnreachableSide: {
    boolConditional: {
      src: 'TheUnreachableSide',
      name: 'boolConditional',
      tag: { src: 'TheUnreachableSide', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'TheUnreachableSide',
      name: 'listConditional',
      tag: { src: 'TheUnreachableSide', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'TheUnreachableSide',
      name: 'numConditional',
      tag: { src: 'TheUnreachableSide', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  ThisIsMe: {
    boolConditional: {
      src: 'ThisIsMe',
      name: 'boolConditional',
      tag: { src: 'ThisIsMe', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'ThisIsMe',
      name: 'listConditional',
      tag: { src: 'ThisIsMe', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'ThisIsMe',
      name: 'numConditional',
      tag: { src: 'ThisIsMe', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  TimeWaitsForNoOne: {
    boolConditional: {
      src: 'TimeWaitsForNoOne',
      name: 'boolConditional',
      tag: { src: 'TimeWaitsForNoOne', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'TimeWaitsForNoOne',
      name: 'listConditional',
      tag: { src: 'TimeWaitsForNoOne', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'TimeWaitsForNoOne',
      name: 'numConditional',
      tag: { src: 'TimeWaitsForNoOne', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  TodayIsAnotherPeacefulDay: {
    boolConditional: {
      src: 'TodayIsAnotherPeacefulDay',
      name: 'boolConditional',
      tag: { src: 'TodayIsAnotherPeacefulDay', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'TodayIsAnotherPeacefulDay',
      name: 'listConditional',
      tag: { src: 'TodayIsAnotherPeacefulDay', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'TodayIsAnotherPeacefulDay',
      name: 'numConditional',
      tag: { src: 'TodayIsAnotherPeacefulDay', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  TrendOfTheUniversalMarket: {
    boolConditional: {
      src: 'TrendOfTheUniversalMarket',
      name: 'boolConditional',
      tag: { src: 'TrendOfTheUniversalMarket', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'TrendOfTheUniversalMarket',
      name: 'listConditional',
      tag: { src: 'TrendOfTheUniversalMarket', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'TrendOfTheUniversalMarket',
      name: 'numConditional',
      tag: { src: 'TrendOfTheUniversalMarket', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  UnderTheBlueSky: {
    boolConditional: {
      src: 'UnderTheBlueSky',
      name: 'boolConditional',
      tag: { src: 'UnderTheBlueSky', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'UnderTheBlueSky',
      name: 'listConditional',
      tag: { src: 'UnderTheBlueSky', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'UnderTheBlueSky',
      name: 'numConditional',
      tag: { src: 'UnderTheBlueSky', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  Void: {
    boolConditional: {
      src: 'Void',
      name: 'boolConditional',
      tag: { src: 'Void', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'Void',
      name: 'listConditional',
      tag: { src: 'Void', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'Void',
      name: 'numConditional',
      tag: { src: 'Void', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  WarmthShortensColdNights: {
    boolConditional: {
      src: 'WarmthShortensColdNights',
      name: 'boolConditional',
      tag: { src: 'WarmthShortensColdNights', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'WarmthShortensColdNights',
      name: 'listConditional',
      tag: { src: 'WarmthShortensColdNights', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'WarmthShortensColdNights',
      name: 'numConditional',
      tag: { src: 'WarmthShortensColdNights', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  WeAreWildfire: {
    boolConditional: {
      src: 'WeAreWildfire',
      name: 'boolConditional',
      tag: { src: 'WeAreWildfire', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'WeAreWildfire',
      name: 'listConditional',
      tag: { src: 'WeAreWildfire', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'WeAreWildfire',
      name: 'numConditional',
      tag: { src: 'WeAreWildfire', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  WeWillMeetAgain: {
    boolConditional: {
      src: 'WeWillMeetAgain',
      name: 'boolConditional',
      tag: { src: 'WeWillMeetAgain', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'WeWillMeetAgain',
      name: 'listConditional',
      tag: { src: 'WeWillMeetAgain', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'WeWillMeetAgain',
      name: 'numConditional',
      tag: { src: 'WeWillMeetAgain', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  WoofWalkTime: {
    boolConditional: {
      src: 'WoofWalkTime',
      name: 'boolConditional',
      tag: { src: 'WoofWalkTime', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'WoofWalkTime',
      name: 'listConditional',
      tag: { src: 'WoofWalkTime', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'WoofWalkTime',
      name: 'numConditional',
      tag: { src: 'WoofWalkTime', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  WorrisomeBlissful: {
    boolConditional: {
      src: 'WorrisomeBlissful',
      name: 'boolConditional',
      tag: { src: 'WorrisomeBlissful', name: 'boolConditional' },
      type: 'bool',
    },
    listConditional: {
      src: 'WorrisomeBlissful',
      name: 'listConditional',
      tag: { src: 'WorrisomeBlissful', name: 'listConditional' },
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      src: 'WorrisomeBlissful',
      name: 'numConditional',
      tag: { src: 'WorrisomeBlissful', name: 'numConditional' },
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
}
export const formulas = {
  Argenti: {
    basicDmg_0: {
      src: 'Argenti',
      name: 'basicDmg_0',
      tag: {
        src: 'Argenti',
        qt: 'formula',
        q: 'dmg',
        et: 'self',
        name: 'basicDmg_0',
      },
    },
  },
  Arlan: {
    basicDmg_0: {
      src: 'Arlan',
      name: 'basicDmg_0',
      tag: {
        src: 'Arlan',
        qt: 'formula',
        q: 'dmg',
        et: 'self',
        name: 'basicDmg_0',
      },
    },
  },
  Asta: {
    basicDmg_0: {
      src: 'Asta',
      name: 'basicDmg_0',
      tag: {
        src: 'Asta',
        qt: 'formula',
        q: 'dmg',
        et: 'self',
        name: 'basicDmg_0',
      },
    },
  },
  Bailu: {
    basicDmg_0: {
      src: 'Bailu',
      name: 'basicDmg_0',
      tag: {
        src: 'Bailu',
        qt: 'formula',
        q: 'dmg',
        et: 'self',
        name: 'basicDmg_0',
      },
    },
  },
  Blade: {
    basicDmg_0: {
      src: 'Blade',
      name: 'basicDmg_0',
      tag: {
        src: 'Blade',
        qt: 'formula',
        q: 'dmg',
        et: 'self',
        name: 'basicDmg_0',
      },
    },
  },
  Bronya: {
    basicDmg_0: {
      src: 'Bronya',
      name: 'basicDmg_0',
      tag: {
        src: 'Bronya',
        qt: 'formula',
        q: 'dmg',
        et: 'self',
        name: 'basicDmg_0',
      },
    },
  },
  Clara: {
    basicDmg_0: {
      src: 'Clara',
      name: 'basicDmg_0',
      tag: {
        src: 'Clara',
        qt: 'formula',
        q: 'dmg',
        et: 'self',
        name: 'basicDmg_0',
      },
    },
  },
  DanHeng: {
    basicDmg_0: {
      src: 'DanHeng',
      name: 'basicDmg_0',
      tag: {
        src: 'DanHeng',
        qt: 'formula',
        q: 'dmg',
        et: 'self',
        name: 'basicDmg_0',
      },
    },
  },
  DanHengImbibitorLunae: {
    basicDmg_0: {
      src: 'DanHengImbibitorLunae',
      name: 'basicDmg_0',
      tag: {
        src: 'DanHengImbibitorLunae',
        qt: 'formula',
        q: 'dmg',
        et: 'self',
        name: 'basicDmg_0',
      },
    },
  },
  DrRatio: {
    basicDmg_0: {
      src: 'DrRatio',
      name: 'basicDmg_0',
      tag: {
        src: 'DrRatio',
        qt: 'formula',
        q: 'dmg',
        et: 'self',
        name: 'basicDmg_0',
      },
    },
  },
  FuXuan: {
    basicDmg_0: {
      src: 'FuXuan',
      name: 'basicDmg_0',
      tag: {
        src: 'FuXuan',
        qt: 'formula',
        q: 'dmg',
        et: 'self',
        name: 'basicDmg_0',
      },
    },
  },
  Gepard: {
    basicDmg_0: {
      src: 'Gepard',
      name: 'basicDmg_0',
      tag: {
        src: 'Gepard',
        qt: 'formula',
        q: 'dmg',
        et: 'self',
        name: 'basicDmg_0',
      },
    },
  },
  Guinaifen: {
    basicDmg_0: {
      src: 'Guinaifen',
      name: 'basicDmg_0',
      tag: {
        src: 'Guinaifen',
        qt: 'formula',
        q: 'dmg',
        et: 'self',
        name: 'basicDmg_0',
      },
    },
  },
  Hanya: {
    basicDmg_0: {
      src: 'Hanya',
      name: 'basicDmg_0',
      tag: {
        src: 'Hanya',
        qt: 'formula',
        q: 'dmg',
        et: 'self',
        name: 'basicDmg_0',
      },
    },
  },
  Herta: {
    basicDmg_0: {
      src: 'Herta',
      name: 'basicDmg_0',
      tag: {
        src: 'Herta',
        qt: 'formula',
        q: 'dmg',
        et: 'self',
        name: 'basicDmg_0',
      },
    },
  },
  Himeko: {
    basicDmg_0: {
      src: 'Himeko',
      name: 'basicDmg_0',
      tag: {
        src: 'Himeko',
        qt: 'formula',
        q: 'dmg',
        et: 'self',
        name: 'basicDmg_0',
      },
    },
  },
  Hook: {
    basicDmg_0: {
      src: 'Hook',
      name: 'basicDmg_0',
      tag: {
        src: 'Hook',
        qt: 'formula',
        q: 'dmg',
        et: 'self',
        name: 'basicDmg_0',
      },
    },
  },
  Huohuo: {
    basicDmg_0: {
      src: 'Huohuo',
      name: 'basicDmg_0',
      tag: {
        src: 'Huohuo',
        qt: 'formula',
        q: 'dmg',
        et: 'self',
        name: 'basicDmg_0',
      },
    },
  },
  JingYuan: {
    basicDmg_0: {
      src: 'JingYuan',
      name: 'basicDmg_0',
      tag: {
        src: 'JingYuan',
        qt: 'formula',
        q: 'dmg',
        et: 'self',
        name: 'basicDmg_0',
      },
    },
  },
  Jingliu: {
    basicDmg_0: {
      src: 'Jingliu',
      name: 'basicDmg_0',
      tag: {
        src: 'Jingliu',
        qt: 'formula',
        q: 'dmg',
        et: 'self',
        name: 'basicDmg_0',
      },
    },
  },
  Kafka: {
    basicDmg_0: {
      src: 'Kafka',
      name: 'basicDmg_0',
      tag: {
        src: 'Kafka',
        qt: 'formula',
        q: 'dmg',
        et: 'self',
        name: 'basicDmg_0',
      },
    },
  },
  Luka: {
    basicDmg_0: {
      src: 'Luka',
      name: 'basicDmg_0',
      tag: {
        src: 'Luka',
        qt: 'formula',
        q: 'dmg',
        et: 'self',
        name: 'basicDmg_0',
      },
    },
  },
  Luocha: {
    basicDmg_0: {
      src: 'Luocha',
      name: 'basicDmg_0',
      tag: {
        src: 'Luocha',
        qt: 'formula',
        q: 'dmg',
        et: 'self',
        name: 'basicDmg_0',
      },
    },
  },
  Lynx: {
    basicDmg_0: {
      src: 'Lynx',
      name: 'basicDmg_0',
      tag: {
        src: 'Lynx',
        qt: 'formula',
        q: 'dmg',
        et: 'self',
        name: 'basicDmg_0',
      },
    },
  },
  March7th: {
    basicDmg_0: {
      src: 'March7th',
      name: 'basicDmg_0',
      tag: {
        src: 'March7th',
        qt: 'formula',
        q: 'dmg',
        et: 'self',
        name: 'basicDmg_0',
      },
    },
    skillShield: {
      src: 'March7th',
      name: 'skillShield',
      tag: {
        src: 'March7th',
        qt: 'formula',
        q: 'shield',
        et: 'self',
        name: 'skillShield',
      },
    },
    ultDmg_0: {
      src: 'March7th',
      name: 'ultDmg_0',
      tag: {
        src: 'March7th',
        qt: 'formula',
        q: 'dmg',
        et: 'self',
        name: 'ultDmg_0',
      },
    },
    ultDmg_1: {
      src: 'March7th',
      name: 'ultDmg_1',
      tag: {
        src: 'March7th',
        qt: 'formula',
        q: 'dmg',
        et: 'self',
        name: 'ultDmg_1',
      },
    },
    ultDmg_2: {
      src: 'March7th',
      name: 'ultDmg_2',
      tag: {
        src: 'March7th',
        qt: 'formula',
        q: 'dmg',
        et: 'self',
        name: 'ultDmg_2',
      },
    },
    ultDmg_3: {
      src: 'March7th',
      name: 'ultDmg_3',
      tag: {
        src: 'March7th',
        qt: 'formula',
        q: 'dmg',
        et: 'self',
        name: 'ultDmg_3',
      },
    },
    ultFreeze_0: {
      src: 'March7th',
      name: 'ultFreeze_0',
      tag: {
        src: 'March7th',
        qt: 'formula',
        q: 'dmg',
        et: 'self',
        name: 'ultFreeze_0',
      },
    },
    talentDmg_0: {
      src: 'March7th',
      name: 'talentDmg_0',
      tag: {
        src: 'March7th',
        qt: 'formula',
        q: 'dmg',
        et: 'self',
        name: 'talentDmg_0',
      },
    },
    techniqueFreeze_0: {
      src: 'March7th',
      name: 'techniqueFreeze_0',
      tag: {
        src: 'March7th',
        qt: 'formula',
        q: 'dmg',
        et: 'self',
        name: 'techniqueFreeze_0',
      },
    },
    e1Shield: {
      src: 'March7th',
      name: 'e1Shield',
      tag: {
        src: 'March7th',
        qt: 'formula',
        q: 'shield',
        et: 'self',
        name: 'e1Shield',
      },
    },
    e6Heal: {
      src: 'March7th',
      name: 'e6Heal',
      tag: {
        src: 'March7th',
        qt: 'formula',
        q: 'heal',
        et: 'self',
        name: 'e6Heal',
      },
    },
  },
  Natasha: {
    basicDmg_0: {
      src: 'Natasha',
      name: 'basicDmg_0',
      tag: {
        src: 'Natasha',
        qt: 'formula',
        q: 'dmg',
        et: 'self',
        name: 'basicDmg_0',
      },
    },
  },
  Pela: {
    basicDmg_0: {
      src: 'Pela',
      name: 'basicDmg_0',
      tag: {
        src: 'Pela',
        qt: 'formula',
        q: 'dmg',
        et: 'self',
        name: 'basicDmg_0',
      },
    },
  },
  Qingque: {
    basicDmg_0: {
      src: 'Qingque',
      name: 'basicDmg_0',
      tag: {
        src: 'Qingque',
        qt: 'formula',
        q: 'dmg',
        et: 'self',
        name: 'basicDmg_0',
      },
    },
  },
  RuanMei: {
    basicDmg_0: {
      src: 'RuanMei',
      name: 'basicDmg_0',
      tag: {
        src: 'RuanMei',
        qt: 'formula',
        q: 'dmg',
        et: 'self',
        name: 'basicDmg_0',
      },
    },
  },
  Sampo: {
    basicDmg_0: {
      src: 'Sampo',
      name: 'basicDmg_0',
      tag: {
        src: 'Sampo',
        qt: 'formula',
        q: 'dmg',
        et: 'self',
        name: 'basicDmg_0',
      },
    },
  },
  Seele: {
    basicDmg_0: {
      src: 'Seele',
      name: 'basicDmg_0',
      tag: {
        src: 'Seele',
        qt: 'formula',
        q: 'dmg',
        et: 'self',
        name: 'basicDmg_0',
      },
    },
  },
  Serval: {
    basicDmg_0: {
      src: 'Serval',
      name: 'basicDmg_0',
      tag: {
        src: 'Serval',
        qt: 'formula',
        q: 'dmg',
        et: 'self',
        name: 'basicDmg_0',
      },
    },
  },
  SilverWolf: {
    basicDmg_0: {
      src: 'SilverWolf',
      name: 'basicDmg_0',
      tag: {
        src: 'SilverWolf',
        qt: 'formula',
        q: 'dmg',
        et: 'self',
        name: 'basicDmg_0',
      },
    },
  },
  Sushang: {
    basicDmg_0: {
      src: 'Sushang',
      name: 'basicDmg_0',
      tag: {
        src: 'Sushang',
        qt: 'formula',
        q: 'dmg',
        et: 'self',
        name: 'basicDmg_0',
      },
    },
  },
  Tingyun: {
    basicDmg_0: {
      src: 'Tingyun',
      name: 'basicDmg_0',
      tag: {
        src: 'Tingyun',
        qt: 'formula',
        q: 'dmg',
        et: 'self',
        name: 'basicDmg_0',
      },
    },
  },
  TopazAndNumby: {
    basicDmg_0: {
      src: 'TopazAndNumby',
      name: 'basicDmg_0',
      tag: {
        src: 'TopazAndNumby',
        qt: 'formula',
        q: 'dmg',
        et: 'self',
        name: 'basicDmg_0',
      },
    },
  },
  Welt: {
    basicDmg_0: {
      src: 'Welt',
      name: 'basicDmg_0',
      tag: {
        src: 'Welt',
        qt: 'formula',
        q: 'dmg',
        et: 'self',
        name: 'basicDmg_0',
      },
    },
  },
  Xueyi: {
    basicDmg_0: {
      src: 'Xueyi',
      name: 'basicDmg_0',
      tag: {
        src: 'Xueyi',
        qt: 'formula',
        q: 'dmg',
        et: 'self',
        name: 'basicDmg_0',
      },
    },
  },
  Yanqing: {
    basicDmg_0: {
      src: 'Yanqing',
      name: 'basicDmg_0',
      tag: {
        src: 'Yanqing',
        qt: 'formula',
        q: 'dmg',
        et: 'self',
        name: 'basicDmg_0',
      },
    },
  },
  Yukong: {
    basicDmg_0: {
      src: 'Yukong',
      name: 'basicDmg_0',
      tag: {
        src: 'Yukong',
        qt: 'formula',
        q: 'dmg',
        et: 'self',
        name: 'basicDmg_0',
      },
    },
  },
}
