// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Qingyi',
    name: 'standardDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Qingyi',
      attribute: 'electric',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Qingyi',
    name: 'anomalyDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_electric: {
    sheet: 'Qingyi',
    name: 'disorderDmgInst_electric',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'disorder',
      name: 'disorderDmgInst_electric',
    },
  },
  vortexDmgInst_electric: {
    sheet: 'Qingyi',
    name: 'vortexDmgInst_electric',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'vortex',
      name: 'vortexDmgInst_electric',
    },
  },
  abloomDmgInst: {
    sheet: 'Qingyi',
    name: 'abloomDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Qingyi',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Qingyi',
      attribute: 'electric',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Qingyi',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Qingyi',
      attribute: 'electric',
      name: 'dazeInst',
    },
  },
  'BasicAttackPenultimate_0:standardDmg': {
    sheet: 'Qingyi',
    name: 'BasicAttackPenultimate_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Qingyi',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackPenultimate_0',
    },
  },
  'BasicAttackPenultimate_0:dazeBuildup': {
    sheet: 'Qingyi',
    name: 'BasicAttackPenultimate_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Qingyi',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackPenultimate_0',
    },
  },
  'BasicAttackPenultimate_0:anomBuildup': {
    sheet: 'Qingyi',
    name: 'BasicAttackPenultimate_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Qingyi',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackPenultimate_0',
    },
  },
  'BasicAttackPenultimate_1:standardDmg': {
    sheet: 'Qingyi',
    name: 'BasicAttackPenultimate_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Qingyi',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackPenultimate_1',
    },
  },
  'BasicAttackPenultimate_1:dazeBuildup': {
    sheet: 'Qingyi',
    name: 'BasicAttackPenultimate_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Qingyi',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackPenultimate_1',
    },
  },
  'BasicAttackPenultimate_1:anomBuildup': {
    sheet: 'Qingyi',
    name: 'BasicAttackPenultimate_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Qingyi',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackPenultimate_1',
    },
  },
  'BasicAttackPenultimate_2:standardDmg': {
    sheet: 'Qingyi',
    name: 'BasicAttackPenultimate_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Qingyi',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackPenultimate_2',
    },
  },
  'BasicAttackPenultimate_2:dazeBuildup': {
    sheet: 'Qingyi',
    name: 'BasicAttackPenultimate_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Qingyi',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackPenultimate_2',
    },
  },
  'BasicAttackPenultimate_2:anomBuildup': {
    sheet: 'Qingyi',
    name: 'BasicAttackPenultimate_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Qingyi',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackPenultimate_2',
    },
  },
  'BasicAttackPenultimate_3:standardDmg': {
    sheet: 'Qingyi',
    name: 'BasicAttackPenultimate_3:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackPenultimate_3',
    },
  },
  'BasicAttackPenultimate_3:dazeBuildup': {
    sheet: 'Qingyi',
    name: 'BasicAttackPenultimate_3:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackPenultimate_3',
    },
  },
  'BasicAttackPenultimate_3:anomBuildup': {
    sheet: 'Qingyi',
    name: 'BasicAttackPenultimate_3:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackPenultimate_3',
    },
  },
  'BasicAttackPenultimate_4:standardDmg': {
    sheet: 'Qingyi',
    name: 'BasicAttackPenultimate_4:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackPenultimate_4',
    },
  },
  'BasicAttackPenultimate_4:dazeBuildup': {
    sheet: 'Qingyi',
    name: 'BasicAttackPenultimate_4:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackPenultimate_4',
    },
  },
  'BasicAttackPenultimate_4:anomBuildup': {
    sheet: 'Qingyi',
    name: 'BasicAttackPenultimate_4:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackPenultimate_4',
    },
  },
  'BasicAttackPenultimate_5:standardDmg': {
    sheet: 'Qingyi',
    name: 'BasicAttackPenultimate_5:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackPenultimate_5',
    },
  },
  'BasicAttackPenultimate_5:dazeBuildup': {
    sheet: 'Qingyi',
    name: 'BasicAttackPenultimate_5:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackPenultimate_5',
    },
  },
  'BasicAttackPenultimate_5:anomBuildup': {
    sheet: 'Qingyi',
    name: 'BasicAttackPenultimate_5:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackPenultimate_5',
    },
  },
  'BasicAttackEnchantedBlossoms_0:standardDmg': {
    sheet: 'Qingyi',
    name: 'BasicAttackEnchantedBlossoms_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackEnchantedBlossoms_0',
    },
  },
  'BasicAttackEnchantedBlossoms_0:dazeBuildup': {
    sheet: 'Qingyi',
    name: 'BasicAttackEnchantedBlossoms_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackEnchantedBlossoms_0',
    },
  },
  'BasicAttackEnchantedBlossoms_0:anomBuildup': {
    sheet: 'Qingyi',
    name: 'BasicAttackEnchantedBlossoms_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackEnchantedBlossoms_0',
    },
  },
  'BasicAttackEnchantedMoonlitBlossoms_0:standardDmg': {
    sheet: 'Qingyi',
    name: 'BasicAttackEnchantedMoonlitBlossoms_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackEnchantedMoonlitBlossoms_0',
    },
  },
  'BasicAttackEnchantedMoonlitBlossoms_0:dazeBuildup': {
    sheet: 'Qingyi',
    name: 'BasicAttackEnchantedMoonlitBlossoms_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackEnchantedMoonlitBlossoms_0',
    },
  },
  'BasicAttackEnchantedMoonlitBlossoms_0:anomBuildup': {
    sheet: 'Qingyi',
    name: 'BasicAttackEnchantedMoonlitBlossoms_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackEnchantedMoonlitBlossoms_0',
    },
  },
  'BasicAttackEnchantedMoonlitBlossoms_1:standardDmg': {
    sheet: 'Qingyi',
    name: 'BasicAttackEnchantedMoonlitBlossoms_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackEnchantedMoonlitBlossoms_1',
    },
  },
  'BasicAttackEnchantedMoonlitBlossoms_1:dazeBuildup': {
    sheet: 'Qingyi',
    name: 'BasicAttackEnchantedMoonlitBlossoms_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackEnchantedMoonlitBlossoms_1',
    },
  },
  'BasicAttackEnchantedMoonlitBlossoms_1:anomBuildup': {
    sheet: 'Qingyi',
    name: 'BasicAttackEnchantedMoonlitBlossoms_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackEnchantedMoonlitBlossoms_1',
    },
  },
  'DashAttackBreach_0:standardDmg': {
    sheet: 'Qingyi',
    name: 'DashAttackBreach_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Qingyi',
      damageType1: 'dash',
      attribute: 'physical',
      skillType1: 'dodgeSkill',
      name: 'DashAttackBreach_0',
    },
  },
  'DashAttackBreach_0:dazeBuildup': {
    sheet: 'Qingyi',
    name: 'DashAttackBreach_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Qingyi',
      damageType1: 'dash',
      attribute: 'physical',
      skillType1: 'dodgeSkill',
      name: 'DashAttackBreach_0',
    },
  },
  'DashAttackBreach_0:anomBuildup': {
    sheet: 'Qingyi',
    name: 'DashAttackBreach_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Qingyi',
      damageType1: 'dash',
      attribute: 'physical',
      skillType1: 'dodgeSkill',
      name: 'DashAttackBreach_0',
    },
  },
  'DodgeCounterLingeringSentiments_0:standardDmg': {
    sheet: 'Qingyi',
    name: 'DodgeCounterLingeringSentiments_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'dodgeCounter',
      skillType1: 'dodgeSkill',
      name: 'DodgeCounterLingeringSentiments_0',
    },
  },
  'DodgeCounterLingeringSentiments_0:dazeBuildup': {
    sheet: 'Qingyi',
    name: 'DodgeCounterLingeringSentiments_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'dodgeCounter',
      skillType1: 'dodgeSkill',
      name: 'DodgeCounterLingeringSentiments_0',
    },
  },
  'DodgeCounterLingeringSentiments_0:anomBuildup': {
    sheet: 'Qingyi',
    name: 'DodgeCounterLingeringSentiments_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'dodgeCounter',
      skillType1: 'dodgeSkill',
      name: 'DodgeCounterLingeringSentiments_0',
    },
  },
  'SpecialAttackSunlitGlory_0:standardDmg': {
    sheet: 'Qingyi',
    name: 'SpecialAttackSunlitGlory_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackSunlitGlory_0',
    },
  },
  'SpecialAttackSunlitGlory_0:dazeBuildup': {
    sheet: 'Qingyi',
    name: 'SpecialAttackSunlitGlory_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackSunlitGlory_0',
    },
  },
  'SpecialAttackSunlitGlory_0:anomBuildup': {
    sheet: 'Qingyi',
    name: 'SpecialAttackSunlitGlory_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackSunlitGlory_0',
    },
  },
  'EXSpecialAttackMoonlitBegonia_0:standardDmg': {
    sheet: 'Qingyi',
    name: 'EXSpecialAttackMoonlitBegonia_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackMoonlitBegonia_0',
    },
  },
  'EXSpecialAttackMoonlitBegonia_0:dazeBuildup': {
    sheet: 'Qingyi',
    name: 'EXSpecialAttackMoonlitBegonia_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackMoonlitBegonia_0',
    },
  },
  'EXSpecialAttackMoonlitBegonia_0:anomBuildup': {
    sheet: 'Qingyi',
    name: 'EXSpecialAttackMoonlitBegonia_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackMoonlitBegonia_0',
    },
  },
  'EXSpecialAttackMoonlitBegonia_1:standardDmg': {
    sheet: 'Qingyi',
    name: 'EXSpecialAttackMoonlitBegonia_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackMoonlitBegonia_1',
    },
  },
  'EXSpecialAttackMoonlitBegonia_1:dazeBuildup': {
    sheet: 'Qingyi',
    name: 'EXSpecialAttackMoonlitBegonia_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackMoonlitBegonia_1',
    },
  },
  'EXSpecialAttackMoonlitBegonia_1:anomBuildup': {
    sheet: 'Qingyi',
    name: 'EXSpecialAttackMoonlitBegonia_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackMoonlitBegonia_1',
    },
  },
  'EXSpecialAttackMoonlitBegonia_2:standardDmg': {
    sheet: 'Qingyi',
    name: 'EXSpecialAttackMoonlitBegonia_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackMoonlitBegonia_2',
    },
  },
  'EXSpecialAttackMoonlitBegonia_2:dazeBuildup': {
    sheet: 'Qingyi',
    name: 'EXSpecialAttackMoonlitBegonia_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackMoonlitBegonia_2',
    },
  },
  'EXSpecialAttackMoonlitBegonia_2:anomBuildup': {
    sheet: 'Qingyi',
    name: 'EXSpecialAttackMoonlitBegonia_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackMoonlitBegonia_2',
    },
  },
  'ChainAttackTranquilSerenade_0:standardDmg': {
    sheet: 'Qingyi',
    name: 'ChainAttackTranquilSerenade_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'chain',
      skillType1: 'chainSkill',
      name: 'ChainAttackTranquilSerenade_0',
    },
  },
  'ChainAttackTranquilSerenade_0:dazeBuildup': {
    sheet: 'Qingyi',
    name: 'ChainAttackTranquilSerenade_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'chain',
      skillType1: 'chainSkill',
      name: 'ChainAttackTranquilSerenade_0',
    },
  },
  'ChainAttackTranquilSerenade_0:anomBuildup': {
    sheet: 'Qingyi',
    name: 'ChainAttackTranquilSerenade_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'chain',
      skillType1: 'chainSkill',
      name: 'ChainAttackTranquilSerenade_0',
    },
  },
  'UltimateEightSoundsOfGanzhou_0:standardDmg': {
    sheet: 'Qingyi',
    name: 'UltimateEightSoundsOfGanzhou_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'ult',
      skillType1: 'chainSkill',
      name: 'UltimateEightSoundsOfGanzhou_0',
    },
  },
  'UltimateEightSoundsOfGanzhou_0:dazeBuildup': {
    sheet: 'Qingyi',
    name: 'UltimateEightSoundsOfGanzhou_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'ult',
      skillType1: 'chainSkill',
      name: 'UltimateEightSoundsOfGanzhou_0',
    },
  },
  'UltimateEightSoundsOfGanzhou_0:anomBuildup': {
    sheet: 'Qingyi',
    name: 'UltimateEightSoundsOfGanzhou_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'ult',
      skillType1: 'chainSkill',
      name: 'UltimateEightSoundsOfGanzhou_0',
    },
  },
  'QuickAssistWindThroughThePines_0:standardDmg': {
    sheet: 'Qingyi',
    name: 'QuickAssistWindThroughThePines_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'quickAssist',
      skillType1: 'assistSkill',
      name: 'QuickAssistWindThroughThePines_0',
    },
  },
  'QuickAssistWindThroughThePines_0:dazeBuildup': {
    sheet: 'Qingyi',
    name: 'QuickAssistWindThroughThePines_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'quickAssist',
      skillType1: 'assistSkill',
      name: 'QuickAssistWindThroughThePines_0',
    },
  },
  'QuickAssistWindThroughThePines_0:anomBuildup': {
    sheet: 'Qingyi',
    name: 'QuickAssistWindThroughThePines_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'quickAssist',
      skillType1: 'assistSkill',
      name: 'QuickAssistWindThroughThePines_0',
    },
  },
  'DefensiveAssistGracefulEmbellishment_0:standardDmg': {
    sheet: 'Qingyi',
    name: 'DefensiveAssistGracefulEmbellishment_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistGracefulEmbellishment_0',
    },
  },
  'DefensiveAssistGracefulEmbellishment_0:dazeBuildup': {
    sheet: 'Qingyi',
    name: 'DefensiveAssistGracefulEmbellishment_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistGracefulEmbellishment_0',
    },
  },
  'DefensiveAssistGracefulEmbellishment_0:anomBuildup': {
    sheet: 'Qingyi',
    name: 'DefensiveAssistGracefulEmbellishment_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistGracefulEmbellishment_0',
    },
  },
  'DefensiveAssistGracefulEmbellishment_1:standardDmg': {
    sheet: 'Qingyi',
    name: 'DefensiveAssistGracefulEmbellishment_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistGracefulEmbellishment_1',
    },
  },
  'DefensiveAssistGracefulEmbellishment_1:dazeBuildup': {
    sheet: 'Qingyi',
    name: 'DefensiveAssistGracefulEmbellishment_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistGracefulEmbellishment_1',
    },
  },
  'DefensiveAssistGracefulEmbellishment_1:anomBuildup': {
    sheet: 'Qingyi',
    name: 'DefensiveAssistGracefulEmbellishment_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistGracefulEmbellishment_1',
    },
  },
  'DefensiveAssistGracefulEmbellishment_2:standardDmg': {
    sheet: 'Qingyi',
    name: 'DefensiveAssistGracefulEmbellishment_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistGracefulEmbellishment_2',
    },
  },
  'DefensiveAssistGracefulEmbellishment_2:dazeBuildup': {
    sheet: 'Qingyi',
    name: 'DefensiveAssistGracefulEmbellishment_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistGracefulEmbellishment_2',
    },
  },
  'DefensiveAssistGracefulEmbellishment_2:anomBuildup': {
    sheet: 'Qingyi',
    name: 'DefensiveAssistGracefulEmbellishment_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistGracefulEmbellishment_2',
    },
  },
  'AssistFollowUpSongOfTheClearRiver_0:standardDmg': {
    sheet: 'Qingyi',
    name: 'AssistFollowUpSongOfTheClearRiver_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'assistFollowUp',
      skillType1: 'assistSkill',
      name: 'AssistFollowUpSongOfTheClearRiver_0',
    },
  },
  'AssistFollowUpSongOfTheClearRiver_0:dazeBuildup': {
    sheet: 'Qingyi',
    name: 'AssistFollowUpSongOfTheClearRiver_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'assistFollowUp',
      skillType1: 'assistSkill',
      name: 'AssistFollowUpSongOfTheClearRiver_0',
    },
  },
  'AssistFollowUpSongOfTheClearRiver_0:anomBuildup': {
    sheet: 'Qingyi',
    name: 'AssistFollowUpSongOfTheClearRiver_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'assistFollowUp',
      skillType1: 'assistSkill',
      name: 'AssistFollowUpSongOfTheClearRiver_0',
    },
  },
  m4_shield: {
    sheet: 'Qingyi',
    name: 'm4_shield',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'shield',
      sheet: 'Qingyi',
      name: 'm4_shield',
    },
  },
} as const
