// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Qingyi',
    name: 'standardDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'standardDmgBase',
      sheet: 'Qingyi',
      attribute: 'electric',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Qingyi',
    name: 'anomalyDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_electric: {
    sheet: 'Qingyi',
    name: 'disorderDmgInst_electric',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'disorder',
      name: 'disorderDmgInst_electric',
    },
  },
  vortexDmgInst_electric: {
    sheet: 'Qingyi',
    name: 'vortexDmgInst_electric',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'vortex',
      name: 'vortexDmgInst_electric',
    },
  },
  abloomDmgInst: {
    sheet: 'Qingyi',
    name: 'abloomDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Qingyi',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Qingyi',
      attribute: 'electric',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Qingyi',
    name: 'dazeInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'dazeBuildupBase',
      sheet: 'Qingyi',
      attribute: 'electric',
      name: 'dazeInst',
    },
  },
  BasicAttackPenultimate_0: {
    sheet: 'Qingyi',
    name: 'BasicAttackPenultimate_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Qingyi',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackPenultimate_0',
    },
  },
  BasicAttackPenultimate_1: {
    sheet: 'Qingyi',
    name: 'BasicAttackPenultimate_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Qingyi',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackPenultimate_1',
    },
  },
  BasicAttackPenultimate_2: {
    sheet: 'Qingyi',
    name: 'BasicAttackPenultimate_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Qingyi',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackPenultimate_2',
    },
  },
  BasicAttackPenultimate_3: {
    sheet: 'Qingyi',
    name: 'BasicAttackPenultimate_3',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPenultimate_3',
    },
  },
  BasicAttackPenultimate_4: {
    sheet: 'Qingyi',
    name: 'BasicAttackPenultimate_4',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPenultimate_4',
    },
  },
  BasicAttackPenultimate_5: {
    sheet: 'Qingyi',
    name: 'BasicAttackPenultimate_5',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPenultimate_5',
    },
  },
  BasicAttackEnchantedBlossoms_0: {
    sheet: 'Qingyi',
    name: 'BasicAttackEnchantedBlossoms_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEnchantedBlossoms_0',
    },
  },
  BasicAttackEnchantedMoonlitBlossoms_0: {
    sheet: 'Qingyi',
    name: 'BasicAttackEnchantedMoonlitBlossoms_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEnchantedMoonlitBlossoms_0',
    },
  },
  BasicAttackEnchantedMoonlitBlossoms_1: {
    sheet: 'Qingyi',
    name: 'BasicAttackEnchantedMoonlitBlossoms_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEnchantedMoonlitBlossoms_1',
    },
  },
  DashAttackBreach_0: {
    sheet: 'Qingyi',
    name: 'DashAttackBreach_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Qingyi',
      damageType1: 'dash',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttackBreach_0',
    },
  },
  DodgeCounterLingeringSentiments_0: {
    sheet: 'Qingyi',
    name: 'DodgeCounterLingeringSentiments_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterLingeringSentiments_0',
    },
  },
  SpecialAttackSunlitGlory_0: {
    sheet: 'Qingyi',
    name: 'SpecialAttackSunlitGlory_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackSunlitGlory_0',
    },
  },
  EXSpecialAttackMoonlitBegonia_0: {
    sheet: 'Qingyi',
    name: 'EXSpecialAttackMoonlitBegonia_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackMoonlitBegonia_0',
    },
  },
  EXSpecialAttackMoonlitBegonia_1: {
    sheet: 'Qingyi',
    name: 'EXSpecialAttackMoonlitBegonia_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackMoonlitBegonia_1',
    },
  },
  EXSpecialAttackMoonlitBegonia_2: {
    sheet: 'Qingyi',
    name: 'EXSpecialAttackMoonlitBegonia_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackMoonlitBegonia_2',
    },
  },
  ChainAttackTranquilSerenade_0: {
    sheet: 'Qingyi',
    name: 'ChainAttackTranquilSerenade_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackTranquilSerenade_0',
    },
  },
  UltimateEightSoundsOfGanzhou_0: {
    sheet: 'Qingyi',
    name: 'UltimateEightSoundsOfGanzhou_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateEightSoundsOfGanzhou_0',
    },
  },
  QuickAssistWindThroughThePines_0: {
    sheet: 'Qingyi',
    name: 'QuickAssistWindThroughThePines_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistWindThroughThePines_0',
    },
  },
  DefensiveAssistGracefulEmbellishment_0: {
    sheet: 'Qingyi',
    name: 'DefensiveAssistGracefulEmbellishment_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistGracefulEmbellishment_0',
    },
  },
  DefensiveAssistGracefulEmbellishment_1: {
    sheet: 'Qingyi',
    name: 'DefensiveAssistGracefulEmbellishment_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistGracefulEmbellishment_1',
    },
  },
  DefensiveAssistGracefulEmbellishment_2: {
    sheet: 'Qingyi',
    name: 'DefensiveAssistGracefulEmbellishment_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistGracefulEmbellishment_2',
    },
  },
  AssistFollowUpSongOfTheClearRiver_0: {
    sheet: 'Qingyi',
    name: 'AssistFollowUpSongOfTheClearRiver_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Qingyi',
      attribute: 'electric',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpSongOfTheClearRiver_0',
    },
  },
  m4_shield: {
    sheet: 'Qingyi',
    name: 'm4_shield',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'shieldBase',
      sheet: 'Qingyi',
      name: 'm4_shield',
    },
  },
} as const
