// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Ben',
    name: 'standardDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ben',
      attribute: 'fire',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Ben',
    name: 'anomalyDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_fire: {
    sheet: 'Ben',
    name: 'disorderDmgInst_fire',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'disorder',
      name: 'disorderDmgInst_fire',
    },
  },
  vortexDmgInst_fire: {
    sheet: 'Ben',
    name: 'vortexDmgInst_fire',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'vortex',
      name: 'vortexDmgInst_fire',
    },
  },
  abloomDmgInst: {
    sheet: 'Ben',
    name: 'abloomDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Ben',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ben',
      attribute: 'fire',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Ben',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ben',
      attribute: 'fire',
      name: 'dazeInst',
    },
  },
  'BasicAttackDebtReconciliation_0:standardDmg': {
    sheet: 'Ben',
    name: 'BasicAttackDebtReconciliation_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ben',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackDebtReconciliation_0',
    },
  },
  'BasicAttackDebtReconciliation_0:dazeBuildup': {
    sheet: 'Ben',
    name: 'BasicAttackDebtReconciliation_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ben',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackDebtReconciliation_0',
    },
  },
  'BasicAttackDebtReconciliation_0:anomBuildup': {
    sheet: 'Ben',
    name: 'BasicAttackDebtReconciliation_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ben',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackDebtReconciliation_0',
    },
  },
  'BasicAttackDebtReconciliation_1:standardDmg': {
    sheet: 'Ben',
    name: 'BasicAttackDebtReconciliation_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ben',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackDebtReconciliation_1',
    },
  },
  'BasicAttackDebtReconciliation_1:dazeBuildup': {
    sheet: 'Ben',
    name: 'BasicAttackDebtReconciliation_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ben',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackDebtReconciliation_1',
    },
  },
  'BasicAttackDebtReconciliation_1:anomBuildup': {
    sheet: 'Ben',
    name: 'BasicAttackDebtReconciliation_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ben',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackDebtReconciliation_1',
    },
  },
  'BasicAttackDebtReconciliation_2:standardDmg': {
    sheet: 'Ben',
    name: 'BasicAttackDebtReconciliation_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ben',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackDebtReconciliation_2',
    },
  },
  'BasicAttackDebtReconciliation_2:dazeBuildup': {
    sheet: 'Ben',
    name: 'BasicAttackDebtReconciliation_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ben',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackDebtReconciliation_2',
    },
  },
  'BasicAttackDebtReconciliation_2:anomBuildup': {
    sheet: 'Ben',
    name: 'BasicAttackDebtReconciliation_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ben',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackDebtReconciliation_2',
    },
  },
  'DashAttackIncomingExpense_0:standardDmg': {
    sheet: 'Ben',
    name: 'DashAttackIncomingExpense_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ben',
      damageType1: 'dash',
      attribute: 'physical',
      skillType1: 'dodgeSkill',
      name: 'DashAttackIncomingExpense_0',
    },
  },
  'DashAttackIncomingExpense_0:dazeBuildup': {
    sheet: 'Ben',
    name: 'DashAttackIncomingExpense_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ben',
      damageType1: 'dash',
      attribute: 'physical',
      skillType1: 'dodgeSkill',
      name: 'DashAttackIncomingExpense_0',
    },
  },
  'DashAttackIncomingExpense_0:anomBuildup': {
    sheet: 'Ben',
    name: 'DashAttackIncomingExpense_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ben',
      damageType1: 'dash',
      attribute: 'physical',
      skillType1: 'dodgeSkill',
      name: 'DashAttackIncomingExpense_0',
    },
  },
  'DodgeCounterAccountsSettled_0:standardDmg': {
    sheet: 'Ben',
    name: 'DodgeCounterAccountsSettled_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'dodgeCounter',
      skillType1: 'dodgeSkill',
      name: 'DodgeCounterAccountsSettled_0',
    },
  },
  'DodgeCounterAccountsSettled_0:dazeBuildup': {
    sheet: 'Ben',
    name: 'DodgeCounterAccountsSettled_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'dodgeCounter',
      skillType1: 'dodgeSkill',
      name: 'DodgeCounterAccountsSettled_0',
    },
  },
  'DodgeCounterAccountsSettled_0:anomBuildup': {
    sheet: 'Ben',
    name: 'DodgeCounterAccountsSettled_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'dodgeCounter',
      skillType1: 'dodgeSkill',
      name: 'DodgeCounterAccountsSettled_0',
    },
  },
  'SpecialAttackFiscalFist_0:standardDmg': {
    sheet: 'Ben',
    name: 'SpecialAttackFiscalFist_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ben',
      damageType1: 'special',
      attribute: 'physical',
      skillType1: 'specialSkill',
      name: 'SpecialAttackFiscalFist_0',
    },
  },
  'SpecialAttackFiscalFist_0:dazeBuildup': {
    sheet: 'Ben',
    name: 'SpecialAttackFiscalFist_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ben',
      damageType1: 'special',
      attribute: 'physical',
      skillType1: 'specialSkill',
      name: 'SpecialAttackFiscalFist_0',
    },
  },
  'SpecialAttackFiscalFist_0:anomBuildup': {
    sheet: 'Ben',
    name: 'SpecialAttackFiscalFist_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ben',
      damageType1: 'special',
      attribute: 'physical',
      skillType1: 'specialSkill',
      name: 'SpecialAttackFiscalFist_0',
    },
  },
  'SpecialAttackFiscalFist_1:standardDmg': {
    sheet: 'Ben',
    name: 'SpecialAttackFiscalFist_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ben',
      damageType1: 'special',
      attribute: 'physical',
      skillType1: 'specialSkill',
      name: 'SpecialAttackFiscalFist_1',
    },
  },
  'SpecialAttackFiscalFist_1:dazeBuildup': {
    sheet: 'Ben',
    name: 'SpecialAttackFiscalFist_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ben',
      damageType1: 'special',
      attribute: 'physical',
      skillType1: 'specialSkill',
      name: 'SpecialAttackFiscalFist_1',
    },
  },
  'SpecialAttackFiscalFist_1:anomBuildup': {
    sheet: 'Ben',
    name: 'SpecialAttackFiscalFist_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ben',
      damageType1: 'special',
      attribute: 'physical',
      skillType1: 'specialSkill',
      name: 'SpecialAttackFiscalFist_1',
    },
  },
  'EXSpecialAttackCashflowCounter_0:standardDmg': {
    sheet: 'Ben',
    name: 'EXSpecialAttackCashflowCounter_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackCashflowCounter_0',
    },
  },
  'EXSpecialAttackCashflowCounter_0:dazeBuildup': {
    sheet: 'Ben',
    name: 'EXSpecialAttackCashflowCounter_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackCashflowCounter_0',
    },
  },
  'EXSpecialAttackCashflowCounter_0:anomBuildup': {
    sheet: 'Ben',
    name: 'EXSpecialAttackCashflowCounter_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackCashflowCounter_0',
    },
  },
  'EXSpecialAttackCashflowCounter_1:standardDmg': {
    sheet: 'Ben',
    name: 'EXSpecialAttackCashflowCounter_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackCashflowCounter_1',
    },
  },
  'EXSpecialAttackCashflowCounter_1:dazeBuildup': {
    sheet: 'Ben',
    name: 'EXSpecialAttackCashflowCounter_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackCashflowCounter_1',
    },
  },
  'EXSpecialAttackCashflowCounter_1:anomBuildup': {
    sheet: 'Ben',
    name: 'EXSpecialAttackCashflowCounter_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackCashflowCounter_1',
    },
  },
  'EXSpecialAttackCashflowCounter_2:standardDmg': {
    sheet: 'Ben',
    name: 'EXSpecialAttackCashflowCounter_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackCashflowCounter_2',
    },
  },
  'EXSpecialAttackCashflowCounter_2:dazeBuildup': {
    sheet: 'Ben',
    name: 'EXSpecialAttackCashflowCounter_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackCashflowCounter_2',
    },
  },
  'EXSpecialAttackCashflowCounter_2:anomBuildup': {
    sheet: 'Ben',
    name: 'EXSpecialAttackCashflowCounter_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackCashflowCounter_2',
    },
  },
  'EXSpecialAttackCashflowCounter_3:standardDmg': {
    sheet: 'Ben',
    name: 'EXSpecialAttackCashflowCounter_3:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackCashflowCounter_3',
    },
  },
  'EXSpecialAttackCashflowCounter_3:dazeBuildup': {
    sheet: 'Ben',
    name: 'EXSpecialAttackCashflowCounter_3:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackCashflowCounter_3',
    },
  },
  'EXSpecialAttackCashflowCounter_3:anomBuildup': {
    sheet: 'Ben',
    name: 'EXSpecialAttackCashflowCounter_3:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackCashflowCounter_3',
    },
  },
  'ChainAttackSignedAndSealed_0:standardDmg': {
    sheet: 'Ben',
    name: 'ChainAttackSignedAndSealed_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'chain',
      skillType1: 'chainSkill',
      name: 'ChainAttackSignedAndSealed_0',
    },
  },
  'ChainAttackSignedAndSealed_0:dazeBuildup': {
    sheet: 'Ben',
    name: 'ChainAttackSignedAndSealed_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'chain',
      skillType1: 'chainSkill',
      name: 'ChainAttackSignedAndSealed_0',
    },
  },
  'ChainAttackSignedAndSealed_0:anomBuildup': {
    sheet: 'Ben',
    name: 'ChainAttackSignedAndSealed_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'chain',
      skillType1: 'chainSkill',
      name: 'ChainAttackSignedAndSealed_0',
    },
  },
  'UltimateCompletePayback_0:standardDmg': {
    sheet: 'Ben',
    name: 'UltimateCompletePayback_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'ult',
      skillType1: 'chainSkill',
      name: 'UltimateCompletePayback_0',
    },
  },
  'UltimateCompletePayback_0:dazeBuildup': {
    sheet: 'Ben',
    name: 'UltimateCompletePayback_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'ult',
      skillType1: 'chainSkill',
      name: 'UltimateCompletePayback_0',
    },
  },
  'UltimateCompletePayback_0:anomBuildup': {
    sheet: 'Ben',
    name: 'UltimateCompletePayback_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'ult',
      skillType1: 'chainSkill',
      name: 'UltimateCompletePayback_0',
    },
  },
  'QuickAssistJointAccount_0:standardDmg': {
    sheet: 'Ben',
    name: 'QuickAssistJointAccount_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'quickAssist',
      skillType1: 'assistSkill',
      name: 'QuickAssistJointAccount_0',
    },
  },
  'QuickAssistJointAccount_0:dazeBuildup': {
    sheet: 'Ben',
    name: 'QuickAssistJointAccount_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'quickAssist',
      skillType1: 'assistSkill',
      name: 'QuickAssistJointAccount_0',
    },
  },
  'QuickAssistJointAccount_0:anomBuildup': {
    sheet: 'Ben',
    name: 'QuickAssistJointAccount_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'quickAssist',
      skillType1: 'assistSkill',
      name: 'QuickAssistJointAccount_0',
    },
  },
  'DefensiveAssistRiskAllocation_0:standardDmg': {
    sheet: 'Ben',
    name: 'DefensiveAssistRiskAllocation_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistRiskAllocation_0',
    },
  },
  'DefensiveAssistRiskAllocation_0:dazeBuildup': {
    sheet: 'Ben',
    name: 'DefensiveAssistRiskAllocation_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistRiskAllocation_0',
    },
  },
  'DefensiveAssistRiskAllocation_0:anomBuildup': {
    sheet: 'Ben',
    name: 'DefensiveAssistRiskAllocation_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistRiskAllocation_0',
    },
  },
  'DefensiveAssistRiskAllocation_1:standardDmg': {
    sheet: 'Ben',
    name: 'DefensiveAssistRiskAllocation_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistRiskAllocation_1',
    },
  },
  'DefensiveAssistRiskAllocation_1:dazeBuildup': {
    sheet: 'Ben',
    name: 'DefensiveAssistRiskAllocation_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistRiskAllocation_1',
    },
  },
  'DefensiveAssistRiskAllocation_1:anomBuildup': {
    sheet: 'Ben',
    name: 'DefensiveAssistRiskAllocation_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistRiskAllocation_1',
    },
  },
  'DefensiveAssistRiskAllocation_2:standardDmg': {
    sheet: 'Ben',
    name: 'DefensiveAssistRiskAllocation_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistRiskAllocation_2',
    },
  },
  'DefensiveAssistRiskAllocation_2:dazeBuildup': {
    sheet: 'Ben',
    name: 'DefensiveAssistRiskAllocation_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistRiskAllocation_2',
    },
  },
  'DefensiveAssistRiskAllocation_2:anomBuildup': {
    sheet: 'Ben',
    name: 'DefensiveAssistRiskAllocation_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistRiskAllocation_2',
    },
  },
  'AssistFollowUpDontBreakContract_0:standardDmg': {
    sheet: 'Ben',
    name: 'AssistFollowUpDontBreakContract_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'assistFollowUp',
      skillType1: 'assistSkill',
      name: 'AssistFollowUpDontBreakContract_0',
    },
  },
  'AssistFollowUpDontBreakContract_0:dazeBuildup': {
    sheet: 'Ben',
    name: 'AssistFollowUpDontBreakContract_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'assistFollowUp',
      skillType1: 'assistSkill',
      name: 'AssistFollowUpDontBreakContract_0',
    },
  },
  'AssistFollowUpDontBreakContract_0:anomBuildup': {
    sheet: 'Ben',
    name: 'AssistFollowUpDontBreakContract_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'assistFollowUp',
      skillType1: 'assistSkill',
      name: 'AssistFollowUpDontBreakContract_0',
    },
  },
  special_shield: {
    sheet: 'Ben',
    name: 'special_shield',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'shield',
      sheet: 'Ben',
      name: 'special_shield',
    },
  },
  core_shield: {
    sheet: 'Ben',
    name: 'core_shield',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'shield',
      sheet: 'Ben',
      name: 'core_shield',
    },
  },
  m2_dmg: {
    sheet: 'Ben',
    name: 'm2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ben',
      damageType1: 'elemental',
      name: 'm2_dmg',
    },
  },
} as const
