// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Ben',
    name: 'standardDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ben',
      attribute: 'fire',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Ben',
    name: 'anomalyDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_fire: {
    sheet: 'Ben',
    name: 'disorderDmgInst_fire',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'disorder',
      name: 'disorderDmgInst_fire',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Ben',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ben',
      attribute: 'fire',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Ben',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ben',
      attribute: 'fire',
      name: 'dazeInst',
    },
  },
  BasicAttackDebtReconciliation_0_dmg: {
    sheet: 'Ben',
    name: 'BasicAttackDebtReconciliation_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ben',
      damageType1: 'basic',
      attribute: 'physical',
      name: 'BasicAttackDebtReconciliation_0_dmg',
    },
  },
  BasicAttackDebtReconciliation_0_daze: {
    sheet: 'Ben',
    name: 'BasicAttackDebtReconciliation_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ben',
      damageType1: 'basic',
      attribute: 'physical',
      name: 'BasicAttackDebtReconciliation_0_daze',
    },
  },
  BasicAttackDebtReconciliation_0_anomBuildup: {
    sheet: 'Ben',
    name: 'BasicAttackDebtReconciliation_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ben',
      damageType1: 'basic',
      attribute: 'physical',
      name: 'BasicAttackDebtReconciliation_0_anomBuildup',
    },
  },
  BasicAttackDebtReconciliation_1_dmg: {
    sheet: 'Ben',
    name: 'BasicAttackDebtReconciliation_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ben',
      damageType1: 'basic',
      attribute: 'physical',
      name: 'BasicAttackDebtReconciliation_1_dmg',
    },
  },
  BasicAttackDebtReconciliation_1_daze: {
    sheet: 'Ben',
    name: 'BasicAttackDebtReconciliation_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ben',
      damageType1: 'basic',
      attribute: 'physical',
      name: 'BasicAttackDebtReconciliation_1_daze',
    },
  },
  BasicAttackDebtReconciliation_1_anomBuildup: {
    sheet: 'Ben',
    name: 'BasicAttackDebtReconciliation_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ben',
      damageType1: 'basic',
      attribute: 'physical',
      name: 'BasicAttackDebtReconciliation_1_anomBuildup',
    },
  },
  BasicAttackDebtReconciliation_2_dmg: {
    sheet: 'Ben',
    name: 'BasicAttackDebtReconciliation_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ben',
      damageType1: 'basic',
      attribute: 'physical',
      name: 'BasicAttackDebtReconciliation_2_dmg',
    },
  },
  BasicAttackDebtReconciliation_2_daze: {
    sheet: 'Ben',
    name: 'BasicAttackDebtReconciliation_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ben',
      damageType1: 'basic',
      attribute: 'physical',
      name: 'BasicAttackDebtReconciliation_2_daze',
    },
  },
  BasicAttackDebtReconciliation_2_anomBuildup: {
    sheet: 'Ben',
    name: 'BasicAttackDebtReconciliation_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ben',
      damageType1: 'basic',
      attribute: 'physical',
      name: 'BasicAttackDebtReconciliation_2_anomBuildup',
    },
  },
  DashAttackIncomingExpense_0_dmg: {
    sheet: 'Ben',
    name: 'DashAttackIncomingExpense_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ben',
      damageType1: 'dash',
      attribute: 'physical',
      name: 'DashAttackIncomingExpense_0_dmg',
    },
  },
  DashAttackIncomingExpense_0_daze: {
    sheet: 'Ben',
    name: 'DashAttackIncomingExpense_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ben',
      damageType1: 'dash',
      attribute: 'physical',
      name: 'DashAttackIncomingExpense_0_daze',
    },
  },
  DashAttackIncomingExpense_0_anomBuildup: {
    sheet: 'Ben',
    name: 'DashAttackIncomingExpense_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ben',
      damageType1: 'dash',
      attribute: 'physical',
      name: 'DashAttackIncomingExpense_0_anomBuildup',
    },
  },
  DodgeCounterAccountsSettled_0_dmg: {
    sheet: 'Ben',
    name: 'DodgeCounterAccountsSettled_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterAccountsSettled_0_dmg',
    },
  },
  DodgeCounterAccountsSettled_0_daze: {
    sheet: 'Ben',
    name: 'DodgeCounterAccountsSettled_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterAccountsSettled_0_daze',
    },
  },
  DodgeCounterAccountsSettled_0_anomBuildup: {
    sheet: 'Ben',
    name: 'DodgeCounterAccountsSettled_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterAccountsSettled_0_anomBuildup',
    },
  },
  SpecialAttackFiscalFist_0_dmg: {
    sheet: 'Ben',
    name: 'SpecialAttackFiscalFist_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ben',
      damageType1: 'special',
      attribute: 'physical',
      name: 'SpecialAttackFiscalFist_0_dmg',
    },
  },
  SpecialAttackFiscalFist_0_daze: {
    sheet: 'Ben',
    name: 'SpecialAttackFiscalFist_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ben',
      damageType1: 'special',
      attribute: 'physical',
      name: 'SpecialAttackFiscalFist_0_daze',
    },
  },
  SpecialAttackFiscalFist_0_anomBuildup: {
    sheet: 'Ben',
    name: 'SpecialAttackFiscalFist_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ben',
      damageType1: 'special',
      attribute: 'physical',
      name: 'SpecialAttackFiscalFist_0_anomBuildup',
    },
  },
  SpecialAttackFiscalFist_1_dmg: {
    sheet: 'Ben',
    name: 'SpecialAttackFiscalFist_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ben',
      damageType1: 'special',
      attribute: 'physical',
      name: 'SpecialAttackFiscalFist_1_dmg',
    },
  },
  SpecialAttackFiscalFist_1_daze: {
    sheet: 'Ben',
    name: 'SpecialAttackFiscalFist_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ben',
      damageType1: 'special',
      attribute: 'physical',
      name: 'SpecialAttackFiscalFist_1_daze',
    },
  },
  SpecialAttackFiscalFist_1_anomBuildup: {
    sheet: 'Ben',
    name: 'SpecialAttackFiscalFist_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ben',
      damageType1: 'special',
      attribute: 'physical',
      name: 'SpecialAttackFiscalFist_1_anomBuildup',
    },
  },
  EXSpecialAttackCashflowCounter_0_dmg: {
    sheet: 'Ben',
    name: 'EXSpecialAttackCashflowCounter_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackCashflowCounter_0_dmg',
    },
  },
  EXSpecialAttackCashflowCounter_0_daze: {
    sheet: 'Ben',
    name: 'EXSpecialAttackCashflowCounter_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackCashflowCounter_0_daze',
    },
  },
  EXSpecialAttackCashflowCounter_0_anomBuildup: {
    sheet: 'Ben',
    name: 'EXSpecialAttackCashflowCounter_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackCashflowCounter_0_anomBuildup',
    },
  },
  EXSpecialAttackCashflowCounter_1_dmg: {
    sheet: 'Ben',
    name: 'EXSpecialAttackCashflowCounter_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackCashflowCounter_1_dmg',
    },
  },
  EXSpecialAttackCashflowCounter_1_daze: {
    sheet: 'Ben',
    name: 'EXSpecialAttackCashflowCounter_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackCashflowCounter_1_daze',
    },
  },
  EXSpecialAttackCashflowCounter_1_anomBuildup: {
    sheet: 'Ben',
    name: 'EXSpecialAttackCashflowCounter_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackCashflowCounter_1_anomBuildup',
    },
  },
  EXSpecialAttackCashflowCounter_2_dmg: {
    sheet: 'Ben',
    name: 'EXSpecialAttackCashflowCounter_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'special',
      name: 'EXSpecialAttackCashflowCounter_2_dmg',
    },
  },
  EXSpecialAttackCashflowCounter_2_daze: {
    sheet: 'Ben',
    name: 'EXSpecialAttackCashflowCounter_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'special',
      name: 'EXSpecialAttackCashflowCounter_2_daze',
    },
  },
  EXSpecialAttackCashflowCounter_2_anomBuildup: {
    sheet: 'Ben',
    name: 'EXSpecialAttackCashflowCounter_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'special',
      name: 'EXSpecialAttackCashflowCounter_2_anomBuildup',
    },
  },
  EXSpecialAttackCashflowCounter_3_dmg: {
    sheet: 'Ben',
    name: 'EXSpecialAttackCashflowCounter_3_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackCashflowCounter_3_dmg',
    },
  },
  EXSpecialAttackCashflowCounter_3_daze: {
    sheet: 'Ben',
    name: 'EXSpecialAttackCashflowCounter_3_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackCashflowCounter_3_daze',
    },
  },
  EXSpecialAttackCashflowCounter_3_anomBuildup: {
    sheet: 'Ben',
    name: 'EXSpecialAttackCashflowCounter_3_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackCashflowCounter_3_anomBuildup',
    },
  },
  ChainAttackSignedAndSealed_0_dmg: {
    sheet: 'Ben',
    name: 'ChainAttackSignedAndSealed_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackSignedAndSealed_0_dmg',
    },
  },
  ChainAttackSignedAndSealed_0_daze: {
    sheet: 'Ben',
    name: 'ChainAttackSignedAndSealed_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackSignedAndSealed_0_daze',
    },
  },
  ChainAttackSignedAndSealed_0_anomBuildup: {
    sheet: 'Ben',
    name: 'ChainAttackSignedAndSealed_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackSignedAndSealed_0_anomBuildup',
    },
  },
  UltimateCompletePayback_0_dmg: {
    sheet: 'Ben',
    name: 'UltimateCompletePayback_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateCompletePayback_0_dmg',
    },
  },
  UltimateCompletePayback_0_daze: {
    sheet: 'Ben',
    name: 'UltimateCompletePayback_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateCompletePayback_0_daze',
    },
  },
  UltimateCompletePayback_0_anomBuildup: {
    sheet: 'Ben',
    name: 'UltimateCompletePayback_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateCompletePayback_0_anomBuildup',
    },
  },
  QuickAssistJointAccount_0_dmg: {
    sheet: 'Ben',
    name: 'QuickAssistJointAccount_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistJointAccount_0_dmg',
    },
  },
  QuickAssistJointAccount_0_daze: {
    sheet: 'Ben',
    name: 'QuickAssistJointAccount_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistJointAccount_0_daze',
    },
  },
  QuickAssistJointAccount_0_anomBuildup: {
    sheet: 'Ben',
    name: 'QuickAssistJointAccount_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistJointAccount_0_anomBuildup',
    },
  },
  DefensiveAssistRiskAllocation_0_dmg: {
    sheet: 'Ben',
    name: 'DefensiveAssistRiskAllocation_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistRiskAllocation_0_dmg',
    },
  },
  DefensiveAssistRiskAllocation_0_daze: {
    sheet: 'Ben',
    name: 'DefensiveAssistRiskAllocation_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistRiskAllocation_0_daze',
    },
  },
  DefensiveAssistRiskAllocation_0_anomBuildup: {
    sheet: 'Ben',
    name: 'DefensiveAssistRiskAllocation_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistRiskAllocation_0_anomBuildup',
    },
  },
  DefensiveAssistRiskAllocation_1_dmg: {
    sheet: 'Ben',
    name: 'DefensiveAssistRiskAllocation_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistRiskAllocation_1_dmg',
    },
  },
  DefensiveAssistRiskAllocation_1_daze: {
    sheet: 'Ben',
    name: 'DefensiveAssistRiskAllocation_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistRiskAllocation_1_daze',
    },
  },
  DefensiveAssistRiskAllocation_1_anomBuildup: {
    sheet: 'Ben',
    name: 'DefensiveAssistRiskAllocation_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistRiskAllocation_1_anomBuildup',
    },
  },
  DefensiveAssistRiskAllocation_2_dmg: {
    sheet: 'Ben',
    name: 'DefensiveAssistRiskAllocation_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistRiskAllocation_2_dmg',
    },
  },
  DefensiveAssistRiskAllocation_2_daze: {
    sheet: 'Ben',
    name: 'DefensiveAssistRiskAllocation_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistRiskAllocation_2_daze',
    },
  },
  DefensiveAssistRiskAllocation_2_anomBuildup: {
    sheet: 'Ben',
    name: 'DefensiveAssistRiskAllocation_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistRiskAllocation_2_anomBuildup',
    },
  },
  AssistFollowUpDontBreakContract_0_dmg: {
    sheet: 'Ben',
    name: 'AssistFollowUpDontBreakContract_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpDontBreakContract_0_dmg',
    },
  },
  AssistFollowUpDontBreakContract_0_daze: {
    sheet: 'Ben',
    name: 'AssistFollowUpDontBreakContract_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpDontBreakContract_0_daze',
    },
  },
  AssistFollowUpDontBreakContract_0_anomBuildup: {
    sheet: 'Ben',
    name: 'AssistFollowUpDontBreakContract_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpDontBreakContract_0_anomBuildup',
    },
  },
  special_shield: {
    sheet: 'Ben',
    name: 'special_shield',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'shield',
      sheet: 'Ben',
      name: 'special_shield',
    },
  },
  core_shield: {
    sheet: 'Ben',
    name: 'core_shield',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'shield',
      sheet: 'Ben',
      name: 'core_shield',
    },
  },
  m2_dmg: {
    sheet: 'Ben',
    name: 'm2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ben',
      damageType1: 'elemental',
      name: 'm2_dmg',
    },
  },
} as const
