// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Ben',
    name: 'standardDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'standardDmgBase',
      sheet: 'Ben',
      attribute: 'fire',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Ben',
    name: 'anomalyDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_fire: {
    sheet: 'Ben',
    name: 'disorderDmgInst_fire',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'disorder',
      name: 'disorderDmgInst_fire',
    },
  },
  vortexDmgInst_fire: {
    sheet: 'Ben',
    name: 'vortexDmgInst_fire',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'vortex',
      name: 'vortexDmgInst_fire',
    },
  },
  abloomDmgInst: {
    sheet: 'Ben',
    name: 'abloomDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Ben',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Ben',
      attribute: 'fire',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Ben',
    name: 'dazeInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'dazeBuildupBase',
      sheet: 'Ben',
      attribute: 'fire',
      name: 'dazeInst',
    },
  },
  BasicAttackDebtReconciliation_0: {
    sheet: 'Ben',
    name: 'BasicAttackDebtReconciliation_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Ben',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackDebtReconciliation_0',
    },
  },
  BasicAttackDebtReconciliation_1: {
    sheet: 'Ben',
    name: 'BasicAttackDebtReconciliation_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Ben',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackDebtReconciliation_1',
    },
  },
  BasicAttackDebtReconciliation_2: {
    sheet: 'Ben',
    name: 'BasicAttackDebtReconciliation_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Ben',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackDebtReconciliation_2',
    },
  },
  DashAttackIncomingExpense_0: {
    sheet: 'Ben',
    name: 'DashAttackIncomingExpense_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Ben',
      damageType1: 'dash',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttackIncomingExpense_0',
    },
  },
  DodgeCounterAccountsSettled_0: {
    sheet: 'Ben',
    name: 'DodgeCounterAccountsSettled_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterAccountsSettled_0',
    },
  },
  SpecialAttackFiscalFist_0: {
    sheet: 'Ben',
    name: 'SpecialAttackFiscalFist_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Ben',
      damageType1: 'special',
      attribute: 'physical',
      skillType: 'specialSkill',
      name: 'SpecialAttackFiscalFist_0',
    },
  },
  SpecialAttackFiscalFist_1: {
    sheet: 'Ben',
    name: 'SpecialAttackFiscalFist_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Ben',
      damageType1: 'special',
      attribute: 'physical',
      skillType: 'specialSkill',
      name: 'SpecialAttackFiscalFist_1',
    },
  },
  EXSpecialAttackCashflowCounter_0: {
    sheet: 'Ben',
    name: 'EXSpecialAttackCashflowCounter_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackCashflowCounter_0',
    },
  },
  EXSpecialAttackCashflowCounter_1: {
    sheet: 'Ben',
    name: 'EXSpecialAttackCashflowCounter_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackCashflowCounter_1',
    },
  },
  EXSpecialAttackCashflowCounter_2: {
    sheet: 'Ben',
    name: 'EXSpecialAttackCashflowCounter_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackCashflowCounter_2',
    },
  },
  EXSpecialAttackCashflowCounter_3: {
    sheet: 'Ben',
    name: 'EXSpecialAttackCashflowCounter_3',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackCashflowCounter_3',
    },
  },
  ChainAttackSignedAndSealed_0: {
    sheet: 'Ben',
    name: 'ChainAttackSignedAndSealed_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackSignedAndSealed_0',
    },
  },
  UltimateCompletePayback_0: {
    sheet: 'Ben',
    name: 'UltimateCompletePayback_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateCompletePayback_0',
    },
  },
  QuickAssistJointAccount_0: {
    sheet: 'Ben',
    name: 'QuickAssistJointAccount_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistJointAccount_0',
    },
  },
  DefensiveAssistRiskAllocation_0: {
    sheet: 'Ben',
    name: 'DefensiveAssistRiskAllocation_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistRiskAllocation_0',
    },
  },
  DefensiveAssistRiskAllocation_1: {
    sheet: 'Ben',
    name: 'DefensiveAssistRiskAllocation_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistRiskAllocation_1',
    },
  },
  DefensiveAssistRiskAllocation_2: {
    sheet: 'Ben',
    name: 'DefensiveAssistRiskAllocation_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistRiskAllocation_2',
    },
  },
  AssistFollowUpDontBreakContract_0: {
    sheet: 'Ben',
    name: 'AssistFollowUpDontBreakContract_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Ben',
      attribute: 'fire',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpDontBreakContract_0',
    },
  },
  special_shield: {
    sheet: 'Ben',
    name: 'special_shield',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'shieldBase',
      sheet: 'Ben',
      name: 'special_shield',
    },
  },
  core_shield: {
    sheet: 'Ben',
    name: 'core_shield',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'shieldBase',
      sheet: 'Ben',
      name: 'core_shield',
    },
  },
  m2_dmg: {
    sheet: 'Ben',
    name: 'm2_dmg',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'standardDmgBase',
      sheet: 'Ben',
      damageType1: 'elemental',
      name: 'm2_dmg',
    },
  },
} as const
