// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Cissia',
    name: 'standardDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Cissia',
      attribute: 'electric',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Cissia',
    name: 'anomalyDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Cissia',
      attribute: 'electric',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_electric: {
    sheet: 'Cissia',
    name: 'disorderDmgInst_electric',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Cissia',
      attribute: 'electric',
      damageType1: 'disorder',
      name: 'disorderDmgInst_electric',
    },
  },
  vortexDmgInst_electric: {
    sheet: 'Cissia',
    name: 'vortexDmgInst_electric',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Cissia',
      attribute: 'electric',
      damageType1: 'vortex',
      name: 'vortexDmgInst_electric',
    },
  },
  abloomDmgInst: {
    sheet: 'Cissia',
    name: 'abloomDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Cissia',
      attribute: 'electric',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Cissia',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Cissia',
      attribute: 'electric',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Cissia',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Cissia',
      attribute: 'electric',
      name: 'dazeInst',
    },
  },
  'BasicAttackTongueFlick_0:standardDmg': {
    sheet: 'Cissia',
    name: 'BasicAttackTongueFlick_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Cissia',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackTongueFlick_0',
    },
  },
  'BasicAttackTongueFlick_0:dazeBuildup': {
    sheet: 'Cissia',
    name: 'BasicAttackTongueFlick_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Cissia',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackTongueFlick_0',
    },
  },
  'BasicAttackTongueFlick_0:anomBuildup': {
    sheet: 'Cissia',
    name: 'BasicAttackTongueFlick_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Cissia',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackTongueFlick_0',
    },
  },
  'BasicAttackTongueFlick_1:standardDmg': {
    sheet: 'Cissia',
    name: 'BasicAttackTongueFlick_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Cissia',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackTongueFlick_1',
    },
  },
  'BasicAttackTongueFlick_1:dazeBuildup': {
    sheet: 'Cissia',
    name: 'BasicAttackTongueFlick_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Cissia',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackTongueFlick_1',
    },
  },
  'BasicAttackTongueFlick_1:anomBuildup': {
    sheet: 'Cissia',
    name: 'BasicAttackTongueFlick_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Cissia',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackTongueFlick_1',
    },
  },
  'BasicAttackTongueFlick_2:standardDmg': {
    sheet: 'Cissia',
    name: 'BasicAttackTongueFlick_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Cissia',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackTongueFlick_2',
    },
  },
  'BasicAttackTongueFlick_2:dazeBuildup': {
    sheet: 'Cissia',
    name: 'BasicAttackTongueFlick_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Cissia',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackTongueFlick_2',
    },
  },
  'BasicAttackTongueFlick_2:anomBuildup': {
    sheet: 'Cissia',
    name: 'BasicAttackTongueFlick_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Cissia',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackTongueFlick_2',
    },
  },
  'BasicAttackTongueFlick_3:standardDmg': {
    sheet: 'Cissia',
    name: 'BasicAttackTongueFlick_3:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Cissia',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackTongueFlick_3',
    },
  },
  'BasicAttackTongueFlick_3:dazeBuildup': {
    sheet: 'Cissia',
    name: 'BasicAttackTongueFlick_3:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Cissia',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackTongueFlick_3',
    },
  },
  'BasicAttackTongueFlick_3:anomBuildup': {
    sheet: 'Cissia',
    name: 'BasicAttackTongueFlick_3:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Cissia',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackTongueFlick_3',
    },
  },
  'BasicAttackSerpentsKiss_0:standardDmg': {
    sheet: 'Cissia',
    name: 'BasicAttackSerpentsKiss_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Cissia',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackSerpentsKiss_0',
    },
  },
  'BasicAttackSerpentsKiss_0:dazeBuildup': {
    sheet: 'Cissia',
    name: 'BasicAttackSerpentsKiss_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Cissia',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackSerpentsKiss_0',
    },
  },
  'BasicAttackSerpentsKiss_0:anomBuildup': {
    sheet: 'Cissia',
    name: 'BasicAttackSerpentsKiss_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Cissia',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackSerpentsKiss_0',
    },
  },
  'CorrodeBone_0:standardDmg': {
    sheet: 'Cissia',
    name: 'CorrodeBone_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Cissia',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'CorrodeBone_0',
    },
  },
  'CorrodeBone_0:dazeBuildup': {
    sheet: 'Cissia',
    name: 'CorrodeBone_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Cissia',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'CorrodeBone_0',
    },
  },
  'CorrodeBone_0:anomBuildup': {
    sheet: 'Cissia',
    name: 'CorrodeBone_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Cissia',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'CorrodeBone_0',
    },
  },
  'DashAttackBiteMark_0:standardDmg': {
    sheet: 'Cissia',
    name: 'DashAttackBiteMark_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Cissia',
      attribute: 'electric',
      damageType1: 'dash',
      skillType1: 'dodgeSkill',
      name: 'DashAttackBiteMark_0',
    },
  },
  'DashAttackBiteMark_0:dazeBuildup': {
    sheet: 'Cissia',
    name: 'DashAttackBiteMark_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Cissia',
      attribute: 'electric',
      damageType1: 'dash',
      skillType1: 'dodgeSkill',
      name: 'DashAttackBiteMark_0',
    },
  },
  'DashAttackBiteMark_0:anomBuildup': {
    sheet: 'Cissia',
    name: 'DashAttackBiteMark_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Cissia',
      attribute: 'electric',
      damageType1: 'dash',
      skillType1: 'dodgeSkill',
      name: 'DashAttackBiteMark_0',
    },
  },
  'DodgeCounterBiteBack_0:standardDmg': {
    sheet: 'Cissia',
    name: 'DodgeCounterBiteBack_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Cissia',
      attribute: 'electric',
      damageType1: 'dodgeCounter',
      skillType1: 'dodgeSkill',
      name: 'DodgeCounterBiteBack_0',
    },
  },
  'DodgeCounterBiteBack_0:dazeBuildup': {
    sheet: 'Cissia',
    name: 'DodgeCounterBiteBack_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Cissia',
      attribute: 'electric',
      damageType1: 'dodgeCounter',
      skillType1: 'dodgeSkill',
      name: 'DodgeCounterBiteBack_0',
    },
  },
  'DodgeCounterBiteBack_0:anomBuildup': {
    sheet: 'Cissia',
    name: 'DodgeCounterBiteBack_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Cissia',
      attribute: 'electric',
      damageType1: 'dodgeCounter',
      skillType1: 'dodgeSkill',
      name: 'DodgeCounterBiteBack_0',
    },
  },
  'SpecialAttackBaredFangs_0:standardDmg': {
    sheet: 'Cissia',
    name: 'SpecialAttackBaredFangs_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Cissia',
      attribute: 'electric',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackBaredFangs_0',
    },
  },
  'SpecialAttackBaredFangs_0:dazeBuildup': {
    sheet: 'Cissia',
    name: 'SpecialAttackBaredFangs_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Cissia',
      attribute: 'electric',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackBaredFangs_0',
    },
  },
  'SpecialAttackBaredFangs_0:anomBuildup': {
    sheet: 'Cissia',
    name: 'SpecialAttackBaredFangs_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Cissia',
      attribute: 'electric',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackBaredFangs_0',
    },
  },
  'EXSpecialAttackVenomousBite_0:standardDmg': {
    sheet: 'Cissia',
    name: 'EXSpecialAttackVenomousBite_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Cissia',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackVenomousBite_0',
    },
  },
  'EXSpecialAttackVenomousBite_0:dazeBuildup': {
    sheet: 'Cissia',
    name: 'EXSpecialAttackVenomousBite_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Cissia',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackVenomousBite_0',
    },
  },
  'EXSpecialAttackVenomousBite_0:anomBuildup': {
    sheet: 'Cissia',
    name: 'EXSpecialAttackVenomousBite_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Cissia',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackVenomousBite_0',
    },
  },
  'EXSpecialAttackVenomousBite_1:standardDmg': {
    sheet: 'Cissia',
    name: 'EXSpecialAttackVenomousBite_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Cissia',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackVenomousBite_1',
    },
  },
  'EXSpecialAttackVenomousBite_1:dazeBuildup': {
    sheet: 'Cissia',
    name: 'EXSpecialAttackVenomousBite_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Cissia',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackVenomousBite_1',
    },
  },
  'EXSpecialAttackVenomousBite_1:anomBuildup': {
    sheet: 'Cissia',
    name: 'EXSpecialAttackVenomousBite_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Cissia',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackVenomousBite_1',
    },
  },
  'ChainAttackGangOperation_0:standardDmg': {
    sheet: 'Cissia',
    name: 'ChainAttackGangOperation_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Cissia',
      attribute: 'electric',
      damageType1: 'chain',
      skillType1: 'chainSkill',
      name: 'ChainAttackGangOperation_0',
    },
  },
  'ChainAttackGangOperation_0:dazeBuildup': {
    sheet: 'Cissia',
    name: 'ChainAttackGangOperation_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Cissia',
      attribute: 'electric',
      damageType1: 'chain',
      skillType1: 'chainSkill',
      name: 'ChainAttackGangOperation_0',
    },
  },
  'ChainAttackGangOperation_0:anomBuildup': {
    sheet: 'Cissia',
    name: 'ChainAttackGangOperation_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Cissia',
      attribute: 'electric',
      damageType1: 'chain',
      skillType1: 'chainSkill',
      name: 'ChainAttackGangOperation_0',
    },
  },
  'UltimateOphidiophobia_0:standardDmg': {
    sheet: 'Cissia',
    name: 'UltimateOphidiophobia_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Cissia',
      attribute: 'electric',
      damageType1: 'ult',
      skillType1: 'chainSkill',
      name: 'UltimateOphidiophobia_0',
    },
  },
  'UltimateOphidiophobia_0:dazeBuildup': {
    sheet: 'Cissia',
    name: 'UltimateOphidiophobia_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Cissia',
      attribute: 'electric',
      damageType1: 'ult',
      skillType1: 'chainSkill',
      name: 'UltimateOphidiophobia_0',
    },
  },
  'UltimateOphidiophobia_0:anomBuildup': {
    sheet: 'Cissia',
    name: 'UltimateOphidiophobia_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Cissia',
      attribute: 'electric',
      damageType1: 'ult',
      skillType1: 'chainSkill',
      name: 'UltimateOphidiophobia_0',
    },
  },
  'QuickAssistAlarmSystem_0:standardDmg': {
    sheet: 'Cissia',
    name: 'QuickAssistAlarmSystem_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Cissia',
      attribute: 'electric',
      damageType1: 'quickAssist',
      skillType1: 'assistSkill',
      name: 'QuickAssistAlarmSystem_0',
    },
  },
  'QuickAssistAlarmSystem_0:dazeBuildup': {
    sheet: 'Cissia',
    name: 'QuickAssistAlarmSystem_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Cissia',
      attribute: 'electric',
      damageType1: 'quickAssist',
      skillType1: 'assistSkill',
      name: 'QuickAssistAlarmSystem_0',
    },
  },
  'QuickAssistAlarmSystem_0:anomBuildup': {
    sheet: 'Cissia',
    name: 'QuickAssistAlarmSystem_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Cissia',
      attribute: 'electric',
      damageType1: 'quickAssist',
      skillType1: 'assistSkill',
      name: 'QuickAssistAlarmSystem_0',
    },
  },
  'DefensiveAssistExtraPrisonRations_0:standardDmg': {
    sheet: 'Cissia',
    name: 'DefensiveAssistExtraPrisonRations_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Cissia',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistExtraPrisonRations_0',
    },
  },
  'DefensiveAssistExtraPrisonRations_0:dazeBuildup': {
    sheet: 'Cissia',
    name: 'DefensiveAssistExtraPrisonRations_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Cissia',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistExtraPrisonRations_0',
    },
  },
  'DefensiveAssistExtraPrisonRations_0:anomBuildup': {
    sheet: 'Cissia',
    name: 'DefensiveAssistExtraPrisonRations_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Cissia',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistExtraPrisonRations_0',
    },
  },
  'DefensiveAssistExtraPrisonRations_1:standardDmg': {
    sheet: 'Cissia',
    name: 'DefensiveAssistExtraPrisonRations_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Cissia',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistExtraPrisonRations_1',
    },
  },
  'DefensiveAssistExtraPrisonRations_1:dazeBuildup': {
    sheet: 'Cissia',
    name: 'DefensiveAssistExtraPrisonRations_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Cissia',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistExtraPrisonRations_1',
    },
  },
  'DefensiveAssistExtraPrisonRations_1:anomBuildup': {
    sheet: 'Cissia',
    name: 'DefensiveAssistExtraPrisonRations_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Cissia',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistExtraPrisonRations_1',
    },
  },
  'DefensiveAssistExtraPrisonRations_2:standardDmg': {
    sheet: 'Cissia',
    name: 'DefensiveAssistExtraPrisonRations_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Cissia',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistExtraPrisonRations_2',
    },
  },
  'DefensiveAssistExtraPrisonRations_2:dazeBuildup': {
    sheet: 'Cissia',
    name: 'DefensiveAssistExtraPrisonRations_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Cissia',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistExtraPrisonRations_2',
    },
  },
  'DefensiveAssistExtraPrisonRations_2:anomBuildup': {
    sheet: 'Cissia',
    name: 'DefensiveAssistExtraPrisonRations_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Cissia',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistExtraPrisonRations_2',
    },
  },
  'AssistFollowUpPartnersInCrime_0:standardDmg': {
    sheet: 'Cissia',
    name: 'AssistFollowUpPartnersInCrime_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Cissia',
      attribute: 'electric',
      damageType1: 'assistFollowUp',
      skillType1: 'assistSkill',
      name: 'AssistFollowUpPartnersInCrime_0',
    },
  },
  'AssistFollowUpPartnersInCrime_0:dazeBuildup': {
    sheet: 'Cissia',
    name: 'AssistFollowUpPartnersInCrime_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Cissia',
      attribute: 'electric',
      damageType1: 'assistFollowUp',
      skillType1: 'assistSkill',
      name: 'AssistFollowUpPartnersInCrime_0',
    },
  },
  'AssistFollowUpPartnersInCrime_0:anomBuildup': {
    sheet: 'Cissia',
    name: 'AssistFollowUpPartnersInCrime_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Cissia',
      attribute: 'electric',
      damageType1: 'assistFollowUp',
      skillType1: 'assistSkill',
      name: 'AssistFollowUpPartnersInCrime_0',
    },
  },
} as const
