// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Remielle',
    name: 'standardDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      name: 'standardDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Remielle',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Remielle',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      name: 'dazeInst',
    },
  },
  'BasicAttackLeap_0:standardDmg': {
    sheet: 'Remielle',
    name: 'BasicAttackLeap_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLeap_0',
    },
  },
  'BasicAttackLeap_0:dazeBuildup': {
    sheet: 'Remielle',
    name: 'BasicAttackLeap_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLeap_0',
    },
  },
  'BasicAttackLeap_0:anomBuildup': {
    sheet: 'Remielle',
    name: 'BasicAttackLeap_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLeap_0',
    },
  },
  'BasicAttackLeap_1:standardDmg': {
    sheet: 'Remielle',
    name: 'BasicAttackLeap_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLeap_1',
    },
  },
  'BasicAttackLeap_1:dazeBuildup': {
    sheet: 'Remielle',
    name: 'BasicAttackLeap_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLeap_1',
    },
  },
  'BasicAttackLeap_1:anomBuildup': {
    sheet: 'Remielle',
    name: 'BasicAttackLeap_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLeap_1',
    },
  },
  'BasicAttackLeap_2:standardDmg': {
    sheet: 'Remielle',
    name: 'BasicAttackLeap_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLeap_2',
    },
  },
  'BasicAttackLeap_2:dazeBuildup': {
    sheet: 'Remielle',
    name: 'BasicAttackLeap_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLeap_2',
    },
  },
  'BasicAttackLeap_2:anomBuildup': {
    sheet: 'Remielle',
    name: 'BasicAttackLeap_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLeap_2',
    },
  },
  'BasicAttackLeap_3:standardDmg': {
    sheet: 'Remielle',
    name: 'BasicAttackLeap_3:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLeap_3',
    },
  },
  'BasicAttackLeap_3:dazeBuildup': {
    sheet: 'Remielle',
    name: 'BasicAttackLeap_3:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLeap_3',
    },
  },
  'BasicAttackLeap_3:anomBuildup': {
    sheet: 'Remielle',
    name: 'BasicAttackLeap_3:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLeap_3',
    },
  },
  'BasicAttackSoloDance_0:standardDmg': {
    sheet: 'Remielle',
    name: 'BasicAttackSoloDance_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSoloDance_0',
    },
  },
  'BasicAttackSoloDance_0:dazeBuildup': {
    sheet: 'Remielle',
    name: 'BasicAttackSoloDance_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSoloDance_0',
    },
  },
  'BasicAttackSoloDance_0:anomBuildup': {
    sheet: 'Remielle',
    name: 'BasicAttackSoloDance_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSoloDance_0',
    },
  },
  'BasicAttackRainbowsEnd_0:standardDmg': {
    sheet: 'Remielle',
    name: 'BasicAttackRainbowsEnd_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackRainbowsEnd_0',
    },
  },
  'BasicAttackRainbowsEnd_0:dazeBuildup': {
    sheet: 'Remielle',
    name: 'BasicAttackRainbowsEnd_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackRainbowsEnd_0',
    },
  },
  'BasicAttackRainbowsEnd_0:anomBuildup': {
    sheet: 'Remielle',
    name: 'BasicAttackRainbowsEnd_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackRainbowsEnd_0',
    },
  },
  'BasicAttackFleetingGrace_0:standardDmg': {
    sheet: 'Remielle',
    name: 'BasicAttackFleetingGrace_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFleetingGrace_0',
    },
  },
  'BasicAttackFleetingGrace_0:dazeBuildup': {
    sheet: 'Remielle',
    name: 'BasicAttackFleetingGrace_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFleetingGrace_0',
    },
  },
  'BasicAttackFleetingGrace_0:anomBuildup': {
    sheet: 'Remielle',
    name: 'BasicAttackFleetingGrace_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFleetingGrace_0',
    },
  },
  'DashAttackKeenLight_0:standardDmg': {
    sheet: 'Remielle',
    name: 'DashAttackKeenLight_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackKeenLight_0',
    },
  },
  'DashAttackKeenLight_0:dazeBuildup': {
    sheet: 'Remielle',
    name: 'DashAttackKeenLight_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackKeenLight_0',
    },
  },
  'DashAttackKeenLight_0:anomBuildup': {
    sheet: 'Remielle',
    name: 'DashAttackKeenLight_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackKeenLight_0',
    },
  },
  'DodgeCounterMirroredShadow_0:standardDmg': {
    sheet: 'Remielle',
    name: 'DodgeCounterMirroredShadow_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterMirroredShadow_0',
    },
  },
  'DodgeCounterMirroredShadow_0:dazeBuildup': {
    sheet: 'Remielle',
    name: 'DodgeCounterMirroredShadow_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterMirroredShadow_0',
    },
  },
  'DodgeCounterMirroredShadow_0:anomBuildup': {
    sheet: 'Remielle',
    name: 'DodgeCounterMirroredShadow_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterMirroredShadow_0',
    },
  },
  'SpecialAttackSliverOfLight_0:standardDmg': {
    sheet: 'Remielle',
    name: 'SpecialAttackSliverOfLight_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackSliverOfLight_0',
    },
  },
  'SpecialAttackSliverOfLight_0:dazeBuildup': {
    sheet: 'Remielle',
    name: 'SpecialAttackSliverOfLight_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackSliverOfLight_0',
    },
  },
  'SpecialAttackSliverOfLight_0:anomBuildup': {
    sheet: 'Remielle',
    name: 'SpecialAttackSliverOfLight_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackSliverOfLight_0',
    },
  },
  'EXSpecialAttackOdeToDawn_0:standardDmg': {
    sheet: 'Remielle',
    name: 'EXSpecialAttackOdeToDawn_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackOdeToDawn_0',
    },
  },
  'EXSpecialAttackOdeToDawn_0:dazeBuildup': {
    sheet: 'Remielle',
    name: 'EXSpecialAttackOdeToDawn_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackOdeToDawn_0',
    },
  },
  'EXSpecialAttackOdeToDawn_0:anomBuildup': {
    sheet: 'Remielle',
    name: 'EXSpecialAttackOdeToDawn_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackOdeToDawn_0',
    },
  },
  'SpecialAttackOdeToDawnRadiantTurn_0:standardDmg': {
    sheet: 'Remielle',
    name: 'SpecialAttackOdeToDawnRadiantTurn_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackOdeToDawnRadiantTurn_0',
    },
  },
  'SpecialAttackOdeToDawnRadiantTurn_0:dazeBuildup': {
    sheet: 'Remielle',
    name: 'SpecialAttackOdeToDawnRadiantTurn_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackOdeToDawnRadiantTurn_0',
    },
  },
  'SpecialAttackOdeToDawnRadiantTurn_0:anomBuildup': {
    sheet: 'Remielle',
    name: 'SpecialAttackOdeToDawnRadiantTurn_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackOdeToDawnRadiantTurn_0',
    },
  },
  'ChainAttackInterwovenDanceSteps_0:standardDmg': {
    sheet: 'Remielle',
    name: 'ChainAttackInterwovenDanceSteps_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackInterwovenDanceSteps_0',
    },
  },
  'ChainAttackInterwovenDanceSteps_0:dazeBuildup': {
    sheet: 'Remielle',
    name: 'ChainAttackInterwovenDanceSteps_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackInterwovenDanceSteps_0',
    },
  },
  'ChainAttackInterwovenDanceSteps_0:anomBuildup': {
    sheet: 'Remielle',
    name: 'ChainAttackInterwovenDanceSteps_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackInterwovenDanceSteps_0',
    },
  },
  'UltimateDazzlingCurtainCall_0:standardDmg': {
    sheet: 'Remielle',
    name: 'UltimateDazzlingCurtainCall_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateDazzlingCurtainCall_0',
    },
  },
  'UltimateDazzlingCurtainCall_0:dazeBuildup': {
    sheet: 'Remielle',
    name: 'UltimateDazzlingCurtainCall_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateDazzlingCurtainCall_0',
    },
  },
  'UltimateDazzlingCurtainCall_0:anomBuildup': {
    sheet: 'Remielle',
    name: 'UltimateDazzlingCurtainCall_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateDazzlingCurtainCall_0',
    },
  },
  'QuickAssistFeatherglowRebirth_0:standardDmg': {
    sheet: 'Remielle',
    name: 'QuickAssistFeatherglowRebirth_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistFeatherglowRebirth_0',
    },
  },
  'QuickAssistFeatherglowRebirth_0:dazeBuildup': {
    sheet: 'Remielle',
    name: 'QuickAssistFeatherglowRebirth_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistFeatherglowRebirth_0',
    },
  },
  'QuickAssistFeatherglowRebirth_0:anomBuildup': {
    sheet: 'Remielle',
    name: 'QuickAssistFeatherglowRebirth_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistFeatherglowRebirth_0',
    },
  },
  'DefensiveAssistFleetingLight_0:standardDmg': {
    sheet: 'Remielle',
    name: 'DefensiveAssistFleetingLight_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistFleetingLight_0',
    },
  },
  'DefensiveAssistFleetingLight_0:dazeBuildup': {
    sheet: 'Remielle',
    name: 'DefensiveAssistFleetingLight_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistFleetingLight_0',
    },
  },
  'DefensiveAssistFleetingLight_0:anomBuildup': {
    sheet: 'Remielle',
    name: 'DefensiveAssistFleetingLight_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistFleetingLight_0',
    },
  },
  'DefensiveAssistFleetingLight_1:standardDmg': {
    sheet: 'Remielle',
    name: 'DefensiveAssistFleetingLight_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistFleetingLight_1',
    },
  },
  'DefensiveAssistFleetingLight_1:dazeBuildup': {
    sheet: 'Remielle',
    name: 'DefensiveAssistFleetingLight_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistFleetingLight_1',
    },
  },
  'DefensiveAssistFleetingLight_1:anomBuildup': {
    sheet: 'Remielle',
    name: 'DefensiveAssistFleetingLight_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistFleetingLight_1',
    },
  },
  'DefensiveAssistFleetingLight_2:standardDmg': {
    sheet: 'Remielle',
    name: 'DefensiveAssistFleetingLight_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistFleetingLight_2',
    },
  },
  'DefensiveAssistFleetingLight_2:dazeBuildup': {
    sheet: 'Remielle',
    name: 'DefensiveAssistFleetingLight_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistFleetingLight_2',
    },
  },
  'DefensiveAssistFleetingLight_2:anomBuildup': {
    sheet: 'Remielle',
    name: 'DefensiveAssistFleetingLight_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistFleetingLight_2',
    },
  },
  'AssistFollowUpAwakeningGlimmer_0:standardDmg': {
    sheet: 'Remielle',
    name: 'AssistFollowUpAwakeningGlimmer_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpAwakeningGlimmer_0',
    },
  },
  'AssistFollowUpAwakeningGlimmer_0:dazeBuildup': {
    sheet: 'Remielle',
    name: 'AssistFollowUpAwakeningGlimmer_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpAwakeningGlimmer_0',
    },
  },
  'AssistFollowUpAwakeningGlimmer_0:anomBuildup': {
    sheet: 'Remielle',
    name: 'AssistFollowUpAwakeningGlimmer_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpAwakeningGlimmer_0',
    },
  },
  'AssistFlowerFeatherDance_0:standardDmg': {
    sheet: 'Remielle',
    name: 'AssistFlowerFeatherDance_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFlowerFeatherDance_0',
    },
  },
  'AssistFlowerFeatherDance_0:dazeBuildup': {
    sheet: 'Remielle',
    name: 'AssistFlowerFeatherDance_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFlowerFeatherDance_0',
    },
  },
  'AssistFlowerFeatherDance_0:anomBuildup': {
    sheet: 'Remielle',
    name: 'AssistFlowerFeatherDance_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFlowerFeatherDance_0',
    },
  },
} as const
