// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Remielle',
    name: 'standardDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'standardDmgBase',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      name: 'standardDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Remielle',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Remielle',
    name: 'dazeInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'dazeBuildupBase',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      name: 'dazeInst',
    },
  },
  BasicAttackLeap_0: {
    sheet: 'Remielle',
    name: 'BasicAttackLeap_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLeap_0',
    },
  },
  BasicAttackLeap_1: {
    sheet: 'Remielle',
    name: 'BasicAttackLeap_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLeap_1',
    },
  },
  BasicAttackLeap_2: {
    sheet: 'Remielle',
    name: 'BasicAttackLeap_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLeap_2',
    },
  },
  BasicAttackLeap_3: {
    sheet: 'Remielle',
    name: 'BasicAttackLeap_3',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLeap_3',
    },
  },
  BasicAttackSoloDance_0: {
    sheet: 'Remielle',
    name: 'BasicAttackSoloDance_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSoloDance_0',
    },
  },
  BasicAttackRainbowsEnd_0: {
    sheet: 'Remielle',
    name: 'BasicAttackRainbowsEnd_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackRainbowsEnd_0',
    },
  },
  BasicAttackFleetingGrace_0: {
    sheet: 'Remielle',
    name: 'BasicAttackFleetingGrace_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFleetingGrace_0',
    },
  },
  DashAttackKeenLight_0: {
    sheet: 'Remielle',
    name: 'DashAttackKeenLight_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackKeenLight_0',
    },
  },
  DodgeCounterMirroredShadow_0: {
    sheet: 'Remielle',
    name: 'DodgeCounterMirroredShadow_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterMirroredShadow_0',
    },
  },
  SpecialAttackSliverOfLight_0: {
    sheet: 'Remielle',
    name: 'SpecialAttackSliverOfLight_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackSliverOfLight_0',
    },
  },
  EXSpecialAttackOdeToDawn_0: {
    sheet: 'Remielle',
    name: 'EXSpecialAttackOdeToDawn_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackOdeToDawn_0',
    },
  },
  SpecialAttackOdeToDawnRadiantTurn_0: {
    sheet: 'Remielle',
    name: 'SpecialAttackOdeToDawnRadiantTurn_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackOdeToDawnRadiantTurn_0',
    },
  },
  ChainAttackInterwovenDanceSteps_0: {
    sheet: 'Remielle',
    name: 'ChainAttackInterwovenDanceSteps_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackInterwovenDanceSteps_0',
    },
  },
  UltimateDazzlingCurtainCall_0: {
    sheet: 'Remielle',
    name: 'UltimateDazzlingCurtainCall_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateDazzlingCurtainCall_0',
    },
  },
  QuickAssistFeatherglowRebirth_0: {
    sheet: 'Remielle',
    name: 'QuickAssistFeatherglowRebirth_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistFeatherglowRebirth_0',
    },
  },
  DefensiveAssistFleetingLight_0: {
    sheet: 'Remielle',
    name: 'DefensiveAssistFleetingLight_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistFleetingLight_0',
    },
  },
  DefensiveAssistFleetingLight_1: {
    sheet: 'Remielle',
    name: 'DefensiveAssistFleetingLight_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistFleetingLight_1',
    },
  },
  DefensiveAssistFleetingLight_2: {
    sheet: 'Remielle',
    name: 'DefensiveAssistFleetingLight_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistFleetingLight_2',
    },
  },
  AssistFollowUpAwakeningGlimmer_0: {
    sheet: 'Remielle',
    name: 'AssistFollowUpAwakeningGlimmer_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpAwakeningGlimmer_0',
    },
  },
  AssistFlowerFeatherDance_0: {
    sheet: 'Remielle',
    name: 'AssistFlowerFeatherDance_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Remielle',
      attribute: 'lumiflux',
      damageType1: 'entrySkill',
      skillType: 'assistSkill',
      name: 'AssistFlowerFeatherDance_0',
    },
  },
} as const
