nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.4.1.cjs

supportedArchitectures:
  os:
    - current
    - linux
  cpu:
    - current
    - x64
  libc:
    - current
    - glibc

# to fix peerdpendencies not being installed by yarn explicitly(needs to be fixed by package author)
packageExtensions:
  '@supabase/ssr@*':
    dependencies:
      '@supabase/supabase-js': ^2.33.1
