// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Anby',
    name: 'standardDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'standardDmgBase',
      sheet: 'Anby',
      attribute: 'electric',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Anby',
    name: 'anomalyDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Anby',
      attribute: 'electric',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_electric: {
    sheet: 'Anby',
    name: 'disorderDmgInst_electric',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Anby',
      attribute: 'electric',
      damageType1: 'disorder',
      name: 'disorderDmgInst_electric',
    },
  },
  vortexDmgInst_electric: {
    sheet: 'Anby',
    name: 'vortexDmgInst_electric',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Anby',
      attribute: 'electric',
      damageType1: 'vortex',
      name: 'vortexDmgInst_electric',
    },
  },
  abloomDmgInst: {
    sheet: 'Anby',
    name: 'abloomDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Anby',
      attribute: 'electric',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Anby',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Anby',
      attribute: 'electric',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Anby',
    name: 'dazeInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'dazeBuildupBase',
      sheet: 'Anby',
      attribute: 'electric',
      name: 'dazeInst',
    },
  },
  BasicAttackTurboVolt_0: {
    sheet: 'Anby',
    name: 'BasicAttackTurboVolt_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Anby',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackTurboVolt_0',
    },
  },
  BasicAttackTurboVolt_1: {
    sheet: 'Anby',
    name: 'BasicAttackTurboVolt_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Anby',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackTurboVolt_1',
    },
  },
  BasicAttackTurboVolt_2: {
    sheet: 'Anby',
    name: 'BasicAttackTurboVolt_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Anby',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackTurboVolt_2',
    },
  },
  BasicAttackTurboVolt_3: {
    sheet: 'Anby',
    name: 'BasicAttackTurboVolt_3',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Anby',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTurboVolt_3',
    },
  },
  BasicAttackThunderbolt_0: {
    sheet: 'Anby',
    name: 'BasicAttackThunderbolt_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Anby',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackThunderbolt_0',
    },
  },
  DashAttackTaserBlast_0: {
    sheet: 'Anby',
    name: 'DashAttackTaserBlast_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Anby',
      attribute: 'electric',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackTaserBlast_0',
    },
  },
  DodgeCounterThunderclap_0: {
    sheet: 'Anby',
    name: 'DodgeCounterThunderclap_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Anby',
      attribute: 'electric',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterThunderclap_0',
    },
  },
  SpecialAttackForkLightning_0: {
    sheet: 'Anby',
    name: 'SpecialAttackForkLightning_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Anby',
      attribute: 'electric',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackForkLightning_0',
    },
  },
  EXSpecialAttackLightningBolt_0: {
    sheet: 'Anby',
    name: 'EXSpecialAttackLightningBolt_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Anby',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackLightningBolt_0',
    },
  },
  ChainAttackElectroEngine_0: {
    sheet: 'Anby',
    name: 'ChainAttackElectroEngine_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Anby',
      attribute: 'electric',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackElectroEngine_0',
    },
  },
  UltimateOverdriveEngine_0: {
    sheet: 'Anby',
    name: 'UltimateOverdriveEngine_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Anby',
      attribute: 'electric',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateOverdriveEngine_0',
    },
  },
  QuickAssistThunderfall_0: {
    sheet: 'Anby',
    name: 'QuickAssistThunderfall_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Anby',
      attribute: 'electric',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistThunderfall_0',
    },
  },
  DefensiveAssistFlash_0: {
    sheet: 'Anby',
    name: 'DefensiveAssistFlash_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Anby',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistFlash_0',
    },
  },
  DefensiveAssistFlash_1: {
    sheet: 'Anby',
    name: 'DefensiveAssistFlash_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Anby',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistFlash_1',
    },
  },
  DefensiveAssistFlash_2: {
    sheet: 'Anby',
    name: 'DefensiveAssistFlash_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Anby',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistFlash_2',
    },
  },
  AssistFollowUpLightningWhirl_0: {
    sheet: 'Anby',
    name: 'AssistFollowUpLightningWhirl_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Anby',
      attribute: 'electric',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpLightningWhirl_0',
    },
  },
} as const
