// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Yuzuha',
    name: 'standardDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'standardDmgBase',
      sheet: 'Yuzuha',
      attribute: 'physical',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Yuzuha',
    name: 'anomalyDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_physical: {
    sheet: 'Yuzuha',
    name: 'disorderDmgInst_physical',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'disorder',
      name: 'disorderDmgInst_physical',
    },
  },
  vortexDmgInst_physical: {
    sheet: 'Yuzuha',
    name: 'vortexDmgInst_physical',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'vortex',
      name: 'vortexDmgInst_physical',
    },
  },
  abloomDmgInst: {
    sheet: 'Yuzuha',
    name: 'abloomDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Yuzuha',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yuzuha',
      attribute: 'physical',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Yuzuha',
    name: 'dazeInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'dazeBuildupBase',
      sheet: 'Yuzuha',
      attribute: 'physical',
      name: 'dazeInst',
    },
  },
  BasicAttackTanukiClaws_0: {
    sheet: 'Yuzuha',
    name: 'BasicAttackTanukiClaws_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTanukiClaws_0',
    },
  },
  BasicAttackTanukiClaws_1: {
    sheet: 'Yuzuha',
    name: 'BasicAttackTanukiClaws_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTanukiClaws_1',
    },
  },
  BasicAttackTanukiClaws_2: {
    sheet: 'Yuzuha',
    name: 'BasicAttackTanukiClaws_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTanukiClaws_2',
    },
  },
  BasicAttackTanukiClaws_3: {
    sheet: 'Yuzuha',
    name: 'BasicAttackTanukiClaws_3',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTanukiClaws_3',
    },
  },
  BasicAttackTanukiClaws_4: {
    sheet: 'Yuzuha',
    name: 'BasicAttackTanukiClaws_4',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTanukiClaws_4',
    },
  },
  BasicAttackTanukiCloak_0: {
    sheet: 'Yuzuha',
    name: 'BasicAttackTanukiCloak_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTanukiCloak_0',
    },
  },
  BasicAttackHardCandyShot_0: {
    sheet: 'Yuzuha',
    name: 'BasicAttackHardCandyShot_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yuzuha',
      damageType1: 'basic',
      damageType2: 'aftershock',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackHardCandyShot_0',
    },
  },
  BasicAttackSugarburstSparkles_0: {
    sheet: 'Yuzuha',
    name: 'BasicAttackSugarburstSparkles_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yuzuha',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackSugarburstSparkles_0',
    },
  },
  BasicAttackSugarburstSparklesMax_0: {
    sheet: 'Yuzuha',
    name: 'BasicAttackSugarburstSparklesMax_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yuzuha',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackSugarburstSparklesMax_0',
    },
  },
  BasicAttackTanukiHelper_0: {
    sheet: 'Yuzuha',
    name: 'BasicAttackTanukiHelper_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTanukiHelper_0',
    },
  },
  BasicAttackTanukiHelper_1: {
    sheet: 'Yuzuha',
    name: 'BasicAttackTanukiHelper_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTanukiHelper_1',
    },
  },
  DashAttackYoureOuttaLuck_0: {
    sheet: 'Yuzuha',
    name: 'DashAttackYoureOuttaLuck_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackYoureOuttaLuck_0',
    },
  },
  DodgeCounterTimeForPayback_0: {
    sheet: 'Yuzuha',
    name: 'DodgeCounterTimeForPayback_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterTimeForPayback_0',
    },
  },
  SpecialAttackGummyBombardment_0: {
    sheet: 'Yuzuha',
    name: 'SpecialAttackGummyBombardment_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackGummyBombardment_0',
    },
  },
  EXSpecialAttackCavityAlert_0: {
    sheet: 'Yuzuha',
    name: 'EXSpecialAttackCavityAlert_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackCavityAlert_0',
    },
  },
  EXSpecialAttackCavityAlertRightNow_0: {
    sheet: 'Yuzuha',
    name: 'EXSpecialAttackCavityAlertRightNow_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackCavityAlertRightNow_0',
    },
  },
  ChainAttackPrankAssault_0: {
    sheet: 'Yuzuha',
    name: 'ChainAttackPrankAssault_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackPrankAssault_0',
    },
  },
  UltimateSurrenderOrSufferTheMischief_0: {
    sheet: 'Yuzuha',
    name: 'UltimateSurrenderOrSufferTheMischief_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateSurrenderOrSufferTheMischief_0',
    },
  },
  QuickAssistDessertTime_0: {
    sheet: 'Yuzuha',
    name: 'QuickAssistDessertTime_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistDessertTime_0',
    },
  },
  DefensiveAssistReplenishYourFun_0: {
    sheet: 'Yuzuha',
    name: 'DefensiveAssistReplenishYourFun_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistReplenishYourFun_0',
    },
  },
  DefensiveAssistReplenishYourFun_1: {
    sheet: 'Yuzuha',
    name: 'DefensiveAssistReplenishYourFun_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistReplenishYourFun_1',
    },
  },
  DefensiveAssistReplenishYourFun_2: {
    sheet: 'Yuzuha',
    name: 'DefensiveAssistReplenishYourFun_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistReplenishYourFun_2',
    },
  },
  AssistFollowUpWeHaveCookies_0: {
    sheet: 'Yuzuha',
    name: 'AssistFollowUpWeHaveCookies_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpWeHaveCookies_0',
    },
  },
  AssistFollowUpStuffedHardCandyShot_0: {
    sheet: 'Yuzuha',
    name: 'AssistFollowUpStuffedHardCandyShot_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpStuffedHardCandyShot_0',
    },
  },
  m6_dmg: {
    sheet: 'Yuzuha',
    name: 'm6_dmg',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'standardDmgBase',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'elemental',
      name: 'm6_dmg',
    },
  },
} as const
