// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Yuzuha',
    name: 'standardDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yuzuha',
      attribute: 'physical',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Yuzuha',
    name: 'anomalyDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_physical: {
    sheet: 'Yuzuha',
    name: 'disorderDmgInst_physical',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'disorder',
      name: 'disorderDmgInst_physical',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Yuzuha',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Yuzuha',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      name: 'dazeInst',
    },
  },
  BasicAttackTanukiClaws_0_dmg: {
    sheet: 'Yuzuha',
    name: 'BasicAttackTanukiClaws_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTanukiClaws_0_dmg',
    },
  },
  BasicAttackTanukiClaws_0_daze: {
    sheet: 'Yuzuha',
    name: 'BasicAttackTanukiClaws_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTanukiClaws_0_daze',
    },
  },
  BasicAttackTanukiClaws_0_anomBuildup: {
    sheet: 'Yuzuha',
    name: 'BasicAttackTanukiClaws_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTanukiClaws_0_anomBuildup',
    },
  },
  BasicAttackTanukiClaws_1_dmg: {
    sheet: 'Yuzuha',
    name: 'BasicAttackTanukiClaws_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTanukiClaws_1_dmg',
    },
  },
  BasicAttackTanukiClaws_1_daze: {
    sheet: 'Yuzuha',
    name: 'BasicAttackTanukiClaws_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTanukiClaws_1_daze',
    },
  },
  BasicAttackTanukiClaws_1_anomBuildup: {
    sheet: 'Yuzuha',
    name: 'BasicAttackTanukiClaws_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTanukiClaws_1_anomBuildup',
    },
  },
  BasicAttackTanukiClaws_2_dmg: {
    sheet: 'Yuzuha',
    name: 'BasicAttackTanukiClaws_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTanukiClaws_2_dmg',
    },
  },
  BasicAttackTanukiClaws_2_daze: {
    sheet: 'Yuzuha',
    name: 'BasicAttackTanukiClaws_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTanukiClaws_2_daze',
    },
  },
  BasicAttackTanukiClaws_2_anomBuildup: {
    sheet: 'Yuzuha',
    name: 'BasicAttackTanukiClaws_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTanukiClaws_2_anomBuildup',
    },
  },
  BasicAttackTanukiClaws_3_dmg: {
    sheet: 'Yuzuha',
    name: 'BasicAttackTanukiClaws_3_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTanukiClaws_3_dmg',
    },
  },
  BasicAttackTanukiClaws_3_daze: {
    sheet: 'Yuzuha',
    name: 'BasicAttackTanukiClaws_3_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTanukiClaws_3_daze',
    },
  },
  BasicAttackTanukiClaws_3_anomBuildup: {
    sheet: 'Yuzuha',
    name: 'BasicAttackTanukiClaws_3_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTanukiClaws_3_anomBuildup',
    },
  },
  BasicAttackTanukiClaws_4_dmg: {
    sheet: 'Yuzuha',
    name: 'BasicAttackTanukiClaws_4_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTanukiClaws_4_dmg',
    },
  },
  BasicAttackTanukiClaws_4_daze: {
    sheet: 'Yuzuha',
    name: 'BasicAttackTanukiClaws_4_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTanukiClaws_4_daze',
    },
  },
  BasicAttackTanukiClaws_4_anomBuildup: {
    sheet: 'Yuzuha',
    name: 'BasicAttackTanukiClaws_4_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTanukiClaws_4_anomBuildup',
    },
  },
  BasicAttackTanukiCloak_0_dmg: {
    sheet: 'Yuzuha',
    name: 'BasicAttackTanukiCloak_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTanukiCloak_0_dmg',
    },
  },
  BasicAttackTanukiCloak_0_daze: {
    sheet: 'Yuzuha',
    name: 'BasicAttackTanukiCloak_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTanukiCloak_0_daze',
    },
  },
  BasicAttackTanukiCloak_0_anomBuildup: {
    sheet: 'Yuzuha',
    name: 'BasicAttackTanukiCloak_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTanukiCloak_0_anomBuildup',
    },
  },
  BasicAttackHardCandyShot_0_dmg: {
    sheet: 'Yuzuha',
    name: 'BasicAttackHardCandyShot_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yuzuha',
      damageType1: 'basic',
      damageType2: 'aftershock',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackHardCandyShot_0_dmg',
    },
  },
  BasicAttackHardCandyShot_0_daze: {
    sheet: 'Yuzuha',
    name: 'BasicAttackHardCandyShot_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yuzuha',
      damageType1: 'basic',
      damageType2: 'aftershock',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackHardCandyShot_0_daze',
    },
  },
  BasicAttackHardCandyShot_0_anomBuildup: {
    sheet: 'Yuzuha',
    name: 'BasicAttackHardCandyShot_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yuzuha',
      damageType1: 'basic',
      damageType2: 'aftershock',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackHardCandyShot_0_anomBuildup',
    },
  },
  BasicAttackSugarburstSparkles_0_dmg: {
    sheet: 'Yuzuha',
    name: 'BasicAttackSugarburstSparkles_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yuzuha',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackSugarburstSparkles_0_dmg',
    },
  },
  BasicAttackSugarburstSparkles_0_daze: {
    sheet: 'Yuzuha',
    name: 'BasicAttackSugarburstSparkles_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yuzuha',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackSugarburstSparkles_0_daze',
    },
  },
  BasicAttackSugarburstSparkles_0_anomBuildup: {
    sheet: 'Yuzuha',
    name: 'BasicAttackSugarburstSparkles_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yuzuha',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackSugarburstSparkles_0_anomBuildup',
    },
  },
  BasicAttackSugarburstSparklesMax_0_dmg: {
    sheet: 'Yuzuha',
    name: 'BasicAttackSugarburstSparklesMax_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yuzuha',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackSugarburstSparklesMax_0_dmg',
    },
  },
  BasicAttackSugarburstSparklesMax_0_daze: {
    sheet: 'Yuzuha',
    name: 'BasicAttackSugarburstSparklesMax_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yuzuha',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackSugarburstSparklesMax_0_daze',
    },
  },
  BasicAttackSugarburstSparklesMax_0_anomBuildup: {
    sheet: 'Yuzuha',
    name: 'BasicAttackSugarburstSparklesMax_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yuzuha',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackSugarburstSparklesMax_0_anomBuildup',
    },
  },
  BasicAttackTanukiHelper_0_dmg: {
    sheet: 'Yuzuha',
    name: 'BasicAttackTanukiHelper_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTanukiHelper_0_dmg',
    },
  },
  BasicAttackTanukiHelper_0_daze: {
    sheet: 'Yuzuha',
    name: 'BasicAttackTanukiHelper_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTanukiHelper_0_daze',
    },
  },
  BasicAttackTanukiHelper_0_anomBuildup: {
    sheet: 'Yuzuha',
    name: 'BasicAttackTanukiHelper_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTanukiHelper_0_anomBuildup',
    },
  },
  BasicAttackTanukiHelper_1_dmg: {
    sheet: 'Yuzuha',
    name: 'BasicAttackTanukiHelper_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTanukiHelper_1_dmg',
    },
  },
  BasicAttackTanukiHelper_1_daze: {
    sheet: 'Yuzuha',
    name: 'BasicAttackTanukiHelper_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTanukiHelper_1_daze',
    },
  },
  BasicAttackTanukiHelper_1_anomBuildup: {
    sheet: 'Yuzuha',
    name: 'BasicAttackTanukiHelper_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTanukiHelper_1_anomBuildup',
    },
  },
  DashAttackYoureOuttaLuck_0_dmg: {
    sheet: 'Yuzuha',
    name: 'DashAttackYoureOuttaLuck_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackYoureOuttaLuck_0_dmg',
    },
  },
  DashAttackYoureOuttaLuck_0_daze: {
    sheet: 'Yuzuha',
    name: 'DashAttackYoureOuttaLuck_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackYoureOuttaLuck_0_daze',
    },
  },
  DashAttackYoureOuttaLuck_0_anomBuildup: {
    sheet: 'Yuzuha',
    name: 'DashAttackYoureOuttaLuck_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackYoureOuttaLuck_0_anomBuildup',
    },
  },
  DodgeCounterTimeForPayback_0_dmg: {
    sheet: 'Yuzuha',
    name: 'DodgeCounterTimeForPayback_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterTimeForPayback_0_dmg',
    },
  },
  DodgeCounterTimeForPayback_0_daze: {
    sheet: 'Yuzuha',
    name: 'DodgeCounterTimeForPayback_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterTimeForPayback_0_daze',
    },
  },
  DodgeCounterTimeForPayback_0_anomBuildup: {
    sheet: 'Yuzuha',
    name: 'DodgeCounterTimeForPayback_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterTimeForPayback_0_anomBuildup',
    },
  },
  SpecialAttackGummyBombardment_0_dmg: {
    sheet: 'Yuzuha',
    name: 'SpecialAttackGummyBombardment_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackGummyBombardment_0_dmg',
    },
  },
  SpecialAttackGummyBombardment_0_daze: {
    sheet: 'Yuzuha',
    name: 'SpecialAttackGummyBombardment_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackGummyBombardment_0_daze',
    },
  },
  SpecialAttackGummyBombardment_0_anomBuildup: {
    sheet: 'Yuzuha',
    name: 'SpecialAttackGummyBombardment_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackGummyBombardment_0_anomBuildup',
    },
  },
  EXSpecialAttackCavityAlert_0_dmg: {
    sheet: 'Yuzuha',
    name: 'EXSpecialAttackCavityAlert_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackCavityAlert_0_dmg',
    },
  },
  EXSpecialAttackCavityAlert_0_daze: {
    sheet: 'Yuzuha',
    name: 'EXSpecialAttackCavityAlert_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackCavityAlert_0_daze',
    },
  },
  EXSpecialAttackCavityAlert_0_anomBuildup: {
    sheet: 'Yuzuha',
    name: 'EXSpecialAttackCavityAlert_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackCavityAlert_0_anomBuildup',
    },
  },
  EXSpecialAttackCavityAlertRightNow_0_dmg: {
    sheet: 'Yuzuha',
    name: 'EXSpecialAttackCavityAlertRightNow_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackCavityAlertRightNow_0_dmg',
    },
  },
  EXSpecialAttackCavityAlertRightNow_0_daze: {
    sheet: 'Yuzuha',
    name: 'EXSpecialAttackCavityAlertRightNow_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackCavityAlertRightNow_0_daze',
    },
  },
  EXSpecialAttackCavityAlertRightNow_0_anomBuildup: {
    sheet: 'Yuzuha',
    name: 'EXSpecialAttackCavityAlertRightNow_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackCavityAlertRightNow_0_anomBuildup',
    },
  },
  ChainAttackPrankAssault_0_dmg: {
    sheet: 'Yuzuha',
    name: 'ChainAttackPrankAssault_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackPrankAssault_0_dmg',
    },
  },
  ChainAttackPrankAssault_0_daze: {
    sheet: 'Yuzuha',
    name: 'ChainAttackPrankAssault_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackPrankAssault_0_daze',
    },
  },
  ChainAttackPrankAssault_0_anomBuildup: {
    sheet: 'Yuzuha',
    name: 'ChainAttackPrankAssault_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackPrankAssault_0_anomBuildup',
    },
  },
  UltimateSurrenderOrSufferTheMischief_0_dmg: {
    sheet: 'Yuzuha',
    name: 'UltimateSurrenderOrSufferTheMischief_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateSurrenderOrSufferTheMischief_0_dmg',
    },
  },
  UltimateSurrenderOrSufferTheMischief_0_daze: {
    sheet: 'Yuzuha',
    name: 'UltimateSurrenderOrSufferTheMischief_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateSurrenderOrSufferTheMischief_0_daze',
    },
  },
  UltimateSurrenderOrSufferTheMischief_0_anomBuildup: {
    sheet: 'Yuzuha',
    name: 'UltimateSurrenderOrSufferTheMischief_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateSurrenderOrSufferTheMischief_0_anomBuildup',
    },
  },
  QuickAssistDessertTime_0_dmg: {
    sheet: 'Yuzuha',
    name: 'QuickAssistDessertTime_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistDessertTime_0_dmg',
    },
  },
  QuickAssistDessertTime_0_daze: {
    sheet: 'Yuzuha',
    name: 'QuickAssistDessertTime_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistDessertTime_0_daze',
    },
  },
  QuickAssistDessertTime_0_anomBuildup: {
    sheet: 'Yuzuha',
    name: 'QuickAssistDessertTime_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistDessertTime_0_anomBuildup',
    },
  },
  DefensiveAssistReplenishYourFun_0_dmg: {
    sheet: 'Yuzuha',
    name: 'DefensiveAssistReplenishYourFun_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistReplenishYourFun_0_dmg',
    },
  },
  DefensiveAssistReplenishYourFun_0_daze: {
    sheet: 'Yuzuha',
    name: 'DefensiveAssistReplenishYourFun_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistReplenishYourFun_0_daze',
    },
  },
  DefensiveAssistReplenishYourFun_0_anomBuildup: {
    sheet: 'Yuzuha',
    name: 'DefensiveAssistReplenishYourFun_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistReplenishYourFun_0_anomBuildup',
    },
  },
  DefensiveAssistReplenishYourFun_1_dmg: {
    sheet: 'Yuzuha',
    name: 'DefensiveAssistReplenishYourFun_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistReplenishYourFun_1_dmg',
    },
  },
  DefensiveAssistReplenishYourFun_1_daze: {
    sheet: 'Yuzuha',
    name: 'DefensiveAssistReplenishYourFun_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistReplenishYourFun_1_daze',
    },
  },
  DefensiveAssistReplenishYourFun_1_anomBuildup: {
    sheet: 'Yuzuha',
    name: 'DefensiveAssistReplenishYourFun_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistReplenishYourFun_1_anomBuildup',
    },
  },
  DefensiveAssistReplenishYourFun_2_dmg: {
    sheet: 'Yuzuha',
    name: 'DefensiveAssistReplenishYourFun_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistReplenishYourFun_2_dmg',
    },
  },
  DefensiveAssistReplenishYourFun_2_daze: {
    sheet: 'Yuzuha',
    name: 'DefensiveAssistReplenishYourFun_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistReplenishYourFun_2_daze',
    },
  },
  DefensiveAssistReplenishYourFun_2_anomBuildup: {
    sheet: 'Yuzuha',
    name: 'DefensiveAssistReplenishYourFun_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistReplenishYourFun_2_anomBuildup',
    },
  },
  AssistFollowUpWeHaveCookies_0_dmg: {
    sheet: 'Yuzuha',
    name: 'AssistFollowUpWeHaveCookies_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpWeHaveCookies_0_dmg',
    },
  },
  AssistFollowUpWeHaveCookies_0_daze: {
    sheet: 'Yuzuha',
    name: 'AssistFollowUpWeHaveCookies_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpWeHaveCookies_0_daze',
    },
  },
  AssistFollowUpWeHaveCookies_0_anomBuildup: {
    sheet: 'Yuzuha',
    name: 'AssistFollowUpWeHaveCookies_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpWeHaveCookies_0_anomBuildup',
    },
  },
  AssistFollowUpStuffedHardCandyShot_0_dmg: {
    sheet: 'Yuzuha',
    name: 'AssistFollowUpStuffedHardCandyShot_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpStuffedHardCandyShot_0_dmg',
    },
  },
  AssistFollowUpStuffedHardCandyShot_0_daze: {
    sheet: 'Yuzuha',
    name: 'AssistFollowUpStuffedHardCandyShot_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpStuffedHardCandyShot_0_daze',
    },
  },
  AssistFollowUpStuffedHardCandyShot_0_anomBuildup: {
    sheet: 'Yuzuha',
    name: 'AssistFollowUpStuffedHardCandyShot_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpStuffedHardCandyShot_0_anomBuildup',
    },
  },
  m6_dmg: {
    sheet: 'Yuzuha',
    name: 'm6_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'elemental',
      name: 'm6_dmg',
    },
  },
} as const
