// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Yuzuha',
    name: 'standardDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yuzuha',
      attribute: 'physical',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Yuzuha',
    name: 'anomalyDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_physical: {
    sheet: 'Yuzuha',
    name: 'disorderDmgInst_physical',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'disorder',
      name: 'disorderDmgInst_physical',
    },
  },
  vortexDmgInst_physical: {
    sheet: 'Yuzuha',
    name: 'vortexDmgInst_physical',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'vortex',
      name: 'vortexDmgInst_physical',
    },
  },
  abloomDmgInst: {
    sheet: 'Yuzuha',
    name: 'abloomDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Yuzuha',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Yuzuha',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      name: 'dazeInst',
    },
  },
  'BasicAttackTanukiClaws_0:standardDmg': {
    sheet: 'Yuzuha',
    name: 'BasicAttackTanukiClaws_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTanukiClaws_0',
    },
  },
  'BasicAttackTanukiClaws_0:dazeBuildup': {
    sheet: 'Yuzuha',
    name: 'BasicAttackTanukiClaws_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTanukiClaws_0',
    },
  },
  'BasicAttackTanukiClaws_0:anomBuildup': {
    sheet: 'Yuzuha',
    name: 'BasicAttackTanukiClaws_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTanukiClaws_0',
    },
  },
  'BasicAttackTanukiClaws_1:standardDmg': {
    sheet: 'Yuzuha',
    name: 'BasicAttackTanukiClaws_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTanukiClaws_1',
    },
  },
  'BasicAttackTanukiClaws_1:dazeBuildup': {
    sheet: 'Yuzuha',
    name: 'BasicAttackTanukiClaws_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTanukiClaws_1',
    },
  },
  'BasicAttackTanukiClaws_1:anomBuildup': {
    sheet: 'Yuzuha',
    name: 'BasicAttackTanukiClaws_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTanukiClaws_1',
    },
  },
  'BasicAttackTanukiClaws_2:standardDmg': {
    sheet: 'Yuzuha',
    name: 'BasicAttackTanukiClaws_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTanukiClaws_2',
    },
  },
  'BasicAttackTanukiClaws_2:dazeBuildup': {
    sheet: 'Yuzuha',
    name: 'BasicAttackTanukiClaws_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTanukiClaws_2',
    },
  },
  'BasicAttackTanukiClaws_2:anomBuildup': {
    sheet: 'Yuzuha',
    name: 'BasicAttackTanukiClaws_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTanukiClaws_2',
    },
  },
  'BasicAttackTanukiClaws_3:standardDmg': {
    sheet: 'Yuzuha',
    name: 'BasicAttackTanukiClaws_3:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTanukiClaws_3',
    },
  },
  'BasicAttackTanukiClaws_3:dazeBuildup': {
    sheet: 'Yuzuha',
    name: 'BasicAttackTanukiClaws_3:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTanukiClaws_3',
    },
  },
  'BasicAttackTanukiClaws_3:anomBuildup': {
    sheet: 'Yuzuha',
    name: 'BasicAttackTanukiClaws_3:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTanukiClaws_3',
    },
  },
  'BasicAttackTanukiClaws_4:standardDmg': {
    sheet: 'Yuzuha',
    name: 'BasicAttackTanukiClaws_4:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTanukiClaws_4',
    },
  },
  'BasicAttackTanukiClaws_4:dazeBuildup': {
    sheet: 'Yuzuha',
    name: 'BasicAttackTanukiClaws_4:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTanukiClaws_4',
    },
  },
  'BasicAttackTanukiClaws_4:anomBuildup': {
    sheet: 'Yuzuha',
    name: 'BasicAttackTanukiClaws_4:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTanukiClaws_4',
    },
  },
  'BasicAttackTanukiCloak_0:standardDmg': {
    sheet: 'Yuzuha',
    name: 'BasicAttackTanukiCloak_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTanukiCloak_0',
    },
  },
  'BasicAttackTanukiCloak_0:dazeBuildup': {
    sheet: 'Yuzuha',
    name: 'BasicAttackTanukiCloak_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTanukiCloak_0',
    },
  },
  'BasicAttackTanukiCloak_0:anomBuildup': {
    sheet: 'Yuzuha',
    name: 'BasicAttackTanukiCloak_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTanukiCloak_0',
    },
  },
  'BasicAttackHardCandyShot_0:standardDmg': {
    sheet: 'Yuzuha',
    name: 'BasicAttackHardCandyShot_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yuzuha',
      damageType1: 'basic',
      damageType2: 'aftershock',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackHardCandyShot_0',
    },
  },
  'BasicAttackHardCandyShot_0:dazeBuildup': {
    sheet: 'Yuzuha',
    name: 'BasicAttackHardCandyShot_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yuzuha',
      damageType1: 'basic',
      damageType2: 'aftershock',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackHardCandyShot_0',
    },
  },
  'BasicAttackHardCandyShot_0:anomBuildup': {
    sheet: 'Yuzuha',
    name: 'BasicAttackHardCandyShot_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yuzuha',
      damageType1: 'basic',
      damageType2: 'aftershock',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackHardCandyShot_0',
    },
  },
  'BasicAttackSugarburstSparkles_0:standardDmg': {
    sheet: 'Yuzuha',
    name: 'BasicAttackSugarburstSparkles_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yuzuha',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackSugarburstSparkles_0',
    },
  },
  'BasicAttackSugarburstSparkles_0:dazeBuildup': {
    sheet: 'Yuzuha',
    name: 'BasicAttackSugarburstSparkles_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yuzuha',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackSugarburstSparkles_0',
    },
  },
  'BasicAttackSugarburstSparkles_0:anomBuildup': {
    sheet: 'Yuzuha',
    name: 'BasicAttackSugarburstSparkles_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yuzuha',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackSugarburstSparkles_0',
    },
  },
  'BasicAttackSugarburstSparklesMax_0:standardDmg': {
    sheet: 'Yuzuha',
    name: 'BasicAttackSugarburstSparklesMax_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yuzuha',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackSugarburstSparklesMax_0',
    },
  },
  'BasicAttackSugarburstSparklesMax_0:dazeBuildup': {
    sheet: 'Yuzuha',
    name: 'BasicAttackSugarburstSparklesMax_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yuzuha',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackSugarburstSparklesMax_0',
    },
  },
  'BasicAttackSugarburstSparklesMax_0:anomBuildup': {
    sheet: 'Yuzuha',
    name: 'BasicAttackSugarburstSparklesMax_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yuzuha',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackSugarburstSparklesMax_0',
    },
  },
  'BasicAttackTanukiHelper_0:standardDmg': {
    sheet: 'Yuzuha',
    name: 'BasicAttackTanukiHelper_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTanukiHelper_0',
    },
  },
  'BasicAttackTanukiHelper_0:dazeBuildup': {
    sheet: 'Yuzuha',
    name: 'BasicAttackTanukiHelper_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTanukiHelper_0',
    },
  },
  'BasicAttackTanukiHelper_0:anomBuildup': {
    sheet: 'Yuzuha',
    name: 'BasicAttackTanukiHelper_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTanukiHelper_0',
    },
  },
  'BasicAttackTanukiHelper_1:standardDmg': {
    sheet: 'Yuzuha',
    name: 'BasicAttackTanukiHelper_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTanukiHelper_1',
    },
  },
  'BasicAttackTanukiHelper_1:dazeBuildup': {
    sheet: 'Yuzuha',
    name: 'BasicAttackTanukiHelper_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTanukiHelper_1',
    },
  },
  'BasicAttackTanukiHelper_1:anomBuildup': {
    sheet: 'Yuzuha',
    name: 'BasicAttackTanukiHelper_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTanukiHelper_1',
    },
  },
  'DashAttackYoureOuttaLuck_0:standardDmg': {
    sheet: 'Yuzuha',
    name: 'DashAttackYoureOuttaLuck_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackYoureOuttaLuck_0',
    },
  },
  'DashAttackYoureOuttaLuck_0:dazeBuildup': {
    sheet: 'Yuzuha',
    name: 'DashAttackYoureOuttaLuck_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackYoureOuttaLuck_0',
    },
  },
  'DashAttackYoureOuttaLuck_0:anomBuildup': {
    sheet: 'Yuzuha',
    name: 'DashAttackYoureOuttaLuck_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackYoureOuttaLuck_0',
    },
  },
  'DodgeCounterTimeForPayback_0:standardDmg': {
    sheet: 'Yuzuha',
    name: 'DodgeCounterTimeForPayback_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterTimeForPayback_0',
    },
  },
  'DodgeCounterTimeForPayback_0:dazeBuildup': {
    sheet: 'Yuzuha',
    name: 'DodgeCounterTimeForPayback_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterTimeForPayback_0',
    },
  },
  'DodgeCounterTimeForPayback_0:anomBuildup': {
    sheet: 'Yuzuha',
    name: 'DodgeCounterTimeForPayback_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterTimeForPayback_0',
    },
  },
  'SpecialAttackGummyBombardment_0:standardDmg': {
    sheet: 'Yuzuha',
    name: 'SpecialAttackGummyBombardment_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackGummyBombardment_0',
    },
  },
  'SpecialAttackGummyBombardment_0:dazeBuildup': {
    sheet: 'Yuzuha',
    name: 'SpecialAttackGummyBombardment_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackGummyBombardment_0',
    },
  },
  'SpecialAttackGummyBombardment_0:anomBuildup': {
    sheet: 'Yuzuha',
    name: 'SpecialAttackGummyBombardment_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackGummyBombardment_0',
    },
  },
  'EXSpecialAttackCavityAlert_0:standardDmg': {
    sheet: 'Yuzuha',
    name: 'EXSpecialAttackCavityAlert_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackCavityAlert_0',
    },
  },
  'EXSpecialAttackCavityAlert_0:dazeBuildup': {
    sheet: 'Yuzuha',
    name: 'EXSpecialAttackCavityAlert_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackCavityAlert_0',
    },
  },
  'EXSpecialAttackCavityAlert_0:anomBuildup': {
    sheet: 'Yuzuha',
    name: 'EXSpecialAttackCavityAlert_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackCavityAlert_0',
    },
  },
  'EXSpecialAttackCavityAlertRightNow_0:standardDmg': {
    sheet: 'Yuzuha',
    name: 'EXSpecialAttackCavityAlertRightNow_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackCavityAlertRightNow_0',
    },
  },
  'EXSpecialAttackCavityAlertRightNow_0:dazeBuildup': {
    sheet: 'Yuzuha',
    name: 'EXSpecialAttackCavityAlertRightNow_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackCavityAlertRightNow_0',
    },
  },
  'EXSpecialAttackCavityAlertRightNow_0:anomBuildup': {
    sheet: 'Yuzuha',
    name: 'EXSpecialAttackCavityAlertRightNow_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackCavityAlertRightNow_0',
    },
  },
  'ChainAttackPrankAssault_0:standardDmg': {
    sheet: 'Yuzuha',
    name: 'ChainAttackPrankAssault_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackPrankAssault_0',
    },
  },
  'ChainAttackPrankAssault_0:dazeBuildup': {
    sheet: 'Yuzuha',
    name: 'ChainAttackPrankAssault_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackPrankAssault_0',
    },
  },
  'ChainAttackPrankAssault_0:anomBuildup': {
    sheet: 'Yuzuha',
    name: 'ChainAttackPrankAssault_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackPrankAssault_0',
    },
  },
  'UltimateSurrenderOrSufferTheMischief_0:standardDmg': {
    sheet: 'Yuzuha',
    name: 'UltimateSurrenderOrSufferTheMischief_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateSurrenderOrSufferTheMischief_0',
    },
  },
  'UltimateSurrenderOrSufferTheMischief_0:dazeBuildup': {
    sheet: 'Yuzuha',
    name: 'UltimateSurrenderOrSufferTheMischief_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateSurrenderOrSufferTheMischief_0',
    },
  },
  'UltimateSurrenderOrSufferTheMischief_0:anomBuildup': {
    sheet: 'Yuzuha',
    name: 'UltimateSurrenderOrSufferTheMischief_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateSurrenderOrSufferTheMischief_0',
    },
  },
  'QuickAssistDessertTime_0:standardDmg': {
    sheet: 'Yuzuha',
    name: 'QuickAssistDessertTime_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistDessertTime_0',
    },
  },
  'QuickAssistDessertTime_0:dazeBuildup': {
    sheet: 'Yuzuha',
    name: 'QuickAssistDessertTime_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistDessertTime_0',
    },
  },
  'QuickAssistDessertTime_0:anomBuildup': {
    sheet: 'Yuzuha',
    name: 'QuickAssistDessertTime_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistDessertTime_0',
    },
  },
  'DefensiveAssistReplenishYourFun_0:standardDmg': {
    sheet: 'Yuzuha',
    name: 'DefensiveAssistReplenishYourFun_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistReplenishYourFun_0',
    },
  },
  'DefensiveAssistReplenishYourFun_0:dazeBuildup': {
    sheet: 'Yuzuha',
    name: 'DefensiveAssistReplenishYourFun_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistReplenishYourFun_0',
    },
  },
  'DefensiveAssistReplenishYourFun_0:anomBuildup': {
    sheet: 'Yuzuha',
    name: 'DefensiveAssistReplenishYourFun_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistReplenishYourFun_0',
    },
  },
  'DefensiveAssistReplenishYourFun_1:standardDmg': {
    sheet: 'Yuzuha',
    name: 'DefensiveAssistReplenishYourFun_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistReplenishYourFun_1',
    },
  },
  'DefensiveAssistReplenishYourFun_1:dazeBuildup': {
    sheet: 'Yuzuha',
    name: 'DefensiveAssistReplenishYourFun_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistReplenishYourFun_1',
    },
  },
  'DefensiveAssistReplenishYourFun_1:anomBuildup': {
    sheet: 'Yuzuha',
    name: 'DefensiveAssistReplenishYourFun_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistReplenishYourFun_1',
    },
  },
  'DefensiveAssistReplenishYourFun_2:standardDmg': {
    sheet: 'Yuzuha',
    name: 'DefensiveAssistReplenishYourFun_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistReplenishYourFun_2',
    },
  },
  'DefensiveAssistReplenishYourFun_2:dazeBuildup': {
    sheet: 'Yuzuha',
    name: 'DefensiveAssistReplenishYourFun_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistReplenishYourFun_2',
    },
  },
  'DefensiveAssistReplenishYourFun_2:anomBuildup': {
    sheet: 'Yuzuha',
    name: 'DefensiveAssistReplenishYourFun_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistReplenishYourFun_2',
    },
  },
  'AssistFollowUpWeHaveCookies_0:standardDmg': {
    sheet: 'Yuzuha',
    name: 'AssistFollowUpWeHaveCookies_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpWeHaveCookies_0',
    },
  },
  'AssistFollowUpWeHaveCookies_0:dazeBuildup': {
    sheet: 'Yuzuha',
    name: 'AssistFollowUpWeHaveCookies_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpWeHaveCookies_0',
    },
  },
  'AssistFollowUpWeHaveCookies_0:anomBuildup': {
    sheet: 'Yuzuha',
    name: 'AssistFollowUpWeHaveCookies_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpWeHaveCookies_0',
    },
  },
  'AssistFollowUpStuffedHardCandyShot_0:standardDmg': {
    sheet: 'Yuzuha',
    name: 'AssistFollowUpStuffedHardCandyShot_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpStuffedHardCandyShot_0',
    },
  },
  'AssistFollowUpStuffedHardCandyShot_0:dazeBuildup': {
    sheet: 'Yuzuha',
    name: 'AssistFollowUpStuffedHardCandyShot_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpStuffedHardCandyShot_0',
    },
  },
  'AssistFollowUpStuffedHardCandyShot_0:anomBuildup': {
    sheet: 'Yuzuha',
    name: 'AssistFollowUpStuffedHardCandyShot_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpStuffedHardCandyShot_0',
    },
  },
  m6_dmg: {
    sheet: 'Yuzuha',
    name: 'm6_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yuzuha',
      attribute: 'physical',
      damageType1: 'elemental',
      name: 'm6_dmg',
    },
  },
} as const
