// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Anton',
    name: 'standardDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Anton',
      attribute: 'electric',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Anton',
    name: 'anomalyDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Anton',
      attribute: 'electric',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_electric: {
    sheet: 'Anton',
    name: 'disorderDmgInst_electric',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Anton',
      attribute: 'electric',
      damageType1: 'disorder',
      name: 'disorderDmgInst_electric',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Anton',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Anton',
      attribute: 'electric',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Anton',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Anton',
      attribute: 'electric',
      name: 'dazeInst',
    },
  },
  BasicAttackEnthusiasticDrills_0_dmg: {
    sheet: 'Anton',
    name: 'BasicAttackEnthusiasticDrills_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Anton',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackEnthusiasticDrills_0_dmg',
    },
  },
  BasicAttackEnthusiasticDrills_0_daze: {
    sheet: 'Anton',
    name: 'BasicAttackEnthusiasticDrills_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Anton',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackEnthusiasticDrills_0_daze',
    },
  },
  BasicAttackEnthusiasticDrills_0_anomBuildup: {
    sheet: 'Anton',
    name: 'BasicAttackEnthusiasticDrills_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Anton',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackEnthusiasticDrills_0_anomBuildup',
    },
  },
  BasicAttackEnthusiasticDrills_1_dmg: {
    sheet: 'Anton',
    name: 'BasicAttackEnthusiasticDrills_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Anton',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackEnthusiasticDrills_1_dmg',
    },
  },
  BasicAttackEnthusiasticDrills_1_daze: {
    sheet: 'Anton',
    name: 'BasicAttackEnthusiasticDrills_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Anton',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackEnthusiasticDrills_1_daze',
    },
  },
  BasicAttackEnthusiasticDrills_1_anomBuildup: {
    sheet: 'Anton',
    name: 'BasicAttackEnthusiasticDrills_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Anton',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackEnthusiasticDrills_1_anomBuildup',
    },
  },
  BasicAttackEnthusiasticDrills_2_dmg: {
    sheet: 'Anton',
    name: 'BasicAttackEnthusiasticDrills_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Anton',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackEnthusiasticDrills_2_dmg',
    },
  },
  BasicAttackEnthusiasticDrills_2_daze: {
    sheet: 'Anton',
    name: 'BasicAttackEnthusiasticDrills_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Anton',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackEnthusiasticDrills_2_daze',
    },
  },
  BasicAttackEnthusiasticDrills_2_anomBuildup: {
    sheet: 'Anton',
    name: 'BasicAttackEnthusiasticDrills_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Anton',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackEnthusiasticDrills_2_anomBuildup',
    },
  },
  BasicAttackEnthusiasticDrills_3_dmg: {
    sheet: 'Anton',
    name: 'BasicAttackEnthusiasticDrills_3_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Anton',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackEnthusiasticDrills_3_dmg',
    },
  },
  BasicAttackEnthusiasticDrills_3_daze: {
    sheet: 'Anton',
    name: 'BasicAttackEnthusiasticDrills_3_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Anton',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackEnthusiasticDrills_3_daze',
    },
  },
  BasicAttackEnthusiasticDrills_3_anomBuildup: {
    sheet: 'Anton',
    name: 'BasicAttackEnthusiasticDrills_3_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Anton',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackEnthusiasticDrills_3_anomBuildup',
    },
  },
  BasicAttackEnthusiasticDrillsBurstMode_0_dmg: {
    sheet: 'Anton',
    name: 'BasicAttackEnthusiasticDrillsBurstMode_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Anton',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEnthusiasticDrillsBurstMode_0_dmg',
    },
  },
  BasicAttackEnthusiasticDrillsBurstMode_0_daze: {
    sheet: 'Anton',
    name: 'BasicAttackEnthusiasticDrillsBurstMode_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Anton',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEnthusiasticDrillsBurstMode_0_daze',
    },
  },
  BasicAttackEnthusiasticDrillsBurstMode_0_anomBuildup: {
    sheet: 'Anton',
    name: 'BasicAttackEnthusiasticDrillsBurstMode_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Anton',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEnthusiasticDrillsBurstMode_0_anomBuildup',
    },
  },
  BasicAttackEnthusiasticDrillsBurstMode_1_dmg: {
    sheet: 'Anton',
    name: 'BasicAttackEnthusiasticDrillsBurstMode_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Anton',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEnthusiasticDrillsBurstMode_1_dmg',
    },
  },
  BasicAttackEnthusiasticDrillsBurstMode_1_daze: {
    sheet: 'Anton',
    name: 'BasicAttackEnthusiasticDrillsBurstMode_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Anton',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEnthusiasticDrillsBurstMode_1_daze',
    },
  },
  BasicAttackEnthusiasticDrillsBurstMode_1_anomBuildup: {
    sheet: 'Anton',
    name: 'BasicAttackEnthusiasticDrillsBurstMode_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Anton',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEnthusiasticDrillsBurstMode_1_anomBuildup',
    },
  },
  BasicAttackEnthusiasticDrillsBurstMode_2_dmg: {
    sheet: 'Anton',
    name: 'BasicAttackEnthusiasticDrillsBurstMode_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Anton',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEnthusiasticDrillsBurstMode_2_dmg',
    },
  },
  BasicAttackEnthusiasticDrillsBurstMode_2_daze: {
    sheet: 'Anton',
    name: 'BasicAttackEnthusiasticDrillsBurstMode_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Anton',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEnthusiasticDrillsBurstMode_2_daze',
    },
  },
  BasicAttackEnthusiasticDrillsBurstMode_2_anomBuildup: {
    sheet: 'Anton',
    name: 'BasicAttackEnthusiasticDrillsBurstMode_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Anton',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEnthusiasticDrillsBurstMode_2_anomBuildup',
    },
  },
  DashAttackFireWithFire_0_dmg: {
    sheet: 'Anton',
    name: 'DashAttackFireWithFire_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Anton',
      damageType1: 'dash',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttackFireWithFire_0_dmg',
    },
  },
  DashAttackFireWithFire_0_daze: {
    sheet: 'Anton',
    name: 'DashAttackFireWithFire_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Anton',
      damageType1: 'dash',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttackFireWithFire_0_daze',
    },
  },
  DashAttackFireWithFire_0_anomBuildup: {
    sheet: 'Anton',
    name: 'DashAttackFireWithFire_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Anton',
      damageType1: 'dash',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttackFireWithFire_0_anomBuildup',
    },
  },
  DodgeCounterRetaliation_0_dmg: {
    sheet: 'Anton',
    name: 'DodgeCounterRetaliation_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Anton',
      damageType1: 'dodgeCounter',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterRetaliation_0_dmg',
    },
  },
  DodgeCounterRetaliation_0_daze: {
    sheet: 'Anton',
    name: 'DodgeCounterRetaliation_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Anton',
      damageType1: 'dodgeCounter',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterRetaliation_0_daze',
    },
  },
  DodgeCounterRetaliation_0_anomBuildup: {
    sheet: 'Anton',
    name: 'DodgeCounterRetaliation_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Anton',
      damageType1: 'dodgeCounter',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterRetaliation_0_anomBuildup',
    },
  },
  DodgeCounterOverloadDrillBurstMode_0_dmg: {
    sheet: 'Anton',
    name: 'DodgeCounterOverloadDrillBurstMode_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Anton',
      attribute: 'electric',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterOverloadDrillBurstMode_0_dmg',
    },
  },
  DodgeCounterOverloadDrillBurstMode_0_daze: {
    sheet: 'Anton',
    name: 'DodgeCounterOverloadDrillBurstMode_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Anton',
      attribute: 'electric',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterOverloadDrillBurstMode_0_daze',
    },
  },
  DodgeCounterOverloadDrillBurstMode_0_anomBuildup: {
    sheet: 'Anton',
    name: 'DodgeCounterOverloadDrillBurstMode_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Anton',
      attribute: 'electric',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterOverloadDrillBurstMode_0_anomBuildup',
    },
  },
  SpecialAttackSpinBro_0_dmg: {
    sheet: 'Anton',
    name: 'SpecialAttackSpinBro_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Anton',
      attribute: 'electric',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackSpinBro_0_dmg',
    },
  },
  SpecialAttackSpinBro_0_daze: {
    sheet: 'Anton',
    name: 'SpecialAttackSpinBro_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Anton',
      attribute: 'electric',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackSpinBro_0_daze',
    },
  },
  SpecialAttackSpinBro_0_anomBuildup: {
    sheet: 'Anton',
    name: 'SpecialAttackSpinBro_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Anton',
      attribute: 'electric',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackSpinBro_0_anomBuildup',
    },
  },
  EXSpecialAttackSmashTheHorizonBro_0_dmg: {
    sheet: 'Anton',
    name: 'EXSpecialAttackSmashTheHorizonBro_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Anton',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackSmashTheHorizonBro_0_dmg',
    },
  },
  EXSpecialAttackSmashTheHorizonBro_0_daze: {
    sheet: 'Anton',
    name: 'EXSpecialAttackSmashTheHorizonBro_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Anton',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackSmashTheHorizonBro_0_daze',
    },
  },
  EXSpecialAttackSmashTheHorizonBro_0_anomBuildup: {
    sheet: 'Anton',
    name: 'EXSpecialAttackSmashTheHorizonBro_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Anton',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackSmashTheHorizonBro_0_anomBuildup',
    },
  },
  SpecialAttackExplosiveDrillBurstMode_0_dmg: {
    sheet: 'Anton',
    name: 'SpecialAttackExplosiveDrillBurstMode_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Anton',
      attribute: 'electric',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackExplosiveDrillBurstMode_0_dmg',
    },
  },
  SpecialAttackExplosiveDrillBurstMode_0_daze: {
    sheet: 'Anton',
    name: 'SpecialAttackExplosiveDrillBurstMode_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Anton',
      attribute: 'electric',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackExplosiveDrillBurstMode_0_daze',
    },
  },
  SpecialAttackExplosiveDrillBurstMode_0_anomBuildup: {
    sheet: 'Anton',
    name: 'SpecialAttackExplosiveDrillBurstMode_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Anton',
      attribute: 'electric',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackExplosiveDrillBurstMode_0_anomBuildup',
    },
  },
  ChainAttackGoGoGo_0_dmg: {
    sheet: 'Anton',
    name: 'ChainAttackGoGoGo_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Anton',
      attribute: 'electric',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackGoGoGo_0_dmg',
    },
  },
  ChainAttackGoGoGo_0_daze: {
    sheet: 'Anton',
    name: 'ChainAttackGoGoGo_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Anton',
      attribute: 'electric',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackGoGoGo_0_daze',
    },
  },
  ChainAttackGoGoGo_0_anomBuildup: {
    sheet: 'Anton',
    name: 'ChainAttackGoGoGo_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Anton',
      attribute: 'electric',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackGoGoGo_0_anomBuildup',
    },
  },
  UltimateGoGoGoGoGo_0_dmg: {
    sheet: 'Anton',
    name: 'UltimateGoGoGoGoGo_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Anton',
      attribute: 'electric',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateGoGoGoGoGo_0_dmg',
    },
  },
  UltimateGoGoGoGoGo_0_daze: {
    sheet: 'Anton',
    name: 'UltimateGoGoGoGoGo_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Anton',
      attribute: 'electric',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateGoGoGoGoGo_0_daze',
    },
  },
  UltimateGoGoGoGoGo_0_anomBuildup: {
    sheet: 'Anton',
    name: 'UltimateGoGoGoGoGo_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Anton',
      attribute: 'electric',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateGoGoGoGoGo_0_anomBuildup',
    },
  },
  QuickAssistShoulderToShoulder_0_dmg: {
    sheet: 'Anton',
    name: 'QuickAssistShoulderToShoulder_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Anton',
      damageType1: 'quickAssist',
      attribute: 'physical',
      skillType: 'assistSkill',
      name: 'QuickAssistShoulderToShoulder_0_dmg',
    },
  },
  QuickAssistShoulderToShoulder_0_daze: {
    sheet: 'Anton',
    name: 'QuickAssistShoulderToShoulder_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Anton',
      damageType1: 'quickAssist',
      attribute: 'physical',
      skillType: 'assistSkill',
      name: 'QuickAssistShoulderToShoulder_0_daze',
    },
  },
  QuickAssistShoulderToShoulder_0_anomBuildup: {
    sheet: 'Anton',
    name: 'QuickAssistShoulderToShoulder_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Anton',
      damageType1: 'quickAssist',
      attribute: 'physical',
      skillType: 'assistSkill',
      name: 'QuickAssistShoulderToShoulder_0_anomBuildup',
    },
  },
  QuickAssistProtectiveDrillBurstMode_0_dmg: {
    sheet: 'Anton',
    name: 'QuickAssistProtectiveDrillBurstMode_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Anton',
      attribute: 'electric',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistProtectiveDrillBurstMode_0_dmg',
    },
  },
  QuickAssistProtectiveDrillBurstMode_0_daze: {
    sheet: 'Anton',
    name: 'QuickAssistProtectiveDrillBurstMode_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Anton',
      attribute: 'electric',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistProtectiveDrillBurstMode_0_daze',
    },
  },
  QuickAssistProtectiveDrillBurstMode_0_anomBuildup: {
    sheet: 'Anton',
    name: 'QuickAssistProtectiveDrillBurstMode_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Anton',
      attribute: 'electric',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistProtectiveDrillBurstMode_0_anomBuildup',
    },
  },
  DefensiveAssistIronWrist_0_dmg: {
    sheet: 'Anton',
    name: 'DefensiveAssistIronWrist_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Anton',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistIronWrist_0_dmg',
    },
  },
  DefensiveAssistIronWrist_0_daze: {
    sheet: 'Anton',
    name: 'DefensiveAssistIronWrist_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Anton',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistIronWrist_0_daze',
    },
  },
  DefensiveAssistIronWrist_0_anomBuildup: {
    sheet: 'Anton',
    name: 'DefensiveAssistIronWrist_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Anton',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistIronWrist_0_anomBuildup',
    },
  },
  DefensiveAssistIronWrist_1_dmg: {
    sheet: 'Anton',
    name: 'DefensiveAssistIronWrist_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Anton',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistIronWrist_1_dmg',
    },
  },
  DefensiveAssistIronWrist_1_daze: {
    sheet: 'Anton',
    name: 'DefensiveAssistIronWrist_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Anton',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistIronWrist_1_daze',
    },
  },
  DefensiveAssistIronWrist_1_anomBuildup: {
    sheet: 'Anton',
    name: 'DefensiveAssistIronWrist_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Anton',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistIronWrist_1_anomBuildup',
    },
  },
  DefensiveAssistIronWrist_2_dmg: {
    sheet: 'Anton',
    name: 'DefensiveAssistIronWrist_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Anton',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistIronWrist_2_dmg',
    },
  },
  DefensiveAssistIronWrist_2_daze: {
    sheet: 'Anton',
    name: 'DefensiveAssistIronWrist_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Anton',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistIronWrist_2_daze',
    },
  },
  DefensiveAssistIronWrist_2_anomBuildup: {
    sheet: 'Anton',
    name: 'DefensiveAssistIronWrist_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Anton',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistIronWrist_2_anomBuildup',
    },
  },
  AssistFollowUpLimitBurst_0_dmg: {
    sheet: 'Anton',
    name: 'AssistFollowUpLimitBurst_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Anton',
      attribute: 'electric',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpLimitBurst_0_dmg',
    },
  },
  AssistFollowUpLimitBurst_0_daze: {
    sheet: 'Anton',
    name: 'AssistFollowUpLimitBurst_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Anton',
      attribute: 'electric',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpLimitBurst_0_daze',
    },
  },
  AssistFollowUpLimitBurst_0_anomBuildup: {
    sheet: 'Anton',
    name: 'AssistFollowUpLimitBurst_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Anton',
      attribute: 'electric',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpLimitBurst_0_anomBuildup',
    },
  },
  m2_shield: {
    sheet: 'Anton',
    name: 'm2_shield',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'shield',
      sheet: 'Anton',
      name: 'm2_shield',
    },
  },
} as const
