// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Velina',
    name: 'standardDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Velina',
      attribute: 'wind',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Velina',
    name: 'anomalyDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_wind: {
    sheet: 'Velina',
    name: 'disorderDmgInst_wind',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'disorder',
      name: 'disorderDmgInst_wind',
    },
  },
  vortexDmgInst_electric: {
    sheet: 'Velina',
    name: 'vortexDmgInst_electric',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Velina',
      attribute: 'electric',
      damageType1: 'vortex',
      name: 'vortexDmgInst_electric',
    },
  },
  vortexDmgInst_fire: {
    sheet: 'Velina',
    name: 'vortexDmgInst_fire',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Velina',
      attribute: 'fire',
      damageType1: 'vortex',
      name: 'vortexDmgInst_fire',
    },
  },
  vortexDmgInst_ice: {
    sheet: 'Velina',
    name: 'vortexDmgInst_ice',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Velina',
      attribute: 'ice',
      damageType1: 'vortex',
      name: 'vortexDmgInst_ice',
    },
  },
  vortexDmgInst_physical: {
    sheet: 'Velina',
    name: 'vortexDmgInst_physical',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Velina',
      attribute: 'physical',
      damageType1: 'vortex',
      name: 'vortexDmgInst_physical',
    },
  },
  vortexDmgInst_ether: {
    sheet: 'Velina',
    name: 'vortexDmgInst_ether',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Velina',
      attribute: 'ether',
      damageType1: 'vortex',
      name: 'vortexDmgInst_ether',
    },
  },
  vortexDmgInst_frost: {
    sheet: 'Velina',
    name: 'vortexDmgInst_frost',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Velina',
      attribute: 'ice',
      damageType1: 'vortex',
      name: 'vortexDmgInst_frost',
    },
  },
  abloomDmgInst: {
    sheet: 'Velina',
    name: 'abloomDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Velina',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Velina',
      attribute: 'wind',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Velina',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Velina',
      attribute: 'wind',
      name: 'dazeInst',
    },
  },
  'BasicAttackDancingFans_0:standardDmg': {
    sheet: 'Velina',
    name: 'BasicAttackDancingFans_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackDancingFans_0',
    },
  },
  'BasicAttackDancingFans_0:dazeBuildup': {
    sheet: 'Velina',
    name: 'BasicAttackDancingFans_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackDancingFans_0',
    },
  },
  'BasicAttackDancingFans_0:anomBuildup': {
    sheet: 'Velina',
    name: 'BasicAttackDancingFans_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackDancingFans_0',
    },
  },
  'BasicAttackDancingFans_1:standardDmg': {
    sheet: 'Velina',
    name: 'BasicAttackDancingFans_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackDancingFans_1',
    },
  },
  'BasicAttackDancingFans_1:dazeBuildup': {
    sheet: 'Velina',
    name: 'BasicAttackDancingFans_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackDancingFans_1',
    },
  },
  'BasicAttackDancingFans_1:anomBuildup': {
    sheet: 'Velina',
    name: 'BasicAttackDancingFans_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackDancingFans_1',
    },
  },
  'BasicAttackDancingFans_2:standardDmg': {
    sheet: 'Velina',
    name: 'BasicAttackDancingFans_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackDancingFans_2',
    },
  },
  'BasicAttackDancingFans_2:dazeBuildup': {
    sheet: 'Velina',
    name: 'BasicAttackDancingFans_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackDancingFans_2',
    },
  },
  'BasicAttackDancingFans_2:anomBuildup': {
    sheet: 'Velina',
    name: 'BasicAttackDancingFans_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackDancingFans_2',
    },
  },
  'BasicAttackDancingFans_3:standardDmg': {
    sheet: 'Velina',
    name: 'BasicAttackDancingFans_3:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackDancingFans_3',
    },
  },
  'BasicAttackDancingFans_3:dazeBuildup': {
    sheet: 'Velina',
    name: 'BasicAttackDancingFans_3:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackDancingFans_3',
    },
  },
  'BasicAttackDancingFans_3:anomBuildup': {
    sheet: 'Velina',
    name: 'BasicAttackDancingFans_3:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackDancingFans_3',
    },
  },
  'BasicAttackDancingFans_4:standardDmg': {
    sheet: 'Velina',
    name: 'BasicAttackDancingFans_4:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackDancingFans_4',
    },
  },
  'BasicAttackDancingFans_4:dazeBuildup': {
    sheet: 'Velina',
    name: 'BasicAttackDancingFans_4:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackDancingFans_4',
    },
  },
  'BasicAttackDancingFans_4:anomBuildup': {
    sheet: 'Velina',
    name: 'BasicAttackDancingFans_4:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackDancingFans_4',
    },
  },
  'DashAttackGaleStep_0:standardDmg': {
    sheet: 'Velina',
    name: 'DashAttackGaleStep_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'dash',
      skillType1: 'dodgeSkill',
      name: 'DashAttackGaleStep_0',
    },
  },
  'DashAttackGaleStep_0:dazeBuildup': {
    sheet: 'Velina',
    name: 'DashAttackGaleStep_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'dash',
      skillType1: 'dodgeSkill',
      name: 'DashAttackGaleStep_0',
    },
  },
  'DashAttackGaleStep_0:anomBuildup': {
    sheet: 'Velina',
    name: 'DashAttackGaleStep_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'dash',
      skillType1: 'dodgeSkill',
      name: 'DashAttackGaleStep_0',
    },
  },
  'DodgeCounterCloudrend_0:standardDmg': {
    sheet: 'Velina',
    name: 'DodgeCounterCloudrend_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'dodgeCounter',
      skillType1: 'dodgeSkill',
      name: 'DodgeCounterCloudrend_0',
    },
  },
  'DodgeCounterCloudrend_0:dazeBuildup': {
    sheet: 'Velina',
    name: 'DodgeCounterCloudrend_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'dodgeCounter',
      skillType1: 'dodgeSkill',
      name: 'DodgeCounterCloudrend_0',
    },
  },
  'DodgeCounterCloudrend_0:anomBuildup': {
    sheet: 'Velina',
    name: 'DodgeCounterCloudrend_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'dodgeCounter',
      skillType1: 'dodgeSkill',
      name: 'DodgeCounterCloudrend_0',
    },
  },
  'SpecialAttackWindShearPurgingSurge_0:standardDmg': {
    sheet: 'Velina',
    name: 'SpecialAttackWindShearPurgingSurge_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackWindShearPurgingSurge_0',
    },
  },
  'SpecialAttackWindShearPurgingSurge_0:dazeBuildup': {
    sheet: 'Velina',
    name: 'SpecialAttackWindShearPurgingSurge_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackWindShearPurgingSurge_0',
    },
  },
  'SpecialAttackWindShearPurgingSurge_0:anomBuildup': {
    sheet: 'Velina',
    name: 'SpecialAttackWindShearPurgingSurge_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackWindShearPurgingSurge_0',
    },
  },
  'EXSpecialAttackWindShearPurifyingRise_0:standardDmg': {
    sheet: 'Velina',
    name: 'EXSpecialAttackWindShearPurifyingRise_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackWindShearPurifyingRise_0',
    },
  },
  'EXSpecialAttackWindShearPurifyingRise_0:dazeBuildup': {
    sheet: 'Velina',
    name: 'EXSpecialAttackWindShearPurifyingRise_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackWindShearPurifyingRise_0',
    },
  },
  'EXSpecialAttackWindShearPurifyingRise_0:anomBuildup': {
    sheet: 'Velina',
    name: 'EXSpecialAttackWindShearPurifyingRise_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackWindShearPurifyingRise_0',
    },
  },
  'EXSpecialAttackWindShearTripleDeathblow_0:standardDmg': {
    sheet: 'Velina',
    name: 'EXSpecialAttackWindShearTripleDeathblow_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackWindShearTripleDeathblow_0',
    },
  },
  'EXSpecialAttackWindShearTripleDeathblow_0:dazeBuildup': {
    sheet: 'Velina',
    name: 'EXSpecialAttackWindShearTripleDeathblow_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackWindShearTripleDeathblow_0',
    },
  },
  'EXSpecialAttackWindShearTripleDeathblow_0:anomBuildup': {
    sheet: 'Velina',
    name: 'EXSpecialAttackWindShearTripleDeathblow_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackWindShearTripleDeathblow_0',
    },
  },
  'EXSpecialAttackWindShearEyeOfTheStorm_0:standardDmg': {
    sheet: 'Velina',
    name: 'EXSpecialAttackWindShearEyeOfTheStorm_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackWindShearEyeOfTheStorm_0',
    },
  },
  'EXSpecialAttackWindShearEyeOfTheStorm_0:dazeBuildup': {
    sheet: 'Velina',
    name: 'EXSpecialAttackWindShearEyeOfTheStorm_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackWindShearEyeOfTheStorm_0',
    },
  },
  'EXSpecialAttackWindShearEyeOfTheStorm_0:anomBuildup': {
    sheet: 'Velina',
    name: 'EXSpecialAttackWindShearEyeOfTheStorm_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackWindShearEyeOfTheStorm_0',
    },
  },
  'SweepingCyclone_0:standardDmg': {
    sheet: 'Velina',
    name: 'SweepingCyclone_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'SweepingCyclone_0',
    },
  },
  'SweepingCyclone_0:dazeBuildup': {
    sheet: 'Velina',
    name: 'SweepingCyclone_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'SweepingCyclone_0',
    },
  },
  'SweepingCyclone_0:anomBuildup': {
    sheet: 'Velina',
    name: 'SweepingCyclone_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'SweepingCyclone_0',
    },
  },
  'SweepingCyclone_1:standardDmg': {
    sheet: 'Velina',
    name: 'SweepingCyclone_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'SweepingCyclone_1',
    },
  },
  'SweepingCyclone_1:dazeBuildup': {
    sheet: 'Velina',
    name: 'SweepingCyclone_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'SweepingCyclone_1',
    },
  },
  'SweepingCyclone_1:anomBuildup': {
    sheet: 'Velina',
    name: 'SweepingCyclone_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'SweepingCyclone_1',
    },
  },
  'CondensedCyclone_0:standardDmg': {
    sheet: 'Velina',
    name: 'CondensedCyclone_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'CondensedCyclone_0',
    },
  },
  'CondensedCyclone_0:dazeBuildup': {
    sheet: 'Velina',
    name: 'CondensedCyclone_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'CondensedCyclone_0',
    },
  },
  'CondensedCyclone_0:anomBuildup': {
    sheet: 'Velina',
    name: 'CondensedCyclone_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'CondensedCyclone_0',
    },
  },
  'ChainAttackThousandfoldSpiral_0:standardDmg': {
    sheet: 'Velina',
    name: 'ChainAttackThousandfoldSpiral_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'chain',
      skillType1: 'chainSkill',
      name: 'ChainAttackThousandfoldSpiral_0',
    },
  },
  'ChainAttackThousandfoldSpiral_0:dazeBuildup': {
    sheet: 'Velina',
    name: 'ChainAttackThousandfoldSpiral_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'chain',
      skillType1: 'chainSkill',
      name: 'ChainAttackThousandfoldSpiral_0',
    },
  },
  'ChainAttackThousandfoldSpiral_0:anomBuildup': {
    sheet: 'Velina',
    name: 'ChainAttackThousandfoldSpiral_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'chain',
      skillType1: 'chainSkill',
      name: 'ChainAttackThousandfoldSpiral_0',
    },
  },
  'UltimateHeedTheTempest_0:standardDmg': {
    sheet: 'Velina',
    name: 'UltimateHeedTheTempest_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'ult',
      skillType1: 'chainSkill',
      name: 'UltimateHeedTheTempest_0',
    },
  },
  'UltimateHeedTheTempest_0:dazeBuildup': {
    sheet: 'Velina',
    name: 'UltimateHeedTheTempest_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'ult',
      skillType1: 'chainSkill',
      name: 'UltimateHeedTheTempest_0',
    },
  },
  'UltimateHeedTheTempest_0:anomBuildup': {
    sheet: 'Velina',
    name: 'UltimateHeedTheTempest_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'ult',
      skillType1: 'chainSkill',
      name: 'UltimateHeedTheTempest_0',
    },
  },
  'QuickAssistEmergencyProtocol_0:standardDmg': {
    sheet: 'Velina',
    name: 'QuickAssistEmergencyProtocol_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'quickAssist',
      skillType1: 'assistSkill',
      name: 'QuickAssistEmergencyProtocol_0',
    },
  },
  'QuickAssistEmergencyProtocol_0:dazeBuildup': {
    sheet: 'Velina',
    name: 'QuickAssistEmergencyProtocol_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'quickAssist',
      skillType1: 'assistSkill',
      name: 'QuickAssistEmergencyProtocol_0',
    },
  },
  'QuickAssistEmergencyProtocol_0:anomBuildup': {
    sheet: 'Velina',
    name: 'QuickAssistEmergencyProtocol_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'quickAssist',
      skillType1: 'assistSkill',
      name: 'QuickAssistEmergencyProtocol_0',
    },
  },
  'DefensiveAssistJudiciousIntervention_0:standardDmg': {
    sheet: 'Velina',
    name: 'DefensiveAssistJudiciousIntervention_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistJudiciousIntervention_0',
    },
  },
  'DefensiveAssistJudiciousIntervention_0:dazeBuildup': {
    sheet: 'Velina',
    name: 'DefensiveAssistJudiciousIntervention_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistJudiciousIntervention_0',
    },
  },
  'DefensiveAssistJudiciousIntervention_0:anomBuildup': {
    sheet: 'Velina',
    name: 'DefensiveAssistJudiciousIntervention_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistJudiciousIntervention_0',
    },
  },
  'DefensiveAssistJudiciousIntervention_1:standardDmg': {
    sheet: 'Velina',
    name: 'DefensiveAssistJudiciousIntervention_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistJudiciousIntervention_1',
    },
  },
  'DefensiveAssistJudiciousIntervention_1:dazeBuildup': {
    sheet: 'Velina',
    name: 'DefensiveAssistJudiciousIntervention_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistJudiciousIntervention_1',
    },
  },
  'DefensiveAssistJudiciousIntervention_1:anomBuildup': {
    sheet: 'Velina',
    name: 'DefensiveAssistJudiciousIntervention_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistJudiciousIntervention_1',
    },
  },
  'DefensiveAssistJudiciousIntervention_2:standardDmg': {
    sheet: 'Velina',
    name: 'DefensiveAssistJudiciousIntervention_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistJudiciousIntervention_2',
    },
  },
  'DefensiveAssistJudiciousIntervention_2:dazeBuildup': {
    sheet: 'Velina',
    name: 'DefensiveAssistJudiciousIntervention_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistJudiciousIntervention_2',
    },
  },
  'DefensiveAssistJudiciousIntervention_2:anomBuildup': {
    sheet: 'Velina',
    name: 'DefensiveAssistJudiciousIntervention_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistJudiciousIntervention_2',
    },
  },
  'AssistFollowUpNegotiationTechniques_0:standardDmg': {
    sheet: 'Velina',
    name: 'AssistFollowUpNegotiationTechniques_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'assistFollowUp',
      skillType1: 'assistSkill',
      name: 'AssistFollowUpNegotiationTechniques_0',
    },
  },
  'AssistFollowUpNegotiationTechniques_0:dazeBuildup': {
    sheet: 'Velina',
    name: 'AssistFollowUpNegotiationTechniques_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'assistFollowUp',
      skillType1: 'assistSkill',
      name: 'AssistFollowUpNegotiationTechniques_0',
    },
  },
  'AssistFollowUpNegotiationTechniques_0:anomBuildup': {
    sheet: 'Velina',
    name: 'AssistFollowUpNegotiationTechniques_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Velina',
      attribute: 'wind',
      damageType1: 'assistFollowUp',
      skillType1: 'assistSkill',
      name: 'AssistFollowUpNegotiationTechniques_0',
    },
  },
} as const
