// WARNING: Generated file, do not modify
export const buffs = {
  core_crit_: {
    sheet: 'Hugo',
    name: 'core_crit_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_',
      sheet: 'Hugo',
      name: 'core_crit_',
    },
  },
  core_crit_dmg_: {
    sheet: 'Hugo',
    name: 'core_crit_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_dmg_',
      sheet: 'Hugo',
      name: 'core_crit_dmg_',
    },
  },
  core_atk: {
    sheet: 'Hugo',
    name: 'core_atk',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'atk',
      sheet: 'Hugo',
      name: 'core_atk',
    },
  },
  core_exSpecial_mv_mult_: {
    sheet: 'Hugo',
    name: 'core_exSpecial_mv_mult_',
    tag: {
      et: 'display',
      qt: 'dmg',
      q: 'mv_mult_',
      sheet: 'Hugo',
      damageType1: 'exSpecial',
      name: 'core_exSpecial_mv_mult_',
    },
  },
  core_ult_mv_mult_: {
    sheet: 'Hugo',
    name: 'core_ult_mv_mult_',
    tag: {
      et: 'display',
      qt: 'dmg',
      q: 'mv_mult_',
      sheet: 'Hugo',
      damageType1: 'ult',
      name: 'core_ult_mv_mult_',
    },
  },
  core_exSpecial_dazeInc_: {
    sheet: 'Hugo',
    name: 'core_exSpecial_dazeInc_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dazeInc_',
      sheet: 'Hugo',
      damageType1: 'exSpecial',
      name: 'core_exSpecial_dazeInc_',
    },
  },
  ability_chain_dmg_: {
    sheet: 'Hugo',
    name: 'ability_chain_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dmg_',
      sheet: 'Hugo',
      damageType1: 'chain',
      name: 'ability_chain_dmg_',
    },
  },
  ability_exSpecial_dmg_: {
    sheet: 'Hugo',
    name: 'ability_exSpecial_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dmg_',
      sheet: 'Hugo',
      damageType1: 'exSpecial',
      name: 'ability_exSpecial_dmg_',
    },
  },
  ability_ult_dmg_: {
    sheet: 'Hugo',
    name: 'ability_ult_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dmg_',
      sheet: 'Hugo',
      damageType1: 'ult',
      name: 'ability_ult_dmg_',
    },
  },
  m1_exSpecial_crit_: {
    sheet: 'Hugo',
    name: 'm1_exSpecial_crit_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_',
      sheet: 'Hugo',
      damageType1: 'exSpecial',
      name: 'm1_exSpecial_crit_',
    },
  },
  m1_exSpecial_crit_dmg_: {
    sheet: 'Hugo',
    name: 'm1_exSpecial_crit_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_dmg_',
      sheet: 'Hugo',
      damageType1: 'exSpecial',
      name: 'm1_exSpecial_crit_dmg_',
    },
  },
  m1_ult_crit_: {
    sheet: 'Hugo',
    name: 'm1_ult_crit_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_',
      sheet: 'Hugo',
      damageType1: 'ult',
      name: 'm1_ult_crit_',
    },
  },
  m1_ult_crit_dmg_: {
    sheet: 'Hugo',
    name: 'm1_ult_crit_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_dmg_',
      sheet: 'Hugo',
      damageType1: 'ult',
      name: 'm1_ult_crit_dmg_',
    },
  },
  m2_exSpecial_defIgn_: {
    sheet: 'Hugo',
    name: 'm2_exSpecial_defIgn_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'defIgn_',
      sheet: 'Hugo',
      damageType1: 'exSpecial',
      name: 'm2_exSpecial_defIgn_',
    },
  },
  m2_ult_defIgn_: {
    sheet: 'Hugo',
    name: 'm2_ult_defIgn_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'defIgn_',
      sheet: 'Hugo',
      damageType1: 'ult',
      name: 'm2_ult_defIgn_',
    },
  },
  m4_ice_resIgn_: {
    sheet: 'Hugo',
    name: 'm4_ice_resIgn_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'resIgn_',
      sheet: 'Hugo',
      attribute: 'ice',
      name: 'm4_ice_resIgn_',
    },
  },
  m6_exSpecial_dmg_: {
    sheet: 'Hugo',
    name: 'm6_exSpecial_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dmg_',
      sheet: 'Hugo',
      damageType1: 'exSpecial',
      name: 'm6_exSpecial_dmg_',
    },
  },
  m6_ult_dmg_: {
    sheet: 'Hugo',
    name: 'm6_ult_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dmg_',
      sheet: 'Hugo',
      damageType1: 'ult',
      name: 'm6_ult_dmg_',
    },
  },
  m6_exSpecial_mv_mult_: {
    sheet: 'Hugo',
    name: 'm6_exSpecial_mv_mult_',
    tag: {
      et: 'display',
      qt: 'dmg',
      q: 'mv_mult_',
      sheet: 'Hugo',
      damageType1: 'exSpecial',
      name: 'm6_exSpecial_mv_mult_',
    },
  },
} as const
