// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Hugo',
    name: 'standardDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Hugo',
      attribute: 'ice',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Hugo',
    name: 'anomalyDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_ice: {
    sheet: 'Hugo',
    name: 'disorderDmgInst_ice',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'disorder',
      name: 'disorderDmgInst_ice',
    },
  },
  vortexDmgInst_ice: {
    sheet: 'Hugo',
    name: 'vortexDmgInst_ice',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'vortex',
      name: 'vortexDmgInst_ice',
    },
  },
  abloomDmgInst: {
    sheet: 'Hugo',
    name: 'abloomDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Hugo',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Hugo',
      attribute: 'ice',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Hugo',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Hugo',
      attribute: 'ice',
      name: 'dazeInst',
    },
  },
  'BasicAttackDarkAbyssQuartet_0:standardDmg': {
    sheet: 'Hugo',
    name: 'BasicAttackDarkAbyssQuartet_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Hugo',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackDarkAbyssQuartet_0',
    },
  },
  'BasicAttackDarkAbyssQuartet_0:dazeBuildup': {
    sheet: 'Hugo',
    name: 'BasicAttackDarkAbyssQuartet_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Hugo',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackDarkAbyssQuartet_0',
    },
  },
  'BasicAttackDarkAbyssQuartet_0:anomBuildup': {
    sheet: 'Hugo',
    name: 'BasicAttackDarkAbyssQuartet_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Hugo',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackDarkAbyssQuartet_0',
    },
  },
  'BasicAttackDarkAbyssQuartet_1:standardDmg': {
    sheet: 'Hugo',
    name: 'BasicAttackDarkAbyssQuartet_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Hugo',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackDarkAbyssQuartet_1',
    },
  },
  'BasicAttackDarkAbyssQuartet_1:dazeBuildup': {
    sheet: 'Hugo',
    name: 'BasicAttackDarkAbyssQuartet_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Hugo',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackDarkAbyssQuartet_1',
    },
  },
  'BasicAttackDarkAbyssQuartet_1:anomBuildup': {
    sheet: 'Hugo',
    name: 'BasicAttackDarkAbyssQuartet_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Hugo',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackDarkAbyssQuartet_1',
    },
  },
  'BasicAttackDarkAbyssQuartet_2:standardDmg': {
    sheet: 'Hugo',
    name: 'BasicAttackDarkAbyssQuartet_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackDarkAbyssQuartet_2',
    },
  },
  'BasicAttackDarkAbyssQuartet_2:dazeBuildup': {
    sheet: 'Hugo',
    name: 'BasicAttackDarkAbyssQuartet_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackDarkAbyssQuartet_2',
    },
  },
  'BasicAttackDarkAbyssQuartet_2:anomBuildup': {
    sheet: 'Hugo',
    name: 'BasicAttackDarkAbyssQuartet_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackDarkAbyssQuartet_2',
    },
  },
  'BasicAttackDarkAbyssQuartet_3:standardDmg': {
    sheet: 'Hugo',
    name: 'BasicAttackDarkAbyssQuartet_3:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackDarkAbyssQuartet_3',
    },
  },
  'BasicAttackDarkAbyssQuartet_3:dazeBuildup': {
    sheet: 'Hugo',
    name: 'BasicAttackDarkAbyssQuartet_3:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackDarkAbyssQuartet_3',
    },
  },
  'BasicAttackDarkAbyssQuartet_3:anomBuildup': {
    sheet: 'Hugo',
    name: 'BasicAttackDarkAbyssQuartet_3:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackDarkAbyssQuartet_3',
    },
  },
  'BasicAttackDarkAbyssQuartet_4:standardDmg': {
    sheet: 'Hugo',
    name: 'BasicAttackDarkAbyssQuartet_4:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackDarkAbyssQuartet_4',
    },
  },
  'BasicAttackDarkAbyssQuartet_4:dazeBuildup': {
    sheet: 'Hugo',
    name: 'BasicAttackDarkAbyssQuartet_4:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackDarkAbyssQuartet_4',
    },
  },
  'BasicAttackDarkAbyssQuartet_4:anomBuildup': {
    sheet: 'Hugo',
    name: 'BasicAttackDarkAbyssQuartet_4:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackDarkAbyssQuartet_4',
    },
  },
  'BasicAttackDarkAbyssQuartet_5:standardDmg': {
    sheet: 'Hugo',
    name: 'BasicAttackDarkAbyssQuartet_5:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackDarkAbyssQuartet_5',
    },
  },
  'BasicAttackDarkAbyssQuartet_5:dazeBuildup': {
    sheet: 'Hugo',
    name: 'BasicAttackDarkAbyssQuartet_5:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackDarkAbyssQuartet_5',
    },
  },
  'BasicAttackDarkAbyssQuartet_5:anomBuildup': {
    sheet: 'Hugo',
    name: 'BasicAttackDarkAbyssQuartet_5:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackDarkAbyssQuartet_5',
    },
  },
  'BasicAttackDarkAbyssConcerto_0:standardDmg': {
    sheet: 'Hugo',
    name: 'BasicAttackDarkAbyssConcerto_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackDarkAbyssConcerto_0',
    },
  },
  'BasicAttackDarkAbyssConcerto_0:dazeBuildup': {
    sheet: 'Hugo',
    name: 'BasicAttackDarkAbyssConcerto_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackDarkAbyssConcerto_0',
    },
  },
  'BasicAttackDarkAbyssConcerto_0:anomBuildup': {
    sheet: 'Hugo',
    name: 'BasicAttackDarkAbyssConcerto_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackDarkAbyssConcerto_0',
    },
  },
  'BasicAttackDarkAbyssConcerto_1:standardDmg': {
    sheet: 'Hugo',
    name: 'BasicAttackDarkAbyssConcerto_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackDarkAbyssConcerto_1',
    },
  },
  'BasicAttackDarkAbyssConcerto_1:dazeBuildup': {
    sheet: 'Hugo',
    name: 'BasicAttackDarkAbyssConcerto_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackDarkAbyssConcerto_1',
    },
  },
  'BasicAttackDarkAbyssConcerto_1:anomBuildup': {
    sheet: 'Hugo',
    name: 'BasicAttackDarkAbyssConcerto_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackDarkAbyssConcerto_1',
    },
  },
  'BasicAttackDarkAbyssConcerto_2:standardDmg': {
    sheet: 'Hugo',
    name: 'BasicAttackDarkAbyssConcerto_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackDarkAbyssConcerto_2',
    },
  },
  'BasicAttackDarkAbyssConcerto_2:dazeBuildup': {
    sheet: 'Hugo',
    name: 'BasicAttackDarkAbyssConcerto_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackDarkAbyssConcerto_2',
    },
  },
  'BasicAttackDarkAbyssConcerto_2:anomBuildup': {
    sheet: 'Hugo',
    name: 'BasicAttackDarkAbyssConcerto_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackDarkAbyssConcerto_2',
    },
  },
  'DashAttackPhantasmShatter_0:standardDmg': {
    sheet: 'Hugo',
    name: 'DashAttackPhantasmShatter_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Hugo',
      damageType1: 'dash',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttackPhantasmShatter_0',
    },
  },
  'DashAttackPhantasmShatter_0:dazeBuildup': {
    sheet: 'Hugo',
    name: 'DashAttackPhantasmShatter_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Hugo',
      damageType1: 'dash',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttackPhantasmShatter_0',
    },
  },
  'DashAttackPhantasmShatter_0:anomBuildup': {
    sheet: 'Hugo',
    name: 'DashAttackPhantasmShatter_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Hugo',
      damageType1: 'dash',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttackPhantasmShatter_0',
    },
  },
  'DodgeCounterPhantasmSlash_0:standardDmg': {
    sheet: 'Hugo',
    name: 'DodgeCounterPhantasmSlash_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterPhantasmSlash_0',
    },
  },
  'DodgeCounterPhantasmSlash_0:dazeBuildup': {
    sheet: 'Hugo',
    name: 'DodgeCounterPhantasmSlash_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterPhantasmSlash_0',
    },
  },
  'DodgeCounterPhantasmSlash_0:anomBuildup': {
    sheet: 'Hugo',
    name: 'DodgeCounterPhantasmSlash_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterPhantasmSlash_0',
    },
  },
  'DodgeCounterPhantasmSlash_1:standardDmg': {
    sheet: 'Hugo',
    name: 'DodgeCounterPhantasmSlash_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterPhantasmSlash_1',
    },
  },
  'DodgeCounterPhantasmSlash_1:dazeBuildup': {
    sheet: 'Hugo',
    name: 'DodgeCounterPhantasmSlash_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterPhantasmSlash_1',
    },
  },
  'DodgeCounterPhantasmSlash_1:anomBuildup': {
    sheet: 'Hugo',
    name: 'DodgeCounterPhantasmSlash_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterPhantasmSlash_1',
    },
  },
  'DodgeCounterPhantasmSlash_2:standardDmg': {
    sheet: 'Hugo',
    name: 'DodgeCounterPhantasmSlash_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterPhantasmSlash_2',
    },
  },
  'DodgeCounterPhantasmSlash_2:dazeBuildup': {
    sheet: 'Hugo',
    name: 'DodgeCounterPhantasmSlash_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterPhantasmSlash_2',
    },
  },
  'DodgeCounterPhantasmSlash_2:anomBuildup': {
    sheet: 'Hugo',
    name: 'DodgeCounterPhantasmSlash_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterPhantasmSlash_2',
    },
  },
  'SpecialAttackSoulHunterJudgment_0:standardDmg': {
    sheet: 'Hugo',
    name: 'SpecialAttackSoulHunterJudgment_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackSoulHunterJudgment_0',
    },
  },
  'SpecialAttackSoulHunterJudgment_0:dazeBuildup': {
    sheet: 'Hugo',
    name: 'SpecialAttackSoulHunterJudgment_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackSoulHunterJudgment_0',
    },
  },
  'SpecialAttackSoulHunterJudgment_0:anomBuildup': {
    sheet: 'Hugo',
    name: 'SpecialAttackSoulHunterJudgment_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackSoulHunterJudgment_0',
    },
  },
  'EXSpecialAttackSoulHunterPunishment_0:standardDmg': {
    sheet: 'Hugo',
    name: 'EXSpecialAttackSoulHunterPunishment_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackSoulHunterPunishment_0',
    },
  },
  'EXSpecialAttackSoulHunterPunishment_0:dazeBuildup': {
    sheet: 'Hugo',
    name: 'EXSpecialAttackSoulHunterPunishment_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackSoulHunterPunishment_0',
    },
  },
  'EXSpecialAttackSoulHunterPunishment_0:anomBuildup': {
    sheet: 'Hugo',
    name: 'EXSpecialAttackSoulHunterPunishment_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackSoulHunterPunishment_0',
    },
  },
  'ChainAttackTrickOfFate_0:standardDmg': {
    sheet: 'Hugo',
    name: 'ChainAttackTrickOfFate_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackTrickOfFate_0',
    },
  },
  'ChainAttackTrickOfFate_0:dazeBuildup': {
    sheet: 'Hugo',
    name: 'ChainAttackTrickOfFate_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackTrickOfFate_0',
    },
  },
  'ChainAttackTrickOfFate_0:anomBuildup': {
    sheet: 'Hugo',
    name: 'ChainAttackTrickOfFate_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackTrickOfFate_0',
    },
  },
  'UltimateBlaspheme_0:standardDmg': {
    sheet: 'Hugo',
    name: 'UltimateBlaspheme_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateBlaspheme_0',
    },
  },
  'UltimateBlaspheme_0:dazeBuildup': {
    sheet: 'Hugo',
    name: 'UltimateBlaspheme_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateBlaspheme_0',
    },
  },
  'UltimateBlaspheme_0:anomBuildup': {
    sheet: 'Hugo',
    name: 'UltimateBlaspheme_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateBlaspheme_0',
    },
  },
  'QuickAssistElegy_0:standardDmg': {
    sheet: 'Hugo',
    name: 'QuickAssistElegy_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistElegy_0',
    },
  },
  'QuickAssistElegy_0:dazeBuildup': {
    sheet: 'Hugo',
    name: 'QuickAssistElegy_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistElegy_0',
    },
  },
  'QuickAssistElegy_0:anomBuildup': {
    sheet: 'Hugo',
    name: 'QuickAssistElegy_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistElegy_0',
    },
  },
  'QuickAssistElegy_1:standardDmg': {
    sheet: 'Hugo',
    name: 'QuickAssistElegy_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistElegy_1',
    },
  },
  'QuickAssistElegy_1:dazeBuildup': {
    sheet: 'Hugo',
    name: 'QuickAssistElegy_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistElegy_1',
    },
  },
  'QuickAssistElegy_1:anomBuildup': {
    sheet: 'Hugo',
    name: 'QuickAssistElegy_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistElegy_1',
    },
  },
  'QuickAssistElegy_2:standardDmg': {
    sheet: 'Hugo',
    name: 'QuickAssistElegy_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistElegy_2',
    },
  },
  'QuickAssistElegy_2:dazeBuildup': {
    sheet: 'Hugo',
    name: 'QuickAssistElegy_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistElegy_2',
    },
  },
  'QuickAssistElegy_2:anomBuildup': {
    sheet: 'Hugo',
    name: 'QuickAssistElegy_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistElegy_2',
    },
  },
  'DefensiveAssistTheEndHasNotCome_0:standardDmg': {
    sheet: 'Hugo',
    name: 'DefensiveAssistTheEndHasNotCome_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistTheEndHasNotCome_0',
    },
  },
  'DefensiveAssistTheEndHasNotCome_0:dazeBuildup': {
    sheet: 'Hugo',
    name: 'DefensiveAssistTheEndHasNotCome_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistTheEndHasNotCome_0',
    },
  },
  'DefensiveAssistTheEndHasNotCome_0:anomBuildup': {
    sheet: 'Hugo',
    name: 'DefensiveAssistTheEndHasNotCome_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistTheEndHasNotCome_0',
    },
  },
  'DefensiveAssistTheEndHasNotCome_1:standardDmg': {
    sheet: 'Hugo',
    name: 'DefensiveAssistTheEndHasNotCome_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistTheEndHasNotCome_1',
    },
  },
  'DefensiveAssistTheEndHasNotCome_1:dazeBuildup': {
    sheet: 'Hugo',
    name: 'DefensiveAssistTheEndHasNotCome_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistTheEndHasNotCome_1',
    },
  },
  'DefensiveAssistTheEndHasNotCome_1:anomBuildup': {
    sheet: 'Hugo',
    name: 'DefensiveAssistTheEndHasNotCome_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistTheEndHasNotCome_1',
    },
  },
  'DefensiveAssistTheEndHasNotCome_2:standardDmg': {
    sheet: 'Hugo',
    name: 'DefensiveAssistTheEndHasNotCome_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistTheEndHasNotCome_2',
    },
  },
  'DefensiveAssistTheEndHasNotCome_2:dazeBuildup': {
    sheet: 'Hugo',
    name: 'DefensiveAssistTheEndHasNotCome_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistTheEndHasNotCome_2',
    },
  },
  'DefensiveAssistTheEndHasNotCome_2:anomBuildup': {
    sheet: 'Hugo',
    name: 'DefensiveAssistTheEndHasNotCome_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistTheEndHasNotCome_2',
    },
  },
  'AssistFollowUpAceReversal_0:standardDmg': {
    sheet: 'Hugo',
    name: 'AssistFollowUpAceReversal_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpAceReversal_0',
    },
  },
  'AssistFollowUpAceReversal_0:dazeBuildup': {
    sheet: 'Hugo',
    name: 'AssistFollowUpAceReversal_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpAceReversal_0',
    },
  },
  'AssistFollowUpAceReversal_0:anomBuildup': {
    sheet: 'Hugo',
    name: 'AssistFollowUpAceReversal_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Hugo',
      attribute: 'ice',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpAceReversal_0',
    },
  },
} as const
