// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Evelyn',
    name: 'standardDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Evelyn',
      attribute: 'fire',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Evelyn',
    name: 'anomalyDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_fire: {
    sheet: 'Evelyn',
    name: 'disorderDmgInst_fire',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'disorder',
      name: 'disorderDmgInst_fire',
    },
  },
  vortexDmgInst_fire: {
    sheet: 'Evelyn',
    name: 'vortexDmgInst_fire',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'vortex',
      name: 'vortexDmgInst_fire',
    },
  },
  abloomDmgInst: {
    sheet: 'Evelyn',
    name: 'abloomDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Evelyn',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Evelyn',
      attribute: 'fire',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Evelyn',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Evelyn',
      attribute: 'fire',
      name: 'dazeInst',
    },
  },
  'BasicAttackRazorWire_0:standardDmg': {
    sheet: 'Evelyn',
    name: 'BasicAttackRazorWire_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Evelyn',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackRazorWire_0',
    },
  },
  'BasicAttackRazorWire_0:dazeBuildup': {
    sheet: 'Evelyn',
    name: 'BasicAttackRazorWire_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Evelyn',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackRazorWire_0',
    },
  },
  'BasicAttackRazorWire_0:anomBuildup': {
    sheet: 'Evelyn',
    name: 'BasicAttackRazorWire_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Evelyn',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackRazorWire_0',
    },
  },
  'BasicAttackRazorWire_1:standardDmg': {
    sheet: 'Evelyn',
    name: 'BasicAttackRazorWire_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Evelyn',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackRazorWire_1',
    },
  },
  'BasicAttackRazorWire_1:dazeBuildup': {
    sheet: 'Evelyn',
    name: 'BasicAttackRazorWire_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Evelyn',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackRazorWire_1',
    },
  },
  'BasicAttackRazorWire_1:anomBuildup': {
    sheet: 'Evelyn',
    name: 'BasicAttackRazorWire_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Evelyn',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackRazorWire_1',
    },
  },
  'BasicAttackRazorWire_2:standardDmg': {
    sheet: 'Evelyn',
    name: 'BasicAttackRazorWire_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Evelyn',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackRazorWire_2',
    },
  },
  'BasicAttackRazorWire_2:dazeBuildup': {
    sheet: 'Evelyn',
    name: 'BasicAttackRazorWire_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Evelyn',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackRazorWire_2',
    },
  },
  'BasicAttackRazorWire_2:anomBuildup': {
    sheet: 'Evelyn',
    name: 'BasicAttackRazorWire_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Evelyn',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackRazorWire_2',
    },
  },
  'BasicAttackRazorWire_3:standardDmg': {
    sheet: 'Evelyn',
    name: 'BasicAttackRazorWire_3:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackRazorWire_3',
    },
  },
  'BasicAttackRazorWire_3:dazeBuildup': {
    sheet: 'Evelyn',
    name: 'BasicAttackRazorWire_3:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackRazorWire_3',
    },
  },
  'BasicAttackRazorWire_3:anomBuildup': {
    sheet: 'Evelyn',
    name: 'BasicAttackRazorWire_3:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackRazorWire_3',
    },
  },
  'BasicAttackRazorWire_4:standardDmg': {
    sheet: 'Evelyn',
    name: 'BasicAttackRazorWire_4:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackRazorWire_4',
    },
  },
  'BasicAttackRazorWire_4:dazeBuildup': {
    sheet: 'Evelyn',
    name: 'BasicAttackRazorWire_4:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackRazorWire_4',
    },
  },
  'BasicAttackRazorWire_4:anomBuildup': {
    sheet: 'Evelyn',
    name: 'BasicAttackRazorWire_4:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackRazorWire_4',
    },
  },
  'BasicAttackGarroteFirstForm_0:standardDmg': {
    sheet: 'Evelyn',
    name: 'BasicAttackGarroteFirstForm_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackGarroteFirstForm_0',
    },
  },
  'BasicAttackGarroteFirstForm_0:dazeBuildup': {
    sheet: 'Evelyn',
    name: 'BasicAttackGarroteFirstForm_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackGarroteFirstForm_0',
    },
  },
  'BasicAttackGarroteFirstForm_0:anomBuildup': {
    sheet: 'Evelyn',
    name: 'BasicAttackGarroteFirstForm_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackGarroteFirstForm_0',
    },
  },
  'BasicAttackGarroteSecondForm_0:standardDmg': {
    sheet: 'Evelyn',
    name: 'BasicAttackGarroteSecondForm_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackGarroteSecondForm_0',
    },
  },
  'BasicAttackGarroteSecondForm_0:dazeBuildup': {
    sheet: 'Evelyn',
    name: 'BasicAttackGarroteSecondForm_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackGarroteSecondForm_0',
    },
  },
  'BasicAttackGarroteSecondForm_0:anomBuildup': {
    sheet: 'Evelyn',
    name: 'BasicAttackGarroteSecondForm_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackGarroteSecondForm_0',
    },
  },
  'DashAttackPiercingAmbush_0:standardDmg': {
    sheet: 'Evelyn',
    name: 'DashAttackPiercingAmbush_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Evelyn',
      damageType1: 'dash',
      attribute: 'physical',
      skillType1: 'dodgeSkill',
      name: 'DashAttackPiercingAmbush_0',
    },
  },
  'DashAttackPiercingAmbush_0:dazeBuildup': {
    sheet: 'Evelyn',
    name: 'DashAttackPiercingAmbush_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Evelyn',
      damageType1: 'dash',
      attribute: 'physical',
      skillType1: 'dodgeSkill',
      name: 'DashAttackPiercingAmbush_0',
    },
  },
  'DashAttackPiercingAmbush_0:anomBuildup': {
    sheet: 'Evelyn',
    name: 'DashAttackPiercingAmbush_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Evelyn',
      damageType1: 'dash',
      attribute: 'physical',
      skillType1: 'dodgeSkill',
      name: 'DashAttackPiercingAmbush_0',
    },
  },
  'DodgeCounterStranglingReversal_0:standardDmg': {
    sheet: 'Evelyn',
    name: 'DodgeCounterStranglingReversal_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'dodgeCounter',
      skillType1: 'dodgeSkill',
      name: 'DodgeCounterStranglingReversal_0',
    },
  },
  'DodgeCounterStranglingReversal_0:dazeBuildup': {
    sheet: 'Evelyn',
    name: 'DodgeCounterStranglingReversal_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'dodgeCounter',
      skillType1: 'dodgeSkill',
      name: 'DodgeCounterStranglingReversal_0',
    },
  },
  'DodgeCounterStranglingReversal_0:anomBuildup': {
    sheet: 'Evelyn',
    name: 'DodgeCounterStranglingReversal_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'dodgeCounter',
      skillType1: 'dodgeSkill',
      name: 'DodgeCounterStranglingReversal_0',
    },
  },
  'SpecialAttackLockedPosition_0:standardDmg': {
    sheet: 'Evelyn',
    name: 'SpecialAttackLockedPosition_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackLockedPosition_0',
    },
  },
  'SpecialAttackLockedPosition_0:dazeBuildup': {
    sheet: 'Evelyn',
    name: 'SpecialAttackLockedPosition_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackLockedPosition_0',
    },
  },
  'SpecialAttackLockedPosition_0:anomBuildup': {
    sheet: 'Evelyn',
    name: 'SpecialAttackLockedPosition_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackLockedPosition_0',
    },
  },
  'SpecialAttackBindingSunderFirstForm_0:standardDmg': {
    sheet: 'Evelyn',
    name: 'SpecialAttackBindingSunderFirstForm_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackBindingSunderFirstForm_0',
    },
  },
  'SpecialAttackBindingSunderFirstForm_0:dazeBuildup': {
    sheet: 'Evelyn',
    name: 'SpecialAttackBindingSunderFirstForm_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackBindingSunderFirstForm_0',
    },
  },
  'SpecialAttackBindingSunderFirstForm_0:anomBuildup': {
    sheet: 'Evelyn',
    name: 'SpecialAttackBindingSunderFirstForm_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackBindingSunderFirstForm_0',
    },
  },
  'SpecialAttackBindingSunderFirstForm_1:standardDmg': {
    sheet: 'Evelyn',
    name: 'SpecialAttackBindingSunderFirstForm_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackBindingSunderFirstForm_1',
    },
  },
  'SpecialAttackBindingSunderFirstForm_1:dazeBuildup': {
    sheet: 'Evelyn',
    name: 'SpecialAttackBindingSunderFirstForm_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackBindingSunderFirstForm_1',
    },
  },
  'SpecialAttackBindingSunderFirstForm_1:anomBuildup': {
    sheet: 'Evelyn',
    name: 'SpecialAttackBindingSunderFirstForm_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackBindingSunderFirstForm_1',
    },
  },
  'EXSpecialAttackBindingSunderFinalForm_0:standardDmg': {
    sheet: 'Evelyn',
    name: 'EXSpecialAttackBindingSunderFinalForm_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackBindingSunderFinalForm_0',
    },
  },
  'EXSpecialAttackBindingSunderFinalForm_0:dazeBuildup': {
    sheet: 'Evelyn',
    name: 'EXSpecialAttackBindingSunderFinalForm_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackBindingSunderFinalForm_0',
    },
  },
  'EXSpecialAttackBindingSunderFinalForm_0:anomBuildup': {
    sheet: 'Evelyn',
    name: 'EXSpecialAttackBindingSunderFinalForm_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackBindingSunderFinalForm_0',
    },
  },
  'EXSpecialAttackBindingSunderFinalForm_1:standardDmg': {
    sheet: 'Evelyn',
    name: 'EXSpecialAttackBindingSunderFinalForm_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackBindingSunderFinalForm_1',
    },
  },
  'EXSpecialAttackBindingSunderFinalForm_1:dazeBuildup': {
    sheet: 'Evelyn',
    name: 'EXSpecialAttackBindingSunderFinalForm_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackBindingSunderFinalForm_1',
    },
  },
  'EXSpecialAttackBindingSunderFinalForm_1:anomBuildup': {
    sheet: 'Evelyn',
    name: 'EXSpecialAttackBindingSunderFinalForm_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackBindingSunderFinalForm_1',
    },
  },
  'ChainAttackLunaluxSnare_0:standardDmg': {
    sheet: 'Evelyn',
    name: 'ChainAttackLunaluxSnare_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'chain',
      skillType1: 'chainSkill',
      name: 'ChainAttackLunaluxSnare_0',
    },
  },
  'ChainAttackLunaluxSnare_0:dazeBuildup': {
    sheet: 'Evelyn',
    name: 'ChainAttackLunaluxSnare_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'chain',
      skillType1: 'chainSkill',
      name: 'ChainAttackLunaluxSnare_0',
    },
  },
  'ChainAttackLunaluxSnare_0:anomBuildup': {
    sheet: 'Evelyn',
    name: 'ChainAttackLunaluxSnare_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'chain',
      skillType1: 'chainSkill',
      name: 'ChainAttackLunaluxSnare_0',
    },
  },
  'UltimateLunaluxGarroteTimbre_0:standardDmg': {
    sheet: 'Evelyn',
    name: 'UltimateLunaluxGarroteTimbre_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'ult',
      skillType1: 'chainSkill',
      name: 'UltimateLunaluxGarroteTimbre_0',
    },
  },
  'UltimateLunaluxGarroteTimbre_0:dazeBuildup': {
    sheet: 'Evelyn',
    name: 'UltimateLunaluxGarroteTimbre_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'ult',
      skillType1: 'chainSkill',
      name: 'UltimateLunaluxGarroteTimbre_0',
    },
  },
  'UltimateLunaluxGarroteTimbre_0:anomBuildup': {
    sheet: 'Evelyn',
    name: 'UltimateLunaluxGarroteTimbre_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'ult',
      skillType1: 'chainSkill',
      name: 'UltimateLunaluxGarroteTimbre_0',
    },
  },
  'UltimateLunaluxGarroteShadow_0:standardDmg': {
    sheet: 'Evelyn',
    name: 'UltimateLunaluxGarroteShadow_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'ult',
      skillType1: 'chainSkill',
      name: 'UltimateLunaluxGarroteShadow_0',
    },
  },
  'UltimateLunaluxGarroteShadow_0:dazeBuildup': {
    sheet: 'Evelyn',
    name: 'UltimateLunaluxGarroteShadow_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'ult',
      skillType1: 'chainSkill',
      name: 'UltimateLunaluxGarroteShadow_0',
    },
  },
  'UltimateLunaluxGarroteShadow_0:anomBuildup': {
    sheet: 'Evelyn',
    name: 'UltimateLunaluxGarroteShadow_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'ult',
      skillType1: 'chainSkill',
      name: 'UltimateLunaluxGarroteShadow_0',
    },
  },
  'QuickAssistFierceBlade_0:standardDmg': {
    sheet: 'Evelyn',
    name: 'QuickAssistFierceBlade_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'quickAssist',
      skillType1: 'assistSkill',
      name: 'QuickAssistFierceBlade_0',
    },
  },
  'QuickAssistFierceBlade_0:dazeBuildup': {
    sheet: 'Evelyn',
    name: 'QuickAssistFierceBlade_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'quickAssist',
      skillType1: 'assistSkill',
      name: 'QuickAssistFierceBlade_0',
    },
  },
  'QuickAssistFierceBlade_0:anomBuildup': {
    sheet: 'Evelyn',
    name: 'QuickAssistFierceBlade_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'quickAssist',
      skillType1: 'assistSkill',
      name: 'QuickAssistFierceBlade_0',
    },
  },
  'DefensiveAssistSilentProtection_0:standardDmg': {
    sheet: 'Evelyn',
    name: 'DefensiveAssistSilentProtection_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistSilentProtection_0',
    },
  },
  'DefensiveAssistSilentProtection_0:dazeBuildup': {
    sheet: 'Evelyn',
    name: 'DefensiveAssistSilentProtection_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistSilentProtection_0',
    },
  },
  'DefensiveAssistSilentProtection_0:anomBuildup': {
    sheet: 'Evelyn',
    name: 'DefensiveAssistSilentProtection_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistSilentProtection_0',
    },
  },
  'DefensiveAssistSilentProtection_1:standardDmg': {
    sheet: 'Evelyn',
    name: 'DefensiveAssistSilentProtection_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistSilentProtection_1',
    },
  },
  'DefensiveAssistSilentProtection_1:dazeBuildup': {
    sheet: 'Evelyn',
    name: 'DefensiveAssistSilentProtection_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistSilentProtection_1',
    },
  },
  'DefensiveAssistSilentProtection_1:anomBuildup': {
    sheet: 'Evelyn',
    name: 'DefensiveAssistSilentProtection_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistSilentProtection_1',
    },
  },
  'DefensiveAssistSilentProtection_2:standardDmg': {
    sheet: 'Evelyn',
    name: 'DefensiveAssistSilentProtection_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistSilentProtection_2',
    },
  },
  'DefensiveAssistSilentProtection_2:dazeBuildup': {
    sheet: 'Evelyn',
    name: 'DefensiveAssistSilentProtection_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistSilentProtection_2',
    },
  },
  'DefensiveAssistSilentProtection_2:anomBuildup': {
    sheet: 'Evelyn',
    name: 'DefensiveAssistSilentProtection_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistSilentProtection_2',
    },
  },
  'AssistFollowUpCourseDisruption_0:standardDmg': {
    sheet: 'Evelyn',
    name: 'AssistFollowUpCourseDisruption_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'assistFollowUp',
      skillType1: 'assistSkill',
      name: 'AssistFollowUpCourseDisruption_0',
    },
  },
  'AssistFollowUpCourseDisruption_0:dazeBuildup': {
    sheet: 'Evelyn',
    name: 'AssistFollowUpCourseDisruption_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'assistFollowUp',
      skillType1: 'assistSkill',
      name: 'AssistFollowUpCourseDisruption_0',
    },
  },
  'AssistFollowUpCourseDisruption_0:anomBuildup': {
    sheet: 'Evelyn',
    name: 'AssistFollowUpCourseDisruption_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'assistFollowUp',
      skillType1: 'assistSkill',
      name: 'AssistFollowUpCourseDisruption_0',
    },
  },
  m4_shield: {
    sheet: 'Evelyn',
    name: 'm4_shield',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'shield',
      sheet: 'Evelyn',
      name: 'm4_shield',
    },
  },
  m6_follow_up_dmg_: {
    sheet: 'Evelyn',
    name: 'm6_follow_up_dmg_',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Evelyn',
      attribute: 'fire',
      skillType1: 'chainSkill',
      name: 'm6_follow_up_dmg_',
    },
  },
} as const
