// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Evelyn',
    name: 'standardDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'standardDmgBase',
      sheet: 'Evelyn',
      attribute: 'fire',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Evelyn',
    name: 'anomalyDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_fire: {
    sheet: 'Evelyn',
    name: 'disorderDmgInst_fire',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'disorder',
      name: 'disorderDmgInst_fire',
    },
  },
  vortexDmgInst_fire: {
    sheet: 'Evelyn',
    name: 'vortexDmgInst_fire',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'vortex',
      name: 'vortexDmgInst_fire',
    },
  },
  abloomDmgInst: {
    sheet: 'Evelyn',
    name: 'abloomDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Evelyn',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Evelyn',
      attribute: 'fire',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Evelyn',
    name: 'dazeInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'dazeBuildupBase',
      sheet: 'Evelyn',
      attribute: 'fire',
      name: 'dazeInst',
    },
  },
  BasicAttackRazorWire_0: {
    sheet: 'Evelyn',
    name: 'BasicAttackRazorWire_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Evelyn',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackRazorWire_0',
    },
  },
  BasicAttackRazorWire_1: {
    sheet: 'Evelyn',
    name: 'BasicAttackRazorWire_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Evelyn',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackRazorWire_1',
    },
  },
  BasicAttackRazorWire_2: {
    sheet: 'Evelyn',
    name: 'BasicAttackRazorWire_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Evelyn',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackRazorWire_2',
    },
  },
  BasicAttackRazorWire_3: {
    sheet: 'Evelyn',
    name: 'BasicAttackRazorWire_3',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackRazorWire_3',
    },
  },
  BasicAttackRazorWire_4: {
    sheet: 'Evelyn',
    name: 'BasicAttackRazorWire_4',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackRazorWire_4',
    },
  },
  BasicAttackGarroteFirstForm_0: {
    sheet: 'Evelyn',
    name: 'BasicAttackGarroteFirstForm_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackGarroteFirstForm_0',
    },
  },
  BasicAttackGarroteSecondForm_0: {
    sheet: 'Evelyn',
    name: 'BasicAttackGarroteSecondForm_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackGarroteSecondForm_0',
    },
  },
  DashAttackPiercingAmbush_0: {
    sheet: 'Evelyn',
    name: 'DashAttackPiercingAmbush_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Evelyn',
      damageType1: 'dash',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttackPiercingAmbush_0',
    },
  },
  DodgeCounterStranglingReversal_0: {
    sheet: 'Evelyn',
    name: 'DodgeCounterStranglingReversal_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterStranglingReversal_0',
    },
  },
  SpecialAttackLockedPosition_0: {
    sheet: 'Evelyn',
    name: 'SpecialAttackLockedPosition_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackLockedPosition_0',
    },
  },
  SpecialAttackBindingSunderFirstForm_0: {
    sheet: 'Evelyn',
    name: 'SpecialAttackBindingSunderFirstForm_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackBindingSunderFirstForm_0',
    },
  },
  SpecialAttackBindingSunderFirstForm_1: {
    sheet: 'Evelyn',
    name: 'SpecialAttackBindingSunderFirstForm_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackBindingSunderFirstForm_1',
    },
  },
  EXSpecialAttackBindingSunderFinalForm_0: {
    sheet: 'Evelyn',
    name: 'EXSpecialAttackBindingSunderFinalForm_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackBindingSunderFinalForm_0',
    },
  },
  EXSpecialAttackBindingSunderFinalForm_1: {
    sheet: 'Evelyn',
    name: 'EXSpecialAttackBindingSunderFinalForm_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackBindingSunderFinalForm_1',
    },
  },
  ChainAttackLunaluxSnare_0: {
    sheet: 'Evelyn',
    name: 'ChainAttackLunaluxSnare_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackLunaluxSnare_0',
    },
  },
  UltimateLunaluxGarroteTimbre_0: {
    sheet: 'Evelyn',
    name: 'UltimateLunaluxGarroteTimbre_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateLunaluxGarroteTimbre_0',
    },
  },
  UltimateLunaluxGarroteShadow_0: {
    sheet: 'Evelyn',
    name: 'UltimateLunaluxGarroteShadow_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateLunaluxGarroteShadow_0',
    },
  },
  QuickAssistFierceBlade_0: {
    sheet: 'Evelyn',
    name: 'QuickAssistFierceBlade_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistFierceBlade_0',
    },
  },
  DefensiveAssistSilentProtection_0: {
    sheet: 'Evelyn',
    name: 'DefensiveAssistSilentProtection_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistSilentProtection_0',
    },
  },
  DefensiveAssistSilentProtection_1: {
    sheet: 'Evelyn',
    name: 'DefensiveAssistSilentProtection_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistSilentProtection_1',
    },
  },
  DefensiveAssistSilentProtection_2: {
    sheet: 'Evelyn',
    name: 'DefensiveAssistSilentProtection_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistSilentProtection_2',
    },
  },
  AssistFollowUpCourseDisruption_0: {
    sheet: 'Evelyn',
    name: 'AssistFollowUpCourseDisruption_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Evelyn',
      attribute: 'fire',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpCourseDisruption_0',
    },
  },
  m4_shield: {
    sheet: 'Evelyn',
    name: 'm4_shield',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'shieldBase',
      sheet: 'Evelyn',
      name: 'm4_shield',
    },
  },
  m6_follow_up_dmg_: {
    sheet: 'Evelyn',
    name: 'm6_follow_up_dmg_',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'standardDmgBase',
      sheet: 'Evelyn',
      attribute: 'fire',
      skillType: 'chainSkill',
      name: 'm6_follow_up_dmg_',
    },
  },
} as const
