// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Claret',
    name: 'standardDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Claret',
      attribute: 'electric',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Claret',
    name: 'anomalyDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_electric: {
    sheet: 'Claret',
    name: 'disorderDmgInst_electric',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'disorder',
      name: 'disorderDmgInst_electric',
    },
  },
  vortexDmgInst_electric: {
    sheet: 'Claret',
    name: 'vortexDmgInst_electric',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'vortex',
      name: 'vortexDmgInst_electric',
    },
  },
  abloomDmgInst: {
    sheet: 'Claret',
    name: 'abloomDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Claret',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Claret',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      name: 'dazeInst',
    },
  },
  'BasicAttackBloodforgingFourForms_0:standardDmg': {
    sheet: 'Claret',
    name: 'BasicAttackBloodforgingFourForms_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBloodforgingFourForms_0',
    },
  },
  'BasicAttackBloodforgingFourForms_0:dazeBuildup': {
    sheet: 'Claret',
    name: 'BasicAttackBloodforgingFourForms_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBloodforgingFourForms_0',
    },
  },
  'BasicAttackBloodforgingFourForms_0:anomBuildup': {
    sheet: 'Claret',
    name: 'BasicAttackBloodforgingFourForms_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBloodforgingFourForms_0',
    },
  },
  'BasicAttackBloodforgingFourForms_1:standardDmg': {
    sheet: 'Claret',
    name: 'BasicAttackBloodforgingFourForms_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBloodforgingFourForms_1',
    },
  },
  'BasicAttackBloodforgingFourForms_1:dazeBuildup': {
    sheet: 'Claret',
    name: 'BasicAttackBloodforgingFourForms_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBloodforgingFourForms_1',
    },
  },
  'BasicAttackBloodforgingFourForms_1:anomBuildup': {
    sheet: 'Claret',
    name: 'BasicAttackBloodforgingFourForms_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBloodforgingFourForms_1',
    },
  },
  'BasicAttackBloodforgingFourForms_2:standardDmg': {
    sheet: 'Claret',
    name: 'BasicAttackBloodforgingFourForms_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBloodforgingFourForms_2',
    },
  },
  'BasicAttackBloodforgingFourForms_2:dazeBuildup': {
    sheet: 'Claret',
    name: 'BasicAttackBloodforgingFourForms_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBloodforgingFourForms_2',
    },
  },
  'BasicAttackBloodforgingFourForms_2:anomBuildup': {
    sheet: 'Claret',
    name: 'BasicAttackBloodforgingFourForms_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBloodforgingFourForms_2',
    },
  },
  'BasicAttackBloodforgingFourForms_3:standardDmg': {
    sheet: 'Claret',
    name: 'BasicAttackBloodforgingFourForms_3:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBloodforgingFourForms_3',
    },
  },
  'BasicAttackBloodforgingFourForms_3:dazeBuildup': {
    sheet: 'Claret',
    name: 'BasicAttackBloodforgingFourForms_3:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBloodforgingFourForms_3',
    },
  },
  'BasicAttackBloodforgingFourForms_3:anomBuildup': {
    sheet: 'Claret',
    name: 'BasicAttackBloodforgingFourForms_3:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBloodforgingFourForms_3',
    },
  },
  'BasicAttackBloodbloomOathStarforging_0:standardDmg': {
    sheet: 'Claret',
    name: 'BasicAttackBloodbloomOathStarforging_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBloodbloomOathStarforging_0',
    },
  },
  'BasicAttackBloodbloomOathStarforging_0:dazeBuildup': {
    sheet: 'Claret',
    name: 'BasicAttackBloodbloomOathStarforging_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBloodbloomOathStarforging_0',
    },
  },
  'BasicAttackBloodbloomOathStarforging_0:anomBuildup': {
    sheet: 'Claret',
    name: 'BasicAttackBloodbloomOathStarforging_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBloodbloomOathStarforging_0',
    },
  },
  'BasicAttackBloodbloomOathStarforging_1:standardDmg': {
    sheet: 'Claret',
    name: 'BasicAttackBloodbloomOathStarforging_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBloodbloomOathStarforging_1',
    },
  },
  'BasicAttackBloodbloomOathStarforging_1:dazeBuildup': {
    sheet: 'Claret',
    name: 'BasicAttackBloodbloomOathStarforging_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBloodbloomOathStarforging_1',
    },
  },
  'BasicAttackBloodbloomOathStarforging_1:anomBuildup': {
    sheet: 'Claret',
    name: 'BasicAttackBloodbloomOathStarforging_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBloodbloomOathStarforging_1',
    },
  },
  'BasicAttackBloodbloomOathStarforging_2:standardDmg': {
    sheet: 'Claret',
    name: 'BasicAttackBloodbloomOathStarforging_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBloodbloomOathStarforging_2',
    },
  },
  'BasicAttackBloodbloomOathStarforging_2:dazeBuildup': {
    sheet: 'Claret',
    name: 'BasicAttackBloodbloomOathStarforging_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBloodbloomOathStarforging_2',
    },
  },
  'BasicAttackBloodbloomOathStarforging_2:anomBuildup': {
    sheet: 'Claret',
    name: 'BasicAttackBloodbloomOathStarforging_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBloodbloomOathStarforging_2',
    },
  },
  'BasicAttackBloodbloomOathStarforging_3:standardDmg': {
    sheet: 'Claret',
    name: 'BasicAttackBloodbloomOathStarforging_3:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBloodbloomOathStarforging_3',
    },
  },
  'BasicAttackBloodbloomOathStarforging_3:dazeBuildup': {
    sheet: 'Claret',
    name: 'BasicAttackBloodbloomOathStarforging_3:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBloodbloomOathStarforging_3',
    },
  },
  'BasicAttackBloodbloomOathStarforging_3:anomBuildup': {
    sheet: 'Claret',
    name: 'BasicAttackBloodbloomOathStarforging_3:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBloodbloomOathStarforging_3',
    },
  },
  'BasicAttackBloodbloomOathSubduingAxe_0:standardDmg': {
    sheet: 'Claret',
    name: 'BasicAttackBloodbloomOathSubduingAxe_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBloodbloomOathSubduingAxe_0',
    },
  },
  'BasicAttackBloodbloomOathSubduingAxe_0:dazeBuildup': {
    sheet: 'Claret',
    name: 'BasicAttackBloodbloomOathSubduingAxe_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBloodbloomOathSubduingAxe_0',
    },
  },
  'BasicAttackBloodbloomOathSubduingAxe_0:anomBuildup': {
    sheet: 'Claret',
    name: 'BasicAttackBloodbloomOathSubduingAxe_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackBloodbloomOathSubduingAxe_0',
    },
  },
  'DashAttackTempering_0:standardDmg': {
    sheet: 'Claret',
    name: 'DashAttackTempering_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackTempering_0',
    },
  },
  'DashAttackTempering_0:dazeBuildup': {
    sheet: 'Claret',
    name: 'DashAttackTempering_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackTempering_0',
    },
  },
  'DashAttackTempering_0:anomBuildup': {
    sheet: 'Claret',
    name: 'DashAttackTempering_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackTempering_0',
    },
  },
  'DodgeCounterReturningEdge_0:standardDmg': {
    sheet: 'Claret',
    name: 'DodgeCounterReturningEdge_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterReturningEdge_0',
    },
  },
  'DodgeCounterReturningEdge_0:dazeBuildup': {
    sheet: 'Claret',
    name: 'DodgeCounterReturningEdge_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterReturningEdge_0',
    },
  },
  'DodgeCounterReturningEdge_0:anomBuildup': {
    sheet: 'Claret',
    name: 'DodgeCounterReturningEdge_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterReturningEdge_0',
    },
  },
  'DodgeCounterBloodbloomOathReturningEdge_0:standardDmg': {
    sheet: 'Claret',
    name: 'DodgeCounterBloodbloomOathReturningEdge_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterBloodbloomOathReturningEdge_0',
    },
  },
  'DodgeCounterBloodbloomOathReturningEdge_0:dazeBuildup': {
    sheet: 'Claret',
    name: 'DodgeCounterBloodbloomOathReturningEdge_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterBloodbloomOathReturningEdge_0',
    },
  },
  'DodgeCounterBloodbloomOathReturningEdge_0:anomBuildup': {
    sheet: 'Claret',
    name: 'DodgeCounterBloodbloomOathReturningEdge_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterBloodbloomOathReturningEdge_0',
    },
  },
  'SpecialAttackPorcelumesFirstCall_0:standardDmg': {
    sheet: 'Claret',
    name: 'SpecialAttackPorcelumesFirstCall_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackPorcelumesFirstCall_0',
    },
  },
  'SpecialAttackPorcelumesFirstCall_0:dazeBuildup': {
    sheet: 'Claret',
    name: 'SpecialAttackPorcelumesFirstCall_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackPorcelumesFirstCall_0',
    },
  },
  'SpecialAttackPorcelumesFirstCall_0:anomBuildup': {
    sheet: 'Claret',
    name: 'SpecialAttackPorcelumesFirstCall_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackPorcelumesFirstCall_0',
    },
  },
  'EXSpecialAttackBloodbloomOathSecretForgingTechniques_0:standardDmg': {
    sheet: 'Claret',
    name: 'EXSpecialAttackBloodbloomOathSecretForgingTechniques_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackBloodbloomOathSecretForgingTechniques_0',
    },
  },
  'EXSpecialAttackBloodbloomOathSecretForgingTechniques_0:dazeBuildup': {
    sheet: 'Claret',
    name: 'EXSpecialAttackBloodbloomOathSecretForgingTechniques_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackBloodbloomOathSecretForgingTechniques_0',
    },
  },
  'EXSpecialAttackBloodbloomOathSecretForgingTechniques_0:anomBuildup': {
    sheet: 'Claret',
    name: 'EXSpecialAttackBloodbloomOathSecretForgingTechniques_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackBloodbloomOathSecretForgingTechniques_0',
    },
  },
  'SpecialAttackBloodbloomOathCleavingGoldAndIron_0:standardDmg': {
    sheet: 'Claret',
    name: 'SpecialAttackBloodbloomOathCleavingGoldAndIron_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackBloodbloomOathCleavingGoldAndIron_0',
    },
  },
  'SpecialAttackBloodbloomOathCleavingGoldAndIron_0:dazeBuildup': {
    sheet: 'Claret',
    name: 'SpecialAttackBloodbloomOathCleavingGoldAndIron_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackBloodbloomOathCleavingGoldAndIron_0',
    },
  },
  'SpecialAttackBloodbloomOathCleavingGoldAndIron_0:anomBuildup': {
    sheet: 'Claret',
    name: 'SpecialAttackBloodbloomOathCleavingGoldAndIron_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackBloodbloomOathCleavingGoldAndIron_0',
    },
  },
  'SpecialAttackBloodbloomOathCleavingGoldAndIron_1:standardDmg': {
    sheet: 'Claret',
    name: 'SpecialAttackBloodbloomOathCleavingGoldAndIron_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackBloodbloomOathCleavingGoldAndIron_1',
    },
  },
  'SpecialAttackBloodbloomOathCleavingGoldAndIron_1:dazeBuildup': {
    sheet: 'Claret',
    name: 'SpecialAttackBloodbloomOathCleavingGoldAndIron_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackBloodbloomOathCleavingGoldAndIron_1',
    },
  },
  'SpecialAttackBloodbloomOathCleavingGoldAndIron_1:anomBuildup': {
    sheet: 'Claret',
    name: 'SpecialAttackBloodbloomOathCleavingGoldAndIron_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackBloodbloomOathCleavingGoldAndIron_1',
    },
  },
  'SpecialAttackBloodbloomOathCleavingGoldAndIron_2:standardDmg': {
    sheet: 'Claret',
    name: 'SpecialAttackBloodbloomOathCleavingGoldAndIron_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackBloodbloomOathCleavingGoldAndIron_2',
    },
  },
  'SpecialAttackBloodbloomOathCleavingGoldAndIron_2:dazeBuildup': {
    sheet: 'Claret',
    name: 'SpecialAttackBloodbloomOathCleavingGoldAndIron_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackBloodbloomOathCleavingGoldAndIron_2',
    },
  },
  'SpecialAttackBloodbloomOathCleavingGoldAndIron_2:anomBuildup': {
    sheet: 'Claret',
    name: 'SpecialAttackBloodbloomOathCleavingGoldAndIron_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackBloodbloomOathCleavingGoldAndIron_2',
    },
  },
  'SpecialAttackBloodbloomOathBloodBurialAssault_0:standardDmg': {
    sheet: 'Claret',
    name: 'SpecialAttackBloodbloomOathBloodBurialAssault_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackBloodbloomOathBloodBurialAssault_0',
    },
  },
  'SpecialAttackBloodbloomOathBloodBurialAssault_0:dazeBuildup': {
    sheet: 'Claret',
    name: 'SpecialAttackBloodbloomOathBloodBurialAssault_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackBloodbloomOathBloodBurialAssault_0',
    },
  },
  'SpecialAttackBloodbloomOathBloodBurialAssault_0:anomBuildup': {
    sheet: 'Claret',
    name: 'SpecialAttackBloodbloomOathBloodBurialAssault_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackBloodbloomOathBloodBurialAssault_0',
    },
  },
  'ChainAttackBloodbloomOathResonantBloodPact_0:standardDmg': {
    sheet: 'Claret',
    name: 'ChainAttackBloodbloomOathResonantBloodPact_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackBloodbloomOathResonantBloodPact_0',
    },
  },
  'ChainAttackBloodbloomOathResonantBloodPact_0:dazeBuildup': {
    sheet: 'Claret',
    name: 'ChainAttackBloodbloomOathResonantBloodPact_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackBloodbloomOathResonantBloodPact_0',
    },
  },
  'ChainAttackBloodbloomOathResonantBloodPact_0:anomBuildup': {
    sheet: 'Claret',
    name: 'ChainAttackBloodbloomOathResonantBloodPact_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackBloodbloomOathResonantBloodPact_0',
    },
  },
  'UltimateBloodbloomOathTrialAfterTrial_0:standardDmg': {
    sheet: 'Claret',
    name: 'UltimateBloodbloomOathTrialAfterTrial_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateBloodbloomOathTrialAfterTrial_0',
    },
  },
  'UltimateBloodbloomOathTrialAfterTrial_0:dazeBuildup': {
    sheet: 'Claret',
    name: 'UltimateBloodbloomOathTrialAfterTrial_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateBloodbloomOathTrialAfterTrial_0',
    },
  },
  'UltimateBloodbloomOathTrialAfterTrial_0:anomBuildup': {
    sheet: 'Claret',
    name: 'UltimateBloodbloomOathTrialAfterTrial_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateBloodbloomOathTrialAfterTrial_0',
    },
  },
  'QuickAssistReturnOfTheDireMoon_0:standardDmg': {
    sheet: 'Claret',
    name: 'QuickAssistReturnOfTheDireMoon_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistReturnOfTheDireMoon_0',
    },
  },
  'QuickAssistReturnOfTheDireMoon_0:dazeBuildup': {
    sheet: 'Claret',
    name: 'QuickAssistReturnOfTheDireMoon_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistReturnOfTheDireMoon_0',
    },
  },
  'QuickAssistReturnOfTheDireMoon_0:anomBuildup': {
    sheet: 'Claret',
    name: 'QuickAssistReturnOfTheDireMoon_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistReturnOfTheDireMoon_0',
    },
  },
  'QuickAssistBloodbloomOathReturnOfTheDireMoon_0:standardDmg': {
    sheet: 'Claret',
    name: 'QuickAssistBloodbloomOathReturnOfTheDireMoon_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistBloodbloomOathReturnOfTheDireMoon_0',
    },
  },
  'QuickAssistBloodbloomOathReturnOfTheDireMoon_0:dazeBuildup': {
    sheet: 'Claret',
    name: 'QuickAssistBloodbloomOathReturnOfTheDireMoon_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistBloodbloomOathReturnOfTheDireMoon_0',
    },
  },
  'QuickAssistBloodbloomOathReturnOfTheDireMoon_0:anomBuildup': {
    sheet: 'Claret',
    name: 'QuickAssistBloodbloomOathReturnOfTheDireMoon_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistBloodbloomOathReturnOfTheDireMoon_0',
    },
  },
  'DefensiveAssistUnyieldingHeartOfTheFurnace_0:standardDmg': {
    sheet: 'Claret',
    name: 'DefensiveAssistUnyieldingHeartOfTheFurnace_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistUnyieldingHeartOfTheFurnace_0',
    },
  },
  'DefensiveAssistUnyieldingHeartOfTheFurnace_0:dazeBuildup': {
    sheet: 'Claret',
    name: 'DefensiveAssistUnyieldingHeartOfTheFurnace_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistUnyieldingHeartOfTheFurnace_0',
    },
  },
  'DefensiveAssistUnyieldingHeartOfTheFurnace_0:anomBuildup': {
    sheet: 'Claret',
    name: 'DefensiveAssistUnyieldingHeartOfTheFurnace_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistUnyieldingHeartOfTheFurnace_0',
    },
  },
  'DefensiveAssistUnyieldingHeartOfTheFurnace_1:standardDmg': {
    sheet: 'Claret',
    name: 'DefensiveAssistUnyieldingHeartOfTheFurnace_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistUnyieldingHeartOfTheFurnace_1',
    },
  },
  'DefensiveAssistUnyieldingHeartOfTheFurnace_1:dazeBuildup': {
    sheet: 'Claret',
    name: 'DefensiveAssistUnyieldingHeartOfTheFurnace_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistUnyieldingHeartOfTheFurnace_1',
    },
  },
  'DefensiveAssistUnyieldingHeartOfTheFurnace_1:anomBuildup': {
    sheet: 'Claret',
    name: 'DefensiveAssistUnyieldingHeartOfTheFurnace_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistUnyieldingHeartOfTheFurnace_1',
    },
  },
  'DefensiveAssistUnyieldingHeartOfTheFurnace_2:standardDmg': {
    sheet: 'Claret',
    name: 'DefensiveAssistUnyieldingHeartOfTheFurnace_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistUnyieldingHeartOfTheFurnace_2',
    },
  },
  'DefensiveAssistUnyieldingHeartOfTheFurnace_2:dazeBuildup': {
    sheet: 'Claret',
    name: 'DefensiveAssistUnyieldingHeartOfTheFurnace_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistUnyieldingHeartOfTheFurnace_2',
    },
  },
  'DefensiveAssistUnyieldingHeartOfTheFurnace_2:anomBuildup': {
    sheet: 'Claret',
    name: 'DefensiveAssistUnyieldingHeartOfTheFurnace_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistUnyieldingHeartOfTheFurnace_2',
    },
  },
  'AssistFollowUpBloodbloomOathPureforgedEdge_0:standardDmg': {
    sheet: 'Claret',
    name: 'AssistFollowUpBloodbloomOathPureforgedEdge_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpBloodbloomOathPureforgedEdge_0',
    },
  },
  'AssistFollowUpBloodbloomOathPureforgedEdge_0:dazeBuildup': {
    sheet: 'Claret',
    name: 'AssistFollowUpBloodbloomOathPureforgedEdge_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpBloodbloomOathPureforgedEdge_0',
    },
  },
  'AssistFollowUpBloodbloomOathPureforgedEdge_0:anomBuildup': {
    sheet: 'Claret',
    name: 'AssistFollowUpBloodbloomOathPureforgedEdge_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpBloodbloomOathPureforgedEdge_0',
    },
  },
  'CounterAssistGiveNotAnInchOfSteel_0:standardDmg': {
    sheet: 'Claret',
    name: 'CounterAssistGiveNotAnInchOfSteel_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'counterAssist',
      skillType: 'assistSkill',
      name: 'CounterAssistGiveNotAnInchOfSteel_0',
    },
  },
  'CounterAssistGiveNotAnInchOfSteel_0:dazeBuildup': {
    sheet: 'Claret',
    name: 'CounterAssistGiveNotAnInchOfSteel_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'counterAssist',
      skillType: 'assistSkill',
      name: 'CounterAssistGiveNotAnInchOfSteel_0',
    },
  },
  'CounterAssistGiveNotAnInchOfSteel_0:anomBuildup': {
    sheet: 'Claret',
    name: 'CounterAssistGiveNotAnInchOfSteel_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'counterAssist',
      skillType: 'assistSkill',
      name: 'CounterAssistGiveNotAnInchOfSteel_0',
    },
  },
  'AssistFollowUpBloodbloomOathHammerIntoShape_0:standardDmg': {
    sheet: 'Claret',
    name: 'AssistFollowUpBloodbloomOathHammerIntoShape_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpBloodbloomOathHammerIntoShape_0',
    },
  },
  'AssistFollowUpBloodbloomOathHammerIntoShape_0:dazeBuildup': {
    sheet: 'Claret',
    name: 'AssistFollowUpBloodbloomOathHammerIntoShape_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpBloodbloomOathHammerIntoShape_0',
    },
  },
  'AssistFollowUpBloodbloomOathHammerIntoShape_0:anomBuildup': {
    sheet: 'Claret',
    name: 'AssistFollowUpBloodbloomOathHammerIntoShape_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Claret',
      attribute: 'electric',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpBloodbloomOathHammerIntoShape_0',
    },
  },
} as const
