export type TalentSheetElementKey =
  | 'basic'
  | 'skill'
  | 'ultimate'
  | 'talent'
  | 'passive1'
  | 'passive2'
  | 'passive3'
  | 'eidolon1'
  | 'eidolon2'
  | 'eidolon3'
  | 'eidolon4'
  | 'eidolon5'
  | 'eidolon6'
