// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Jane',
    name: 'standardDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Jane',
      attribute: 'physical',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Jane',
    name: 'anomalyDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_physical: {
    sheet: 'Jane',
    name: 'disorderDmgInst_physical',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'disorder',
      name: 'disorderDmgInst_physical',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Jane',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Jane',
      attribute: 'physical',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Jane',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Jane',
      attribute: 'physical',
      name: 'dazeInst',
    },
  },
  BasicAttackDancingBlades_0_dmg: {
    sheet: 'Jane',
    name: 'BasicAttackDancingBlades_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackDancingBlades_0_dmg',
    },
  },
  BasicAttackDancingBlades_0_daze: {
    sheet: 'Jane',
    name: 'BasicAttackDancingBlades_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackDancingBlades_0_daze',
    },
  },
  BasicAttackDancingBlades_0_anomBuildup: {
    sheet: 'Jane',
    name: 'BasicAttackDancingBlades_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackDancingBlades_0_anomBuildup',
    },
  },
  BasicAttackDancingBlades_1_dmg: {
    sheet: 'Jane',
    name: 'BasicAttackDancingBlades_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackDancingBlades_1_dmg',
    },
  },
  BasicAttackDancingBlades_1_daze: {
    sheet: 'Jane',
    name: 'BasicAttackDancingBlades_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackDancingBlades_1_daze',
    },
  },
  BasicAttackDancingBlades_1_anomBuildup: {
    sheet: 'Jane',
    name: 'BasicAttackDancingBlades_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackDancingBlades_1_anomBuildup',
    },
  },
  BasicAttackDancingBlades_2_dmg: {
    sheet: 'Jane',
    name: 'BasicAttackDancingBlades_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackDancingBlades_2_dmg',
    },
  },
  BasicAttackDancingBlades_2_daze: {
    sheet: 'Jane',
    name: 'BasicAttackDancingBlades_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackDancingBlades_2_daze',
    },
  },
  BasicAttackDancingBlades_2_anomBuildup: {
    sheet: 'Jane',
    name: 'BasicAttackDancingBlades_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackDancingBlades_2_anomBuildup',
    },
  },
  BasicAttackDancingBlades_3_dmg: {
    sheet: 'Jane',
    name: 'BasicAttackDancingBlades_3_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackDancingBlades_3_dmg',
    },
  },
  BasicAttackDancingBlades_3_daze: {
    sheet: 'Jane',
    name: 'BasicAttackDancingBlades_3_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackDancingBlades_3_daze',
    },
  },
  BasicAttackDancingBlades_3_anomBuildup: {
    sheet: 'Jane',
    name: 'BasicAttackDancingBlades_3_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackDancingBlades_3_anomBuildup',
    },
  },
  BasicAttackDancingBlades_4_dmg: {
    sheet: 'Jane',
    name: 'BasicAttackDancingBlades_4_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackDancingBlades_4_dmg',
    },
  },
  BasicAttackDancingBlades_4_daze: {
    sheet: 'Jane',
    name: 'BasicAttackDancingBlades_4_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackDancingBlades_4_daze',
    },
  },
  BasicAttackDancingBlades_4_anomBuildup: {
    sheet: 'Jane',
    name: 'BasicAttackDancingBlades_4_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackDancingBlades_4_anomBuildup',
    },
  },
  BasicAttackDancingBlades_5_dmg: {
    sheet: 'Jane',
    name: 'BasicAttackDancingBlades_5_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackDancingBlades_5_dmg',
    },
  },
  BasicAttackDancingBlades_5_daze: {
    sheet: 'Jane',
    name: 'BasicAttackDancingBlades_5_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackDancingBlades_5_daze',
    },
  },
  BasicAttackDancingBlades_5_anomBuildup: {
    sheet: 'Jane',
    name: 'BasicAttackDancingBlades_5_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackDancingBlades_5_anomBuildup',
    },
  },
  BasicAttackSalchowJump_0_dmg: {
    sheet: 'Jane',
    name: 'BasicAttackSalchowJump_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSalchowJump_0_dmg',
    },
  },
  BasicAttackSalchowJump_0_daze: {
    sheet: 'Jane',
    name: 'BasicAttackSalchowJump_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSalchowJump_0_daze',
    },
  },
  BasicAttackSalchowJump_0_anomBuildup: {
    sheet: 'Jane',
    name: 'BasicAttackSalchowJump_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSalchowJump_0_anomBuildup',
    },
  },
  BasicAttackSalchowJump_1_dmg: {
    sheet: 'Jane',
    name: 'BasicAttackSalchowJump_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSalchowJump_1_dmg',
    },
  },
  BasicAttackSalchowJump_1_daze: {
    sheet: 'Jane',
    name: 'BasicAttackSalchowJump_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSalchowJump_1_daze',
    },
  },
  BasicAttackSalchowJump_1_anomBuildup: {
    sheet: 'Jane',
    name: 'BasicAttackSalchowJump_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSalchowJump_1_anomBuildup',
    },
  },
  DashAttackEdgeJump_0_dmg: {
    sheet: 'Jane',
    name: 'DashAttackEdgeJump_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackEdgeJump_0_dmg',
    },
  },
  DashAttackEdgeJump_0_daze: {
    sheet: 'Jane',
    name: 'DashAttackEdgeJump_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackEdgeJump_0_daze',
    },
  },
  DashAttackEdgeJump_0_anomBuildup: {
    sheet: 'Jane',
    name: 'DashAttackEdgeJump_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackEdgeJump_0_anomBuildup',
    },
  },
  DashAttackEdgeJump_1_dmg: {
    sheet: 'Jane',
    name: 'DashAttackEdgeJump_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackEdgeJump_1_dmg',
    },
  },
  DashAttackEdgeJump_1_daze: {
    sheet: 'Jane',
    name: 'DashAttackEdgeJump_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackEdgeJump_1_daze',
    },
  },
  DashAttackEdgeJump_1_anomBuildup: {
    sheet: 'Jane',
    name: 'DashAttackEdgeJump_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackEdgeJump_1_anomBuildup',
    },
  },
  DashAttackPhantomThrust_0_dmg: {
    sheet: 'Jane',
    name: 'DashAttackPhantomThrust_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackPhantomThrust_0_dmg',
    },
  },
  DashAttackPhantomThrust_0_daze: {
    sheet: 'Jane',
    name: 'DashAttackPhantomThrust_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackPhantomThrust_0_daze',
    },
  },
  DashAttackPhantomThrust_0_anomBuildup: {
    sheet: 'Jane',
    name: 'DashAttackPhantomThrust_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackPhantomThrust_0_anomBuildup',
    },
  },
  DodgeCounterSwiftShadow_0_dmg: {
    sheet: 'Jane',
    name: 'DodgeCounterSwiftShadow_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterSwiftShadow_0_dmg',
    },
  },
  DodgeCounterSwiftShadow_0_daze: {
    sheet: 'Jane',
    name: 'DodgeCounterSwiftShadow_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterSwiftShadow_0_daze',
    },
  },
  DodgeCounterSwiftShadow_0_anomBuildup: {
    sheet: 'Jane',
    name: 'DodgeCounterSwiftShadow_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterSwiftShadow_0_anomBuildup',
    },
  },
  DodgeCounterSwiftShadow_1_dmg: {
    sheet: 'Jane',
    name: 'DodgeCounterSwiftShadow_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterSwiftShadow_1_dmg',
    },
  },
  DodgeCounterSwiftShadow_1_daze: {
    sheet: 'Jane',
    name: 'DodgeCounterSwiftShadow_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterSwiftShadow_1_daze',
    },
  },
  DodgeCounterSwiftShadow_1_anomBuildup: {
    sheet: 'Jane',
    name: 'DodgeCounterSwiftShadow_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterSwiftShadow_1_anomBuildup',
    },
  },
  DodgeCounterSwiftShadowDance_0_dmg: {
    sheet: 'Jane',
    name: 'DodgeCounterSwiftShadowDance_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterSwiftShadowDance_0_dmg',
    },
  },
  DodgeCounterSwiftShadowDance_0_daze: {
    sheet: 'Jane',
    name: 'DodgeCounterSwiftShadowDance_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterSwiftShadowDance_0_daze',
    },
  },
  DodgeCounterSwiftShadowDance_0_anomBuildup: {
    sheet: 'Jane',
    name: 'DodgeCounterSwiftShadowDance_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterSwiftShadowDance_0_anomBuildup',
    },
  },
  SpecialAttackAerialSweep_0_dmg: {
    sheet: 'Jane',
    name: 'SpecialAttackAerialSweep_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackAerialSweep_0_dmg',
    },
  },
  SpecialAttackAerialSweep_0_daze: {
    sheet: 'Jane',
    name: 'SpecialAttackAerialSweep_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackAerialSweep_0_daze',
    },
  },
  SpecialAttackAerialSweep_0_anomBuildup: {
    sheet: 'Jane',
    name: 'SpecialAttackAerialSweep_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackAerialSweep_0_anomBuildup',
    },
  },
  EXSpecialAttackAerialSweepClearout_0_dmg: {
    sheet: 'Jane',
    name: 'EXSpecialAttackAerialSweepClearout_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackAerialSweepClearout_0_dmg',
    },
  },
  EXSpecialAttackAerialSweepClearout_0_daze: {
    sheet: 'Jane',
    name: 'EXSpecialAttackAerialSweepClearout_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackAerialSweepClearout_0_daze',
    },
  },
  EXSpecialAttackAerialSweepClearout_0_anomBuildup: {
    sheet: 'Jane',
    name: 'EXSpecialAttackAerialSweepClearout_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackAerialSweepClearout_0_anomBuildup',
    },
  },
  ChainAttackFlowersOfSin_0_dmg: {
    sheet: 'Jane',
    name: 'ChainAttackFlowersOfSin_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackFlowersOfSin_0_dmg',
    },
  },
  ChainAttackFlowersOfSin_0_daze: {
    sheet: 'Jane',
    name: 'ChainAttackFlowersOfSin_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackFlowersOfSin_0_daze',
    },
  },
  ChainAttackFlowersOfSin_0_anomBuildup: {
    sheet: 'Jane',
    name: 'ChainAttackFlowersOfSin_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackFlowersOfSin_0_anomBuildup',
    },
  },
  UltimateFinalCurtain_0_dmg: {
    sheet: 'Jane',
    name: 'UltimateFinalCurtain_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateFinalCurtain_0_dmg',
    },
  },
  UltimateFinalCurtain_0_daze: {
    sheet: 'Jane',
    name: 'UltimateFinalCurtain_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateFinalCurtain_0_daze',
    },
  },
  UltimateFinalCurtain_0_anomBuildup: {
    sheet: 'Jane',
    name: 'UltimateFinalCurtain_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateFinalCurtain_0_anomBuildup',
    },
  },
  QuickAssistDarkThorn_0_dmg: {
    sheet: 'Jane',
    name: 'QuickAssistDarkThorn_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistDarkThorn_0_dmg',
    },
  },
  QuickAssistDarkThorn_0_daze: {
    sheet: 'Jane',
    name: 'QuickAssistDarkThorn_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistDarkThorn_0_daze',
    },
  },
  QuickAssistDarkThorn_0_anomBuildup: {
    sheet: 'Jane',
    name: 'QuickAssistDarkThorn_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistDarkThorn_0_anomBuildup',
    },
  },
  QuickAssistLutzJump_0_dmg: {
    sheet: 'Jane',
    name: 'QuickAssistLutzJump_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistLutzJump_0_dmg',
    },
  },
  QuickAssistLutzJump_0_daze: {
    sheet: 'Jane',
    name: 'QuickAssistLutzJump_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistLutzJump_0_daze',
    },
  },
  QuickAssistLutzJump_0_anomBuildup: {
    sheet: 'Jane',
    name: 'QuickAssistLutzJump_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistLutzJump_0_anomBuildup',
    },
  },
  DefensiveAssistLastDefense_0_dmg: {
    sheet: 'Jane',
    name: 'DefensiveAssistLastDefense_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistLastDefense_0_dmg',
    },
  },
  DefensiveAssistLastDefense_0_daze: {
    sheet: 'Jane',
    name: 'DefensiveAssistLastDefense_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistLastDefense_0_daze',
    },
  },
  DefensiveAssistLastDefense_0_anomBuildup: {
    sheet: 'Jane',
    name: 'DefensiveAssistLastDefense_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistLastDefense_0_anomBuildup',
    },
  },
  DefensiveAssistLastDefense_1_dmg: {
    sheet: 'Jane',
    name: 'DefensiveAssistLastDefense_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistLastDefense_1_dmg',
    },
  },
  DefensiveAssistLastDefense_1_daze: {
    sheet: 'Jane',
    name: 'DefensiveAssistLastDefense_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistLastDefense_1_daze',
    },
  },
  DefensiveAssistLastDefense_1_anomBuildup: {
    sheet: 'Jane',
    name: 'DefensiveAssistLastDefense_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistLastDefense_1_anomBuildup',
    },
  },
  DefensiveAssistLastDefense_2_dmg: {
    sheet: 'Jane',
    name: 'DefensiveAssistLastDefense_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistLastDefense_2_dmg',
    },
  },
  DefensiveAssistLastDefense_2_daze: {
    sheet: 'Jane',
    name: 'DefensiveAssistLastDefense_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistLastDefense_2_daze',
    },
  },
  DefensiveAssistLastDefense_2_anomBuildup: {
    sheet: 'Jane',
    name: 'DefensiveAssistLastDefense_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistLastDefense_2_anomBuildup',
    },
  },
  AssistFollowUpGaleSweep_0_dmg: {
    sheet: 'Jane',
    name: 'AssistFollowUpGaleSweep_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpGaleSweep_0_dmg',
    },
  },
  AssistFollowUpGaleSweep_0_daze: {
    sheet: 'Jane',
    name: 'AssistFollowUpGaleSweep_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpGaleSweep_0_daze',
    },
  },
  AssistFollowUpGaleSweep_0_anomBuildup: {
    sheet: 'Jane',
    name: 'AssistFollowUpGaleSweep_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpGaleSweep_0_anomBuildup',
    },
  },
  m6_additional_dmg: {
    sheet: 'Jane',
    name: 'm6_additional_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'elemental',
      name: 'm6_additional_dmg',
    },
  },
} as const
