// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Jane',
    name: 'standardDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'standardDmgBase',
      sheet: 'Jane',
      attribute: 'physical',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Jane',
    name: 'anomalyDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_physical: {
    sheet: 'Jane',
    name: 'disorderDmgInst_physical',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'disorder',
      name: 'disorderDmgInst_physical',
    },
  },
  vortexDmgInst_physical: {
    sheet: 'Jane',
    name: 'vortexDmgInst_physical',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'vortex',
      name: 'vortexDmgInst_physical',
    },
  },
  abloomDmgInst: {
    sheet: 'Jane',
    name: 'abloomDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Jane',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Jane',
      attribute: 'physical',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Jane',
    name: 'dazeInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'dazeBuildupBase',
      sheet: 'Jane',
      attribute: 'physical',
      name: 'dazeInst',
    },
  },
  BasicAttackDancingBlades_0: {
    sheet: 'Jane',
    name: 'BasicAttackDancingBlades_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackDancingBlades_0',
    },
  },
  BasicAttackDancingBlades_1: {
    sheet: 'Jane',
    name: 'BasicAttackDancingBlades_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackDancingBlades_1',
    },
  },
  BasicAttackDancingBlades_2: {
    sheet: 'Jane',
    name: 'BasicAttackDancingBlades_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackDancingBlades_2',
    },
  },
  BasicAttackDancingBlades_3: {
    sheet: 'Jane',
    name: 'BasicAttackDancingBlades_3',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackDancingBlades_3',
    },
  },
  BasicAttackDancingBlades_4: {
    sheet: 'Jane',
    name: 'BasicAttackDancingBlades_4',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackDancingBlades_4',
    },
  },
  BasicAttackDancingBlades_5: {
    sheet: 'Jane',
    name: 'BasicAttackDancingBlades_5',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackDancingBlades_5',
    },
  },
  BasicAttackSalchowJump_0: {
    sheet: 'Jane',
    name: 'BasicAttackSalchowJump_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSalchowJump_0',
    },
  },
  BasicAttackSalchowJump_1: {
    sheet: 'Jane',
    name: 'BasicAttackSalchowJump_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSalchowJump_1',
    },
  },
  DashAttackEdgeJump_0: {
    sheet: 'Jane',
    name: 'DashAttackEdgeJump_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackEdgeJump_0',
    },
  },
  DashAttackEdgeJump_1: {
    sheet: 'Jane',
    name: 'DashAttackEdgeJump_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackEdgeJump_1',
    },
  },
  DashAttackPhantomThrust_0: {
    sheet: 'Jane',
    name: 'DashAttackPhantomThrust_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackPhantomThrust_0',
    },
  },
  DodgeCounterSwiftShadow_0: {
    sheet: 'Jane',
    name: 'DodgeCounterSwiftShadow_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterSwiftShadow_0',
    },
  },
  DodgeCounterSwiftShadow_1: {
    sheet: 'Jane',
    name: 'DodgeCounterSwiftShadow_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterSwiftShadow_1',
    },
  },
  DodgeCounterSwiftShadowDance_0: {
    sheet: 'Jane',
    name: 'DodgeCounterSwiftShadowDance_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterSwiftShadowDance_0',
    },
  },
  SpecialAttackAerialSweep_0: {
    sheet: 'Jane',
    name: 'SpecialAttackAerialSweep_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackAerialSweep_0',
    },
  },
  EXSpecialAttackAerialSweepClearout_0: {
    sheet: 'Jane',
    name: 'EXSpecialAttackAerialSweepClearout_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackAerialSweepClearout_0',
    },
  },
  ChainAttackFlowersOfSin_0: {
    sheet: 'Jane',
    name: 'ChainAttackFlowersOfSin_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackFlowersOfSin_0',
    },
  },
  UltimateFinalCurtain_0: {
    sheet: 'Jane',
    name: 'UltimateFinalCurtain_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateFinalCurtain_0',
    },
  },
  QuickAssistDarkThorn_0: {
    sheet: 'Jane',
    name: 'QuickAssistDarkThorn_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistDarkThorn_0',
    },
  },
  QuickAssistLutzJump_0: {
    sheet: 'Jane',
    name: 'QuickAssistLutzJump_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistLutzJump_0',
    },
  },
  DefensiveAssistLastDefense_0: {
    sheet: 'Jane',
    name: 'DefensiveAssistLastDefense_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistLastDefense_0',
    },
  },
  DefensiveAssistLastDefense_1: {
    sheet: 'Jane',
    name: 'DefensiveAssistLastDefense_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistLastDefense_1',
    },
  },
  DefensiveAssistLastDefense_2: {
    sheet: 'Jane',
    name: 'DefensiveAssistLastDefense_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistLastDefense_2',
    },
  },
  AssistFollowUpGaleSweep_0: {
    sheet: 'Jane',
    name: 'AssistFollowUpGaleSweep_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpGaleSweep_0',
    },
  },
  m6_additional_dmg: {
    sheet: 'Jane',
    name: 'm6_additional_dmg',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'standardDmgBase',
      sheet: 'Jane',
      attribute: 'physical',
      damageType1: 'elemental',
      name: 'm6_additional_dmg',
    },
  },
} as const
