// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Pyrois',
    name: 'standardDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'standardDmgBase',
      sheet: 'Pyrois',
      attribute: 'ether',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Pyrois',
    name: 'anomalyDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Pyrois',
      attribute: 'ether',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_ether: {
    sheet: 'Pyrois',
    name: 'disorderDmgInst_ether',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Pyrois',
      attribute: 'ether',
      damageType1: 'disorder',
      name: 'disorderDmgInst_ether',
    },
  },
  vortexDmgInst_ether: {
    sheet: 'Pyrois',
    name: 'vortexDmgInst_ether',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Pyrois',
      attribute: 'ether',
      damageType1: 'vortex',
      name: 'vortexDmgInst_ether',
    },
  },
  abloomDmgInst: {
    sheet: 'Pyrois',
    name: 'abloomDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Pyrois',
      attribute: 'ether',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Pyrois',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Pyrois',
      attribute: 'ether',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Pyrois',
    name: 'dazeInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'dazeBuildupBase',
      sheet: 'Pyrois',
      attribute: 'ether',
      name: 'dazeInst',
    },
  },
  BasicAttackEmberglow_0: {
    sheet: 'Pyrois',
    name: 'BasicAttackEmberglow_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Pyrois',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEmberglow_0',
    },
  },
  BasicAttackEmberglow_1: {
    sheet: 'Pyrois',
    name: 'BasicAttackEmberglow_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Pyrois',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEmberglow_1',
    },
  },
  BasicAttackEmberglow_2: {
    sheet: 'Pyrois',
    name: 'BasicAttackEmberglow_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Pyrois',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEmberglow_2',
    },
  },
  BasicAttackCelestialLight_0: {
    sheet: 'Pyrois',
    name: 'BasicAttackCelestialLight_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Pyrois',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackCelestialLight_0',
    },
  },
  BasicAttackCelestialLight_1: {
    sheet: 'Pyrois',
    name: 'BasicAttackCelestialLight_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Pyrois',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackCelestialLight_1',
    },
  },
  BasicAttackCelestialLight_2: {
    sheet: 'Pyrois',
    name: 'BasicAttackCelestialLight_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Pyrois',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackCelestialLight_2',
    },
  },
  BasicAttackCelestialLight_3: {
    sheet: 'Pyrois',
    name: 'BasicAttackCelestialLight_3',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Pyrois',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackCelestialLight_3',
    },
  },
  DashAttackSunrise_0: {
    sheet: 'Pyrois',
    name: 'DashAttackSunrise_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Pyrois',
      attribute: 'ether',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackSunrise_0',
    },
  },
  DodgeCounterFirstLight_0: {
    sheet: 'Pyrois',
    name: 'DodgeCounterFirstLight_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Pyrois',
      attribute: 'ether',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterFirstLight_0',
    },
  },
  SpecialAttackFadingRays_0: {
    sheet: 'Pyrois',
    name: 'SpecialAttackFadingRays_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Pyrois',
      attribute: 'ether',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackFadingRays_0',
    },
  },
  EXSpecialAttackSunsHalo_0: {
    sheet: 'Pyrois',
    name: 'EXSpecialAttackSunsHalo_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Pyrois',
      attribute: 'ether',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackSunsHalo_0',
    },
  },
  SpecialAttackAssaultDirective_0: {
    sheet: 'Pyrois',
    name: 'SpecialAttackAssaultDirective_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Pyrois',
      attribute: 'ether',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackAssaultDirective_0',
    },
  },
  ChainAttackCeremonialMarch_0: {
    sheet: 'Pyrois',
    name: 'ChainAttackCeremonialMarch_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Pyrois',
      attribute: 'ether',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackCeremonialMarch_0',
    },
  },
  UltimateTotalAnnihilation_0: {
    sheet: 'Pyrois',
    name: 'UltimateTotalAnnihilation_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Pyrois',
      attribute: 'ether',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateTotalAnnihilation_0',
    },
  },
  UltimateTriumphantReturn_0: {
    sheet: 'Pyrois',
    name: 'UltimateTriumphantReturn_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Pyrois',
      attribute: 'ether',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateTriumphantReturn_0',
    },
  },
  UltimateUnboundSwordstorm_0: {
    sheet: 'Pyrois',
    name: 'UltimateUnboundSwordstorm_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Pyrois',
      attribute: 'ether',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateUnboundSwordstorm_0',
    },
  },
  UltimateEternalImprisonment_0: {
    sheet: 'Pyrois',
    name: 'UltimateEternalImprisonment_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Pyrois',
      attribute: 'ether',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateEternalImprisonment_0',
    },
  },
  QuickAssistDuskguard_0: {
    sheet: 'Pyrois',
    name: 'QuickAssistDuskguard_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Pyrois',
      attribute: 'ether',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistDuskguard_0',
    },
  },
  DefensiveAssistIronhideBehemoth_0: {
    sheet: 'Pyrois',
    name: 'DefensiveAssistIronhideBehemoth_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Pyrois',
      attribute: 'ether',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistIronhideBehemoth_0',
    },
  },
  DefensiveAssistIronhideBehemoth_1: {
    sheet: 'Pyrois',
    name: 'DefensiveAssistIronhideBehemoth_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Pyrois',
      attribute: 'ether',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistIronhideBehemoth_1',
    },
  },
  DefensiveAssistIronhideBehemoth_2: {
    sheet: 'Pyrois',
    name: 'DefensiveAssistIronhideBehemoth_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Pyrois',
      attribute: 'ether',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistIronhideBehemoth_2',
    },
  },
  AssistFollowUpReturnToDaylight_0: {
    sheet: 'Pyrois',
    name: 'AssistFollowUpReturnToDaylight_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Pyrois',
      attribute: 'ether',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpReturnToDaylight_0',
    },
  },
} as const
