// WARNING: Generated file, do not modify
export const conditionals = {} as const
export const formulas = {
  Anby: {
    anomalyDmgInst: {
      sheet: 'Anby',
      name: 'anomalyDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'anomalyDmg',
        sheet: 'Anby',
        attribute: 'electric',
        damageType1: 'anomaly',
        name: 'anomalyDmgInst',
      },
    },
    standardDmgInst: {
      sheet: 'Anby',
      name: 'standardDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'standardDmg',
        sheet: 'Anby',
        attribute: 'electric',
        damageType1: 'elemental',
        name: 'standardDmgInst',
      },
    },
  },
  Anton: {
    anomalyDmgInst: {
      sheet: 'Anton',
      name: 'anomalyDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'anomalyDmg',
        sheet: 'Anton',
        attribute: 'electric',
        damageType1: 'anomaly',
        name: 'anomalyDmgInst',
      },
    },
    standardDmgInst: {
      sheet: 'Anton',
      name: 'standardDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'standardDmg',
        sheet: 'Anton',
        attribute: 'electric',
        damageType1: 'elemental',
        name: 'standardDmgInst',
      },
    },
  },
  Astra: {
    anomalyDmgInst: {
      sheet: 'Astra',
      name: 'anomalyDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'anomalyDmg',
        sheet: 'Astra',
        attribute: 'ether',
        damageType1: 'anomaly',
        name: 'anomalyDmgInst',
      },
    },
    standardDmgInst: {
      sheet: 'Astra',
      name: 'standardDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'standardDmg',
        sheet: 'Astra',
        attribute: 'ether',
        damageType1: 'elemental',
        name: 'standardDmgInst',
      },
    },
  },
  Ben: {
    anomalyDmgInst: {
      sheet: 'Ben',
      name: 'anomalyDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'anomalyDmg',
        sheet: 'Ben',
        attribute: 'fire',
        damageType1: 'anomaly',
        name: 'anomalyDmgInst',
      },
    },
    standardDmgInst: {
      sheet: 'Ben',
      name: 'standardDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'standardDmg',
        sheet: 'Ben',
        attribute: 'fire',
        damageType1: 'elemental',
        name: 'standardDmgInst',
      },
    },
  },
  Billy: {
    anomalyDmgInst: {
      sheet: 'Billy',
      name: 'anomalyDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'anomalyDmg',
        sheet: 'Billy',
        attribute: 'physical',
        damageType1: 'anomaly',
        name: 'anomalyDmgInst',
      },
    },
    standardDmgInst: {
      sheet: 'Billy',
      name: 'standardDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'standardDmg',
        sheet: 'Billy',
        attribute: 'physical',
        damageType1: 'elemental',
        name: 'standardDmgInst',
      },
    },
  },
  Burnice: {
    anomalyDmgInst: {
      sheet: 'Burnice',
      name: 'anomalyDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'anomalyDmg',
        sheet: 'Burnice',
        attribute: 'fire',
        damageType1: 'anomaly',
        name: 'anomalyDmgInst',
      },
    },
    standardDmgInst: {
      sheet: 'Burnice',
      name: 'standardDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'standardDmg',
        sheet: 'Burnice',
        attribute: 'fire',
        damageType1: 'elemental',
        name: 'standardDmgInst',
      },
    },
  },
  Caesar: {
    anomalyDmgInst: {
      sheet: 'Caesar',
      name: 'anomalyDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'anomalyDmg',
        sheet: 'Caesar',
        attribute: 'physical',
        damageType1: 'anomaly',
        name: 'anomalyDmgInst',
      },
    },
    standardDmgInst: {
      sheet: 'Caesar',
      name: 'standardDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'standardDmg',
        sheet: 'Caesar',
        attribute: 'physical',
        damageType1: 'elemental',
        name: 'standardDmgInst',
      },
    },
  },
  Corin: {
    anomalyDmgInst: {
      sheet: 'Corin',
      name: 'anomalyDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'anomalyDmg',
        sheet: 'Corin',
        attribute: 'physical',
        damageType1: 'anomaly',
        name: 'anomalyDmgInst',
      },
    },
    standardDmgInst: {
      sheet: 'Corin',
      name: 'standardDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'standardDmg',
        sheet: 'Corin',
        attribute: 'physical',
        damageType1: 'elemental',
        name: 'standardDmgInst',
      },
    },
  },
  Ellen: {
    anomalyDmgInst: {
      sheet: 'Ellen',
      name: 'anomalyDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'anomalyDmg',
        sheet: 'Ellen',
        attribute: 'ice',
        damageType1: 'anomaly',
        name: 'anomalyDmgInst',
      },
    },
    standardDmgInst: {
      sheet: 'Ellen',
      name: 'standardDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'standardDmg',
        sheet: 'Ellen',
        attribute: 'ice',
        damageType1: 'elemental',
        name: 'standardDmgInst',
      },
    },
  },
  Evelyn: {
    anomalyDmgInst: {
      sheet: 'Evelyn',
      name: 'anomalyDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'anomalyDmg',
        sheet: 'Evelyn',
        attribute: 'fire',
        damageType1: 'anomaly',
        name: 'anomalyDmgInst',
      },
    },
    standardDmgInst: {
      sheet: 'Evelyn',
      name: 'standardDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'standardDmg',
        sheet: 'Evelyn',
        attribute: 'fire',
        damageType1: 'elemental',
        name: 'standardDmgInst',
      },
    },
  },
  Grace: {
    anomalyDmgInst: {
      sheet: 'Grace',
      name: 'anomalyDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'anomalyDmg',
        sheet: 'Grace',
        attribute: 'electric',
        damageType1: 'anomaly',
        name: 'anomalyDmgInst',
      },
    },
    standardDmgInst: {
      sheet: 'Grace',
      name: 'standardDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'standardDmg',
        sheet: 'Grace',
        attribute: 'electric',
        damageType1: 'elemental',
        name: 'standardDmgInst',
      },
    },
  },
  Harumasa: {
    anomalyDmgInst: {
      sheet: 'Harumasa',
      name: 'anomalyDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'anomalyDmg',
        sheet: 'Harumasa',
        attribute: 'electric',
        damageType1: 'anomaly',
        name: 'anomalyDmgInst',
      },
    },
    standardDmgInst: {
      sheet: 'Harumasa',
      name: 'standardDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'standardDmg',
        sheet: 'Harumasa',
        attribute: 'electric',
        damageType1: 'elemental',
        name: 'standardDmgInst',
      },
    },
  },
  Jane: {
    anomalyDmgInst: {
      sheet: 'Jane',
      name: 'anomalyDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'anomalyDmg',
        sheet: 'Jane',
        attribute: 'physical',
        damageType1: 'anomaly',
        name: 'anomalyDmgInst',
      },
    },
    standardDmgInst: {
      sheet: 'Jane',
      name: 'standardDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'standardDmg',
        sheet: 'Jane',
        attribute: 'physical',
        damageType1: 'elemental',
        name: 'standardDmgInst',
      },
    },
  },
  Koleda: {
    anomalyDmgInst: {
      sheet: 'Koleda',
      name: 'anomalyDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'anomalyDmg',
        sheet: 'Koleda',
        attribute: 'fire',
        damageType1: 'anomaly',
        name: 'anomalyDmgInst',
      },
    },
    standardDmgInst: {
      sheet: 'Koleda',
      name: 'standardDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'standardDmg',
        sheet: 'Koleda',
        attribute: 'fire',
        damageType1: 'elemental',
        name: 'standardDmgInst',
      },
    },
  },
  Lighter: {
    anomalyDmgInst: {
      sheet: 'Lighter',
      name: 'anomalyDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'anomalyDmg',
        sheet: 'Lighter',
        attribute: 'fire',
        damageType1: 'anomaly',
        name: 'anomalyDmgInst',
      },
    },
    standardDmgInst: {
      sheet: 'Lighter',
      name: 'standardDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'standardDmg',
        sheet: 'Lighter',
        attribute: 'fire',
        damageType1: 'elemental',
        name: 'standardDmgInst',
      },
    },
  },
  Lucy: {
    anomalyDmgInst: {
      sheet: 'Lucy',
      name: 'anomalyDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'anomalyDmg',
        sheet: 'Lucy',
        attribute: 'fire',
        damageType1: 'anomaly',
        name: 'anomalyDmgInst',
      },
    },
    standardDmgInst: {
      sheet: 'Lucy',
      name: 'standardDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'standardDmg',
        sheet: 'Lucy',
        attribute: 'fire',
        damageType1: 'elemental',
        name: 'standardDmgInst',
      },
    },
  },
  Lycaon: {
    anomalyDmgInst: {
      sheet: 'Lycaon',
      name: 'anomalyDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'anomalyDmg',
        sheet: 'Lycaon',
        attribute: 'ice',
        damageType1: 'anomaly',
        name: 'anomalyDmgInst',
      },
    },
    standardDmgInst: {
      sheet: 'Lycaon',
      name: 'standardDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'standardDmg',
        sheet: 'Lycaon',
        attribute: 'ice',
        damageType1: 'elemental',
        name: 'standardDmgInst',
      },
    },
  },
  Miyabi: {
    anomalyDmgInst: {
      sheet: 'Miyabi',
      name: 'anomalyDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'anomalyDmg',
        sheet: 'Miyabi',
        attribute: 'ice',
        damageType1: 'anomaly',
        name: 'anomalyDmgInst',
      },
    },
    standardDmgInst: {
      sheet: 'Miyabi',
      name: 'standardDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'standardDmg',
        sheet: 'Miyabi',
        attribute: 'ice',
        damageType1: 'elemental',
        name: 'standardDmgInst',
      },
    },
  },
  Nekomata: {
    anomalyDmgInst: {
      sheet: 'Nekomata',
      name: 'anomalyDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'anomalyDmg',
        sheet: 'Nekomata',
        attribute: 'physical',
        damageType1: 'anomaly',
        name: 'anomalyDmgInst',
      },
    },
    standardDmgInst: {
      sheet: 'Nekomata',
      name: 'standardDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'standardDmg',
        sheet: 'Nekomata',
        attribute: 'physical',
        damageType1: 'elemental',
        name: 'standardDmgInst',
      },
    },
  },
  Nicole: {
    anomalyDmgInst: {
      sheet: 'Nicole',
      name: 'anomalyDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'anomalyDmg',
        sheet: 'Nicole',
        attribute: 'ether',
        damageType1: 'anomaly',
        name: 'anomalyDmgInst',
      },
    },
    standardDmgInst: {
      sheet: 'Nicole',
      name: 'standardDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'standardDmg',
        sheet: 'Nicole',
        attribute: 'ether',
        damageType1: 'elemental',
        name: 'standardDmgInst',
      },
    },
  },
  Piper: {
    anomalyDmgInst: {
      sheet: 'Piper',
      name: 'anomalyDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'anomalyDmg',
        sheet: 'Piper',
        attribute: 'physical',
        damageType1: 'anomaly',
        name: 'anomalyDmgInst',
      },
    },
    standardDmgInst: {
      sheet: 'Piper',
      name: 'standardDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'standardDmg',
        sheet: 'Piper',
        attribute: 'physical',
        damageType1: 'elemental',
        name: 'standardDmgInst',
      },
    },
  },
  PulchraFeliny: {
    anomalyDmgInst: {
      sheet: 'PulchraFeliny',
      name: 'anomalyDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'anomalyDmg',
        sheet: 'PulchraFeliny',
        attribute: 'physical',
        damageType1: 'anomaly',
        name: 'anomalyDmgInst',
      },
    },
    standardDmgInst: {
      sheet: 'PulchraFeliny',
      name: 'standardDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'standardDmg',
        sheet: 'PulchraFeliny',
        attribute: 'physical',
        damageType1: 'elemental',
        name: 'standardDmgInst',
      },
    },
  },
  QingYi: {
    anomalyDmgInst: {
      sheet: 'QingYi',
      name: 'anomalyDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'anomalyDmg',
        sheet: 'QingYi',
        attribute: 'electric',
        damageType1: 'anomaly',
        name: 'anomalyDmgInst',
      },
    },
    standardDmgInst: {
      sheet: 'QingYi',
      name: 'standardDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'standardDmg',
        sheet: 'QingYi',
        attribute: 'electric',
        damageType1: 'elemental',
        name: 'standardDmgInst',
      },
    },
  },
  Rina: {
    anomalyDmgInst: {
      sheet: 'Rina',
      name: 'anomalyDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'anomalyDmg',
        sheet: 'Rina',
        attribute: 'electric',
        damageType1: 'anomaly',
        name: 'anomalyDmgInst',
      },
    },
    standardDmgInst: {
      sheet: 'Rina',
      name: 'standardDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'standardDmg',
        sheet: 'Rina',
        attribute: 'electric',
        damageType1: 'elemental',
        name: 'standardDmgInst',
      },
    },
  },
  Seth: {
    anomalyDmgInst: {
      sheet: 'Seth',
      name: 'anomalyDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'anomalyDmg',
        sheet: 'Seth',
        attribute: 'electric',
        damageType1: 'anomaly',
        name: 'anomalyDmgInst',
      },
    },
    standardDmgInst: {
      sheet: 'Seth',
      name: 'standardDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'standardDmg',
        sheet: 'Seth',
        attribute: 'electric',
        damageType1: 'elemental',
        name: 'standardDmgInst',
      },
    },
  },
  SilverAnby: {
    anomalyDmgInst: {
      sheet: 'SilverAnby',
      name: 'anomalyDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'anomalyDmg',
        sheet: 'SilverAnby',
        attribute: 'electric',
        damageType1: 'anomaly',
        name: 'anomalyDmgInst',
      },
    },
    standardDmgInst: {
      sheet: 'SilverAnby',
      name: 'standardDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'standardDmg',
        sheet: 'SilverAnby',
        attribute: 'electric',
        damageType1: 'elemental',
        name: 'standardDmgInst',
      },
    },
  },
  Soldier11: {
    anomalyDmgInst: {
      sheet: 'Soldier11',
      name: 'anomalyDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'anomalyDmg',
        sheet: 'Soldier11',
        attribute: 'fire',
        damageType1: 'anomaly',
        name: 'anomalyDmgInst',
      },
    },
    standardDmgInst: {
      sheet: 'Soldier11',
      name: 'standardDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'standardDmg',
        sheet: 'Soldier11',
        attribute: 'fire',
        damageType1: 'elemental',
        name: 'standardDmgInst',
      },
    },
  },
  Soukaku: {
    anomalyDmgInst: {
      sheet: 'Soukaku',
      name: 'anomalyDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'anomalyDmg',
        sheet: 'Soukaku',
        attribute: 'ice',
        damageType1: 'anomaly',
        name: 'anomalyDmgInst',
      },
    },
    standardDmgInst: {
      sheet: 'Soukaku',
      name: 'standardDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'standardDmg',
        sheet: 'Soukaku',
        attribute: 'ice',
        damageType1: 'elemental',
        name: 'standardDmgInst',
      },
    },
  },
  Trigger: {
    anomalyDmgInst: {
      sheet: 'Trigger',
      name: 'anomalyDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'anomalyDmg',
        sheet: 'Trigger',
        attribute: 'electric',
        damageType1: 'anomaly',
        name: 'anomalyDmgInst',
      },
    },
    standardDmgInst: {
      sheet: 'Trigger',
      name: 'standardDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'standardDmg',
        sheet: 'Trigger',
        attribute: 'electric',
        damageType1: 'elemental',
        name: 'standardDmgInst',
      },
    },
  },
  Yanagi: {
    anomalyDmgInst: {
      sheet: 'Yanagi',
      name: 'anomalyDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'anomalyDmg',
        sheet: 'Yanagi',
        attribute: 'electric',
        damageType1: 'anomaly',
        name: 'anomalyDmgInst',
      },
    },
    standardDmgInst: {
      sheet: 'Yanagi',
      name: 'standardDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'standardDmg',
        sheet: 'Yanagi',
        attribute: 'electric',
        damageType1: 'elemental',
        name: 'standardDmgInst',
      },
    },
  },
  ZhuYuan: {
    anomalyDmgInst: {
      sheet: 'ZhuYuan',
      name: 'anomalyDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'anomalyDmg',
        sheet: 'ZhuYuan',
        attribute: 'ether',
        damageType1: 'anomaly',
        name: 'anomalyDmgInst',
      },
    },
    standardDmgInst: {
      sheet: 'ZhuYuan',
      name: 'standardDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'standardDmg',
        sheet: 'ZhuYuan',
        attribute: 'ether',
        damageType1: 'elemental',
        name: 'standardDmgInst',
      },
    },
  },
} as const
export const buffs = {} as const
