// WARNING: Generated file, do not modify
export const conditionals = {
  AstralVoice: {
    astral: {
      sheet: 'AstralVoice',
      name: 'astral',
      type: 'num',
      int_only: true,
      min: 1,
      max: 3,
    },
  },
  BashfulDemon: {
    launch_ex_attack: {
      sheet: 'BashfulDemon',
      name: 'launch_ex_attack',
      type: 'num',
      int_only: true,
      min: 0,
      max: 4,
    },
  },
  BigCylinder: {
    boolConditional: {
      sheet: 'BigCylinder',
      name: 'boolConditional',
      type: 'bool',
    },
    listConditional: {
      sheet: 'BigCylinder',
      name: 'listConditional',
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      sheet: 'BigCylinder',
      name: 'numConditional',
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  BlazingLaurel: {
    boolConditional: {
      sheet: 'BlazingLaurel',
      name: 'boolConditional',
      type: 'bool',
    },
    listConditional: {
      sheet: 'BlazingLaurel',
      name: 'listConditional',
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      sheet: 'BlazingLaurel',
      name: 'numConditional',
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  BranchBladeSong: {
    apply_or_trigger: {
      sheet: 'BranchBladeSong',
      name: 'apply_or_trigger',
      type: 'bool',
    },
  },
  BunnyBand: {
    boolConditional: {
      sheet: 'BunnyBand',
      name: 'boolConditional',
      type: 'bool',
    },
    listConditional: {
      sheet: 'BunnyBand',
      name: 'listConditional',
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      sheet: 'BunnyBand',
      name: 'numConditional',
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  CannonRotor: {
    boolConditional: {
      sheet: 'CannonRotor',
      name: 'boolConditional',
      type: 'bool',
    },
    listConditional: {
      sheet: 'CannonRotor',
      name: 'listConditional',
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      sheet: 'CannonRotor',
      name: 'numConditional',
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  ChaosJazz: {
    while_off_field: {
      sheet: 'ChaosJazz',
      name: 'while_off_field',
      type: 'bool',
    },
  },
  ChaoticMetal: {
    trigger_corruption: {
      sheet: 'ChaoticMetal',
      name: 'trigger_corruption',
      type: 'bool',
    },
  },
  DeepSeaVisitor: {
    boolConditional: {
      sheet: 'DeepSeaVisitor',
      name: 'boolConditional',
      type: 'bool',
    },
    listConditional: {
      sheet: 'DeepSeaVisitor',
      name: 'listConditional',
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      sheet: 'DeepSeaVisitor',
      name: 'numConditional',
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  DemaraBatteryMarkII: {
    boolConditional: {
      sheet: 'DemaraBatteryMarkII',
      name: 'boolConditional',
      type: 'bool',
    },
    listConditional: {
      sheet: 'DemaraBatteryMarkII',
      name: 'listConditional',
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      sheet: 'DemaraBatteryMarkII',
      name: 'numConditional',
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  DrillRigRedAxis: {
    boolConditional: {
      sheet: 'DrillRigRedAxis',
      name: 'boolConditional',
      type: 'bool',
    },
    listConditional: {
      sheet: 'DrillRigRedAxis',
      name: 'listConditional',
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      sheet: 'DrillRigRedAxis',
      name: 'numConditional',
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  ElectroLipGloss: {
    boolConditional: {
      sheet: 'ElectroLipGloss',
      name: 'boolConditional',
      type: 'bool',
    },
    listConditional: {
      sheet: 'ElectroLipGloss',
      name: 'listConditional',
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      sheet: 'ElectroLipGloss',
      name: 'numConditional',
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  ElegantVanity: {
    boolConditional: {
      sheet: 'ElegantVanity',
      name: 'boolConditional',
      type: 'bool',
    },
    listConditional: {
      sheet: 'ElegantVanity',
      name: 'listConditional',
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      sheet: 'ElegantVanity',
      name: 'numConditional',
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  FangedMetal: {
    inflict_assault: {
      sheet: 'FangedMetal',
      name: 'inflict_assault',
      type: 'bool',
    },
  },
  FlamemakerShaker: {
    boolConditional: {
      sheet: 'FlamemakerShaker',
      name: 'boolConditional',
      type: 'bool',
    },
    listConditional: {
      sheet: 'FlamemakerShaker',
      name: 'listConditional',
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      sheet: 'FlamemakerShaker',
      name: 'numConditional',
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  FusionCompiler: {
    boolConditional: {
      sheet: 'FusionCompiler',
      name: 'boolConditional',
      type: 'bool',
    },
    listConditional: {
      sheet: 'FusionCompiler',
      name: 'listConditional',
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      sheet: 'FusionCompiler',
      name: 'numConditional',
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  GildedBlossom: {
    boolConditional: {
      sheet: 'GildedBlossom',
      name: 'boolConditional',
      type: 'bool',
    },
    listConditional: {
      sheet: 'GildedBlossom',
      name: 'listConditional',
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      sheet: 'GildedBlossom',
      name: 'numConditional',
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  HailstormShrine: {
    boolConditional: {
      sheet: 'HailstormShrine',
      name: 'boolConditional',
      type: 'bool',
    },
    listConditional: {
      sheet: 'HailstormShrine',
      name: 'listConditional',
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      sheet: 'HailstormShrine',
      name: 'numConditional',
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  HeartstringNocturne: {
    boolConditional: {
      sheet: 'HeartstringNocturne',
      name: 'boolConditional',
      type: 'bool',
    },
    listConditional: {
      sheet: 'HeartstringNocturne',
      name: 'listConditional',
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      sheet: 'HeartstringNocturne',
      name: 'numConditional',
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  HellfireGears: {
    boolConditional: {
      sheet: 'HellfireGears',
      name: 'boolConditional',
      type: 'bool',
    },
    listConditional: {
      sheet: 'HellfireGears',
      name: 'listConditional',
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      sheet: 'HellfireGears',
      name: 'numConditional',
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  HormonePunk: {
    entering_combat: {
      sheet: 'HormonePunk',
      name: 'entering_combat',
      type: 'bool',
    },
  },
  Housekeeper: {
    boolConditional: {
      sheet: 'Housekeeper',
      name: 'boolConditional',
      type: 'bool',
    },
    listConditional: {
      sheet: 'Housekeeper',
      name: 'listConditional',
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      sheet: 'Housekeeper',
      name: 'numConditional',
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  IceJadeTeapot: {
    boolConditional: {
      sheet: 'IceJadeTeapot',
      name: 'boolConditional',
      type: 'bool',
    },
    listConditional: {
      sheet: 'IceJadeTeapot',
      name: 'listConditional',
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      sheet: 'IceJadeTeapot',
      name: 'numConditional',
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  IdentityBase: {
    boolConditional: {
      sheet: 'IdentityBase',
      name: 'boolConditional',
      type: 'bool',
    },
    listConditional: {
      sheet: 'IdentityBase',
      name: 'listConditional',
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      sheet: 'IdentityBase',
      name: 'numConditional',
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  IdentityInflection: {
    boolConditional: {
      sheet: 'IdentityInflection',
      name: 'boolConditional',
      type: 'bool',
    },
    listConditional: {
      sheet: 'IdentityInflection',
      name: 'listConditional',
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      sheet: 'IdentityInflection',
      name: 'numConditional',
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  InfernoMetal: {
    hitting_burning_enemy: {
      sheet: 'InfernoMetal',
      name: 'hitting_burning_enemy',
      type: 'bool',
    },
  },
  KaboomTheCannon: {
    boolConditional: {
      sheet: 'KaboomTheCannon',
      name: 'boolConditional',
      type: 'bool',
    },
    listConditional: {
      sheet: 'KaboomTheCannon',
      name: 'listConditional',
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      sheet: 'KaboomTheCannon',
      name: 'numConditional',
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  LunarDecrescent: {
    boolConditional: {
      sheet: 'LunarDecrescent',
      name: 'boolConditional',
      type: 'bool',
    },
    listConditional: {
      sheet: 'LunarDecrescent',
      name: 'listConditional',
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      sheet: 'LunarDecrescent',
      name: 'numConditional',
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  LunarNoviluna: {
    boolConditional: {
      sheet: 'LunarNoviluna',
      name: 'boolConditional',
      type: 'bool',
    },
    listConditional: {
      sheet: 'LunarNoviluna',
      name: 'listConditional',
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      sheet: 'LunarNoviluna',
      name: 'numConditional',
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  LunarPleniluna: {
    boolConditional: {
      sheet: 'LunarPleniluna',
      name: 'boolConditional',
      type: 'bool',
    },
    listConditional: {
      sheet: 'LunarPleniluna',
      name: 'listConditional',
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      sheet: 'LunarPleniluna',
      name: 'numConditional',
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  MagneticStormAlpha: {
    boolConditional: {
      sheet: 'MagneticStormAlpha',
      name: 'boolConditional',
      type: 'bool',
    },
    listConditional: {
      sheet: 'MagneticStormAlpha',
      name: 'listConditional',
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      sheet: 'MagneticStormAlpha',
      name: 'numConditional',
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  MagneticStormBravo: {
    boolConditional: {
      sheet: 'MagneticStormBravo',
      name: 'boolConditional',
      type: 'bool',
    },
    listConditional: {
      sheet: 'MagneticStormBravo',
      name: 'listConditional',
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      sheet: 'MagneticStormBravo',
      name: 'numConditional',
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  MagneticStormCharlie: {
    boolConditional: {
      sheet: 'MagneticStormCharlie',
      name: 'boolConditional',
      type: 'bool',
    },
    listConditional: {
      sheet: 'MagneticStormCharlie',
      name: 'listConditional',
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      sheet: 'MagneticStormCharlie',
      name: 'numConditional',
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  MarcatoDesire: {
    boolConditional: {
      sheet: 'MarcatoDesire',
      name: 'boolConditional',
      type: 'bool',
    },
    listConditional: {
      sheet: 'MarcatoDesire',
      name: 'listConditional',
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      sheet: 'MarcatoDesire',
      name: 'numConditional',
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  OriginalTransmorpher: {
    boolConditional: {
      sheet: 'OriginalTransmorpher',
      name: 'boolConditional',
      type: 'bool',
    },
    listConditional: {
      sheet: 'OriginalTransmorpher',
      name: 'listConditional',
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      sheet: 'OriginalTransmorpher',
      name: 'numConditional',
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  PeacekeeperSpecialized: {
    boolConditional: {
      sheet: 'PeacekeeperSpecialized',
      name: 'boolConditional',
      type: 'bool',
    },
    listConditional: {
      sheet: 'PeacekeeperSpecialized',
      name: 'listConditional',
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      sheet: 'PeacekeeperSpecialized',
      name: 'numConditional',
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  PolarMetal: {
    freeze_shatter: {
      sheet: 'PolarMetal',
      name: 'freeze_shatter',
      type: 'bool',
    },
  },
  PreciousFossilizedCore: {
    boolConditional: {
      sheet: 'PreciousFossilizedCore',
      name: 'boolConditional',
      type: 'bool',
    },
    listConditional: {
      sheet: 'PreciousFossilizedCore',
      name: 'listConditional',
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      sheet: 'PreciousFossilizedCore',
      name: 'numConditional',
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  ProtoPunk: {
    def_assist_or_evasive_assist: {
      sheet: 'ProtoPunk',
      name: 'def_assist_or_evasive_assist',
      type: 'bool',
    },
  },
  PufferElectro: {
    launching_ult: {
      sheet: 'PufferElectro',
      name: 'launching_ult',
      type: 'bool',
    },
  },
  RainforestGourmet: {
    boolConditional: {
      sheet: 'RainforestGourmet',
      name: 'boolConditional',
      type: 'bool',
    },
    listConditional: {
      sheet: 'RainforestGourmet',
      name: 'listConditional',
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      sheet: 'RainforestGourmet',
      name: 'numConditional',
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  ReverbMarkI: {
    boolConditional: {
      sheet: 'ReverbMarkI',
      name: 'boolConditional',
      type: 'bool',
    },
    listConditional: {
      sheet: 'ReverbMarkI',
      name: 'listConditional',
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      sheet: 'ReverbMarkI',
      name: 'numConditional',
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  ReverbMarkII: {
    boolConditional: {
      sheet: 'ReverbMarkII',
      name: 'boolConditional',
      type: 'bool',
    },
    listConditional: {
      sheet: 'ReverbMarkII',
      name: 'listConditional',
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      sheet: 'ReverbMarkII',
      name: 'numConditional',
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  ReverbMarkIII: {
    boolConditional: {
      sheet: 'ReverbMarkIII',
      name: 'boolConditional',
      type: 'bool',
    },
    listConditional: {
      sheet: 'ReverbMarkIII',
      name: 'listConditional',
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      sheet: 'ReverbMarkIII',
      name: 'numConditional',
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  RiotSuppressorMarkVI: {
    boolConditional: {
      sheet: 'RiotSuppressorMarkVI',
      name: 'boolConditional',
      type: 'bool',
    },
    listConditional: {
      sheet: 'RiotSuppressorMarkVI',
      name: 'listConditional',
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      sheet: 'RiotSuppressorMarkVI',
      name: 'numConditional',
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  RoaringRide: {
    boolConditional: {
      sheet: 'RoaringRide',
      name: 'boolConditional',
      type: 'bool',
    },
    listConditional: {
      sheet: 'RoaringRide',
      name: 'listConditional',
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      sheet: 'RoaringRide',
      name: 'numConditional',
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  SharpenedStinger: {
    boolConditional: {
      sheet: 'SharpenedStinger',
      name: 'boolConditional',
      type: 'bool',
    },
    listConditional: {
      sheet: 'SharpenedStinger',
      name: 'listConditional',
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      sheet: 'SharpenedStinger',
      name: 'numConditional',
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  SixShooter: {
    boolConditional: {
      sheet: 'SixShooter',
      name: 'boolConditional',
      type: 'bool',
    },
    listConditional: {
      sheet: 'SixShooter',
      name: 'listConditional',
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      sheet: 'SixShooter',
      name: 'numConditional',
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  SliceOfTime: {
    boolConditional: {
      sheet: 'SliceOfTime',
      name: 'boolConditional',
      type: 'bool',
    },
    listConditional: {
      sheet: 'SliceOfTime',
      name: 'listConditional',
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      sheet: 'SliceOfTime',
      name: 'numConditional',
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  SpringEmbrace: {
    boolConditional: {
      sheet: 'SpringEmbrace',
      name: 'boolConditional',
      type: 'bool',
    },
    listConditional: {
      sheet: 'SpringEmbrace',
      name: 'listConditional',
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      sheet: 'SpringEmbrace',
      name: 'numConditional',
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  StarlightEngine: {
    boolConditional: {
      sheet: 'StarlightEngine',
      name: 'boolConditional',
      type: 'bool',
    },
    listConditional: {
      sheet: 'StarlightEngine',
      name: 'listConditional',
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      sheet: 'StarlightEngine',
      name: 'numConditional',
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  StarlightEngineReplica: {
    boolConditional: {
      sheet: 'StarlightEngineReplica',
      name: 'boolConditional',
      type: 'bool',
    },
    listConditional: {
      sheet: 'StarlightEngineReplica',
      name: 'listConditional',
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      sheet: 'StarlightEngineReplica',
      name: 'numConditional',
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  SteamOven: {
    boolConditional: {
      sheet: 'SteamOven',
      name: 'boolConditional',
      type: 'bool',
    },
    listConditional: {
      sheet: 'SteamOven',
      name: 'listConditional',
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      sheet: 'SteamOven',
      name: 'numConditional',
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  SteelCushion: {
    boolConditional: {
      sheet: 'SteelCushion',
      name: 'boolConditional',
      type: 'bool',
    },
    listConditional: {
      sheet: 'SteelCushion',
      name: 'listConditional',
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      sheet: 'SteelCushion',
      name: 'numConditional',
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  StreetSuperstar: {
    boolConditional: {
      sheet: 'StreetSuperstar',
      name: 'boolConditional',
      type: 'bool',
    },
    listConditional: {
      sheet: 'StreetSuperstar',
      name: 'listConditional',
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      sheet: 'StreetSuperstar',
      name: 'numConditional',
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  SwingJazz: {
    chain_or_ult: { sheet: 'SwingJazz', name: 'chain_or_ult', type: 'bool' },
  },
  TheBrimstone: {
    boolConditional: {
      sheet: 'TheBrimstone',
      name: 'boolConditional',
      type: 'bool',
    },
    listConditional: {
      sheet: 'TheBrimstone',
      name: 'listConditional',
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      sheet: 'TheBrimstone',
      name: 'numConditional',
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  TheRestrained: {
    boolConditional: {
      sheet: 'TheRestrained',
      name: 'boolConditional',
      type: 'bool',
    },
    listConditional: {
      sheet: 'TheRestrained',
      name: 'listConditional',
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      sheet: 'TheRestrained',
      name: 'numConditional',
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  TheVault: {
    boolConditional: {
      sheet: 'TheVault',
      name: 'boolConditional',
      type: 'bool',
    },
    listConditional: {
      sheet: 'TheVault',
      name: 'listConditional',
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      sheet: 'TheVault',
      name: 'numConditional',
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  ThunderMetal: {
    enemy_shocked: {
      sheet: 'ThunderMetal',
      name: 'enemy_shocked',
      type: 'bool',
    },
  },
  Timeweaver: {
    boolConditional: {
      sheet: 'Timeweaver',
      name: 'boolConditional',
      type: 'bool',
    },
    listConditional: {
      sheet: 'Timeweaver',
      name: 'listConditional',
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      sheet: 'Timeweaver',
      name: 'numConditional',
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  TusksOfFury: {
    boolConditional: {
      sheet: 'TusksOfFury',
      name: 'boolConditional',
      type: 'bool',
    },
    listConditional: {
      sheet: 'TusksOfFury',
      name: 'listConditional',
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      sheet: 'TusksOfFury',
      name: 'numConditional',
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  UnfetteredGameBall: {
    boolConditional: {
      sheet: 'UnfetteredGameBall',
      name: 'boolConditional',
      type: 'bool',
    },
    listConditional: {
      sheet: 'UnfetteredGameBall',
      name: 'listConditional',
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      sheet: 'UnfetteredGameBall',
      name: 'numConditional',
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  VortexArrow: {
    boolConditional: {
      sheet: 'VortexArrow',
      name: 'boolConditional',
      type: 'bool',
    },
    listConditional: {
      sheet: 'VortexArrow',
      name: 'listConditional',
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      sheet: 'VortexArrow',
      name: 'numConditional',
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  VortexHatchet: {
    boolConditional: {
      sheet: 'VortexHatchet',
      name: 'boolConditional',
      type: 'bool',
    },
    listConditional: {
      sheet: 'VortexHatchet',
      name: 'listConditional',
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      sheet: 'VortexHatchet',
      name: 'numConditional',
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  VortexRevolver: {
    boolConditional: {
      sheet: 'VortexRevolver',
      name: 'boolConditional',
      type: 'bool',
    },
    listConditional: {
      sheet: 'VortexRevolver',
      name: 'listConditional',
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      sheet: 'VortexRevolver',
      name: 'numConditional',
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  WeepingCradle: {
    boolConditional: {
      sheet: 'WeepingCradle',
      name: 'boolConditional',
      type: 'bool',
    },
    listConditional: {
      sheet: 'WeepingCradle',
      name: 'listConditional',
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      sheet: 'WeepingCradle',
      name: 'numConditional',
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  WeepingGemini: {
    boolConditional: {
      sheet: 'WeepingGemini',
      name: 'boolConditional',
      type: 'bool',
    },
    listConditional: {
      sheet: 'WeepingGemini',
      name: 'listConditional',
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      sheet: 'WeepingGemini',
      name: 'numConditional',
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
  WoodpeckerElectro: {
    crit_basic_dodge_ex: {
      sheet: 'WoodpeckerElectro',
      name: 'crit_basic_dodge_ex',
      type: 'num',
      int_only: true,
      min: 1,
      max: 3,
    },
  },
  ZanshinHerbCase: {
    boolConditional: {
      sheet: 'ZanshinHerbCase',
      name: 'boolConditional',
      type: 'bool',
    },
    listConditional: {
      sheet: 'ZanshinHerbCase',
      name: 'listConditional',
      type: 'list',
      list: ['val1', 'val2'],
    },
    numConditional: {
      sheet: 'ZanshinHerbCase',
      name: 'numConditional',
      type: 'num',
      int_only: true,
      min: 0,
      max: 2,
    },
  },
} as const
export const formulas = {
  Anby: {
    anomalyDmgInst: {
      sheet: 'Anby',
      name: 'anomalyDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'anomalyDmg',
        sheet: 'Anby',
        attribute: 'electric',
        damageType1: 'anomaly',
        name: 'anomalyDmgInst',
      },
    },
    standardDmgInst: {
      sheet: 'Anby',
      name: 'standardDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'standardDmg',
        sheet: 'Anby',
        attribute: 'electric',
        damageType1: 'elemental',
        name: 'standardDmgInst',
      },
    },
  },
  Anton: {
    anomalyDmgInst: {
      sheet: 'Anton',
      name: 'anomalyDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'anomalyDmg',
        sheet: 'Anton',
        attribute: 'electric',
        damageType1: 'anomaly',
        name: 'anomalyDmgInst',
      },
    },
    standardDmgInst: {
      sheet: 'Anton',
      name: 'standardDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'standardDmg',
        sheet: 'Anton',
        attribute: 'electric',
        damageType1: 'elemental',
        name: 'standardDmgInst',
      },
    },
  },
  Astra: {
    anomalyDmgInst: {
      sheet: 'Astra',
      name: 'anomalyDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'anomalyDmg',
        sheet: 'Astra',
        attribute: 'ether',
        damageType1: 'anomaly',
        name: 'anomalyDmgInst',
      },
    },
    standardDmgInst: {
      sheet: 'Astra',
      name: 'standardDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'standardDmg',
        sheet: 'Astra',
        attribute: 'ether',
        damageType1: 'elemental',
        name: 'standardDmgInst',
      },
    },
  },
  Ben: {
    anomalyDmgInst: {
      sheet: 'Ben',
      name: 'anomalyDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'anomalyDmg',
        sheet: 'Ben',
        attribute: 'fire',
        damageType1: 'anomaly',
        name: 'anomalyDmgInst',
      },
    },
    standardDmgInst: {
      sheet: 'Ben',
      name: 'standardDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'standardDmg',
        sheet: 'Ben',
        attribute: 'fire',
        damageType1: 'elemental',
        name: 'standardDmgInst',
      },
    },
  },
  Billy: {
    anomalyDmgInst: {
      sheet: 'Billy',
      name: 'anomalyDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'anomalyDmg',
        sheet: 'Billy',
        attribute: 'physical',
        damageType1: 'anomaly',
        name: 'anomalyDmgInst',
      },
    },
    standardDmgInst: {
      sheet: 'Billy',
      name: 'standardDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'standardDmg',
        sheet: 'Billy',
        attribute: 'physical',
        damageType1: 'elemental',
        name: 'standardDmgInst',
      },
    },
  },
  Burnice: {
    anomalyDmgInst: {
      sheet: 'Burnice',
      name: 'anomalyDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'anomalyDmg',
        sheet: 'Burnice',
        attribute: 'fire',
        damageType1: 'anomaly',
        name: 'anomalyDmgInst',
      },
    },
    standardDmgInst: {
      sheet: 'Burnice',
      name: 'standardDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'standardDmg',
        sheet: 'Burnice',
        attribute: 'fire',
        damageType1: 'elemental',
        name: 'standardDmgInst',
      },
    },
  },
  Caesar: {
    anomalyDmgInst: {
      sheet: 'Caesar',
      name: 'anomalyDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'anomalyDmg',
        sheet: 'Caesar',
        attribute: 'physical',
        damageType1: 'anomaly',
        name: 'anomalyDmgInst',
      },
    },
    standardDmgInst: {
      sheet: 'Caesar',
      name: 'standardDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'standardDmg',
        sheet: 'Caesar',
        attribute: 'physical',
        damageType1: 'elemental',
        name: 'standardDmgInst',
      },
    },
  },
  Corin: {
    anomalyDmgInst: {
      sheet: 'Corin',
      name: 'anomalyDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'anomalyDmg',
        sheet: 'Corin',
        attribute: 'physical',
        damageType1: 'anomaly',
        name: 'anomalyDmgInst',
      },
    },
    standardDmgInst: {
      sheet: 'Corin',
      name: 'standardDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'standardDmg',
        sheet: 'Corin',
        attribute: 'physical',
        damageType1: 'elemental',
        name: 'standardDmgInst',
      },
    },
  },
  Ellen: {
    anomalyDmgInst: {
      sheet: 'Ellen',
      name: 'anomalyDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'anomalyDmg',
        sheet: 'Ellen',
        attribute: 'ice',
        damageType1: 'anomaly',
        name: 'anomalyDmgInst',
      },
    },
    standardDmgInst: {
      sheet: 'Ellen',
      name: 'standardDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'standardDmg',
        sheet: 'Ellen',
        attribute: 'ice',
        damageType1: 'elemental',
        name: 'standardDmgInst',
      },
    },
  },
  Evelyn: {
    anomalyDmgInst: {
      sheet: 'Evelyn',
      name: 'anomalyDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'anomalyDmg',
        sheet: 'Evelyn',
        attribute: 'fire',
        damageType1: 'anomaly',
        name: 'anomalyDmgInst',
      },
    },
    standardDmgInst: {
      sheet: 'Evelyn',
      name: 'standardDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'standardDmg',
        sheet: 'Evelyn',
        attribute: 'fire',
        damageType1: 'elemental',
        name: 'standardDmgInst',
      },
    },
  },
  Grace: {
    anomalyDmgInst: {
      sheet: 'Grace',
      name: 'anomalyDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'anomalyDmg',
        sheet: 'Grace',
        attribute: 'electric',
        damageType1: 'anomaly',
        name: 'anomalyDmgInst',
      },
    },
    standardDmgInst: {
      sheet: 'Grace',
      name: 'standardDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'standardDmg',
        sheet: 'Grace',
        attribute: 'electric',
        damageType1: 'elemental',
        name: 'standardDmgInst',
      },
    },
  },
  Harumasa: {
    anomalyDmgInst: {
      sheet: 'Harumasa',
      name: 'anomalyDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'anomalyDmg',
        sheet: 'Harumasa',
        attribute: 'electric',
        damageType1: 'anomaly',
        name: 'anomalyDmgInst',
      },
    },
    standardDmgInst: {
      sheet: 'Harumasa',
      name: 'standardDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'standardDmg',
        sheet: 'Harumasa',
        attribute: 'electric',
        damageType1: 'elemental',
        name: 'standardDmgInst',
      },
    },
  },
  Jane: {
    anomalyDmgInst: {
      sheet: 'Jane',
      name: 'anomalyDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'anomalyDmg',
        sheet: 'Jane',
        attribute: 'physical',
        damageType1: 'anomaly',
        name: 'anomalyDmgInst',
      },
    },
    standardDmgInst: {
      sheet: 'Jane',
      name: 'standardDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'standardDmg',
        sheet: 'Jane',
        attribute: 'physical',
        damageType1: 'elemental',
        name: 'standardDmgInst',
      },
    },
  },
  Koleda: {
    anomalyDmgInst: {
      sheet: 'Koleda',
      name: 'anomalyDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'anomalyDmg',
        sheet: 'Koleda',
        attribute: 'fire',
        damageType1: 'anomaly',
        name: 'anomalyDmgInst',
      },
    },
    standardDmgInst: {
      sheet: 'Koleda',
      name: 'standardDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'standardDmg',
        sheet: 'Koleda',
        attribute: 'fire',
        damageType1: 'elemental',
        name: 'standardDmgInst',
      },
    },
  },
  Lighter: {
    anomalyDmgInst: {
      sheet: 'Lighter',
      name: 'anomalyDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'anomalyDmg',
        sheet: 'Lighter',
        attribute: 'fire',
        damageType1: 'anomaly',
        name: 'anomalyDmgInst',
      },
    },
    standardDmgInst: {
      sheet: 'Lighter',
      name: 'standardDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'standardDmg',
        sheet: 'Lighter',
        attribute: 'fire',
        damageType1: 'elemental',
        name: 'standardDmgInst',
      },
    },
  },
  Lucy: {
    anomalyDmgInst: {
      sheet: 'Lucy',
      name: 'anomalyDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'anomalyDmg',
        sheet: 'Lucy',
        attribute: 'fire',
        damageType1: 'anomaly',
        name: 'anomalyDmgInst',
      },
    },
    standardDmgInst: {
      sheet: 'Lucy',
      name: 'standardDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'standardDmg',
        sheet: 'Lucy',
        attribute: 'fire',
        damageType1: 'elemental',
        name: 'standardDmgInst',
      },
    },
  },
  Lycaon: {
    anomalyDmgInst: {
      sheet: 'Lycaon',
      name: 'anomalyDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'anomalyDmg',
        sheet: 'Lycaon',
        attribute: 'ice',
        damageType1: 'anomaly',
        name: 'anomalyDmgInst',
      },
    },
    standardDmgInst: {
      sheet: 'Lycaon',
      name: 'standardDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'standardDmg',
        sheet: 'Lycaon',
        attribute: 'ice',
        damageType1: 'elemental',
        name: 'standardDmgInst',
      },
    },
  },
  Miyabi: {
    anomalyDmgInst: {
      sheet: 'Miyabi',
      name: 'anomalyDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'anomalyDmg',
        sheet: 'Miyabi',
        attribute: 'ice',
        damageType1: 'anomaly',
        name: 'anomalyDmgInst',
      },
    },
    standardDmgInst: {
      sheet: 'Miyabi',
      name: 'standardDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'standardDmg',
        sheet: 'Miyabi',
        attribute: 'ice',
        damageType1: 'elemental',
        name: 'standardDmgInst',
      },
    },
  },
  Nekomata: {
    anomalyDmgInst: {
      sheet: 'Nekomata',
      name: 'anomalyDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'anomalyDmg',
        sheet: 'Nekomata',
        attribute: 'physical',
        damageType1: 'anomaly',
        name: 'anomalyDmgInst',
      },
    },
    standardDmgInst: {
      sheet: 'Nekomata',
      name: 'standardDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'standardDmg',
        sheet: 'Nekomata',
        attribute: 'physical',
        damageType1: 'elemental',
        name: 'standardDmgInst',
      },
    },
  },
  Nicole: {
    anomalyDmgInst: {
      sheet: 'Nicole',
      name: 'anomalyDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'anomalyDmg',
        sheet: 'Nicole',
        attribute: 'ether',
        damageType1: 'anomaly',
        name: 'anomalyDmgInst',
      },
    },
    standardDmgInst: {
      sheet: 'Nicole',
      name: 'standardDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'standardDmg',
        sheet: 'Nicole',
        attribute: 'ether',
        damageType1: 'elemental',
        name: 'standardDmgInst',
      },
    },
  },
  Piper: {
    anomalyDmgInst: {
      sheet: 'Piper',
      name: 'anomalyDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'anomalyDmg',
        sheet: 'Piper',
        attribute: 'physical',
        damageType1: 'anomaly',
        name: 'anomalyDmgInst',
      },
    },
    standardDmgInst: {
      sheet: 'Piper',
      name: 'standardDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'standardDmg',
        sheet: 'Piper',
        attribute: 'physical',
        damageType1: 'elemental',
        name: 'standardDmgInst',
      },
    },
  },
  QingYi: {
    anomalyDmgInst: {
      sheet: 'QingYi',
      name: 'anomalyDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'anomalyDmg',
        sheet: 'QingYi',
        attribute: 'electric',
        damageType1: 'anomaly',
        name: 'anomalyDmgInst',
      },
    },
    standardDmgInst: {
      sheet: 'QingYi',
      name: 'standardDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'standardDmg',
        sheet: 'QingYi',
        attribute: 'electric',
        damageType1: 'elemental',
        name: 'standardDmgInst',
      },
    },
  },
  Rina: {
    anomalyDmgInst: {
      sheet: 'Rina',
      name: 'anomalyDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'anomalyDmg',
        sheet: 'Rina',
        attribute: 'electric',
        damageType1: 'anomaly',
        name: 'anomalyDmgInst',
      },
    },
    standardDmgInst: {
      sheet: 'Rina',
      name: 'standardDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'standardDmg',
        sheet: 'Rina',
        attribute: 'electric',
        damageType1: 'elemental',
        name: 'standardDmgInst',
      },
    },
  },
  Seth: {
    anomalyDmgInst: {
      sheet: 'Seth',
      name: 'anomalyDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'anomalyDmg',
        sheet: 'Seth',
        attribute: 'electric',
        damageType1: 'anomaly',
        name: 'anomalyDmgInst',
      },
    },
    standardDmgInst: {
      sheet: 'Seth',
      name: 'standardDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'standardDmg',
        sheet: 'Seth',
        attribute: 'electric',
        damageType1: 'elemental',
        name: 'standardDmgInst',
      },
    },
  },
  Soldier11: {
    anomalyDmgInst: {
      sheet: 'Soldier11',
      name: 'anomalyDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'anomalyDmg',
        sheet: 'Soldier11',
        attribute: 'fire',
        damageType1: 'anomaly',
        name: 'anomalyDmgInst',
      },
    },
    standardDmgInst: {
      sheet: 'Soldier11',
      name: 'standardDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'standardDmg',
        sheet: 'Soldier11',
        attribute: 'fire',
        damageType1: 'elemental',
        name: 'standardDmgInst',
      },
    },
  },
  Soukaku: {
    anomalyDmgInst: {
      sheet: 'Soukaku',
      name: 'anomalyDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'anomalyDmg',
        sheet: 'Soukaku',
        attribute: 'ice',
        damageType1: 'anomaly',
        name: 'anomalyDmgInst',
      },
    },
    standardDmgInst: {
      sheet: 'Soukaku',
      name: 'standardDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'standardDmg',
        sheet: 'Soukaku',
        attribute: 'ice',
        damageType1: 'elemental',
        name: 'standardDmgInst',
      },
    },
  },
  Yanagi: {
    anomalyDmgInst: {
      sheet: 'Yanagi',
      name: 'anomalyDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'anomalyDmg',
        sheet: 'Yanagi',
        attribute: 'electric',
        damageType1: 'anomaly',
        name: 'anomalyDmgInst',
      },
    },
    standardDmgInst: {
      sheet: 'Yanagi',
      name: 'standardDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'standardDmg',
        sheet: 'Yanagi',
        attribute: 'electric',
        damageType1: 'elemental',
        name: 'standardDmgInst',
      },
    },
  },
  ZhuYuan: {
    anomalyDmgInst: {
      sheet: 'ZhuYuan',
      name: 'anomalyDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'anomalyDmg',
        sheet: 'ZhuYuan',
        attribute: 'ether',
        damageType1: 'anomaly',
        name: 'anomalyDmgInst',
      },
    },
    standardDmgInst: {
      sheet: 'ZhuYuan',
      name: 'standardDmgInst',
      tag: {
        et: 'own',
        qt: 'formula',
        q: 'standardDmg',
        sheet: 'ZhuYuan',
        attribute: 'ether',
        damageType1: 'elemental',
        name: 'standardDmgInst',
      },
    },
  },
} as const
export const buffs = {
  AstralVoice: {
    set4_team_dmg_: {
      sheet: 'AstralVoice',
      name: 'set4_team_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'AstralVoice',
        name: 'set4_team_dmg_',
      },
    },
  },
  BashfulDemon: {
    ice_dmg_: {
      sheet: 'BashfulDemon',
      name: 'ice_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'dmg_',
        sheet: 'BashfulDemon',
        attribute: 'ice',
        name: 'ice_dmg_',
      },
    },
    team_atk_: {
      sheet: 'BashfulDemon',
      name: 'team_atk_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'atk_',
        sheet: 'BashfulDemon',
        name: 'team_atk_',
      },
    },
  },
  BigCylinder: {
    cond_dmg_: {
      sheet: 'BigCylinder',
      name: 'cond_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'BigCylinder',
        name: 'cond_dmg_',
      },
    },
    enemy_defIgn_: {
      sheet: 'BigCylinder',
      name: 'enemy_defIgn_',
      tag: {
        et: 'display',
        qt: 'common',
        q: 'dmgRed_',
        sheet: 'BigCylinder',
        name: 'enemy_defIgn_',
      },
    },
    team_dmg_: {
      sheet: 'BigCylinder',
      name: 'team_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'BigCylinder',
        name: 'team_dmg_',
      },
    },
  },
  BlazingLaurel: {
    cond_dmg_: {
      sheet: 'BlazingLaurel',
      name: 'cond_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'BlazingLaurel',
        name: 'cond_dmg_',
      },
    },
    enemy_defIgn_: {
      sheet: 'BlazingLaurel',
      name: 'enemy_defIgn_',
      tag: {
        et: 'display',
        qt: 'common',
        q: 'dmgRed_',
        sheet: 'BlazingLaurel',
        name: 'enemy_defIgn_',
      },
    },
    team_dmg_: {
      sheet: 'BlazingLaurel',
      name: 'team_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'BlazingLaurel',
        name: 'team_dmg_',
      },
    },
  },
  BranchBladeSong: {
    set4_cond: {
      sheet: 'BranchBladeSong',
      name: 'set4_cond',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'crit_',
        sheet: 'BranchBladeSong',
        name: 'set4_cond',
      },
    },
    set4_passive: {
      sheet: 'BranchBladeSong',
      name: 'set4_passive',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'crit_dmg_',
        sheet: 'BranchBladeSong',
        name: 'set4_passive',
      },
    },
  },
  BunnyBand: {
    cond_dmg_: {
      sheet: 'BunnyBand',
      name: 'cond_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'BunnyBand',
        name: 'cond_dmg_',
      },
    },
    enemy_defIgn_: {
      sheet: 'BunnyBand',
      name: 'enemy_defIgn_',
      tag: {
        et: 'display',
        qt: 'common',
        q: 'dmgRed_',
        sheet: 'BunnyBand',
        name: 'enemy_defIgn_',
      },
    },
    team_dmg_: {
      sheet: 'BunnyBand',
      name: 'team_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'BunnyBand',
        name: 'team_dmg_',
      },
    },
  },
  CannonRotor: {
    cond_dmg_: {
      sheet: 'CannonRotor',
      name: 'cond_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'CannonRotor',
        name: 'cond_dmg_',
      },
    },
    enemy_defIgn_: {
      sheet: 'CannonRotor',
      name: 'enemy_defIgn_',
      tag: {
        et: 'display',
        qt: 'common',
        q: 'dmgRed_',
        sheet: 'CannonRotor',
        name: 'enemy_defIgn_',
      },
    },
    team_dmg_: {
      sheet: 'CannonRotor',
      name: 'team_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'CannonRotor',
        name: 'team_dmg_',
      },
    },
  },
  ChaosJazz: {
    set4_off_field_assist_dmg_: {
      sheet: 'ChaosJazz',
      name: 'set4_off_field_assist_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'dmg_',
        sheet: 'ChaosJazz',
        dst: null,
        damageType2: 'assist',
        name: 'set4_off_field_assist_dmg_',
      },
    },
    set4_off_field_special_dmg_: {
      sheet: 'ChaosJazz',
      name: 'set4_off_field_special_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'dmg_',
        sheet: 'ChaosJazz',
        dst: null,
        damageType2: 'special',
        name: 'set4_off_field_special_dmg_',
      },
    },
    set4_passive_electric_dmg_: {
      sheet: 'ChaosJazz',
      name: 'set4_passive_electric_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'dmg_',
        sheet: 'ChaosJazz',
        dst: null,
        attribute: 'electric',
        name: 'set4_passive_electric_dmg_',
      },
    },
    set4_passive_fire_dmg_: {
      sheet: 'ChaosJazz',
      name: 'set4_passive_fire_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'dmg_',
        sheet: 'ChaosJazz',
        dst: null,
        attribute: 'fire',
        name: 'set4_passive_fire_dmg_',
      },
    },
  },
  ChaoticMetal: {
    set4_cond_trigger_corruption: {
      sheet: 'ChaoticMetal',
      name: 'set4_cond_trigger_corruption',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'crit_dmg_',
        sheet: 'ChaoticMetal',
        name: 'set4_cond_trigger_corruption',
      },
    },
    set4_passive: {
      sheet: 'ChaoticMetal',
      name: 'set4_passive',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'crit_dmg_',
        sheet: 'ChaoticMetal',
        name: 'set4_passive',
      },
    },
  },
  DeepSeaVisitor: {
    cond_dmg_: {
      sheet: 'DeepSeaVisitor',
      name: 'cond_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'DeepSeaVisitor',
        name: 'cond_dmg_',
      },
    },
    enemy_defIgn_: {
      sheet: 'DeepSeaVisitor',
      name: 'enemy_defIgn_',
      tag: {
        et: 'display',
        qt: 'common',
        q: 'dmgRed_',
        sheet: 'DeepSeaVisitor',
        name: 'enemy_defIgn_',
      },
    },
    team_dmg_: {
      sheet: 'DeepSeaVisitor',
      name: 'team_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'DeepSeaVisitor',
        name: 'team_dmg_',
      },
    },
  },
  DemaraBatteryMarkII: {
    cond_dmg_: {
      sheet: 'DemaraBatteryMarkII',
      name: 'cond_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'DemaraBatteryMarkII',
        name: 'cond_dmg_',
      },
    },
    enemy_defIgn_: {
      sheet: 'DemaraBatteryMarkII',
      name: 'enemy_defIgn_',
      tag: {
        et: 'display',
        qt: 'common',
        q: 'dmgRed_',
        sheet: 'DemaraBatteryMarkII',
        name: 'enemy_defIgn_',
      },
    },
    team_dmg_: {
      sheet: 'DemaraBatteryMarkII',
      name: 'team_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'DemaraBatteryMarkII',
        name: 'team_dmg_',
      },
    },
  },
  DrillRigRedAxis: {
    cond_dmg_: {
      sheet: 'DrillRigRedAxis',
      name: 'cond_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'DrillRigRedAxis',
        name: 'cond_dmg_',
      },
    },
    enemy_defIgn_: {
      sheet: 'DrillRigRedAxis',
      name: 'enemy_defIgn_',
      tag: {
        et: 'display',
        qt: 'common',
        q: 'dmgRed_',
        sheet: 'DrillRigRedAxis',
        name: 'enemy_defIgn_',
      },
    },
    team_dmg_: {
      sheet: 'DrillRigRedAxis',
      name: 'team_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'DrillRigRedAxis',
        name: 'team_dmg_',
      },
    },
  },
  ElectroLipGloss: {
    cond_dmg_: {
      sheet: 'ElectroLipGloss',
      name: 'cond_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'ElectroLipGloss',
        name: 'cond_dmg_',
      },
    },
    enemy_defIgn_: {
      sheet: 'ElectroLipGloss',
      name: 'enemy_defIgn_',
      tag: {
        et: 'display',
        qt: 'common',
        q: 'dmgRed_',
        sheet: 'ElectroLipGloss',
        name: 'enemy_defIgn_',
      },
    },
    team_dmg_: {
      sheet: 'ElectroLipGloss',
      name: 'team_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'ElectroLipGloss',
        name: 'team_dmg_',
      },
    },
  },
  ElegantVanity: {
    cond_dmg_: {
      sheet: 'ElegantVanity',
      name: 'cond_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'ElegantVanity',
        name: 'cond_dmg_',
      },
    },
    enemy_defIgn_: {
      sheet: 'ElegantVanity',
      name: 'enemy_defIgn_',
      tag: {
        et: 'display',
        qt: 'common',
        q: 'dmgRed_',
        sheet: 'ElegantVanity',
        name: 'enemy_defIgn_',
      },
    },
    team_dmg_: {
      sheet: 'ElegantVanity',
      name: 'team_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'ElegantVanity',
        name: 'team_dmg_',
      },
    },
  },
  FangedMetal: {
    set4_cond_inflict_assault: {
      sheet: 'FangedMetal',
      name: 'set4_cond_inflict_assault',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'FangedMetal',
        name: 'set4_cond_inflict_assault',
      },
    },
  },
  FlamemakerShaker: {
    cond_dmg_: {
      sheet: 'FlamemakerShaker',
      name: 'cond_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'FlamemakerShaker',
        name: 'cond_dmg_',
      },
    },
    enemy_defIgn_: {
      sheet: 'FlamemakerShaker',
      name: 'enemy_defIgn_',
      tag: {
        et: 'display',
        qt: 'common',
        q: 'dmgRed_',
        sheet: 'FlamemakerShaker',
        name: 'enemy_defIgn_',
      },
    },
    team_dmg_: {
      sheet: 'FlamemakerShaker',
      name: 'team_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'FlamemakerShaker',
        name: 'team_dmg_',
      },
    },
  },
  FusionCompiler: {
    cond_dmg_: {
      sheet: 'FusionCompiler',
      name: 'cond_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'FusionCompiler',
        name: 'cond_dmg_',
      },
    },
    enemy_defIgn_: {
      sheet: 'FusionCompiler',
      name: 'enemy_defIgn_',
      tag: {
        et: 'display',
        qt: 'common',
        q: 'dmgRed_',
        sheet: 'FusionCompiler',
        name: 'enemy_defIgn_',
      },
    },
    team_dmg_: {
      sheet: 'FusionCompiler',
      name: 'team_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'FusionCompiler',
        name: 'team_dmg_',
      },
    },
  },
  GildedBlossom: {
    cond_dmg_: {
      sheet: 'GildedBlossom',
      name: 'cond_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'GildedBlossom',
        name: 'cond_dmg_',
      },
    },
    enemy_defIgn_: {
      sheet: 'GildedBlossom',
      name: 'enemy_defIgn_',
      tag: {
        et: 'display',
        qt: 'common',
        q: 'dmgRed_',
        sheet: 'GildedBlossom',
        name: 'enemy_defIgn_',
      },
    },
    team_dmg_: {
      sheet: 'GildedBlossom',
      name: 'team_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'GildedBlossom',
        name: 'team_dmg_',
      },
    },
  },
  HailstormShrine: {
    cond_dmg_: {
      sheet: 'HailstormShrine',
      name: 'cond_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'HailstormShrine',
        name: 'cond_dmg_',
      },
    },
    enemy_defIgn_: {
      sheet: 'HailstormShrine',
      name: 'enemy_defIgn_',
      tag: {
        et: 'display',
        qt: 'common',
        q: 'dmgRed_',
        sheet: 'HailstormShrine',
        name: 'enemy_defIgn_',
      },
    },
    team_dmg_: {
      sheet: 'HailstormShrine',
      name: 'team_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'HailstormShrine',
        name: 'team_dmg_',
      },
    },
  },
  HeartstringNocturne: {
    cond_dmg_: {
      sheet: 'HeartstringNocturne',
      name: 'cond_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'HeartstringNocturne',
        name: 'cond_dmg_',
      },
    },
    enemy_defIgn_: {
      sheet: 'HeartstringNocturne',
      name: 'enemy_defIgn_',
      tag: {
        et: 'display',
        qt: 'common',
        q: 'dmgRed_',
        sheet: 'HeartstringNocturne',
        name: 'enemy_defIgn_',
      },
    },
    team_dmg_: {
      sheet: 'HeartstringNocturne',
      name: 'team_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'HeartstringNocturne',
        name: 'team_dmg_',
      },
    },
  },
  HellfireGears: {
    cond_dmg_: {
      sheet: 'HellfireGears',
      name: 'cond_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'HellfireGears',
        name: 'cond_dmg_',
      },
    },
    enemy_defIgn_: {
      sheet: 'HellfireGears',
      name: 'enemy_defIgn_',
      tag: {
        et: 'display',
        qt: 'common',
        q: 'dmgRed_',
        sheet: 'HellfireGears',
        name: 'enemy_defIgn_',
      },
    },
    team_dmg_: {
      sheet: 'HellfireGears',
      name: 'team_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'HellfireGears',
        name: 'team_dmg_',
      },
    },
  },
  HormonePunk: {
    set4_cond_entering_combat: {
      sheet: 'HormonePunk',
      name: 'set4_cond_entering_combat',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'atk_',
        sheet: 'HormonePunk',
        name: 'set4_cond_entering_combat',
      },
    },
  },
  Housekeeper: {
    cond_dmg_: {
      sheet: 'Housekeeper',
      name: 'cond_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'Housekeeper',
        name: 'cond_dmg_',
      },
    },
    enemy_defIgn_: {
      sheet: 'Housekeeper',
      name: 'enemy_defIgn_',
      tag: {
        et: 'display',
        qt: 'common',
        q: 'dmgRed_',
        sheet: 'Housekeeper',
        name: 'enemy_defIgn_',
      },
    },
    team_dmg_: {
      sheet: 'Housekeeper',
      name: 'team_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'Housekeeper',
        name: 'team_dmg_',
      },
    },
  },
  IceJadeTeapot: {
    cond_dmg_: {
      sheet: 'IceJadeTeapot',
      name: 'cond_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'IceJadeTeapot',
        name: 'cond_dmg_',
      },
    },
    enemy_defIgn_: {
      sheet: 'IceJadeTeapot',
      name: 'enemy_defIgn_',
      tag: {
        et: 'display',
        qt: 'common',
        q: 'dmgRed_',
        sheet: 'IceJadeTeapot',
        name: 'enemy_defIgn_',
      },
    },
    team_dmg_: {
      sheet: 'IceJadeTeapot',
      name: 'team_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'IceJadeTeapot',
        name: 'team_dmg_',
      },
    },
  },
  IdentityBase: {
    cond_dmg_: {
      sheet: 'IdentityBase',
      name: 'cond_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'IdentityBase',
        name: 'cond_dmg_',
      },
    },
    enemy_defIgn_: {
      sheet: 'IdentityBase',
      name: 'enemy_defIgn_',
      tag: {
        et: 'display',
        qt: 'common',
        q: 'dmgRed_',
        sheet: 'IdentityBase',
        name: 'enemy_defIgn_',
      },
    },
    team_dmg_: {
      sheet: 'IdentityBase',
      name: 'team_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'IdentityBase',
        name: 'team_dmg_',
      },
    },
  },
  IdentityInflection: {
    cond_dmg_: {
      sheet: 'IdentityInflection',
      name: 'cond_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'IdentityInflection',
        name: 'cond_dmg_',
      },
    },
    enemy_defIgn_: {
      sheet: 'IdentityInflection',
      name: 'enemy_defIgn_',
      tag: {
        et: 'display',
        qt: 'common',
        q: 'dmgRed_',
        sheet: 'IdentityInflection',
        name: 'enemy_defIgn_',
      },
    },
    team_dmg_: {
      sheet: 'IdentityInflection',
      name: 'team_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'IdentityInflection',
        name: 'team_dmg_',
      },
    },
  },
  InfernoMetal: {
    set4_cond_hitting_burning_enemy: {
      sheet: 'InfernoMetal',
      name: 'set4_cond_hitting_burning_enemy',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'crit_',
        sheet: 'InfernoMetal',
        name: 'set4_cond_hitting_burning_enemy',
      },
    },
  },
  KaboomTheCannon: {
    cond_dmg_: {
      sheet: 'KaboomTheCannon',
      name: 'cond_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'KaboomTheCannon',
        name: 'cond_dmg_',
      },
    },
    enemy_defIgn_: {
      sheet: 'KaboomTheCannon',
      name: 'enemy_defIgn_',
      tag: {
        et: 'display',
        qt: 'common',
        q: 'dmgRed_',
        sheet: 'KaboomTheCannon',
        name: 'enemy_defIgn_',
      },
    },
    team_dmg_: {
      sheet: 'KaboomTheCannon',
      name: 'team_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'KaboomTheCannon',
        name: 'team_dmg_',
      },
    },
  },
  LunarDecrescent: {
    cond_dmg_: {
      sheet: 'LunarDecrescent',
      name: 'cond_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'LunarDecrescent',
        name: 'cond_dmg_',
      },
    },
    enemy_defIgn_: {
      sheet: 'LunarDecrescent',
      name: 'enemy_defIgn_',
      tag: {
        et: 'display',
        qt: 'common',
        q: 'dmgRed_',
        sheet: 'LunarDecrescent',
        name: 'enemy_defIgn_',
      },
    },
    team_dmg_: {
      sheet: 'LunarDecrescent',
      name: 'team_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'LunarDecrescent',
        name: 'team_dmg_',
      },
    },
  },
  LunarNoviluna: {
    cond_dmg_: {
      sheet: 'LunarNoviluna',
      name: 'cond_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'LunarNoviluna',
        name: 'cond_dmg_',
      },
    },
    enemy_defIgn_: {
      sheet: 'LunarNoviluna',
      name: 'enemy_defIgn_',
      tag: {
        et: 'display',
        qt: 'common',
        q: 'dmgRed_',
        sheet: 'LunarNoviluna',
        name: 'enemy_defIgn_',
      },
    },
    team_dmg_: {
      sheet: 'LunarNoviluna',
      name: 'team_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'LunarNoviluna',
        name: 'team_dmg_',
      },
    },
  },
  LunarPleniluna: {
    cond_dmg_: {
      sheet: 'LunarPleniluna',
      name: 'cond_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'LunarPleniluna',
        name: 'cond_dmg_',
      },
    },
    enemy_defIgn_: {
      sheet: 'LunarPleniluna',
      name: 'enemy_defIgn_',
      tag: {
        et: 'display',
        qt: 'common',
        q: 'dmgRed_',
        sheet: 'LunarPleniluna',
        name: 'enemy_defIgn_',
      },
    },
    team_dmg_: {
      sheet: 'LunarPleniluna',
      name: 'team_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'LunarPleniluna',
        name: 'team_dmg_',
      },
    },
  },
  MagneticStormAlpha: {
    cond_dmg_: {
      sheet: 'MagneticStormAlpha',
      name: 'cond_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'MagneticStormAlpha',
        name: 'cond_dmg_',
      },
    },
    enemy_defIgn_: {
      sheet: 'MagneticStormAlpha',
      name: 'enemy_defIgn_',
      tag: {
        et: 'display',
        qt: 'common',
        q: 'dmgRed_',
        sheet: 'MagneticStormAlpha',
        name: 'enemy_defIgn_',
      },
    },
    team_dmg_: {
      sheet: 'MagneticStormAlpha',
      name: 'team_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'MagneticStormAlpha',
        name: 'team_dmg_',
      },
    },
  },
  MagneticStormBravo: {
    cond_dmg_: {
      sheet: 'MagneticStormBravo',
      name: 'cond_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'MagneticStormBravo',
        name: 'cond_dmg_',
      },
    },
    enemy_defIgn_: {
      sheet: 'MagneticStormBravo',
      name: 'enemy_defIgn_',
      tag: {
        et: 'display',
        qt: 'common',
        q: 'dmgRed_',
        sheet: 'MagneticStormBravo',
        name: 'enemy_defIgn_',
      },
    },
    team_dmg_: {
      sheet: 'MagneticStormBravo',
      name: 'team_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'MagneticStormBravo',
        name: 'team_dmg_',
      },
    },
  },
  MagneticStormCharlie: {
    cond_dmg_: {
      sheet: 'MagneticStormCharlie',
      name: 'cond_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'MagneticStormCharlie',
        name: 'cond_dmg_',
      },
    },
    enemy_defIgn_: {
      sheet: 'MagneticStormCharlie',
      name: 'enemy_defIgn_',
      tag: {
        et: 'display',
        qt: 'common',
        q: 'dmgRed_',
        sheet: 'MagneticStormCharlie',
        name: 'enemy_defIgn_',
      },
    },
    team_dmg_: {
      sheet: 'MagneticStormCharlie',
      name: 'team_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'MagneticStormCharlie',
        name: 'team_dmg_',
      },
    },
  },
  MarcatoDesire: {
    cond_dmg_: {
      sheet: 'MarcatoDesire',
      name: 'cond_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'MarcatoDesire',
        name: 'cond_dmg_',
      },
    },
    enemy_defIgn_: {
      sheet: 'MarcatoDesire',
      name: 'enemy_defIgn_',
      tag: {
        et: 'display',
        qt: 'common',
        q: 'dmgRed_',
        sheet: 'MarcatoDesire',
        name: 'enemy_defIgn_',
      },
    },
    team_dmg_: {
      sheet: 'MarcatoDesire',
      name: 'team_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'MarcatoDesire',
        name: 'team_dmg_',
      },
    },
  },
  OriginalTransmorpher: {
    cond_dmg_: {
      sheet: 'OriginalTransmorpher',
      name: 'cond_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'OriginalTransmorpher',
        name: 'cond_dmg_',
      },
    },
    enemy_defIgn_: {
      sheet: 'OriginalTransmorpher',
      name: 'enemy_defIgn_',
      tag: {
        et: 'display',
        qt: 'common',
        q: 'dmgRed_',
        sheet: 'OriginalTransmorpher',
        name: 'enemy_defIgn_',
      },
    },
    team_dmg_: {
      sheet: 'OriginalTransmorpher',
      name: 'team_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'OriginalTransmorpher',
        name: 'team_dmg_',
      },
    },
  },
  PeacekeeperSpecialized: {
    cond_dmg_: {
      sheet: 'PeacekeeperSpecialized',
      name: 'cond_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'PeacekeeperSpecialized',
        name: 'cond_dmg_',
      },
    },
    enemy_defIgn_: {
      sheet: 'PeacekeeperSpecialized',
      name: 'enemy_defIgn_',
      tag: {
        et: 'display',
        qt: 'common',
        q: 'dmgRed_',
        sheet: 'PeacekeeperSpecialized',
        name: 'enemy_defIgn_',
      },
    },
    team_dmg_: {
      sheet: 'PeacekeeperSpecialized',
      name: 'team_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'PeacekeeperSpecialized',
        name: 'team_dmg_',
      },
    },
  },
  PolarMetal: {
    set4_basic_dmg_: {
      sheet: 'PolarMetal',
      name: 'set4_basic_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'dmg_',
        sheet: 'PolarMetal',
        damageType2: 'basic',
        name: 'set4_basic_dmg_',
      },
    },
    set4_dodge_dmg_: {
      sheet: 'PolarMetal',
      name: 'set4_dodge_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'dmg_',
        sheet: 'PolarMetal',
        damageType2: 'dodge',
        name: 'set4_dodge_dmg_',
      },
    },
  },
  PreciousFossilizedCore: {
    cond_dmg_: {
      sheet: 'PreciousFossilizedCore',
      name: 'cond_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'PreciousFossilizedCore',
        name: 'cond_dmg_',
      },
    },
    enemy_defIgn_: {
      sheet: 'PreciousFossilizedCore',
      name: 'enemy_defIgn_',
      tag: {
        et: 'display',
        qt: 'common',
        q: 'dmgRed_',
        sheet: 'PreciousFossilizedCore',
        name: 'enemy_defIgn_',
      },
    },
    team_dmg_: {
      sheet: 'PreciousFossilizedCore',
      name: 'team_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'PreciousFossilizedCore',
        name: 'team_dmg_',
      },
    },
  },
  ProtoPunk: {
    set4_cond_def_assist_or_evasive_assist_dmg_: {
      sheet: 'ProtoPunk',
      name: 'set4_cond_def_assist_or_evasive_assist_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'ProtoPunk',
        name: 'set4_cond_def_assist_or_evasive_assist_dmg_',
      },
    },
  },
  PufferElectro: {
    set4_cond_launching_ult_atk_: {
      sheet: 'PufferElectro',
      name: 'set4_cond_launching_ult_atk_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'atk_',
        sheet: 'PufferElectro',
        name: 'set4_cond_launching_ult_atk_',
      },
    },
    set4_dmg_: {
      sheet: 'PufferElectro',
      name: 'set4_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'dmg_',
        sheet: 'PufferElectro',
        damageType2: 'ult',
        name: 'set4_dmg_',
      },
    },
  },
  RainforestGourmet: {
    cond_dmg_: {
      sheet: 'RainforestGourmet',
      name: 'cond_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'RainforestGourmet',
        name: 'cond_dmg_',
      },
    },
    enemy_defIgn_: {
      sheet: 'RainforestGourmet',
      name: 'enemy_defIgn_',
      tag: {
        et: 'display',
        qt: 'common',
        q: 'dmgRed_',
        sheet: 'RainforestGourmet',
        name: 'enemy_defIgn_',
      },
    },
    team_dmg_: {
      sheet: 'RainforestGourmet',
      name: 'team_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'RainforestGourmet',
        name: 'team_dmg_',
      },
    },
  },
  ReverbMarkI: {
    cond_dmg_: {
      sheet: 'ReverbMarkI',
      name: 'cond_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'ReverbMarkI',
        name: 'cond_dmg_',
      },
    },
    enemy_defIgn_: {
      sheet: 'ReverbMarkI',
      name: 'enemy_defIgn_',
      tag: {
        et: 'display',
        qt: 'common',
        q: 'dmgRed_',
        sheet: 'ReverbMarkI',
        name: 'enemy_defIgn_',
      },
    },
    team_dmg_: {
      sheet: 'ReverbMarkI',
      name: 'team_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'ReverbMarkI',
        name: 'team_dmg_',
      },
    },
  },
  ReverbMarkII: {
    cond_dmg_: {
      sheet: 'ReverbMarkII',
      name: 'cond_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'ReverbMarkII',
        name: 'cond_dmg_',
      },
    },
    enemy_defIgn_: {
      sheet: 'ReverbMarkII',
      name: 'enemy_defIgn_',
      tag: {
        et: 'display',
        qt: 'common',
        q: 'dmgRed_',
        sheet: 'ReverbMarkII',
        name: 'enemy_defIgn_',
      },
    },
    team_dmg_: {
      sheet: 'ReverbMarkII',
      name: 'team_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'ReverbMarkII',
        name: 'team_dmg_',
      },
    },
  },
  ReverbMarkIII: {
    cond_dmg_: {
      sheet: 'ReverbMarkIII',
      name: 'cond_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'ReverbMarkIII',
        name: 'cond_dmg_',
      },
    },
    enemy_defIgn_: {
      sheet: 'ReverbMarkIII',
      name: 'enemy_defIgn_',
      tag: {
        et: 'display',
        qt: 'common',
        q: 'dmgRed_',
        sheet: 'ReverbMarkIII',
        name: 'enemy_defIgn_',
      },
    },
    team_dmg_: {
      sheet: 'ReverbMarkIII',
      name: 'team_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'ReverbMarkIII',
        name: 'team_dmg_',
      },
    },
  },
  RiotSuppressorMarkVI: {
    cond_dmg_: {
      sheet: 'RiotSuppressorMarkVI',
      name: 'cond_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'RiotSuppressorMarkVI',
        name: 'cond_dmg_',
      },
    },
    enemy_defIgn_: {
      sheet: 'RiotSuppressorMarkVI',
      name: 'enemy_defIgn_',
      tag: {
        et: 'display',
        qt: 'common',
        q: 'dmgRed_',
        sheet: 'RiotSuppressorMarkVI',
        name: 'enemy_defIgn_',
      },
    },
    team_dmg_: {
      sheet: 'RiotSuppressorMarkVI',
      name: 'team_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'RiotSuppressorMarkVI',
        name: 'team_dmg_',
      },
    },
  },
  RoaringRide: {
    cond_dmg_: {
      sheet: 'RoaringRide',
      name: 'cond_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'RoaringRide',
        name: 'cond_dmg_',
      },
    },
    enemy_defIgn_: {
      sheet: 'RoaringRide',
      name: 'enemy_defIgn_',
      tag: {
        et: 'display',
        qt: 'common',
        q: 'dmgRed_',
        sheet: 'RoaringRide',
        name: 'enemy_defIgn_',
      },
    },
    team_dmg_: {
      sheet: 'RoaringRide',
      name: 'team_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'RoaringRide',
        name: 'team_dmg_',
      },
    },
  },
  SharpenedStinger: {
    cond_dmg_: {
      sheet: 'SharpenedStinger',
      name: 'cond_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'SharpenedStinger',
        name: 'cond_dmg_',
      },
    },
    enemy_defIgn_: {
      sheet: 'SharpenedStinger',
      name: 'enemy_defIgn_',
      tag: {
        et: 'display',
        qt: 'common',
        q: 'dmgRed_',
        sheet: 'SharpenedStinger',
        name: 'enemy_defIgn_',
      },
    },
    team_dmg_: {
      sheet: 'SharpenedStinger',
      name: 'team_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'SharpenedStinger',
        name: 'team_dmg_',
      },
    },
  },
  ShockstarDisco: {
    set4_basic_daze_: {
      sheet: 'ShockstarDisco',
      name: 'set4_basic_daze_',
      tag: {
        et: 'display',
        qt: 'common',
        q: 'stun_',
        sheet: 'ShockstarDisco',
        damageType2: 'basic',
        name: 'set4_basic_daze_',
      },
    },
    set4_dash_daze_: {
      sheet: 'ShockstarDisco',
      name: 'set4_dash_daze_',
      tag: {
        et: 'display',
        qt: 'common',
        q: 'stun_',
        sheet: 'ShockstarDisco',
        damageType2: 'dodge',
        name: 'set4_dash_daze_',
      },
    },
    set4_dodgeCounter_daze_: {
      sheet: 'ShockstarDisco',
      name: 'set4_dodgeCounter_daze_',
      tag: {
        et: 'display',
        qt: 'common',
        q: 'stun_',
        sheet: 'ShockstarDisco',
        damageType2: 'dodgeCounter',
        name: 'set4_dodgeCounter_daze_',
      },
    },
  },
  SixShooter: {
    cond_dmg_: {
      sheet: 'SixShooter',
      name: 'cond_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'SixShooter',
        name: 'cond_dmg_',
      },
    },
    enemy_defIgn_: {
      sheet: 'SixShooter',
      name: 'enemy_defIgn_',
      tag: {
        et: 'display',
        qt: 'common',
        q: 'dmgRed_',
        sheet: 'SixShooter',
        name: 'enemy_defIgn_',
      },
    },
    team_dmg_: {
      sheet: 'SixShooter',
      name: 'team_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'SixShooter',
        name: 'team_dmg_',
      },
    },
  },
  SliceOfTime: {
    cond_dmg_: {
      sheet: 'SliceOfTime',
      name: 'cond_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'SliceOfTime',
        name: 'cond_dmg_',
      },
    },
    enemy_defIgn_: {
      sheet: 'SliceOfTime',
      name: 'enemy_defIgn_',
      tag: {
        et: 'display',
        qt: 'common',
        q: 'dmgRed_',
        sheet: 'SliceOfTime',
        name: 'enemy_defIgn_',
      },
    },
    team_dmg_: {
      sheet: 'SliceOfTime',
      name: 'team_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'SliceOfTime',
        name: 'team_dmg_',
      },
    },
  },
  SpringEmbrace: {
    cond_dmg_: {
      sheet: 'SpringEmbrace',
      name: 'cond_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'SpringEmbrace',
        name: 'cond_dmg_',
      },
    },
    enemy_defIgn_: {
      sheet: 'SpringEmbrace',
      name: 'enemy_defIgn_',
      tag: {
        et: 'display',
        qt: 'common',
        q: 'dmgRed_',
        sheet: 'SpringEmbrace',
        name: 'enemy_defIgn_',
      },
    },
    team_dmg_: {
      sheet: 'SpringEmbrace',
      name: 'team_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'SpringEmbrace',
        name: 'team_dmg_',
      },
    },
  },
  StarlightEngine: {
    cond_dmg_: {
      sheet: 'StarlightEngine',
      name: 'cond_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'StarlightEngine',
        name: 'cond_dmg_',
      },
    },
    enemy_defIgn_: {
      sheet: 'StarlightEngine',
      name: 'enemy_defIgn_',
      tag: {
        et: 'display',
        qt: 'common',
        q: 'dmgRed_',
        sheet: 'StarlightEngine',
        name: 'enemy_defIgn_',
      },
    },
    team_dmg_: {
      sheet: 'StarlightEngine',
      name: 'team_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'StarlightEngine',
        name: 'team_dmg_',
      },
    },
  },
  StarlightEngineReplica: {
    cond_dmg_: {
      sheet: 'StarlightEngineReplica',
      name: 'cond_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'StarlightEngineReplica',
        name: 'cond_dmg_',
      },
    },
    enemy_defIgn_: {
      sheet: 'StarlightEngineReplica',
      name: 'enemy_defIgn_',
      tag: {
        et: 'display',
        qt: 'common',
        q: 'dmgRed_',
        sheet: 'StarlightEngineReplica',
        name: 'enemy_defIgn_',
      },
    },
    team_dmg_: {
      sheet: 'StarlightEngineReplica',
      name: 'team_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'StarlightEngineReplica',
        name: 'team_dmg_',
      },
    },
  },
  SteamOven: {
    cond_dmg_: {
      sheet: 'SteamOven',
      name: 'cond_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'SteamOven',
        name: 'cond_dmg_',
      },
    },
    enemy_defIgn_: {
      sheet: 'SteamOven',
      name: 'enemy_defIgn_',
      tag: {
        et: 'display',
        qt: 'common',
        q: 'dmgRed_',
        sheet: 'SteamOven',
        name: 'enemy_defIgn_',
      },
    },
    team_dmg_: {
      sheet: 'SteamOven',
      name: 'team_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'SteamOven',
        name: 'team_dmg_',
      },
    },
  },
  SteelCushion: {
    cond_dmg_: {
      sheet: 'SteelCushion',
      name: 'cond_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'SteelCushion',
        name: 'cond_dmg_',
      },
    },
    enemy_defIgn_: {
      sheet: 'SteelCushion',
      name: 'enemy_defIgn_',
      tag: {
        et: 'display',
        qt: 'common',
        q: 'dmgRed_',
        sheet: 'SteelCushion',
        name: 'enemy_defIgn_',
      },
    },
    team_dmg_: {
      sheet: 'SteelCushion',
      name: 'team_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'SteelCushion',
        name: 'team_dmg_',
      },
    },
  },
  StreetSuperstar: {
    cond_dmg_: {
      sheet: 'StreetSuperstar',
      name: 'cond_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'StreetSuperstar',
        name: 'cond_dmg_',
      },
    },
    enemy_defIgn_: {
      sheet: 'StreetSuperstar',
      name: 'enemy_defIgn_',
      tag: {
        et: 'display',
        qt: 'common',
        q: 'dmgRed_',
        sheet: 'StreetSuperstar',
        name: 'enemy_defIgn_',
      },
    },
    team_dmg_: {
      sheet: 'StreetSuperstar',
      name: 'team_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'StreetSuperstar',
        name: 'team_dmg_',
      },
    },
  },
  SwingJazz: {
    set4_cond_chain_or_ult: {
      sheet: 'SwingJazz',
      name: 'set4_cond_chain_or_ult',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'atk_',
        sheet: 'SwingJazz',
        name: 'set4_cond_chain_or_ult',
      },
    },
  },
  TheBrimstone: {
    cond_dmg_: {
      sheet: 'TheBrimstone',
      name: 'cond_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'TheBrimstone',
        name: 'cond_dmg_',
      },
    },
    enemy_defIgn_: {
      sheet: 'TheBrimstone',
      name: 'enemy_defIgn_',
      tag: {
        et: 'display',
        qt: 'common',
        q: 'dmgRed_',
        sheet: 'TheBrimstone',
        name: 'enemy_defIgn_',
      },
    },
    team_dmg_: {
      sheet: 'TheBrimstone',
      name: 'team_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'TheBrimstone',
        name: 'team_dmg_',
      },
    },
  },
  TheRestrained: {
    cond_dmg_: {
      sheet: 'TheRestrained',
      name: 'cond_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'TheRestrained',
        name: 'cond_dmg_',
      },
    },
    enemy_defIgn_: {
      sheet: 'TheRestrained',
      name: 'enemy_defIgn_',
      tag: {
        et: 'display',
        qt: 'common',
        q: 'dmgRed_',
        sheet: 'TheRestrained',
        name: 'enemy_defIgn_',
      },
    },
    team_dmg_: {
      sheet: 'TheRestrained',
      name: 'team_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'TheRestrained',
        name: 'team_dmg_',
      },
    },
  },
  TheVault: {
    cond_dmg_: {
      sheet: 'TheVault',
      name: 'cond_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'TheVault',
        name: 'cond_dmg_',
      },
    },
    enemy_defIgn_: {
      sheet: 'TheVault',
      name: 'enemy_defIgn_',
      tag: {
        et: 'display',
        qt: 'common',
        q: 'dmgRed_',
        sheet: 'TheVault',
        name: 'enemy_defIgn_',
      },
    },
    team_dmg_: {
      sheet: 'TheVault',
      name: 'team_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'TheVault',
        name: 'team_dmg_',
      },
    },
  },
  ThunderMetal: {
    set4_cond_enemy_shocked_atk_: {
      sheet: 'ThunderMetal',
      name: 'set4_cond_enemy_shocked_atk_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'atk_',
        sheet: 'ThunderMetal',
        name: 'set4_cond_enemy_shocked_atk_',
      },
    },
  },
  Timeweaver: {
    cond_dmg_: {
      sheet: 'Timeweaver',
      name: 'cond_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'Timeweaver',
        name: 'cond_dmg_',
      },
    },
    enemy_defIgn_: {
      sheet: 'Timeweaver',
      name: 'enemy_defIgn_',
      tag: {
        et: 'display',
        qt: 'common',
        q: 'dmgRed_',
        sheet: 'Timeweaver',
        name: 'enemy_defIgn_',
      },
    },
    team_dmg_: {
      sheet: 'Timeweaver',
      name: 'team_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'Timeweaver',
        name: 'team_dmg_',
      },
    },
  },
  TusksOfFury: {
    cond_dmg_: {
      sheet: 'TusksOfFury',
      name: 'cond_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'TusksOfFury',
        name: 'cond_dmg_',
      },
    },
    enemy_defIgn_: {
      sheet: 'TusksOfFury',
      name: 'enemy_defIgn_',
      tag: {
        et: 'display',
        qt: 'common',
        q: 'dmgRed_',
        sheet: 'TusksOfFury',
        name: 'enemy_defIgn_',
      },
    },
    team_dmg_: {
      sheet: 'TusksOfFury',
      name: 'team_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'TusksOfFury',
        name: 'team_dmg_',
      },
    },
  },
  UnfetteredGameBall: {
    cond_dmg_: {
      sheet: 'UnfetteredGameBall',
      name: 'cond_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'UnfetteredGameBall',
        name: 'cond_dmg_',
      },
    },
    enemy_defIgn_: {
      sheet: 'UnfetteredGameBall',
      name: 'enemy_defIgn_',
      tag: {
        et: 'display',
        qt: 'common',
        q: 'dmgRed_',
        sheet: 'UnfetteredGameBall',
        name: 'enemy_defIgn_',
      },
    },
    team_dmg_: {
      sheet: 'UnfetteredGameBall',
      name: 'team_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'UnfetteredGameBall',
        name: 'team_dmg_',
      },
    },
  },
  VortexArrow: {
    cond_dmg_: {
      sheet: 'VortexArrow',
      name: 'cond_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'VortexArrow',
        name: 'cond_dmg_',
      },
    },
    enemy_defIgn_: {
      sheet: 'VortexArrow',
      name: 'enemy_defIgn_',
      tag: {
        et: 'display',
        qt: 'common',
        q: 'dmgRed_',
        sheet: 'VortexArrow',
        name: 'enemy_defIgn_',
      },
    },
    team_dmg_: {
      sheet: 'VortexArrow',
      name: 'team_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'VortexArrow',
        name: 'team_dmg_',
      },
    },
  },
  VortexHatchet: {
    cond_dmg_: {
      sheet: 'VortexHatchet',
      name: 'cond_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'VortexHatchet',
        name: 'cond_dmg_',
      },
    },
    enemy_defIgn_: {
      sheet: 'VortexHatchet',
      name: 'enemy_defIgn_',
      tag: {
        et: 'display',
        qt: 'common',
        q: 'dmgRed_',
        sheet: 'VortexHatchet',
        name: 'enemy_defIgn_',
      },
    },
    team_dmg_: {
      sheet: 'VortexHatchet',
      name: 'team_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'VortexHatchet',
        name: 'team_dmg_',
      },
    },
  },
  VortexRevolver: {
    cond_dmg_: {
      sheet: 'VortexRevolver',
      name: 'cond_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'VortexRevolver',
        name: 'cond_dmg_',
      },
    },
    enemy_defIgn_: {
      sheet: 'VortexRevolver',
      name: 'enemy_defIgn_',
      tag: {
        et: 'display',
        qt: 'common',
        q: 'dmgRed_',
        sheet: 'VortexRevolver',
        name: 'enemy_defIgn_',
      },
    },
    team_dmg_: {
      sheet: 'VortexRevolver',
      name: 'team_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'VortexRevolver',
        name: 'team_dmg_',
      },
    },
  },
  WeepingCradle: {
    cond_dmg_: {
      sheet: 'WeepingCradle',
      name: 'cond_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'WeepingCradle',
        name: 'cond_dmg_',
      },
    },
    enemy_defIgn_: {
      sheet: 'WeepingCradle',
      name: 'enemy_defIgn_',
      tag: {
        et: 'display',
        qt: 'common',
        q: 'dmgRed_',
        sheet: 'WeepingCradle',
        name: 'enemy_defIgn_',
      },
    },
    team_dmg_: {
      sheet: 'WeepingCradle',
      name: 'team_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'WeepingCradle',
        name: 'team_dmg_',
      },
    },
  },
  WeepingGemini: {
    cond_dmg_: {
      sheet: 'WeepingGemini',
      name: 'cond_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'WeepingGemini',
        name: 'cond_dmg_',
      },
    },
    enemy_defIgn_: {
      sheet: 'WeepingGemini',
      name: 'enemy_defIgn_',
      tag: {
        et: 'display',
        qt: 'common',
        q: 'dmgRed_',
        sheet: 'WeepingGemini',
        name: 'enemy_defIgn_',
      },
    },
    team_dmg_: {
      sheet: 'WeepingGemini',
      name: 'team_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'WeepingGemini',
        name: 'team_dmg_',
      },
    },
  },
  WoodpeckerElectro: {
    set4_cond_crit_basic_dodge_ex_atk_: {
      sheet: 'WoodpeckerElectro',
      name: 'set4_cond_crit_basic_dodge_ex_atk_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'atk_',
        sheet: 'WoodpeckerElectro',
        name: 'set4_cond_crit_basic_dodge_ex_atk_',
      },
    },
  },
  ZanshinHerbCase: {
    cond_dmg_: {
      sheet: 'ZanshinHerbCase',
      name: 'cond_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'ZanshinHerbCase',
        name: 'cond_dmg_',
      },
    },
    enemy_defIgn_: {
      sheet: 'ZanshinHerbCase',
      name: 'enemy_defIgn_',
      tag: {
        et: 'display',
        qt: 'common',
        q: 'dmgRed_',
        sheet: 'ZanshinHerbCase',
        name: 'enemy_defIgn_',
      },
    },
    team_dmg_: {
      sheet: 'ZanshinHerbCase',
      name: 'team_dmg_',
      tag: {
        et: 'display',
        qt: 'combat',
        q: 'common_dmg_',
        sheet: 'ZanshinHerbCase',
        name: 'team_dmg_',
      },
    },
  },
} as const
