// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Nicole',
    name: 'standardDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'standardDmgBase',
      sheet: 'Nicole',
      attribute: 'ether',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Nicole',
    name: 'anomalyDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Nicole',
      attribute: 'ether',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_ether: {
    sheet: 'Nicole',
    name: 'disorderDmgInst_ether',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Nicole',
      attribute: 'ether',
      damageType1: 'disorder',
      name: 'disorderDmgInst_ether',
    },
  },
  vortexDmgInst_ether: {
    sheet: 'Nicole',
    name: 'vortexDmgInst_ether',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Nicole',
      attribute: 'ether',
      damageType1: 'vortex',
      name: 'vortexDmgInst_ether',
    },
  },
  abloomDmgInst: {
    sheet: 'Nicole',
    name: 'abloomDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Nicole',
      attribute: 'ether',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Nicole',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Nicole',
      attribute: 'ether',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Nicole',
    name: 'dazeInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'dazeBuildupBase',
      sheet: 'Nicole',
      attribute: 'ether',
      name: 'dazeInst',
    },
  },
  BasicAttackCunningCombo_0: {
    sheet: 'Nicole',
    name: 'BasicAttackCunningCombo_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Nicole',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackCunningCombo_0',
    },
  },
  BasicAttackCunningCombo_1: {
    sheet: 'Nicole',
    name: 'BasicAttackCunningCombo_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Nicole',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackCunningCombo_1',
    },
  },
  BasicAttackCunningCombo_2: {
    sheet: 'Nicole',
    name: 'BasicAttackCunningCombo_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Nicole',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackCunningCombo_2',
    },
  },
  BasicAttackDoAsIPlease_0: {
    sheet: 'Nicole',
    name: 'BasicAttackDoAsIPlease_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Nicole',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackDoAsIPlease_0',
    },
  },
  BasicAttackDoAsIPlease_1: {
    sheet: 'Nicole',
    name: 'BasicAttackDoAsIPlease_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Nicole',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackDoAsIPlease_1',
    },
  },
  BasicAttackDoAsIPlease_2: {
    sheet: 'Nicole',
    name: 'BasicAttackDoAsIPlease_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Nicole',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackDoAsIPlease_2',
    },
  },
  DashAttackJackInTheBox_0: {
    sheet: 'Nicole',
    name: 'DashAttackJackInTheBox_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Nicole',
      damageType1: 'dash',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttackJackInTheBox_0',
    },
  },
  DashAttackJackInTheBox_1: {
    sheet: 'Nicole',
    name: 'DashAttackJackInTheBox_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Nicole',
      damageType1: 'dash',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttackJackInTheBox_1',
    },
  },
  DodgeCounterDivertedBombard_0: {
    sheet: 'Nicole',
    name: 'DodgeCounterDivertedBombard_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Nicole',
      attribute: 'ether',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterDivertedBombard_0',
    },
  },
  SpecialAttackSugarcoatedBullet_0: {
    sheet: 'Nicole',
    name: 'SpecialAttackSugarcoatedBullet_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Nicole',
      attribute: 'ether',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackSugarcoatedBullet_0',
    },
  },
  EXSpecialAttackStuffedSugarcoatedBullet_0: {
    sheet: 'Nicole',
    name: 'EXSpecialAttackStuffedSugarcoatedBullet_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Nicole',
      attribute: 'ether',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackStuffedSugarcoatedBullet_0',
    },
  },
  EXSpecialAttackStuffedSugarcoatedBullet_1: {
    sheet: 'Nicole',
    name: 'EXSpecialAttackStuffedSugarcoatedBullet_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Nicole',
      attribute: 'ether',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackStuffedSugarcoatedBullet_1',
    },
  },
  EXSpecialAttackStuffedSugarcoatedBullet_2: {
    sheet: 'Nicole',
    name: 'EXSpecialAttackStuffedSugarcoatedBullet_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Nicole',
      attribute: 'ether',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackStuffedSugarcoatedBullet_2',
    },
  },
  EXSpecialAttackStuffedSugarcoatedBullet_3: {
    sheet: 'Nicole',
    name: 'EXSpecialAttackStuffedSugarcoatedBullet_3',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Nicole',
      attribute: 'ether',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackStuffedSugarcoatedBullet_3',
    },
  },
  ChainAttackEtherShellacking_0: {
    sheet: 'Nicole',
    name: 'ChainAttackEtherShellacking_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Nicole',
      attribute: 'ether',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackEtherShellacking_0',
    },
  },
  ChainAttackEtherShellacking_1: {
    sheet: 'Nicole',
    name: 'ChainAttackEtherShellacking_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Nicole',
      attribute: 'ether',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackEtherShellacking_1',
    },
  },
  UltimateEtherGrenade_0: {
    sheet: 'Nicole',
    name: 'UltimateEtherGrenade_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Nicole',
      attribute: 'ether',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateEtherGrenade_0',
    },
  },
  UltimateEtherGrenade_1: {
    sheet: 'Nicole',
    name: 'UltimateEtherGrenade_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Nicole',
      attribute: 'ether',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateEtherGrenade_1',
    },
  },
  QuickAssistEmergencyBombard_0: {
    sheet: 'Nicole',
    name: 'QuickAssistEmergencyBombard_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Nicole',
      attribute: 'ether',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistEmergencyBombard_0',
    },
  },
  DefensiveAssistTheHareStrikesBack_0: {
    sheet: 'Nicole',
    name: 'DefensiveAssistTheHareStrikesBack_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Nicole',
      attribute: 'ether',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistTheHareStrikesBack_0',
    },
  },
  DefensiveAssistTheHareStrikesBack_1: {
    sheet: 'Nicole',
    name: 'DefensiveAssistTheHareStrikesBack_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Nicole',
      attribute: 'ether',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistTheHareStrikesBack_1',
    },
  },
  DefensiveAssistTheHareStrikesBack_2: {
    sheet: 'Nicole',
    name: 'DefensiveAssistTheHareStrikesBack_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Nicole',
      attribute: 'ether',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistTheHareStrikesBack_2',
    },
  },
  AssistFollowUpWindowOfOpportunity_0: {
    sheet: 'Nicole',
    name: 'AssistFollowUpWindowOfOpportunity_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Nicole',
      attribute: 'ether',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpWindowOfOpportunity_0',
    },
  },
} as const
