// WARNING: Generated file, do not modify
export const buffs = {
  ult_atk: {
    sheet: 'Aria',
    name: 'ult_atk',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'atk',
      sheet: 'Aria',
      name: 'ult_atk',
    },
  },
  core_anomProf: {
    sheet: 'Aria',
    name: 'core_anomProf',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anomProf',
      sheet: 'Aria',
      name: 'core_anomProf',
    },
  },
  core_electric_anom_mv_mult_: {
    sheet: 'Aria',
    name: 'core_electric_anom_mv_mult_',
    tag: {
      et: 'display',
      qt: 'dmg',
      q: 'anom_mv_mult_',
      sheet: 'Aria',
      attribute: 'electric',
      damageType1: 'abloom',
      name: 'core_electric_anom_mv_mult_',
    },
  },
  core_fire_anom_mv_mult_: {
    sheet: 'Aria',
    name: 'core_fire_anom_mv_mult_',
    tag: {
      et: 'display',
      qt: 'dmg',
      q: 'anom_mv_mult_',
      sheet: 'Aria',
      attribute: 'fire',
      damageType1: 'abloom',
      name: 'core_fire_anom_mv_mult_',
    },
  },
  core_ice_anom_mv_mult_: {
    sheet: 'Aria',
    name: 'core_ice_anom_mv_mult_',
    tag: {
      et: 'display',
      qt: 'dmg',
      q: 'anom_mv_mult_',
      sheet: 'Aria',
      attribute: 'ice',
      damageType1: 'abloom',
      name: 'core_ice_anom_mv_mult_',
    },
  },
  core_physical_anom_mv_mult_: {
    sheet: 'Aria',
    name: 'core_physical_anom_mv_mult_',
    tag: {
      et: 'display',
      qt: 'dmg',
      q: 'anom_mv_mult_',
      sheet: 'Aria',
      attribute: 'physical',
      damageType1: 'abloom',
      name: 'core_physical_anom_mv_mult_',
    },
  },
  core_ether_anom_mv_mult_: {
    sheet: 'Aria',
    name: 'core_ether_anom_mv_mult_',
    tag: {
      et: 'display',
      qt: 'dmg',
      q: 'anom_mv_mult_',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'abloom',
      name: 'core_ether_anom_mv_mult_',
    },
  },
  m1_basic_ether_anomBuildupResIgn_: {
    sheet: 'Aria',
    name: 'm1_basic_ether_anomBuildupResIgn_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anomBuildupResIgn_',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      name: 'm1_basic_ether_anomBuildupResIgn_',
    },
  },
  m1_special_ether_anomBuildupResIgn_: {
    sheet: 'Aria',
    name: 'm1_special_ether_anomBuildupResIgn_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anomBuildupResIgn_',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'special',
      name: 'm1_special_ether_anomBuildupResIgn_',
    },
  },
  m1_exSpecial_ether_anomBuildupResIgn_: {
    sheet: 'Aria',
    name: 'm1_exSpecial_ether_anomBuildupResIgn_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anomBuildupResIgn_',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'exSpecial',
      name: 'm1_exSpecial_ether_anomBuildupResIgn_',
    },
  },
  m1_abloom_anom_crit_: {
    sheet: 'Aria',
    name: 'm1_abloom_anom_crit_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anom_crit_',
      sheet: 'Aria',
      damageType1: 'abloom',
      name: 'm1_abloom_anom_crit_',
    },
  },
  m1_abloom_anom_crit_dmg_: {
    sheet: 'Aria',
    name: 'm1_abloom_anom_crit_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'anom_crit_dmg_',
      sheet: 'Aria',
      damageType1: 'abloom',
      name: 'm1_abloom_anom_crit_dmg_',
    },
  },
  m2_basic_defIgn_: {
    sheet: 'Aria',
    name: 'm2_basic_defIgn_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'defIgn_',
      sheet: 'Aria',
      damageType1: 'basic',
      name: 'm2_basic_defIgn_',
    },
  },
  m2_dash_defIgn_: {
    sheet: 'Aria',
    name: 'm2_dash_defIgn_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'defIgn_',
      sheet: 'Aria',
      damageType1: 'dash',
      name: 'm2_dash_defIgn_',
    },
  },
  m2_dodgeCounter_defIgn_: {
    sheet: 'Aria',
    name: 'm2_dodgeCounter_defIgn_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'defIgn_',
      sheet: 'Aria',
      damageType1: 'dodgeCounter',
      name: 'm2_dodgeCounter_defIgn_',
    },
  },
  m2_special_defIgn_: {
    sheet: 'Aria',
    name: 'm2_special_defIgn_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'defIgn_',
      sheet: 'Aria',
      damageType1: 'special',
      name: 'm2_special_defIgn_',
    },
  },
  m2_exSpecial_defIgn_: {
    sheet: 'Aria',
    name: 'm2_exSpecial_defIgn_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'defIgn_',
      sheet: 'Aria',
      damageType1: 'exSpecial',
      name: 'm2_exSpecial_defIgn_',
    },
  },
  m2_chain_defIgn_: {
    sheet: 'Aria',
    name: 'm2_chain_defIgn_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'defIgn_',
      sheet: 'Aria',
      damageType1: 'chain',
      name: 'm2_chain_defIgn_',
    },
  },
  m2_ult_defIgn_: {
    sheet: 'Aria',
    name: 'm2_ult_defIgn_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'defIgn_',
      sheet: 'Aria',
      damageType1: 'ult',
      name: 'm2_ult_defIgn_',
    },
  },
  m2_quickAssist_defIgn_: {
    sheet: 'Aria',
    name: 'm2_quickAssist_defIgn_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'defIgn_',
      sheet: 'Aria',
      damageType1: 'quickAssist',
      name: 'm2_quickAssist_defIgn_',
    },
  },
  m2_defensiveAssist_defIgn_: {
    sheet: 'Aria',
    name: 'm2_defensiveAssist_defIgn_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'defIgn_',
      sheet: 'Aria',
      damageType1: 'defensiveAssist',
      name: 'm2_defensiveAssist_defIgn_',
    },
  },
  m2_assistFollowUp_defIgn_: {
    sheet: 'Aria',
    name: 'm2_assistFollowUp_defIgn_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'defIgn_',
      sheet: 'Aria',
      damageType1: 'assistFollowUp',
      name: 'm2_assistFollowUp_defIgn_',
    },
  },
  m2_aftershock_defIgn_: {
    sheet: 'Aria',
    name: 'm2_aftershock_defIgn_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'defIgn_',
      sheet: 'Aria',
      damageType1: 'aftershock',
      name: 'm2_aftershock_defIgn_',
    },
  },
  m2_elemental_defIgn_: {
    sheet: 'Aria',
    name: 'm2_elemental_defIgn_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'defIgn_',
      sheet: 'Aria',
      damageType1: 'elemental',
      name: 'm2_elemental_defIgn_',
    },
  },
  m2_abloom_defIgn_: {
    sheet: 'Aria',
    name: 'm2_abloom_defIgn_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'defIgn_',
      sheet: 'Aria',
      damageType1: 'abloom',
      name: 'm2_abloom_defIgn_',
    },
  },
  m2_defIgn_: {
    sheet: 'Aria',
    name: 'm2_defIgn_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'defIgn_',
      sheet: 'Aria',
      name: 'm2_defIgn_',
    },
  },
  m6_basic_ether_dmg_: {
    sheet: 'Aria',
    name: 'm6_basic_ether_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dmg_',
      sheet: 'Aria',
      damageType1: 'basic',
      name: 'm6_basic_ether_dmg_',
    },
  },
  m6_ult_ether_dmg_: {
    sheet: 'Aria',
    name: 'm6_ult_ether_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dmg_',
      sheet: 'Aria',
      damageType1: 'ult',
      name: 'm6_ult_ether_dmg_',
    },
  },
} as const
