// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Aria',
    name: 'standardDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'standardDmgBase',
      sheet: 'Aria',
      attribute: 'ether',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Aria',
    name: 'anomalyDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_ether: {
    sheet: 'Aria',
    name: 'disorderDmgInst_ether',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'disorder',
      name: 'disorderDmgInst_ether',
    },
  },
  vortexDmgInst_ether: {
    sheet: 'Aria',
    name: 'vortexDmgInst_ether',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'vortex',
      name: 'vortexDmgInst_ether',
    },
  },
  abloomDmgInst: {
    sheet: 'Aria',
    name: 'abloomDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Aria',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Aria',
      attribute: 'ether',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Aria',
    name: 'dazeInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'dazeBuildupBase',
      sheet: 'Aria',
      attribute: 'ether',
      name: 'dazeInst',
    },
  },
  BasicAttackSweetMelody_0: {
    sheet: 'Aria',
    name: 'BasicAttackSweetMelody_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSweetMelody_0',
    },
  },
  BasicAttackSweetMelody_1: {
    sheet: 'Aria',
    name: 'BasicAttackSweetMelody_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSweetMelody_1',
    },
  },
  BasicAttackSweetMelody_2: {
    sheet: 'Aria',
    name: 'BasicAttackSweetMelody_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSweetMelody_2',
    },
  },
  BasicAttackSweetMelody_3: {
    sheet: 'Aria',
    name: 'BasicAttackSweetMelody_3',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSweetMelody_3',
    },
  },
  BasicAttackPerfectPitch_0: {
    sheet: 'Aria',
    name: 'BasicAttackPerfectPitch_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPerfectPitch_0',
    },
  },
  BasicAttackPerfectPitch_1: {
    sheet: 'Aria',
    name: 'BasicAttackPerfectPitch_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPerfectPitch_1',
    },
  },
  BasicAttackPerfectPitch_2: {
    sheet: 'Aria',
    name: 'BasicAttackPerfectPitch_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPerfectPitch_2',
    },
  },
  BasicAttackPerfectPitch_3: {
    sheet: 'Aria',
    name: 'BasicAttackPerfectPitch_3',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPerfectPitch_3',
    },
  },
  BasicAttackPerfectPitch_4: {
    sheet: 'Aria',
    name: 'BasicAttackPerfectPitch_4',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPerfectPitch_4',
    },
  },
  DashAttackSilkySmoothCombo_0: {
    sheet: 'Aria',
    name: 'DashAttackSilkySmoothCombo_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackSilkySmoothCombo_0',
    },
  },
  DodgeCounterSlideShiftVariation_0: {
    sheet: 'Aria',
    name: 'DodgeCounterSlideShiftVariation_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterSlideShiftVariation_0',
    },
  },
  SpecialAttackFullSugarElectronica_0: {
    sheet: 'Aria',
    name: 'SpecialAttackFullSugarElectronica_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackFullSugarElectronica_0',
    },
  },
  SpecialAttackFullSugarElectronicaNoIce_0: {
    sheet: 'Aria',
    name: 'SpecialAttackFullSugarElectronicaNoIce_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackFullSugarElectronicaNoIce_0',
    },
  },
  EXSpecialAttackFallIntoDelusion_0: {
    sheet: 'Aria',
    name: 'EXSpecialAttackFallIntoDelusion_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackFallIntoDelusion_0',
    },
  },
  EXSpecialAttackInstantlyHooked_0: {
    sheet: 'Aria',
    name: 'EXSpecialAttackInstantlyHooked_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackInstantlyHooked_0',
    },
  },
  ChainAttackDreamCollab_0: {
    sheet: 'Aria',
    name: 'ChainAttackDreamCollab_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackDreamCollab_0',
    },
  },
  Ultimate100Energy_0: {
    sheet: 'Aria',
    name: 'Ultimate100Energy_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'Ultimate100Energy_0',
    },
  },
  QuickAssistShatterFantasy_0: {
    sheet: 'Aria',
    name: 'QuickAssistShatterFantasy_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistShatterFantasy_0',
    },
  },
  DefensiveAssistClutchSave_0: {
    sheet: 'Aria',
    name: 'DefensiveAssistClutchSave_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistClutchSave_0',
    },
  },
  DefensiveAssistClutchSave_1: {
    sheet: 'Aria',
    name: 'DefensiveAssistClutchSave_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistClutchSave_1',
    },
  },
  DefensiveAssistClutchSave_2: {
    sheet: 'Aria',
    name: 'DefensiveAssistClutchSave_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistClutchSave_2',
    },
  },
  AssistFollowUpEncoreSong_0: {
    sheet: 'Aria',
    name: 'AssistFollowUpEncoreSong_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpEncoreSong_0',
    },
  },
} as const
