// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Aria',
    name: 'standardDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Aria',
      attribute: 'ether',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Aria',
    name: 'anomalyDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_ether: {
    sheet: 'Aria',
    name: 'disorderDmgInst_ether',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'disorder',
      name: 'disorderDmgInst_ether',
    },
  },
  vortexDmgInst_ether: {
    sheet: 'Aria',
    name: 'vortexDmgInst_ether',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'vortex',
      name: 'vortexDmgInst_ether',
    },
  },
  abloomDmgInst: {
    sheet: 'Aria',
    name: 'abloomDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Aria',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Aria',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      name: 'dazeInst',
    },
  },
  'BasicAttackSweetMelody_0:standardDmg': {
    sheet: 'Aria',
    name: 'BasicAttackSweetMelody_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSweetMelody_0',
    },
  },
  'BasicAttackSweetMelody_0:dazeBuildup': {
    sheet: 'Aria',
    name: 'BasicAttackSweetMelody_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSweetMelody_0',
    },
  },
  'BasicAttackSweetMelody_0:anomBuildup': {
    sheet: 'Aria',
    name: 'BasicAttackSweetMelody_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSweetMelody_0',
    },
  },
  'BasicAttackSweetMelody_1:standardDmg': {
    sheet: 'Aria',
    name: 'BasicAttackSweetMelody_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSweetMelody_1',
    },
  },
  'BasicAttackSweetMelody_1:dazeBuildup': {
    sheet: 'Aria',
    name: 'BasicAttackSweetMelody_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSweetMelody_1',
    },
  },
  'BasicAttackSweetMelody_1:anomBuildup': {
    sheet: 'Aria',
    name: 'BasicAttackSweetMelody_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSweetMelody_1',
    },
  },
  'BasicAttackSweetMelody_2:standardDmg': {
    sheet: 'Aria',
    name: 'BasicAttackSweetMelody_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSweetMelody_2',
    },
  },
  'BasicAttackSweetMelody_2:dazeBuildup': {
    sheet: 'Aria',
    name: 'BasicAttackSweetMelody_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSweetMelody_2',
    },
  },
  'BasicAttackSweetMelody_2:anomBuildup': {
    sheet: 'Aria',
    name: 'BasicAttackSweetMelody_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSweetMelody_2',
    },
  },
  'BasicAttackSweetMelody_3:standardDmg': {
    sheet: 'Aria',
    name: 'BasicAttackSweetMelody_3:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSweetMelody_3',
    },
  },
  'BasicAttackSweetMelody_3:dazeBuildup': {
    sheet: 'Aria',
    name: 'BasicAttackSweetMelody_3:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSweetMelody_3',
    },
  },
  'BasicAttackSweetMelody_3:anomBuildup': {
    sheet: 'Aria',
    name: 'BasicAttackSweetMelody_3:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSweetMelody_3',
    },
  },
  'BasicAttackPerfectPitch_0:standardDmg': {
    sheet: 'Aria',
    name: 'BasicAttackPerfectPitch_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPerfectPitch_0',
    },
  },
  'BasicAttackPerfectPitch_0:dazeBuildup': {
    sheet: 'Aria',
    name: 'BasicAttackPerfectPitch_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPerfectPitch_0',
    },
  },
  'BasicAttackPerfectPitch_0:anomBuildup': {
    sheet: 'Aria',
    name: 'BasicAttackPerfectPitch_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPerfectPitch_0',
    },
  },
  'BasicAttackPerfectPitch_1:standardDmg': {
    sheet: 'Aria',
    name: 'BasicAttackPerfectPitch_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPerfectPitch_1',
    },
  },
  'BasicAttackPerfectPitch_1:dazeBuildup': {
    sheet: 'Aria',
    name: 'BasicAttackPerfectPitch_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPerfectPitch_1',
    },
  },
  'BasicAttackPerfectPitch_1:anomBuildup': {
    sheet: 'Aria',
    name: 'BasicAttackPerfectPitch_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPerfectPitch_1',
    },
  },
  'BasicAttackPerfectPitch_2:standardDmg': {
    sheet: 'Aria',
    name: 'BasicAttackPerfectPitch_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPerfectPitch_2',
    },
  },
  'BasicAttackPerfectPitch_2:dazeBuildup': {
    sheet: 'Aria',
    name: 'BasicAttackPerfectPitch_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPerfectPitch_2',
    },
  },
  'BasicAttackPerfectPitch_2:anomBuildup': {
    sheet: 'Aria',
    name: 'BasicAttackPerfectPitch_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPerfectPitch_2',
    },
  },
  'BasicAttackPerfectPitch_3:standardDmg': {
    sheet: 'Aria',
    name: 'BasicAttackPerfectPitch_3:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPerfectPitch_3',
    },
  },
  'BasicAttackPerfectPitch_3:dazeBuildup': {
    sheet: 'Aria',
    name: 'BasicAttackPerfectPitch_3:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPerfectPitch_3',
    },
  },
  'BasicAttackPerfectPitch_3:anomBuildup': {
    sheet: 'Aria',
    name: 'BasicAttackPerfectPitch_3:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPerfectPitch_3',
    },
  },
  'BasicAttackPerfectPitch_4:standardDmg': {
    sheet: 'Aria',
    name: 'BasicAttackPerfectPitch_4:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPerfectPitch_4',
    },
  },
  'BasicAttackPerfectPitch_4:dazeBuildup': {
    sheet: 'Aria',
    name: 'BasicAttackPerfectPitch_4:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPerfectPitch_4',
    },
  },
  'BasicAttackPerfectPitch_4:anomBuildup': {
    sheet: 'Aria',
    name: 'BasicAttackPerfectPitch_4:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPerfectPitch_4',
    },
  },
  'DashAttackSilkySmoothCombo_0:standardDmg': {
    sheet: 'Aria',
    name: 'DashAttackSilkySmoothCombo_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackSilkySmoothCombo_0',
    },
  },
  'DashAttackSilkySmoothCombo_0:dazeBuildup': {
    sheet: 'Aria',
    name: 'DashAttackSilkySmoothCombo_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackSilkySmoothCombo_0',
    },
  },
  'DashAttackSilkySmoothCombo_0:anomBuildup': {
    sheet: 'Aria',
    name: 'DashAttackSilkySmoothCombo_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackSilkySmoothCombo_0',
    },
  },
  'DodgeCounterSlideShiftVariation_0:standardDmg': {
    sheet: 'Aria',
    name: 'DodgeCounterSlideShiftVariation_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterSlideShiftVariation_0',
    },
  },
  'DodgeCounterSlideShiftVariation_0:dazeBuildup': {
    sheet: 'Aria',
    name: 'DodgeCounterSlideShiftVariation_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterSlideShiftVariation_0',
    },
  },
  'DodgeCounterSlideShiftVariation_0:anomBuildup': {
    sheet: 'Aria',
    name: 'DodgeCounterSlideShiftVariation_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterSlideShiftVariation_0',
    },
  },
  'SpecialAttackFullSugarElectronica_0:standardDmg': {
    sheet: 'Aria',
    name: 'SpecialAttackFullSugarElectronica_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackFullSugarElectronica_0',
    },
  },
  'SpecialAttackFullSugarElectronica_0:dazeBuildup': {
    sheet: 'Aria',
    name: 'SpecialAttackFullSugarElectronica_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackFullSugarElectronica_0',
    },
  },
  'SpecialAttackFullSugarElectronica_0:anomBuildup': {
    sheet: 'Aria',
    name: 'SpecialAttackFullSugarElectronica_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackFullSugarElectronica_0',
    },
  },
  'SpecialAttackFullSugarElectronicaNoIce_0:standardDmg': {
    sheet: 'Aria',
    name: 'SpecialAttackFullSugarElectronicaNoIce_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackFullSugarElectronicaNoIce_0',
    },
  },
  'SpecialAttackFullSugarElectronicaNoIce_0:dazeBuildup': {
    sheet: 'Aria',
    name: 'SpecialAttackFullSugarElectronicaNoIce_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackFullSugarElectronicaNoIce_0',
    },
  },
  'SpecialAttackFullSugarElectronicaNoIce_0:anomBuildup': {
    sheet: 'Aria',
    name: 'SpecialAttackFullSugarElectronicaNoIce_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackFullSugarElectronicaNoIce_0',
    },
  },
  'EXSpecialAttackFallIntoDelusion_0:standardDmg': {
    sheet: 'Aria',
    name: 'EXSpecialAttackFallIntoDelusion_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackFallIntoDelusion_0',
    },
  },
  'EXSpecialAttackFallIntoDelusion_0:dazeBuildup': {
    sheet: 'Aria',
    name: 'EXSpecialAttackFallIntoDelusion_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackFallIntoDelusion_0',
    },
  },
  'EXSpecialAttackFallIntoDelusion_0:anomBuildup': {
    sheet: 'Aria',
    name: 'EXSpecialAttackFallIntoDelusion_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackFallIntoDelusion_0',
    },
  },
  'EXSpecialAttackInstantlyHooked_0:standardDmg': {
    sheet: 'Aria',
    name: 'EXSpecialAttackInstantlyHooked_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackInstantlyHooked_0',
    },
  },
  'EXSpecialAttackInstantlyHooked_0:dazeBuildup': {
    sheet: 'Aria',
    name: 'EXSpecialAttackInstantlyHooked_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackInstantlyHooked_0',
    },
  },
  'EXSpecialAttackInstantlyHooked_0:anomBuildup': {
    sheet: 'Aria',
    name: 'EXSpecialAttackInstantlyHooked_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackInstantlyHooked_0',
    },
  },
  'ChainAttackDreamCollab_0:standardDmg': {
    sheet: 'Aria',
    name: 'ChainAttackDreamCollab_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackDreamCollab_0',
    },
  },
  'ChainAttackDreamCollab_0:dazeBuildup': {
    sheet: 'Aria',
    name: 'ChainAttackDreamCollab_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackDreamCollab_0',
    },
  },
  'ChainAttackDreamCollab_0:anomBuildup': {
    sheet: 'Aria',
    name: 'ChainAttackDreamCollab_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackDreamCollab_0',
    },
  },
  'Ultimate100Energy_0:standardDmg': {
    sheet: 'Aria',
    name: 'Ultimate100Energy_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'Ultimate100Energy_0',
    },
  },
  'Ultimate100Energy_0:dazeBuildup': {
    sheet: 'Aria',
    name: 'Ultimate100Energy_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'Ultimate100Energy_0',
    },
  },
  'Ultimate100Energy_0:anomBuildup': {
    sheet: 'Aria',
    name: 'Ultimate100Energy_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'Ultimate100Energy_0',
    },
  },
  'QuickAssistShatterFantasy_0:standardDmg': {
    sheet: 'Aria',
    name: 'QuickAssistShatterFantasy_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistShatterFantasy_0',
    },
  },
  'QuickAssistShatterFantasy_0:dazeBuildup': {
    sheet: 'Aria',
    name: 'QuickAssistShatterFantasy_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistShatterFantasy_0',
    },
  },
  'QuickAssistShatterFantasy_0:anomBuildup': {
    sheet: 'Aria',
    name: 'QuickAssistShatterFantasy_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistShatterFantasy_0',
    },
  },
  'DefensiveAssistClutchSave_0:standardDmg': {
    sheet: 'Aria',
    name: 'DefensiveAssistClutchSave_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistClutchSave_0',
    },
  },
  'DefensiveAssistClutchSave_0:dazeBuildup': {
    sheet: 'Aria',
    name: 'DefensiveAssistClutchSave_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistClutchSave_0',
    },
  },
  'DefensiveAssistClutchSave_0:anomBuildup': {
    sheet: 'Aria',
    name: 'DefensiveAssistClutchSave_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistClutchSave_0',
    },
  },
  'DefensiveAssistClutchSave_1:standardDmg': {
    sheet: 'Aria',
    name: 'DefensiveAssistClutchSave_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistClutchSave_1',
    },
  },
  'DefensiveAssistClutchSave_1:dazeBuildup': {
    sheet: 'Aria',
    name: 'DefensiveAssistClutchSave_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistClutchSave_1',
    },
  },
  'DefensiveAssistClutchSave_1:anomBuildup': {
    sheet: 'Aria',
    name: 'DefensiveAssistClutchSave_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistClutchSave_1',
    },
  },
  'DefensiveAssistClutchSave_2:standardDmg': {
    sheet: 'Aria',
    name: 'DefensiveAssistClutchSave_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistClutchSave_2',
    },
  },
  'DefensiveAssistClutchSave_2:dazeBuildup': {
    sheet: 'Aria',
    name: 'DefensiveAssistClutchSave_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistClutchSave_2',
    },
  },
  'DefensiveAssistClutchSave_2:anomBuildup': {
    sheet: 'Aria',
    name: 'DefensiveAssistClutchSave_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistClutchSave_2',
    },
  },
  'AssistFollowUpEncoreSong_0:standardDmg': {
    sheet: 'Aria',
    name: 'AssistFollowUpEncoreSong_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpEncoreSong_0',
    },
  },
  'AssistFollowUpEncoreSong_0:dazeBuildup': {
    sheet: 'Aria',
    name: 'AssistFollowUpEncoreSong_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpEncoreSong_0',
    },
  },
  'AssistFollowUpEncoreSong_0:anomBuildup': {
    sheet: 'Aria',
    name: 'AssistFollowUpEncoreSong_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpEncoreSong_0',
    },
  },
} as const
