// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Aria',
    name: 'standardDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Aria',
      attribute: 'ether',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Aria',
    name: 'anomalyDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_ether: {
    sheet: 'Aria',
    name: 'disorderDmgInst_ether',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'disorder',
      name: 'disorderDmgInst_ether',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Aria',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Aria',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      name: 'dazeInst',
    },
  },
  BasicAttackSweetMelody_0_dmg: {
    sheet: 'Aria',
    name: 'BasicAttackSweetMelody_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSweetMelody_0_dmg',
    },
  },
  BasicAttackSweetMelody_0_daze: {
    sheet: 'Aria',
    name: 'BasicAttackSweetMelody_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSweetMelody_0_daze',
    },
  },
  BasicAttackSweetMelody_0_anomBuildup: {
    sheet: 'Aria',
    name: 'BasicAttackSweetMelody_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSweetMelody_0_anomBuildup',
    },
  },
  BasicAttackSweetMelody_1_dmg: {
    sheet: 'Aria',
    name: 'BasicAttackSweetMelody_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSweetMelody_1_dmg',
    },
  },
  BasicAttackSweetMelody_1_daze: {
    sheet: 'Aria',
    name: 'BasicAttackSweetMelody_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSweetMelody_1_daze',
    },
  },
  BasicAttackSweetMelody_1_anomBuildup: {
    sheet: 'Aria',
    name: 'BasicAttackSweetMelody_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSweetMelody_1_anomBuildup',
    },
  },
  BasicAttackSweetMelody_2_dmg: {
    sheet: 'Aria',
    name: 'BasicAttackSweetMelody_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSweetMelody_2_dmg',
    },
  },
  BasicAttackSweetMelody_2_daze: {
    sheet: 'Aria',
    name: 'BasicAttackSweetMelody_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSweetMelody_2_daze',
    },
  },
  BasicAttackSweetMelody_2_anomBuildup: {
    sheet: 'Aria',
    name: 'BasicAttackSweetMelody_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSweetMelody_2_anomBuildup',
    },
  },
  BasicAttackSweetMelody_3_dmg: {
    sheet: 'Aria',
    name: 'BasicAttackSweetMelody_3_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSweetMelody_3_dmg',
    },
  },
  BasicAttackSweetMelody_3_daze: {
    sheet: 'Aria',
    name: 'BasicAttackSweetMelody_3_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSweetMelody_3_daze',
    },
  },
  BasicAttackSweetMelody_3_anomBuildup: {
    sheet: 'Aria',
    name: 'BasicAttackSweetMelody_3_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSweetMelody_3_anomBuildup',
    },
  },
  BasicAttackPerfectPitch_0_dmg: {
    sheet: 'Aria',
    name: 'BasicAttackPerfectPitch_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPerfectPitch_0_dmg',
    },
  },
  BasicAttackPerfectPitch_0_daze: {
    sheet: 'Aria',
    name: 'BasicAttackPerfectPitch_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPerfectPitch_0_daze',
    },
  },
  BasicAttackPerfectPitch_0_anomBuildup: {
    sheet: 'Aria',
    name: 'BasicAttackPerfectPitch_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPerfectPitch_0_anomBuildup',
    },
  },
  BasicAttackPerfectPitch_1_dmg: {
    sheet: 'Aria',
    name: 'BasicAttackPerfectPitch_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPerfectPitch_1_dmg',
    },
  },
  BasicAttackPerfectPitch_1_daze: {
    sheet: 'Aria',
    name: 'BasicAttackPerfectPitch_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPerfectPitch_1_daze',
    },
  },
  BasicAttackPerfectPitch_1_anomBuildup: {
    sheet: 'Aria',
    name: 'BasicAttackPerfectPitch_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPerfectPitch_1_anomBuildup',
    },
  },
  BasicAttackPerfectPitch_2_dmg: {
    sheet: 'Aria',
    name: 'BasicAttackPerfectPitch_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPerfectPitch_2_dmg',
    },
  },
  BasicAttackPerfectPitch_2_daze: {
    sheet: 'Aria',
    name: 'BasicAttackPerfectPitch_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPerfectPitch_2_daze',
    },
  },
  BasicAttackPerfectPitch_2_anomBuildup: {
    sheet: 'Aria',
    name: 'BasicAttackPerfectPitch_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPerfectPitch_2_anomBuildup',
    },
  },
  BasicAttackPerfectPitch_3_dmg: {
    sheet: 'Aria',
    name: 'BasicAttackPerfectPitch_3_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPerfectPitch_3_dmg',
    },
  },
  BasicAttackPerfectPitch_3_daze: {
    sheet: 'Aria',
    name: 'BasicAttackPerfectPitch_3_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPerfectPitch_3_daze',
    },
  },
  BasicAttackPerfectPitch_3_anomBuildup: {
    sheet: 'Aria',
    name: 'BasicAttackPerfectPitch_3_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPerfectPitch_3_anomBuildup',
    },
  },
  BasicAttackPerfectPitch_4_dmg: {
    sheet: 'Aria',
    name: 'BasicAttackPerfectPitch_4_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPerfectPitch_4_dmg',
    },
  },
  BasicAttackPerfectPitch_4_daze: {
    sheet: 'Aria',
    name: 'BasicAttackPerfectPitch_4_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPerfectPitch_4_daze',
    },
  },
  BasicAttackPerfectPitch_4_anomBuildup: {
    sheet: 'Aria',
    name: 'BasicAttackPerfectPitch_4_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPerfectPitch_4_anomBuildup',
    },
  },
  DashAttackSilkySmoothCombo_0_dmg: {
    sheet: 'Aria',
    name: 'DashAttackSilkySmoothCombo_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackSilkySmoothCombo_0_dmg',
    },
  },
  DashAttackSilkySmoothCombo_0_daze: {
    sheet: 'Aria',
    name: 'DashAttackSilkySmoothCombo_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackSilkySmoothCombo_0_daze',
    },
  },
  DashAttackSilkySmoothCombo_0_anomBuildup: {
    sheet: 'Aria',
    name: 'DashAttackSilkySmoothCombo_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackSilkySmoothCombo_0_anomBuildup',
    },
  },
  DodgeCounterSlideShiftVariation_0_dmg: {
    sheet: 'Aria',
    name: 'DodgeCounterSlideShiftVariation_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterSlideShiftVariation_0_dmg',
    },
  },
  DodgeCounterSlideShiftVariation_0_daze: {
    sheet: 'Aria',
    name: 'DodgeCounterSlideShiftVariation_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterSlideShiftVariation_0_daze',
    },
  },
  DodgeCounterSlideShiftVariation_0_anomBuildup: {
    sheet: 'Aria',
    name: 'DodgeCounterSlideShiftVariation_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterSlideShiftVariation_0_anomBuildup',
    },
  },
  SpecialAttackFullSugarElectronica_0_dmg: {
    sheet: 'Aria',
    name: 'SpecialAttackFullSugarElectronica_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackFullSugarElectronica_0_dmg',
    },
  },
  SpecialAttackFullSugarElectronica_0_daze: {
    sheet: 'Aria',
    name: 'SpecialAttackFullSugarElectronica_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackFullSugarElectronica_0_daze',
    },
  },
  SpecialAttackFullSugarElectronica_0_anomBuildup: {
    sheet: 'Aria',
    name: 'SpecialAttackFullSugarElectronica_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackFullSugarElectronica_0_anomBuildup',
    },
  },
  SpecialAttackFullSugarElectronicaNoIce_0_dmg: {
    sheet: 'Aria',
    name: 'SpecialAttackFullSugarElectronicaNoIce_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackFullSugarElectronicaNoIce_0_dmg',
    },
  },
  SpecialAttackFullSugarElectronicaNoIce_0_daze: {
    sheet: 'Aria',
    name: 'SpecialAttackFullSugarElectronicaNoIce_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackFullSugarElectronicaNoIce_0_daze',
    },
  },
  SpecialAttackFullSugarElectronicaNoIce_0_anomBuildup: {
    sheet: 'Aria',
    name: 'SpecialAttackFullSugarElectronicaNoIce_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackFullSugarElectronicaNoIce_0_anomBuildup',
    },
  },
  EXSpecialAttackFallIntoDelusion_0_dmg: {
    sheet: 'Aria',
    name: 'EXSpecialAttackFallIntoDelusion_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackFallIntoDelusion_0_dmg',
    },
  },
  EXSpecialAttackFallIntoDelusion_0_daze: {
    sheet: 'Aria',
    name: 'EXSpecialAttackFallIntoDelusion_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackFallIntoDelusion_0_daze',
    },
  },
  EXSpecialAttackFallIntoDelusion_0_anomBuildup: {
    sheet: 'Aria',
    name: 'EXSpecialAttackFallIntoDelusion_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackFallIntoDelusion_0_anomBuildup',
    },
  },
  EXSpecialAttackInstantlyHooked_0_dmg: {
    sheet: 'Aria',
    name: 'EXSpecialAttackInstantlyHooked_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackInstantlyHooked_0_dmg',
    },
  },
  EXSpecialAttackInstantlyHooked_0_daze: {
    sheet: 'Aria',
    name: 'EXSpecialAttackInstantlyHooked_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackInstantlyHooked_0_daze',
    },
  },
  EXSpecialAttackInstantlyHooked_0_anomBuildup: {
    sheet: 'Aria',
    name: 'EXSpecialAttackInstantlyHooked_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackInstantlyHooked_0_anomBuildup',
    },
  },
  ChainAttackDreamCollab_0_dmg: {
    sheet: 'Aria',
    name: 'ChainAttackDreamCollab_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackDreamCollab_0_dmg',
    },
  },
  ChainAttackDreamCollab_0_daze: {
    sheet: 'Aria',
    name: 'ChainAttackDreamCollab_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackDreamCollab_0_daze',
    },
  },
  ChainAttackDreamCollab_0_anomBuildup: {
    sheet: 'Aria',
    name: 'ChainAttackDreamCollab_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackDreamCollab_0_anomBuildup',
    },
  },
  Ultimate100Energy_0_dmg: {
    sheet: 'Aria',
    name: 'Ultimate100Energy_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'Ultimate100Energy_0_dmg',
    },
  },
  Ultimate100Energy_0_daze: {
    sheet: 'Aria',
    name: 'Ultimate100Energy_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'Ultimate100Energy_0_daze',
    },
  },
  Ultimate100Energy_0_anomBuildup: {
    sheet: 'Aria',
    name: 'Ultimate100Energy_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'Ultimate100Energy_0_anomBuildup',
    },
  },
  QuickAssistShatterFantasy_0_dmg: {
    sheet: 'Aria',
    name: 'QuickAssistShatterFantasy_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistShatterFantasy_0_dmg',
    },
  },
  QuickAssistShatterFantasy_0_daze: {
    sheet: 'Aria',
    name: 'QuickAssistShatterFantasy_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistShatterFantasy_0_daze',
    },
  },
  QuickAssistShatterFantasy_0_anomBuildup: {
    sheet: 'Aria',
    name: 'QuickAssistShatterFantasy_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistShatterFantasy_0_anomBuildup',
    },
  },
  DefensiveAssistClutchSave_0_dmg: {
    sheet: 'Aria',
    name: 'DefensiveAssistClutchSave_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistClutchSave_0_dmg',
    },
  },
  DefensiveAssistClutchSave_0_daze: {
    sheet: 'Aria',
    name: 'DefensiveAssistClutchSave_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistClutchSave_0_daze',
    },
  },
  DefensiveAssistClutchSave_0_anomBuildup: {
    sheet: 'Aria',
    name: 'DefensiveAssistClutchSave_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistClutchSave_0_anomBuildup',
    },
  },
  DefensiveAssistClutchSave_1_dmg: {
    sheet: 'Aria',
    name: 'DefensiveAssistClutchSave_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistClutchSave_1_dmg',
    },
  },
  DefensiveAssistClutchSave_1_daze: {
    sheet: 'Aria',
    name: 'DefensiveAssistClutchSave_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistClutchSave_1_daze',
    },
  },
  DefensiveAssistClutchSave_1_anomBuildup: {
    sheet: 'Aria',
    name: 'DefensiveAssistClutchSave_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistClutchSave_1_anomBuildup',
    },
  },
  DefensiveAssistClutchSave_2_dmg: {
    sheet: 'Aria',
    name: 'DefensiveAssistClutchSave_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistClutchSave_2_dmg',
    },
  },
  DefensiveAssistClutchSave_2_daze: {
    sheet: 'Aria',
    name: 'DefensiveAssistClutchSave_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistClutchSave_2_daze',
    },
  },
  DefensiveAssistClutchSave_2_anomBuildup: {
    sheet: 'Aria',
    name: 'DefensiveAssistClutchSave_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistClutchSave_2_anomBuildup',
    },
  },
  AssistFollowUpEncoreSong_0_dmg: {
    sheet: 'Aria',
    name: 'AssistFollowUpEncoreSong_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpEncoreSong_0_dmg',
    },
  },
  AssistFollowUpEncoreSong_0_daze: {
    sheet: 'Aria',
    name: 'AssistFollowUpEncoreSong_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpEncoreSong_0_daze',
    },
  },
  AssistFollowUpEncoreSong_0_anomBuildup: {
    sheet: 'Aria',
    name: 'AssistFollowUpEncoreSong_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Aria',
      attribute: 'ether',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpEncoreSong_0_anomBuildup',
    },
  },
} as const
