import { RarityKey } from './common'

export const allWeaponTypeKeys = ['sword', 'claymore', 'polearm', 'bow', 'catalyst'] as const
export type WeaponTypeKey = typeof allWeaponTypeKeys[number]

export const allWeaponSwordKeys = [
  'AmenomaKageuchi',
  'AquilaFavonia',
  'BlackcliffLongsword',
  'CinnabarSpindle',
  'CoolSteel',
  'KagotsurubeIsshin',
  'DarkIronSword',
  'DullBlade',
  'FavoniusSword',
  'FesteringDesire',
  'FilletBlade',
  'FreedomSworn',
  'HaranGeppakuFutsu',
  'HarbingerOfDawn',
  'IronSting',
  'KeyOfKhajNisut',
  'LightOfFoliarIncision',
  'LionsRoar',
  'MistsplitterReforged',
  'PrimordialJadeCutter',
  'PrototypeRancour',
  'RoyalLongsword',
  'SacrificialSword',
  'SapwoodBlade',
  'SilverSword',
  'SkyriderSword',
  'SkywardBlade',
  'SummitShaper',
  'SwordOfDescension',
  'TheAlleyFlash',
  'TheBlackSword',
  'TheFlute',
  'ToukabouShigure',
  'TravelersHandySword',
  'XiphosMoonlight',
] as const
export type WeaponSwordKey = typeof allWeaponSwordKeys[number]

export const allWeaponClaymoreKeys = [
  'Akuoumaru',
  'BeaconOfTheReedSea',
  'BlackcliffSlasher',
  'BloodtaintedGreatsword',
  'DebateClub',
  'FavoniusGreatsword',
  'FerrousShadow',
  'ForestRegalia',
  'KatsuragikiriNagamasa',
  'LithicBlade',
  'LuxuriousSeaLord',
  'MakhairaAquamarine',
  'OldMercsPal',
  'PrototypeArchaic',
  'Rainslasher',
  'RedhornStonethresher',
  'RoyalGreatsword',
  'SacrificialGreatsword',
  'SerpentSpine',
  'SkyriderGreatsword',
  'SkywardPride',
  'SnowTombedStarsilver',
  'SongOfBrokenPines',
  'TheBell',
  'TheUnforged',
  'WasterGreatsword',
  'Whiteblind',
  'WhiteIronGreatsword',
  'WolfsGravestone',
] as const
export type WeaponClaymoreKey = typeof allWeaponClaymoreKeys[number]

export const allWeaponPolearmKeys = [
  'BeginnersProtector',
  'BlackcliffPole',
  'BlackTassel',
  'CalamityQueller',
  'CrescentPike',
  'Deathmatch',
  'DragonsBane',
  'DragonspineSpear',
  'EngulfingLightning',
  'FavoniusLance',
  'Halberd',
  'IronPoint',
  'KitainCrossSpear',
  'LithicSpear',
  'MissiveWindspear',
  'Moonpiercer',
  'PrimordialJadeWingedSpear',
  'PrototypeStarglitter',
  'RoyalSpear',
  'SkywardSpine',
  'StaffOfHoma',
  'StaffOfTheScarletSands',
  'TheCatch',
  'VortexVanquisher',
  'WavebreakersFin',
  'WhiteTassel',
] as const
export type WeaponPoleArmKey = typeof allWeaponPolearmKeys[number]

export const allWeaponBowKeys = [
  'AlleyHunter',
  'AmosBow',
  'AquaSimulacra',
  'BlackcliffWarbow',
  'CompoundBow',
  'ElegyForTheEnd',
  'EndOfTheLine',
  'FadingTwilight',
  'FavoniusWarbow',
  'Hamayumi',
  'HuntersBow',
  'HuntersPath',
  'KingsSquire',
  'Messenger',
  'MitternachtsWaltz',
  'MouunsMoon',
  'PolarStar',
  'Predator',
  'PrototypeCrescent',
  'RavenBow',
  'RecurveBow',
  'RoyalBow',
  'Rust',
  'SacrificialBow',
  'SeasonedHuntersBow',
  'SharpshootersOath',
  'SkywardHarp',
  'Slingshot',
  'TheStringless',
  'TheViridescentHunt',
  'ThunderingPulse',
  'WindblumeOde',
] as const
export type WeaponBowKey = typeof allWeaponBowKeys[number]

export const allWeaponCatalystKeys = [
  'ApprenticesNotes',
  'AThousandFloatingDreams',
  'BlackcliffAgate',
  'DodocoTales',
  'EmeraldOrb',
  'EverlastingMoonglow',
  'EyeOfPerception',
  'FavoniusCodex',
  'Frostbearer',
  'FruitOfFulfillment',
  'HakushinRing',
  'KagurasVerity',
  'LostPrayerToTheSacredWinds',
  'MagicGuide',
  'MappaMare',
  'MemoryOfDust',
  'OathswornEye',
  'OtherworldlyStory',
  'PocketGrimoire',
  'PrototypeAmber',
  'RoyalGrimoire',
  'SacrificialFragments',
  'SkywardAtlas',
  'SolarPearl',
  'TheWidsith',
  'ThrillingTalesOfDragonSlayers',
  'TulaytullahsRemembrance',
  'TwinNephrite',
  'WanderingEvenstar',
  'WineAndSong',
] as const
export type WeaponCatalystKey = typeof allWeaponCatalystKeys[number]

export const allWeaponKeys = [
  ...allWeaponSwordKeys,
  ...allWeaponClaymoreKeys,
  ...allWeaponPolearmKeys,
  ...allWeaponBowKeys,
  ...allWeaponCatalystKeys,
] as const
export type WeaponKey = WeaponSwordKey | WeaponClaymoreKey | WeaponPoleArmKey | WeaponBowKey | WeaponCatalystKey

export const weaponMaxLevel: Record<RarityKey, number> = {
  1: 70,
  2: 70,
  3: 90,
  4: 90,
  5: 90,
} as const
