import { type AscensionKey, type RarityKey, validateLevelAsc } from './common'

export const allWeaponTypeKeys = [
  'sword',
  'claymore',
  'polearm',
  'bow',
  'catalyst',
] as const
export type WeaponTypeKey = (typeof allWeaponTypeKeys)[number]

export const allWeaponSwordKeys = [
  'Absolution',
  'AmenomaKageuchi',
  'AquilaFavonia',
  'AthameArtis',
  'Azurelight',
  'BlackcliffLongsword',
  'CalamityOfEshu',
  'CinnabarSpindle',
  'CoolSteel',
  'DarkIronSword',
  'DullBlade',
  'FavoniusSword',
  'FesteringDesire',
  'FilletBlade',
  'FinaleOfTheDeep',
  'FleuveCendreFerryman',
  'FluteOfEzpitzal',
  'FreedomSworn',
  'HaranGeppakuFutsu',
  'HarbingerOfDawn',
  'IronSting',
  'KagotsurubeIsshin',
  'KeyOfKhajNisut',
  'LightOfFoliarIncision',
  'LionsRoar',
  'MistsplitterReforged',
  'MoonweaversDawn',
  'PeakPatrolSong',
  'PrimordialJadeCutter',
  'PrototypeRancour',
  'RoyalLongsword',
  'SacrificialSword',
  'SapwoodBlade',
  'SerenitysCall',
  'SilverSword',
  'SkyriderSword',
  'SkywardBlade',
  'SplendorOfTranquilWaters',
  'SturdyBone',
  'SummitShaper',
  'SwordOfDescension',
  'SwordOfNarzissenkreuz',
  'TheAlleyFlash',
  'TheBlackSword',
  'TheDockhandsAssistant',
  'TheFlute',
  'ToukabouShigure',
  'TravelersHandySword',
  'UrakuMisugiri',
  'WolfFang',
  'XiphosMoonlight',
] as const
export type WeaponSwordKey = (typeof allWeaponSwordKeys)[number]

export const allWeaponClaymoreKeys = [
  'Akuoumaru',
  'AThousandBlazingSuns',
  'BeaconOfTheReedSea',
  'BlackcliffSlasher',
  'BloodtaintedGreatsword',
  'DebateClub',
  'EarthShaker',
  'FangOfTheMountainKing',
  'FavoniusGreatsword',
  'FerrousShadow',
  'FlameForgedInsight',
  'ForestRegalia',
  'FruitfulHook',
  'KatsuragikiriNagamasa',
  'LithicBlade',
  'LuxuriousSeaLord',
  'MailedFlower',
  'MakhairaAquamarine',
  'MasterKey',
  'OldMercsPal',
  'PortablePowerSaw',
  'PrototypeArchaic',
  'Rainslasher',
  'RedhornStonethresher',
  'RoyalGreatsword',
  'SacrificialGreatsword',
  'SerpentSpine',
  'SkyriderGreatsword',
  'SkywardPride',
  'SnowTombedStarsilver',
  'SongOfBrokenPines',
  'TalkingStick',
  'TheBell',
  'TheUnforged',
  'TidalShadow',
  'UltimateOverlordsMegaMagicSword',
  'Verdict',
  'WasterGreatsword',
  'Whiteblind',
  'WhiteIronGreatsword',
  'WolfsGravestone',
] as const
export type WeaponClaymoreKey = (typeof allWeaponClaymoreKeys)[number]

export const allWeaponPolearmKeys = [
  'BalladOfTheFjords',
  'BeginnersProtector',
  'BlackcliffPole',
  'BlackTassel',
  'BloodsoakedRuins',
  'CalamityQueller',
  'CrescentPike',
  'CrimsonMoonsSemblance',
  'Deathmatch',
  'DialoguesOfTheDesertSages',
  'DragonsBane',
  'DragonspineSpear',
  'EngulfingLightning',
  'FavoniusLance',
  'FootprintOfTheRainbow',
  'FracturedHalo',
  'Halberd',
  'IronPoint',
  'KitainCrossSpear',
  'LithicSpear',
  'LumidouceElegy',
  'MissiveWindspear',
  'Moonpiercer',
  'MountainBracingBolt',
  'PrimordialJadeWingedSpear',
  'ProspectorsDrill',
  'ProspectorsShovel',
  'PrototypeStarglitter',
  'RightfulReward',
  'RoyalSpear',
  'SacrificersStaff',
  'SkywardSpine',
  'StaffOfHoma',
  'StaffOfTheScarletSands',
  'SymphonistOfScents',
  'TamayurateiNoOhanashi',
  'TheCatch',
  'VortexVanquisher',
  'WavebreakersFin',
  'WhiteTassel',
] as const
export type WeaponPoleArmKey = (typeof allWeaponPolearmKeys)[number]

export const allWeaponBowKeys = [
  'AlleyHunter',
  'AmosBow',
  'AquaSimulacra',
  'AstralVulturesCrimsonPlumage',
  'BlackcliffWarbow',
  'ChainBreaker',
  'Cloudforged',
  'CompoundBow',
  'ElegyForTheEnd',
  'EndOfTheLine',
  'FadingTwilight',
  'FavoniusWarbow',
  'FlowerWreathedFeathers',
  'Hamayumi',
  'HuntersBow',
  'HuntersPath',
  'IbisPiercer',
  'KingsSquire',
  'Messenger',
  'MitternachtsWaltz',
  'MouunsMoon',
  'PolarStar',
  'Predator',
  'PrototypeCrescent',
  'RainbowSerpentsRainBow',
  'RangeGauge',
  'RavenBow',
  'RecurveBow',
  'RoyalBow',
  'Rust',
  'SacrificialBow',
  'ScionOfTheBlazingSun',
  'SeasonedHuntersBow',
  'SequenceOfSolitude',
  'SharpshootersOath',
  'SilvershowerHeartstrings',
  'SkywardHarp',
  'Slingshot',
  'SnareHook',
  'SongOfStillness',
  'TheDaybreakChronicles',
  'TheFirstGreatMagic',
  'TheStringless',
  'TheViridescentHunt',
  'ThunderingPulse',
  'WindblumeOde',
] as const
export type WeaponBowKey = (typeof allWeaponBowKeys)[number]

export const allWeaponCatalystKeys = [
  'ApprenticesNotes',
  'AshGravenDrinkingHorn',
  'AThousandFloatingDreams',
  'BalladOfTheBoundlessBlue',
  'BlackcliffAgate',
  'BlackmarrowLantern',
  'CashflowSupervision',
  'CranesEchoingCall',
  'DawningFrost',
  'DodocoTales',
  'EmeraldOrb',
  'EtherlightSpindlelute',
  'EverlastingMoonglow',
  'EyeOfPerception',
  'FavoniusCodex',
  'FlowingPurity',
  'Frostbearer',
  'FruitOfFulfillment',
  'HakushinRing',
  'JadefallsSplendor',
  'KagurasVerity',
  'LostPrayerToTheSacredWinds',
  'MagicGuide',
  'MappaMare',
  'MemoryOfDust',
  'NightweaversLookingGlass',
  'NocturnesCurtainCall',
  'OathswornEye',
  'OtherworldlyStory',
  'PocketGrimoire',
  'PrototypeAmber',
  'QuantumCatalyst',
  'ReliquaryOfTruth',
  'RingOfYaxche',
  'RoyalGrimoire',
  'SacrificialFragments',
  'SacrificialJade',
  'SkywardAtlas',
  'SolarPearl',
  'StarcallersWatch',
  'SunnyMorningSleepIn',
  'SurfsUp',
  'TheWidsith',
  'ThrillingTalesOfDragonSlayers',
  'TomeOfTheEternalFlow',
  'TulaytullahsRemembrance',
  'TwinNephrite',
  'VividNotions',
  'WanderingEvenstar',
  'WaveridingWhirl',
  'WineAndSong',
] as const
export type WeaponCatalystKey = (typeof allWeaponCatalystKeys)[number]

export const allWeaponKeys = [
  ...allWeaponSwordKeys,
  ...allWeaponClaymoreKeys,
  ...allWeaponPolearmKeys,
  ...allWeaponBowKeys,
  ...allWeaponCatalystKeys,
] as const
export type WeaponKey =
  | WeaponSwordKey
  | WeaponClaymoreKey
  | WeaponPoleArmKey
  | WeaponBowKey
  | WeaponCatalystKey

export const weaponMaxLevel: Record<RarityKey, number> = {
  1: 70,
  2: 70,
  3: 90,
  4: 90,
  5: 90,
} as const

export const weaponMaxAscension: Record<RarityKey, AscensionKey> = {
  1: 4,
  2: 4,
  3: 6,
  4: 6,
  5: 6,
} as const

export const allRefinementKeys = [1, 2, 3, 4, 5] as const
export type RefinementKey = (typeof allRefinementKeys)[number]

export const allWeaponSubstatKeys = [
  'atk_',
  'critDMG_',
  'critRate_',
  'def_',
  'eleMas',
  'enerRech_',
  'hp_',
  'physical_dmg_',
] as const
export type WeaponSubstatKey = (typeof allWeaponSubstatKeys)[number]

// Weapon global max level constant
const weaponGlobalMaxLevel = 90

export function validateWeaponLevelAsc(
  level: number,
  ascension: AscensionKey
): { level: number; ascension: AscensionKey } {
  return validateLevelAsc(level, ascension, weaponGlobalMaxLevel)
}
