// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Lucy',
    name: 'standardDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lucy',
      attribute: 'fire',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Lucy',
    name: 'anomalyDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_fire: {
    sheet: 'Lucy',
    name: 'disorderDmgInst_fire',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'disorder',
      name: 'disorderDmgInst_fire',
    },
  },
  vortexDmgInst_fire: {
    sheet: 'Lucy',
    name: 'vortexDmgInst_fire',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'vortex',
      name: 'vortexDmgInst_fire',
    },
  },
  abloomDmgInst: {
    sheet: 'Lucy',
    name: 'abloomDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Lucy',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lucy',
      attribute: 'fire',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Lucy',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lucy',
      attribute: 'fire',
      name: 'dazeInst',
    },
  },
  'BasicAttackLadysBat_0:standardDmg': {
    sheet: 'Lucy',
    name: 'BasicAttackLadysBat_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lucy',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackLadysBat_0',
    },
  },
  'BasicAttackLadysBat_0:dazeBuildup': {
    sheet: 'Lucy',
    name: 'BasicAttackLadysBat_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lucy',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackLadysBat_0',
    },
  },
  'BasicAttackLadysBat_0:anomBuildup': {
    sheet: 'Lucy',
    name: 'BasicAttackLadysBat_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lucy',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackLadysBat_0',
    },
  },
  'BasicAttackLadysBat_1:standardDmg': {
    sheet: 'Lucy',
    name: 'BasicAttackLadysBat_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lucy',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackLadysBat_1',
    },
  },
  'BasicAttackLadysBat_1:dazeBuildup': {
    sheet: 'Lucy',
    name: 'BasicAttackLadysBat_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lucy',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackLadysBat_1',
    },
  },
  'BasicAttackLadysBat_1:anomBuildup': {
    sheet: 'Lucy',
    name: 'BasicAttackLadysBat_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lucy',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackLadysBat_1',
    },
  },
  'BasicAttackLadysBat_2:standardDmg': {
    sheet: 'Lucy',
    name: 'BasicAttackLadysBat_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLadysBat_2',
    },
  },
  'BasicAttackLadysBat_2:dazeBuildup': {
    sheet: 'Lucy',
    name: 'BasicAttackLadysBat_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLadysBat_2',
    },
  },
  'BasicAttackLadysBat_2:anomBuildup': {
    sheet: 'Lucy',
    name: 'BasicAttackLadysBat_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLadysBat_2',
    },
  },
  'BasicAttackLadysBat_3:standardDmg': {
    sheet: 'Lucy',
    name: 'BasicAttackLadysBat_3:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lucy',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackLadysBat_3',
    },
  },
  'BasicAttackLadysBat_3:dazeBuildup': {
    sheet: 'Lucy',
    name: 'BasicAttackLadysBat_3:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lucy',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackLadysBat_3',
    },
  },
  'BasicAttackLadysBat_3:anomBuildup': {
    sheet: 'Lucy',
    name: 'BasicAttackLadysBat_3:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lucy',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackLadysBat_3',
    },
  },
  'BasicAttackLadysBat_4:standardDmg': {
    sheet: 'Lucy',
    name: 'BasicAttackLadysBat_4:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLadysBat_4',
    },
  },
  'BasicAttackLadysBat_4:dazeBuildup': {
    sheet: 'Lucy',
    name: 'BasicAttackLadysBat_4:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLadysBat_4',
    },
  },
  'BasicAttackLadysBat_4:anomBuildup': {
    sheet: 'Lucy',
    name: 'BasicAttackLadysBat_4:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLadysBat_4',
    },
  },
  'GuardBoarsToArms_0:standardDmg': {
    sheet: 'Lucy',
    name: 'GuardBoarsToArms_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lucy',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'GuardBoarsToArms_0',
    },
  },
  'GuardBoarsToArms_0:dazeBuildup': {
    sheet: 'Lucy',
    name: 'GuardBoarsToArms_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lucy',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'GuardBoarsToArms_0',
    },
  },
  'GuardBoarsToArms_0:anomBuildup': {
    sheet: 'Lucy',
    name: 'GuardBoarsToArms_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lucy',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'GuardBoarsToArms_0',
    },
  },
  'GuardBoarsToArms_1:standardDmg': {
    sheet: 'Lucy',
    name: 'GuardBoarsToArms_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lucy',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'GuardBoarsToArms_1',
    },
  },
  'GuardBoarsToArms_1:dazeBuildup': {
    sheet: 'Lucy',
    name: 'GuardBoarsToArms_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lucy',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'GuardBoarsToArms_1',
    },
  },
  'GuardBoarsToArms_1:anomBuildup': {
    sheet: 'Lucy',
    name: 'GuardBoarsToArms_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lucy',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'GuardBoarsToArms_1',
    },
  },
  'GuardBoarsToArms_2:standardDmg': {
    sheet: 'Lucy',
    name: 'GuardBoarsToArms_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lucy',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'GuardBoarsToArms_2',
    },
  },
  'GuardBoarsToArms_2:dazeBuildup': {
    sheet: 'Lucy',
    name: 'GuardBoarsToArms_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lucy',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'GuardBoarsToArms_2',
    },
  },
  'GuardBoarsToArms_2:anomBuildup': {
    sheet: 'Lucy',
    name: 'GuardBoarsToArms_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lucy',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'GuardBoarsToArms_2',
    },
  },
  'GuardBoarsSpinningSwing_0:standardDmg': {
    sheet: 'Lucy',
    name: 'GuardBoarsSpinningSwing_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lucy',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'GuardBoarsSpinningSwing_0',
    },
  },
  'GuardBoarsSpinningSwing_0:dazeBuildup': {
    sheet: 'Lucy',
    name: 'GuardBoarsSpinningSwing_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lucy',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'GuardBoarsSpinningSwing_0',
    },
  },
  'GuardBoarsSpinningSwing_0:anomBuildup': {
    sheet: 'Lucy',
    name: 'GuardBoarsSpinningSwing_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lucy',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'GuardBoarsSpinningSwing_0',
    },
  },
  'DashAttackFearlessBoar_0:standardDmg': {
    sheet: 'Lucy',
    name: 'DashAttackFearlessBoar_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lucy',
      damageType1: 'dash',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttackFearlessBoar_0',
    },
  },
  'DashAttackFearlessBoar_0:dazeBuildup': {
    sheet: 'Lucy',
    name: 'DashAttackFearlessBoar_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lucy',
      damageType1: 'dash',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttackFearlessBoar_0',
    },
  },
  'DashAttackFearlessBoar_0:anomBuildup': {
    sheet: 'Lucy',
    name: 'DashAttackFearlessBoar_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lucy',
      damageType1: 'dash',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttackFearlessBoar_0',
    },
  },
  'DodgeCounterReturningTusk_0:standardDmg': {
    sheet: 'Lucy',
    name: 'DodgeCounterReturningTusk_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterReturningTusk_0',
    },
  },
  'DodgeCounterReturningTusk_0:dazeBuildup': {
    sheet: 'Lucy',
    name: 'DodgeCounterReturningTusk_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterReturningTusk_0',
    },
  },
  'DodgeCounterReturningTusk_0:anomBuildup': {
    sheet: 'Lucy',
    name: 'DodgeCounterReturningTusk_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterReturningTusk_0',
    },
  },
  'SpecialAttackSolidHit_0:standardDmg': {
    sheet: 'Lucy',
    name: 'SpecialAttackSolidHit_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackSolidHit_0',
    },
  },
  'SpecialAttackSolidHit_0:dazeBuildup': {
    sheet: 'Lucy',
    name: 'SpecialAttackSolidHit_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackSolidHit_0',
    },
  },
  'SpecialAttackSolidHit_0:anomBuildup': {
    sheet: 'Lucy',
    name: 'SpecialAttackSolidHit_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackSolidHit_0',
    },
  },
  'SpecialAttackSolidHit_1:standardDmg': {
    sheet: 'Lucy',
    name: 'SpecialAttackSolidHit_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackSolidHit_1',
    },
  },
  'SpecialAttackSolidHit_1:dazeBuildup': {
    sheet: 'Lucy',
    name: 'SpecialAttackSolidHit_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackSolidHit_1',
    },
  },
  'SpecialAttackSolidHit_1:anomBuildup': {
    sheet: 'Lucy',
    name: 'SpecialAttackSolidHit_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackSolidHit_1',
    },
  },
  'EXSpecialAttackHomeRun_0:standardDmg': {
    sheet: 'Lucy',
    name: 'EXSpecialAttackHomeRun_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackHomeRun_0',
    },
  },
  'EXSpecialAttackHomeRun_0:dazeBuildup': {
    sheet: 'Lucy',
    name: 'EXSpecialAttackHomeRun_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackHomeRun_0',
    },
  },
  'EXSpecialAttackHomeRun_0:anomBuildup': {
    sheet: 'Lucy',
    name: 'EXSpecialAttackHomeRun_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackHomeRun_0',
    },
  },
  'EXSpecialAttackHomeRun_1:standardDmg': {
    sheet: 'Lucy',
    name: 'EXSpecialAttackHomeRun_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackHomeRun_1',
    },
  },
  'EXSpecialAttackHomeRun_1:dazeBuildup': {
    sheet: 'Lucy',
    name: 'EXSpecialAttackHomeRun_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackHomeRun_1',
    },
  },
  'EXSpecialAttackHomeRun_1:anomBuildup': {
    sheet: 'Lucy',
    name: 'EXSpecialAttackHomeRun_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackHomeRun_1',
    },
  },
  'ChainAttackGrandSlam_0:standardDmg': {
    sheet: 'Lucy',
    name: 'ChainAttackGrandSlam_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackGrandSlam_0',
    },
  },
  'ChainAttackGrandSlam_0:dazeBuildup': {
    sheet: 'Lucy',
    name: 'ChainAttackGrandSlam_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackGrandSlam_0',
    },
  },
  'ChainAttackGrandSlam_0:anomBuildup': {
    sheet: 'Lucy',
    name: 'ChainAttackGrandSlam_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackGrandSlam_0',
    },
  },
  'UltimateWalkOffHomeRun_0:standardDmg': {
    sheet: 'Lucy',
    name: 'UltimateWalkOffHomeRun_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateWalkOffHomeRun_0',
    },
  },
  'UltimateWalkOffHomeRun_0:dazeBuildup': {
    sheet: 'Lucy',
    name: 'UltimateWalkOffHomeRun_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateWalkOffHomeRun_0',
    },
  },
  'UltimateWalkOffHomeRun_0:anomBuildup': {
    sheet: 'Lucy',
    name: 'UltimateWalkOffHomeRun_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateWalkOffHomeRun_0',
    },
  },
  'QuickAssistHitByPitch_0:standardDmg': {
    sheet: 'Lucy',
    name: 'QuickAssistHitByPitch_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistHitByPitch_0',
    },
  },
  'QuickAssistHitByPitch_0:dazeBuildup': {
    sheet: 'Lucy',
    name: 'QuickAssistHitByPitch_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistHitByPitch_0',
    },
  },
  'QuickAssistHitByPitch_0:anomBuildup': {
    sheet: 'Lucy',
    name: 'QuickAssistHitByPitch_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistHitByPitch_0',
    },
  },
  'DefensiveAssistSafeOnBase_0:standardDmg': {
    sheet: 'Lucy',
    name: 'DefensiveAssistSafeOnBase_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistSafeOnBase_0',
    },
  },
  'DefensiveAssistSafeOnBase_0:dazeBuildup': {
    sheet: 'Lucy',
    name: 'DefensiveAssistSafeOnBase_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistSafeOnBase_0',
    },
  },
  'DefensiveAssistSafeOnBase_0:anomBuildup': {
    sheet: 'Lucy',
    name: 'DefensiveAssistSafeOnBase_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistSafeOnBase_0',
    },
  },
  'DefensiveAssistSafeOnBase_1:standardDmg': {
    sheet: 'Lucy',
    name: 'DefensiveAssistSafeOnBase_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistSafeOnBase_1',
    },
  },
  'DefensiveAssistSafeOnBase_1:dazeBuildup': {
    sheet: 'Lucy',
    name: 'DefensiveAssistSafeOnBase_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistSafeOnBase_1',
    },
  },
  'DefensiveAssistSafeOnBase_1:anomBuildup': {
    sheet: 'Lucy',
    name: 'DefensiveAssistSafeOnBase_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistSafeOnBase_1',
    },
  },
  'DefensiveAssistSafeOnBase_2:standardDmg': {
    sheet: 'Lucy',
    name: 'DefensiveAssistSafeOnBase_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistSafeOnBase_2',
    },
  },
  'DefensiveAssistSafeOnBase_2:dazeBuildup': {
    sheet: 'Lucy',
    name: 'DefensiveAssistSafeOnBase_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistSafeOnBase_2',
    },
  },
  'DefensiveAssistSafeOnBase_2:anomBuildup': {
    sheet: 'Lucy',
    name: 'DefensiveAssistSafeOnBase_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistSafeOnBase_2',
    },
  },
  'AssistFollowUpScoredARun_0:standardDmg': {
    sheet: 'Lucy',
    name: 'AssistFollowUpScoredARun_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpScoredARun_0',
    },
  },
  'AssistFollowUpScoredARun_0:dazeBuildup': {
    sheet: 'Lucy',
    name: 'AssistFollowUpScoredARun_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpScoredARun_0',
    },
  },
  'AssistFollowUpScoredARun_0:anomBuildup': {
    sheet: 'Lucy',
    name: 'AssistFollowUpScoredARun_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpScoredARun_0',
    },
  },
  m6_dmg: {
    sheet: 'Lucy',
    name: 'm6_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'elemental',
      name: 'm6_dmg',
    },
  },
} as const
