// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Lucy',
    name: 'standardDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'standardDmgBase',
      sheet: 'Lucy',
      attribute: 'fire',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Lucy',
    name: 'anomalyDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_fire: {
    sheet: 'Lucy',
    name: 'disorderDmgInst_fire',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'disorder',
      name: 'disorderDmgInst_fire',
    },
  },
  vortexDmgInst_fire: {
    sheet: 'Lucy',
    name: 'vortexDmgInst_fire',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'vortex',
      name: 'vortexDmgInst_fire',
    },
  },
  abloomDmgInst: {
    sheet: 'Lucy',
    name: 'abloomDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Lucy',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lucy',
      attribute: 'fire',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Lucy',
    name: 'dazeInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'dazeBuildupBase',
      sheet: 'Lucy',
      attribute: 'fire',
      name: 'dazeInst',
    },
  },
  BasicAttackLadysBat_0: {
    sheet: 'Lucy',
    name: 'BasicAttackLadysBat_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lucy',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackLadysBat_0',
    },
  },
  BasicAttackLadysBat_1: {
    sheet: 'Lucy',
    name: 'BasicAttackLadysBat_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lucy',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackLadysBat_1',
    },
  },
  BasicAttackLadysBat_2: {
    sheet: 'Lucy',
    name: 'BasicAttackLadysBat_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLadysBat_2',
    },
  },
  BasicAttackLadysBat_3: {
    sheet: 'Lucy',
    name: 'BasicAttackLadysBat_3',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lucy',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackLadysBat_3',
    },
  },
  BasicAttackLadysBat_4: {
    sheet: 'Lucy',
    name: 'BasicAttackLadysBat_4',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLadysBat_4',
    },
  },
  GuardBoarsToArms_0: {
    sheet: 'Lucy',
    name: 'GuardBoarsToArms_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lucy',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'GuardBoarsToArms_0',
    },
  },
  GuardBoarsToArms_1: {
    sheet: 'Lucy',
    name: 'GuardBoarsToArms_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lucy',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'GuardBoarsToArms_1',
    },
  },
  GuardBoarsToArms_2: {
    sheet: 'Lucy',
    name: 'GuardBoarsToArms_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lucy',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'GuardBoarsToArms_2',
    },
  },
  GuardBoarsSpinningSwing_0: {
    sheet: 'Lucy',
    name: 'GuardBoarsSpinningSwing_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lucy',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'GuardBoarsSpinningSwing_0',
    },
  },
  DashAttackFearlessBoar_0: {
    sheet: 'Lucy',
    name: 'DashAttackFearlessBoar_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lucy',
      damageType1: 'dash',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttackFearlessBoar_0',
    },
  },
  DodgeCounterReturningTusk_0: {
    sheet: 'Lucy',
    name: 'DodgeCounterReturningTusk_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterReturningTusk_0',
    },
  },
  SpecialAttackSolidHit_0: {
    sheet: 'Lucy',
    name: 'SpecialAttackSolidHit_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackSolidHit_0',
    },
  },
  SpecialAttackSolidHit_1: {
    sheet: 'Lucy',
    name: 'SpecialAttackSolidHit_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackSolidHit_1',
    },
  },
  EXSpecialAttackHomeRun_0: {
    sheet: 'Lucy',
    name: 'EXSpecialAttackHomeRun_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackHomeRun_0',
    },
  },
  EXSpecialAttackHomeRun_1: {
    sheet: 'Lucy',
    name: 'EXSpecialAttackHomeRun_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackHomeRun_1',
    },
  },
  ChainAttackGrandSlam_0: {
    sheet: 'Lucy',
    name: 'ChainAttackGrandSlam_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackGrandSlam_0',
    },
  },
  UltimateWalkOffHomeRun_0: {
    sheet: 'Lucy',
    name: 'UltimateWalkOffHomeRun_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateWalkOffHomeRun_0',
    },
  },
  QuickAssistHitByPitch_0: {
    sheet: 'Lucy',
    name: 'QuickAssistHitByPitch_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistHitByPitch_0',
    },
  },
  DefensiveAssistSafeOnBase_0: {
    sheet: 'Lucy',
    name: 'DefensiveAssistSafeOnBase_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistSafeOnBase_0',
    },
  },
  DefensiveAssistSafeOnBase_1: {
    sheet: 'Lucy',
    name: 'DefensiveAssistSafeOnBase_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistSafeOnBase_1',
    },
  },
  DefensiveAssistSafeOnBase_2: {
    sheet: 'Lucy',
    name: 'DefensiveAssistSafeOnBase_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistSafeOnBase_2',
    },
  },
  AssistFollowUpScoredARun_0: {
    sheet: 'Lucy',
    name: 'AssistFollowUpScoredARun_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpScoredARun_0',
    },
  },
  m6_dmg: {
    sheet: 'Lucy',
    name: 'm6_dmg',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'standardDmgBase',
      sheet: 'Lucy',
      attribute: 'fire',
      damageType1: 'elemental',
      name: 'm6_dmg',
    },
  },
} as const
