// WARNING: Generated file, do not modify
export const formulas = {
  sheerDmgInst: {
    sheet: 'Banyue',
    name: 'sheerDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'sheer',
      name: 'sheerDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Banyue',
    name: 'anomalyDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_fire: {
    sheet: 'Banyue',
    name: 'disorderDmgInst_fire',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'disorder',
      name: 'disorderDmgInst_fire',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Banyue',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Banyue',
      attribute: 'fire',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Banyue',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Banyue',
      attribute: 'fire',
      name: 'dazeInst',
    },
  },
  BasicAttackToweringPeaks_0_dmg: {
    sheet: 'Banyue',
    name: 'BasicAttackToweringPeaks_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackToweringPeaks_0_dmg',
    },
  },
  BasicAttackToweringPeaks_0_daze: {
    sheet: 'Banyue',
    name: 'BasicAttackToweringPeaks_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackToweringPeaks_0_daze',
    },
  },
  BasicAttackToweringPeaks_0_anomBuildup: {
    sheet: 'Banyue',
    name: 'BasicAttackToweringPeaks_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackToweringPeaks_0_anomBuildup',
    },
  },
  BasicAttackToweringPeaks_1_dmg: {
    sheet: 'Banyue',
    name: 'BasicAttackToweringPeaks_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackToweringPeaks_1_dmg',
    },
  },
  BasicAttackToweringPeaks_1_daze: {
    sheet: 'Banyue',
    name: 'BasicAttackToweringPeaks_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackToweringPeaks_1_daze',
    },
  },
  BasicAttackToweringPeaks_1_anomBuildup: {
    sheet: 'Banyue',
    name: 'BasicAttackToweringPeaks_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackToweringPeaks_1_anomBuildup',
    },
  },
  BasicAttackToweringPeaks_2_dmg: {
    sheet: 'Banyue',
    name: 'BasicAttackToweringPeaks_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackToweringPeaks_2_dmg',
    },
  },
  BasicAttackToweringPeaks_2_daze: {
    sheet: 'Banyue',
    name: 'BasicAttackToweringPeaks_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackToweringPeaks_2_daze',
    },
  },
  BasicAttackToweringPeaks_2_anomBuildup: {
    sheet: 'Banyue',
    name: 'BasicAttackToweringPeaks_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackToweringPeaks_2_anomBuildup',
    },
  },
  BasicAttackToweringPeaks_3_dmg: {
    sheet: 'Banyue',
    name: 'BasicAttackToweringPeaks_3_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackToweringPeaks_3_dmg',
    },
  },
  BasicAttackToweringPeaks_3_daze: {
    sheet: 'Banyue',
    name: 'BasicAttackToweringPeaks_3_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackToweringPeaks_3_daze',
    },
  },
  BasicAttackToweringPeaks_3_anomBuildup: {
    sheet: 'Banyue',
    name: 'BasicAttackToweringPeaks_3_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackToweringPeaks_3_anomBuildup',
    },
  },
  BasicAttackMajesticSummit_0_dmg: {
    sheet: 'Banyue',
    name: 'BasicAttackMajesticSummit_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackMajesticSummit_0_dmg',
    },
  },
  BasicAttackMajesticSummit_0_daze: {
    sheet: 'Banyue',
    name: 'BasicAttackMajesticSummit_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackMajesticSummit_0_daze',
    },
  },
  BasicAttackMajesticSummit_0_anomBuildup: {
    sheet: 'Banyue',
    name: 'BasicAttackMajesticSummit_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackMajesticSummit_0_anomBuildup',
    },
  },
  BasicAttackMajesticSummit_1_dmg: {
    sheet: 'Banyue',
    name: 'BasicAttackMajesticSummit_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackMajesticSummit_1_dmg',
    },
  },
  BasicAttackMajesticSummit_1_daze: {
    sheet: 'Banyue',
    name: 'BasicAttackMajesticSummit_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackMajesticSummit_1_daze',
    },
  },
  BasicAttackMajesticSummit_1_anomBuildup: {
    sheet: 'Banyue',
    name: 'BasicAttackMajesticSummit_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackMajesticSummit_1_anomBuildup',
    },
  },
  BasicAttackMajesticSummit_2_dmg: {
    sheet: 'Banyue',
    name: 'BasicAttackMajesticSummit_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackMajesticSummit_2_dmg',
    },
  },
  BasicAttackMajesticSummit_2_daze: {
    sheet: 'Banyue',
    name: 'BasicAttackMajesticSummit_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackMajesticSummit_2_daze',
    },
  },
  BasicAttackMajesticSummit_2_anomBuildup: {
    sheet: 'Banyue',
    name: 'BasicAttackMajesticSummit_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackMajesticSummit_2_anomBuildup',
    },
  },
  BasicAttackMajesticSummit_3_dmg: {
    sheet: 'Banyue',
    name: 'BasicAttackMajesticSummit_3_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackMajesticSummit_3_dmg',
    },
  },
  BasicAttackMajesticSummit_3_daze: {
    sheet: 'Banyue',
    name: 'BasicAttackMajesticSummit_3_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackMajesticSummit_3_daze',
    },
  },
  BasicAttackMajesticSummit_3_anomBuildup: {
    sheet: 'Banyue',
    name: 'BasicAttackMajesticSummit_3_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackMajesticSummit_3_anomBuildup',
    },
  },
  BasicAttackImmolate_0_dmg: {
    sheet: 'Banyue',
    name: 'BasicAttackImmolate_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackImmolate_0_dmg',
    },
  },
  BasicAttackImmolate_0_daze: {
    sheet: 'Banyue',
    name: 'BasicAttackImmolate_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackImmolate_0_daze',
    },
  },
  BasicAttackImmolate_0_anomBuildup: {
    sheet: 'Banyue',
    name: 'BasicAttackImmolate_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackImmolate_0_anomBuildup',
    },
  },
  BasicAttackTopplingMountain_0_dmg: {
    sheet: 'Banyue',
    name: 'BasicAttackTopplingMountain_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTopplingMountain_0_dmg',
    },
  },
  BasicAttackTopplingMountain_0_daze: {
    sheet: 'Banyue',
    name: 'BasicAttackTopplingMountain_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTopplingMountain_0_daze',
    },
  },
  BasicAttackTopplingMountain_0_anomBuildup: {
    sheet: 'Banyue',
    name: 'BasicAttackTopplingMountain_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackTopplingMountain_0_anomBuildup',
    },
  },
  BasicAttackCrushingPeaks_0_dmg: {
    sheet: 'Banyue',
    name: 'BasicAttackCrushingPeaks_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackCrushingPeaks_0_dmg',
    },
  },
  BasicAttackCrushingPeaks_0_daze: {
    sheet: 'Banyue',
    name: 'BasicAttackCrushingPeaks_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackCrushingPeaks_0_daze',
    },
  },
  BasicAttackCrushingPeaks_0_anomBuildup: {
    sheet: 'Banyue',
    name: 'BasicAttackCrushingPeaks_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackCrushingPeaks_0_anomBuildup',
    },
  },
  DodgeImmovableMountain_0_dmg: {
    sheet: 'Banyue',
    name: 'DodgeImmovableMountain_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeImmovableMountain_0_dmg',
    },
  },
  DodgeImmovableMountain_0_daze: {
    sheet: 'Banyue',
    name: 'DodgeImmovableMountain_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeImmovableMountain_0_daze',
    },
  },
  DodgeImmovableMountain_0_anomBuildup: {
    sheet: 'Banyue',
    name: 'DodgeImmovableMountain_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeImmovableMountain_0_anomBuildup',
    },
  },
  DashAttackScatteringSands_0_dmg: {
    sheet: 'Banyue',
    name: 'DashAttackScatteringSands_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackScatteringSands_0_dmg',
    },
  },
  DashAttackScatteringSands_0_daze: {
    sheet: 'Banyue',
    name: 'DashAttackScatteringSands_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackScatteringSands_0_daze',
    },
  },
  DashAttackScatteringSands_0_anomBuildup: {
    sheet: 'Banyue',
    name: 'DashAttackScatteringSands_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackScatteringSands_0_anomBuildup',
    },
  },
  DodgeCounterStoneburst_0_dmg: {
    sheet: 'Banyue',
    name: 'DodgeCounterStoneburst_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterStoneburst_0_dmg',
    },
  },
  DodgeCounterStoneburst_0_daze: {
    sheet: 'Banyue',
    name: 'DodgeCounterStoneburst_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterStoneburst_0_daze',
    },
  },
  DodgeCounterStoneburst_0_anomBuildup: {
    sheet: 'Banyue',
    name: 'DodgeCounterStoneburst_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterStoneburst_0_anomBuildup',
    },
  },
  EXSpecialAttackMountainTremor_0_dmg: {
    sheet: 'Banyue',
    name: 'EXSpecialAttackMountainTremor_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackMountainTremor_0_dmg',
    },
  },
  EXSpecialAttackMountainTremor_0_daze: {
    sheet: 'Banyue',
    name: 'EXSpecialAttackMountainTremor_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackMountainTremor_0_daze',
    },
  },
  EXSpecialAttackMountainTremor_0_anomBuildup: {
    sheet: 'Banyue',
    name: 'EXSpecialAttackMountainTremor_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackMountainTremor_0_anomBuildup',
    },
  },
  EXSpecialAttackEarthShaker_0_dmg: {
    sheet: 'Banyue',
    name: 'EXSpecialAttackEarthShaker_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackEarthShaker_0_dmg',
    },
  },
  EXSpecialAttackEarthShaker_0_daze: {
    sheet: 'Banyue',
    name: 'EXSpecialAttackEarthShaker_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackEarthShaker_0_daze',
    },
  },
  EXSpecialAttackEarthShaker_0_anomBuildup: {
    sheet: 'Banyue',
    name: 'EXSpecialAttackEarthShaker_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackEarthShaker_0_anomBuildup',
    },
  },
  EXSpecialAttackLionsRoar_0_dmg: {
    sheet: 'Banyue',
    name: 'EXSpecialAttackLionsRoar_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackLionsRoar_0_dmg',
    },
  },
  EXSpecialAttackLionsRoar_0_daze: {
    sheet: 'Banyue',
    name: 'EXSpecialAttackLionsRoar_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackLionsRoar_0_daze',
    },
  },
  EXSpecialAttackLionsRoar_0_anomBuildup: {
    sheet: 'Banyue',
    name: 'EXSpecialAttackLionsRoar_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackLionsRoar_0_anomBuildup',
    },
  },
  EXSpecialAttackOnesPath_0_dmg: {
    sheet: 'Banyue',
    name: 'EXSpecialAttackOnesPath_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackOnesPath_0_dmg',
    },
  },
  EXSpecialAttackOnesPath_0_daze: {
    sheet: 'Banyue',
    name: 'EXSpecialAttackOnesPath_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackOnesPath_0_daze',
    },
  },
  EXSpecialAttackOnesPath_0_anomBuildup: {
    sheet: 'Banyue',
    name: 'EXSpecialAttackOnesPath_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackOnesPath_0_anomBuildup',
    },
  },
  EXSpecialAttackLionsRoarWrath_0_dmg: {
    sheet: 'Banyue',
    name: 'EXSpecialAttackLionsRoarWrath_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackLionsRoarWrath_0_dmg',
    },
  },
  EXSpecialAttackLionsRoarWrath_0_daze: {
    sheet: 'Banyue',
    name: 'EXSpecialAttackLionsRoarWrath_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackLionsRoarWrath_0_daze',
    },
  },
  EXSpecialAttackLionsRoarWrath_0_anomBuildup: {
    sheet: 'Banyue',
    name: 'EXSpecialAttackLionsRoarWrath_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackLionsRoarWrath_0_anomBuildup',
    },
  },
  EXSpecialAttackMountainTremorWrath_0_dmg: {
    sheet: 'Banyue',
    name: 'EXSpecialAttackMountainTremorWrath_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackMountainTremorWrath_0_dmg',
    },
  },
  EXSpecialAttackMountainTremorWrath_0_daze: {
    sheet: 'Banyue',
    name: 'EXSpecialAttackMountainTremorWrath_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackMountainTremorWrath_0_daze',
    },
  },
  EXSpecialAttackMountainTremorWrath_0_anomBuildup: {
    sheet: 'Banyue',
    name: 'EXSpecialAttackMountainTremorWrath_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackMountainTremorWrath_0_anomBuildup',
    },
  },
  ChainAttackBlazingWrath_0_dmg: {
    sheet: 'Banyue',
    name: 'ChainAttackBlazingWrath_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackBlazingWrath_0_dmg',
    },
  },
  ChainAttackBlazingWrath_0_daze: {
    sheet: 'Banyue',
    name: 'ChainAttackBlazingWrath_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackBlazingWrath_0_daze',
    },
  },
  ChainAttackBlazingWrath_0_anomBuildup: {
    sheet: 'Banyue',
    name: 'ChainAttackBlazingWrath_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackBlazingWrath_0_anomBuildup',
    },
  },
  UltimateTheWorldTrembles_0_dmg: {
    sheet: 'Banyue',
    name: 'UltimateTheWorldTrembles_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateTheWorldTrembles_0_dmg',
    },
  },
  UltimateTheWorldTrembles_0_daze: {
    sheet: 'Banyue',
    name: 'UltimateTheWorldTrembles_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateTheWorldTrembles_0_daze',
    },
  },
  UltimateTheWorldTrembles_0_anomBuildup: {
    sheet: 'Banyue',
    name: 'UltimateTheWorldTrembles_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateTheWorldTrembles_0_anomBuildup',
    },
  },
  QuickAssistBatholith_0_dmg: {
    sheet: 'Banyue',
    name: 'QuickAssistBatholith_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistBatholith_0_dmg',
    },
  },
  QuickAssistBatholith_0_daze: {
    sheet: 'Banyue',
    name: 'QuickAssistBatholith_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistBatholith_0_daze',
    },
  },
  QuickAssistBatholith_0_anomBuildup: {
    sheet: 'Banyue',
    name: 'QuickAssistBatholith_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistBatholith_0_anomBuildup',
    },
  },
  DefensiveAssistIronBastion_0_dmg: {
    sheet: 'Banyue',
    name: 'DefensiveAssistIronBastion_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistIronBastion_0_dmg',
    },
  },
  DefensiveAssistIronBastion_0_daze: {
    sheet: 'Banyue',
    name: 'DefensiveAssistIronBastion_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistIronBastion_0_daze',
    },
  },
  DefensiveAssistIronBastion_0_anomBuildup: {
    sheet: 'Banyue',
    name: 'DefensiveAssistIronBastion_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistIronBastion_0_anomBuildup',
    },
  },
  DefensiveAssistIronBastion_1_dmg: {
    sheet: 'Banyue',
    name: 'DefensiveAssistIronBastion_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistIronBastion_1_dmg',
    },
  },
  DefensiveAssistIronBastion_1_daze: {
    sheet: 'Banyue',
    name: 'DefensiveAssistIronBastion_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistIronBastion_1_daze',
    },
  },
  DefensiveAssistIronBastion_1_anomBuildup: {
    sheet: 'Banyue',
    name: 'DefensiveAssistIronBastion_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistIronBastion_1_anomBuildup',
    },
  },
  DefensiveAssistIronBastion_2_dmg: {
    sheet: 'Banyue',
    name: 'DefensiveAssistIronBastion_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistIronBastion_2_dmg',
    },
  },
  DefensiveAssistIronBastion_2_daze: {
    sheet: 'Banyue',
    name: 'DefensiveAssistIronBastion_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistIronBastion_2_daze',
    },
  },
  DefensiveAssistIronBastion_2_anomBuildup: {
    sheet: 'Banyue',
    name: 'DefensiveAssistIronBastion_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistIronBastion_2_anomBuildup',
    },
  },
  AssistFollowUpLoftyAscent_0_dmg: {
    sheet: 'Banyue',
    name: 'AssistFollowUpLoftyAscent_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpLoftyAscent_0_dmg',
    },
  },
  AssistFollowUpLoftyAscent_0_daze: {
    sheet: 'Banyue',
    name: 'AssistFollowUpLoftyAscent_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpLoftyAscent_0_daze',
    },
  },
  AssistFollowUpLoftyAscent_0_anomBuildup: {
    sheet: 'Banyue',
    name: 'AssistFollowUpLoftyAscent_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpLoftyAscent_0_anomBuildup',
    },
  },
  AssistFollowUpPierceHeavens_0_dmg: {
    sheet: 'Banyue',
    name: 'AssistFollowUpPierceHeavens_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpPierceHeavens_0_dmg',
    },
  },
  AssistFollowUpPierceHeavens_0_daze: {
    sheet: 'Banyue',
    name: 'AssistFollowUpPierceHeavens_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpPierceHeavens_0_daze',
    },
  },
  AssistFollowUpPierceHeavens_0_anomBuildup: {
    sheet: 'Banyue',
    name: 'AssistFollowUpPierceHeavens_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Banyue',
      attribute: 'fire',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpPierceHeavens_0_anomBuildup',
    },
  },
} as const
