// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Miyabi',
    name: 'standardDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Miyabi',
      attribute: 'ice',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Miyabi',
    name: 'anomalyDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_frost: {
    sheet: 'Miyabi',
    name: 'disorderDmgInst_frost',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'disorder',
      name: 'disorderDmgInst_frost',
    },
  },
  vortexDmgInst_frost: {
    sheet: 'Miyabi',
    name: 'vortexDmgInst_frost',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'vortex',
      name: 'vortexDmgInst_frost',
    },
  },
  abloomDmgInst: {
    sheet: 'Miyabi',
    name: 'abloomDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Miyabi',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Miyabi',
      attribute: 'ice',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Miyabi',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Miyabi',
      attribute: 'ice',
      name: 'dazeInst',
    },
  },
  'BasicAttackKazahana_0:standardDmg': {
    sheet: 'Miyabi',
    name: 'BasicAttackKazahana_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Miyabi',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackKazahana_0',
    },
  },
  'BasicAttackKazahana_0:dazeBuildup': {
    sheet: 'Miyabi',
    name: 'BasicAttackKazahana_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Miyabi',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackKazahana_0',
    },
  },
  'BasicAttackKazahana_0:anomBuildup': {
    sheet: 'Miyabi',
    name: 'BasicAttackKazahana_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Miyabi',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackKazahana_0',
    },
  },
  'BasicAttackKazahana_1:standardDmg': {
    sheet: 'Miyabi',
    name: 'BasicAttackKazahana_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Miyabi',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackKazahana_1',
    },
  },
  'BasicAttackKazahana_1:dazeBuildup': {
    sheet: 'Miyabi',
    name: 'BasicAttackKazahana_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Miyabi',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackKazahana_1',
    },
  },
  'BasicAttackKazahana_1:anomBuildup': {
    sheet: 'Miyabi',
    name: 'BasicAttackKazahana_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Miyabi',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackKazahana_1',
    },
  },
  'BasicAttackKazahana_2:standardDmg': {
    sheet: 'Miyabi',
    name: 'BasicAttackKazahana_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackKazahana_2',
    },
  },
  'BasicAttackKazahana_2:dazeBuildup': {
    sheet: 'Miyabi',
    name: 'BasicAttackKazahana_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackKazahana_2',
    },
  },
  'BasicAttackKazahana_2:anomBuildup': {
    sheet: 'Miyabi',
    name: 'BasicAttackKazahana_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackKazahana_2',
    },
  },
  'BasicAttackKazahana_3:standardDmg': {
    sheet: 'Miyabi',
    name: 'BasicAttackKazahana_3:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackKazahana_3',
    },
  },
  'BasicAttackKazahana_3:dazeBuildup': {
    sheet: 'Miyabi',
    name: 'BasicAttackKazahana_3:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackKazahana_3',
    },
  },
  'BasicAttackKazahana_3:anomBuildup': {
    sheet: 'Miyabi',
    name: 'BasicAttackKazahana_3:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackKazahana_3',
    },
  },
  'BasicAttackKazahana_4:standardDmg': {
    sheet: 'Miyabi',
    name: 'BasicAttackKazahana_4:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackKazahana_4',
    },
  },
  'BasicAttackKazahana_4:dazeBuildup': {
    sheet: 'Miyabi',
    name: 'BasicAttackKazahana_4:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackKazahana_4',
    },
  },
  'BasicAttackKazahana_4:anomBuildup': {
    sheet: 'Miyabi',
    name: 'BasicAttackKazahana_4:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackKazahana_4',
    },
  },
  'BasicAttackShimotsuki_0:standardDmg': {
    sheet: 'Miyabi',
    name: 'BasicAttackShimotsuki_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackShimotsuki_0',
    },
  },
  'BasicAttackShimotsuki_0:dazeBuildup': {
    sheet: 'Miyabi',
    name: 'BasicAttackShimotsuki_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackShimotsuki_0',
    },
  },
  'BasicAttackShimotsuki_0:anomBuildup': {
    sheet: 'Miyabi',
    name: 'BasicAttackShimotsuki_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackShimotsuki_0',
    },
  },
  'BasicAttackShimotsuki_1:standardDmg': {
    sheet: 'Miyabi',
    name: 'BasicAttackShimotsuki_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackShimotsuki_1',
    },
  },
  'BasicAttackShimotsuki_1:dazeBuildup': {
    sheet: 'Miyabi',
    name: 'BasicAttackShimotsuki_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackShimotsuki_1',
    },
  },
  'BasicAttackShimotsuki_1:anomBuildup': {
    sheet: 'Miyabi',
    name: 'BasicAttackShimotsuki_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackShimotsuki_1',
    },
  },
  'BasicAttackShimotsuki_2:standardDmg': {
    sheet: 'Miyabi',
    name: 'BasicAttackShimotsuki_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackShimotsuki_2',
    },
  },
  'BasicAttackShimotsuki_2:dazeBuildup': {
    sheet: 'Miyabi',
    name: 'BasicAttackShimotsuki_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackShimotsuki_2',
    },
  },
  'BasicAttackShimotsuki_2:anomBuildup': {
    sheet: 'Miyabi',
    name: 'BasicAttackShimotsuki_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackShimotsuki_2',
    },
  },
  'DashAttackFuyubachi_0:standardDmg': {
    sheet: 'Miyabi',
    name: 'DashAttackFuyubachi_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Miyabi',
      damageType1: 'dash',
      attribute: 'physical',
      skillType1: 'dodgeSkill',
      name: 'DashAttackFuyubachi_0',
    },
  },
  'DashAttackFuyubachi_0:dazeBuildup': {
    sheet: 'Miyabi',
    name: 'DashAttackFuyubachi_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Miyabi',
      damageType1: 'dash',
      attribute: 'physical',
      skillType1: 'dodgeSkill',
      name: 'DashAttackFuyubachi_0',
    },
  },
  'DashAttackFuyubachi_0:anomBuildup': {
    sheet: 'Miyabi',
    name: 'DashAttackFuyubachi_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Miyabi',
      damageType1: 'dash',
      attribute: 'physical',
      skillType1: 'dodgeSkill',
      name: 'DashAttackFuyubachi_0',
    },
  },
  'DodgeCounterKanSuzume_0:standardDmg': {
    sheet: 'Miyabi',
    name: 'DodgeCounterKanSuzume_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'dodgeCounter',
      skillType1: 'dodgeSkill',
      name: 'DodgeCounterKanSuzume_0',
    },
  },
  'DodgeCounterKanSuzume_0:dazeBuildup': {
    sheet: 'Miyabi',
    name: 'DodgeCounterKanSuzume_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'dodgeCounter',
      skillType1: 'dodgeSkill',
      name: 'DodgeCounterKanSuzume_0',
    },
  },
  'DodgeCounterKanSuzume_0:anomBuildup': {
    sheet: 'Miyabi',
    name: 'DodgeCounterKanSuzume_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'dodgeCounter',
      skillType1: 'dodgeSkill',
      name: 'DodgeCounterKanSuzume_0',
    },
  },
  'SpecialAttackMiyuki_0:standardDmg': {
    sheet: 'Miyabi',
    name: 'SpecialAttackMiyuki_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackMiyuki_0',
    },
  },
  'SpecialAttackMiyuki_0:dazeBuildup': {
    sheet: 'Miyabi',
    name: 'SpecialAttackMiyuki_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackMiyuki_0',
    },
  },
  'SpecialAttackMiyuki_0:anomBuildup': {
    sheet: 'Miyabi',
    name: 'SpecialAttackMiyuki_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackMiyuki_0',
    },
  },
  'EXSpecialAttackHisetsu_0:standardDmg': {
    sheet: 'Miyabi',
    name: 'EXSpecialAttackHisetsu_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackHisetsu_0',
    },
  },
  'EXSpecialAttackHisetsu_0:dazeBuildup': {
    sheet: 'Miyabi',
    name: 'EXSpecialAttackHisetsu_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackHisetsu_0',
    },
  },
  'EXSpecialAttackHisetsu_0:anomBuildup': {
    sheet: 'Miyabi',
    name: 'EXSpecialAttackHisetsu_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackHisetsu_0',
    },
  },
  'EXSpecialAttackHisetsu_1:standardDmg': {
    sheet: 'Miyabi',
    name: 'EXSpecialAttackHisetsu_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackHisetsu_1',
    },
  },
  'EXSpecialAttackHisetsu_1:dazeBuildup': {
    sheet: 'Miyabi',
    name: 'EXSpecialAttackHisetsu_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackHisetsu_1',
    },
  },
  'EXSpecialAttackHisetsu_1:anomBuildup': {
    sheet: 'Miyabi',
    name: 'EXSpecialAttackHisetsu_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackHisetsu_1',
    },
  },
  'EXSpecialAttackHisetsu_2:standardDmg': {
    sheet: 'Miyabi',
    name: 'EXSpecialAttackHisetsu_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackHisetsu_2',
    },
  },
  'EXSpecialAttackHisetsu_2:dazeBuildup': {
    sheet: 'Miyabi',
    name: 'EXSpecialAttackHisetsu_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackHisetsu_2',
    },
  },
  'EXSpecialAttackHisetsu_2:anomBuildup': {
    sheet: 'Miyabi',
    name: 'EXSpecialAttackHisetsu_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackHisetsu_2',
    },
  },
  'EXSpecialAttackHisetsu_3:standardDmg': {
    sheet: 'Miyabi',
    name: 'EXSpecialAttackHisetsu_3:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackHisetsu_3',
    },
  },
  'EXSpecialAttackHisetsu_3:dazeBuildup': {
    sheet: 'Miyabi',
    name: 'EXSpecialAttackHisetsu_3:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackHisetsu_3',
    },
  },
  'EXSpecialAttackHisetsu_3:anomBuildup': {
    sheet: 'Miyabi',
    name: 'EXSpecialAttackHisetsu_3:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackHisetsu_3',
    },
  },
  'ChainAttackSpringsCall_0:standardDmg': {
    sheet: 'Miyabi',
    name: 'ChainAttackSpringsCall_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'chain',
      skillType1: 'chainSkill',
      name: 'ChainAttackSpringsCall_0',
    },
  },
  'ChainAttackSpringsCall_0:dazeBuildup': {
    sheet: 'Miyabi',
    name: 'ChainAttackSpringsCall_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'chain',
      skillType1: 'chainSkill',
      name: 'ChainAttackSpringsCall_0',
    },
  },
  'ChainAttackSpringsCall_0:anomBuildup': {
    sheet: 'Miyabi',
    name: 'ChainAttackSpringsCall_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'chain',
      skillType1: 'chainSkill',
      name: 'ChainAttackSpringsCall_0',
    },
  },
  'UltimateLingeringSnow_0:standardDmg': {
    sheet: 'Miyabi',
    name: 'UltimateLingeringSnow_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'ult',
      skillType1: 'chainSkill',
      name: 'UltimateLingeringSnow_0',
    },
  },
  'UltimateLingeringSnow_0:dazeBuildup': {
    sheet: 'Miyabi',
    name: 'UltimateLingeringSnow_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'ult',
      skillType1: 'chainSkill',
      name: 'UltimateLingeringSnow_0',
    },
  },
  'UltimateLingeringSnow_0:anomBuildup': {
    sheet: 'Miyabi',
    name: 'UltimateLingeringSnow_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'ult',
      skillType1: 'chainSkill',
      name: 'UltimateLingeringSnow_0',
    },
  },
  'QuickAssistDancingPetals_0:standardDmg': {
    sheet: 'Miyabi',
    name: 'QuickAssistDancingPetals_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'quickAssist',
      skillType1: 'assistSkill',
      name: 'QuickAssistDancingPetals_0',
    },
  },
  'QuickAssistDancingPetals_0:dazeBuildup': {
    sheet: 'Miyabi',
    name: 'QuickAssistDancingPetals_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'quickAssist',
      skillType1: 'assistSkill',
      name: 'QuickAssistDancingPetals_0',
    },
  },
  'QuickAssistDancingPetals_0:anomBuildup': {
    sheet: 'Miyabi',
    name: 'QuickAssistDancingPetals_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'quickAssist',
      skillType1: 'assistSkill',
      name: 'QuickAssistDancingPetals_0',
    },
  },
  'DefensiveAssistDriftingPetals_0:standardDmg': {
    sheet: 'Miyabi',
    name: 'DefensiveAssistDriftingPetals_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistDriftingPetals_0',
    },
  },
  'DefensiveAssistDriftingPetals_0:dazeBuildup': {
    sheet: 'Miyabi',
    name: 'DefensiveAssistDriftingPetals_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistDriftingPetals_0',
    },
  },
  'DefensiveAssistDriftingPetals_0:anomBuildup': {
    sheet: 'Miyabi',
    name: 'DefensiveAssistDriftingPetals_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistDriftingPetals_0',
    },
  },
  'DefensiveAssistDriftingPetals_1:standardDmg': {
    sheet: 'Miyabi',
    name: 'DefensiveAssistDriftingPetals_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistDriftingPetals_1',
    },
  },
  'DefensiveAssistDriftingPetals_1:dazeBuildup': {
    sheet: 'Miyabi',
    name: 'DefensiveAssistDriftingPetals_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistDriftingPetals_1',
    },
  },
  'DefensiveAssistDriftingPetals_1:anomBuildup': {
    sheet: 'Miyabi',
    name: 'DefensiveAssistDriftingPetals_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistDriftingPetals_1',
    },
  },
  'DefensiveAssistDriftingPetals_2:standardDmg': {
    sheet: 'Miyabi',
    name: 'DefensiveAssistDriftingPetals_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistDriftingPetals_2',
    },
  },
  'DefensiveAssistDriftingPetals_2:dazeBuildup': {
    sheet: 'Miyabi',
    name: 'DefensiveAssistDriftingPetals_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistDriftingPetals_2',
    },
  },
  'DefensiveAssistDriftingPetals_2:anomBuildup': {
    sheet: 'Miyabi',
    name: 'DefensiveAssistDriftingPetals_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistDriftingPetals_2',
    },
  },
  'AssistFollowUpFallingPetals_0:standardDmg': {
    sheet: 'Miyabi',
    name: 'AssistFollowUpFallingPetals_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'assistFollowUp',
      skillType1: 'assistSkill',
      name: 'AssistFollowUpFallingPetals_0',
    },
  },
  'AssistFollowUpFallingPetals_0:dazeBuildup': {
    sheet: 'Miyabi',
    name: 'AssistFollowUpFallingPetals_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'assistFollowUp',
      skillType1: 'assistSkill',
      name: 'AssistFollowUpFallingPetals_0',
    },
  },
  'AssistFollowUpFallingPetals_0:anomBuildup': {
    sheet: 'Miyabi',
    name: 'AssistFollowUpFallingPetals_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'assistFollowUp',
      skillType1: 'assistSkill',
      name: 'AssistFollowUpFallingPetals_0',
    },
  },
  core_frostburnBreak_dmg: {
    sheet: 'Miyabi',
    name: 'core_frostburnBreak_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Miyabi',
      attribute: 'ice',
      damageType1: 'anomaly',
      name: 'core_frostburnBreak_dmg',
    },
  },
} as const
