// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Yanagi',
    name: 'standardDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yanagi',
      attribute: 'electric',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Yanagi',
    name: 'anomalyDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_electric: {
    sheet: 'Yanagi',
    name: 'disorderDmgInst_electric',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'disorder',
      name: 'disorderDmgInst_electric',
    },
  },
  vortexDmgInst_electric: {
    sheet: 'Yanagi',
    name: 'vortexDmgInst_electric',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'vortex',
      name: 'vortexDmgInst_electric',
    },
  },
  abloomDmgInst: {
    sheet: 'Yanagi',
    name: 'abloomDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Yanagi',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Yanagi',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      name: 'dazeInst',
    },
  },
  'StanceJougen_0:standardDmg': {
    sheet: 'Yanagi',
    name: 'StanceJougen_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yanagi',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'StanceJougen_0',
    },
  },
  'StanceJougen_0:dazeBuildup': {
    sheet: 'Yanagi',
    name: 'StanceJougen_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yanagi',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'StanceJougen_0',
    },
  },
  'StanceJougen_0:anomBuildup': {
    sheet: 'Yanagi',
    name: 'StanceJougen_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yanagi',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'StanceJougen_0',
    },
  },
  'StanceJougen_1:standardDmg': {
    sheet: 'Yanagi',
    name: 'StanceJougen_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yanagi',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'StanceJougen_1',
    },
  },
  'StanceJougen_1:dazeBuildup': {
    sheet: 'Yanagi',
    name: 'StanceJougen_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yanagi',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'StanceJougen_1',
    },
  },
  'StanceJougen_1:anomBuildup': {
    sheet: 'Yanagi',
    name: 'StanceJougen_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yanagi',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'StanceJougen_1',
    },
  },
  'StanceJougen_2:standardDmg': {
    sheet: 'Yanagi',
    name: 'StanceJougen_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'StanceJougen_2',
    },
  },
  'StanceJougen_2:dazeBuildup': {
    sheet: 'Yanagi',
    name: 'StanceJougen_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'StanceJougen_2',
    },
  },
  'StanceJougen_2:anomBuildup': {
    sheet: 'Yanagi',
    name: 'StanceJougen_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'StanceJougen_2',
    },
  },
  'StanceJougen_3:standardDmg': {
    sheet: 'Yanagi',
    name: 'StanceJougen_3:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'StanceJougen_3',
    },
  },
  'StanceJougen_3:dazeBuildup': {
    sheet: 'Yanagi',
    name: 'StanceJougen_3:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'StanceJougen_3',
    },
  },
  'StanceJougen_3:anomBuildup': {
    sheet: 'Yanagi',
    name: 'StanceJougen_3:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'StanceJougen_3',
    },
  },
  'StanceJougen_4:standardDmg': {
    sheet: 'Yanagi',
    name: 'StanceJougen_4:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'StanceJougen_4',
    },
  },
  'StanceJougen_4:dazeBuildup': {
    sheet: 'Yanagi',
    name: 'StanceJougen_4:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'StanceJougen_4',
    },
  },
  'StanceJougen_4:anomBuildup': {
    sheet: 'Yanagi',
    name: 'StanceJougen_4:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'StanceJougen_4',
    },
  },
  'StanceKagen_0:standardDmg': {
    sheet: 'Yanagi',
    name: 'StanceKagen_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yanagi',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'StanceKagen_0',
    },
  },
  'StanceKagen_0:dazeBuildup': {
    sheet: 'Yanagi',
    name: 'StanceKagen_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yanagi',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'StanceKagen_0',
    },
  },
  'StanceKagen_0:anomBuildup': {
    sheet: 'Yanagi',
    name: 'StanceKagen_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yanagi',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'StanceKagen_0',
    },
  },
  'StanceKagen_1:standardDmg': {
    sheet: 'Yanagi',
    name: 'StanceKagen_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yanagi',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'StanceKagen_1',
    },
  },
  'StanceKagen_1:dazeBuildup': {
    sheet: 'Yanagi',
    name: 'StanceKagen_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yanagi',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'StanceKagen_1',
    },
  },
  'StanceKagen_1:anomBuildup': {
    sheet: 'Yanagi',
    name: 'StanceKagen_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yanagi',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'StanceKagen_1',
    },
  },
  'StanceKagen_2:standardDmg': {
    sheet: 'Yanagi',
    name: 'StanceKagen_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'StanceKagen_2',
    },
  },
  'StanceKagen_2:dazeBuildup': {
    sheet: 'Yanagi',
    name: 'StanceKagen_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'StanceKagen_2',
    },
  },
  'StanceKagen_2:anomBuildup': {
    sheet: 'Yanagi',
    name: 'StanceKagen_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'StanceKagen_2',
    },
  },
  'StanceKagen_3:standardDmg': {
    sheet: 'Yanagi',
    name: 'StanceKagen_3:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'StanceKagen_3',
    },
  },
  'StanceKagen_3:dazeBuildup': {
    sheet: 'Yanagi',
    name: 'StanceKagen_3:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'StanceKagen_3',
    },
  },
  'StanceKagen_3:anomBuildup': {
    sheet: 'Yanagi',
    name: 'StanceKagen_3:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'StanceKagen_3',
    },
  },
  'StanceKagen_4:standardDmg': {
    sheet: 'Yanagi',
    name: 'StanceKagen_4:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'StanceKagen_4',
    },
  },
  'StanceKagen_4:dazeBuildup': {
    sheet: 'Yanagi',
    name: 'StanceKagen_4:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'StanceKagen_4',
    },
  },
  'StanceKagen_4:anomBuildup': {
    sheet: 'Yanagi',
    name: 'StanceKagen_4:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'StanceKagen_4',
    },
  },
  'DashAttackFleetingFlight_0:standardDmg': {
    sheet: 'Yanagi',
    name: 'DashAttackFleetingFlight_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yanagi',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttackFleetingFlight_0',
    },
  },
  'DashAttackFleetingFlight_0:dazeBuildup': {
    sheet: 'Yanagi',
    name: 'DashAttackFleetingFlight_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yanagi',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttackFleetingFlight_0',
    },
  },
  'DashAttackFleetingFlight_0:anomBuildup': {
    sheet: 'Yanagi',
    name: 'DashAttackFleetingFlight_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yanagi',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttackFleetingFlight_0',
    },
  },
  'DodgeCounterRapidRetaliation_0:standardDmg': {
    sheet: 'Yanagi',
    name: 'DodgeCounterRapidRetaliation_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterRapidRetaliation_0',
    },
  },
  'DodgeCounterRapidRetaliation_0:dazeBuildup': {
    sheet: 'Yanagi',
    name: 'DodgeCounterRapidRetaliation_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterRapidRetaliation_0',
    },
  },
  'DodgeCounterRapidRetaliation_0:anomBuildup': {
    sheet: 'Yanagi',
    name: 'DodgeCounterRapidRetaliation_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterRapidRetaliation_0',
    },
  },
  'SpecialAttackRuten_0:standardDmg': {
    sheet: 'Yanagi',
    name: 'SpecialAttackRuten_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackRuten_0',
    },
  },
  'SpecialAttackRuten_0:dazeBuildup': {
    sheet: 'Yanagi',
    name: 'SpecialAttackRuten_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackRuten_0',
    },
  },
  'SpecialAttackRuten_0:anomBuildup': {
    sheet: 'Yanagi',
    name: 'SpecialAttackRuten_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackRuten_0',
    },
  },
  'EXSpecialAttackGekkaRuten_0:standardDmg': {
    sheet: 'Yanagi',
    name: 'EXSpecialAttackGekkaRuten_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackGekkaRuten_0',
    },
  },
  'EXSpecialAttackGekkaRuten_0:dazeBuildup': {
    sheet: 'Yanagi',
    name: 'EXSpecialAttackGekkaRuten_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackGekkaRuten_0',
    },
  },
  'EXSpecialAttackGekkaRuten_0:anomBuildup': {
    sheet: 'Yanagi',
    name: 'EXSpecialAttackGekkaRuten_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackGekkaRuten_0',
    },
  },
  'EXSpecialAttackGekkaRuten_1:standardDmg': {
    sheet: 'Yanagi',
    name: 'EXSpecialAttackGekkaRuten_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackGekkaRuten_1',
    },
  },
  'EXSpecialAttackGekkaRuten_1:dazeBuildup': {
    sheet: 'Yanagi',
    name: 'EXSpecialAttackGekkaRuten_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackGekkaRuten_1',
    },
  },
  'EXSpecialAttackGekkaRuten_1:anomBuildup': {
    sheet: 'Yanagi',
    name: 'EXSpecialAttackGekkaRuten_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackGekkaRuten_1',
    },
  },
  'ChainAttackCelestialHarmony_0:standardDmg': {
    sheet: 'Yanagi',
    name: 'ChainAttackCelestialHarmony_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackCelestialHarmony_0',
    },
  },
  'ChainAttackCelestialHarmony_0:dazeBuildup': {
    sheet: 'Yanagi',
    name: 'ChainAttackCelestialHarmony_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackCelestialHarmony_0',
    },
  },
  'ChainAttackCelestialHarmony_0:anomBuildup': {
    sheet: 'Yanagi',
    name: 'ChainAttackCelestialHarmony_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackCelestialHarmony_0',
    },
  },
  'UltimateRaieiTenge_0:standardDmg': {
    sheet: 'Yanagi',
    name: 'UltimateRaieiTenge_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateRaieiTenge_0',
    },
  },
  'UltimateRaieiTenge_0:dazeBuildup': {
    sheet: 'Yanagi',
    name: 'UltimateRaieiTenge_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateRaieiTenge_0',
    },
  },
  'UltimateRaieiTenge_0:anomBuildup': {
    sheet: 'Yanagi',
    name: 'UltimateRaieiTenge_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateRaieiTenge_0',
    },
  },
  'QuickAssistBladeOfElegance_0:standardDmg': {
    sheet: 'Yanagi',
    name: 'QuickAssistBladeOfElegance_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistBladeOfElegance_0',
    },
  },
  'QuickAssistBladeOfElegance_0:dazeBuildup': {
    sheet: 'Yanagi',
    name: 'QuickAssistBladeOfElegance_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistBladeOfElegance_0',
    },
  },
  'QuickAssistBladeOfElegance_0:anomBuildup': {
    sheet: 'Yanagi',
    name: 'QuickAssistBladeOfElegance_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistBladeOfElegance_0',
    },
  },
  'DefensiveAssistRadiantReversal_0:standardDmg': {
    sheet: 'Yanagi',
    name: 'DefensiveAssistRadiantReversal_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistRadiantReversal_0',
    },
  },
  'DefensiveAssistRadiantReversal_0:dazeBuildup': {
    sheet: 'Yanagi',
    name: 'DefensiveAssistRadiantReversal_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistRadiantReversal_0',
    },
  },
  'DefensiveAssistRadiantReversal_0:anomBuildup': {
    sheet: 'Yanagi',
    name: 'DefensiveAssistRadiantReversal_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistRadiantReversal_0',
    },
  },
  'DefensiveAssistRadiantReversal_1:standardDmg': {
    sheet: 'Yanagi',
    name: 'DefensiveAssistRadiantReversal_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistRadiantReversal_1',
    },
  },
  'DefensiveAssistRadiantReversal_1:dazeBuildup': {
    sheet: 'Yanagi',
    name: 'DefensiveAssistRadiantReversal_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistRadiantReversal_1',
    },
  },
  'DefensiveAssistRadiantReversal_1:anomBuildup': {
    sheet: 'Yanagi',
    name: 'DefensiveAssistRadiantReversal_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistRadiantReversal_1',
    },
  },
  'DefensiveAssistRadiantReversal_2:standardDmg': {
    sheet: 'Yanagi',
    name: 'DefensiveAssistRadiantReversal_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistRadiantReversal_2',
    },
  },
  'DefensiveAssistRadiantReversal_2:dazeBuildup': {
    sheet: 'Yanagi',
    name: 'DefensiveAssistRadiantReversal_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistRadiantReversal_2',
    },
  },
  'DefensiveAssistRadiantReversal_2:anomBuildup': {
    sheet: 'Yanagi',
    name: 'DefensiveAssistRadiantReversal_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistRadiantReversal_2',
    },
  },
  'AssistFollowUpWeepingWillowStab_0:standardDmg': {
    sheet: 'Yanagi',
    name: 'AssistFollowUpWeepingWillowStab_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpWeepingWillowStab_0',
    },
  },
  'AssistFollowUpWeepingWillowStab_0:dazeBuildup': {
    sheet: 'Yanagi',
    name: 'AssistFollowUpWeepingWillowStab_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpWeepingWillowStab_0',
    },
  },
  'AssistFollowUpWeepingWillowStab_0:anomBuildup': {
    sheet: 'Yanagi',
    name: 'AssistFollowUpWeepingWillowStab_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpWeepingWillowStab_0',
    },
  },
} as const
