// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Yanagi',
    name: 'standardDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yanagi',
      attribute: 'electric',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Yanagi',
    name: 'anomalyDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_electric: {
    sheet: 'Yanagi',
    name: 'disorderDmgInst_electric',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'disorder',
      name: 'disorderDmgInst_electric',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Yanagi',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Yanagi',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      name: 'dazeInst',
    },
  },
  StanceJougen_0_dmg: {
    sheet: 'Yanagi',
    name: 'StanceJougen_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yanagi',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'StanceJougen_0_dmg',
    },
  },
  StanceJougen_0_daze: {
    sheet: 'Yanagi',
    name: 'StanceJougen_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yanagi',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'StanceJougen_0_daze',
    },
  },
  StanceJougen_0_anomBuildup: {
    sheet: 'Yanagi',
    name: 'StanceJougen_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yanagi',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'StanceJougen_0_anomBuildup',
    },
  },
  StanceJougen_1_dmg: {
    sheet: 'Yanagi',
    name: 'StanceJougen_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yanagi',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'StanceJougen_1_dmg',
    },
  },
  StanceJougen_1_daze: {
    sheet: 'Yanagi',
    name: 'StanceJougen_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yanagi',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'StanceJougen_1_daze',
    },
  },
  StanceJougen_1_anomBuildup: {
    sheet: 'Yanagi',
    name: 'StanceJougen_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yanagi',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'StanceJougen_1_anomBuildup',
    },
  },
  StanceJougen_2_dmg: {
    sheet: 'Yanagi',
    name: 'StanceJougen_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'StanceJougen_2_dmg',
    },
  },
  StanceJougen_2_daze: {
    sheet: 'Yanagi',
    name: 'StanceJougen_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'StanceJougen_2_daze',
    },
  },
  StanceJougen_2_anomBuildup: {
    sheet: 'Yanagi',
    name: 'StanceJougen_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'StanceJougen_2_anomBuildup',
    },
  },
  StanceJougen_3_dmg: {
    sheet: 'Yanagi',
    name: 'StanceJougen_3_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'StanceJougen_3_dmg',
    },
  },
  StanceJougen_3_daze: {
    sheet: 'Yanagi',
    name: 'StanceJougen_3_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'StanceJougen_3_daze',
    },
  },
  StanceJougen_3_anomBuildup: {
    sheet: 'Yanagi',
    name: 'StanceJougen_3_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'StanceJougen_3_anomBuildup',
    },
  },
  StanceJougen_4_dmg: {
    sheet: 'Yanagi',
    name: 'StanceJougen_4_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'StanceJougen_4_dmg',
    },
  },
  StanceJougen_4_daze: {
    sheet: 'Yanagi',
    name: 'StanceJougen_4_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'StanceJougen_4_daze',
    },
  },
  StanceJougen_4_anomBuildup: {
    sheet: 'Yanagi',
    name: 'StanceJougen_4_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'StanceJougen_4_anomBuildup',
    },
  },
  StanceKagen_0_dmg: {
    sheet: 'Yanagi',
    name: 'StanceKagen_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yanagi',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'StanceKagen_0_dmg',
    },
  },
  StanceKagen_0_daze: {
    sheet: 'Yanagi',
    name: 'StanceKagen_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yanagi',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'StanceKagen_0_daze',
    },
  },
  StanceKagen_0_anomBuildup: {
    sheet: 'Yanagi',
    name: 'StanceKagen_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yanagi',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'StanceKagen_0_anomBuildup',
    },
  },
  StanceKagen_1_dmg: {
    sheet: 'Yanagi',
    name: 'StanceKagen_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yanagi',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'StanceKagen_1_dmg',
    },
  },
  StanceKagen_1_daze: {
    sheet: 'Yanagi',
    name: 'StanceKagen_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yanagi',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'StanceKagen_1_daze',
    },
  },
  StanceKagen_1_anomBuildup: {
    sheet: 'Yanagi',
    name: 'StanceKagen_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yanagi',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'StanceKagen_1_anomBuildup',
    },
  },
  StanceKagen_2_dmg: {
    sheet: 'Yanagi',
    name: 'StanceKagen_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'StanceKagen_2_dmg',
    },
  },
  StanceKagen_2_daze: {
    sheet: 'Yanagi',
    name: 'StanceKagen_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'StanceKagen_2_daze',
    },
  },
  StanceKagen_2_anomBuildup: {
    sheet: 'Yanagi',
    name: 'StanceKagen_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'StanceKagen_2_anomBuildup',
    },
  },
  StanceKagen_3_dmg: {
    sheet: 'Yanagi',
    name: 'StanceKagen_3_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'StanceKagen_3_dmg',
    },
  },
  StanceKagen_3_daze: {
    sheet: 'Yanagi',
    name: 'StanceKagen_3_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'StanceKagen_3_daze',
    },
  },
  StanceKagen_3_anomBuildup: {
    sheet: 'Yanagi',
    name: 'StanceKagen_3_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'StanceKagen_3_anomBuildup',
    },
  },
  StanceKagen_4_dmg: {
    sheet: 'Yanagi',
    name: 'StanceKagen_4_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'StanceKagen_4_dmg',
    },
  },
  StanceKagen_4_daze: {
    sheet: 'Yanagi',
    name: 'StanceKagen_4_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'StanceKagen_4_daze',
    },
  },
  StanceKagen_4_anomBuildup: {
    sheet: 'Yanagi',
    name: 'StanceKagen_4_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'StanceKagen_4_anomBuildup',
    },
  },
  DashAttackFleetingFlight_0_dmg: {
    sheet: 'Yanagi',
    name: 'DashAttackFleetingFlight_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yanagi',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttackFleetingFlight_0_dmg',
    },
  },
  DashAttackFleetingFlight_0_daze: {
    sheet: 'Yanagi',
    name: 'DashAttackFleetingFlight_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yanagi',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttackFleetingFlight_0_daze',
    },
  },
  DashAttackFleetingFlight_0_anomBuildup: {
    sheet: 'Yanagi',
    name: 'DashAttackFleetingFlight_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yanagi',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttackFleetingFlight_0_anomBuildup',
    },
  },
  DodgeCounterRapidRetaliation_0_dmg: {
    sheet: 'Yanagi',
    name: 'DodgeCounterRapidRetaliation_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterRapidRetaliation_0_dmg',
    },
  },
  DodgeCounterRapidRetaliation_0_daze: {
    sheet: 'Yanagi',
    name: 'DodgeCounterRapidRetaliation_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterRapidRetaliation_0_daze',
    },
  },
  DodgeCounterRapidRetaliation_0_anomBuildup: {
    sheet: 'Yanagi',
    name: 'DodgeCounterRapidRetaliation_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterRapidRetaliation_0_anomBuildup',
    },
  },
  SpecialAttackRuten_0_dmg: {
    sheet: 'Yanagi',
    name: 'SpecialAttackRuten_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackRuten_0_dmg',
    },
  },
  SpecialAttackRuten_0_daze: {
    sheet: 'Yanagi',
    name: 'SpecialAttackRuten_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackRuten_0_daze',
    },
  },
  SpecialAttackRuten_0_anomBuildup: {
    sheet: 'Yanagi',
    name: 'SpecialAttackRuten_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackRuten_0_anomBuildup',
    },
  },
  EXSpecialAttackGekkaRuten_0_dmg: {
    sheet: 'Yanagi',
    name: 'EXSpecialAttackGekkaRuten_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackGekkaRuten_0_dmg',
    },
  },
  EXSpecialAttackGekkaRuten_0_daze: {
    sheet: 'Yanagi',
    name: 'EXSpecialAttackGekkaRuten_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackGekkaRuten_0_daze',
    },
  },
  EXSpecialAttackGekkaRuten_0_anomBuildup: {
    sheet: 'Yanagi',
    name: 'EXSpecialAttackGekkaRuten_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackGekkaRuten_0_anomBuildup',
    },
  },
  EXSpecialAttackGekkaRuten_1_dmg: {
    sheet: 'Yanagi',
    name: 'EXSpecialAttackGekkaRuten_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackGekkaRuten_1_dmg',
    },
  },
  EXSpecialAttackGekkaRuten_1_daze: {
    sheet: 'Yanagi',
    name: 'EXSpecialAttackGekkaRuten_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackGekkaRuten_1_daze',
    },
  },
  EXSpecialAttackGekkaRuten_1_anomBuildup: {
    sheet: 'Yanagi',
    name: 'EXSpecialAttackGekkaRuten_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackGekkaRuten_1_anomBuildup',
    },
  },
  ChainAttackCelestialHarmony_0_dmg: {
    sheet: 'Yanagi',
    name: 'ChainAttackCelestialHarmony_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackCelestialHarmony_0_dmg',
    },
  },
  ChainAttackCelestialHarmony_0_daze: {
    sheet: 'Yanagi',
    name: 'ChainAttackCelestialHarmony_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackCelestialHarmony_0_daze',
    },
  },
  ChainAttackCelestialHarmony_0_anomBuildup: {
    sheet: 'Yanagi',
    name: 'ChainAttackCelestialHarmony_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackCelestialHarmony_0_anomBuildup',
    },
  },
  UltimateRaieiTenge_0_dmg: {
    sheet: 'Yanagi',
    name: 'UltimateRaieiTenge_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateRaieiTenge_0_dmg',
    },
  },
  UltimateRaieiTenge_0_daze: {
    sheet: 'Yanagi',
    name: 'UltimateRaieiTenge_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateRaieiTenge_0_daze',
    },
  },
  UltimateRaieiTenge_0_anomBuildup: {
    sheet: 'Yanagi',
    name: 'UltimateRaieiTenge_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateRaieiTenge_0_anomBuildup',
    },
  },
  QuickAssistBladeOfElegance_0_dmg: {
    sheet: 'Yanagi',
    name: 'QuickAssistBladeOfElegance_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistBladeOfElegance_0_dmg',
    },
  },
  QuickAssistBladeOfElegance_0_daze: {
    sheet: 'Yanagi',
    name: 'QuickAssistBladeOfElegance_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistBladeOfElegance_0_daze',
    },
  },
  QuickAssistBladeOfElegance_0_anomBuildup: {
    sheet: 'Yanagi',
    name: 'QuickAssistBladeOfElegance_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistBladeOfElegance_0_anomBuildup',
    },
  },
  DefensiveAssistRadiantReversal_0_dmg: {
    sheet: 'Yanagi',
    name: 'DefensiveAssistRadiantReversal_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistRadiantReversal_0_dmg',
    },
  },
  DefensiveAssistRadiantReversal_0_daze: {
    sheet: 'Yanagi',
    name: 'DefensiveAssistRadiantReversal_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistRadiantReversal_0_daze',
    },
  },
  DefensiveAssistRadiantReversal_0_anomBuildup: {
    sheet: 'Yanagi',
    name: 'DefensiveAssistRadiantReversal_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistRadiantReversal_0_anomBuildup',
    },
  },
  DefensiveAssistRadiantReversal_1_dmg: {
    sheet: 'Yanagi',
    name: 'DefensiveAssistRadiantReversal_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistRadiantReversal_1_dmg',
    },
  },
  DefensiveAssistRadiantReversal_1_daze: {
    sheet: 'Yanagi',
    name: 'DefensiveAssistRadiantReversal_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistRadiantReversal_1_daze',
    },
  },
  DefensiveAssistRadiantReversal_1_anomBuildup: {
    sheet: 'Yanagi',
    name: 'DefensiveAssistRadiantReversal_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistRadiantReversal_1_anomBuildup',
    },
  },
  DefensiveAssistRadiantReversal_2_dmg: {
    sheet: 'Yanagi',
    name: 'DefensiveAssistRadiantReversal_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistRadiantReversal_2_dmg',
    },
  },
  DefensiveAssistRadiantReversal_2_daze: {
    sheet: 'Yanagi',
    name: 'DefensiveAssistRadiantReversal_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistRadiantReversal_2_daze',
    },
  },
  DefensiveAssistRadiantReversal_2_anomBuildup: {
    sheet: 'Yanagi',
    name: 'DefensiveAssistRadiantReversal_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistRadiantReversal_2_anomBuildup',
    },
  },
  AssistFollowUpWeepingWillowStab_0_dmg: {
    sheet: 'Yanagi',
    name: 'AssistFollowUpWeepingWillowStab_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpWeepingWillowStab_0_dmg',
    },
  },
  AssistFollowUpWeepingWillowStab_0_daze: {
    sheet: 'Yanagi',
    name: 'AssistFollowUpWeepingWillowStab_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpWeepingWillowStab_0_daze',
    },
  },
  AssistFollowUpWeepingWillowStab_0_anomBuildup: {
    sheet: 'Yanagi',
    name: 'AssistFollowUpWeepingWillowStab_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpWeepingWillowStab_0_anomBuildup',
    },
  },
} as const
