// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Yanagi',
    name: 'standardDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'standardDmgBase',
      sheet: 'Yanagi',
      attribute: 'electric',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Yanagi',
    name: 'anomalyDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_electric: {
    sheet: 'Yanagi',
    name: 'disorderDmgInst_electric',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'disorder',
      name: 'disorderDmgInst_electric',
    },
  },
  vortexDmgInst_electric: {
    sheet: 'Yanagi',
    name: 'vortexDmgInst_electric',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'vortex',
      name: 'vortexDmgInst_electric',
    },
  },
  abloomDmgInst: {
    sheet: 'Yanagi',
    name: 'abloomDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Yanagi',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yanagi',
      attribute: 'electric',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Yanagi',
    name: 'dazeInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'dazeBuildupBase',
      sheet: 'Yanagi',
      attribute: 'electric',
      name: 'dazeInst',
    },
  },
  StanceJougen_0: {
    sheet: 'Yanagi',
    name: 'StanceJougen_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yanagi',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'StanceJougen_0',
    },
  },
  StanceJougen_1: {
    sheet: 'Yanagi',
    name: 'StanceJougen_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yanagi',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'StanceJougen_1',
    },
  },
  StanceJougen_2: {
    sheet: 'Yanagi',
    name: 'StanceJougen_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'StanceJougen_2',
    },
  },
  StanceJougen_3: {
    sheet: 'Yanagi',
    name: 'StanceJougen_3',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'StanceJougen_3',
    },
  },
  StanceJougen_4: {
    sheet: 'Yanagi',
    name: 'StanceJougen_4',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'StanceJougen_4',
    },
  },
  StanceKagen_0: {
    sheet: 'Yanagi',
    name: 'StanceKagen_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yanagi',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'StanceKagen_0',
    },
  },
  StanceKagen_1: {
    sheet: 'Yanagi',
    name: 'StanceKagen_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yanagi',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'StanceKagen_1',
    },
  },
  StanceKagen_2: {
    sheet: 'Yanagi',
    name: 'StanceKagen_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'StanceKagen_2',
    },
  },
  StanceKagen_3: {
    sheet: 'Yanagi',
    name: 'StanceKagen_3',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'StanceKagen_3',
    },
  },
  StanceKagen_4: {
    sheet: 'Yanagi',
    name: 'StanceKagen_4',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'StanceKagen_4',
    },
  },
  DashAttackFleetingFlight_0: {
    sheet: 'Yanagi',
    name: 'DashAttackFleetingFlight_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yanagi',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttackFleetingFlight_0',
    },
  },
  DodgeCounterRapidRetaliation_0: {
    sheet: 'Yanagi',
    name: 'DodgeCounterRapidRetaliation_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterRapidRetaliation_0',
    },
  },
  SpecialAttackRuten_0: {
    sheet: 'Yanagi',
    name: 'SpecialAttackRuten_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackRuten_0',
    },
  },
  EXSpecialAttackGekkaRuten_0: {
    sheet: 'Yanagi',
    name: 'EXSpecialAttackGekkaRuten_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackGekkaRuten_0',
    },
  },
  EXSpecialAttackGekkaRuten_1: {
    sheet: 'Yanagi',
    name: 'EXSpecialAttackGekkaRuten_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackGekkaRuten_1',
    },
  },
  ChainAttackCelestialHarmony_0: {
    sheet: 'Yanagi',
    name: 'ChainAttackCelestialHarmony_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackCelestialHarmony_0',
    },
  },
  UltimateRaieiTenge_0: {
    sheet: 'Yanagi',
    name: 'UltimateRaieiTenge_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateRaieiTenge_0',
    },
  },
  QuickAssistBladeOfElegance_0: {
    sheet: 'Yanagi',
    name: 'QuickAssistBladeOfElegance_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistBladeOfElegance_0',
    },
  },
  DefensiveAssistRadiantReversal_0: {
    sheet: 'Yanagi',
    name: 'DefensiveAssistRadiantReversal_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistRadiantReversal_0',
    },
  },
  DefensiveAssistRadiantReversal_1: {
    sheet: 'Yanagi',
    name: 'DefensiveAssistRadiantReversal_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistRadiantReversal_1',
    },
  },
  DefensiveAssistRadiantReversal_2: {
    sheet: 'Yanagi',
    name: 'DefensiveAssistRadiantReversal_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistRadiantReversal_2',
    },
  },
  AssistFollowUpWeepingWillowStab_0: {
    sheet: 'Yanagi',
    name: 'AssistFollowUpWeepingWillowStab_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yanagi',
      attribute: 'electric',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpWeepingWillowStab_0',
    },
  },
} as const
