// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Koleda',
    name: 'standardDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Koleda',
      attribute: 'fire',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Koleda',
    name: 'anomalyDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_fire: {
    sheet: 'Koleda',
    name: 'disorderDmgInst_fire',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'disorder',
      name: 'disorderDmgInst_fire',
    },
  },
  vortexDmgInst_fire: {
    sheet: 'Koleda',
    name: 'vortexDmgInst_fire',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'vortex',
      name: 'vortexDmgInst_fire',
    },
  },
  abloomDmgInst: {
    sheet: 'Koleda',
    name: 'abloomDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Koleda',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Koleda',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      name: 'dazeInst',
    },
  },
  'BasicAttackSmashNBash_0:standardDmg': {
    sheet: 'Koleda',
    name: 'BasicAttackSmashNBash_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Koleda',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackSmashNBash_0',
    },
  },
  'BasicAttackSmashNBash_0:dazeBuildup': {
    sheet: 'Koleda',
    name: 'BasicAttackSmashNBash_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Koleda',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackSmashNBash_0',
    },
  },
  'BasicAttackSmashNBash_0:anomBuildup': {
    sheet: 'Koleda',
    name: 'BasicAttackSmashNBash_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Koleda',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackSmashNBash_0',
    },
  },
  'BasicAttackSmashNBash_1:standardDmg': {
    sheet: 'Koleda',
    name: 'BasicAttackSmashNBash_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Koleda',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackSmashNBash_1',
    },
  },
  'BasicAttackSmashNBash_1:dazeBuildup': {
    sheet: 'Koleda',
    name: 'BasicAttackSmashNBash_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Koleda',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackSmashNBash_1',
    },
  },
  'BasicAttackSmashNBash_1:anomBuildup': {
    sheet: 'Koleda',
    name: 'BasicAttackSmashNBash_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Koleda',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackSmashNBash_1',
    },
  },
  'BasicAttackSmashNBash_2:standardDmg': {
    sheet: 'Koleda',
    name: 'BasicAttackSmashNBash_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Koleda',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackSmashNBash_2',
    },
  },
  'BasicAttackSmashNBash_2:dazeBuildup': {
    sheet: 'Koleda',
    name: 'BasicAttackSmashNBash_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Koleda',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackSmashNBash_2',
    },
  },
  'BasicAttackSmashNBash_2:anomBuildup': {
    sheet: 'Koleda',
    name: 'BasicAttackSmashNBash_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Koleda',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackSmashNBash_2',
    },
  },
  'BasicAttackSmashNBash_3:standardDmg': {
    sheet: 'Koleda',
    name: 'BasicAttackSmashNBash_3:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Koleda',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackSmashNBash_3',
    },
  },
  'BasicAttackSmashNBash_3:dazeBuildup': {
    sheet: 'Koleda',
    name: 'BasicAttackSmashNBash_3:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Koleda',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackSmashNBash_3',
    },
  },
  'BasicAttackSmashNBash_3:anomBuildup': {
    sheet: 'Koleda',
    name: 'BasicAttackSmashNBash_3:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Koleda',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackSmashNBash_3',
    },
  },
  'BasicAttackSmashNBash_4:standardDmg': {
    sheet: 'Koleda',
    name: 'BasicAttackSmashNBash_4:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackSmashNBash_4',
    },
  },
  'BasicAttackSmashNBash_4:dazeBuildup': {
    sheet: 'Koleda',
    name: 'BasicAttackSmashNBash_4:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackSmashNBash_4',
    },
  },
  'BasicAttackSmashNBash_4:anomBuildup': {
    sheet: 'Koleda',
    name: 'BasicAttackSmashNBash_4:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackSmashNBash_4',
    },
  },
  'BasicAttackSmashNBash_5:standardDmg': {
    sheet: 'Koleda',
    name: 'BasicAttackSmashNBash_5:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackSmashNBash_5',
    },
  },
  'BasicAttackSmashNBash_5:dazeBuildup': {
    sheet: 'Koleda',
    name: 'BasicAttackSmashNBash_5:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackSmashNBash_5',
    },
  },
  'BasicAttackSmashNBash_5:anomBuildup': {
    sheet: 'Koleda',
    name: 'BasicAttackSmashNBash_5:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackSmashNBash_5',
    },
  },
  'BasicAttackSmashNBash_6:standardDmg': {
    sheet: 'Koleda',
    name: 'BasicAttackSmashNBash_6:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackSmashNBash_6',
    },
  },
  'BasicAttackSmashNBash_6:dazeBuildup': {
    sheet: 'Koleda',
    name: 'BasicAttackSmashNBash_6:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackSmashNBash_6',
    },
  },
  'BasicAttackSmashNBash_6:anomBuildup': {
    sheet: 'Koleda',
    name: 'BasicAttackSmashNBash_6:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackSmashNBash_6',
    },
  },
  'DashAttackTremble_0:standardDmg': {
    sheet: 'Koleda',
    name: 'DashAttackTremble_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Koleda',
      damageType1: 'dash',
      attribute: 'physical',
      skillType1: 'dodgeSkill',
      name: 'DashAttackTremble_0',
    },
  },
  'DashAttackTremble_0:dazeBuildup': {
    sheet: 'Koleda',
    name: 'DashAttackTremble_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Koleda',
      damageType1: 'dash',
      attribute: 'physical',
      skillType1: 'dodgeSkill',
      name: 'DashAttackTremble_0',
    },
  },
  'DashAttackTremble_0:anomBuildup': {
    sheet: 'Koleda',
    name: 'DashAttackTremble_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Koleda',
      damageType1: 'dash',
      attribute: 'physical',
      skillType1: 'dodgeSkill',
      name: 'DashAttackTremble_0',
    },
  },
  'DodgeCounterDontLookDownOnMe_0:standardDmg': {
    sheet: 'Koleda',
    name: 'DodgeCounterDontLookDownOnMe_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'dodgeCounter',
      skillType1: 'dodgeSkill',
      name: 'DodgeCounterDontLookDownOnMe_0',
    },
  },
  'DodgeCounterDontLookDownOnMe_0:dazeBuildup': {
    sheet: 'Koleda',
    name: 'DodgeCounterDontLookDownOnMe_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'dodgeCounter',
      skillType1: 'dodgeSkill',
      name: 'DodgeCounterDontLookDownOnMe_0',
    },
  },
  'DodgeCounterDontLookDownOnMe_0:anomBuildup': {
    sheet: 'Koleda',
    name: 'DodgeCounterDontLookDownOnMe_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'dodgeCounter',
      skillType1: 'dodgeSkill',
      name: 'DodgeCounterDontLookDownOnMe_0',
    },
  },
  'SpecialAttackHammerTime_0:standardDmg': {
    sheet: 'Koleda',
    name: 'SpecialAttackHammerTime_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackHammerTime_0',
    },
  },
  'SpecialAttackHammerTime_0:dazeBuildup': {
    sheet: 'Koleda',
    name: 'SpecialAttackHammerTime_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackHammerTime_0',
    },
  },
  'SpecialAttackHammerTime_0:anomBuildup': {
    sheet: 'Koleda',
    name: 'SpecialAttackHammerTime_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackHammerTime_0',
    },
  },
  'SpecialAttackHammerTime_1:standardDmg': {
    sheet: 'Koleda',
    name: 'SpecialAttackHammerTime_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackHammerTime_1',
    },
  },
  'SpecialAttackHammerTime_1:dazeBuildup': {
    sheet: 'Koleda',
    name: 'SpecialAttackHammerTime_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackHammerTime_1',
    },
  },
  'SpecialAttackHammerTime_1:anomBuildup': {
    sheet: 'Koleda',
    name: 'SpecialAttackHammerTime_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackHammerTime_1',
    },
  },
  'SpecialAttackHammerTime_2:standardDmg': {
    sheet: 'Koleda',
    name: 'SpecialAttackHammerTime_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackHammerTime_2',
    },
  },
  'SpecialAttackHammerTime_2:dazeBuildup': {
    sheet: 'Koleda',
    name: 'SpecialAttackHammerTime_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackHammerTime_2',
    },
  },
  'SpecialAttackHammerTime_2:anomBuildup': {
    sheet: 'Koleda',
    name: 'SpecialAttackHammerTime_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackHammerTime_2',
    },
  },
  'EXSpecialAttackBoilingFurnace_0:standardDmg': {
    sheet: 'Koleda',
    name: 'EXSpecialAttackBoilingFurnace_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackBoilingFurnace_0',
    },
  },
  'EXSpecialAttackBoilingFurnace_0:dazeBuildup': {
    sheet: 'Koleda',
    name: 'EXSpecialAttackBoilingFurnace_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackBoilingFurnace_0',
    },
  },
  'EXSpecialAttackBoilingFurnace_0:anomBuildup': {
    sheet: 'Koleda',
    name: 'EXSpecialAttackBoilingFurnace_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackBoilingFurnace_0',
    },
  },
  'EXSpecialAttackBoilingFurnace_1:standardDmg': {
    sheet: 'Koleda',
    name: 'EXSpecialAttackBoilingFurnace_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackBoilingFurnace_1',
    },
  },
  'EXSpecialAttackBoilingFurnace_1:dazeBuildup': {
    sheet: 'Koleda',
    name: 'EXSpecialAttackBoilingFurnace_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackBoilingFurnace_1',
    },
  },
  'EXSpecialAttackBoilingFurnace_1:anomBuildup': {
    sheet: 'Koleda',
    name: 'EXSpecialAttackBoilingFurnace_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackBoilingFurnace_1',
    },
  },
  'EXSpecialAttackBoilingFurnace_2:standardDmg': {
    sheet: 'Koleda',
    name: 'EXSpecialAttackBoilingFurnace_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackBoilingFurnace_2',
    },
  },
  'EXSpecialAttackBoilingFurnace_2:dazeBuildup': {
    sheet: 'Koleda',
    name: 'EXSpecialAttackBoilingFurnace_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackBoilingFurnace_2',
    },
  },
  'EXSpecialAttackBoilingFurnace_2:anomBuildup': {
    sheet: 'Koleda',
    name: 'EXSpecialAttackBoilingFurnace_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackBoilingFurnace_2',
    },
  },
  'ChainAttackNaturalDisaster_0:standardDmg': {
    sheet: 'Koleda',
    name: 'ChainAttackNaturalDisaster_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'chain',
      skillType1: 'chainSkill',
      name: 'ChainAttackNaturalDisaster_0',
    },
  },
  'ChainAttackNaturalDisaster_0:dazeBuildup': {
    sheet: 'Koleda',
    name: 'ChainAttackNaturalDisaster_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'chain',
      skillType1: 'chainSkill',
      name: 'ChainAttackNaturalDisaster_0',
    },
  },
  'ChainAttackNaturalDisaster_0:anomBuildup': {
    sheet: 'Koleda',
    name: 'ChainAttackNaturalDisaster_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'chain',
      skillType1: 'chainSkill',
      name: 'ChainAttackNaturalDisaster_0',
    },
  },
  'UltimateHammerquake_0:standardDmg': {
    sheet: 'Koleda',
    name: 'UltimateHammerquake_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'ult',
      skillType1: 'chainSkill',
      name: 'UltimateHammerquake_0',
    },
  },
  'UltimateHammerquake_0:dazeBuildup': {
    sheet: 'Koleda',
    name: 'UltimateHammerquake_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'ult',
      skillType1: 'chainSkill',
      name: 'UltimateHammerquake_0',
    },
  },
  'UltimateHammerquake_0:anomBuildup': {
    sheet: 'Koleda',
    name: 'UltimateHammerquake_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'ult',
      skillType1: 'chainSkill',
      name: 'UltimateHammerquake_0',
    },
  },
  'UltimateHammerquake_1:standardDmg': {
    sheet: 'Koleda',
    name: 'UltimateHammerquake_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'ult',
      skillType1: 'chainSkill',
      name: 'UltimateHammerquake_1',
    },
  },
  'UltimateHammerquake_1:dazeBuildup': {
    sheet: 'Koleda',
    name: 'UltimateHammerquake_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'ult',
      skillType1: 'chainSkill',
      name: 'UltimateHammerquake_1',
    },
  },
  'UltimateHammerquake_1:anomBuildup': {
    sheet: 'Koleda',
    name: 'UltimateHammerquake_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'ult',
      skillType1: 'chainSkill',
      name: 'UltimateHammerquake_1',
    },
  },
  'QuickAssistComingThru_0:standardDmg': {
    sheet: 'Koleda',
    name: 'QuickAssistComingThru_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'quickAssist',
      skillType1: 'assistSkill',
      name: 'QuickAssistComingThru_0',
    },
  },
  'QuickAssistComingThru_0:dazeBuildup': {
    sheet: 'Koleda',
    name: 'QuickAssistComingThru_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'quickAssist',
      skillType1: 'assistSkill',
      name: 'QuickAssistComingThru_0',
    },
  },
  'QuickAssistComingThru_0:anomBuildup': {
    sheet: 'Koleda',
    name: 'QuickAssistComingThru_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'quickAssist',
      skillType1: 'assistSkill',
      name: 'QuickAssistComingThru_0',
    },
  },
  'DefensiveAssistProtectiveHammer_0:standardDmg': {
    sheet: 'Koleda',
    name: 'DefensiveAssistProtectiveHammer_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistProtectiveHammer_0',
    },
  },
  'DefensiveAssistProtectiveHammer_0:dazeBuildup': {
    sheet: 'Koleda',
    name: 'DefensiveAssistProtectiveHammer_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistProtectiveHammer_0',
    },
  },
  'DefensiveAssistProtectiveHammer_0:anomBuildup': {
    sheet: 'Koleda',
    name: 'DefensiveAssistProtectiveHammer_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistProtectiveHammer_0',
    },
  },
  'DefensiveAssistProtectiveHammer_1:standardDmg': {
    sheet: 'Koleda',
    name: 'DefensiveAssistProtectiveHammer_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistProtectiveHammer_1',
    },
  },
  'DefensiveAssistProtectiveHammer_1:dazeBuildup': {
    sheet: 'Koleda',
    name: 'DefensiveAssistProtectiveHammer_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistProtectiveHammer_1',
    },
  },
  'DefensiveAssistProtectiveHammer_1:anomBuildup': {
    sheet: 'Koleda',
    name: 'DefensiveAssistProtectiveHammer_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistProtectiveHammer_1',
    },
  },
  'DefensiveAssistProtectiveHammer_2:standardDmg': {
    sheet: 'Koleda',
    name: 'DefensiveAssistProtectiveHammer_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistProtectiveHammer_2',
    },
  },
  'DefensiveAssistProtectiveHammer_2:dazeBuildup': {
    sheet: 'Koleda',
    name: 'DefensiveAssistProtectiveHammer_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistProtectiveHammer_2',
    },
  },
  'DefensiveAssistProtectiveHammer_2:anomBuildup': {
    sheet: 'Koleda',
    name: 'DefensiveAssistProtectiveHammer_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistProtectiveHammer_2',
    },
  },
  'AssistFollowUpHammerBell_0:standardDmg': {
    sheet: 'Koleda',
    name: 'AssistFollowUpHammerBell_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'assistFollowUp',
      skillType1: 'assistSkill',
      name: 'AssistFollowUpHammerBell_0',
    },
  },
  'AssistFollowUpHammerBell_0:dazeBuildup': {
    sheet: 'Koleda',
    name: 'AssistFollowUpHammerBell_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'assistFollowUp',
      skillType1: 'assistSkill',
      name: 'AssistFollowUpHammerBell_0',
    },
  },
  'AssistFollowUpHammerBell_0:anomBuildup': {
    sheet: 'Koleda',
    name: 'AssistFollowUpHammerBell_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'assistFollowUp',
      skillType1: 'assistSkill',
      name: 'AssistFollowUpHammerBell_0',
    },
  },
  m6_dmg: {
    sheet: 'Koleda',
    name: 'm6_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Koleda',
      damageType1: 'elemental',
      name: 'm6_dmg',
    },
  },
} as const
