// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Koleda',
    name: 'standardDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Koleda',
      attribute: 'fire',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Koleda',
    name: 'anomalyDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_fire: {
    sheet: 'Koleda',
    name: 'disorderDmgInst_fire',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'disorder',
      name: 'disorderDmgInst_fire',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Koleda',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Koleda',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      name: 'dazeInst',
    },
  },
  BasicAttackSmashNBash_0_dmg: {
    sheet: 'Koleda',
    name: 'BasicAttackSmashNBash_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Koleda',
      damageType1: 'basic',
      attribute: 'physical',
      name: 'BasicAttackSmashNBash_0_dmg',
    },
  },
  BasicAttackSmashNBash_0_daze: {
    sheet: 'Koleda',
    name: 'BasicAttackSmashNBash_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Koleda',
      damageType1: 'basic',
      attribute: 'physical',
      name: 'BasicAttackSmashNBash_0_daze',
    },
  },
  BasicAttackSmashNBash_0_anomBuildup: {
    sheet: 'Koleda',
    name: 'BasicAttackSmashNBash_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Koleda',
      damageType1: 'basic',
      attribute: 'physical',
      name: 'BasicAttackSmashNBash_0_anomBuildup',
    },
  },
  BasicAttackSmashNBash_1_dmg: {
    sheet: 'Koleda',
    name: 'BasicAttackSmashNBash_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Koleda',
      damageType1: 'basic',
      attribute: 'physical',
      name: 'BasicAttackSmashNBash_1_dmg',
    },
  },
  BasicAttackSmashNBash_1_daze: {
    sheet: 'Koleda',
    name: 'BasicAttackSmashNBash_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Koleda',
      damageType1: 'basic',
      attribute: 'physical',
      name: 'BasicAttackSmashNBash_1_daze',
    },
  },
  BasicAttackSmashNBash_1_anomBuildup: {
    sheet: 'Koleda',
    name: 'BasicAttackSmashNBash_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Koleda',
      damageType1: 'basic',
      attribute: 'physical',
      name: 'BasicAttackSmashNBash_1_anomBuildup',
    },
  },
  BasicAttackSmashNBash_2_dmg: {
    sheet: 'Koleda',
    name: 'BasicAttackSmashNBash_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Koleda',
      damageType1: 'basic',
      attribute: 'physical',
      name: 'BasicAttackSmashNBash_2_dmg',
    },
  },
  BasicAttackSmashNBash_2_daze: {
    sheet: 'Koleda',
    name: 'BasicAttackSmashNBash_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Koleda',
      damageType1: 'basic',
      attribute: 'physical',
      name: 'BasicAttackSmashNBash_2_daze',
    },
  },
  BasicAttackSmashNBash_2_anomBuildup: {
    sheet: 'Koleda',
    name: 'BasicAttackSmashNBash_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Koleda',
      damageType1: 'basic',
      attribute: 'physical',
      name: 'BasicAttackSmashNBash_2_anomBuildup',
    },
  },
  BasicAttackSmashNBash_3_dmg: {
    sheet: 'Koleda',
    name: 'BasicAttackSmashNBash_3_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Koleda',
      damageType1: 'basic',
      attribute: 'physical',
      name: 'BasicAttackSmashNBash_3_dmg',
    },
  },
  BasicAttackSmashNBash_3_daze: {
    sheet: 'Koleda',
    name: 'BasicAttackSmashNBash_3_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Koleda',
      damageType1: 'basic',
      attribute: 'physical',
      name: 'BasicAttackSmashNBash_3_daze',
    },
  },
  BasicAttackSmashNBash_3_anomBuildup: {
    sheet: 'Koleda',
    name: 'BasicAttackSmashNBash_3_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Koleda',
      damageType1: 'basic',
      attribute: 'physical',
      name: 'BasicAttackSmashNBash_3_anomBuildup',
    },
  },
  BasicAttackSmashNBash_4_dmg: {
    sheet: 'Koleda',
    name: 'BasicAttackSmashNBash_4_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'basic',
      name: 'BasicAttackSmashNBash_4_dmg',
    },
  },
  BasicAttackSmashNBash_4_daze: {
    sheet: 'Koleda',
    name: 'BasicAttackSmashNBash_4_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'basic',
      name: 'BasicAttackSmashNBash_4_daze',
    },
  },
  BasicAttackSmashNBash_4_anomBuildup: {
    sheet: 'Koleda',
    name: 'BasicAttackSmashNBash_4_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'basic',
      name: 'BasicAttackSmashNBash_4_anomBuildup',
    },
  },
  BasicAttackSmashNBash_5_dmg: {
    sheet: 'Koleda',
    name: 'BasicAttackSmashNBash_5_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'basic',
      name: 'BasicAttackSmashNBash_5_dmg',
    },
  },
  BasicAttackSmashNBash_5_daze: {
    sheet: 'Koleda',
    name: 'BasicAttackSmashNBash_5_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'basic',
      name: 'BasicAttackSmashNBash_5_daze',
    },
  },
  BasicAttackSmashNBash_5_anomBuildup: {
    sheet: 'Koleda',
    name: 'BasicAttackSmashNBash_5_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'basic',
      name: 'BasicAttackSmashNBash_5_anomBuildup',
    },
  },
  BasicAttackSmashNBash_6_dmg: {
    sheet: 'Koleda',
    name: 'BasicAttackSmashNBash_6_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'basic',
      name: 'BasicAttackSmashNBash_6_dmg',
    },
  },
  BasicAttackSmashNBash_6_daze: {
    sheet: 'Koleda',
    name: 'BasicAttackSmashNBash_6_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'basic',
      name: 'BasicAttackSmashNBash_6_daze',
    },
  },
  BasicAttackSmashNBash_6_anomBuildup: {
    sheet: 'Koleda',
    name: 'BasicAttackSmashNBash_6_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'basic',
      name: 'BasicAttackSmashNBash_6_anomBuildup',
    },
  },
  DashAttackTremble_0_dmg: {
    sheet: 'Koleda',
    name: 'DashAttackTremble_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Koleda',
      damageType1: 'dash',
      attribute: 'physical',
      name: 'DashAttackTremble_0_dmg',
    },
  },
  DashAttackTremble_0_daze: {
    sheet: 'Koleda',
    name: 'DashAttackTremble_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Koleda',
      damageType1: 'dash',
      attribute: 'physical',
      name: 'DashAttackTremble_0_daze',
    },
  },
  DashAttackTremble_0_anomBuildup: {
    sheet: 'Koleda',
    name: 'DashAttackTremble_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Koleda',
      damageType1: 'dash',
      attribute: 'physical',
      name: 'DashAttackTremble_0_anomBuildup',
    },
  },
  DodgeCounterDontLookDownOnMe_0_dmg: {
    sheet: 'Koleda',
    name: 'DodgeCounterDontLookDownOnMe_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterDontLookDownOnMe_0_dmg',
    },
  },
  DodgeCounterDontLookDownOnMe_0_daze: {
    sheet: 'Koleda',
    name: 'DodgeCounterDontLookDownOnMe_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterDontLookDownOnMe_0_daze',
    },
  },
  DodgeCounterDontLookDownOnMe_0_anomBuildup: {
    sheet: 'Koleda',
    name: 'DodgeCounterDontLookDownOnMe_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterDontLookDownOnMe_0_anomBuildup',
    },
  },
  SpecialAttackHammerTime_0_dmg: {
    sheet: 'Koleda',
    name: 'SpecialAttackHammerTime_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackHammerTime_0_dmg',
    },
  },
  SpecialAttackHammerTime_0_daze: {
    sheet: 'Koleda',
    name: 'SpecialAttackHammerTime_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackHammerTime_0_daze',
    },
  },
  SpecialAttackHammerTime_0_anomBuildup: {
    sheet: 'Koleda',
    name: 'SpecialAttackHammerTime_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackHammerTime_0_anomBuildup',
    },
  },
  SpecialAttackHammerTime_1_dmg: {
    sheet: 'Koleda',
    name: 'SpecialAttackHammerTime_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackHammerTime_1_dmg',
    },
  },
  SpecialAttackHammerTime_1_daze: {
    sheet: 'Koleda',
    name: 'SpecialAttackHammerTime_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackHammerTime_1_daze',
    },
  },
  SpecialAttackHammerTime_1_anomBuildup: {
    sheet: 'Koleda',
    name: 'SpecialAttackHammerTime_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackHammerTime_1_anomBuildup',
    },
  },
  SpecialAttackHammerTime_2_dmg: {
    sheet: 'Koleda',
    name: 'SpecialAttackHammerTime_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackHammerTime_2_dmg',
    },
  },
  SpecialAttackHammerTime_2_daze: {
    sheet: 'Koleda',
    name: 'SpecialAttackHammerTime_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackHammerTime_2_daze',
    },
  },
  SpecialAttackHammerTime_2_anomBuildup: {
    sheet: 'Koleda',
    name: 'SpecialAttackHammerTime_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackHammerTime_2_anomBuildup',
    },
  },
  EXSpecialAttackBoilingFurnace_0_dmg: {
    sheet: 'Koleda',
    name: 'EXSpecialAttackBoilingFurnace_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackBoilingFurnace_0_dmg',
    },
  },
  EXSpecialAttackBoilingFurnace_0_daze: {
    sheet: 'Koleda',
    name: 'EXSpecialAttackBoilingFurnace_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackBoilingFurnace_0_daze',
    },
  },
  EXSpecialAttackBoilingFurnace_0_anomBuildup: {
    sheet: 'Koleda',
    name: 'EXSpecialAttackBoilingFurnace_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackBoilingFurnace_0_anomBuildup',
    },
  },
  EXSpecialAttackBoilingFurnace_1_dmg: {
    sheet: 'Koleda',
    name: 'EXSpecialAttackBoilingFurnace_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackBoilingFurnace_1_dmg',
    },
  },
  EXSpecialAttackBoilingFurnace_1_daze: {
    sheet: 'Koleda',
    name: 'EXSpecialAttackBoilingFurnace_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackBoilingFurnace_1_daze',
    },
  },
  EXSpecialAttackBoilingFurnace_1_anomBuildup: {
    sheet: 'Koleda',
    name: 'EXSpecialAttackBoilingFurnace_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackBoilingFurnace_1_anomBuildup',
    },
  },
  EXSpecialAttackBoilingFurnace_2_dmg: {
    sheet: 'Koleda',
    name: 'EXSpecialAttackBoilingFurnace_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackBoilingFurnace_2_dmg',
    },
  },
  EXSpecialAttackBoilingFurnace_2_daze: {
    sheet: 'Koleda',
    name: 'EXSpecialAttackBoilingFurnace_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackBoilingFurnace_2_daze',
    },
  },
  EXSpecialAttackBoilingFurnace_2_anomBuildup: {
    sheet: 'Koleda',
    name: 'EXSpecialAttackBoilingFurnace_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackBoilingFurnace_2_anomBuildup',
    },
  },
  ChainAttackNaturalDisaster_0_dmg: {
    sheet: 'Koleda',
    name: 'ChainAttackNaturalDisaster_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackNaturalDisaster_0_dmg',
    },
  },
  ChainAttackNaturalDisaster_0_daze: {
    sheet: 'Koleda',
    name: 'ChainAttackNaturalDisaster_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackNaturalDisaster_0_daze',
    },
  },
  ChainAttackNaturalDisaster_0_anomBuildup: {
    sheet: 'Koleda',
    name: 'ChainAttackNaturalDisaster_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackNaturalDisaster_0_anomBuildup',
    },
  },
  UltimateHammerquake_0_dmg: {
    sheet: 'Koleda',
    name: 'UltimateHammerquake_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateHammerquake_0_dmg',
    },
  },
  UltimateHammerquake_0_daze: {
    sheet: 'Koleda',
    name: 'UltimateHammerquake_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateHammerquake_0_daze',
    },
  },
  UltimateHammerquake_0_anomBuildup: {
    sheet: 'Koleda',
    name: 'UltimateHammerquake_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateHammerquake_0_anomBuildup',
    },
  },
  UltimateHammerquake_1_dmg: {
    sheet: 'Koleda',
    name: 'UltimateHammerquake_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateHammerquake_1_dmg',
    },
  },
  UltimateHammerquake_1_daze: {
    sheet: 'Koleda',
    name: 'UltimateHammerquake_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateHammerquake_1_daze',
    },
  },
  UltimateHammerquake_1_anomBuildup: {
    sheet: 'Koleda',
    name: 'UltimateHammerquake_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateHammerquake_1_anomBuildup',
    },
  },
  QuickAssistComingThru_0_dmg: {
    sheet: 'Koleda',
    name: 'QuickAssistComingThru_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistComingThru_0_dmg',
    },
  },
  QuickAssistComingThru_0_daze: {
    sheet: 'Koleda',
    name: 'QuickAssistComingThru_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistComingThru_0_daze',
    },
  },
  QuickAssistComingThru_0_anomBuildup: {
    sheet: 'Koleda',
    name: 'QuickAssistComingThru_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistComingThru_0_anomBuildup',
    },
  },
  DefensiveAssistProtectiveHammer_0_dmg: {
    sheet: 'Koleda',
    name: 'DefensiveAssistProtectiveHammer_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistProtectiveHammer_0_dmg',
    },
  },
  DefensiveAssistProtectiveHammer_0_daze: {
    sheet: 'Koleda',
    name: 'DefensiveAssistProtectiveHammer_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistProtectiveHammer_0_daze',
    },
  },
  DefensiveAssistProtectiveHammer_0_anomBuildup: {
    sheet: 'Koleda',
    name: 'DefensiveAssistProtectiveHammer_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistProtectiveHammer_0_anomBuildup',
    },
  },
  DefensiveAssistProtectiveHammer_1_dmg: {
    sheet: 'Koleda',
    name: 'DefensiveAssistProtectiveHammer_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistProtectiveHammer_1_dmg',
    },
  },
  DefensiveAssistProtectiveHammer_1_daze: {
    sheet: 'Koleda',
    name: 'DefensiveAssistProtectiveHammer_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistProtectiveHammer_1_daze',
    },
  },
  DefensiveAssistProtectiveHammer_1_anomBuildup: {
    sheet: 'Koleda',
    name: 'DefensiveAssistProtectiveHammer_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistProtectiveHammer_1_anomBuildup',
    },
  },
  DefensiveAssistProtectiveHammer_2_dmg: {
    sheet: 'Koleda',
    name: 'DefensiveAssistProtectiveHammer_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistProtectiveHammer_2_dmg',
    },
  },
  DefensiveAssistProtectiveHammer_2_daze: {
    sheet: 'Koleda',
    name: 'DefensiveAssistProtectiveHammer_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistProtectiveHammer_2_daze',
    },
  },
  DefensiveAssistProtectiveHammer_2_anomBuildup: {
    sheet: 'Koleda',
    name: 'DefensiveAssistProtectiveHammer_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistProtectiveHammer_2_anomBuildup',
    },
  },
  AssistFollowUpHammerBell_0_dmg: {
    sheet: 'Koleda',
    name: 'AssistFollowUpHammerBell_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpHammerBell_0_dmg',
    },
  },
  AssistFollowUpHammerBell_0_daze: {
    sheet: 'Koleda',
    name: 'AssistFollowUpHammerBell_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpHammerBell_0_daze',
    },
  },
  AssistFollowUpHammerBell_0_anomBuildup: {
    sheet: 'Koleda',
    name: 'AssistFollowUpHammerBell_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpHammerBell_0_anomBuildup',
    },
  },
  m6_dmg: {
    sheet: 'Koleda',
    name: 'm6_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Koleda',
      damageType1: 'elemental',
      name: 'm6_dmg',
    },
  },
} as const
