// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Koleda',
    name: 'standardDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'standardDmgBase',
      sheet: 'Koleda',
      attribute: 'fire',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Koleda',
    name: 'anomalyDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_fire: {
    sheet: 'Koleda',
    name: 'disorderDmgInst_fire',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'disorder',
      name: 'disorderDmgInst_fire',
    },
  },
  vortexDmgInst_fire: {
    sheet: 'Koleda',
    name: 'vortexDmgInst_fire',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'vortex',
      name: 'vortexDmgInst_fire',
    },
  },
  abloomDmgInst: {
    sheet: 'Koleda',
    name: 'abloomDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Koleda',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Koleda',
      attribute: 'fire',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Koleda',
    name: 'dazeInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'dazeBuildupBase',
      sheet: 'Koleda',
      attribute: 'fire',
      name: 'dazeInst',
    },
  },
  BasicAttackSmashNBash_0: {
    sheet: 'Koleda',
    name: 'BasicAttackSmashNBash_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Koleda',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackSmashNBash_0',
    },
  },
  BasicAttackSmashNBash_1: {
    sheet: 'Koleda',
    name: 'BasicAttackSmashNBash_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Koleda',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackSmashNBash_1',
    },
  },
  BasicAttackSmashNBash_2: {
    sheet: 'Koleda',
    name: 'BasicAttackSmashNBash_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Koleda',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackSmashNBash_2',
    },
  },
  BasicAttackSmashNBash_3: {
    sheet: 'Koleda',
    name: 'BasicAttackSmashNBash_3',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Koleda',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackSmashNBash_3',
    },
  },
  BasicAttackSmashNBash_4: {
    sheet: 'Koleda',
    name: 'BasicAttackSmashNBash_4',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSmashNBash_4',
    },
  },
  BasicAttackSmashNBash_5: {
    sheet: 'Koleda',
    name: 'BasicAttackSmashNBash_5',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSmashNBash_5',
    },
  },
  BasicAttackSmashNBash_6: {
    sheet: 'Koleda',
    name: 'BasicAttackSmashNBash_6',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSmashNBash_6',
    },
  },
  DashAttackTremble_0: {
    sheet: 'Koleda',
    name: 'DashAttackTremble_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Koleda',
      damageType1: 'dash',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttackTremble_0',
    },
  },
  DodgeCounterDontLookDownOnMe_0: {
    sheet: 'Koleda',
    name: 'DodgeCounterDontLookDownOnMe_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterDontLookDownOnMe_0',
    },
  },
  SpecialAttackHammerTime_0: {
    sheet: 'Koleda',
    name: 'SpecialAttackHammerTime_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackHammerTime_0',
    },
  },
  SpecialAttackHammerTime_1: {
    sheet: 'Koleda',
    name: 'SpecialAttackHammerTime_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackHammerTime_1',
    },
  },
  SpecialAttackHammerTime_2: {
    sheet: 'Koleda',
    name: 'SpecialAttackHammerTime_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackHammerTime_2',
    },
  },
  EXSpecialAttackBoilingFurnace_0: {
    sheet: 'Koleda',
    name: 'EXSpecialAttackBoilingFurnace_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackBoilingFurnace_0',
    },
  },
  EXSpecialAttackBoilingFurnace_1: {
    sheet: 'Koleda',
    name: 'EXSpecialAttackBoilingFurnace_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackBoilingFurnace_1',
    },
  },
  EXSpecialAttackBoilingFurnace_2: {
    sheet: 'Koleda',
    name: 'EXSpecialAttackBoilingFurnace_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackBoilingFurnace_2',
    },
  },
  ChainAttackNaturalDisaster_0: {
    sheet: 'Koleda',
    name: 'ChainAttackNaturalDisaster_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackNaturalDisaster_0',
    },
  },
  UltimateHammerquake_0: {
    sheet: 'Koleda',
    name: 'UltimateHammerquake_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateHammerquake_0',
    },
  },
  UltimateHammerquake_1: {
    sheet: 'Koleda',
    name: 'UltimateHammerquake_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateHammerquake_1',
    },
  },
  QuickAssistComingThru_0: {
    sheet: 'Koleda',
    name: 'QuickAssistComingThru_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistComingThru_0',
    },
  },
  DefensiveAssistProtectiveHammer_0: {
    sheet: 'Koleda',
    name: 'DefensiveAssistProtectiveHammer_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistProtectiveHammer_0',
    },
  },
  DefensiveAssistProtectiveHammer_1: {
    sheet: 'Koleda',
    name: 'DefensiveAssistProtectiveHammer_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistProtectiveHammer_1',
    },
  },
  DefensiveAssistProtectiveHammer_2: {
    sheet: 'Koleda',
    name: 'DefensiveAssistProtectiveHammer_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistProtectiveHammer_2',
    },
  },
  AssistFollowUpHammerBell_0: {
    sheet: 'Koleda',
    name: 'AssistFollowUpHammerBell_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Koleda',
      attribute: 'fire',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpHammerBell_0',
    },
  },
  m6_dmg: {
    sheet: 'Koleda',
    name: 'm6_dmg',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'standardDmgBase',
      sheet: 'Koleda',
      damageType1: 'elemental',
      name: 'm6_dmg',
    },
  },
} as const
