// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Caesar',
    name: 'standardDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'standardDmgBase',
      sheet: 'Caesar',
      attribute: 'physical',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Caesar',
    name: 'anomalyDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_physical: {
    sheet: 'Caesar',
    name: 'disorderDmgInst_physical',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'disorder',
      name: 'disorderDmgInst_physical',
    },
  },
  vortexDmgInst_physical: {
    sheet: 'Caesar',
    name: 'vortexDmgInst_physical',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'vortex',
      name: 'vortexDmgInst_physical',
    },
  },
  abloomDmgInst: {
    sheet: 'Caesar',
    name: 'abloomDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Caesar',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Caesar',
      attribute: 'physical',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Caesar',
    name: 'dazeInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'dazeBuildupBase',
      sheet: 'Caesar',
      attribute: 'physical',
      name: 'dazeInst',
    },
  },
  BasicAttackRampagingSlash_0: {
    sheet: 'Caesar',
    name: 'BasicAttackRampagingSlash_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackRampagingSlash_0',
    },
  },
  BasicAttackRampagingSlash_1: {
    sheet: 'Caesar',
    name: 'BasicAttackRampagingSlash_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackRampagingSlash_1',
    },
  },
  BasicAttackRampagingSlash_2: {
    sheet: 'Caesar',
    name: 'BasicAttackRampagingSlash_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackRampagingSlash_2',
    },
  },
  BasicAttackRampagingSlash_3: {
    sheet: 'Caesar',
    name: 'BasicAttackRampagingSlash_3',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackRampagingSlash_3',
    },
  },
  BasicAttackRampagingSlash_4: {
    sheet: 'Caesar',
    name: 'BasicAttackRampagingSlash_4',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackRampagingSlash_4',
    },
  },
  BasicAttackRampagingSlash_5: {
    sheet: 'Caesar',
    name: 'BasicAttackRampagingSlash_5',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackRampagingSlash_5',
    },
  },
  BasicAttackRampagingSlash_6: {
    sheet: 'Caesar',
    name: 'BasicAttackRampagingSlash_6',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackRampagingSlash_6',
    },
  },
  BasicAttackDeadEnd_0: {
    sheet: 'Caesar',
    name: 'BasicAttackDeadEnd_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackDeadEnd_0',
    },
  },
  DashAttackHogRush_0: {
    sheet: 'Caesar',
    name: 'DashAttackHogRush_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackHogRush_0',
    },
  },
  DodgeCounterEyeForAnEye_0: {
    sheet: 'Caesar',
    name: 'DodgeCounterEyeForAnEye_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterEyeForAnEye_0',
    },
  },
  SpecialAttackShockwaveShieldBash_0: {
    sheet: 'Caesar',
    name: 'SpecialAttackShockwaveShieldBash_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackShockwaveShieldBash_0',
    },
  },
  SpecialAttackShockwaveShieldBash_1: {
    sheet: 'Caesar',
    name: 'SpecialAttackShockwaveShieldBash_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackShockwaveShieldBash_1',
    },
  },
  SpecialAttackRoaringThrust_0: {
    sheet: 'Caesar',
    name: 'SpecialAttackRoaringThrust_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackRoaringThrust_0',
    },
  },
  EXSpecialAttackParryCounter_0: {
    sheet: 'Caesar',
    name: 'EXSpecialAttackParryCounter_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackParryCounter_0',
    },
  },
  EXSpecialAttackParryCounter_1: {
    sheet: 'Caesar',
    name: 'EXSpecialAttackParryCounter_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackParryCounter_1',
    },
  },
  EXSpecialAttackParryCounter_2: {
    sheet: 'Caesar',
    name: 'EXSpecialAttackParryCounter_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackParryCounter_2',
    },
  },
  EXSpecialAttackOverpoweredShieldBash_0: {
    sheet: 'Caesar',
    name: 'EXSpecialAttackOverpoweredShieldBash_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Caesar',
      damageType1: 'exSpecial',
      attribute: 'physical',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackOverpoweredShieldBash_0',
    },
  },
  EXSpecialAttackOverpoweredShieldBash_1: {
    sheet: 'Caesar',
    name: 'EXSpecialAttackOverpoweredShieldBash_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackOverpoweredShieldBash_1',
    },
  },
  ChainAttackRoadRageSlam_0: {
    sheet: 'Caesar',
    name: 'ChainAttackRoadRageSlam_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackRoadRageSlam_0',
    },
  },
  UltimateSavageSmash_0: {
    sheet: 'Caesar',
    name: 'UltimateSavageSmash_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateSavageSmash_0',
    },
  },
  QuickAssistLaneChange_0: {
    sheet: 'Caesar',
    name: 'QuickAssistLaneChange_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistLaneChange_0',
    },
  },
  DefensiveAssistAegisShield_0: {
    sheet: 'Caesar',
    name: 'DefensiveAssistAegisShield_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistAegisShield_0',
    },
  },
  DefensiveAssistAegisShield_1: {
    sheet: 'Caesar',
    name: 'DefensiveAssistAegisShield_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistAegisShield_1',
    },
  },
  DefensiveAssistAegisShield_2: {
    sheet: 'Caesar',
    name: 'DefensiveAssistAegisShield_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistAegisShield_2',
    },
  },
  AssistFollowUpAidingBlade_0: {
    sheet: 'Caesar',
    name: 'AssistFollowUpAidingBlade_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Caesar',
      damageType1: 'assistFollowUp',
      attribute: 'physical',
      skillType: 'assistSkill',
      name: 'AssistFollowUpAidingBlade_0',
    },
  },
  core_shield: {
    sheet: 'Caesar',
    name: 'core_shield',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'shieldBase',
      sheet: 'Caesar',
      name: 'core_shield',
    },
  },
} as const
