// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Caesar',
    name: 'standardDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Caesar',
      attribute: 'physical',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Caesar',
    name: 'anomalyDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_physical: {
    sheet: 'Caesar',
    name: 'disorderDmgInst_physical',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'disorder',
      name: 'disorderDmgInst_physical',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Caesar',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Caesar',
      attribute: 'physical',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Caesar',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Caesar',
      attribute: 'physical',
      name: 'dazeInst',
    },
  },
  BasicAttackRampagingSlash_0_dmg: {
    sheet: 'Caesar',
    name: 'BasicAttackRampagingSlash_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackRampagingSlash_0_dmg',
    },
  },
  BasicAttackRampagingSlash_0_daze: {
    sheet: 'Caesar',
    name: 'BasicAttackRampagingSlash_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackRampagingSlash_0_daze',
    },
  },
  BasicAttackRampagingSlash_0_anomBuildup: {
    sheet: 'Caesar',
    name: 'BasicAttackRampagingSlash_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackRampagingSlash_0_anomBuildup',
    },
  },
  BasicAttackRampagingSlash_1_dmg: {
    sheet: 'Caesar',
    name: 'BasicAttackRampagingSlash_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackRampagingSlash_1_dmg',
    },
  },
  BasicAttackRampagingSlash_1_daze: {
    sheet: 'Caesar',
    name: 'BasicAttackRampagingSlash_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackRampagingSlash_1_daze',
    },
  },
  BasicAttackRampagingSlash_1_anomBuildup: {
    sheet: 'Caesar',
    name: 'BasicAttackRampagingSlash_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackRampagingSlash_1_anomBuildup',
    },
  },
  BasicAttackRampagingSlash_2_dmg: {
    sheet: 'Caesar',
    name: 'BasicAttackRampagingSlash_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackRampagingSlash_2_dmg',
    },
  },
  BasicAttackRampagingSlash_2_daze: {
    sheet: 'Caesar',
    name: 'BasicAttackRampagingSlash_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackRampagingSlash_2_daze',
    },
  },
  BasicAttackRampagingSlash_2_anomBuildup: {
    sheet: 'Caesar',
    name: 'BasicAttackRampagingSlash_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackRampagingSlash_2_anomBuildup',
    },
  },
  BasicAttackRampagingSlash_3_dmg: {
    sheet: 'Caesar',
    name: 'BasicAttackRampagingSlash_3_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackRampagingSlash_3_dmg',
    },
  },
  BasicAttackRampagingSlash_3_daze: {
    sheet: 'Caesar',
    name: 'BasicAttackRampagingSlash_3_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackRampagingSlash_3_daze',
    },
  },
  BasicAttackRampagingSlash_3_anomBuildup: {
    sheet: 'Caesar',
    name: 'BasicAttackRampagingSlash_3_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackRampagingSlash_3_anomBuildup',
    },
  },
  BasicAttackRampagingSlash_4_dmg: {
    sheet: 'Caesar',
    name: 'BasicAttackRampagingSlash_4_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackRampagingSlash_4_dmg',
    },
  },
  BasicAttackRampagingSlash_4_daze: {
    sheet: 'Caesar',
    name: 'BasicAttackRampagingSlash_4_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackRampagingSlash_4_daze',
    },
  },
  BasicAttackRampagingSlash_4_anomBuildup: {
    sheet: 'Caesar',
    name: 'BasicAttackRampagingSlash_4_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackRampagingSlash_4_anomBuildup',
    },
  },
  BasicAttackRampagingSlash_5_dmg: {
    sheet: 'Caesar',
    name: 'BasicAttackRampagingSlash_5_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackRampagingSlash_5_dmg',
    },
  },
  BasicAttackRampagingSlash_5_daze: {
    sheet: 'Caesar',
    name: 'BasicAttackRampagingSlash_5_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackRampagingSlash_5_daze',
    },
  },
  BasicAttackRampagingSlash_5_anomBuildup: {
    sheet: 'Caesar',
    name: 'BasicAttackRampagingSlash_5_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackRampagingSlash_5_anomBuildup',
    },
  },
  BasicAttackRampagingSlash_6_dmg: {
    sheet: 'Caesar',
    name: 'BasicAttackRampagingSlash_6_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackRampagingSlash_6_dmg',
    },
  },
  BasicAttackRampagingSlash_6_daze: {
    sheet: 'Caesar',
    name: 'BasicAttackRampagingSlash_6_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackRampagingSlash_6_daze',
    },
  },
  BasicAttackRampagingSlash_6_anomBuildup: {
    sheet: 'Caesar',
    name: 'BasicAttackRampagingSlash_6_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackRampagingSlash_6_anomBuildup',
    },
  },
  BasicAttackDeadEnd_0_dmg: {
    sheet: 'Caesar',
    name: 'BasicAttackDeadEnd_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackDeadEnd_0_dmg',
    },
  },
  BasicAttackDeadEnd_0_daze: {
    sheet: 'Caesar',
    name: 'BasicAttackDeadEnd_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackDeadEnd_0_daze',
    },
  },
  BasicAttackDeadEnd_0_anomBuildup: {
    sheet: 'Caesar',
    name: 'BasicAttackDeadEnd_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackDeadEnd_0_anomBuildup',
    },
  },
  DashAttackHogRush_0_dmg: {
    sheet: 'Caesar',
    name: 'DashAttackHogRush_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackHogRush_0_dmg',
    },
  },
  DashAttackHogRush_0_daze: {
    sheet: 'Caesar',
    name: 'DashAttackHogRush_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackHogRush_0_daze',
    },
  },
  DashAttackHogRush_0_anomBuildup: {
    sheet: 'Caesar',
    name: 'DashAttackHogRush_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackHogRush_0_anomBuildup',
    },
  },
  DodgeCounterEyeForAnEye_0_dmg: {
    sheet: 'Caesar',
    name: 'DodgeCounterEyeForAnEye_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterEyeForAnEye_0_dmg',
    },
  },
  DodgeCounterEyeForAnEye_0_daze: {
    sheet: 'Caesar',
    name: 'DodgeCounterEyeForAnEye_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterEyeForAnEye_0_daze',
    },
  },
  DodgeCounterEyeForAnEye_0_anomBuildup: {
    sheet: 'Caesar',
    name: 'DodgeCounterEyeForAnEye_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterEyeForAnEye_0_anomBuildup',
    },
  },
  SpecialAttackShockwaveShieldBash_0_dmg: {
    sheet: 'Caesar',
    name: 'SpecialAttackShockwaveShieldBash_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackShockwaveShieldBash_0_dmg',
    },
  },
  SpecialAttackShockwaveShieldBash_0_daze: {
    sheet: 'Caesar',
    name: 'SpecialAttackShockwaveShieldBash_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackShockwaveShieldBash_0_daze',
    },
  },
  SpecialAttackShockwaveShieldBash_0_anomBuildup: {
    sheet: 'Caesar',
    name: 'SpecialAttackShockwaveShieldBash_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackShockwaveShieldBash_0_anomBuildup',
    },
  },
  SpecialAttackShockwaveShieldBash_1_dmg: {
    sheet: 'Caesar',
    name: 'SpecialAttackShockwaveShieldBash_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackShockwaveShieldBash_1_dmg',
    },
  },
  SpecialAttackShockwaveShieldBash_1_daze: {
    sheet: 'Caesar',
    name: 'SpecialAttackShockwaveShieldBash_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackShockwaveShieldBash_1_daze',
    },
  },
  SpecialAttackShockwaveShieldBash_1_anomBuildup: {
    sheet: 'Caesar',
    name: 'SpecialAttackShockwaveShieldBash_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackShockwaveShieldBash_1_anomBuildup',
    },
  },
  SpecialAttackRoaringThrust_0_dmg: {
    sheet: 'Caesar',
    name: 'SpecialAttackRoaringThrust_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackRoaringThrust_0_dmg',
    },
  },
  SpecialAttackRoaringThrust_0_daze: {
    sheet: 'Caesar',
    name: 'SpecialAttackRoaringThrust_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackRoaringThrust_0_daze',
    },
  },
  SpecialAttackRoaringThrust_0_anomBuildup: {
    sheet: 'Caesar',
    name: 'SpecialAttackRoaringThrust_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackRoaringThrust_0_anomBuildup',
    },
  },
  EXSpecialAttackParryCounter_0_dmg: {
    sheet: 'Caesar',
    name: 'EXSpecialAttackParryCounter_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackParryCounter_0_dmg',
    },
  },
  EXSpecialAttackParryCounter_0_daze: {
    sheet: 'Caesar',
    name: 'EXSpecialAttackParryCounter_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackParryCounter_0_daze',
    },
  },
  EXSpecialAttackParryCounter_0_anomBuildup: {
    sheet: 'Caesar',
    name: 'EXSpecialAttackParryCounter_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackParryCounter_0_anomBuildup',
    },
  },
  EXSpecialAttackParryCounter_1_dmg: {
    sheet: 'Caesar',
    name: 'EXSpecialAttackParryCounter_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackParryCounter_1_dmg',
    },
  },
  EXSpecialAttackParryCounter_1_daze: {
    sheet: 'Caesar',
    name: 'EXSpecialAttackParryCounter_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackParryCounter_1_daze',
    },
  },
  EXSpecialAttackParryCounter_1_anomBuildup: {
    sheet: 'Caesar',
    name: 'EXSpecialAttackParryCounter_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackParryCounter_1_anomBuildup',
    },
  },
  EXSpecialAttackParryCounter_2_dmg: {
    sheet: 'Caesar',
    name: 'EXSpecialAttackParryCounter_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackParryCounter_2_dmg',
    },
  },
  EXSpecialAttackParryCounter_2_daze: {
    sheet: 'Caesar',
    name: 'EXSpecialAttackParryCounter_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackParryCounter_2_daze',
    },
  },
  EXSpecialAttackParryCounter_2_anomBuildup: {
    sheet: 'Caesar',
    name: 'EXSpecialAttackParryCounter_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackParryCounter_2_anomBuildup',
    },
  },
  EXSpecialAttackOverpoweredShieldBash_0_dmg: {
    sheet: 'Caesar',
    name: 'EXSpecialAttackOverpoweredShieldBash_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Caesar',
      damageType1: 'exSpecial',
      attribute: 'physical',
      name: 'EXSpecialAttackOverpoweredShieldBash_0_dmg',
    },
  },
  EXSpecialAttackOverpoweredShieldBash_0_daze: {
    sheet: 'Caesar',
    name: 'EXSpecialAttackOverpoweredShieldBash_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Caesar',
      damageType1: 'exSpecial',
      attribute: 'physical',
      name: 'EXSpecialAttackOverpoweredShieldBash_0_daze',
    },
  },
  EXSpecialAttackOverpoweredShieldBash_0_anomBuildup: {
    sheet: 'Caesar',
    name: 'EXSpecialAttackOverpoweredShieldBash_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Caesar',
      damageType1: 'exSpecial',
      attribute: 'physical',
      name: 'EXSpecialAttackOverpoweredShieldBash_0_anomBuildup',
    },
  },
  EXSpecialAttackOverpoweredShieldBash_1_dmg: {
    sheet: 'Caesar',
    name: 'EXSpecialAttackOverpoweredShieldBash_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackOverpoweredShieldBash_1_dmg',
    },
  },
  EXSpecialAttackOverpoweredShieldBash_1_daze: {
    sheet: 'Caesar',
    name: 'EXSpecialAttackOverpoweredShieldBash_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackOverpoweredShieldBash_1_daze',
    },
  },
  EXSpecialAttackOverpoweredShieldBash_1_anomBuildup: {
    sheet: 'Caesar',
    name: 'EXSpecialAttackOverpoweredShieldBash_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackOverpoweredShieldBash_1_anomBuildup',
    },
  },
  ChainAttackRoadRageSlam_0_dmg: {
    sheet: 'Caesar',
    name: 'ChainAttackRoadRageSlam_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackRoadRageSlam_0_dmg',
    },
  },
  ChainAttackRoadRageSlam_0_daze: {
    sheet: 'Caesar',
    name: 'ChainAttackRoadRageSlam_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackRoadRageSlam_0_daze',
    },
  },
  ChainAttackRoadRageSlam_0_anomBuildup: {
    sheet: 'Caesar',
    name: 'ChainAttackRoadRageSlam_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackRoadRageSlam_0_anomBuildup',
    },
  },
  UltimateSavageSmash_0_dmg: {
    sheet: 'Caesar',
    name: 'UltimateSavageSmash_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateSavageSmash_0_dmg',
    },
  },
  UltimateSavageSmash_0_daze: {
    sheet: 'Caesar',
    name: 'UltimateSavageSmash_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateSavageSmash_0_daze',
    },
  },
  UltimateSavageSmash_0_anomBuildup: {
    sheet: 'Caesar',
    name: 'UltimateSavageSmash_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateSavageSmash_0_anomBuildup',
    },
  },
  QuickAssistLaneChange_0_dmg: {
    sheet: 'Caesar',
    name: 'QuickAssistLaneChange_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistLaneChange_0_dmg',
    },
  },
  QuickAssistLaneChange_0_daze: {
    sheet: 'Caesar',
    name: 'QuickAssistLaneChange_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistLaneChange_0_daze',
    },
  },
  QuickAssistLaneChange_0_anomBuildup: {
    sheet: 'Caesar',
    name: 'QuickAssistLaneChange_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistLaneChange_0_anomBuildup',
    },
  },
  DefensiveAssistAegisShield_0_dmg: {
    sheet: 'Caesar',
    name: 'DefensiveAssistAegisShield_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistAegisShield_0_dmg',
    },
  },
  DefensiveAssistAegisShield_0_daze: {
    sheet: 'Caesar',
    name: 'DefensiveAssistAegisShield_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistAegisShield_0_daze',
    },
  },
  DefensiveAssistAegisShield_0_anomBuildup: {
    sheet: 'Caesar',
    name: 'DefensiveAssistAegisShield_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistAegisShield_0_anomBuildup',
    },
  },
  DefensiveAssistAegisShield_1_dmg: {
    sheet: 'Caesar',
    name: 'DefensiveAssistAegisShield_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistAegisShield_1_dmg',
    },
  },
  DefensiveAssistAegisShield_1_daze: {
    sheet: 'Caesar',
    name: 'DefensiveAssistAegisShield_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistAegisShield_1_daze',
    },
  },
  DefensiveAssistAegisShield_1_anomBuildup: {
    sheet: 'Caesar',
    name: 'DefensiveAssistAegisShield_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistAegisShield_1_anomBuildup',
    },
  },
  DefensiveAssistAegisShield_2_dmg: {
    sheet: 'Caesar',
    name: 'DefensiveAssistAegisShield_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistAegisShield_2_dmg',
    },
  },
  DefensiveAssistAegisShield_2_daze: {
    sheet: 'Caesar',
    name: 'DefensiveAssistAegisShield_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistAegisShield_2_daze',
    },
  },
  DefensiveAssistAegisShield_2_anomBuildup: {
    sheet: 'Caesar',
    name: 'DefensiveAssistAegisShield_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Caesar',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistAegisShield_2_anomBuildup',
    },
  },
  AssistFollowUpAidingBlade_0_dmg: {
    sheet: 'Caesar',
    name: 'AssistFollowUpAidingBlade_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Caesar',
      damageType1: 'assistFollowUp',
      attribute: 'physical',
      name: 'AssistFollowUpAidingBlade_0_dmg',
    },
  },
  AssistFollowUpAidingBlade_0_daze: {
    sheet: 'Caesar',
    name: 'AssistFollowUpAidingBlade_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Caesar',
      damageType1: 'assistFollowUp',
      attribute: 'physical',
      name: 'AssistFollowUpAidingBlade_0_daze',
    },
  },
  AssistFollowUpAidingBlade_0_anomBuildup: {
    sheet: 'Caesar',
    name: 'AssistFollowUpAidingBlade_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Caesar',
      damageType1: 'assistFollowUp',
      attribute: 'physical',
      name: 'AssistFollowUpAidingBlade_0_anomBuildup',
    },
  },
  core_shield: {
    sheet: 'Caesar',
    name: 'core_shield',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'shield',
      sheet: 'Caesar',
      name: 'core_shield',
    },
  },
} as const
