// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Pulchra',
    name: 'standardDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Pulchra',
      attribute: 'physical',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Pulchra',
    name: 'anomalyDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_physical: {
    sheet: 'Pulchra',
    name: 'disorderDmgInst_physical',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'disorder',
      name: 'disorderDmgInst_physical',
    },
  },
  vortexDmgInst_physical: {
    sheet: 'Pulchra',
    name: 'vortexDmgInst_physical',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'vortex',
      name: 'vortexDmgInst_physical',
    },
  },
  abloomDmgInst: {
    sheet: 'Pulchra',
    name: 'abloomDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Pulchra',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Pulchra',
      attribute: 'physical',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Pulchra',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Pulchra',
      attribute: 'physical',
      name: 'dazeInst',
    },
  },
  'BasicAttackSwiftStrike_0:standardDmg': {
    sheet: 'Pulchra',
    name: 'BasicAttackSwiftStrike_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSwiftStrike_0',
    },
  },
  'BasicAttackSwiftStrike_0:dazeBuildup': {
    sheet: 'Pulchra',
    name: 'BasicAttackSwiftStrike_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSwiftStrike_0',
    },
  },
  'BasicAttackSwiftStrike_0:anomBuildup': {
    sheet: 'Pulchra',
    name: 'BasicAttackSwiftStrike_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSwiftStrike_0',
    },
  },
  'BasicAttackSwiftStrike_1:standardDmg': {
    sheet: 'Pulchra',
    name: 'BasicAttackSwiftStrike_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSwiftStrike_1',
    },
  },
  'BasicAttackSwiftStrike_1:dazeBuildup': {
    sheet: 'Pulchra',
    name: 'BasicAttackSwiftStrike_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSwiftStrike_1',
    },
  },
  'BasicAttackSwiftStrike_1:anomBuildup': {
    sheet: 'Pulchra',
    name: 'BasicAttackSwiftStrike_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSwiftStrike_1',
    },
  },
  'BasicAttackSwiftStrike_2:standardDmg': {
    sheet: 'Pulchra',
    name: 'BasicAttackSwiftStrike_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSwiftStrike_2',
    },
  },
  'BasicAttackSwiftStrike_2:dazeBuildup': {
    sheet: 'Pulchra',
    name: 'BasicAttackSwiftStrike_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSwiftStrike_2',
    },
  },
  'BasicAttackSwiftStrike_2:anomBuildup': {
    sheet: 'Pulchra',
    name: 'BasicAttackSwiftStrike_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSwiftStrike_2',
    },
  },
  'BasicAttackLeapingStrike_0:standardDmg': {
    sheet: 'Pulchra',
    name: 'BasicAttackLeapingStrike_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLeapingStrike_0',
    },
  },
  'BasicAttackLeapingStrike_0:dazeBuildup': {
    sheet: 'Pulchra',
    name: 'BasicAttackLeapingStrike_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLeapingStrike_0',
    },
  },
  'BasicAttackLeapingStrike_0:anomBuildup': {
    sheet: 'Pulchra',
    name: 'BasicAttackLeapingStrike_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLeapingStrike_0',
    },
  },
  'DashAttackFirstStrikeAdvantage_0:standardDmg': {
    sheet: 'Pulchra',
    name: 'DashAttackFirstStrikeAdvantage_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackFirstStrikeAdvantage_0',
    },
  },
  'DashAttackFirstStrikeAdvantage_0:dazeBuildup': {
    sheet: 'Pulchra',
    name: 'DashAttackFirstStrikeAdvantage_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackFirstStrikeAdvantage_0',
    },
  },
  'DashAttackFirstStrikeAdvantage_0:anomBuildup': {
    sheet: 'Pulchra',
    name: 'DashAttackFirstStrikeAdvantage_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackFirstStrikeAdvantage_0',
    },
  },
  'DodgeCounterRelentlessRetribution_0:standardDmg': {
    sheet: 'Pulchra',
    name: 'DodgeCounterRelentlessRetribution_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterRelentlessRetribution_0',
    },
  },
  'DodgeCounterRelentlessRetribution_0:dazeBuildup': {
    sheet: 'Pulchra',
    name: 'DodgeCounterRelentlessRetribution_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterRelentlessRetribution_0',
    },
  },
  'DodgeCounterRelentlessRetribution_0:anomBuildup': {
    sheet: 'Pulchra',
    name: 'DodgeCounterRelentlessRetribution_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterRelentlessRetribution_0',
    },
  },
  'SpecialAttackRendingClaw_0:standardDmg': {
    sheet: 'Pulchra',
    name: 'SpecialAttackRendingClaw_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackRendingClaw_0',
    },
  },
  'SpecialAttackRendingClaw_0:dazeBuildup': {
    sheet: 'Pulchra',
    name: 'SpecialAttackRendingClaw_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackRendingClaw_0',
    },
  },
  'SpecialAttackRendingClaw_0:anomBuildup': {
    sheet: 'Pulchra',
    name: 'SpecialAttackRendingClaw_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackRendingClaw_0',
    },
  },
  'SpecialAttackRendingClawNightmareShadow_0:standardDmg': {
    sheet: 'Pulchra',
    name: 'SpecialAttackRendingClawNightmareShadow_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Pulchra',
      damageType1: 'special',
      damageType2: 'aftershock',
      attribute: 'physical',
      skillType: 'specialSkill',
      name: 'SpecialAttackRendingClawNightmareShadow_0',
    },
  },
  'SpecialAttackRendingClawNightmareShadow_0:dazeBuildup': {
    sheet: 'Pulchra',
    name: 'SpecialAttackRendingClawNightmareShadow_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Pulchra',
      damageType1: 'special',
      damageType2: 'aftershock',
      attribute: 'physical',
      skillType: 'specialSkill',
      name: 'SpecialAttackRendingClawNightmareShadow_0',
    },
  },
  'SpecialAttackRendingClawNightmareShadow_0:anomBuildup': {
    sheet: 'Pulchra',
    name: 'SpecialAttackRendingClawNightmareShadow_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Pulchra',
      damageType1: 'special',
      damageType2: 'aftershock',
      attribute: 'physical',
      skillType: 'specialSkill',
      name: 'SpecialAttackRendingClawNightmareShadow_0',
    },
  },
  'SpecialAttackRendingClawNightmareShadow_1:standardDmg': {
    sheet: 'Pulchra',
    name: 'SpecialAttackRendingClawNightmareShadow_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Pulchra',
      damageType1: 'special',
      damageType2: 'aftershock',
      attribute: 'physical',
      skillType: 'specialSkill',
      name: 'SpecialAttackRendingClawNightmareShadow_1',
    },
  },
  'SpecialAttackRendingClawNightmareShadow_1:dazeBuildup': {
    sheet: 'Pulchra',
    name: 'SpecialAttackRendingClawNightmareShadow_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Pulchra',
      damageType1: 'special',
      damageType2: 'aftershock',
      attribute: 'physical',
      skillType: 'specialSkill',
      name: 'SpecialAttackRendingClawNightmareShadow_1',
    },
  },
  'SpecialAttackRendingClawNightmareShadow_1:anomBuildup': {
    sheet: 'Pulchra',
    name: 'SpecialAttackRendingClawNightmareShadow_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Pulchra',
      damageType1: 'special',
      damageType2: 'aftershock',
      attribute: 'physical',
      skillType: 'specialSkill',
      name: 'SpecialAttackRendingClawNightmareShadow_1',
    },
  },
  'EXSpecialAttackRendingClawFlashstep_0:standardDmg': {
    sheet: 'Pulchra',
    name: 'EXSpecialAttackRendingClawFlashstep_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackRendingClawFlashstep_0',
    },
  },
  'EXSpecialAttackRendingClawFlashstep_0:dazeBuildup': {
    sheet: 'Pulchra',
    name: 'EXSpecialAttackRendingClawFlashstep_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackRendingClawFlashstep_0',
    },
  },
  'EXSpecialAttackRendingClawFlashstep_0:anomBuildup': {
    sheet: 'Pulchra',
    name: 'EXSpecialAttackRendingClawFlashstep_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackRendingClawFlashstep_0',
    },
  },
  'ChainAttackHeyDidntExpectThatRight_0:standardDmg': {
    sheet: 'Pulchra',
    name: 'ChainAttackHeyDidntExpectThatRight_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackHeyDidntExpectThatRight_0',
    },
  },
  'ChainAttackHeyDidntExpectThatRight_0:dazeBuildup': {
    sheet: 'Pulchra',
    name: 'ChainAttackHeyDidntExpectThatRight_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackHeyDidntExpectThatRight_0',
    },
  },
  'ChainAttackHeyDidntExpectThatRight_0:anomBuildup': {
    sheet: 'Pulchra',
    name: 'ChainAttackHeyDidntExpectThatRight_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackHeyDidntExpectThatRight_0',
    },
  },
  'UltimateOhTimeToPlay_0:standardDmg': {
    sheet: 'Pulchra',
    name: 'UltimateOhTimeToPlay_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateOhTimeToPlay_0',
    },
  },
  'UltimateOhTimeToPlay_0:dazeBuildup': {
    sheet: 'Pulchra',
    name: 'UltimateOhTimeToPlay_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateOhTimeToPlay_0',
    },
  },
  'UltimateOhTimeToPlay_0:anomBuildup': {
    sheet: 'Pulchra',
    name: 'UltimateOhTimeToPlay_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateOhTimeToPlay_0',
    },
  },
  'QuickAssistContractBodyguard_0:standardDmg': {
    sheet: 'Pulchra',
    name: 'QuickAssistContractBodyguard_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistContractBodyguard_0',
    },
  },
  'QuickAssistContractBodyguard_0:dazeBuildup': {
    sheet: 'Pulchra',
    name: 'QuickAssistContractBodyguard_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistContractBodyguard_0',
    },
  },
  'QuickAssistContractBodyguard_0:anomBuildup': {
    sheet: 'Pulchra',
    name: 'QuickAssistContractBodyguard_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistContractBodyguard_0',
    },
  },
  'AssistFollowUpIndependentPricing_0:standardDmg': {
    sheet: 'Pulchra',
    name: 'AssistFollowUpIndependentPricing_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpIndependentPricing_0',
    },
  },
  'AssistFollowUpIndependentPricing_0:dazeBuildup': {
    sheet: 'Pulchra',
    name: 'AssistFollowUpIndependentPricing_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpIndependentPricing_0',
    },
  },
  'AssistFollowUpIndependentPricing_0:anomBuildup': {
    sheet: 'Pulchra',
    name: 'AssistFollowUpIndependentPricing_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpIndependentPricing_0',
    },
  },
} as const
