// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Pulchra',
    name: 'standardDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Pulchra',
      attribute: 'physical',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Pulchra',
    name: 'anomalyDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_physical: {
    sheet: 'Pulchra',
    name: 'disorderDmgInst_physical',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'disorder',
      name: 'disorderDmgInst_physical',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Pulchra',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Pulchra',
      attribute: 'physical',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Pulchra',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Pulchra',
      attribute: 'physical',
      name: 'dazeInst',
    },
  },
  BasicAttackSwiftStrike_0_dmg: {
    sheet: 'Pulchra',
    name: 'BasicAttackSwiftStrike_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSwiftStrike_0_dmg',
    },
  },
  BasicAttackSwiftStrike_0_daze: {
    sheet: 'Pulchra',
    name: 'BasicAttackSwiftStrike_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSwiftStrike_0_daze',
    },
  },
  BasicAttackSwiftStrike_0_anomBuildup: {
    sheet: 'Pulchra',
    name: 'BasicAttackSwiftStrike_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSwiftStrike_0_anomBuildup',
    },
  },
  BasicAttackSwiftStrike_1_dmg: {
    sheet: 'Pulchra',
    name: 'BasicAttackSwiftStrike_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSwiftStrike_1_dmg',
    },
  },
  BasicAttackSwiftStrike_1_daze: {
    sheet: 'Pulchra',
    name: 'BasicAttackSwiftStrike_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSwiftStrike_1_daze',
    },
  },
  BasicAttackSwiftStrike_1_anomBuildup: {
    sheet: 'Pulchra',
    name: 'BasicAttackSwiftStrike_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSwiftStrike_1_anomBuildup',
    },
  },
  BasicAttackSwiftStrike_2_dmg: {
    sheet: 'Pulchra',
    name: 'BasicAttackSwiftStrike_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSwiftStrike_2_dmg',
    },
  },
  BasicAttackSwiftStrike_2_daze: {
    sheet: 'Pulchra',
    name: 'BasicAttackSwiftStrike_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSwiftStrike_2_daze',
    },
  },
  BasicAttackSwiftStrike_2_anomBuildup: {
    sheet: 'Pulchra',
    name: 'BasicAttackSwiftStrike_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSwiftStrike_2_anomBuildup',
    },
  },
  BasicAttackLeapingStrike_0_dmg: {
    sheet: 'Pulchra',
    name: 'BasicAttackLeapingStrike_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLeapingStrike_0_dmg',
    },
  },
  BasicAttackLeapingStrike_0_daze: {
    sheet: 'Pulchra',
    name: 'BasicAttackLeapingStrike_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLeapingStrike_0_daze',
    },
  },
  BasicAttackLeapingStrike_0_anomBuildup: {
    sheet: 'Pulchra',
    name: 'BasicAttackLeapingStrike_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLeapingStrike_0_anomBuildup',
    },
  },
  DashAttackFirstStrikeAdvantage_0_dmg: {
    sheet: 'Pulchra',
    name: 'DashAttackFirstStrikeAdvantage_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackFirstStrikeAdvantage_0_dmg',
    },
  },
  DashAttackFirstStrikeAdvantage_0_daze: {
    sheet: 'Pulchra',
    name: 'DashAttackFirstStrikeAdvantage_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackFirstStrikeAdvantage_0_daze',
    },
  },
  DashAttackFirstStrikeAdvantage_0_anomBuildup: {
    sheet: 'Pulchra',
    name: 'DashAttackFirstStrikeAdvantage_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackFirstStrikeAdvantage_0_anomBuildup',
    },
  },
  DodgeCounterRelentlessRetribution_0_dmg: {
    sheet: 'Pulchra',
    name: 'DodgeCounterRelentlessRetribution_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterRelentlessRetribution_0_dmg',
    },
  },
  DodgeCounterRelentlessRetribution_0_daze: {
    sheet: 'Pulchra',
    name: 'DodgeCounterRelentlessRetribution_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterRelentlessRetribution_0_daze',
    },
  },
  DodgeCounterRelentlessRetribution_0_anomBuildup: {
    sheet: 'Pulchra',
    name: 'DodgeCounterRelentlessRetribution_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterRelentlessRetribution_0_anomBuildup',
    },
  },
  SpecialAttackRendingClaw_0_dmg: {
    sheet: 'Pulchra',
    name: 'SpecialAttackRendingClaw_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackRendingClaw_0_dmg',
    },
  },
  SpecialAttackRendingClaw_0_daze: {
    sheet: 'Pulchra',
    name: 'SpecialAttackRendingClaw_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackRendingClaw_0_daze',
    },
  },
  SpecialAttackRendingClaw_0_anomBuildup: {
    sheet: 'Pulchra',
    name: 'SpecialAttackRendingClaw_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackRendingClaw_0_anomBuildup',
    },
  },
  SpecialAttackRendingClawNightmareShadow_0_dmg: {
    sheet: 'Pulchra',
    name: 'SpecialAttackRendingClawNightmareShadow_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Pulchra',
      damageType1: 'special',
      damageType2: 'aftershock',
      attribute: 'physical',
      skillType: 'specialSkill',
      name: 'SpecialAttackRendingClawNightmareShadow_0_dmg',
    },
  },
  SpecialAttackRendingClawNightmareShadow_0_daze: {
    sheet: 'Pulchra',
    name: 'SpecialAttackRendingClawNightmareShadow_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Pulchra',
      damageType1: 'special',
      damageType2: 'aftershock',
      attribute: 'physical',
      skillType: 'specialSkill',
      name: 'SpecialAttackRendingClawNightmareShadow_0_daze',
    },
  },
  SpecialAttackRendingClawNightmareShadow_0_anomBuildup: {
    sheet: 'Pulchra',
    name: 'SpecialAttackRendingClawNightmareShadow_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Pulchra',
      damageType1: 'special',
      damageType2: 'aftershock',
      attribute: 'physical',
      skillType: 'specialSkill',
      name: 'SpecialAttackRendingClawNightmareShadow_0_anomBuildup',
    },
  },
  SpecialAttackRendingClawNightmareShadow_1_dmg: {
    sheet: 'Pulchra',
    name: 'SpecialAttackRendingClawNightmareShadow_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Pulchra',
      damageType1: 'special',
      damageType2: 'aftershock',
      attribute: 'physical',
      skillType: 'specialSkill',
      name: 'SpecialAttackRendingClawNightmareShadow_1_dmg',
    },
  },
  SpecialAttackRendingClawNightmareShadow_1_daze: {
    sheet: 'Pulchra',
    name: 'SpecialAttackRendingClawNightmareShadow_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Pulchra',
      damageType1: 'special',
      damageType2: 'aftershock',
      attribute: 'physical',
      skillType: 'specialSkill',
      name: 'SpecialAttackRendingClawNightmareShadow_1_daze',
    },
  },
  SpecialAttackRendingClawNightmareShadow_1_anomBuildup: {
    sheet: 'Pulchra',
    name: 'SpecialAttackRendingClawNightmareShadow_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Pulchra',
      damageType1: 'special',
      damageType2: 'aftershock',
      attribute: 'physical',
      skillType: 'specialSkill',
      name: 'SpecialAttackRendingClawNightmareShadow_1_anomBuildup',
    },
  },
  EXSpecialAttackRendingClawFlashstep_0_dmg: {
    sheet: 'Pulchra',
    name: 'EXSpecialAttackRendingClawFlashstep_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackRendingClawFlashstep_0_dmg',
    },
  },
  EXSpecialAttackRendingClawFlashstep_0_daze: {
    sheet: 'Pulchra',
    name: 'EXSpecialAttackRendingClawFlashstep_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackRendingClawFlashstep_0_daze',
    },
  },
  EXSpecialAttackRendingClawFlashstep_0_anomBuildup: {
    sheet: 'Pulchra',
    name: 'EXSpecialAttackRendingClawFlashstep_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackRendingClawFlashstep_0_anomBuildup',
    },
  },
  ChainAttackHeyDidntExpectThatRight_0_dmg: {
    sheet: 'Pulchra',
    name: 'ChainAttackHeyDidntExpectThatRight_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackHeyDidntExpectThatRight_0_dmg',
    },
  },
  ChainAttackHeyDidntExpectThatRight_0_daze: {
    sheet: 'Pulchra',
    name: 'ChainAttackHeyDidntExpectThatRight_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackHeyDidntExpectThatRight_0_daze',
    },
  },
  ChainAttackHeyDidntExpectThatRight_0_anomBuildup: {
    sheet: 'Pulchra',
    name: 'ChainAttackHeyDidntExpectThatRight_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackHeyDidntExpectThatRight_0_anomBuildup',
    },
  },
  UltimateOhTimeToPlay_0_dmg: {
    sheet: 'Pulchra',
    name: 'UltimateOhTimeToPlay_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateOhTimeToPlay_0_dmg',
    },
  },
  UltimateOhTimeToPlay_0_daze: {
    sheet: 'Pulchra',
    name: 'UltimateOhTimeToPlay_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateOhTimeToPlay_0_daze',
    },
  },
  UltimateOhTimeToPlay_0_anomBuildup: {
    sheet: 'Pulchra',
    name: 'UltimateOhTimeToPlay_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateOhTimeToPlay_0_anomBuildup',
    },
  },
  QuickAssistContractBodyguard_0_dmg: {
    sheet: 'Pulchra',
    name: 'QuickAssistContractBodyguard_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistContractBodyguard_0_dmg',
    },
  },
  QuickAssistContractBodyguard_0_daze: {
    sheet: 'Pulchra',
    name: 'QuickAssistContractBodyguard_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistContractBodyguard_0_daze',
    },
  },
  QuickAssistContractBodyguard_0_anomBuildup: {
    sheet: 'Pulchra',
    name: 'QuickAssistContractBodyguard_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistContractBodyguard_0_anomBuildup',
    },
  },
  AssistFollowUpIndependentPricing_0_dmg: {
    sheet: 'Pulchra',
    name: 'AssistFollowUpIndependentPricing_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpIndependentPricing_0_dmg',
    },
  },
  AssistFollowUpIndependentPricing_0_daze: {
    sheet: 'Pulchra',
    name: 'AssistFollowUpIndependentPricing_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpIndependentPricing_0_daze',
    },
  },
  AssistFollowUpIndependentPricing_0_anomBuildup: {
    sheet: 'Pulchra',
    name: 'AssistFollowUpIndependentPricing_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Pulchra',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpIndependentPricing_0_anomBuildup',
    },
  },
} as const
