// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Soldier11',
    name: 'standardDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'standardDmgBase',
      sheet: 'Soldier11',
      attribute: 'fire',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Soldier11',
    name: 'anomalyDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Soldier11',
      attribute: 'fire',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_fire: {
    sheet: 'Soldier11',
    name: 'disorderDmgInst_fire',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Soldier11',
      attribute: 'fire',
      damageType1: 'disorder',
      name: 'disorderDmgInst_fire',
    },
  },
  vortexDmgInst_fire: {
    sheet: 'Soldier11',
    name: 'vortexDmgInst_fire',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Soldier11',
      attribute: 'fire',
      damageType1: 'vortex',
      name: 'vortexDmgInst_fire',
    },
  },
  abloomDmgInst: {
    sheet: 'Soldier11',
    name: 'abloomDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Soldier11',
      attribute: 'fire',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Soldier11',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Soldier11',
      attribute: 'fire',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Soldier11',
    name: 'dazeInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'dazeBuildupBase',
      sheet: 'Soldier11',
      attribute: 'fire',
      name: 'dazeInst',
    },
  },
  BasicAttackWarmupSparks_0: {
    sheet: 'Soldier11',
    name: 'BasicAttackWarmupSparks_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Soldier11',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackWarmupSparks_0',
    },
  },
  BasicAttackWarmupSparks_1: {
    sheet: 'Soldier11',
    name: 'BasicAttackWarmupSparks_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Soldier11',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackWarmupSparks_1',
    },
  },
  BasicAttackWarmupSparks_2: {
    sheet: 'Soldier11',
    name: 'BasicAttackWarmupSparks_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Soldier11',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackWarmupSparks_2',
    },
  },
  BasicAttackWarmupSparks_3: {
    sheet: 'Soldier11',
    name: 'BasicAttackWarmupSparks_3',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Soldier11',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackWarmupSparks_3',
    },
  },
  BasicAttackFireSuppression_0: {
    sheet: 'Soldier11',
    name: 'BasicAttackFireSuppression_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Soldier11',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFireSuppression_0',
    },
  },
  BasicAttackFireSuppression_1: {
    sheet: 'Soldier11',
    name: 'BasicAttackFireSuppression_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Soldier11',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFireSuppression_1',
    },
  },
  BasicAttackFireSuppression_2: {
    sheet: 'Soldier11',
    name: 'BasicAttackFireSuppression_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Soldier11',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFireSuppression_2',
    },
  },
  BasicAttackFireSuppression_3: {
    sheet: 'Soldier11',
    name: 'BasicAttackFireSuppression_3',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Soldier11',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFireSuppression_3',
    },
  },
  BasicAttackFireSuppression_4: {
    sheet: 'Soldier11',
    name: 'BasicAttackFireSuppression_4',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Soldier11',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFireSuppression_4',
    },
  },
  BasicAttackFireSuppression_5: {
    sheet: 'Soldier11',
    name: 'BasicAttackFireSuppression_5',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Soldier11',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFireSuppression_5',
    },
  },
  BasicAttackFireSuppression_6: {
    sheet: 'Soldier11',
    name: 'BasicAttackFireSuppression_6',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Soldier11',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFireSuppression_6',
    },
  },
  DashAttackBlazingFire_0: {
    sheet: 'Soldier11',
    name: 'DashAttackBlazingFire_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Soldier11',
      damageType1: 'dash',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttackBlazingFire_0',
    },
  },
  DashAttackFireSuppression_0: {
    sheet: 'Soldier11',
    name: 'DashAttackFireSuppression_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Soldier11',
      attribute: 'fire',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackFireSuppression_0',
    },
  },
  DodgeCounterBackdraft_0: {
    sheet: 'Soldier11',
    name: 'DodgeCounterBackdraft_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Soldier11',
      attribute: 'fire',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterBackdraft_0',
    },
  },
  SpecialAttackRagingFire_0: {
    sheet: 'Soldier11',
    name: 'SpecialAttackRagingFire_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Soldier11',
      attribute: 'fire',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackRagingFire_0',
    },
  },
  EXSpecialAttackFerventFire_0: {
    sheet: 'Soldier11',
    name: 'EXSpecialAttackFerventFire_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Soldier11',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackFerventFire_0',
    },
  },
  ChainAttackUpliftingFlame_0: {
    sheet: 'Soldier11',
    name: 'ChainAttackUpliftingFlame_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Soldier11',
      attribute: 'fire',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackUpliftingFlame_0',
    },
  },
  UltimateBellowingFlame_0: {
    sheet: 'Soldier11',
    name: 'UltimateBellowingFlame_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Soldier11',
      attribute: 'fire',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateBellowingFlame_0',
    },
  },
  QuickAssistCoveringFire_0: {
    sheet: 'Soldier11',
    name: 'QuickAssistCoveringFire_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Soldier11',
      attribute: 'fire',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistCoveringFire_0',
    },
  },
  DefensiveAssistHoldTheLine_0: {
    sheet: 'Soldier11',
    name: 'DefensiveAssistHoldTheLine_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Soldier11',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistHoldTheLine_0',
    },
  },
  DefensiveAssistHoldTheLine_1: {
    sheet: 'Soldier11',
    name: 'DefensiveAssistHoldTheLine_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Soldier11',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistHoldTheLine_1',
    },
  },
  DefensiveAssistHoldTheLine_2: {
    sheet: 'Soldier11',
    name: 'DefensiveAssistHoldTheLine_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Soldier11',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistHoldTheLine_2',
    },
  },
  AssistFollowUpReignition_0: {
    sheet: 'Soldier11',
    name: 'AssistFollowUpReignition_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Soldier11',
      attribute: 'fire',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpReignition_0',
    },
  },
} as const
