// WARNING: Generated file, do not modify
export const formulas = {
  sheerDmgInst: {
    sheet: 'Yidhari',
    name: 'sheerDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'sheer',
      name: 'sheerDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Yidhari',
    name: 'anomalyDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_ice: {
    sheet: 'Yidhari',
    name: 'disorderDmgInst_ice',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'disorder',
      name: 'disorderDmgInst_ice',
    },
  },
  vortexDmgInst_ice: {
    sheet: 'Yidhari',
    name: 'vortexDmgInst_ice',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'vortex',
      name: 'vortexDmgInst_ice',
    },
  },
  abloomDmgInst: {
    sheet: 'Yidhari',
    name: 'abloomDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Yidhari',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yidhari',
      attribute: 'ice',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Yidhari',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yidhari',
      attribute: 'ice',
      name: 'dazeInst',
    },
  },
  'BasicAttackCrushingStrike_0:sheerDmg': {
    sheet: 'Yidhari',
    name: 'BasicAttackCrushingStrike_0:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackCrushingStrike_0',
    },
  },
  'BasicAttackCrushingStrike_0:dazeBuildup': {
    sheet: 'Yidhari',
    name: 'BasicAttackCrushingStrike_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackCrushingStrike_0',
    },
  },
  'BasicAttackCrushingStrike_0:anomBuildup': {
    sheet: 'Yidhari',
    name: 'BasicAttackCrushingStrike_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackCrushingStrike_0',
    },
  },
  'BasicAttackCrushingStrike_1:sheerDmg': {
    sheet: 'Yidhari',
    name: 'BasicAttackCrushingStrike_1:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackCrushingStrike_1',
    },
  },
  'BasicAttackCrushingStrike_1:dazeBuildup': {
    sheet: 'Yidhari',
    name: 'BasicAttackCrushingStrike_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackCrushingStrike_1',
    },
  },
  'BasicAttackCrushingStrike_1:anomBuildup': {
    sheet: 'Yidhari',
    name: 'BasicAttackCrushingStrike_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackCrushingStrike_1',
    },
  },
  'BasicAttackCrushingStrike_2:sheerDmg': {
    sheet: 'Yidhari',
    name: 'BasicAttackCrushingStrike_2:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackCrushingStrike_2',
    },
  },
  'BasicAttackCrushingStrike_2:dazeBuildup': {
    sheet: 'Yidhari',
    name: 'BasicAttackCrushingStrike_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackCrushingStrike_2',
    },
  },
  'BasicAttackCrushingStrike_2:anomBuildup': {
    sheet: 'Yidhari',
    name: 'BasicAttackCrushingStrike_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackCrushingStrike_2',
    },
  },
  'BasicAttackCrushingStrike_3:sheerDmg': {
    sheet: 'Yidhari',
    name: 'BasicAttackCrushingStrike_3:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackCrushingStrike_3',
    },
  },
  'BasicAttackCrushingStrike_3:dazeBuildup': {
    sheet: 'Yidhari',
    name: 'BasicAttackCrushingStrike_3:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackCrushingStrike_3',
    },
  },
  'BasicAttackCrushingStrike_3:anomBuildup': {
    sheet: 'Yidhari',
    name: 'BasicAttackCrushingStrike_3:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackCrushingStrike_3',
    },
  },
  'BasicAttackFrostbiteEmbrace_0:sheerDmg': {
    sheet: 'Yidhari',
    name: 'BasicAttackFrostbiteEmbrace_0:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFrostbiteEmbrace_0',
    },
  },
  'BasicAttackFrostbiteEmbrace_0:dazeBuildup': {
    sheet: 'Yidhari',
    name: 'BasicAttackFrostbiteEmbrace_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFrostbiteEmbrace_0',
    },
  },
  'BasicAttackFrostbiteEmbrace_0:anomBuildup': {
    sheet: 'Yidhari',
    name: 'BasicAttackFrostbiteEmbrace_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFrostbiteEmbrace_0',
    },
  },
  'BasicAttackFrostbiteEmbrace_1:sheerDmg': {
    sheet: 'Yidhari',
    name: 'BasicAttackFrostbiteEmbrace_1:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFrostbiteEmbrace_1',
    },
  },
  'BasicAttackFrostbiteEmbrace_1:dazeBuildup': {
    sheet: 'Yidhari',
    name: 'BasicAttackFrostbiteEmbrace_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFrostbiteEmbrace_1',
    },
  },
  'BasicAttackFrostbiteEmbrace_1:anomBuildup': {
    sheet: 'Yidhari',
    name: 'BasicAttackFrostbiteEmbrace_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFrostbiteEmbrace_1',
    },
  },
  'BasicAttackFrostbiteEmbrace_2:sheerDmg': {
    sheet: 'Yidhari',
    name: 'BasicAttackFrostbiteEmbrace_2:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFrostbiteEmbrace_2',
    },
  },
  'BasicAttackFrostbiteEmbrace_2:dazeBuildup': {
    sheet: 'Yidhari',
    name: 'BasicAttackFrostbiteEmbrace_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFrostbiteEmbrace_2',
    },
  },
  'BasicAttackFrostbiteEmbrace_2:anomBuildup': {
    sheet: 'Yidhari',
    name: 'BasicAttackFrostbiteEmbrace_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFrostbiteEmbrace_2',
    },
  },
  'BasicAttackFrostbiteEmbrace_3:sheerDmg': {
    sheet: 'Yidhari',
    name: 'BasicAttackFrostbiteEmbrace_3:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFrostbiteEmbrace_3',
    },
  },
  'BasicAttackFrostbiteEmbrace_3:dazeBuildup': {
    sheet: 'Yidhari',
    name: 'BasicAttackFrostbiteEmbrace_3:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFrostbiteEmbrace_3',
    },
  },
  'BasicAttackFrostbiteEmbrace_3:anomBuildup': {
    sheet: 'Yidhari',
    name: 'BasicAttackFrostbiteEmbrace_3:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFrostbiteEmbrace_3',
    },
  },
  'FrostsCrushingWeight_0:sheerDmg': {
    sheet: 'Yidhari',
    name: 'FrostsCrushingWeight_0:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'FrostsCrushingWeight_0',
    },
  },
  'FrostsCrushingWeight_0:dazeBuildup': {
    sheet: 'Yidhari',
    name: 'FrostsCrushingWeight_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'FrostsCrushingWeight_0',
    },
  },
  'FrostsCrushingWeight_0:anomBuildup': {
    sheet: 'Yidhari',
    name: 'FrostsCrushingWeight_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'FrostsCrushingWeight_0',
    },
  },
  'DashAttackFrostbloomImpact_0:sheerDmg': {
    sheet: 'Yidhari',
    name: 'DashAttackFrostbloomImpact_0:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackFrostbloomImpact_0',
    },
  },
  'DashAttackFrostbloomImpact_0:dazeBuildup': {
    sheet: 'Yidhari',
    name: 'DashAttackFrostbloomImpact_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackFrostbloomImpact_0',
    },
  },
  'DashAttackFrostbloomImpact_0:anomBuildup': {
    sheet: 'Yidhari',
    name: 'DashAttackFrostbloomImpact_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackFrostbloomImpact_0',
    },
  },
  'DodgeCounterIcehaulReverb_0:sheerDmg': {
    sheet: 'Yidhari',
    name: 'DodgeCounterIcehaulReverb_0:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterIcehaulReverb_0',
    },
  },
  'DodgeCounterIcehaulReverb_0:dazeBuildup': {
    sheet: 'Yidhari',
    name: 'DodgeCounterIcehaulReverb_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterIcehaulReverb_0',
    },
  },
  'DodgeCounterIcehaulReverb_0:anomBuildup': {
    sheet: 'Yidhari',
    name: 'DodgeCounterIcehaulReverb_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterIcehaulReverb_0',
    },
  },
  'SpecialAttackCeaseThoughts_0:sheerDmg': {
    sheet: 'Yidhari',
    name: 'SpecialAttackCeaseThoughts_0:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackCeaseThoughts_0',
    },
  },
  'SpecialAttackCeaseThoughts_0:dazeBuildup': {
    sheet: 'Yidhari',
    name: 'SpecialAttackCeaseThoughts_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackCeaseThoughts_0',
    },
  },
  'SpecialAttackCeaseThoughts_0:anomBuildup': {
    sheet: 'Yidhari',
    name: 'SpecialAttackCeaseThoughts_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackCeaseThoughts_0',
    },
  },
  'EXSpecialAttackFrostCoil_0:sheerDmg': {
    sheet: 'Yidhari',
    name: 'EXSpecialAttackFrostCoil_0:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackFrostCoil_0',
    },
  },
  'EXSpecialAttackFrostCoil_0:dazeBuildup': {
    sheet: 'Yidhari',
    name: 'EXSpecialAttackFrostCoil_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackFrostCoil_0',
    },
  },
  'EXSpecialAttackFrostCoil_0:anomBuildup': {
    sheet: 'Yidhari',
    name: 'EXSpecialAttackFrostCoil_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackFrostCoil_0',
    },
  },
  'SpecialAttackSurgingColdCrushingPursuit_0:sheerDmg': {
    sheet: 'Yidhari',
    name: 'SpecialAttackSurgingColdCrushingPursuit_0:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackSurgingColdCrushingPursuit_0',
    },
  },
  'SpecialAttackSurgingColdCrushingPursuit_0:dazeBuildup': {
    sheet: 'Yidhari',
    name: 'SpecialAttackSurgingColdCrushingPursuit_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackSurgingColdCrushingPursuit_0',
    },
  },
  'SpecialAttackSurgingColdCrushingPursuit_0:anomBuildup': {
    sheet: 'Yidhari',
    name: 'SpecialAttackSurgingColdCrushingPursuit_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackSurgingColdCrushingPursuit_0',
    },
  },
  'EXSpecialAttackGlacialCrush_0:sheerDmg': {
    sheet: 'Yidhari',
    name: 'EXSpecialAttackGlacialCrush_0:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackGlacialCrush_0',
    },
  },
  'EXSpecialAttackGlacialCrush_0:dazeBuildup': {
    sheet: 'Yidhari',
    name: 'EXSpecialAttackGlacialCrush_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackGlacialCrush_0',
    },
  },
  'EXSpecialAttackGlacialCrush_0:anomBuildup': {
    sheet: 'Yidhari',
    name: 'EXSpecialAttackGlacialCrush_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackGlacialCrush_0',
    },
  },
  'EXSpecialAttackGlacialCrush_1:sheerDmg': {
    sheet: 'Yidhari',
    name: 'EXSpecialAttackGlacialCrush_1:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackGlacialCrush_1',
    },
  },
  'EXSpecialAttackGlacialCrush_1:dazeBuildup': {
    sheet: 'Yidhari',
    name: 'EXSpecialAttackGlacialCrush_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackGlacialCrush_1',
    },
  },
  'EXSpecialAttackGlacialCrush_1:anomBuildup': {
    sheet: 'Yidhari',
    name: 'EXSpecialAttackGlacialCrush_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackGlacialCrush_1',
    },
  },
  'ChainAttackFrostboundOath_0:sheerDmg': {
    sheet: 'Yidhari',
    name: 'ChainAttackFrostboundOath_0:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackFrostboundOath_0',
    },
  },
  'ChainAttackFrostboundOath_0:dazeBuildup': {
    sheet: 'Yidhari',
    name: 'ChainAttackFrostboundOath_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackFrostboundOath_0',
    },
  },
  'ChainAttackFrostboundOath_0:anomBuildup': {
    sheet: 'Yidhari',
    name: 'ChainAttackFrostboundOath_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackFrostboundOath_0',
    },
  },
  'ChainAttackFrostboundOath_1:sheerDmg': {
    sheet: 'Yidhari',
    name: 'ChainAttackFrostboundOath_1:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackFrostboundOath_1',
    },
  },
  'ChainAttackFrostboundOath_1:dazeBuildup': {
    sheet: 'Yidhari',
    name: 'ChainAttackFrostboundOath_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackFrostboundOath_1',
    },
  },
  'ChainAttackFrostboundOath_1:anomBuildup': {
    sheet: 'Yidhari',
    name: 'ChainAttackFrostboundOath_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackFrostboundOath_1',
    },
  },
  'UltimateFinalActCrossingTheRiverOfRegret_0:sheerDmg': {
    sheet: 'Yidhari',
    name: 'UltimateFinalActCrossingTheRiverOfRegret_0:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateFinalActCrossingTheRiverOfRegret_0',
    },
  },
  'UltimateFinalActCrossingTheRiverOfRegret_0:dazeBuildup': {
    sheet: 'Yidhari',
    name: 'UltimateFinalActCrossingTheRiverOfRegret_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateFinalActCrossingTheRiverOfRegret_0',
    },
  },
  'UltimateFinalActCrossingTheRiverOfRegret_0:anomBuildup': {
    sheet: 'Yidhari',
    name: 'UltimateFinalActCrossingTheRiverOfRegret_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateFinalActCrossingTheRiverOfRegret_0',
    },
  },
  'QuickAssistFrostshockReinforcement_0:sheerDmg': {
    sheet: 'Yidhari',
    name: 'QuickAssistFrostshockReinforcement_0:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistFrostshockReinforcement_0',
    },
  },
  'QuickAssistFrostshockReinforcement_0:dazeBuildup': {
    sheet: 'Yidhari',
    name: 'QuickAssistFrostshockReinforcement_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistFrostshockReinforcement_0',
    },
  },
  'QuickAssistFrostshockReinforcement_0:anomBuildup': {
    sheet: 'Yidhari',
    name: 'QuickAssistFrostshockReinforcement_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistFrostshockReinforcement_0',
    },
  },
  'DefensiveAssistFlashquakeRejection_0:sheerDmg': {
    sheet: 'Yidhari',
    name: 'DefensiveAssistFlashquakeRejection_0:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistFlashquakeRejection_0',
    },
  },
  'DefensiveAssistFlashquakeRejection_0:dazeBuildup': {
    sheet: 'Yidhari',
    name: 'DefensiveAssistFlashquakeRejection_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistFlashquakeRejection_0',
    },
  },
  'DefensiveAssistFlashquakeRejection_0:anomBuildup': {
    sheet: 'Yidhari',
    name: 'DefensiveAssistFlashquakeRejection_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistFlashquakeRejection_0',
    },
  },
  'DefensiveAssistFlashquakeRejection_1:sheerDmg': {
    sheet: 'Yidhari',
    name: 'DefensiveAssistFlashquakeRejection_1:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistFlashquakeRejection_1',
    },
  },
  'DefensiveAssistFlashquakeRejection_1:dazeBuildup': {
    sheet: 'Yidhari',
    name: 'DefensiveAssistFlashquakeRejection_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistFlashquakeRejection_1',
    },
  },
  'DefensiveAssistFlashquakeRejection_1:anomBuildup': {
    sheet: 'Yidhari',
    name: 'DefensiveAssistFlashquakeRejection_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistFlashquakeRejection_1',
    },
  },
  'DefensiveAssistFlashquakeRejection_2:sheerDmg': {
    sheet: 'Yidhari',
    name: 'DefensiveAssistFlashquakeRejection_2:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistFlashquakeRejection_2',
    },
  },
  'DefensiveAssistFlashquakeRejection_2:dazeBuildup': {
    sheet: 'Yidhari',
    name: 'DefensiveAssistFlashquakeRejection_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistFlashquakeRejection_2',
    },
  },
  'DefensiveAssistFlashquakeRejection_2:anomBuildup': {
    sheet: 'Yidhari',
    name: 'DefensiveAssistFlashquakeRejection_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistFlashquakeRejection_2',
    },
  },
  'AssistFollowUpGlacialOnslaught_0:sheerDmg': {
    sheet: 'Yidhari',
    name: 'AssistFollowUpGlacialOnslaught_0:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpGlacialOnslaught_0',
    },
  },
  'AssistFollowUpGlacialOnslaught_0:dazeBuildup': {
    sheet: 'Yidhari',
    name: 'AssistFollowUpGlacialOnslaught_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpGlacialOnslaught_0',
    },
  },
  'AssistFollowUpGlacialOnslaught_0:anomBuildup': {
    sheet: 'Yidhari',
    name: 'AssistFollowUpGlacialOnslaught_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpGlacialOnslaught_0',
    },
  },
  m6_heal: {
    sheet: 'Yidhari',
    name: 'm6_heal',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'heal',
      sheet: 'Yidhari',
      name: 'm6_heal',
    },
  },
} as const
