// WARNING: Generated file, do not modify
export const formulas = {
  sheerDmgInst: {
    sheet: 'Yidhari',
    name: 'sheerDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'sheerDmgBase',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'sheer',
      name: 'sheerDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Yidhari',
    name: 'anomalyDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_ice: {
    sheet: 'Yidhari',
    name: 'disorderDmgInst_ice',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'disorder',
      name: 'disorderDmgInst_ice',
    },
  },
  vortexDmgInst_ice: {
    sheet: 'Yidhari',
    name: 'vortexDmgInst_ice',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'vortex',
      name: 'vortexDmgInst_ice',
    },
  },
  abloomDmgInst: {
    sheet: 'Yidhari',
    name: 'abloomDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Yidhari',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yidhari',
      attribute: 'ice',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Yidhari',
    name: 'dazeInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'dazeBuildupBase',
      sheet: 'Yidhari',
      attribute: 'ice',
      name: 'dazeInst',
    },
  },
  BasicAttackCrushingStrike_0: {
    sheet: 'Yidhari',
    name: 'BasicAttackCrushingStrike_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackCrushingStrike_0',
    },
  },
  BasicAttackCrushingStrike_1: {
    sheet: 'Yidhari',
    name: 'BasicAttackCrushingStrike_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackCrushingStrike_1',
    },
  },
  BasicAttackCrushingStrike_2: {
    sheet: 'Yidhari',
    name: 'BasicAttackCrushingStrike_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackCrushingStrike_2',
    },
  },
  BasicAttackCrushingStrike_3: {
    sheet: 'Yidhari',
    name: 'BasicAttackCrushingStrike_3',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackCrushingStrike_3',
    },
  },
  BasicAttackFrostbiteEmbrace_0: {
    sheet: 'Yidhari',
    name: 'BasicAttackFrostbiteEmbrace_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFrostbiteEmbrace_0',
    },
  },
  BasicAttackFrostbiteEmbrace_1: {
    sheet: 'Yidhari',
    name: 'BasicAttackFrostbiteEmbrace_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFrostbiteEmbrace_1',
    },
  },
  BasicAttackFrostbiteEmbrace_2: {
    sheet: 'Yidhari',
    name: 'BasicAttackFrostbiteEmbrace_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFrostbiteEmbrace_2',
    },
  },
  BasicAttackFrostbiteEmbrace_3: {
    sheet: 'Yidhari',
    name: 'BasicAttackFrostbiteEmbrace_3',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFrostbiteEmbrace_3',
    },
  },
  FrostsCrushingWeight_0: {
    sheet: 'Yidhari',
    name: 'FrostsCrushingWeight_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'FrostsCrushingWeight_0',
    },
  },
  DashAttackFrostbloomImpact_0: {
    sheet: 'Yidhari',
    name: 'DashAttackFrostbloomImpact_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackFrostbloomImpact_0',
    },
  },
  DodgeCounterIcehaulReverb_0: {
    sheet: 'Yidhari',
    name: 'DodgeCounterIcehaulReverb_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterIcehaulReverb_0',
    },
  },
  SpecialAttackCeaseThoughts_0: {
    sheet: 'Yidhari',
    name: 'SpecialAttackCeaseThoughts_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackCeaseThoughts_0',
    },
  },
  EXSpecialAttackFrostCoil_0: {
    sheet: 'Yidhari',
    name: 'EXSpecialAttackFrostCoil_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackFrostCoil_0',
    },
  },
  SpecialAttackSurgingColdCrushingPursuit_0: {
    sheet: 'Yidhari',
    name: 'SpecialAttackSurgingColdCrushingPursuit_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackSurgingColdCrushingPursuit_0',
    },
  },
  EXSpecialAttackGlacialCrush_0: {
    sheet: 'Yidhari',
    name: 'EXSpecialAttackGlacialCrush_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackGlacialCrush_0',
    },
  },
  EXSpecialAttackGlacialCrush_1: {
    sheet: 'Yidhari',
    name: 'EXSpecialAttackGlacialCrush_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackGlacialCrush_1',
    },
  },
  ChainAttackFrostboundOath_0: {
    sheet: 'Yidhari',
    name: 'ChainAttackFrostboundOath_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackFrostboundOath_0',
    },
  },
  ChainAttackFrostboundOath_1: {
    sheet: 'Yidhari',
    name: 'ChainAttackFrostboundOath_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackFrostboundOath_1',
    },
  },
  UltimateFinalActCrossingTheRiverOfRegret_0: {
    sheet: 'Yidhari',
    name: 'UltimateFinalActCrossingTheRiverOfRegret_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateFinalActCrossingTheRiverOfRegret_0',
    },
  },
  QuickAssistFrostshockReinforcement_0: {
    sheet: 'Yidhari',
    name: 'QuickAssistFrostshockReinforcement_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistFrostshockReinforcement_0',
    },
  },
  DefensiveAssistFlashquakeRejection_0: {
    sheet: 'Yidhari',
    name: 'DefensiveAssistFlashquakeRejection_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistFlashquakeRejection_0',
    },
  },
  DefensiveAssistFlashquakeRejection_1: {
    sheet: 'Yidhari',
    name: 'DefensiveAssistFlashquakeRejection_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistFlashquakeRejection_1',
    },
  },
  DefensiveAssistFlashquakeRejection_2: {
    sheet: 'Yidhari',
    name: 'DefensiveAssistFlashquakeRejection_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistFlashquakeRejection_2',
    },
  },
  AssistFollowUpGlacialOnslaught_0: {
    sheet: 'Yidhari',
    name: 'AssistFollowUpGlacialOnslaught_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yidhari',
      attribute: 'ice',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpGlacialOnslaught_0',
    },
  },
  m6_heal: {
    sheet: 'Yidhari',
    name: 'm6_heal',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'healBase',
      sheet: 'Yidhari',
      name: 'm6_heal',
    },
  },
} as const
