export declare const allRelicPlanarSlotKeys: readonly ["sphere", "rope"];
export type RelicPlanarSlotKey = (typeof allRelicPlanarSlotKeys)[number];
export declare const allRelicCavernSlotKeys: readonly ["head", "hands", "body", "feet"];
export type RelicCavernSlotKey = (typeof allRelicCavernSlotKeys)[number];
export declare const allRelicSlotKeys: readonly ["head", "hands", "body", "feet", "sphere", "rope"];
export type RelicSlotKey = (typeof allRelicSlotKeys)[number];
export declare const allRelicCavernSetKeys: readonly ["BandOfSizzlingThunder", "ChampionOfStreetwiseBoxing", "EagleOfTwilightLine", "FiresmithOfLavaForging", "GeniusOfBrilliantStars", "GuardOfWutheringSnow", "HeroOfTriumphantSong", "HunterOfGlacialForest", "IronCavalryAgainstTheScourge", "KnightOfPurityPalace", "LongevousDisciple", "MessengerTraversingHackerspace", "MusketeerOfWildWheat", "PasserbyOfWanderingCloud", "PioneerDiverOfDeadWaters", "PoetOfMourningCollapse", "PrisonerInDeepConfinement", "SacerdosRelivedOrdeal", "ScholarLostInErudition", "TheAshblazingGrandDuke", "TheWindSoaringValorous", "ThiefOfShootingMeteor", "WastelanderOfBanditryDesert", "WatchmakerMasterOfDreamMachinations"];
export type RelicCavernSetKey = (typeof allRelicCavernSetKeys)[number];
export declare const allRelicPlanarSetKeys: readonly ["BelobogOfTheArchitects", "BoneCollectionsSereneDemesne", "BrokenKeel", "CelestialDifferentiator", "DuranDynastyOfRunningWolves", "FirmamentFrontlineGlamoth", "FleetOfTheAgeless", "ForgeOfTheKalpagniLantern", "GiantTreeOfRaptBrooding", "InertSalsotto", "IzumoGenseiAndTakamaDivineRealm", "LushakaTheSunkenSeas", "PanCosmicCommercialEnterprise", "PenaconyLandOfTheDreams", "RutilantArena", "SigoniaTheUnclaimedDesolation", "SpaceSealingStation", "SprightlyVonwacq", "TaliaKingdomOfBanditry", "TheWondrousBananAmusementPark"];
export type RelicPlanarSetKey = (typeof allRelicPlanarSetKeys)[number];
export declare const allRelicSetKeys: readonly ["BandOfSizzlingThunder", "ChampionOfStreetwiseBoxing", "EagleOfTwilightLine", "FiresmithOfLavaForging", "GeniusOfBrilliantStars", "GuardOfWutheringSnow", "HeroOfTriumphantSong", "HunterOfGlacialForest", "IronCavalryAgainstTheScourge", "KnightOfPurityPalace", "LongevousDisciple", "MessengerTraversingHackerspace", "MusketeerOfWildWheat", "PasserbyOfWanderingCloud", "PioneerDiverOfDeadWaters", "PoetOfMourningCollapse", "PrisonerInDeepConfinement", "SacerdosRelivedOrdeal", "ScholarLostInErudition", "TheAshblazingGrandDuke", "TheWindSoaringValorous", "ThiefOfShootingMeteor", "WastelanderOfBanditryDesert", "WatchmakerMasterOfDreamMachinations", "BelobogOfTheArchitects", "BoneCollectionsSereneDemesne", "BrokenKeel", "CelestialDifferentiator", "DuranDynastyOfRunningWolves", "FirmamentFrontlineGlamoth", "FleetOfTheAgeless", "ForgeOfTheKalpagniLantern", "GiantTreeOfRaptBrooding", "InertSalsotto", "IzumoGenseiAndTakamaDivineRealm", "LushakaTheSunkenSeas", "PanCosmicCommercialEnterprise", "PenaconyLandOfTheDreams", "RutilantArena", "SigoniaTheUnclaimedDesolation", "SpaceSealingStation", "SprightlyVonwacq", "TaliaKingdomOfBanditry", "TheWondrousBananAmusementPark"];
export type RelicSetKey = (typeof allRelicSetKeys)[number];
export declare const allRelicSubStatKeys: readonly ["hp", "atk", "def", "hp_", "atk_", "def_", "spd", "crit_", "crit_dmg_", "eff_", "eff_res_", "brEffect_"];
export type RelicSubStatKey = (typeof allRelicSubStatKeys)[number];
export declare const allElementalDmgMainStatKeys: readonly ["physical_dmg_", "fire_dmg_", "ice_dmg_", "lightning_dmg_", "wind_dmg_", "quantum_dmg_", "imaginary_dmg_"];
export declare const allRelicMainStatKeys: readonly ["hp", "atk", "hp_", "atk_", "def_", "crit_", "crit_dmg_", "heal_", "eff_", "spd", "physical_dmg_", "fire_dmg_", "ice_dmg_", "lightning_dmg_", "wind_dmg_", "quantum_dmg_", "imaginary_dmg_", "brEffect_", "enerRegen_"];
export type RelicMainStatKey = (typeof allRelicMainStatKeys)[number];
export declare const allRelicRarityKeys: readonly [2, 3, 4, 5];
export type RelicRarityKey = (typeof allRelicRarityKeys)[number];
export declare function isRelicRarityKey(rarity: unknown): rarity is RelicRarityKey;
export declare const allRelicSetCountKeys: readonly [2, 4];
export type RelicSetCountKey = (typeof allRelicSetCountKeys)[number];
export declare const relicMaxLevel: Record<RelicRarityKey, number>;
export declare const relicSubstatRollData: Record<RelicRarityKey, {
    low: number;
    high: number;
    numUpgrades: number;
}>;
export declare const relicSlotToMainStatKeys: Record<RelicSlotKey, RelicMainStatKey[]>;
export declare const allRelicMainSubStatKeys: ("hp" | "atk" | "def" | "hp_" | "atk_" | "def_" | "spd" | "crit_" | "crit_dmg_" | "eff_" | "eff_res_" | "brEffect_" | "physical_dmg_" | "fire_dmg_" | "ice_dmg_" | "lightning_dmg_" | "wind_dmg_" | "quantum_dmg_" | "imaginary_dmg_" | "heal_" | "enerRegen_")[];
export type RelicMainSubStatKey = (typeof allRelicMainSubStatKeys)[number];
export declare function isCavernRelicSetKey(key: RelicSetKey): key is RelicCavernSetKey;
export declare function isPlanarRelicSetKey(key: RelicSetKey): key is RelicPlanarSetKey;
export declare function isRelicSetKey(key: unknown): key is RelicSetKey;
//# sourceMappingURL=relic.d.ts.map