// WARNING: Generated file, do not modify
export * from './char'
export * from './common'
export * from './disc'
export * from './wengine'

import * as char from './char'
import * as common from './common'
import * as disc from './disc'
import * as wengine from './wengine'

const {
  Alice,
  Anby,
  Anton,
  AstraYao,
  Ben,
  Billy,
  Burnice,
  Caesar,
  Corin,
  Ellen,
  Evelyn,
  Grace,
  Harumasa,
  Hugo,
  Jane,
  JuFufu,
  Koleda,
  Lighter,
  Lucy,
  Lycaon,
  Miyabi,
  Nekomata,
  Nicole,
  OrphieMagus,
  PanYinhu,
  Piper,
  Pulchra,
  Qingyi,
  Rina,
  Seed,
  Seth,
  Soldier0Anby,
  Soldier11,
  Soukaku,
  Trigger,
  Vivian,
  Yanagi,
  Yixuan,
  Yuzuha,
  ZhuYuan,
} = char
const {
  AstralVoice,
  BranchBladeSong,
  ChaosJazz,
  ChaoticMetal,
  DawnsBloom,
  FangedMetal,
  FreedomBlues,
  HormonePunk,
  InfernoMetal,
  KingOfTheSummit,
  MoonlightLullaby,
  PhaethonsMelody,
  PolarMetal,
  ProtoPunk,
  PufferElectro,
  ShadowHarmony,
  ShockstarDisco,
  SoulRock,
  SwingJazz,
  ThunderMetal,
  WoodpeckerElectro,
  YunkuiTales,
} = disc
const {
  BashfulDemon,
  BellicoseBlaze,
  BigCylinder,
  BlazingLaurel,
  BoxCutter,
  BunnyBand,
  CannonRotor,
  CinderCobalt,
  CordisGermina,
  DeepSeaVisitor,
  DemaraBatteryMarkII,
  DrillRigRedAxis,
  ElectroLipGloss,
  ElegantVanity,
  FlamemakerShaker,
  FlightOfFancy,
  FusionCompiler,
  GildedBlossom,
  HailstormShrine,
  HeartstringNocturne,
  HellfireGears,
  Housekeeper,
  IceJadeTeapot,
  IdentityBase,
  IdentityInflection,
  KaboomTheCannon,
  LunarDecrescent,
  LunarNoviluna,
  LunarPleniluna,
  MagneticStormAlpha,
  MagneticStormBravo,
  MagneticStormCharlie,
  MarcatoDesire,
  Metanukimorphosis,
  MyriadEclipse,
  OriginalTransmorpher,
  PeacekeeperSpecialized,
  PracticedPerfection,
  PreciousFossilizedCore,
  PuzzleSphere,
  QingmingBirdcage,
  RadiowaveJourney,
  RainforestGourmet,
  ReelProjector,
  ReverbMarkI,
  ReverbMarkII,
  ReverbMarkIII,
  RiotSuppressorMarkVI,
  RoaringFurnace,
  RoaringRide,
  SeveredInnocence,
  SharpenedStinger,
  SixShooter,
  SliceOfTime,
  SpectralGaze,
  SpringEmbrace,
  StarlightEngine,
  StarlightEngineReplica,
  SteamOven,
  SteelCushion,
  StreetSuperstar,
  TheBrimstone,
  TheRestrained,
  TheVault,
  Timeweaver,
  TremorTrigramVessel,
  TusksOfFury,
  UnfetteredGameBall,
  VortexArrow,
  VortexHatchet,
  VortexRevolver,
  WeepingCradle,
  WeepingGemini,
  ZanshinHerbCase,
} = wengine
const { enemyMeta: enemy, anomalyMeta: anomaly } = common

export const conditionals = {
  Alice: Alice.conditionals,
  Anby: Anby.conditionals,
  Anton: Anton.conditionals,
  AstraYao: AstraYao.conditionals,
  Ben: Ben.conditionals,
  Billy: Billy.conditionals,
  Burnice: Burnice.conditionals,
  Caesar: Caesar.conditionals,
  Corin: Corin.conditionals,
  Ellen: Ellen.conditionals,
  Evelyn: Evelyn.conditionals,
  Grace: Grace.conditionals,
  Harumasa: Harumasa.conditionals,
  Hugo: Hugo.conditionals,
  Jane: Jane.conditionals,
  JuFufu: JuFufu.conditionals,
  Koleda: Koleda.conditionals,
  Lighter: Lighter.conditionals,
  Lucy: Lucy.conditionals,
  Lycaon: Lycaon.conditionals,
  Miyabi: Miyabi.conditionals,
  Nekomata: Nekomata.conditionals,
  Nicole: Nicole.conditionals,
  OrphieMagus: OrphieMagus.conditionals,
  PanYinhu: PanYinhu.conditionals,
  Piper: Piper.conditionals,
  Pulchra: Pulchra.conditionals,
  Qingyi: Qingyi.conditionals,
  Rina: Rina.conditionals,
  Seed: Seed.conditionals,
  Seth: Seth.conditionals,
  Soldier0Anby: Soldier0Anby.conditionals,
  Soldier11: Soldier11.conditionals,
  Soukaku: Soukaku.conditionals,
  Trigger: Trigger.conditionals,
  Vivian: Vivian.conditionals,
  Yanagi: Yanagi.conditionals,
  Yixuan: Yixuan.conditionals,
  Yuzuha: Yuzuha.conditionals,
  ZhuYuan: ZhuYuan.conditionals,
  AstralVoice: AstralVoice.conditionals,
  BranchBladeSong: BranchBladeSong.conditionals,
  ChaosJazz: ChaosJazz.conditionals,
  ChaoticMetal: ChaoticMetal.conditionals,
  DawnsBloom: DawnsBloom.conditionals,
  FangedMetal: FangedMetal.conditionals,
  FreedomBlues: FreedomBlues.conditionals,
  HormonePunk: HormonePunk.conditionals,
  InfernoMetal: InfernoMetal.conditionals,
  KingOfTheSummit: KingOfTheSummit.conditionals,
  MoonlightLullaby: MoonlightLullaby.conditionals,
  PhaethonsMelody: PhaethonsMelody.conditionals,
  PolarMetal: PolarMetal.conditionals,
  ProtoPunk: ProtoPunk.conditionals,
  PufferElectro: PufferElectro.conditionals,
  ShadowHarmony: ShadowHarmony.conditionals,
  ShockstarDisco: ShockstarDisco.conditionals,
  SoulRock: SoulRock.conditionals,
  SwingJazz: SwingJazz.conditionals,
  ThunderMetal: ThunderMetal.conditionals,
  WoodpeckerElectro: WoodpeckerElectro.conditionals,
  YunkuiTales: YunkuiTales.conditionals,
  BashfulDemon: BashfulDemon.conditionals,
  BellicoseBlaze: BellicoseBlaze.conditionals,
  BigCylinder: BigCylinder.conditionals,
  BlazingLaurel: BlazingLaurel.conditionals,
  BoxCutter: BoxCutter.conditionals,
  BunnyBand: BunnyBand.conditionals,
  CannonRotor: CannonRotor.conditionals,
  CinderCobalt: CinderCobalt.conditionals,
  CordisGermina: CordisGermina.conditionals,
  DeepSeaVisitor: DeepSeaVisitor.conditionals,
  DemaraBatteryMarkII: DemaraBatteryMarkII.conditionals,
  DrillRigRedAxis: DrillRigRedAxis.conditionals,
  ElectroLipGloss: ElectroLipGloss.conditionals,
  ElegantVanity: ElegantVanity.conditionals,
  FlamemakerShaker: FlamemakerShaker.conditionals,
  FlightOfFancy: FlightOfFancy.conditionals,
  FusionCompiler: FusionCompiler.conditionals,
  GildedBlossom: GildedBlossom.conditionals,
  HailstormShrine: HailstormShrine.conditionals,
  HeartstringNocturne: HeartstringNocturne.conditionals,
  HellfireGears: HellfireGears.conditionals,
  Housekeeper: Housekeeper.conditionals,
  IceJadeTeapot: IceJadeTeapot.conditionals,
  IdentityBase: IdentityBase.conditionals,
  IdentityInflection: IdentityInflection.conditionals,
  KaboomTheCannon: KaboomTheCannon.conditionals,
  LunarDecrescent: LunarDecrescent.conditionals,
  LunarNoviluna: LunarNoviluna.conditionals,
  LunarPleniluna: LunarPleniluna.conditionals,
  MagneticStormAlpha: MagneticStormAlpha.conditionals,
  MagneticStormBravo: MagneticStormBravo.conditionals,
  MagneticStormCharlie: MagneticStormCharlie.conditionals,
  MarcatoDesire: MarcatoDesire.conditionals,
  Metanukimorphosis: Metanukimorphosis.conditionals,
  MyriadEclipse: MyriadEclipse.conditionals,
  OriginalTransmorpher: OriginalTransmorpher.conditionals,
  PeacekeeperSpecialized: PeacekeeperSpecialized.conditionals,
  PracticedPerfection: PracticedPerfection.conditionals,
  PreciousFossilizedCore: PreciousFossilizedCore.conditionals,
  PuzzleSphere: PuzzleSphere.conditionals,
  QingmingBirdcage: QingmingBirdcage.conditionals,
  RadiowaveJourney: RadiowaveJourney.conditionals,
  RainforestGourmet: RainforestGourmet.conditionals,
  ReelProjector: ReelProjector.conditionals,
  ReverbMarkI: ReverbMarkI.conditionals,
  ReverbMarkII: ReverbMarkII.conditionals,
  ReverbMarkIII: ReverbMarkIII.conditionals,
  RiotSuppressorMarkVI: RiotSuppressorMarkVI.conditionals,
  RoaringFurnace: RoaringFurnace.conditionals,
  RoaringRide: RoaringRide.conditionals,
  SeveredInnocence: SeveredInnocence.conditionals,
  SharpenedStinger: SharpenedStinger.conditionals,
  SixShooter: SixShooter.conditionals,
  SliceOfTime: SliceOfTime.conditionals,
  SpectralGaze: SpectralGaze.conditionals,
  SpringEmbrace: SpringEmbrace.conditionals,
  StarlightEngine: StarlightEngine.conditionals,
  StarlightEngineReplica: StarlightEngineReplica.conditionals,
  SteamOven: SteamOven.conditionals,
  SteelCushion: SteelCushion.conditionals,
  StreetSuperstar: StreetSuperstar.conditionals,
  TheBrimstone: TheBrimstone.conditionals,
  TheRestrained: TheRestrained.conditionals,
  TheVault: TheVault.conditionals,
  Timeweaver: Timeweaver.conditionals,
  TremorTrigramVessel: TremorTrigramVessel.conditionals,
  TusksOfFury: TusksOfFury.conditionals,
  UnfetteredGameBall: UnfetteredGameBall.conditionals,
  VortexArrow: VortexArrow.conditionals,
  VortexHatchet: VortexHatchet.conditionals,
  VortexRevolver: VortexRevolver.conditionals,
  WeepingCradle: WeepingCradle.conditionals,
  WeepingGemini: WeepingGemini.conditionals,
  ZanshinHerbCase: ZanshinHerbCase.conditionals,
  enemy: enemy.conditionals,
  anomaly: anomaly.conditionals,
} as any

export const formulas = {
  Alice: Alice.formulas,
  Anby: Anby.formulas,
  Anton: Anton.formulas,
  AstraYao: AstraYao.formulas,
  Ben: Ben.formulas,
  Billy: Billy.formulas,
  Burnice: Burnice.formulas,
  Caesar: Caesar.formulas,
  Corin: Corin.formulas,
  Ellen: Ellen.formulas,
  Evelyn: Evelyn.formulas,
  Grace: Grace.formulas,
  Harumasa: Harumasa.formulas,
  Hugo: Hugo.formulas,
  Jane: Jane.formulas,
  JuFufu: JuFufu.formulas,
  Koleda: Koleda.formulas,
  Lighter: Lighter.formulas,
  Lucy: Lucy.formulas,
  Lycaon: Lycaon.formulas,
  Miyabi: Miyabi.formulas,
  Nekomata: Nekomata.formulas,
  Nicole: Nicole.formulas,
  OrphieMagus: OrphieMagus.formulas,
  PanYinhu: PanYinhu.formulas,
  Piper: Piper.formulas,
  Pulchra: Pulchra.formulas,
  Qingyi: Qingyi.formulas,
  Rina: Rina.formulas,
  Seed: Seed.formulas,
  Seth: Seth.formulas,
  Soldier0Anby: Soldier0Anby.formulas,
  Soldier11: Soldier11.formulas,
  Soukaku: Soukaku.formulas,
  Trigger: Trigger.formulas,
  Vivian: Vivian.formulas,
  Yanagi: Yanagi.formulas,
  Yixuan: Yixuan.formulas,
  Yuzuha: Yuzuha.formulas,
  ZhuYuan: ZhuYuan.formulas,
  AstralVoice: AstralVoice.formulas,
  BranchBladeSong: BranchBladeSong.formulas,
  ChaosJazz: ChaosJazz.formulas,
  ChaoticMetal: ChaoticMetal.formulas,
  DawnsBloom: DawnsBloom.formulas,
  FangedMetal: FangedMetal.formulas,
  FreedomBlues: FreedomBlues.formulas,
  HormonePunk: HormonePunk.formulas,
  InfernoMetal: InfernoMetal.formulas,
  KingOfTheSummit: KingOfTheSummit.formulas,
  MoonlightLullaby: MoonlightLullaby.formulas,
  PhaethonsMelody: PhaethonsMelody.formulas,
  PolarMetal: PolarMetal.formulas,
  ProtoPunk: ProtoPunk.formulas,
  PufferElectro: PufferElectro.formulas,
  ShadowHarmony: ShadowHarmony.formulas,
  ShockstarDisco: ShockstarDisco.formulas,
  SoulRock: SoulRock.formulas,
  SwingJazz: SwingJazz.formulas,
  ThunderMetal: ThunderMetal.formulas,
  WoodpeckerElectro: WoodpeckerElectro.formulas,
  YunkuiTales: YunkuiTales.formulas,
  BashfulDemon: BashfulDemon.formulas,
  BellicoseBlaze: BellicoseBlaze.formulas,
  BigCylinder: BigCylinder.formulas,
  BlazingLaurel: BlazingLaurel.formulas,
  BoxCutter: BoxCutter.formulas,
  BunnyBand: BunnyBand.formulas,
  CannonRotor: CannonRotor.formulas,
  CinderCobalt: CinderCobalt.formulas,
  CordisGermina: CordisGermina.formulas,
  DeepSeaVisitor: DeepSeaVisitor.formulas,
  DemaraBatteryMarkII: DemaraBatteryMarkII.formulas,
  DrillRigRedAxis: DrillRigRedAxis.formulas,
  ElectroLipGloss: ElectroLipGloss.formulas,
  ElegantVanity: ElegantVanity.formulas,
  FlamemakerShaker: FlamemakerShaker.formulas,
  FlightOfFancy: FlightOfFancy.formulas,
  FusionCompiler: FusionCompiler.formulas,
  GildedBlossom: GildedBlossom.formulas,
  HailstormShrine: HailstormShrine.formulas,
  HeartstringNocturne: HeartstringNocturne.formulas,
  HellfireGears: HellfireGears.formulas,
  Housekeeper: Housekeeper.formulas,
  IceJadeTeapot: IceJadeTeapot.formulas,
  IdentityBase: IdentityBase.formulas,
  IdentityInflection: IdentityInflection.formulas,
  KaboomTheCannon: KaboomTheCannon.formulas,
  LunarDecrescent: LunarDecrescent.formulas,
  LunarNoviluna: LunarNoviluna.formulas,
  LunarPleniluna: LunarPleniluna.formulas,
  MagneticStormAlpha: MagneticStormAlpha.formulas,
  MagneticStormBravo: MagneticStormBravo.formulas,
  MagneticStormCharlie: MagneticStormCharlie.formulas,
  MarcatoDesire: MarcatoDesire.formulas,
  Metanukimorphosis: Metanukimorphosis.formulas,
  MyriadEclipse: MyriadEclipse.formulas,
  OriginalTransmorpher: OriginalTransmorpher.formulas,
  PeacekeeperSpecialized: PeacekeeperSpecialized.formulas,
  PracticedPerfection: PracticedPerfection.formulas,
  PreciousFossilizedCore: PreciousFossilizedCore.formulas,
  PuzzleSphere: PuzzleSphere.formulas,
  QingmingBirdcage: QingmingBirdcage.formulas,
  RadiowaveJourney: RadiowaveJourney.formulas,
  RainforestGourmet: RainforestGourmet.formulas,
  ReelProjector: ReelProjector.formulas,
  ReverbMarkI: ReverbMarkI.formulas,
  ReverbMarkII: ReverbMarkII.formulas,
  ReverbMarkIII: ReverbMarkIII.formulas,
  RiotSuppressorMarkVI: RiotSuppressorMarkVI.formulas,
  RoaringFurnace: RoaringFurnace.formulas,
  RoaringRide: RoaringRide.formulas,
  SeveredInnocence: SeveredInnocence.formulas,
  SharpenedStinger: SharpenedStinger.formulas,
  SixShooter: SixShooter.formulas,
  SliceOfTime: SliceOfTime.formulas,
  SpectralGaze: SpectralGaze.formulas,
  SpringEmbrace: SpringEmbrace.formulas,
  StarlightEngine: StarlightEngine.formulas,
  StarlightEngineReplica: StarlightEngineReplica.formulas,
  SteamOven: SteamOven.formulas,
  SteelCushion: SteelCushion.formulas,
  StreetSuperstar: StreetSuperstar.formulas,
  TheBrimstone: TheBrimstone.formulas,
  TheRestrained: TheRestrained.formulas,
  TheVault: TheVault.formulas,
  Timeweaver: Timeweaver.formulas,
  TremorTrigramVessel: TremorTrigramVessel.formulas,
  TusksOfFury: TusksOfFury.formulas,
  UnfetteredGameBall: UnfetteredGameBall.formulas,
  VortexArrow: VortexArrow.formulas,
  VortexHatchet: VortexHatchet.formulas,
  VortexRevolver: VortexRevolver.formulas,
  WeepingCradle: WeepingCradle.formulas,
  WeepingGemini: WeepingGemini.formulas,
  ZanshinHerbCase: ZanshinHerbCase.formulas,
  enemy: enemy.formulas,
  anomaly: anomaly.formulas,
} as any

export const buffs = {
  Alice: Alice.buffs,
  Anby: Anby.buffs,
  Anton: Anton.buffs,
  AstraYao: AstraYao.buffs,
  Ben: Ben.buffs,
  Billy: Billy.buffs,
  Burnice: Burnice.buffs,
  Caesar: Caesar.buffs,
  Corin: Corin.buffs,
  Ellen: Ellen.buffs,
  Evelyn: Evelyn.buffs,
  Grace: Grace.buffs,
  Harumasa: Harumasa.buffs,
  Hugo: Hugo.buffs,
  Jane: Jane.buffs,
  JuFufu: JuFufu.buffs,
  Koleda: Koleda.buffs,
  Lighter: Lighter.buffs,
  Lucy: Lucy.buffs,
  Lycaon: Lycaon.buffs,
  Miyabi: Miyabi.buffs,
  Nekomata: Nekomata.buffs,
  Nicole: Nicole.buffs,
  OrphieMagus: OrphieMagus.buffs,
  PanYinhu: PanYinhu.buffs,
  Piper: Piper.buffs,
  Pulchra: Pulchra.buffs,
  Qingyi: Qingyi.buffs,
  Rina: Rina.buffs,
  Seed: Seed.buffs,
  Seth: Seth.buffs,
  Soldier0Anby: Soldier0Anby.buffs,
  Soldier11: Soldier11.buffs,
  Soukaku: Soukaku.buffs,
  Trigger: Trigger.buffs,
  Vivian: Vivian.buffs,
  Yanagi: Yanagi.buffs,
  Yixuan: Yixuan.buffs,
  Yuzuha: Yuzuha.buffs,
  ZhuYuan: ZhuYuan.buffs,
  AstralVoice: AstralVoice.buffs,
  BranchBladeSong: BranchBladeSong.buffs,
  ChaosJazz: ChaosJazz.buffs,
  ChaoticMetal: ChaoticMetal.buffs,
  DawnsBloom: DawnsBloom.buffs,
  FangedMetal: FangedMetal.buffs,
  FreedomBlues: FreedomBlues.buffs,
  HormonePunk: HormonePunk.buffs,
  InfernoMetal: InfernoMetal.buffs,
  KingOfTheSummit: KingOfTheSummit.buffs,
  MoonlightLullaby: MoonlightLullaby.buffs,
  PhaethonsMelody: PhaethonsMelody.buffs,
  PolarMetal: PolarMetal.buffs,
  ProtoPunk: ProtoPunk.buffs,
  PufferElectro: PufferElectro.buffs,
  ShadowHarmony: ShadowHarmony.buffs,
  ShockstarDisco: ShockstarDisco.buffs,
  SoulRock: SoulRock.buffs,
  SwingJazz: SwingJazz.buffs,
  ThunderMetal: ThunderMetal.buffs,
  WoodpeckerElectro: WoodpeckerElectro.buffs,
  YunkuiTales: YunkuiTales.buffs,
  BashfulDemon: BashfulDemon.buffs,
  BellicoseBlaze: BellicoseBlaze.buffs,
  BigCylinder: BigCylinder.buffs,
  BlazingLaurel: BlazingLaurel.buffs,
  BoxCutter: BoxCutter.buffs,
  BunnyBand: BunnyBand.buffs,
  CannonRotor: CannonRotor.buffs,
  CinderCobalt: CinderCobalt.buffs,
  CordisGermina: CordisGermina.buffs,
  DeepSeaVisitor: DeepSeaVisitor.buffs,
  DemaraBatteryMarkII: DemaraBatteryMarkII.buffs,
  DrillRigRedAxis: DrillRigRedAxis.buffs,
  ElectroLipGloss: ElectroLipGloss.buffs,
  ElegantVanity: ElegantVanity.buffs,
  FlamemakerShaker: FlamemakerShaker.buffs,
  FlightOfFancy: FlightOfFancy.buffs,
  FusionCompiler: FusionCompiler.buffs,
  GildedBlossom: GildedBlossom.buffs,
  HailstormShrine: HailstormShrine.buffs,
  HeartstringNocturne: HeartstringNocturne.buffs,
  HellfireGears: HellfireGears.buffs,
  Housekeeper: Housekeeper.buffs,
  IceJadeTeapot: IceJadeTeapot.buffs,
  IdentityBase: IdentityBase.buffs,
  IdentityInflection: IdentityInflection.buffs,
  KaboomTheCannon: KaboomTheCannon.buffs,
  LunarDecrescent: LunarDecrescent.buffs,
  LunarNoviluna: LunarNoviluna.buffs,
  LunarPleniluna: LunarPleniluna.buffs,
  MagneticStormAlpha: MagneticStormAlpha.buffs,
  MagneticStormBravo: MagneticStormBravo.buffs,
  MagneticStormCharlie: MagneticStormCharlie.buffs,
  MarcatoDesire: MarcatoDesire.buffs,
  Metanukimorphosis: Metanukimorphosis.buffs,
  MyriadEclipse: MyriadEclipse.buffs,
  OriginalTransmorpher: OriginalTransmorpher.buffs,
  PeacekeeperSpecialized: PeacekeeperSpecialized.buffs,
  PracticedPerfection: PracticedPerfection.buffs,
  PreciousFossilizedCore: PreciousFossilizedCore.buffs,
  PuzzleSphere: PuzzleSphere.buffs,
  QingmingBirdcage: QingmingBirdcage.buffs,
  RadiowaveJourney: RadiowaveJourney.buffs,
  RainforestGourmet: RainforestGourmet.buffs,
  ReelProjector: ReelProjector.buffs,
  ReverbMarkI: ReverbMarkI.buffs,
  ReverbMarkII: ReverbMarkII.buffs,
  ReverbMarkIII: ReverbMarkIII.buffs,
  RiotSuppressorMarkVI: RiotSuppressorMarkVI.buffs,
  RoaringFurnace: RoaringFurnace.buffs,
  RoaringRide: RoaringRide.buffs,
  SeveredInnocence: SeveredInnocence.buffs,
  SharpenedStinger: SharpenedStinger.buffs,
  SixShooter: SixShooter.buffs,
  SliceOfTime: SliceOfTime.buffs,
  SpectralGaze: SpectralGaze.buffs,
  SpringEmbrace: SpringEmbrace.buffs,
  StarlightEngine: StarlightEngine.buffs,
  StarlightEngineReplica: StarlightEngineReplica.buffs,
  SteamOven: SteamOven.buffs,
  SteelCushion: SteelCushion.buffs,
  StreetSuperstar: StreetSuperstar.buffs,
  TheBrimstone: TheBrimstone.buffs,
  TheRestrained: TheRestrained.buffs,
  TheVault: TheVault.buffs,
  Timeweaver: Timeweaver.buffs,
  TremorTrigramVessel: TremorTrigramVessel.buffs,
  TusksOfFury: TusksOfFury.buffs,
  UnfetteredGameBall: UnfetteredGameBall.buffs,
  VortexArrow: VortexArrow.buffs,
  VortexHatchet: VortexHatchet.buffs,
  VortexRevolver: VortexRevolver.buffs,
  WeepingCradle: WeepingCradle.buffs,
  WeepingGemini: WeepingGemini.buffs,
  ZanshinHerbCase: ZanshinHerbCase.buffs,
  enemy: enemy.buffs,
  anomaly: anomaly.buffs,
} as any
