// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Corin',
    name: 'standardDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'standardDmgBase',
      sheet: 'Corin',
      attribute: 'physical',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Corin',
    name: 'anomalyDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Corin',
      attribute: 'physical',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_physical: {
    sheet: 'Corin',
    name: 'disorderDmgInst_physical',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Corin',
      attribute: 'physical',
      damageType1: 'disorder',
      name: 'disorderDmgInst_physical',
    },
  },
  vortexDmgInst_physical: {
    sheet: 'Corin',
    name: 'vortexDmgInst_physical',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Corin',
      attribute: 'physical',
      damageType1: 'vortex',
      name: 'vortexDmgInst_physical',
    },
  },
  abloomDmgInst: {
    sheet: 'Corin',
    name: 'abloomDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Corin',
      attribute: 'physical',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Corin',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Corin',
      attribute: 'physical',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Corin',
    name: 'dazeInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'dazeBuildupBase',
      sheet: 'Corin',
      attribute: 'physical',
      name: 'dazeInst',
    },
  },
  BasicAttackWipeout_0: {
    sheet: 'Corin',
    name: 'BasicAttackWipeout_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Corin',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackWipeout_0',
    },
  },
  BasicAttackWipeout_1: {
    sheet: 'Corin',
    name: 'BasicAttackWipeout_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Corin',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackWipeout_1',
    },
  },
  BasicAttackWipeout_2: {
    sheet: 'Corin',
    name: 'BasicAttackWipeout_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Corin',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackWipeout_2',
    },
  },
  BasicAttackWipeout_3: {
    sheet: 'Corin',
    name: 'BasicAttackWipeout_3',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Corin',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackWipeout_3',
    },
  },
  BasicAttackWipeout_4: {
    sheet: 'Corin',
    name: 'BasicAttackWipeout_4',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Corin',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackWipeout_4',
    },
  },
  DashAttackOopsyDaisy_0: {
    sheet: 'Corin',
    name: 'DashAttackOopsyDaisy_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Corin',
      damageType1: 'dash',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttackOopsyDaisy_0',
    },
  },
  DodgeCounterNope_0: {
    sheet: 'Corin',
    name: 'DodgeCounterNope_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Corin',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterNope_0',
    },
  },
  DodgeCounterNope_1: {
    sheet: 'Corin',
    name: 'DodgeCounterNope_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Corin',
      damageType1: 'dodgeCounter',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterNope_1',
    },
  },
  SpecialAttackCleanSweep_0: {
    sheet: 'Corin',
    name: 'SpecialAttackCleanSweep_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Corin',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackCleanSweep_0',
    },
  },
  SpecialAttackCleanSweep_1: {
    sheet: 'Corin',
    name: 'SpecialAttackCleanSweep_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Corin',
      damageType1: 'special',
      attribute: 'physical',
      skillType: 'specialSkill',
      name: 'SpecialAttackCleanSweep_1',
    },
  },
  SpecialAttackCleanSweep_2: {
    sheet: 'Corin',
    name: 'SpecialAttackCleanSweep_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Corin',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackCleanSweep_2',
    },
  },
  EXSpecialAttackSkirtAlert_0: {
    sheet: 'Corin',
    name: 'EXSpecialAttackSkirtAlert_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Corin',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackSkirtAlert_0',
    },
  },
  EXSpecialAttackSkirtAlert_1: {
    sheet: 'Corin',
    name: 'EXSpecialAttackSkirtAlert_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Corin',
      damageType1: 'exSpecial',
      attribute: 'physical',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackSkirtAlert_1',
    },
  },
  EXSpecialAttackSkirtAlert_2: {
    sheet: 'Corin',
    name: 'EXSpecialAttackSkirtAlert_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Corin',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackSkirtAlert_2',
    },
  },
  ChainAttackSorry_0: {
    sheet: 'Corin',
    name: 'ChainAttackSorry_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Corin',
      damageType1: 'chain',
      attribute: 'physical',
      skillType: 'chainSkill',
      name: 'ChainAttackSorry_0',
    },
  },
  UltimateVeryVerySorry_0: {
    sheet: 'Corin',
    name: 'UltimateVeryVerySorry_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Corin',
      damageType1: 'ult',
      attribute: 'physical',
      skillType: 'chainSkill',
      name: 'UltimateVeryVerySorry_0',
    },
  },
  QuickAssistEmergencyMeasures_0: {
    sheet: 'Corin',
    name: 'QuickAssistEmergencyMeasures_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Corin',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistEmergencyMeasures_0',
    },
  },
  QuickAssistEmergencyMeasures_1: {
    sheet: 'Corin',
    name: 'QuickAssistEmergencyMeasures_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Corin',
      damageType1: 'quickAssist',
      attribute: 'physical',
      skillType: 'assistSkill',
      name: 'QuickAssistEmergencyMeasures_1',
    },
  },
  DefensiveAssistPPleaseAllowMe_0: {
    sheet: 'Corin',
    name: 'DefensiveAssistPPleaseAllowMe_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Corin',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistPPleaseAllowMe_0',
    },
  },
  DefensiveAssistPPleaseAllowMe_1: {
    sheet: 'Corin',
    name: 'DefensiveAssistPPleaseAllowMe_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Corin',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistPPleaseAllowMe_1',
    },
  },
  DefensiveAssistPPleaseAllowMe_2: {
    sheet: 'Corin',
    name: 'DefensiveAssistPPleaseAllowMe_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Corin',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistPPleaseAllowMe_2',
    },
  },
  AssistFollowUpQuickSweep_0: {
    sheet: 'Corin',
    name: 'AssistFollowUpQuickSweep_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Corin',
      damageType1: 'assistFollowUp',
      attribute: 'physical',
      skillType: 'assistSkill',
      name: 'AssistFollowUpQuickSweep_0',
    },
  },
  m6_dmg: {
    sheet: 'Corin',
    name: 'm6_dmg',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'standardDmgBase',
      sheet: 'Corin',
      damageType1: 'elemental',
      name: 'm6_dmg',
    },
  },
} as const
