// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Grace',
    name: 'standardDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'standardDmgBase',
      sheet: 'Grace',
      attribute: 'electric',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Grace',
    name: 'anomalyDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Grace',
      attribute: 'electric',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_electric: {
    sheet: 'Grace',
    name: 'disorderDmgInst_electric',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Grace',
      attribute: 'electric',
      damageType1: 'disorder',
      name: 'disorderDmgInst_electric',
    },
  },
  vortexDmgInst_electric: {
    sheet: 'Grace',
    name: 'vortexDmgInst_electric',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Grace',
      attribute: 'electric',
      damageType1: 'vortex',
      name: 'vortexDmgInst_electric',
    },
  },
  abloomDmgInst: {
    sheet: 'Grace',
    name: 'abloomDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Grace',
      attribute: 'electric',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Grace',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Grace',
      attribute: 'electric',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Grace',
    name: 'dazeInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'dazeBuildupBase',
      sheet: 'Grace',
      attribute: 'electric',
      name: 'dazeInst',
    },
  },
  BasicAttackHighPressureSpike_0: {
    sheet: 'Grace',
    name: 'BasicAttackHighPressureSpike_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Grace',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackHighPressureSpike_0',
    },
  },
  BasicAttackHighPressureSpike_1: {
    sheet: 'Grace',
    name: 'BasicAttackHighPressureSpike_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Grace',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackHighPressureSpike_1',
    },
  },
  BasicAttackHighPressureSpike_2: {
    sheet: 'Grace',
    name: 'BasicAttackHighPressureSpike_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Grace',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackHighPressureSpike_2',
    },
  },
  BasicAttackHighPressureSpike_3: {
    sheet: 'Grace',
    name: 'BasicAttackHighPressureSpike_3',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Grace',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackHighPressureSpike_3',
    },
  },
  BasicAttackHighPressureSpike_4: {
    sheet: 'Grace',
    name: 'BasicAttackHighPressureSpike_4',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Grace',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackHighPressureSpike_4',
    },
  },
  DashAttackQuickInspection_0: {
    sheet: 'Grace',
    name: 'DashAttackQuickInspection_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Grace',
      damageType1: 'dash',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttackQuickInspection_0',
    },
  },
  DodgeCounterViolationPenalty_0: {
    sheet: 'Grace',
    name: 'DodgeCounterViolationPenalty_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Grace',
      attribute: 'electric',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterViolationPenalty_0',
    },
  },
  SpecialAttackObstructionRemoval_0: {
    sheet: 'Grace',
    name: 'SpecialAttackObstructionRemoval_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Grace',
      attribute: 'electric',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackObstructionRemoval_0',
    },
  },
  EXSpecialAttackSuperchargedObstructionRemoval_0: {
    sheet: 'Grace',
    name: 'EXSpecialAttackSuperchargedObstructionRemoval_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Grace',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackSuperchargedObstructionRemoval_0',
    },
  },
  ChainAttackCollaborativeConstruction_0: {
    sheet: 'Grace',
    name: 'ChainAttackCollaborativeConstruction_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Grace',
      attribute: 'electric',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackCollaborativeConstruction_0',
    },
  },
  UltimateDemolitionBlastBeware_0: {
    sheet: 'Grace',
    name: 'UltimateDemolitionBlastBeware_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Grace',
      attribute: 'electric',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateDemolitionBlastBeware_0',
    },
  },
  QuickAssistIncidentManagement_0: {
    sheet: 'Grace',
    name: 'QuickAssistIncidentManagement_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Grace',
      attribute: 'electric',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistIncidentManagement_0',
    },
  },
  AssistFollowUpCounterVoltNeedle_0: {
    sheet: 'Grace',
    name: 'AssistFollowUpCounterVoltNeedle_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Grace',
      attribute: 'electric',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpCounterVoltNeedle_0',
    },
  },
} as const
