// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Grace',
    name: 'standardDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Grace',
      attribute: 'electric',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Grace',
    name: 'anomalyDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Grace',
      attribute: 'electric',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_electric: {
    sheet: 'Grace',
    name: 'disorderDmgInst_electric',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Grace',
      attribute: 'electric',
      damageType1: 'disorder',
      name: 'disorderDmgInst_electric',
    },
  },
  vortexDmgInst_electric: {
    sheet: 'Grace',
    name: 'vortexDmgInst_electric',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Grace',
      attribute: 'electric',
      damageType1: 'vortex',
      name: 'vortexDmgInst_electric',
    },
  },
  abloomDmgInst: {
    sheet: 'Grace',
    name: 'abloomDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Grace',
      attribute: 'electric',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Grace',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Grace',
      attribute: 'electric',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Grace',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Grace',
      attribute: 'electric',
      name: 'dazeInst',
    },
  },
  'BasicAttackHighPressureSpike_0:standardDmg': {
    sheet: 'Grace',
    name: 'BasicAttackHighPressureSpike_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Grace',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackHighPressureSpike_0',
    },
  },
  'BasicAttackHighPressureSpike_0:dazeBuildup': {
    sheet: 'Grace',
    name: 'BasicAttackHighPressureSpike_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Grace',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackHighPressureSpike_0',
    },
  },
  'BasicAttackHighPressureSpike_0:anomBuildup': {
    sheet: 'Grace',
    name: 'BasicAttackHighPressureSpike_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Grace',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackHighPressureSpike_0',
    },
  },
  'BasicAttackHighPressureSpike_1:standardDmg': {
    sheet: 'Grace',
    name: 'BasicAttackHighPressureSpike_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Grace',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackHighPressureSpike_1',
    },
  },
  'BasicAttackHighPressureSpike_1:dazeBuildup': {
    sheet: 'Grace',
    name: 'BasicAttackHighPressureSpike_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Grace',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackHighPressureSpike_1',
    },
  },
  'BasicAttackHighPressureSpike_1:anomBuildup': {
    sheet: 'Grace',
    name: 'BasicAttackHighPressureSpike_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Grace',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackHighPressureSpike_1',
    },
  },
  'BasicAttackHighPressureSpike_2:standardDmg': {
    sheet: 'Grace',
    name: 'BasicAttackHighPressureSpike_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Grace',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackHighPressureSpike_2',
    },
  },
  'BasicAttackHighPressureSpike_2:dazeBuildup': {
    sheet: 'Grace',
    name: 'BasicAttackHighPressureSpike_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Grace',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackHighPressureSpike_2',
    },
  },
  'BasicAttackHighPressureSpike_2:anomBuildup': {
    sheet: 'Grace',
    name: 'BasicAttackHighPressureSpike_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Grace',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackHighPressureSpike_2',
    },
  },
  'BasicAttackHighPressureSpike_3:standardDmg': {
    sheet: 'Grace',
    name: 'BasicAttackHighPressureSpike_3:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Grace',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackHighPressureSpike_3',
    },
  },
  'BasicAttackHighPressureSpike_3:dazeBuildup': {
    sheet: 'Grace',
    name: 'BasicAttackHighPressureSpike_3:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Grace',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackHighPressureSpike_3',
    },
  },
  'BasicAttackHighPressureSpike_3:anomBuildup': {
    sheet: 'Grace',
    name: 'BasicAttackHighPressureSpike_3:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Grace',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackHighPressureSpike_3',
    },
  },
  'BasicAttackHighPressureSpike_4:standardDmg': {
    sheet: 'Grace',
    name: 'BasicAttackHighPressureSpike_4:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Grace',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackHighPressureSpike_4',
    },
  },
  'BasicAttackHighPressureSpike_4:dazeBuildup': {
    sheet: 'Grace',
    name: 'BasicAttackHighPressureSpike_4:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Grace',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackHighPressureSpike_4',
    },
  },
  'BasicAttackHighPressureSpike_4:anomBuildup': {
    sheet: 'Grace',
    name: 'BasicAttackHighPressureSpike_4:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Grace',
      attribute: 'electric',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackHighPressureSpike_4',
    },
  },
  'DashAttackQuickInspection_0:standardDmg': {
    sheet: 'Grace',
    name: 'DashAttackQuickInspection_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Grace',
      damageType1: 'dash',
      attribute: 'physical',
      skillType1: 'dodgeSkill',
      name: 'DashAttackQuickInspection_0',
    },
  },
  'DashAttackQuickInspection_0:dazeBuildup': {
    sheet: 'Grace',
    name: 'DashAttackQuickInspection_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Grace',
      damageType1: 'dash',
      attribute: 'physical',
      skillType1: 'dodgeSkill',
      name: 'DashAttackQuickInspection_0',
    },
  },
  'DashAttackQuickInspection_0:anomBuildup': {
    sheet: 'Grace',
    name: 'DashAttackQuickInspection_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Grace',
      damageType1: 'dash',
      attribute: 'physical',
      skillType1: 'dodgeSkill',
      name: 'DashAttackQuickInspection_0',
    },
  },
  'DodgeCounterViolationPenalty_0:standardDmg': {
    sheet: 'Grace',
    name: 'DodgeCounterViolationPenalty_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Grace',
      attribute: 'electric',
      damageType1: 'dodgeCounter',
      skillType1: 'dodgeSkill',
      name: 'DodgeCounterViolationPenalty_0',
    },
  },
  'DodgeCounterViolationPenalty_0:dazeBuildup': {
    sheet: 'Grace',
    name: 'DodgeCounterViolationPenalty_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Grace',
      attribute: 'electric',
      damageType1: 'dodgeCounter',
      skillType1: 'dodgeSkill',
      name: 'DodgeCounterViolationPenalty_0',
    },
  },
  'DodgeCounterViolationPenalty_0:anomBuildup': {
    sheet: 'Grace',
    name: 'DodgeCounterViolationPenalty_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Grace',
      attribute: 'electric',
      damageType1: 'dodgeCounter',
      skillType1: 'dodgeSkill',
      name: 'DodgeCounterViolationPenalty_0',
    },
  },
  'SpecialAttackObstructionRemoval_0:standardDmg': {
    sheet: 'Grace',
    name: 'SpecialAttackObstructionRemoval_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Grace',
      attribute: 'electric',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackObstructionRemoval_0',
    },
  },
  'SpecialAttackObstructionRemoval_0:dazeBuildup': {
    sheet: 'Grace',
    name: 'SpecialAttackObstructionRemoval_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Grace',
      attribute: 'electric',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackObstructionRemoval_0',
    },
  },
  'SpecialAttackObstructionRemoval_0:anomBuildup': {
    sheet: 'Grace',
    name: 'SpecialAttackObstructionRemoval_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Grace',
      attribute: 'electric',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackObstructionRemoval_0',
    },
  },
  'EXSpecialAttackSuperchargedObstructionRemoval_0:standardDmg': {
    sheet: 'Grace',
    name: 'EXSpecialAttackSuperchargedObstructionRemoval_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Grace',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackSuperchargedObstructionRemoval_0',
    },
  },
  'EXSpecialAttackSuperchargedObstructionRemoval_0:dazeBuildup': {
    sheet: 'Grace',
    name: 'EXSpecialAttackSuperchargedObstructionRemoval_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Grace',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackSuperchargedObstructionRemoval_0',
    },
  },
  'EXSpecialAttackSuperchargedObstructionRemoval_0:anomBuildup': {
    sheet: 'Grace',
    name: 'EXSpecialAttackSuperchargedObstructionRemoval_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Grace',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackSuperchargedObstructionRemoval_0',
    },
  },
  'SpecialAttackObstructionRemovalCycle_0:standardDmg': {
    sheet: 'Grace',
    name: 'SpecialAttackObstructionRemovalCycle_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Grace',
      attribute: 'electric',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackObstructionRemovalCycle_0',
    },
  },
  'SpecialAttackObstructionRemovalCycle_0:dazeBuildup': {
    sheet: 'Grace',
    name: 'SpecialAttackObstructionRemovalCycle_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Grace',
      attribute: 'electric',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackObstructionRemovalCycle_0',
    },
  },
  'SpecialAttackObstructionRemovalCycle_0:anomBuildup': {
    sheet: 'Grace',
    name: 'SpecialAttackObstructionRemovalCycle_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Grace',
      attribute: 'electric',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackObstructionRemovalCycle_0',
    },
  },
  'ChainAttackCollaborativeConstruction_0:standardDmg': {
    sheet: 'Grace',
    name: 'ChainAttackCollaborativeConstruction_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Grace',
      attribute: 'electric',
      damageType1: 'chain',
      skillType1: 'chainSkill',
      name: 'ChainAttackCollaborativeConstruction_0',
    },
  },
  'ChainAttackCollaborativeConstruction_0:dazeBuildup': {
    sheet: 'Grace',
    name: 'ChainAttackCollaborativeConstruction_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Grace',
      attribute: 'electric',
      damageType1: 'chain',
      skillType1: 'chainSkill',
      name: 'ChainAttackCollaborativeConstruction_0',
    },
  },
  'ChainAttackCollaborativeConstruction_0:anomBuildup': {
    sheet: 'Grace',
    name: 'ChainAttackCollaborativeConstruction_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Grace',
      attribute: 'electric',
      damageType1: 'chain',
      skillType1: 'chainSkill',
      name: 'ChainAttackCollaborativeConstruction_0',
    },
  },
  'UltimateDemolitionBlastBeware_0:standardDmg': {
    sheet: 'Grace',
    name: 'UltimateDemolitionBlastBeware_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Grace',
      attribute: 'electric',
      damageType1: 'ult',
      skillType1: 'chainSkill',
      name: 'UltimateDemolitionBlastBeware_0',
    },
  },
  'UltimateDemolitionBlastBeware_0:dazeBuildup': {
    sheet: 'Grace',
    name: 'UltimateDemolitionBlastBeware_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Grace',
      attribute: 'electric',
      damageType1: 'ult',
      skillType1: 'chainSkill',
      name: 'UltimateDemolitionBlastBeware_0',
    },
  },
  'UltimateDemolitionBlastBeware_0:anomBuildup': {
    sheet: 'Grace',
    name: 'UltimateDemolitionBlastBeware_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Grace',
      attribute: 'electric',
      damageType1: 'ult',
      skillType1: 'chainSkill',
      name: 'UltimateDemolitionBlastBeware_0',
    },
  },
  'QuickAssistIncidentManagement_0:standardDmg': {
    sheet: 'Grace',
    name: 'QuickAssistIncidentManagement_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Grace',
      attribute: 'electric',
      damageType1: 'quickAssist',
      skillType1: 'assistSkill',
      name: 'QuickAssistIncidentManagement_0',
    },
  },
  'QuickAssistIncidentManagement_0:dazeBuildup': {
    sheet: 'Grace',
    name: 'QuickAssistIncidentManagement_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Grace',
      attribute: 'electric',
      damageType1: 'quickAssist',
      skillType1: 'assistSkill',
      name: 'QuickAssistIncidentManagement_0',
    },
  },
  'QuickAssistIncidentManagement_0:anomBuildup': {
    sheet: 'Grace',
    name: 'QuickAssistIncidentManagement_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Grace',
      attribute: 'electric',
      damageType1: 'quickAssist',
      skillType1: 'assistSkill',
      name: 'QuickAssistIncidentManagement_0',
    },
  },
  'AssistFollowUpCounterVoltNeedle_0:standardDmg': {
    sheet: 'Grace',
    name: 'AssistFollowUpCounterVoltNeedle_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Grace',
      attribute: 'electric',
      damageType1: 'assistFollowUp',
      skillType1: 'assistSkill',
      name: 'AssistFollowUpCounterVoltNeedle_0',
    },
  },
  'AssistFollowUpCounterVoltNeedle_0:dazeBuildup': {
    sheet: 'Grace',
    name: 'AssistFollowUpCounterVoltNeedle_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Grace',
      attribute: 'electric',
      damageType1: 'assistFollowUp',
      skillType1: 'assistSkill',
      name: 'AssistFollowUpCounterVoltNeedle_0',
    },
  },
  'AssistFollowUpCounterVoltNeedle_0:anomBuildup': {
    sheet: 'Grace',
    name: 'AssistFollowUpCounterVoltNeedle_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Grace',
      attribute: 'electric',
      damageType1: 'assistFollowUp',
      skillType1: 'assistSkill',
      name: 'AssistFollowUpCounterVoltNeedle_0',
    },
  },
} as const
