// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Soldier0Anby',
    name: 'standardDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Soldier0Anby',
    name: 'anomalyDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_electric: {
    sheet: 'Soldier0Anby',
    name: 'disorderDmgInst_electric',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'disorder',
      name: 'disorderDmgInst_electric',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Soldier0Anby',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Soldier0Anby',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      name: 'dazeInst',
    },
  },
  BasicAttackPenetratingShock_0_dmg: {
    sheet: 'Soldier0Anby',
    name: 'BasicAttackPenetratingShock_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPenetratingShock_0_dmg',
    },
  },
  BasicAttackPenetratingShock_0_daze: {
    sheet: 'Soldier0Anby',
    name: 'BasicAttackPenetratingShock_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPenetratingShock_0_daze',
    },
  },
  BasicAttackPenetratingShock_0_anomBuildup: {
    sheet: 'Soldier0Anby',
    name: 'BasicAttackPenetratingShock_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPenetratingShock_0_anomBuildup',
    },
  },
  BasicAttackPenetratingShock_1_dmg: {
    sheet: 'Soldier0Anby',
    name: 'BasicAttackPenetratingShock_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPenetratingShock_1_dmg',
    },
  },
  BasicAttackPenetratingShock_1_daze: {
    sheet: 'Soldier0Anby',
    name: 'BasicAttackPenetratingShock_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPenetratingShock_1_daze',
    },
  },
  BasicAttackPenetratingShock_1_anomBuildup: {
    sheet: 'Soldier0Anby',
    name: 'BasicAttackPenetratingShock_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPenetratingShock_1_anomBuildup',
    },
  },
  BasicAttackPenetratingShock_2_dmg: {
    sheet: 'Soldier0Anby',
    name: 'BasicAttackPenetratingShock_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPenetratingShock_2_dmg',
    },
  },
  BasicAttackPenetratingShock_2_daze: {
    sheet: 'Soldier0Anby',
    name: 'BasicAttackPenetratingShock_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPenetratingShock_2_daze',
    },
  },
  BasicAttackPenetratingShock_2_anomBuildup: {
    sheet: 'Soldier0Anby',
    name: 'BasicAttackPenetratingShock_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPenetratingShock_2_anomBuildup',
    },
  },
  BasicAttackPenetratingShock_3_dmg: {
    sheet: 'Soldier0Anby',
    name: 'BasicAttackPenetratingShock_3_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPenetratingShock_3_dmg',
    },
  },
  BasicAttackPenetratingShock_3_daze: {
    sheet: 'Soldier0Anby',
    name: 'BasicAttackPenetratingShock_3_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPenetratingShock_3_daze',
    },
  },
  BasicAttackPenetratingShock_3_anomBuildup: {
    sheet: 'Soldier0Anby',
    name: 'BasicAttackPenetratingShock_3_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPenetratingShock_3_anomBuildup',
    },
  },
  BasicAttackPenetratingShock_4_dmg: {
    sheet: 'Soldier0Anby',
    name: 'BasicAttackPenetratingShock_4_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPenetratingShock_4_dmg',
    },
  },
  BasicAttackPenetratingShock_4_daze: {
    sheet: 'Soldier0Anby',
    name: 'BasicAttackPenetratingShock_4_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPenetratingShock_4_daze',
    },
  },
  BasicAttackPenetratingShock_4_anomBuildup: {
    sheet: 'Soldier0Anby',
    name: 'BasicAttackPenetratingShock_4_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPenetratingShock_4_anomBuildup',
    },
  },
  BasicAttackPenetratingShock_5_dmg: {
    sheet: 'Soldier0Anby',
    name: 'BasicAttackPenetratingShock_5_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPenetratingShock_5_dmg',
    },
  },
  BasicAttackPenetratingShock_5_daze: {
    sheet: 'Soldier0Anby',
    name: 'BasicAttackPenetratingShock_5_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPenetratingShock_5_daze',
    },
  },
  BasicAttackPenetratingShock_5_anomBuildup: {
    sheet: 'Soldier0Anby',
    name: 'BasicAttackPenetratingShock_5_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPenetratingShock_5_anomBuildup',
    },
  },
  DashAttackTorrent_0_dmg: {
    sheet: 'Soldier0Anby',
    name: 'DashAttackTorrent_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackTorrent_0_dmg',
    },
  },
  DashAttackTorrent_0_daze: {
    sheet: 'Soldier0Anby',
    name: 'DashAttackTorrent_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackTorrent_0_daze',
    },
  },
  DashAttackTorrent_0_anomBuildup: {
    sheet: 'Soldier0Anby',
    name: 'DashAttackTorrent_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackTorrent_0_anomBuildup',
    },
  },
  DodgeCounterGroundFlashCounter_0_dmg: {
    sheet: 'Soldier0Anby',
    name: 'DodgeCounterGroundFlashCounter_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterGroundFlashCounter_0_dmg',
    },
  },
  DodgeCounterGroundFlashCounter_0_daze: {
    sheet: 'Soldier0Anby',
    name: 'DodgeCounterGroundFlashCounter_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterGroundFlashCounter_0_daze',
    },
  },
  DodgeCounterGroundFlashCounter_0_anomBuildup: {
    sheet: 'Soldier0Anby',
    name: 'DodgeCounterGroundFlashCounter_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterGroundFlashCounter_0_anomBuildup',
    },
  },
  SpecialAttackCelestialThunder_0_dmg: {
    sheet: 'Soldier0Anby',
    name: 'SpecialAttackCelestialThunder_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackCelestialThunder_0_dmg',
    },
  },
  SpecialAttackCelestialThunder_0_daze: {
    sheet: 'Soldier0Anby',
    name: 'SpecialAttackCelestialThunder_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackCelestialThunder_0_daze',
    },
  },
  SpecialAttackCelestialThunder_0_anomBuildup: {
    sheet: 'Soldier0Anby',
    name: 'SpecialAttackCelestialThunder_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackCelestialThunder_0_anomBuildup',
    },
  },
  SpecialAttackAzureFlash_0_dmg: {
    sheet: 'Soldier0Anby',
    name: 'SpecialAttackAzureFlash_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackAzureFlash_0_dmg',
    },
  },
  SpecialAttackAzureFlash_0_daze: {
    sheet: 'Soldier0Anby',
    name: 'SpecialAttackAzureFlash_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackAzureFlash_0_daze',
    },
  },
  SpecialAttackAzureFlash_0_anomBuildup: {
    sheet: 'Soldier0Anby',
    name: 'SpecialAttackAzureFlash_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackAzureFlash_0_anomBuildup',
    },
  },
  SpecialAttackAzureFlash_1_dmg: {
    sheet: 'Soldier0Anby',
    name: 'SpecialAttackAzureFlash_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackAzureFlash_1_dmg',
    },
  },
  SpecialAttackAzureFlash_1_daze: {
    sheet: 'Soldier0Anby',
    name: 'SpecialAttackAzureFlash_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackAzureFlash_1_daze',
    },
  },
  SpecialAttackAzureFlash_1_anomBuildup: {
    sheet: 'Soldier0Anby',
    name: 'SpecialAttackAzureFlash_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackAzureFlash_1_anomBuildup',
    },
  },
  SpecialAttackThunderSmite_0_dmg: {
    sheet: 'Soldier0Anby',
    name: 'SpecialAttackThunderSmite_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackThunderSmite_0_dmg',
    },
  },
  SpecialAttackThunderSmite_0_daze: {
    sheet: 'Soldier0Anby',
    name: 'SpecialAttackThunderSmite_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackThunderSmite_0_daze',
    },
  },
  SpecialAttackThunderSmite_0_anomBuildup: {
    sheet: 'Soldier0Anby',
    name: 'SpecialAttackThunderSmite_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackThunderSmite_0_anomBuildup',
    },
  },
  EXSpecialAttackSunderingBolt_0_dmg: {
    sheet: 'Soldier0Anby',
    name: 'EXSpecialAttackSunderingBolt_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackSunderingBolt_0_dmg',
    },
  },
  EXSpecialAttackSunderingBolt_0_daze: {
    sheet: 'Soldier0Anby',
    name: 'EXSpecialAttackSunderingBolt_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackSunderingBolt_0_daze',
    },
  },
  EXSpecialAttackSunderingBolt_0_anomBuildup: {
    sheet: 'Soldier0Anby',
    name: 'EXSpecialAttackSunderingBolt_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackSunderingBolt_0_anomBuildup',
    },
  },
  ChainAttackLeapingThunderstrike_0_dmg: {
    sheet: 'Soldier0Anby',
    name: 'ChainAttackLeapingThunderstrike_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'nonDmg',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackLeapingThunderstrike_0_dmg',
    },
  },
  ChainAttackLeapingThunderstrike_0_daze: {
    sheet: 'Soldier0Anby',
    name: 'ChainAttackLeapingThunderstrike_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackLeapingThunderstrike_0_daze',
    },
  },
  ChainAttackLeapingThunderstrike_0_anomBuildup: {
    sheet: 'Soldier0Anby',
    name: 'ChainAttackLeapingThunderstrike_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackLeapingThunderstrike_0_anomBuildup',
    },
  },
  UltimateVoidstrike_0_dmg: {
    sheet: 'Soldier0Anby',
    name: 'UltimateVoidstrike_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'nonDmg',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateVoidstrike_0_dmg',
    },
  },
  UltimateVoidstrike_0_daze: {
    sheet: 'Soldier0Anby',
    name: 'UltimateVoidstrike_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateVoidstrike_0_daze',
    },
  },
  UltimateVoidstrike_0_anomBuildup: {
    sheet: 'Soldier0Anby',
    name: 'UltimateVoidstrike_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateVoidstrike_0_anomBuildup',
    },
  },
  QuickAssistCloudFlash_0_dmg: {
    sheet: 'Soldier0Anby',
    name: 'QuickAssistCloudFlash_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistCloudFlash_0_dmg',
    },
  },
  QuickAssistCloudFlash_0_daze: {
    sheet: 'Soldier0Anby',
    name: 'QuickAssistCloudFlash_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistCloudFlash_0_daze',
    },
  },
  QuickAssistCloudFlash_0_anomBuildup: {
    sheet: 'Soldier0Anby',
    name: 'QuickAssistCloudFlash_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistCloudFlash_0_anomBuildup',
    },
  },
  DefensiveAssistCounterSurge_0_dmg: {
    sheet: 'Soldier0Anby',
    name: 'DefensiveAssistCounterSurge_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistCounterSurge_0_dmg',
    },
  },
  DefensiveAssistCounterSurge_0_daze: {
    sheet: 'Soldier0Anby',
    name: 'DefensiveAssistCounterSurge_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistCounterSurge_0_daze',
    },
  },
  DefensiveAssistCounterSurge_0_anomBuildup: {
    sheet: 'Soldier0Anby',
    name: 'DefensiveAssistCounterSurge_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistCounterSurge_0_anomBuildup',
    },
  },
  DefensiveAssistCounterSurge_1_dmg: {
    sheet: 'Soldier0Anby',
    name: 'DefensiveAssistCounterSurge_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistCounterSurge_1_dmg',
    },
  },
  DefensiveAssistCounterSurge_1_daze: {
    sheet: 'Soldier0Anby',
    name: 'DefensiveAssistCounterSurge_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistCounterSurge_1_daze',
    },
  },
  DefensiveAssistCounterSurge_1_anomBuildup: {
    sheet: 'Soldier0Anby',
    name: 'DefensiveAssistCounterSurge_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistCounterSurge_1_anomBuildup',
    },
  },
  DefensiveAssistCounterSurge_2_dmg: {
    sheet: 'Soldier0Anby',
    name: 'DefensiveAssistCounterSurge_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistCounterSurge_2_dmg',
    },
  },
  DefensiveAssistCounterSurge_2_daze: {
    sheet: 'Soldier0Anby',
    name: 'DefensiveAssistCounterSurge_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistCounterSurge_2_daze',
    },
  },
  DefensiveAssistCounterSurge_2_anomBuildup: {
    sheet: 'Soldier0Anby',
    name: 'DefensiveAssistCounterSurge_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistCounterSurge_2_anomBuildup',
    },
  },
  AssistFollowUpConductingBlow_0_dmg: {
    sheet: 'Soldier0Anby',
    name: 'AssistFollowUpConductingBlow_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpConductingBlow_0_dmg',
    },
  },
  AssistFollowUpConductingBlow_0_daze: {
    sheet: 'Soldier0Anby',
    name: 'AssistFollowUpConductingBlow_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpConductingBlow_0_daze',
    },
  },
  AssistFollowUpConductingBlow_0_anomBuildup: {
    sheet: 'Soldier0Anby',
    name: 'AssistFollowUpConductingBlow_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpConductingBlow_0_anomBuildup',
    },
  },
  m6_additional_dmg: {
    sheet: 'Soldier0Anby',
    name: 'm6_additional_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'aftershock',
      name: 'm6_additional_dmg',
    },
  },
} as const
