// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Soldier0Anby',
    name: 'standardDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'standardDmgBase',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Soldier0Anby',
    name: 'anomalyDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_electric: {
    sheet: 'Soldier0Anby',
    name: 'disorderDmgInst_electric',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'disorder',
      name: 'disorderDmgInst_electric',
    },
  },
  vortexDmgInst_electric: {
    sheet: 'Soldier0Anby',
    name: 'vortexDmgInst_electric',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'vortex',
      name: 'vortexDmgInst_electric',
    },
  },
  abloomDmgInst: {
    sheet: 'Soldier0Anby',
    name: 'abloomDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Soldier0Anby',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Soldier0Anby',
    name: 'dazeInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'dazeBuildupBase',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      name: 'dazeInst',
    },
  },
  BasicAttackPenetratingShock_0: {
    sheet: 'Soldier0Anby',
    name: 'BasicAttackPenetratingShock_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPenetratingShock_0',
    },
  },
  BasicAttackPenetratingShock_1: {
    sheet: 'Soldier0Anby',
    name: 'BasicAttackPenetratingShock_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPenetratingShock_1',
    },
  },
  BasicAttackPenetratingShock_2: {
    sheet: 'Soldier0Anby',
    name: 'BasicAttackPenetratingShock_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPenetratingShock_2',
    },
  },
  BasicAttackPenetratingShock_3: {
    sheet: 'Soldier0Anby',
    name: 'BasicAttackPenetratingShock_3',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPenetratingShock_3',
    },
  },
  BasicAttackPenetratingShock_4: {
    sheet: 'Soldier0Anby',
    name: 'BasicAttackPenetratingShock_4',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPenetratingShock_4',
    },
  },
  BasicAttackPenetratingShock_5: {
    sheet: 'Soldier0Anby',
    name: 'BasicAttackPenetratingShock_5',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPenetratingShock_5',
    },
  },
  DashAttackTorrent_0: {
    sheet: 'Soldier0Anby',
    name: 'DashAttackTorrent_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackTorrent_0',
    },
  },
  DodgeCounterGroundFlashCounter_0: {
    sheet: 'Soldier0Anby',
    name: 'DodgeCounterGroundFlashCounter_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterGroundFlashCounter_0',
    },
  },
  SpecialAttackCelestialThunder_0: {
    sheet: 'Soldier0Anby',
    name: 'SpecialAttackCelestialThunder_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackCelestialThunder_0',
    },
  },
  SpecialAttackAzureFlash_0: {
    sheet: 'Soldier0Anby',
    name: 'SpecialAttackAzureFlash_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackAzureFlash_0',
    },
  },
  SpecialAttackAzureFlash_1: {
    sheet: 'Soldier0Anby',
    name: 'SpecialAttackAzureFlash_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackAzureFlash_1',
    },
  },
  SpecialAttackThunderSmite_0: {
    sheet: 'Soldier0Anby',
    name: 'SpecialAttackThunderSmite_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackThunderSmite_0',
    },
  },
  EXSpecialAttackSunderingBolt_0: {
    sheet: 'Soldier0Anby',
    name: 'EXSpecialAttackSunderingBolt_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackSunderingBolt_0',
    },
  },
  ChainAttackLeapingThunderstrike_0: {
    sheet: 'Soldier0Anby',
    name: 'ChainAttackLeapingThunderstrike_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackLeapingThunderstrike_0',
    },
  },
  UltimateVoidstrike_0: {
    sheet: 'Soldier0Anby',
    name: 'UltimateVoidstrike_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateVoidstrike_0',
    },
  },
  QuickAssistCloudFlash_0: {
    sheet: 'Soldier0Anby',
    name: 'QuickAssistCloudFlash_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistCloudFlash_0',
    },
  },
  DefensiveAssistCounterSurge_0: {
    sheet: 'Soldier0Anby',
    name: 'DefensiveAssistCounterSurge_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistCounterSurge_0',
    },
  },
  DefensiveAssistCounterSurge_1: {
    sheet: 'Soldier0Anby',
    name: 'DefensiveAssistCounterSurge_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistCounterSurge_1',
    },
  },
  DefensiveAssistCounterSurge_2: {
    sheet: 'Soldier0Anby',
    name: 'DefensiveAssistCounterSurge_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistCounterSurge_2',
    },
  },
  AssistFollowUpConductingBlow_0: {
    sheet: 'Soldier0Anby',
    name: 'AssistFollowUpConductingBlow_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpConductingBlow_0',
    },
  },
  ChainAttackLeapingThunderstrike_aftershock0: {
    sheet: 'Soldier0Anby',
    name: 'ChainAttackLeapingThunderstrike_aftershock0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'chain',
      damageType2: 'aftershock',
      skillType: 'chainSkill',
      name: 'ChainAttackLeapingThunderstrike_aftershock0',
    },
  },
  UltimateVoidstrike_aftershock0: {
    sheet: 'Soldier0Anby',
    name: 'UltimateVoidstrike_aftershock0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'ult',
      damageType2: 'aftershock',
      skillType: 'chainSkill',
      name: 'UltimateVoidstrike_aftershock0',
    },
  },
  m6_additional_dmg: {
    sheet: 'Soldier0Anby',
    name: 'm6_additional_dmg',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'standardDmgBase',
      sheet: 'Soldier0Anby',
      attribute: 'electric',
      damageType1: 'aftershock',
      name: 'm6_additional_dmg',
    },
  },
} as const
