// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Rina',
    name: 'standardDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'standardDmgBase',
      sheet: 'Rina',
      attribute: 'electric',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Rina',
    name: 'anomalyDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Rina',
      attribute: 'electric',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_electric: {
    sheet: 'Rina',
    name: 'disorderDmgInst_electric',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Rina',
      attribute: 'electric',
      damageType1: 'disorder',
      name: 'disorderDmgInst_electric',
    },
  },
  vortexDmgInst_electric: {
    sheet: 'Rina',
    name: 'vortexDmgInst_electric',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Rina',
      attribute: 'electric',
      damageType1: 'vortex',
      name: 'vortexDmgInst_electric',
    },
  },
  abloomDmgInst: {
    sheet: 'Rina',
    name: 'abloomDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Rina',
      attribute: 'electric',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Rina',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Rina',
      attribute: 'electric',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Rina',
    name: 'dazeInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'dazeBuildupBase',
      sheet: 'Rina',
      attribute: 'electric',
      name: 'dazeInst',
    },
  },
  BasicAttackWhackTheDimwit_0: {
    sheet: 'Rina',
    name: 'BasicAttackWhackTheDimwit_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Rina',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackWhackTheDimwit_0',
    },
  },
  BasicAttackWhackTheDimwit_1: {
    sheet: 'Rina',
    name: 'BasicAttackWhackTheDimwit_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Rina',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackWhackTheDimwit_1',
    },
  },
  BasicAttackWhackTheDimwit_2: {
    sheet: 'Rina',
    name: 'BasicAttackWhackTheDimwit_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Rina',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackWhackTheDimwit_2',
    },
  },
  BasicAttackWhackTheDimwit_3: {
    sheet: 'Rina',
    name: 'BasicAttackWhackTheDimwit_3',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Rina',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackWhackTheDimwit_3',
    },
  },
  BasicAttackShooTheFool_0: {
    sheet: 'Rina',
    name: 'BasicAttackShooTheFool_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Rina',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackShooTheFool_0',
    },
  },
  DashAttackSuddenSurprise_0: {
    sheet: 'Rina',
    name: 'DashAttackSuddenSurprise_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Rina',
      damageType1: 'dash',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttackSuddenSurprise_0',
    },
  },
  DodgeCounterBangbooCallback_0: {
    sheet: 'Rina',
    name: 'DodgeCounterBangbooCallback_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Rina',
      attribute: 'electric',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterBangbooCallback_0',
    },
  },
  SpecialAttackBeatTheBlockhead_0: {
    sheet: 'Rina',
    name: 'SpecialAttackBeatTheBlockhead_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Rina',
      attribute: 'electric',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackBeatTheBlockhead_0',
    },
  },
  EXSpecialAttackDimwitDisappearingTrick_0: {
    sheet: 'Rina',
    name: 'EXSpecialAttackDimwitDisappearingTrick_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Rina',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackDimwitDisappearingTrick_0',
    },
  },
  ChainAttackCodeOfConduct_0: {
    sheet: 'Rina',
    name: 'ChainAttackCodeOfConduct_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Rina',
      attribute: 'electric',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackCodeOfConduct_0',
    },
  },
  UltimateTheQueensAttendants_0: {
    sheet: 'Rina',
    name: 'UltimateTheQueensAttendants_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Rina',
      attribute: 'electric',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateTheQueensAttendants_0',
    },
  },
  QuickAssistDupleMeterAllemande_0: {
    sheet: 'Rina',
    name: 'QuickAssistDupleMeterAllemande_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Rina',
      attribute: 'electric',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistDupleMeterAllemande_0',
    },
  },
  AssistFollowUpQuadrupleMeterGavotte_0: {
    sheet: 'Rina',
    name: 'AssistFollowUpQuadrupleMeterGavotte_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Rina',
      attribute: 'electric',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpQuadrupleMeterGavotte_0',
    },
  },
} as const
