// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Rina',
    name: 'standardDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Rina',
      attribute: 'electric',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Rina',
    name: 'anomalyDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Rina',
      attribute: 'electric',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_electric: {
    sheet: 'Rina',
    name: 'disorderDmgInst_electric',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Rina',
      attribute: 'electric',
      damageType1: 'disorder',
      name: 'disorderDmgInst_electric',
    },
  },
  vortexDmgInst_electric: {
    sheet: 'Rina',
    name: 'vortexDmgInst_electric',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Rina',
      attribute: 'electric',
      damageType1: 'vortex',
      name: 'vortexDmgInst_electric',
    },
  },
  abloomDmgInst: {
    sheet: 'Rina',
    name: 'abloomDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Rina',
      attribute: 'electric',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Rina',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Rina',
      attribute: 'electric',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Rina',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Rina',
      attribute: 'electric',
      name: 'dazeInst',
    },
  },
  'BasicAttackWhackTheDimwit_0:standardDmg': {
    sheet: 'Rina',
    name: 'BasicAttackWhackTheDimwit_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Rina',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackWhackTheDimwit_0',
    },
  },
  'BasicAttackWhackTheDimwit_0:dazeBuildup': {
    sheet: 'Rina',
    name: 'BasicAttackWhackTheDimwit_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Rina',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackWhackTheDimwit_0',
    },
  },
  'BasicAttackWhackTheDimwit_0:anomBuildup': {
    sheet: 'Rina',
    name: 'BasicAttackWhackTheDimwit_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Rina',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackWhackTheDimwit_0',
    },
  },
  'BasicAttackWhackTheDimwit_1:standardDmg': {
    sheet: 'Rina',
    name: 'BasicAttackWhackTheDimwit_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Rina',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackWhackTheDimwit_1',
    },
  },
  'BasicAttackWhackTheDimwit_1:dazeBuildup': {
    sheet: 'Rina',
    name: 'BasicAttackWhackTheDimwit_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Rina',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackWhackTheDimwit_1',
    },
  },
  'BasicAttackWhackTheDimwit_1:anomBuildup': {
    sheet: 'Rina',
    name: 'BasicAttackWhackTheDimwit_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Rina',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackWhackTheDimwit_1',
    },
  },
  'BasicAttackWhackTheDimwit_2:standardDmg': {
    sheet: 'Rina',
    name: 'BasicAttackWhackTheDimwit_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Rina',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackWhackTheDimwit_2',
    },
  },
  'BasicAttackWhackTheDimwit_2:dazeBuildup': {
    sheet: 'Rina',
    name: 'BasicAttackWhackTheDimwit_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Rina',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackWhackTheDimwit_2',
    },
  },
  'BasicAttackWhackTheDimwit_2:anomBuildup': {
    sheet: 'Rina',
    name: 'BasicAttackWhackTheDimwit_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Rina',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackWhackTheDimwit_2',
    },
  },
  'BasicAttackWhackTheDimwit_3:standardDmg': {
    sheet: 'Rina',
    name: 'BasicAttackWhackTheDimwit_3:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Rina',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackWhackTheDimwit_3',
    },
  },
  'BasicAttackWhackTheDimwit_3:dazeBuildup': {
    sheet: 'Rina',
    name: 'BasicAttackWhackTheDimwit_3:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Rina',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackWhackTheDimwit_3',
    },
  },
  'BasicAttackWhackTheDimwit_3:anomBuildup': {
    sheet: 'Rina',
    name: 'BasicAttackWhackTheDimwit_3:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Rina',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackWhackTheDimwit_3',
    },
  },
  'BasicAttackShooTheFool_0:standardDmg': {
    sheet: 'Rina',
    name: 'BasicAttackShooTheFool_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Rina',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackShooTheFool_0',
    },
  },
  'BasicAttackShooTheFool_0:dazeBuildup': {
    sheet: 'Rina',
    name: 'BasicAttackShooTheFool_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Rina',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackShooTheFool_0',
    },
  },
  'BasicAttackShooTheFool_0:anomBuildup': {
    sheet: 'Rina',
    name: 'BasicAttackShooTheFool_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Rina',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackShooTheFool_0',
    },
  },
  'DashAttackSuddenSurprise_0:standardDmg': {
    sheet: 'Rina',
    name: 'DashAttackSuddenSurprise_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Rina',
      damageType1: 'dash',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttackSuddenSurprise_0',
    },
  },
  'DashAttackSuddenSurprise_0:dazeBuildup': {
    sheet: 'Rina',
    name: 'DashAttackSuddenSurprise_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Rina',
      damageType1: 'dash',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttackSuddenSurprise_0',
    },
  },
  'DashAttackSuddenSurprise_0:anomBuildup': {
    sheet: 'Rina',
    name: 'DashAttackSuddenSurprise_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Rina',
      damageType1: 'dash',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttackSuddenSurprise_0',
    },
  },
  'DodgeCounterBangbooCallback_0:standardDmg': {
    sheet: 'Rina',
    name: 'DodgeCounterBangbooCallback_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Rina',
      attribute: 'electric',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterBangbooCallback_0',
    },
  },
  'DodgeCounterBangbooCallback_0:dazeBuildup': {
    sheet: 'Rina',
    name: 'DodgeCounterBangbooCallback_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Rina',
      attribute: 'electric',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterBangbooCallback_0',
    },
  },
  'DodgeCounterBangbooCallback_0:anomBuildup': {
    sheet: 'Rina',
    name: 'DodgeCounterBangbooCallback_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Rina',
      attribute: 'electric',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterBangbooCallback_0',
    },
  },
  'SpecialAttackBeatTheBlockhead_0:standardDmg': {
    sheet: 'Rina',
    name: 'SpecialAttackBeatTheBlockhead_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Rina',
      attribute: 'electric',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackBeatTheBlockhead_0',
    },
  },
  'SpecialAttackBeatTheBlockhead_0:dazeBuildup': {
    sheet: 'Rina',
    name: 'SpecialAttackBeatTheBlockhead_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Rina',
      attribute: 'electric',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackBeatTheBlockhead_0',
    },
  },
  'SpecialAttackBeatTheBlockhead_0:anomBuildup': {
    sheet: 'Rina',
    name: 'SpecialAttackBeatTheBlockhead_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Rina',
      attribute: 'electric',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackBeatTheBlockhead_0',
    },
  },
  'EXSpecialAttackDimwitDisappearingTrick_0:standardDmg': {
    sheet: 'Rina',
    name: 'EXSpecialAttackDimwitDisappearingTrick_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Rina',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackDimwitDisappearingTrick_0',
    },
  },
  'EXSpecialAttackDimwitDisappearingTrick_0:dazeBuildup': {
    sheet: 'Rina',
    name: 'EXSpecialAttackDimwitDisappearingTrick_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Rina',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackDimwitDisappearingTrick_0',
    },
  },
  'EXSpecialAttackDimwitDisappearingTrick_0:anomBuildup': {
    sheet: 'Rina',
    name: 'EXSpecialAttackDimwitDisappearingTrick_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Rina',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackDimwitDisappearingTrick_0',
    },
  },
  'ChainAttackCodeOfConduct_0:standardDmg': {
    sheet: 'Rina',
    name: 'ChainAttackCodeOfConduct_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Rina',
      attribute: 'electric',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackCodeOfConduct_0',
    },
  },
  'ChainAttackCodeOfConduct_0:dazeBuildup': {
    sheet: 'Rina',
    name: 'ChainAttackCodeOfConduct_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Rina',
      attribute: 'electric',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackCodeOfConduct_0',
    },
  },
  'ChainAttackCodeOfConduct_0:anomBuildup': {
    sheet: 'Rina',
    name: 'ChainAttackCodeOfConduct_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Rina',
      attribute: 'electric',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackCodeOfConduct_0',
    },
  },
  'UltimateTheQueensAttendants_0:standardDmg': {
    sheet: 'Rina',
    name: 'UltimateTheQueensAttendants_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Rina',
      attribute: 'electric',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateTheQueensAttendants_0',
    },
  },
  'UltimateTheQueensAttendants_0:dazeBuildup': {
    sheet: 'Rina',
    name: 'UltimateTheQueensAttendants_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Rina',
      attribute: 'electric',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateTheQueensAttendants_0',
    },
  },
  'UltimateTheQueensAttendants_0:anomBuildup': {
    sheet: 'Rina',
    name: 'UltimateTheQueensAttendants_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Rina',
      attribute: 'electric',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateTheQueensAttendants_0',
    },
  },
  'QuickAssistDupleMeterAllemande_0:standardDmg': {
    sheet: 'Rina',
    name: 'QuickAssistDupleMeterAllemande_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Rina',
      attribute: 'electric',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistDupleMeterAllemande_0',
    },
  },
  'QuickAssistDupleMeterAllemande_0:dazeBuildup': {
    sheet: 'Rina',
    name: 'QuickAssistDupleMeterAllemande_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Rina',
      attribute: 'electric',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistDupleMeterAllemande_0',
    },
  },
  'QuickAssistDupleMeterAllemande_0:anomBuildup': {
    sheet: 'Rina',
    name: 'QuickAssistDupleMeterAllemande_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Rina',
      attribute: 'electric',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistDupleMeterAllemande_0',
    },
  },
  'AssistFollowUpQuadrupleMeterGavotte_0:standardDmg': {
    sheet: 'Rina',
    name: 'AssistFollowUpQuadrupleMeterGavotte_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Rina',
      attribute: 'electric',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpQuadrupleMeterGavotte_0',
    },
  },
  'AssistFollowUpQuadrupleMeterGavotte_0:dazeBuildup': {
    sheet: 'Rina',
    name: 'AssistFollowUpQuadrupleMeterGavotte_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Rina',
      attribute: 'electric',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpQuadrupleMeterGavotte_0',
    },
  },
  'AssistFollowUpQuadrupleMeterGavotte_0:anomBuildup': {
    sheet: 'Rina',
    name: 'AssistFollowUpQuadrupleMeterGavotte_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Rina',
      attribute: 'electric',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpQuadrupleMeterGavotte_0',
    },
  },
} as const
