export const allLightConeKeys = [
  'ASecretVow',
  'Adversarial',
  'Amber',
  'Arrows',
  'BeforeDawn',
  'ButTheBattleIsntOver',
  'CarveTheMoonWeaveTheClouds',
  'Chorus',
  'CollapsingSky',
  'Cornucopia',
  'CruisingInTheStellarSea',
  'DanceDanceDance',
  'DartingArrow',
  'DataBank',
  'DayOneOfMyNewLife',
  'Defense',
  'EyesOfThePrey',
  'Fermata',
  'FineFruit',
  'GeniusesRepose',
  'GoodNightAndSleepWell',
  'HiddenShadow',
  'InTheNameOfTheWorld',
  'InTheNight',
  'LandausChoice',
  'Loop',
  'MakeTheWorldClamor',
  'Mediation',
  'MemoriesOfThePast',
  'MeshingCogs',
  'MomentOfVictory',
  'Multiplication',
  'MutualDemise',
  'NightOnTheMilkyWay',
  'NowhereToRun',
  'OnTheFallOfAnAeon',
  'OnlySilenceRemains',
  'Passkey',
  'PastAndFuture',
  'PerfectTiming',
  'Pioneering',
  'PlanetaryRendezvous',
  'PostOpConversation',
  'QuidProQuo',
  'ResolutionShinesAsPearlsOfSweat',
  'ReturnToDarkness',
  'RiverFlowsInSpring',
  'Sagacity',
  'SharedFeeling',
  'ShatteredHome',
  'SleepLikeTheDead',
  'SomethingIrreplaceable',
  'SubscribeForMore',
  'Swordplay',
  'TextureOfMemories',
  'TheBirthOfTheSelf',
  'TheMolesWelcomeYou',
  'TheSeriousnessOfBreakfast',
  'ThisIsMe',
  'TimeWaitsForNoOne',
  'TodayIsAnotherPeacefulDay',
  'TrendOfTheUniversalMarket',
  'UnderTheBlueSky',
  'Void',
  'WarmthShortensColdNights',
  'WeAreWildfire',
  'WeWillMeetAgain',
  'WoofWalkTime',
] as const

export type LightConeKey = (typeof allLightConeKeys)[number]

export const allSuperimposeKeys = [0, 1, 2, 3, 4, 5] as const
export type SuperimposeKey = (typeof allSuperimposeKeys)[number]
