// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Lucia',
    name: 'standardDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'standardDmgBase',
      sheet: 'Lucia',
      attribute: 'ether',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Lucia',
    name: 'anomalyDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Lucia',
      attribute: 'ether',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_ether: {
    sheet: 'Lucia',
    name: 'disorderDmgInst_ether',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Lucia',
      attribute: 'ether',
      damageType1: 'disorder',
      name: 'disorderDmgInst_ether',
    },
  },
  vortexDmgInst_ether: {
    sheet: 'Lucia',
    name: 'vortexDmgInst_ether',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Lucia',
      attribute: 'ether',
      damageType1: 'vortex',
      name: 'vortexDmgInst_ether',
    },
  },
  abloomDmgInst: {
    sheet: 'Lucia',
    name: 'abloomDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Lucia',
      attribute: 'ether',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Lucia',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lucia',
      attribute: 'ether',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Lucia',
    name: 'dazeInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'dazeBuildupBase',
      sheet: 'Lucia',
      attribute: 'ether',
      name: 'dazeInst',
    },
  },
  BasicAttackOrbitalCombo_0: {
    sheet: 'Lucia',
    name: 'BasicAttackOrbitalCombo_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lucia',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackOrbitalCombo_0',
    },
  },
  BasicAttackOrbitalCombo_1: {
    sheet: 'Lucia',
    name: 'BasicAttackOrbitalCombo_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lucia',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackOrbitalCombo_1',
    },
  },
  BasicAttackOrbitalCombo_2: {
    sheet: 'Lucia',
    name: 'BasicAttackOrbitalCombo_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lucia',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackOrbitalCombo_2',
    },
  },
  BasicAttackOrbitalCombo_3: {
    sheet: 'Lucia',
    name: 'BasicAttackOrbitalCombo_3',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lucia',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackOrbitalCombo_3',
    },
  },
  BasicAttackOrbitalCombo_4: {
    sheet: 'Lucia',
    name: 'BasicAttackOrbitalCombo_4',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lucia',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackOrbitalCombo_4',
    },
  },
  BasicAttackOrbitalCombo_5: {
    sheet: 'Lucia',
    name: 'BasicAttackOrbitalCombo_5',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lucia',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackOrbitalCombo_5',
    },
  },
  BasicAttackOrbitalCombo_6: {
    sheet: 'Lucia',
    name: 'BasicAttackOrbitalCombo_6',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lucia',
      attribute: 'ether',
      damageType1: 'basic',
      damageType2: 'aftershock',
      skillType: 'basicSkill',
      name: 'BasicAttackOrbitalCombo_6',
    },
  },
  DashAttackRefraction_0: {
    sheet: 'Lucia',
    name: 'DashAttackRefraction_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lucia',
      attribute: 'ether',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackRefraction_0',
    },
  },
  DodgeCounterStardustEcho_0: {
    sheet: 'Lucia',
    name: 'DodgeCounterStardustEcho_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lucia',
      attribute: 'ether',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterStardustEcho_0',
    },
  },
  DodgeCounterStardustEcho_1: {
    sheet: 'Lucia',
    name: 'DodgeCounterStardustEcho_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lucia',
      attribute: 'ether',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterStardustEcho_1',
    },
  },
  SpecialAttackSymphonyOfTheReaperStorm_0: {
    sheet: 'Lucia',
    name: 'SpecialAttackSymphonyOfTheReaperStorm_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lucia',
      attribute: 'ether',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackSymphonyOfTheReaperStorm_0',
    },
  },
  SpecialAttackSymphonyOfTheReaperStorm_1: {
    sheet: 'Lucia',
    name: 'SpecialAttackSymphonyOfTheReaperStorm_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lucia',
      attribute: 'ether',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackSymphonyOfTheReaperStorm_1',
    },
  },
  SpecialAttackSymphonyOfTheReaperStorm_2: {
    sheet: 'Lucia',
    name: 'SpecialAttackSymphonyOfTheReaperStorm_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lucia',
      attribute: 'ether',
      damageType1: 'special',
      damageType2: 'aftershock',
      skillType: 'specialSkill',
      name: 'SpecialAttackSymphonyOfTheReaperStorm_2',
    },
  },
  EXSpecialAttackSymphonyOfTheReaperDaybreak_0: {
    sheet: 'Lucia',
    name: 'EXSpecialAttackSymphonyOfTheReaperDaybreak_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lucia',
      attribute: 'ether',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackSymphonyOfTheReaperDaybreak_0',
    },
  },
  ChainAttackStageOfBrilliance_0: {
    sheet: 'Lucia',
    name: 'ChainAttackStageOfBrilliance_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lucia',
      attribute: 'ether',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackStageOfBrilliance_0',
    },
  },
  UltimateChargeGreatArmor_0: {
    sheet: 'Lucia',
    name: 'UltimateChargeGreatArmor_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lucia',
      attribute: 'ether',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateChargeGreatArmor_0',
    },
  },
  UltimateChargeGreatArmor_1: {
    sheet: 'Lucia',
    name: 'UltimateChargeGreatArmor_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lucia',
      attribute: 'ether',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateChargeGreatArmor_1',
    },
  },
  QuickAssistCrushingMist_0: {
    sheet: 'Lucia',
    name: 'QuickAssistCrushingMist_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lucia',
      attribute: 'ether',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistCrushingMist_0',
    },
  },
  QuickAssistCrushingMist_1: {
    sheet: 'Lucia',
    name: 'QuickAssistCrushingMist_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lucia',
      attribute: 'ether',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistCrushingMist_1',
    },
  },
  QuickAssistCrushingMist_2: {
    sheet: 'Lucia',
    name: 'QuickAssistCrushingMist_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lucia',
      attribute: 'ether',
      damageType1: 'quickAssist',
      damageType2: 'aftershock',
      skillType: 'assistSkill',
      name: 'QuickAssistCrushingMist_2',
    },
  },
  DefensiveAssistVoiceOfIllusoryDreams_0: {
    sheet: 'Lucia',
    name: 'DefensiveAssistVoiceOfIllusoryDreams_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lucia',
      attribute: 'ether',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistVoiceOfIllusoryDreams_0',
    },
  },
  DefensiveAssistVoiceOfIllusoryDreams_1: {
    sheet: 'Lucia',
    name: 'DefensiveAssistVoiceOfIllusoryDreams_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lucia',
      attribute: 'ether',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistVoiceOfIllusoryDreams_1',
    },
  },
  DefensiveAssistVoiceOfIllusoryDreams_2: {
    sheet: 'Lucia',
    name: 'DefensiveAssistVoiceOfIllusoryDreams_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lucia',
      attribute: 'ether',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistVoiceOfIllusoryDreams_2',
    },
  },
  AssistFollowUpHarmonyOfPaintedDreams_0: {
    sheet: 'Lucia',
    name: 'AssistFollowUpHarmonyOfPaintedDreams_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lucia',
      attribute: 'ether',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpHarmonyOfPaintedDreams_0',
    },
  },
  ult_heal: {
    sheet: 'Lucia',
    name: 'ult_heal',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'healBase',
      sheet: 'Lucia',
      name: 'ult_heal',
    },
  },
  exSpecial_sheerForce: {
    sheet: 'Lucia',
    name: 'exSpecial_sheerForce',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'sheerForce',
      sheet: 'Lucia',
      name: 'exSpecial_sheerForce',
    },
  },
} as const
