// WARNING: Generated file, do not modify
export const buffs = {
  core_hpSheerForce: {
    sheet: 'Yixuan',
    name: 'core_hpSheerForce',
    tag: {
      et: 'display',
      qt: 'initial',
      q: 'sheerForce',
      sheet: 'Yixuan',
      name: 'core_hpSheerForce',
    },
  },
  core_exSpecial_dmg_: {
    sheet: 'Yixuan',
    name: 'core_exSpecial_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dmg_',
      sheet: 'Yixuan',
      damageType1: 'exSpecial',
      name: 'core_exSpecial_dmg_',
    },
  },
  core_assistFollowUp_dmg_: {
    sheet: 'Yixuan',
    name: 'core_assistFollowUp_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dmg_',
      sheet: 'Yixuan',
      damageType1: 'assistFollowUp',
      name: 'core_assistFollowUp_dmg_',
    },
  },
  core_chain_dmg_: {
    sheet: 'Yixuan',
    name: 'core_chain_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dmg_',
      sheet: 'Yixuan',
      damageType1: 'chain',
      name: 'core_chain_dmg_',
    },
  },
  core_ult_dmg_: {
    sheet: 'Yixuan',
    name: 'core_ult_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'dmg_',
      sheet: 'Yixuan',
      damageType1: 'ult',
      name: 'core_ult_dmg_',
    },
  },
  core_dmg_: {
    sheet: 'Yixuan',
    name: 'core_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'common_dmg_',
      sheet: 'Yixuan',
      name: 'core_dmg_',
    },
  },
  ability_dmg_: {
    sheet: 'Yixuan',
    name: 'ability_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'common_dmg_',
      sheet: 'Yixuan',
      name: 'ability_dmg_',
    },
  },
  ability_crit_dmg_: {
    sheet: 'Yixuan',
    name: 'ability_crit_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_dmg_',
      sheet: 'Yixuan',
      name: 'ability_crit_dmg_',
    },
  },
  m1_crit_: {
    sheet: 'Yixuan',
    name: 'm1_crit_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'crit_',
      sheet: 'Yixuan',
      name: 'm1_crit_',
    },
  },
  m2_ult_ether_resIgn_: {
    sheet: 'Yixuan',
    name: 'm2_ult_ether_resIgn_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'resIgn_',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'ult',
      name: 'm2_ult_ether_resIgn_',
    },
  },
  m2_exSpecial_ether_resIgn_: {
    sheet: 'Yixuan',
    name: 'm2_exSpecial_ether_resIgn_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'resIgn_',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'exSpecial',
      name: 'm2_exSpecial_ether_resIgn_',
    },
  },
  m4_dmg_: {
    sheet: 'Yixuan',
    name: 'm4_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'common_dmg_',
      sheet: 'Yixuan',
      name: 'm4_dmg_',
    },
  },
  m6_sheer_dmg_: {
    sheet: 'Yixuan',
    name: 'm6_sheer_dmg_',
    tag: {
      et: 'display',
      qt: 'combat',
      q: 'sheer_dmg_',
      sheet: 'Yixuan',
      name: 'm6_sheer_dmg_',
    },
  },
} as const
