// WARNING: Generated file, do not modify
export const formulas = {
  sheerDmgInst: {
    sheet: 'Yixuan',
    name: 'sheerDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'sheerDmgBase',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'sheer',
      name: 'sheerDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Yixuan',
    name: 'anomalyDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_ether: {
    sheet: 'Yixuan',
    name: 'disorderDmgInst_ether',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'disorder',
      name: 'disorderDmgInst_ether',
    },
  },
  vortexDmgInst_ether: {
    sheet: 'Yixuan',
    name: 'vortexDmgInst_ether',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'vortex',
      name: 'vortexDmgInst_ether',
    },
  },
  abloomDmgInst: {
    sheet: 'Yixuan',
    name: 'abloomDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Yixuan',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yixuan',
      attribute: 'ether',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Yixuan',
    name: 'dazeInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'dazeBuildupBase',
      sheet: 'Yixuan',
      attribute: 'ether',
      name: 'dazeInst',
    },
  },
  BasicAttackCirrusStrike_0: {
    sheet: 'Yixuan',
    name: 'BasicAttackCirrusStrike_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackCirrusStrike_0',
    },
  },
  BasicAttackCirrusStrike_1: {
    sheet: 'Yixuan',
    name: 'BasicAttackCirrusStrike_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackCirrusStrike_1',
    },
  },
  BasicAttackCirrusStrike_2: {
    sheet: 'Yixuan',
    name: 'BasicAttackCirrusStrike_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackCirrusStrike_2',
    },
  },
  BasicAttackCirrusStrike_3: {
    sheet: 'Yixuan',
    name: 'BasicAttackCirrusStrike_3',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackCirrusStrike_3',
    },
  },
  BasicAttackCirrusStrike_4: {
    sheet: 'Yixuan',
    name: 'BasicAttackCirrusStrike_4',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackCirrusStrike_4',
    },
  },
  BasicAttackInkVeilCloudCoalescence_0: {
    sheet: 'Yixuan',
    name: 'BasicAttackInkVeilCloudCoalescence_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackInkVeilCloudCoalescence_0',
    },
  },
  BasicAttackAuricArray_0: {
    sheet: 'Yixuan',
    name: 'BasicAttackAuricArray_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackAuricArray_0',
    },
  },
  BasicAttackQingmingEruption_0: {
    sheet: 'Yixuan',
    name: 'BasicAttackQingmingEruption_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackQingmingEruption_0',
    },
  },
  DashAttackSkybreaker_0: {
    sheet: 'Yixuan',
    name: 'DashAttackSkybreaker_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackSkybreaker_0',
    },
  },
  DodgeCounterBanishingBlow_0: {
    sheet: 'Yixuan',
    name: 'DodgeCounterBanishingBlow_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterBanishingBlow_0',
    },
  },
  SpecialAttackShadowIgnition_0: {
    sheet: 'Yixuan',
    name: 'SpecialAttackShadowIgnition_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackShadowIgnition_0',
    },
  },
  EXSpecialAttackInkManifestation_0: {
    sheet: 'Yixuan',
    name: 'EXSpecialAttackInkManifestation_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackInkManifestation_0',
    },
  },
  EXSpecialAttackInkManifestation_1: {
    sheet: 'Yixuan',
    name: 'EXSpecialAttackInkManifestation_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackInkManifestation_1',
    },
  },
  EXSpecialAttackInkManifestation_2: {
    sheet: 'Yixuan',
    name: 'EXSpecialAttackInkManifestation_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackInkManifestation_2',
    },
  },
  EXSpecialAttackInkManifestation_3: {
    sheet: 'Yixuan',
    name: 'EXSpecialAttackInkManifestation_3',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackInkManifestation_3',
    },
  },
  EXSpecialAttackCloudShaper_0: {
    sheet: 'Yixuan',
    name: 'EXSpecialAttackCloudShaper_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackCloudShaper_0',
    },
  },
  EXSpecialAttackAshenInkBecomesShadows_0: {
    sheet: 'Yixuan',
    name: 'EXSpecialAttackAshenInkBecomesShadows_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackAshenInkBecomesShadows_0',
    },
  },
  ChainAttackAuricInkRush_0: {
    sheet: 'Yixuan',
    name: 'ChainAttackAuricInkRush_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackAuricInkRush_0',
    },
  },
  UltimateQingmingSkyshade_0: {
    sheet: 'Yixuan',
    name: 'UltimateQingmingSkyshade_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateQingmingSkyshade_0',
    },
  },
  UltimateEndlessTalismanSuppression_0: {
    sheet: 'Yixuan',
    name: 'UltimateEndlessTalismanSuppression_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateEndlessTalismanSuppression_0',
    },
  },
  QuickAssistCloudstreamShadow_0: {
    sheet: 'Yixuan',
    name: 'QuickAssistCloudstreamShadow_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistCloudstreamShadow_0',
    },
  },
  DefensiveAssistClearSkySurge_0: {
    sheet: 'Yixuan',
    name: 'DefensiveAssistClearSkySurge_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistClearSkySurge_0',
    },
  },
  DefensiveAssistClearSkySurge_1: {
    sheet: 'Yixuan',
    name: 'DefensiveAssistClearSkySurge_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistClearSkySurge_1',
    },
  },
  DefensiveAssistClearSkySurge_2: {
    sheet: 'Yixuan',
    name: 'DefensiveAssistClearSkySurge_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistClearSkySurge_2',
    },
  },
  AssistFollowUpCelestialCloudBlitz_0: {
    sheet: 'Yixuan',
    name: 'AssistFollowUpCelestialCloudBlitz_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpCelestialCloudBlitz_0',
    },
  },
  ability_dmg: {
    sheet: 'Yixuan',
    name: 'ability_dmg',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'sheerDmgBase',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'elemental',
      name: 'ability_dmg',
    },
  },
  m1_dmg: {
    sheet: 'Yixuan',
    name: 'm1_dmg',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'sheerDmgBase',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'elemental',
      name: 'm1_dmg',
    },
  },
  m2_dmg: {
    sheet: 'Yixuan',
    name: 'm2_dmg',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'sheerDmgBase',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'exSpecial',
      name: 'm2_dmg',
    },
  },
} as const
