// WARNING: Generated file, do not modify
export const formulas = {
  sheerDmgInst: {
    sheet: 'Yixuan',
    name: 'sheerDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'sheer',
      name: 'sheerDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Yixuan',
    name: 'anomalyDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_ether: {
    sheet: 'Yixuan',
    name: 'disorderDmgInst_ether',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'disorder',
      name: 'disorderDmgInst_ether',
    },
  },
  vortexDmgInst_ether: {
    sheet: 'Yixuan',
    name: 'vortexDmgInst_ether',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'vortex',
      name: 'vortexDmgInst_ether',
    },
  },
  abloomDmgInst: {
    sheet: 'Yixuan',
    name: 'abloomDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Yixuan',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yixuan',
      attribute: 'ether',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Yixuan',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yixuan',
      attribute: 'ether',
      name: 'dazeInst',
    },
  },
  'BasicAttackCirrusStrike_0:sheerDmg': {
    sheet: 'Yixuan',
    name: 'BasicAttackCirrusStrike_0:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackCirrusStrike_0',
    },
  },
  'BasicAttackCirrusStrike_0:dazeBuildup': {
    sheet: 'Yixuan',
    name: 'BasicAttackCirrusStrike_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackCirrusStrike_0',
    },
  },
  'BasicAttackCirrusStrike_0:anomBuildup': {
    sheet: 'Yixuan',
    name: 'BasicAttackCirrusStrike_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackCirrusStrike_0',
    },
  },
  'BasicAttackCirrusStrike_1:sheerDmg': {
    sheet: 'Yixuan',
    name: 'BasicAttackCirrusStrike_1:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackCirrusStrike_1',
    },
  },
  'BasicAttackCirrusStrike_1:dazeBuildup': {
    sheet: 'Yixuan',
    name: 'BasicAttackCirrusStrike_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackCirrusStrike_1',
    },
  },
  'BasicAttackCirrusStrike_1:anomBuildup': {
    sheet: 'Yixuan',
    name: 'BasicAttackCirrusStrike_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackCirrusStrike_1',
    },
  },
  'BasicAttackCirrusStrike_2:sheerDmg': {
    sheet: 'Yixuan',
    name: 'BasicAttackCirrusStrike_2:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackCirrusStrike_2',
    },
  },
  'BasicAttackCirrusStrike_2:dazeBuildup': {
    sheet: 'Yixuan',
    name: 'BasicAttackCirrusStrike_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackCirrusStrike_2',
    },
  },
  'BasicAttackCirrusStrike_2:anomBuildup': {
    sheet: 'Yixuan',
    name: 'BasicAttackCirrusStrike_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackCirrusStrike_2',
    },
  },
  'BasicAttackCirrusStrike_3:sheerDmg': {
    sheet: 'Yixuan',
    name: 'BasicAttackCirrusStrike_3:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackCirrusStrike_3',
    },
  },
  'BasicAttackCirrusStrike_3:dazeBuildup': {
    sheet: 'Yixuan',
    name: 'BasicAttackCirrusStrike_3:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackCirrusStrike_3',
    },
  },
  'BasicAttackCirrusStrike_3:anomBuildup': {
    sheet: 'Yixuan',
    name: 'BasicAttackCirrusStrike_3:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackCirrusStrike_3',
    },
  },
  'BasicAttackCirrusStrike_4:sheerDmg': {
    sheet: 'Yixuan',
    name: 'BasicAttackCirrusStrike_4:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackCirrusStrike_4',
    },
  },
  'BasicAttackCirrusStrike_4:dazeBuildup': {
    sheet: 'Yixuan',
    name: 'BasicAttackCirrusStrike_4:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackCirrusStrike_4',
    },
  },
  'BasicAttackCirrusStrike_4:anomBuildup': {
    sheet: 'Yixuan',
    name: 'BasicAttackCirrusStrike_4:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackCirrusStrike_4',
    },
  },
  'BasicAttackInkVeilCloudCoalescence_0:sheerDmg': {
    sheet: 'Yixuan',
    name: 'BasicAttackInkVeilCloudCoalescence_0:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackInkVeilCloudCoalescence_0',
    },
  },
  'BasicAttackInkVeilCloudCoalescence_0:dazeBuildup': {
    sheet: 'Yixuan',
    name: 'BasicAttackInkVeilCloudCoalescence_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackInkVeilCloudCoalescence_0',
    },
  },
  'BasicAttackInkVeilCloudCoalescence_0:anomBuildup': {
    sheet: 'Yixuan',
    name: 'BasicAttackInkVeilCloudCoalescence_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackInkVeilCloudCoalescence_0',
    },
  },
  'BasicAttackAuricArray_0:sheerDmg': {
    sheet: 'Yixuan',
    name: 'BasicAttackAuricArray_0:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackAuricArray_0',
    },
  },
  'BasicAttackAuricArray_0:dazeBuildup': {
    sheet: 'Yixuan',
    name: 'BasicAttackAuricArray_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackAuricArray_0',
    },
  },
  'BasicAttackAuricArray_0:anomBuildup': {
    sheet: 'Yixuan',
    name: 'BasicAttackAuricArray_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackAuricArray_0',
    },
  },
  'BasicAttackQingmingEruption_0:sheerDmg': {
    sheet: 'Yixuan',
    name: 'BasicAttackQingmingEruption_0:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackQingmingEruption_0',
    },
  },
  'BasicAttackQingmingEruption_0:dazeBuildup': {
    sheet: 'Yixuan',
    name: 'BasicAttackQingmingEruption_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackQingmingEruption_0',
    },
  },
  'BasicAttackQingmingEruption_0:anomBuildup': {
    sheet: 'Yixuan',
    name: 'BasicAttackQingmingEruption_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackQingmingEruption_0',
    },
  },
  'DashAttackSkybreaker_0:sheerDmg': {
    sheet: 'Yixuan',
    name: 'DashAttackSkybreaker_0:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'dash',
      skillType1: 'dodgeSkill',
      name: 'DashAttackSkybreaker_0',
    },
  },
  'DashAttackSkybreaker_0:dazeBuildup': {
    sheet: 'Yixuan',
    name: 'DashAttackSkybreaker_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'dash',
      skillType1: 'dodgeSkill',
      name: 'DashAttackSkybreaker_0',
    },
  },
  'DashAttackSkybreaker_0:anomBuildup': {
    sheet: 'Yixuan',
    name: 'DashAttackSkybreaker_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'dash',
      skillType1: 'dodgeSkill',
      name: 'DashAttackSkybreaker_0',
    },
  },
  'DodgeCounterBanishingBlow_0:sheerDmg': {
    sheet: 'Yixuan',
    name: 'DodgeCounterBanishingBlow_0:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'dodgeCounter',
      skillType1: 'dodgeSkill',
      name: 'DodgeCounterBanishingBlow_0',
    },
  },
  'DodgeCounterBanishingBlow_0:dazeBuildup': {
    sheet: 'Yixuan',
    name: 'DodgeCounterBanishingBlow_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'dodgeCounter',
      skillType1: 'dodgeSkill',
      name: 'DodgeCounterBanishingBlow_0',
    },
  },
  'DodgeCounterBanishingBlow_0:anomBuildup': {
    sheet: 'Yixuan',
    name: 'DodgeCounterBanishingBlow_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'dodgeCounter',
      skillType1: 'dodgeSkill',
      name: 'DodgeCounterBanishingBlow_0',
    },
  },
  'SpecialAttackShadowIgnition_0:sheerDmg': {
    sheet: 'Yixuan',
    name: 'SpecialAttackShadowIgnition_0:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackShadowIgnition_0',
    },
  },
  'SpecialAttackShadowIgnition_0:dazeBuildup': {
    sheet: 'Yixuan',
    name: 'SpecialAttackShadowIgnition_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackShadowIgnition_0',
    },
  },
  'SpecialAttackShadowIgnition_0:anomBuildup': {
    sheet: 'Yixuan',
    name: 'SpecialAttackShadowIgnition_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackShadowIgnition_0',
    },
  },
  'EXSpecialAttackInkManifestation_0:sheerDmg': {
    sheet: 'Yixuan',
    name: 'EXSpecialAttackInkManifestation_0:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackInkManifestation_0',
    },
  },
  'EXSpecialAttackInkManifestation_0:dazeBuildup': {
    sheet: 'Yixuan',
    name: 'EXSpecialAttackInkManifestation_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackInkManifestation_0',
    },
  },
  'EXSpecialAttackInkManifestation_0:anomBuildup': {
    sheet: 'Yixuan',
    name: 'EXSpecialAttackInkManifestation_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackInkManifestation_0',
    },
  },
  'EXSpecialAttackInkManifestation_1:sheerDmg': {
    sheet: 'Yixuan',
    name: 'EXSpecialAttackInkManifestation_1:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackInkManifestation_1',
    },
  },
  'EXSpecialAttackInkManifestation_1:dazeBuildup': {
    sheet: 'Yixuan',
    name: 'EXSpecialAttackInkManifestation_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackInkManifestation_1',
    },
  },
  'EXSpecialAttackInkManifestation_1:anomBuildup': {
    sheet: 'Yixuan',
    name: 'EXSpecialAttackInkManifestation_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackInkManifestation_1',
    },
  },
  'EXSpecialAttackInkManifestation_2:sheerDmg': {
    sheet: 'Yixuan',
    name: 'EXSpecialAttackInkManifestation_2:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackInkManifestation_2',
    },
  },
  'EXSpecialAttackInkManifestation_2:dazeBuildup': {
    sheet: 'Yixuan',
    name: 'EXSpecialAttackInkManifestation_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackInkManifestation_2',
    },
  },
  'EXSpecialAttackInkManifestation_2:anomBuildup': {
    sheet: 'Yixuan',
    name: 'EXSpecialAttackInkManifestation_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackInkManifestation_2',
    },
  },
  'EXSpecialAttackInkManifestation_3:sheerDmg': {
    sheet: 'Yixuan',
    name: 'EXSpecialAttackInkManifestation_3:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackInkManifestation_3',
    },
  },
  'EXSpecialAttackInkManifestation_3:dazeBuildup': {
    sheet: 'Yixuan',
    name: 'EXSpecialAttackInkManifestation_3:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackInkManifestation_3',
    },
  },
  'EXSpecialAttackInkManifestation_3:anomBuildup': {
    sheet: 'Yixuan',
    name: 'EXSpecialAttackInkManifestation_3:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackInkManifestation_3',
    },
  },
  'EXSpecialAttackCloudShaper_0:sheerDmg': {
    sheet: 'Yixuan',
    name: 'EXSpecialAttackCloudShaper_0:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackCloudShaper_0',
    },
  },
  'EXSpecialAttackCloudShaper_0:dazeBuildup': {
    sheet: 'Yixuan',
    name: 'EXSpecialAttackCloudShaper_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackCloudShaper_0',
    },
  },
  'EXSpecialAttackCloudShaper_0:anomBuildup': {
    sheet: 'Yixuan',
    name: 'EXSpecialAttackCloudShaper_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackCloudShaper_0',
    },
  },
  'EXSpecialAttackAshenInkBecomesShadows_0:sheerDmg': {
    sheet: 'Yixuan',
    name: 'EXSpecialAttackAshenInkBecomesShadows_0:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackAshenInkBecomesShadows_0',
    },
  },
  'EXSpecialAttackAshenInkBecomesShadows_0:dazeBuildup': {
    sheet: 'Yixuan',
    name: 'EXSpecialAttackAshenInkBecomesShadows_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackAshenInkBecomesShadows_0',
    },
  },
  'EXSpecialAttackAshenInkBecomesShadows_0:anomBuildup': {
    sheet: 'Yixuan',
    name: 'EXSpecialAttackAshenInkBecomesShadows_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackAshenInkBecomesShadows_0',
    },
  },
  'ChainAttackAuricInkRush_0:sheerDmg': {
    sheet: 'Yixuan',
    name: 'ChainAttackAuricInkRush_0:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'chain',
      skillType1: 'chainSkill',
      name: 'ChainAttackAuricInkRush_0',
    },
  },
  'ChainAttackAuricInkRush_0:dazeBuildup': {
    sheet: 'Yixuan',
    name: 'ChainAttackAuricInkRush_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'chain',
      skillType1: 'chainSkill',
      name: 'ChainAttackAuricInkRush_0',
    },
  },
  'ChainAttackAuricInkRush_0:anomBuildup': {
    sheet: 'Yixuan',
    name: 'ChainAttackAuricInkRush_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'chain',
      skillType1: 'chainSkill',
      name: 'ChainAttackAuricInkRush_0',
    },
  },
  'UltimateQingmingSkyshade_0:sheerDmg': {
    sheet: 'Yixuan',
    name: 'UltimateQingmingSkyshade_0:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'ult',
      skillType1: 'chainSkill',
      name: 'UltimateQingmingSkyshade_0',
    },
  },
  'UltimateQingmingSkyshade_0:dazeBuildup': {
    sheet: 'Yixuan',
    name: 'UltimateQingmingSkyshade_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'ult',
      skillType1: 'chainSkill',
      name: 'UltimateQingmingSkyshade_0',
    },
  },
  'UltimateQingmingSkyshade_0:anomBuildup': {
    sheet: 'Yixuan',
    name: 'UltimateQingmingSkyshade_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'ult',
      skillType1: 'chainSkill',
      name: 'UltimateQingmingSkyshade_0',
    },
  },
  'UltimateEndlessTalismanSuppression_0:sheerDmg': {
    sheet: 'Yixuan',
    name: 'UltimateEndlessTalismanSuppression_0:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'ult',
      skillType1: 'chainSkill',
      name: 'UltimateEndlessTalismanSuppression_0',
    },
  },
  'UltimateEndlessTalismanSuppression_0:dazeBuildup': {
    sheet: 'Yixuan',
    name: 'UltimateEndlessTalismanSuppression_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'ult',
      skillType1: 'chainSkill',
      name: 'UltimateEndlessTalismanSuppression_0',
    },
  },
  'UltimateEndlessTalismanSuppression_0:anomBuildup': {
    sheet: 'Yixuan',
    name: 'UltimateEndlessTalismanSuppression_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'ult',
      skillType1: 'chainSkill',
      name: 'UltimateEndlessTalismanSuppression_0',
    },
  },
  'QuickAssistCloudstreamShadow_0:sheerDmg': {
    sheet: 'Yixuan',
    name: 'QuickAssistCloudstreamShadow_0:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'quickAssist',
      skillType1: 'assistSkill',
      name: 'QuickAssistCloudstreamShadow_0',
    },
  },
  'QuickAssistCloudstreamShadow_0:dazeBuildup': {
    sheet: 'Yixuan',
    name: 'QuickAssistCloudstreamShadow_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'quickAssist',
      skillType1: 'assistSkill',
      name: 'QuickAssistCloudstreamShadow_0',
    },
  },
  'QuickAssistCloudstreamShadow_0:anomBuildup': {
    sheet: 'Yixuan',
    name: 'QuickAssistCloudstreamShadow_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'quickAssist',
      skillType1: 'assistSkill',
      name: 'QuickAssistCloudstreamShadow_0',
    },
  },
  'DefensiveAssistClearSkySurge_0:sheerDmg': {
    sheet: 'Yixuan',
    name: 'DefensiveAssistClearSkySurge_0:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistClearSkySurge_0',
    },
  },
  'DefensiveAssistClearSkySurge_0:dazeBuildup': {
    sheet: 'Yixuan',
    name: 'DefensiveAssistClearSkySurge_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistClearSkySurge_0',
    },
  },
  'DefensiveAssistClearSkySurge_0:anomBuildup': {
    sheet: 'Yixuan',
    name: 'DefensiveAssistClearSkySurge_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistClearSkySurge_0',
    },
  },
  'DefensiveAssistClearSkySurge_1:sheerDmg': {
    sheet: 'Yixuan',
    name: 'DefensiveAssistClearSkySurge_1:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistClearSkySurge_1',
    },
  },
  'DefensiveAssistClearSkySurge_1:dazeBuildup': {
    sheet: 'Yixuan',
    name: 'DefensiveAssistClearSkySurge_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistClearSkySurge_1',
    },
  },
  'DefensiveAssistClearSkySurge_1:anomBuildup': {
    sheet: 'Yixuan',
    name: 'DefensiveAssistClearSkySurge_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistClearSkySurge_1',
    },
  },
  'DefensiveAssistClearSkySurge_2:sheerDmg': {
    sheet: 'Yixuan',
    name: 'DefensiveAssistClearSkySurge_2:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistClearSkySurge_2',
    },
  },
  'DefensiveAssistClearSkySurge_2:dazeBuildup': {
    sheet: 'Yixuan',
    name: 'DefensiveAssistClearSkySurge_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistClearSkySurge_2',
    },
  },
  'DefensiveAssistClearSkySurge_2:anomBuildup': {
    sheet: 'Yixuan',
    name: 'DefensiveAssistClearSkySurge_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistClearSkySurge_2',
    },
  },
  'AssistFollowUpCelestialCloudBlitz_0:sheerDmg': {
    sheet: 'Yixuan',
    name: 'AssistFollowUpCelestialCloudBlitz_0:sheerDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'assistFollowUp',
      skillType1: 'assistSkill',
      name: 'AssistFollowUpCelestialCloudBlitz_0',
    },
  },
  'AssistFollowUpCelestialCloudBlitz_0:dazeBuildup': {
    sheet: 'Yixuan',
    name: 'AssistFollowUpCelestialCloudBlitz_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'assistFollowUp',
      skillType1: 'assistSkill',
      name: 'AssistFollowUpCelestialCloudBlitz_0',
    },
  },
  'AssistFollowUpCelestialCloudBlitz_0:anomBuildup': {
    sheet: 'Yixuan',
    name: 'AssistFollowUpCelestialCloudBlitz_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'assistFollowUp',
      skillType1: 'assistSkill',
      name: 'AssistFollowUpCelestialCloudBlitz_0',
    },
  },
  ability_dmg: {
    sheet: 'Yixuan',
    name: 'ability_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'elemental',
      name: 'ability_dmg',
    },
  },
  m1_dmg: {
    sheet: 'Yixuan',
    name: 'm1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'elemental',
      name: 'm1_dmg',
    },
  },
  m2_dmg: {
    sheet: 'Yixuan',
    name: 'm2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'sheerDmg',
      sheet: 'Yixuan',
      attribute: 'ether',
      damageType1: 'exSpecial',
      name: 'm2_dmg',
    },
  },
} as const
