// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Promeia',
    name: 'standardDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Promeia',
      attribute: 'ice',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Promeia',
    name: 'anomalyDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_ice: {
    sheet: 'Promeia',
    name: 'disorderDmgInst_ice',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'disorder',
      name: 'disorderDmgInst_ice',
    },
  },
  vortexDmgInst_ice: {
    sheet: 'Promeia',
    name: 'vortexDmgInst_ice',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'vortex',
      name: 'vortexDmgInst_ice',
    },
  },
  abloomDmgInst: {
    sheet: 'Promeia',
    name: 'abloomDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Promeia',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Promeia',
      attribute: 'ice',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Promeia',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Promeia',
      attribute: 'ice',
      name: 'dazeInst',
    },
  },
  BasicAttackSweepingEdge_0_dmg: {
    sheet: 'Promeia',
    name: 'BasicAttackSweepingEdge_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSweepingEdge_0_dmg',
    },
  },
  BasicAttackSweepingEdge_0_daze: {
    sheet: 'Promeia',
    name: 'BasicAttackSweepingEdge_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSweepingEdge_0_daze',
    },
  },
  BasicAttackSweepingEdge_0_anomBuildup: {
    sheet: 'Promeia',
    name: 'BasicAttackSweepingEdge_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSweepingEdge_0_anomBuildup',
    },
  },
  BasicAttackSweepingEdge_1_dmg: {
    sheet: 'Promeia',
    name: 'BasicAttackSweepingEdge_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSweepingEdge_1_dmg',
    },
  },
  BasicAttackSweepingEdge_1_daze: {
    sheet: 'Promeia',
    name: 'BasicAttackSweepingEdge_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSweepingEdge_1_daze',
    },
  },
  BasicAttackSweepingEdge_1_anomBuildup: {
    sheet: 'Promeia',
    name: 'BasicAttackSweepingEdge_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSweepingEdge_1_anomBuildup',
    },
  },
  BasicAttackSweepingEdge_2_dmg: {
    sheet: 'Promeia',
    name: 'BasicAttackSweepingEdge_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSweepingEdge_2_dmg',
    },
  },
  BasicAttackSweepingEdge_2_daze: {
    sheet: 'Promeia',
    name: 'BasicAttackSweepingEdge_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSweepingEdge_2_daze',
    },
  },
  BasicAttackSweepingEdge_2_anomBuildup: {
    sheet: 'Promeia',
    name: 'BasicAttackSweepingEdge_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSweepingEdge_2_anomBuildup',
    },
  },
  BasicAttackSweepingEdge_3_dmg: {
    sheet: 'Promeia',
    name: 'BasicAttackSweepingEdge_3_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSweepingEdge_3_dmg',
    },
  },
  BasicAttackSweepingEdge_3_daze: {
    sheet: 'Promeia',
    name: 'BasicAttackSweepingEdge_3_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSweepingEdge_3_daze',
    },
  },
  BasicAttackSweepingEdge_3_anomBuildup: {
    sheet: 'Promeia',
    name: 'BasicAttackSweepingEdge_3_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSweepingEdge_3_anomBuildup',
    },
  },
  BasicAttackSweepingEdge_4_dmg: {
    sheet: 'Promeia',
    name: 'BasicAttackSweepingEdge_4_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSweepingEdge_4_dmg',
    },
  },
  BasicAttackSweepingEdge_4_daze: {
    sheet: 'Promeia',
    name: 'BasicAttackSweepingEdge_4_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSweepingEdge_4_daze',
    },
  },
  BasicAttackSweepingEdge_4_anomBuildup: {
    sheet: 'Promeia',
    name: 'BasicAttackSweepingEdge_4_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSweepingEdge_4_anomBuildup',
    },
  },
  BasicAttackSweepingEdge_5_dmg: {
    sheet: 'Promeia',
    name: 'BasicAttackSweepingEdge_5_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSweepingEdge_5_dmg',
    },
  },
  BasicAttackSweepingEdge_5_daze: {
    sheet: 'Promeia',
    name: 'BasicAttackSweepingEdge_5_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSweepingEdge_5_daze',
    },
  },
  BasicAttackSweepingEdge_5_anomBuildup: {
    sheet: 'Promeia',
    name: 'BasicAttackSweepingEdge_5_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSweepingEdge_5_anomBuildup',
    },
  },
  BasicAttackWhirlingBlade_0_dmg: {
    sheet: 'Promeia',
    name: 'BasicAttackWhirlingBlade_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackWhirlingBlade_0_dmg',
    },
  },
  BasicAttackWhirlingBlade_0_daze: {
    sheet: 'Promeia',
    name: 'BasicAttackWhirlingBlade_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackWhirlingBlade_0_daze',
    },
  },
  BasicAttackWhirlingBlade_0_anomBuildup: {
    sheet: 'Promeia',
    name: 'BasicAttackWhirlingBlade_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackWhirlingBlade_0_anomBuildup',
    },
  },
  DashAttackGrimReap_0_dmg: {
    sheet: 'Promeia',
    name: 'DashAttackGrimReap_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackGrimReap_0_dmg',
    },
  },
  DashAttackGrimReap_0_daze: {
    sheet: 'Promeia',
    name: 'DashAttackGrimReap_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackGrimReap_0_daze',
    },
  },
  DashAttackGrimReap_0_anomBuildup: {
    sheet: 'Promeia',
    name: 'DashAttackGrimReap_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackGrimReap_0_anomBuildup',
    },
  },
  DodgeCounterSoaringBat_0_dmg: {
    sheet: 'Promeia',
    name: 'DodgeCounterSoaringBat_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterSoaringBat_0_dmg',
    },
  },
  DodgeCounterSoaringBat_0_daze: {
    sheet: 'Promeia',
    name: 'DodgeCounterSoaringBat_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterSoaringBat_0_daze',
    },
  },
  DodgeCounterSoaringBat_0_anomBuildup: {
    sheet: 'Promeia',
    name: 'DodgeCounterSoaringBat_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterSoaringBat_0_anomBuildup',
    },
  },
  SpecialAttackExecutionColdFlash_0_dmg: {
    sheet: 'Promeia',
    name: 'SpecialAttackExecutionColdFlash_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackExecutionColdFlash_0_dmg',
    },
  },
  SpecialAttackExecutionColdFlash_0_daze: {
    sheet: 'Promeia',
    name: 'SpecialAttackExecutionColdFlash_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackExecutionColdFlash_0_daze',
    },
  },
  SpecialAttackExecutionColdFlash_0_anomBuildup: {
    sheet: 'Promeia',
    name: 'SpecialAttackExecutionColdFlash_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackExecutionColdFlash_0_anomBuildup',
    },
  },
  EXSpecialAttackExecutionGlacialDeath_0_dmg: {
    sheet: 'Promeia',
    name: 'EXSpecialAttackExecutionGlacialDeath_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackExecutionGlacialDeath_0_dmg',
    },
  },
  EXSpecialAttackExecutionGlacialDeath_0_daze: {
    sheet: 'Promeia',
    name: 'EXSpecialAttackExecutionGlacialDeath_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackExecutionGlacialDeath_0_daze',
    },
  },
  EXSpecialAttackExecutionGlacialDeath_0_anomBuildup: {
    sheet: 'Promeia',
    name: 'EXSpecialAttackExecutionGlacialDeath_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackExecutionGlacialDeath_0_anomBuildup',
    },
  },
  SpecialAttackExecutionDescendingFrost_0_dmg: {
    sheet: 'Promeia',
    name: 'SpecialAttackExecutionDescendingFrost_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackExecutionDescendingFrost_0_dmg',
    },
  },
  SpecialAttackExecutionDescendingFrost_0_daze: {
    sheet: 'Promeia',
    name: 'SpecialAttackExecutionDescendingFrost_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackExecutionDescendingFrost_0_daze',
    },
  },
  SpecialAttackExecutionDescendingFrost_0_anomBuildup: {
    sheet: 'Promeia',
    name: 'SpecialAttackExecutionDescendingFrost_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackExecutionDescendingFrost_0_anomBuildup',
    },
  },
  SpecialAttackExecutionLayeredFrost_0_dmg: {
    sheet: 'Promeia',
    name: 'SpecialAttackExecutionLayeredFrost_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackExecutionLayeredFrost_0_dmg',
    },
  },
  SpecialAttackExecutionLayeredFrost_0_daze: {
    sheet: 'Promeia',
    name: 'SpecialAttackExecutionLayeredFrost_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackExecutionLayeredFrost_0_daze',
    },
  },
  SpecialAttackExecutionLayeredFrost_0_anomBuildup: {
    sheet: 'Promeia',
    name: 'SpecialAttackExecutionLayeredFrost_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackExecutionLayeredFrost_0_anomBuildup',
    },
  },
  SpecialAttackExecutionLayeredFrost_1_dmg: {
    sheet: 'Promeia',
    name: 'SpecialAttackExecutionLayeredFrost_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackExecutionLayeredFrost_1_dmg',
    },
  },
  SpecialAttackExecutionLayeredFrost_1_daze: {
    sheet: 'Promeia',
    name: 'SpecialAttackExecutionLayeredFrost_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackExecutionLayeredFrost_1_daze',
    },
  },
  SpecialAttackExecutionLayeredFrost_1_anomBuildup: {
    sheet: 'Promeia',
    name: 'SpecialAttackExecutionLayeredFrost_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackExecutionLayeredFrost_1_anomBuildup',
    },
  },
  EXSpecialAttackExecutionMercilessJudgment_0_dmg: {
    sheet: 'Promeia',
    name: 'EXSpecialAttackExecutionMercilessJudgment_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackExecutionMercilessJudgment_0_dmg',
    },
  },
  EXSpecialAttackExecutionMercilessJudgment_0_daze: {
    sheet: 'Promeia',
    name: 'EXSpecialAttackExecutionMercilessJudgment_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackExecutionMercilessJudgment_0_daze',
    },
  },
  EXSpecialAttackExecutionMercilessJudgment_0_anomBuildup: {
    sheet: 'Promeia',
    name: 'EXSpecialAttackExecutionMercilessJudgment_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackExecutionMercilessJudgment_0_anomBuildup',
    },
  },
  ChainAttackHangingJudgment_0_dmg: {
    sheet: 'Promeia',
    name: 'ChainAttackHangingJudgment_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackHangingJudgment_0_dmg',
    },
  },
  ChainAttackHangingJudgment_0_daze: {
    sheet: 'Promeia',
    name: 'ChainAttackHangingJudgment_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackHangingJudgment_0_daze',
    },
  },
  ChainAttackHangingJudgment_0_anomBuildup: {
    sheet: 'Promeia',
    name: 'ChainAttackHangingJudgment_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackHangingJudgment_0_anomBuildup',
    },
  },
  UltimateGlaciatingImpalement_0_dmg: {
    sheet: 'Promeia',
    name: 'UltimateGlaciatingImpalement_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateGlaciatingImpalement_0_dmg',
    },
  },
  UltimateGlaciatingImpalement_0_daze: {
    sheet: 'Promeia',
    name: 'UltimateGlaciatingImpalement_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateGlaciatingImpalement_0_daze',
    },
  },
  UltimateGlaciatingImpalement_0_anomBuildup: {
    sheet: 'Promeia',
    name: 'UltimateGlaciatingImpalement_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateGlaciatingImpalement_0_anomBuildup',
    },
  },
  QuickAssistAmbushingStrike_0_dmg: {
    sheet: 'Promeia',
    name: 'QuickAssistAmbushingStrike_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistAmbushingStrike_0_dmg',
    },
  },
  QuickAssistAmbushingStrike_0_daze: {
    sheet: 'Promeia',
    name: 'QuickAssistAmbushingStrike_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistAmbushingStrike_0_daze',
    },
  },
  QuickAssistAmbushingStrike_0_anomBuildup: {
    sheet: 'Promeia',
    name: 'QuickAssistAmbushingStrike_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistAmbushingStrike_0_anomBuildup',
    },
  },
  DefensiveAssistInjunction_0_dmg: {
    sheet: 'Promeia',
    name: 'DefensiveAssistInjunction_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistInjunction_0_dmg',
    },
  },
  DefensiveAssistInjunction_0_daze: {
    sheet: 'Promeia',
    name: 'DefensiveAssistInjunction_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistInjunction_0_daze',
    },
  },
  DefensiveAssistInjunction_0_anomBuildup: {
    sheet: 'Promeia',
    name: 'DefensiveAssistInjunction_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistInjunction_0_anomBuildup',
    },
  },
  DefensiveAssistInjunction_1_dmg: {
    sheet: 'Promeia',
    name: 'DefensiveAssistInjunction_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistInjunction_1_dmg',
    },
  },
  DefensiveAssistInjunction_1_daze: {
    sheet: 'Promeia',
    name: 'DefensiveAssistInjunction_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistInjunction_1_daze',
    },
  },
  DefensiveAssistInjunction_1_anomBuildup: {
    sheet: 'Promeia',
    name: 'DefensiveAssistInjunction_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistInjunction_1_anomBuildup',
    },
  },
  DefensiveAssistInjunction_2_dmg: {
    sheet: 'Promeia',
    name: 'DefensiveAssistInjunction_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistInjunction_2_dmg',
    },
  },
  DefensiveAssistInjunction_2_daze: {
    sheet: 'Promeia',
    name: 'DefensiveAssistInjunction_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistInjunction_2_daze',
    },
  },
  DefensiveAssistInjunction_2_anomBuildup: {
    sheet: 'Promeia',
    name: 'DefensiveAssistInjunction_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistInjunction_2_anomBuildup',
    },
  },
  AssistFollowUpInterceptingStrike_0_dmg: {
    sheet: 'Promeia',
    name: 'AssistFollowUpInterceptingStrike_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpInterceptingStrike_0_dmg',
    },
  },
  AssistFollowUpInterceptingStrike_0_daze: {
    sheet: 'Promeia',
    name: 'AssistFollowUpInterceptingStrike_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpInterceptingStrike_0_daze',
    },
  },
  AssistFollowUpInterceptingStrike_0_anomBuildup: {
    sheet: 'Promeia',
    name: 'AssistFollowUpInterceptingStrike_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Promeia',
      attribute: 'ice',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpInterceptingStrike_0_anomBuildup',
    },
  },
} as const
