// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Harumasa',
    name: 'standardDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Harumasa',
      attribute: 'electric',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Harumasa',
    name: 'anomalyDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_electric: {
    sheet: 'Harumasa',
    name: 'disorderDmgInst_electric',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'disorder',
      name: 'disorderDmgInst_electric',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Harumasa',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Harumasa',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      name: 'dazeInst',
    },
  },
  BasicAttackCloudPiercer_0_dmg: {
    sheet: 'Harumasa',
    name: 'BasicAttackCloudPiercer_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Harumasa',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackCloudPiercer_0_dmg',
    },
  },
  BasicAttackCloudPiercer_0_daze: {
    sheet: 'Harumasa',
    name: 'BasicAttackCloudPiercer_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Harumasa',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackCloudPiercer_0_daze',
    },
  },
  BasicAttackCloudPiercer_0_anomBuildup: {
    sheet: 'Harumasa',
    name: 'BasicAttackCloudPiercer_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Harumasa',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackCloudPiercer_0_anomBuildup',
    },
  },
  BasicAttackCloudPiercer_1_dmg: {
    sheet: 'Harumasa',
    name: 'BasicAttackCloudPiercer_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Harumasa',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackCloudPiercer_1_dmg',
    },
  },
  BasicAttackCloudPiercer_1_daze: {
    sheet: 'Harumasa',
    name: 'BasicAttackCloudPiercer_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Harumasa',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackCloudPiercer_1_daze',
    },
  },
  BasicAttackCloudPiercer_1_anomBuildup: {
    sheet: 'Harumasa',
    name: 'BasicAttackCloudPiercer_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Harumasa',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackCloudPiercer_1_anomBuildup',
    },
  },
  BasicAttackCloudPiercer_2_dmg: {
    sheet: 'Harumasa',
    name: 'BasicAttackCloudPiercer_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Harumasa',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackCloudPiercer_2_dmg',
    },
  },
  BasicAttackCloudPiercer_2_daze: {
    sheet: 'Harumasa',
    name: 'BasicAttackCloudPiercer_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Harumasa',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackCloudPiercer_2_daze',
    },
  },
  BasicAttackCloudPiercer_2_anomBuildup: {
    sheet: 'Harumasa',
    name: 'BasicAttackCloudPiercer_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Harumasa',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackCloudPiercer_2_anomBuildup',
    },
  },
  BasicAttackCloudPiercer_3_dmg: {
    sheet: 'Harumasa',
    name: 'BasicAttackCloudPiercer_3_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackCloudPiercer_3_dmg',
    },
  },
  BasicAttackCloudPiercer_3_daze: {
    sheet: 'Harumasa',
    name: 'BasicAttackCloudPiercer_3_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackCloudPiercer_3_daze',
    },
  },
  BasicAttackCloudPiercer_3_anomBuildup: {
    sheet: 'Harumasa',
    name: 'BasicAttackCloudPiercer_3_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackCloudPiercer_3_anomBuildup',
    },
  },
  BasicAttackCloudPiercer_4_dmg: {
    sheet: 'Harumasa',
    name: 'BasicAttackCloudPiercer_4_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackCloudPiercer_4_dmg',
    },
  },
  BasicAttackCloudPiercer_4_daze: {
    sheet: 'Harumasa',
    name: 'BasicAttackCloudPiercer_4_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackCloudPiercer_4_daze',
    },
  },
  BasicAttackCloudPiercer_4_anomBuildup: {
    sheet: 'Harumasa',
    name: 'BasicAttackCloudPiercer_4_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackCloudPiercer_4_anomBuildup',
    },
  },
  BasicAttackCloudPiercerDrift_0_dmg: {
    sheet: 'Harumasa',
    name: 'BasicAttackCloudPiercerDrift_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Harumasa',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackCloudPiercerDrift_0_dmg',
    },
  },
  BasicAttackCloudPiercerDrift_0_daze: {
    sheet: 'Harumasa',
    name: 'BasicAttackCloudPiercerDrift_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Harumasa',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackCloudPiercerDrift_0_daze',
    },
  },
  BasicAttackCloudPiercerDrift_0_anomBuildup: {
    sheet: 'Harumasa',
    name: 'BasicAttackCloudPiercerDrift_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Harumasa',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackCloudPiercerDrift_0_anomBuildup',
    },
  },
  BasicAttackFallingFeather_0_dmg: {
    sheet: 'Harumasa',
    name: 'BasicAttackFallingFeather_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFallingFeather_0_dmg',
    },
  },
  BasicAttackFallingFeather_0_daze: {
    sheet: 'Harumasa',
    name: 'BasicAttackFallingFeather_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFallingFeather_0_daze',
    },
  },
  BasicAttackFallingFeather_0_anomBuildup: {
    sheet: 'Harumasa',
    name: 'BasicAttackFallingFeather_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFallingFeather_0_anomBuildup',
    },
  },
  BasicAttackHaOtoNoYa_0_dmg: {
    sheet: 'Harumasa',
    name: 'BasicAttackHaOtoNoYa_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackHaOtoNoYa_0_dmg',
    },
  },
  BasicAttackHaOtoNoYa_0_daze: {
    sheet: 'Harumasa',
    name: 'BasicAttackHaOtoNoYa_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackHaOtoNoYa_0_daze',
    },
  },
  BasicAttackHaOtoNoYa_0_anomBuildup: {
    sheet: 'Harumasa',
    name: 'BasicAttackHaOtoNoYa_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackHaOtoNoYa_0_anomBuildup',
    },
  },
  DashAttackHitenNoTsuru_0_dmg: {
    sheet: 'Harumasa',
    name: 'DashAttackHitenNoTsuru_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Harumasa',
      damageType1: 'dash',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttackHitenNoTsuru_0_dmg',
    },
  },
  DashAttackHitenNoTsuru_0_daze: {
    sheet: 'Harumasa',
    name: 'DashAttackHitenNoTsuru_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Harumasa',
      damageType1: 'dash',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttackHitenNoTsuru_0_daze',
    },
  },
  DashAttackHitenNoTsuru_0_anomBuildup: {
    sheet: 'Harumasa',
    name: 'DashAttackHitenNoTsuru_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Harumasa',
      damageType1: 'dash',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttackHitenNoTsuru_0_anomBuildup',
    },
  },
  DodgeCounterHiddenEdge_0_dmg: {
    sheet: 'Harumasa',
    name: 'DodgeCounterHiddenEdge_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterHiddenEdge_0_dmg',
    },
  },
  DodgeCounterHiddenEdge_0_daze: {
    sheet: 'Harumasa',
    name: 'DodgeCounterHiddenEdge_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterHiddenEdge_0_daze',
    },
  },
  DodgeCounterHiddenEdge_0_anomBuildup: {
    sheet: 'Harumasa',
    name: 'DodgeCounterHiddenEdge_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterHiddenEdge_0_anomBuildup',
    },
  },
  DashAttackHitenNoTsuruSlash_0_dmg: {
    sheet: 'Harumasa',
    name: 'DashAttackHitenNoTsuruSlash_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackHitenNoTsuruSlash_0_dmg',
    },
  },
  DashAttackHitenNoTsuruSlash_0_daze: {
    sheet: 'Harumasa',
    name: 'DashAttackHitenNoTsuruSlash_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackHitenNoTsuruSlash_0_daze',
    },
  },
  DashAttackHitenNoTsuruSlash_0_anomBuildup: {
    sheet: 'Harumasa',
    name: 'DashAttackHitenNoTsuruSlash_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackHitenNoTsuruSlash_0_anomBuildup',
    },
  },
  DashAttackHitenNoTsuruSlash_1_dmg: {
    sheet: 'Harumasa',
    name: 'DashAttackHitenNoTsuruSlash_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackHitenNoTsuruSlash_1_dmg',
    },
  },
  DashAttackHitenNoTsuruSlash_1_daze: {
    sheet: 'Harumasa',
    name: 'DashAttackHitenNoTsuruSlash_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackHitenNoTsuruSlash_1_daze',
    },
  },
  DashAttackHitenNoTsuruSlash_1_anomBuildup: {
    sheet: 'Harumasa',
    name: 'DashAttackHitenNoTsuruSlash_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackHitenNoTsuruSlash_1_anomBuildup',
    },
  },
  DashAttackHitenNoTsuruSlash_2_dmg: {
    sheet: 'Harumasa',
    name: 'DashAttackHitenNoTsuruSlash_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackHitenNoTsuruSlash_2_dmg',
    },
  },
  DashAttackHitenNoTsuruSlash_2_daze: {
    sheet: 'Harumasa',
    name: 'DashAttackHitenNoTsuruSlash_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackHitenNoTsuruSlash_2_daze',
    },
  },
  DashAttackHitenNoTsuruSlash_2_anomBuildup: {
    sheet: 'Harumasa',
    name: 'DashAttackHitenNoTsuruSlash_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackHitenNoTsuruSlash_2_anomBuildup',
    },
  },
  SpecialAttackNowhereToHide_0_dmg: {
    sheet: 'Harumasa',
    name: 'SpecialAttackNowhereToHide_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackNowhereToHide_0_dmg',
    },
  },
  SpecialAttackNowhereToHide_0_daze: {
    sheet: 'Harumasa',
    name: 'SpecialAttackNowhereToHide_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackNowhereToHide_0_daze',
    },
  },
  SpecialAttackNowhereToHide_0_anomBuildup: {
    sheet: 'Harumasa',
    name: 'SpecialAttackNowhereToHide_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackNowhereToHide_0_anomBuildup',
    },
  },
  EXSpecialAttackNowhereToRun_0_dmg: {
    sheet: 'Harumasa',
    name: 'EXSpecialAttackNowhereToRun_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackNowhereToRun_0_dmg',
    },
  },
  EXSpecialAttackNowhereToRun_0_daze: {
    sheet: 'Harumasa',
    name: 'EXSpecialAttackNowhereToRun_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackNowhereToRun_0_daze',
    },
  },
  EXSpecialAttackNowhereToRun_0_anomBuildup: {
    sheet: 'Harumasa',
    name: 'EXSpecialAttackNowhereToRun_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackNowhereToRun_0_anomBuildup',
    },
  },
  ChainAttackKaiHanare_0_dmg: {
    sheet: 'Harumasa',
    name: 'ChainAttackKaiHanare_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackKaiHanare_0_dmg',
    },
  },
  ChainAttackKaiHanare_0_daze: {
    sheet: 'Harumasa',
    name: 'ChainAttackKaiHanare_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackKaiHanare_0_daze',
    },
  },
  ChainAttackKaiHanare_0_anomBuildup: {
    sheet: 'Harumasa',
    name: 'ChainAttackKaiHanare_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackKaiHanare_0_anomBuildup',
    },
  },
  UltimateZanshin_0_dmg: {
    sheet: 'Harumasa',
    name: 'UltimateZanshin_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateZanshin_0_dmg',
    },
  },
  UltimateZanshin_0_daze: {
    sheet: 'Harumasa',
    name: 'UltimateZanshin_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateZanshin_0_daze',
    },
  },
  UltimateZanshin_0_anomBuildup: {
    sheet: 'Harumasa',
    name: 'UltimateZanshin_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateZanshin_0_anomBuildup',
    },
  },
  QuickAssistBracedBow_0_dmg: {
    sheet: 'Harumasa',
    name: 'QuickAssistBracedBow_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistBracedBow_0_dmg',
    },
  },
  QuickAssistBracedBow_0_daze: {
    sheet: 'Harumasa',
    name: 'QuickAssistBracedBow_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistBracedBow_0_daze',
    },
  },
  QuickAssistBracedBow_0_anomBuildup: {
    sheet: 'Harumasa',
    name: 'QuickAssistBracedBow_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistBracedBow_0_anomBuildup',
    },
  },
  DefensiveAssistYugamae_0_dmg: {
    sheet: 'Harumasa',
    name: 'DefensiveAssistYugamae_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistYugamae_0_dmg',
    },
  },
  DefensiveAssistYugamae_0_daze: {
    sheet: 'Harumasa',
    name: 'DefensiveAssistYugamae_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistYugamae_0_daze',
    },
  },
  DefensiveAssistYugamae_0_anomBuildup: {
    sheet: 'Harumasa',
    name: 'DefensiveAssistYugamae_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistYugamae_0_anomBuildup',
    },
  },
  DefensiveAssistYugamae_1_dmg: {
    sheet: 'Harumasa',
    name: 'DefensiveAssistYugamae_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistYugamae_1_dmg',
    },
  },
  DefensiveAssistYugamae_1_daze: {
    sheet: 'Harumasa',
    name: 'DefensiveAssistYugamae_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistYugamae_1_daze',
    },
  },
  DefensiveAssistYugamae_1_anomBuildup: {
    sheet: 'Harumasa',
    name: 'DefensiveAssistYugamae_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistYugamae_1_anomBuildup',
    },
  },
  DefensiveAssistYugamae_2_dmg: {
    sheet: 'Harumasa',
    name: 'DefensiveAssistYugamae_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistYugamae_2_dmg',
    },
  },
  DefensiveAssistYugamae_2_daze: {
    sheet: 'Harumasa',
    name: 'DefensiveAssistYugamae_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistYugamae_2_daze',
    },
  },
  DefensiveAssistYugamae_2_anomBuildup: {
    sheet: 'Harumasa',
    name: 'DefensiveAssistYugamae_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistYugamae_2_anomBuildup',
    },
  },
  AssistFollowUpYugamaeSlash_0_dmg: {
    sheet: 'Harumasa',
    name: 'AssistFollowUpYugamaeSlash_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpYugamaeSlash_0_dmg',
    },
  },
  AssistFollowUpYugamaeSlash_0_daze: {
    sheet: 'Harumasa',
    name: 'AssistFollowUpYugamaeSlash_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpYugamaeSlash_0_daze',
    },
  },
  AssistFollowUpYugamaeSlash_0_anomBuildup: {
    sheet: 'Harumasa',
    name: 'AssistFollowUpYugamaeSlash_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpYugamaeSlash_0_anomBuildup',
    },
  },
  m6_dmg: {
    sheet: 'Harumasa',
    name: 'm6_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'elemental',
      name: 'm6_dmg',
    },
  },
} as const
