// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Harumasa',
    name: 'standardDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Harumasa',
      attribute: 'electric',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Harumasa',
    name: 'anomalyDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_electric: {
    sheet: 'Harumasa',
    name: 'disorderDmgInst_electric',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'disorder',
      name: 'disorderDmgInst_electric',
    },
  },
  vortexDmgInst_electric: {
    sheet: 'Harumasa',
    name: 'vortexDmgInst_electric',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'vortex',
      name: 'vortexDmgInst_electric',
    },
  },
  abloomDmgInst: {
    sheet: 'Harumasa',
    name: 'abloomDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Harumasa',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Harumasa',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      name: 'dazeInst',
    },
  },
  'BasicAttackCloudPiercer_0:standardDmg': {
    sheet: 'Harumasa',
    name: 'BasicAttackCloudPiercer_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Harumasa',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackCloudPiercer_0',
    },
  },
  'BasicAttackCloudPiercer_0:dazeBuildup': {
    sheet: 'Harumasa',
    name: 'BasicAttackCloudPiercer_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Harumasa',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackCloudPiercer_0',
    },
  },
  'BasicAttackCloudPiercer_0:anomBuildup': {
    sheet: 'Harumasa',
    name: 'BasicAttackCloudPiercer_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Harumasa',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackCloudPiercer_0',
    },
  },
  'BasicAttackCloudPiercer_1:standardDmg': {
    sheet: 'Harumasa',
    name: 'BasicAttackCloudPiercer_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Harumasa',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackCloudPiercer_1',
    },
  },
  'BasicAttackCloudPiercer_1:dazeBuildup': {
    sheet: 'Harumasa',
    name: 'BasicAttackCloudPiercer_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Harumasa',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackCloudPiercer_1',
    },
  },
  'BasicAttackCloudPiercer_1:anomBuildup': {
    sheet: 'Harumasa',
    name: 'BasicAttackCloudPiercer_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Harumasa',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackCloudPiercer_1',
    },
  },
  'BasicAttackCloudPiercer_2:standardDmg': {
    sheet: 'Harumasa',
    name: 'BasicAttackCloudPiercer_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Harumasa',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackCloudPiercer_2',
    },
  },
  'BasicAttackCloudPiercer_2:dazeBuildup': {
    sheet: 'Harumasa',
    name: 'BasicAttackCloudPiercer_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Harumasa',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackCloudPiercer_2',
    },
  },
  'BasicAttackCloudPiercer_2:anomBuildup': {
    sheet: 'Harumasa',
    name: 'BasicAttackCloudPiercer_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Harumasa',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackCloudPiercer_2',
    },
  },
  'BasicAttackCloudPiercer_3:standardDmg': {
    sheet: 'Harumasa',
    name: 'BasicAttackCloudPiercer_3:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackCloudPiercer_3',
    },
  },
  'BasicAttackCloudPiercer_3:dazeBuildup': {
    sheet: 'Harumasa',
    name: 'BasicAttackCloudPiercer_3:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackCloudPiercer_3',
    },
  },
  'BasicAttackCloudPiercer_3:anomBuildup': {
    sheet: 'Harumasa',
    name: 'BasicAttackCloudPiercer_3:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackCloudPiercer_3',
    },
  },
  'BasicAttackCloudPiercer_4:standardDmg': {
    sheet: 'Harumasa',
    name: 'BasicAttackCloudPiercer_4:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackCloudPiercer_4',
    },
  },
  'BasicAttackCloudPiercer_4:dazeBuildup': {
    sheet: 'Harumasa',
    name: 'BasicAttackCloudPiercer_4:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackCloudPiercer_4',
    },
  },
  'BasicAttackCloudPiercer_4:anomBuildup': {
    sheet: 'Harumasa',
    name: 'BasicAttackCloudPiercer_4:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackCloudPiercer_4',
    },
  },
  'BasicAttackCloudPiercerDrift_0:standardDmg': {
    sheet: 'Harumasa',
    name: 'BasicAttackCloudPiercerDrift_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Harumasa',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackCloudPiercerDrift_0',
    },
  },
  'BasicAttackCloudPiercerDrift_0:dazeBuildup': {
    sheet: 'Harumasa',
    name: 'BasicAttackCloudPiercerDrift_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Harumasa',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackCloudPiercerDrift_0',
    },
  },
  'BasicAttackCloudPiercerDrift_0:anomBuildup': {
    sheet: 'Harumasa',
    name: 'BasicAttackCloudPiercerDrift_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Harumasa',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackCloudPiercerDrift_0',
    },
  },
  'BasicAttackFallingFeather_0:standardDmg': {
    sheet: 'Harumasa',
    name: 'BasicAttackFallingFeather_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFallingFeather_0',
    },
  },
  'BasicAttackFallingFeather_0:dazeBuildup': {
    sheet: 'Harumasa',
    name: 'BasicAttackFallingFeather_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFallingFeather_0',
    },
  },
  'BasicAttackFallingFeather_0:anomBuildup': {
    sheet: 'Harumasa',
    name: 'BasicAttackFallingFeather_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFallingFeather_0',
    },
  },
  'BasicAttackHaOtoNoYa_0:standardDmg': {
    sheet: 'Harumasa',
    name: 'BasicAttackHaOtoNoYa_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackHaOtoNoYa_0',
    },
  },
  'BasicAttackHaOtoNoYa_0:dazeBuildup': {
    sheet: 'Harumasa',
    name: 'BasicAttackHaOtoNoYa_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackHaOtoNoYa_0',
    },
  },
  'BasicAttackHaOtoNoYa_0:anomBuildup': {
    sheet: 'Harumasa',
    name: 'BasicAttackHaOtoNoYa_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackHaOtoNoYa_0',
    },
  },
  'DashAttackHitenNoTsuru_0:standardDmg': {
    sheet: 'Harumasa',
    name: 'DashAttackHitenNoTsuru_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Harumasa',
      damageType1: 'dash',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttackHitenNoTsuru_0',
    },
  },
  'DashAttackHitenNoTsuru_0:dazeBuildup': {
    sheet: 'Harumasa',
    name: 'DashAttackHitenNoTsuru_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Harumasa',
      damageType1: 'dash',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttackHitenNoTsuru_0',
    },
  },
  'DashAttackHitenNoTsuru_0:anomBuildup': {
    sheet: 'Harumasa',
    name: 'DashAttackHitenNoTsuru_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Harumasa',
      damageType1: 'dash',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttackHitenNoTsuru_0',
    },
  },
  'DodgeCounterHiddenEdge_0:standardDmg': {
    sheet: 'Harumasa',
    name: 'DodgeCounterHiddenEdge_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterHiddenEdge_0',
    },
  },
  'DodgeCounterHiddenEdge_0:dazeBuildup': {
    sheet: 'Harumasa',
    name: 'DodgeCounterHiddenEdge_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterHiddenEdge_0',
    },
  },
  'DodgeCounterHiddenEdge_0:anomBuildup': {
    sheet: 'Harumasa',
    name: 'DodgeCounterHiddenEdge_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterHiddenEdge_0',
    },
  },
  'DashAttackHitenNoTsuruSlash_0:standardDmg': {
    sheet: 'Harumasa',
    name: 'DashAttackHitenNoTsuruSlash_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackHitenNoTsuruSlash_0',
    },
  },
  'DashAttackHitenNoTsuruSlash_0:dazeBuildup': {
    sheet: 'Harumasa',
    name: 'DashAttackHitenNoTsuruSlash_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackHitenNoTsuruSlash_0',
    },
  },
  'DashAttackHitenNoTsuruSlash_0:anomBuildup': {
    sheet: 'Harumasa',
    name: 'DashAttackHitenNoTsuruSlash_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackHitenNoTsuruSlash_0',
    },
  },
  'DashAttackHitenNoTsuruSlash_1:standardDmg': {
    sheet: 'Harumasa',
    name: 'DashAttackHitenNoTsuruSlash_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackHitenNoTsuruSlash_1',
    },
  },
  'DashAttackHitenNoTsuruSlash_1:dazeBuildup': {
    sheet: 'Harumasa',
    name: 'DashAttackHitenNoTsuruSlash_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackHitenNoTsuruSlash_1',
    },
  },
  'DashAttackHitenNoTsuruSlash_1:anomBuildup': {
    sheet: 'Harumasa',
    name: 'DashAttackHitenNoTsuruSlash_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackHitenNoTsuruSlash_1',
    },
  },
  'DashAttackHitenNoTsuruSlash_2:standardDmg': {
    sheet: 'Harumasa',
    name: 'DashAttackHitenNoTsuruSlash_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackHitenNoTsuruSlash_2',
    },
  },
  'DashAttackHitenNoTsuruSlash_2:dazeBuildup': {
    sheet: 'Harumasa',
    name: 'DashAttackHitenNoTsuruSlash_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackHitenNoTsuruSlash_2',
    },
  },
  'DashAttackHitenNoTsuruSlash_2:anomBuildup': {
    sheet: 'Harumasa',
    name: 'DashAttackHitenNoTsuruSlash_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackHitenNoTsuruSlash_2',
    },
  },
  'ChasingThunder_0:standardDmg': {
    sheet: 'Harumasa',
    name: 'ChasingThunder_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'ChasingThunder_0',
    },
  },
  'ChasingThunder_0:dazeBuildup': {
    sheet: 'Harumasa',
    name: 'ChasingThunder_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'ChasingThunder_0',
    },
  },
  'ChasingThunder_0:anomBuildup': {
    sheet: 'Harumasa',
    name: 'ChasingThunder_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'ChasingThunder_0',
    },
  },
  'SpecialAttackNowhereToHide_0:standardDmg': {
    sheet: 'Harumasa',
    name: 'SpecialAttackNowhereToHide_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackNowhereToHide_0',
    },
  },
  'SpecialAttackNowhereToHide_0:dazeBuildup': {
    sheet: 'Harumasa',
    name: 'SpecialAttackNowhereToHide_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackNowhereToHide_0',
    },
  },
  'SpecialAttackNowhereToHide_0:anomBuildup': {
    sheet: 'Harumasa',
    name: 'SpecialAttackNowhereToHide_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackNowhereToHide_0',
    },
  },
  'EXSpecialAttackNowhereToRun_0:standardDmg': {
    sheet: 'Harumasa',
    name: 'EXSpecialAttackNowhereToRun_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackNowhereToRun_0',
    },
  },
  'EXSpecialAttackNowhereToRun_0:dazeBuildup': {
    sheet: 'Harumasa',
    name: 'EXSpecialAttackNowhereToRun_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackNowhereToRun_0',
    },
  },
  'EXSpecialAttackNowhereToRun_0:anomBuildup': {
    sheet: 'Harumasa',
    name: 'EXSpecialAttackNowhereToRun_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackNowhereToRun_0',
    },
  },
  'EXSpecialAttackNowhereToRunPatrol_0:standardDmg': {
    sheet: 'Harumasa',
    name: 'EXSpecialAttackNowhereToRunPatrol_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackNowhereToRunPatrol_0',
    },
  },
  'EXSpecialAttackNowhereToRunPatrol_0:dazeBuildup': {
    sheet: 'Harumasa',
    name: 'EXSpecialAttackNowhereToRunPatrol_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackNowhereToRunPatrol_0',
    },
  },
  'EXSpecialAttackNowhereToRunPatrol_0:anomBuildup': {
    sheet: 'Harumasa',
    name: 'EXSpecialAttackNowhereToRunPatrol_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackNowhereToRunPatrol_0',
    },
  },
  'ChainAttackKaiHanare_0:standardDmg': {
    sheet: 'Harumasa',
    name: 'ChainAttackKaiHanare_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackKaiHanare_0',
    },
  },
  'ChainAttackKaiHanare_0:dazeBuildup': {
    sheet: 'Harumasa',
    name: 'ChainAttackKaiHanare_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackKaiHanare_0',
    },
  },
  'ChainAttackKaiHanare_0:anomBuildup': {
    sheet: 'Harumasa',
    name: 'ChainAttackKaiHanare_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackKaiHanare_0',
    },
  },
  'UltimateZanshin_0:standardDmg': {
    sheet: 'Harumasa',
    name: 'UltimateZanshin_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateZanshin_0',
    },
  },
  'UltimateZanshin_0:dazeBuildup': {
    sheet: 'Harumasa',
    name: 'UltimateZanshin_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateZanshin_0',
    },
  },
  'UltimateZanshin_0:anomBuildup': {
    sheet: 'Harumasa',
    name: 'UltimateZanshin_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateZanshin_0',
    },
  },
  'ZanshinScatteredBlossoms_0:standardDmg': {
    sheet: 'Harumasa',
    name: 'ZanshinScatteredBlossoms_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'ZanshinScatteredBlossoms_0',
    },
  },
  'ZanshinScatteredBlossoms_0:dazeBuildup': {
    sheet: 'Harumasa',
    name: 'ZanshinScatteredBlossoms_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'ZanshinScatteredBlossoms_0',
    },
  },
  'ZanshinScatteredBlossoms_0:anomBuildup': {
    sheet: 'Harumasa',
    name: 'ZanshinScatteredBlossoms_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'ZanshinScatteredBlossoms_0',
    },
  },
  'QuickAssistBracedBow_0:standardDmg': {
    sheet: 'Harumasa',
    name: 'QuickAssistBracedBow_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistBracedBow_0',
    },
  },
  'QuickAssistBracedBow_0:dazeBuildup': {
    sheet: 'Harumasa',
    name: 'QuickAssistBracedBow_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistBracedBow_0',
    },
  },
  'QuickAssistBracedBow_0:anomBuildup': {
    sheet: 'Harumasa',
    name: 'QuickAssistBracedBow_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistBracedBow_0',
    },
  },
  'DefensiveAssistYugamae_0:standardDmg': {
    sheet: 'Harumasa',
    name: 'DefensiveAssistYugamae_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistYugamae_0',
    },
  },
  'DefensiveAssistYugamae_0:dazeBuildup': {
    sheet: 'Harumasa',
    name: 'DefensiveAssistYugamae_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistYugamae_0',
    },
  },
  'DefensiveAssistYugamae_0:anomBuildup': {
    sheet: 'Harumasa',
    name: 'DefensiveAssistYugamae_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistYugamae_0',
    },
  },
  'DefensiveAssistYugamae_1:standardDmg': {
    sheet: 'Harumasa',
    name: 'DefensiveAssistYugamae_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistYugamae_1',
    },
  },
  'DefensiveAssistYugamae_1:dazeBuildup': {
    sheet: 'Harumasa',
    name: 'DefensiveAssistYugamae_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistYugamae_1',
    },
  },
  'DefensiveAssistYugamae_1:anomBuildup': {
    sheet: 'Harumasa',
    name: 'DefensiveAssistYugamae_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistYugamae_1',
    },
  },
  'DefensiveAssistYugamae_2:standardDmg': {
    sheet: 'Harumasa',
    name: 'DefensiveAssistYugamae_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistYugamae_2',
    },
  },
  'DefensiveAssistYugamae_2:dazeBuildup': {
    sheet: 'Harumasa',
    name: 'DefensiveAssistYugamae_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistYugamae_2',
    },
  },
  'DefensiveAssistYugamae_2:anomBuildup': {
    sheet: 'Harumasa',
    name: 'DefensiveAssistYugamae_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistYugamae_2',
    },
  },
  'AssistFollowUpYugamaeSlash_0:standardDmg': {
    sheet: 'Harumasa',
    name: 'AssistFollowUpYugamaeSlash_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpYugamaeSlash_0',
    },
  },
  'AssistFollowUpYugamaeSlash_0:dazeBuildup': {
    sheet: 'Harumasa',
    name: 'AssistFollowUpYugamaeSlash_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpYugamaeSlash_0',
    },
  },
  'AssistFollowUpYugamaeSlash_0:anomBuildup': {
    sheet: 'Harumasa',
    name: 'AssistFollowUpYugamaeSlash_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpYugamaeSlash_0',
    },
  },
  m6_dmg: {
    sheet: 'Harumasa',
    name: 'm6_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Harumasa',
      attribute: 'electric',
      damageType1: 'elemental',
      name: 'm6_dmg',
    },
  },
} as const
