// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Soukaku',
    name: 'standardDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soukaku',
      attribute: 'ice',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Soukaku',
    name: 'anomalyDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_ice: {
    sheet: 'Soukaku',
    name: 'disorderDmgInst_ice',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'disorder',
      name: 'disorderDmgInst_ice',
    },
  },
  vortexDmgInst_ice: {
    sheet: 'Soukaku',
    name: 'vortexDmgInst_ice',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'vortex',
      name: 'vortexDmgInst_ice',
    },
  },
  abloomDmgInst: {
    sheet: 'Soukaku',
    name: 'abloomDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Soukaku',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Soukaku',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      name: 'dazeInst',
    },
  },
  'BasicAttackMakingRiceCakes_0:standardDmg': {
    sheet: 'Soukaku',
    name: 'BasicAttackMakingRiceCakes_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soukaku',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackMakingRiceCakes_0',
    },
  },
  'BasicAttackMakingRiceCakes_0:dazeBuildup': {
    sheet: 'Soukaku',
    name: 'BasicAttackMakingRiceCakes_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soukaku',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackMakingRiceCakes_0',
    },
  },
  'BasicAttackMakingRiceCakes_0:anomBuildup': {
    sheet: 'Soukaku',
    name: 'BasicAttackMakingRiceCakes_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soukaku',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackMakingRiceCakes_0',
    },
  },
  'BasicAttackMakingRiceCakes_1:standardDmg': {
    sheet: 'Soukaku',
    name: 'BasicAttackMakingRiceCakes_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soukaku',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackMakingRiceCakes_1',
    },
  },
  'BasicAttackMakingRiceCakes_1:dazeBuildup': {
    sheet: 'Soukaku',
    name: 'BasicAttackMakingRiceCakes_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soukaku',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackMakingRiceCakes_1',
    },
  },
  'BasicAttackMakingRiceCakes_1:anomBuildup': {
    sheet: 'Soukaku',
    name: 'BasicAttackMakingRiceCakes_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soukaku',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackMakingRiceCakes_1',
    },
  },
  'BasicAttackMakingRiceCakes_2:standardDmg': {
    sheet: 'Soukaku',
    name: 'BasicAttackMakingRiceCakes_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soukaku',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackMakingRiceCakes_2',
    },
  },
  'BasicAttackMakingRiceCakes_2:dazeBuildup': {
    sheet: 'Soukaku',
    name: 'BasicAttackMakingRiceCakes_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soukaku',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackMakingRiceCakes_2',
    },
  },
  'BasicAttackMakingRiceCakes_2:anomBuildup': {
    sheet: 'Soukaku',
    name: 'BasicAttackMakingRiceCakes_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soukaku',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackMakingRiceCakes_2',
    },
  },
  'BasicAttackMakingRiceCakesFrostedBanner_0:standardDmg': {
    sheet: 'Soukaku',
    name: 'BasicAttackMakingRiceCakesFrostedBanner_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackMakingRiceCakesFrostedBanner_0',
    },
  },
  'BasicAttackMakingRiceCakesFrostedBanner_0:dazeBuildup': {
    sheet: 'Soukaku',
    name: 'BasicAttackMakingRiceCakesFrostedBanner_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackMakingRiceCakesFrostedBanner_0',
    },
  },
  'BasicAttackMakingRiceCakesFrostedBanner_0:anomBuildup': {
    sheet: 'Soukaku',
    name: 'BasicAttackMakingRiceCakesFrostedBanner_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackMakingRiceCakesFrostedBanner_0',
    },
  },
  'BasicAttackMakingRiceCakesFrostedBanner_1:standardDmg': {
    sheet: 'Soukaku',
    name: 'BasicAttackMakingRiceCakesFrostedBanner_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackMakingRiceCakesFrostedBanner_1',
    },
  },
  'BasicAttackMakingRiceCakesFrostedBanner_1:dazeBuildup': {
    sheet: 'Soukaku',
    name: 'BasicAttackMakingRiceCakesFrostedBanner_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackMakingRiceCakesFrostedBanner_1',
    },
  },
  'BasicAttackMakingRiceCakesFrostedBanner_1:anomBuildup': {
    sheet: 'Soukaku',
    name: 'BasicAttackMakingRiceCakesFrostedBanner_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackMakingRiceCakesFrostedBanner_1',
    },
  },
  'BasicAttackMakingRiceCakesFrostedBanner_2:standardDmg': {
    sheet: 'Soukaku',
    name: 'BasicAttackMakingRiceCakesFrostedBanner_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackMakingRiceCakesFrostedBanner_2',
    },
  },
  'BasicAttackMakingRiceCakesFrostedBanner_2:dazeBuildup': {
    sheet: 'Soukaku',
    name: 'BasicAttackMakingRiceCakesFrostedBanner_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackMakingRiceCakesFrostedBanner_2',
    },
  },
  'BasicAttackMakingRiceCakesFrostedBanner_2:anomBuildup': {
    sheet: 'Soukaku',
    name: 'BasicAttackMakingRiceCakesFrostedBanner_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackMakingRiceCakesFrostedBanner_2',
    },
  },
  'DashAttack5050_0:standardDmg': {
    sheet: 'Soukaku',
    name: 'DashAttack5050_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soukaku',
      damageType1: 'dash',
      attribute: 'physical',
      skillType1: 'dodgeSkill',
      name: 'DashAttack5050_0',
    },
  },
  'DashAttack5050_0:dazeBuildup': {
    sheet: 'Soukaku',
    name: 'DashAttack5050_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soukaku',
      damageType1: 'dash',
      attribute: 'physical',
      skillType1: 'dodgeSkill',
      name: 'DashAttack5050_0',
    },
  },
  'DashAttack5050_0:anomBuildup': {
    sheet: 'Soukaku',
    name: 'DashAttack5050_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soukaku',
      damageType1: 'dash',
      attribute: 'physical',
      skillType1: 'dodgeSkill',
      name: 'DashAttack5050_0',
    },
  },
  'DashAttack5050FrostedBanner_0:standardDmg': {
    sheet: 'Soukaku',
    name: 'DashAttack5050FrostedBanner_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'dash',
      skillType1: 'dodgeSkill',
      name: 'DashAttack5050FrostedBanner_0',
    },
  },
  'DashAttack5050FrostedBanner_0:dazeBuildup': {
    sheet: 'Soukaku',
    name: 'DashAttack5050FrostedBanner_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'dash',
      skillType1: 'dodgeSkill',
      name: 'DashAttack5050FrostedBanner_0',
    },
  },
  'DashAttack5050FrostedBanner_0:anomBuildup': {
    sheet: 'Soukaku',
    name: 'DashAttack5050FrostedBanner_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'dash',
      skillType1: 'dodgeSkill',
      name: 'DashAttack5050FrostedBanner_0',
    },
  },
  'DodgeCounterAwayFromMySnacks_0:standardDmg': {
    sheet: 'Soukaku',
    name: 'DodgeCounterAwayFromMySnacks_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'dodgeCounter',
      skillType1: 'dodgeSkill',
      name: 'DodgeCounterAwayFromMySnacks_0',
    },
  },
  'DodgeCounterAwayFromMySnacks_0:dazeBuildup': {
    sheet: 'Soukaku',
    name: 'DodgeCounterAwayFromMySnacks_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'dodgeCounter',
      skillType1: 'dodgeSkill',
      name: 'DodgeCounterAwayFromMySnacks_0',
    },
  },
  'DodgeCounterAwayFromMySnacks_0:anomBuildup': {
    sheet: 'Soukaku',
    name: 'DodgeCounterAwayFromMySnacks_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'dodgeCounter',
      skillType1: 'dodgeSkill',
      name: 'DodgeCounterAwayFromMySnacks_0',
    },
  },
  'SpecialAttackCoolingBento_0:standardDmg': {
    sheet: 'Soukaku',
    name: 'SpecialAttackCoolingBento_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackCoolingBento_0',
    },
  },
  'SpecialAttackCoolingBento_0:dazeBuildup': {
    sheet: 'Soukaku',
    name: 'SpecialAttackCoolingBento_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackCoolingBento_0',
    },
  },
  'SpecialAttackCoolingBento_0:anomBuildup': {
    sheet: 'Soukaku',
    name: 'SpecialAttackCoolingBento_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackCoolingBento_0',
    },
  },
  'SpecialAttackCoolingBento_1:standardDmg': {
    sheet: 'Soukaku',
    name: 'SpecialAttackCoolingBento_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackCoolingBento_1',
    },
  },
  'SpecialAttackCoolingBento_1:dazeBuildup': {
    sheet: 'Soukaku',
    name: 'SpecialAttackCoolingBento_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackCoolingBento_1',
    },
  },
  'SpecialAttackCoolingBento_1:anomBuildup': {
    sheet: 'Soukaku',
    name: 'SpecialAttackCoolingBento_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackCoolingBento_1',
    },
  },
  'EXSpecialAttackFanningMosquitoes_0:standardDmg': {
    sheet: 'Soukaku',
    name: 'EXSpecialAttackFanningMosquitoes_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackFanningMosquitoes_0',
    },
  },
  'EXSpecialAttackFanningMosquitoes_0:dazeBuildup': {
    sheet: 'Soukaku',
    name: 'EXSpecialAttackFanningMosquitoes_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackFanningMosquitoes_0',
    },
  },
  'EXSpecialAttackFanningMosquitoes_0:anomBuildup': {
    sheet: 'Soukaku',
    name: 'EXSpecialAttackFanningMosquitoes_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackFanningMosquitoes_0',
    },
  },
  'EXSpecialAttackFanningMosquitoes_1:standardDmg': {
    sheet: 'Soukaku',
    name: 'EXSpecialAttackFanningMosquitoes_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackFanningMosquitoes_1',
    },
  },
  'EXSpecialAttackFanningMosquitoes_1:dazeBuildup': {
    sheet: 'Soukaku',
    name: 'EXSpecialAttackFanningMosquitoes_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackFanningMosquitoes_1',
    },
  },
  'EXSpecialAttackFanningMosquitoes_1:anomBuildup': {
    sheet: 'Soukaku',
    name: 'EXSpecialAttackFanningMosquitoes_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackFanningMosquitoes_1',
    },
  },
  'SpecialAttackRally_0:standardDmg': {
    sheet: 'Soukaku',
    name: 'SpecialAttackRally_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackRally_0',
    },
  },
  'SpecialAttackRally_0:dazeBuildup': {
    sheet: 'Soukaku',
    name: 'SpecialAttackRally_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackRally_0',
    },
  },
  'SpecialAttackRally_0:anomBuildup': {
    sheet: 'Soukaku',
    name: 'SpecialAttackRally_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackRally_0',
    },
  },
  'SpecialAttackRally_1:standardDmg': {
    sheet: 'Soukaku',
    name: 'SpecialAttackRally_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackRally_1',
    },
  },
  'SpecialAttackRally_1:dazeBuildup': {
    sheet: 'Soukaku',
    name: 'SpecialAttackRally_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackRally_1',
    },
  },
  'SpecialAttackRally_1:anomBuildup': {
    sheet: 'Soukaku',
    name: 'SpecialAttackRally_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackRally_1',
    },
  },
  'SpecialAttackRally_2:standardDmg': {
    sheet: 'Soukaku',
    name: 'SpecialAttackRally_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackRally_2',
    },
  },
  'SpecialAttackRally_2:dazeBuildup': {
    sheet: 'Soukaku',
    name: 'SpecialAttackRally_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackRally_2',
    },
  },
  'SpecialAttackRally_2:anomBuildup': {
    sheet: 'Soukaku',
    name: 'SpecialAttackRally_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackRally_2',
    },
  },
  'ChainAttackPuddingSlash_0:standardDmg': {
    sheet: 'Soukaku',
    name: 'ChainAttackPuddingSlash_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'chain',
      skillType1: 'chainSkill',
      name: 'ChainAttackPuddingSlash_0',
    },
  },
  'ChainAttackPuddingSlash_0:dazeBuildup': {
    sheet: 'Soukaku',
    name: 'ChainAttackPuddingSlash_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'chain',
      skillType1: 'chainSkill',
      name: 'ChainAttackPuddingSlash_0',
    },
  },
  'ChainAttackPuddingSlash_0:anomBuildup': {
    sheet: 'Soukaku',
    name: 'ChainAttackPuddingSlash_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'chain',
      skillType1: 'chainSkill',
      name: 'ChainAttackPuddingSlash_0',
    },
  },
  'UltimateJumboPuddingSlash_0:standardDmg': {
    sheet: 'Soukaku',
    name: 'UltimateJumboPuddingSlash_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'ult',
      skillType1: 'chainSkill',
      name: 'UltimateJumboPuddingSlash_0',
    },
  },
  'UltimateJumboPuddingSlash_0:dazeBuildup': {
    sheet: 'Soukaku',
    name: 'UltimateJumboPuddingSlash_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'ult',
      skillType1: 'chainSkill',
      name: 'UltimateJumboPuddingSlash_0',
    },
  },
  'UltimateJumboPuddingSlash_0:anomBuildup': {
    sheet: 'Soukaku',
    name: 'UltimateJumboPuddingSlash_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'ult',
      skillType1: 'chainSkill',
      name: 'UltimateJumboPuddingSlash_0',
    },
  },
  'QuickAssistASetForTwo_0:standardDmg': {
    sheet: 'Soukaku',
    name: 'QuickAssistASetForTwo_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'quickAssist',
      skillType1: 'assistSkill',
      name: 'QuickAssistASetForTwo_0',
    },
  },
  'QuickAssistASetForTwo_0:dazeBuildup': {
    sheet: 'Soukaku',
    name: 'QuickAssistASetForTwo_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'quickAssist',
      skillType1: 'assistSkill',
      name: 'QuickAssistASetForTwo_0',
    },
  },
  'QuickAssistASetForTwo_0:anomBuildup': {
    sheet: 'Soukaku',
    name: 'QuickAssistASetForTwo_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'quickAssist',
      skillType1: 'assistSkill',
      name: 'QuickAssistASetForTwo_0',
    },
  },
  'DefensiveAssistGuardingTactics_0:standardDmg': {
    sheet: 'Soukaku',
    name: 'DefensiveAssistGuardingTactics_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistGuardingTactics_0',
    },
  },
  'DefensiveAssistGuardingTactics_0:dazeBuildup': {
    sheet: 'Soukaku',
    name: 'DefensiveAssistGuardingTactics_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistGuardingTactics_0',
    },
  },
  'DefensiveAssistGuardingTactics_0:anomBuildup': {
    sheet: 'Soukaku',
    name: 'DefensiveAssistGuardingTactics_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistGuardingTactics_0',
    },
  },
  'DefensiveAssistGuardingTactics_1:standardDmg': {
    sheet: 'Soukaku',
    name: 'DefensiveAssistGuardingTactics_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistGuardingTactics_1',
    },
  },
  'DefensiveAssistGuardingTactics_1:dazeBuildup': {
    sheet: 'Soukaku',
    name: 'DefensiveAssistGuardingTactics_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistGuardingTactics_1',
    },
  },
  'DefensiveAssistGuardingTactics_1:anomBuildup': {
    sheet: 'Soukaku',
    name: 'DefensiveAssistGuardingTactics_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistGuardingTactics_1',
    },
  },
  'DefensiveAssistGuardingTactics_2:standardDmg': {
    sheet: 'Soukaku',
    name: 'DefensiveAssistGuardingTactics_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistGuardingTactics_2',
    },
  },
  'DefensiveAssistGuardingTactics_2:dazeBuildup': {
    sheet: 'Soukaku',
    name: 'DefensiveAssistGuardingTactics_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistGuardingTactics_2',
    },
  },
  'DefensiveAssistGuardingTactics_2:anomBuildup': {
    sheet: 'Soukaku',
    name: 'DefensiveAssistGuardingTactics_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistGuardingTactics_2',
    },
  },
  'AssistFollowUpSweepingStrike_0:standardDmg': {
    sheet: 'Soukaku',
    name: 'AssistFollowUpSweepingStrike_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'assistFollowUp',
      skillType1: 'assistSkill',
      name: 'AssistFollowUpSweepingStrike_0',
    },
  },
  'AssistFollowUpSweepingStrike_0:dazeBuildup': {
    sheet: 'Soukaku',
    name: 'AssistFollowUpSweepingStrike_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'assistFollowUp',
      skillType1: 'assistSkill',
      name: 'AssistFollowUpSweepingStrike_0',
    },
  },
  'AssistFollowUpSweepingStrike_0:anomBuildup': {
    sheet: 'Soukaku',
    name: 'AssistFollowUpSweepingStrike_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'assistFollowUp',
      skillType1: 'assistSkill',
      name: 'AssistFollowUpSweepingStrike_0',
    },
  },
} as const
