// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Soukaku',
    name: 'standardDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soukaku',
      attribute: 'ice',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Soukaku',
    name: 'anomalyDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_ice: {
    sheet: 'Soukaku',
    name: 'disorderDmgInst_ice',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'disorder',
      name: 'disorderDmgInst_ice',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Soukaku',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Soukaku',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      name: 'dazeInst',
    },
  },
  BasicAttackMakingRiceCakes_0_dmg: {
    sheet: 'Soukaku',
    name: 'BasicAttackMakingRiceCakes_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soukaku',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackMakingRiceCakes_0_dmg',
    },
  },
  BasicAttackMakingRiceCakes_0_daze: {
    sheet: 'Soukaku',
    name: 'BasicAttackMakingRiceCakes_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soukaku',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackMakingRiceCakes_0_daze',
    },
  },
  BasicAttackMakingRiceCakes_0_anomBuildup: {
    sheet: 'Soukaku',
    name: 'BasicAttackMakingRiceCakes_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soukaku',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackMakingRiceCakes_0_anomBuildup',
    },
  },
  BasicAttackMakingRiceCakes_1_dmg: {
    sheet: 'Soukaku',
    name: 'BasicAttackMakingRiceCakes_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soukaku',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackMakingRiceCakes_1_dmg',
    },
  },
  BasicAttackMakingRiceCakes_1_daze: {
    sheet: 'Soukaku',
    name: 'BasicAttackMakingRiceCakes_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soukaku',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackMakingRiceCakes_1_daze',
    },
  },
  BasicAttackMakingRiceCakes_1_anomBuildup: {
    sheet: 'Soukaku',
    name: 'BasicAttackMakingRiceCakes_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soukaku',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackMakingRiceCakes_1_anomBuildup',
    },
  },
  BasicAttackMakingRiceCakes_2_dmg: {
    sheet: 'Soukaku',
    name: 'BasicAttackMakingRiceCakes_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soukaku',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackMakingRiceCakes_2_dmg',
    },
  },
  BasicAttackMakingRiceCakes_2_daze: {
    sheet: 'Soukaku',
    name: 'BasicAttackMakingRiceCakes_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soukaku',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackMakingRiceCakes_2_daze',
    },
  },
  BasicAttackMakingRiceCakes_2_anomBuildup: {
    sheet: 'Soukaku',
    name: 'BasicAttackMakingRiceCakes_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soukaku',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackMakingRiceCakes_2_anomBuildup',
    },
  },
  BasicAttackMakingRiceCakesFrostedBanner_0_dmg: {
    sheet: 'Soukaku',
    name: 'BasicAttackMakingRiceCakesFrostedBanner_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackMakingRiceCakesFrostedBanner_0_dmg',
    },
  },
  BasicAttackMakingRiceCakesFrostedBanner_0_daze: {
    sheet: 'Soukaku',
    name: 'BasicAttackMakingRiceCakesFrostedBanner_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackMakingRiceCakesFrostedBanner_0_daze',
    },
  },
  BasicAttackMakingRiceCakesFrostedBanner_0_anomBuildup: {
    sheet: 'Soukaku',
    name: 'BasicAttackMakingRiceCakesFrostedBanner_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackMakingRiceCakesFrostedBanner_0_anomBuildup',
    },
  },
  BasicAttackMakingRiceCakesFrostedBanner_1_dmg: {
    sheet: 'Soukaku',
    name: 'BasicAttackMakingRiceCakesFrostedBanner_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackMakingRiceCakesFrostedBanner_1_dmg',
    },
  },
  BasicAttackMakingRiceCakesFrostedBanner_1_daze: {
    sheet: 'Soukaku',
    name: 'BasicAttackMakingRiceCakesFrostedBanner_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackMakingRiceCakesFrostedBanner_1_daze',
    },
  },
  BasicAttackMakingRiceCakesFrostedBanner_1_anomBuildup: {
    sheet: 'Soukaku',
    name: 'BasicAttackMakingRiceCakesFrostedBanner_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackMakingRiceCakesFrostedBanner_1_anomBuildup',
    },
  },
  BasicAttackMakingRiceCakesFrostedBanner_2_dmg: {
    sheet: 'Soukaku',
    name: 'BasicAttackMakingRiceCakesFrostedBanner_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackMakingRiceCakesFrostedBanner_2_dmg',
    },
  },
  BasicAttackMakingRiceCakesFrostedBanner_2_daze: {
    sheet: 'Soukaku',
    name: 'BasicAttackMakingRiceCakesFrostedBanner_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackMakingRiceCakesFrostedBanner_2_daze',
    },
  },
  BasicAttackMakingRiceCakesFrostedBanner_2_anomBuildup: {
    sheet: 'Soukaku',
    name: 'BasicAttackMakingRiceCakesFrostedBanner_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackMakingRiceCakesFrostedBanner_2_anomBuildup',
    },
  },
  DashAttack5050_0_dmg: {
    sheet: 'Soukaku',
    name: 'DashAttack5050_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soukaku',
      damageType1: 'dash',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttack5050_0_dmg',
    },
  },
  DashAttack5050_0_daze: {
    sheet: 'Soukaku',
    name: 'DashAttack5050_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soukaku',
      damageType1: 'dash',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttack5050_0_daze',
    },
  },
  DashAttack5050_0_anomBuildup: {
    sheet: 'Soukaku',
    name: 'DashAttack5050_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soukaku',
      damageType1: 'dash',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttack5050_0_anomBuildup',
    },
  },
  DashAttack5050FrostedBanner_0_dmg: {
    sheet: 'Soukaku',
    name: 'DashAttack5050FrostedBanner_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttack5050FrostedBanner_0_dmg',
    },
  },
  DashAttack5050FrostedBanner_0_daze: {
    sheet: 'Soukaku',
    name: 'DashAttack5050FrostedBanner_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttack5050FrostedBanner_0_daze',
    },
  },
  DashAttack5050FrostedBanner_0_anomBuildup: {
    sheet: 'Soukaku',
    name: 'DashAttack5050FrostedBanner_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttack5050FrostedBanner_0_anomBuildup',
    },
  },
  DodgeCounterAwayFromMySnacks_0_dmg: {
    sheet: 'Soukaku',
    name: 'DodgeCounterAwayFromMySnacks_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterAwayFromMySnacks_0_dmg',
    },
  },
  DodgeCounterAwayFromMySnacks_0_daze: {
    sheet: 'Soukaku',
    name: 'DodgeCounterAwayFromMySnacks_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterAwayFromMySnacks_0_daze',
    },
  },
  DodgeCounterAwayFromMySnacks_0_anomBuildup: {
    sheet: 'Soukaku',
    name: 'DodgeCounterAwayFromMySnacks_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterAwayFromMySnacks_0_anomBuildup',
    },
  },
  SpecialAttackCoolingBento_0_dmg: {
    sheet: 'Soukaku',
    name: 'SpecialAttackCoolingBento_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackCoolingBento_0_dmg',
    },
  },
  SpecialAttackCoolingBento_0_daze: {
    sheet: 'Soukaku',
    name: 'SpecialAttackCoolingBento_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackCoolingBento_0_daze',
    },
  },
  SpecialAttackCoolingBento_0_anomBuildup: {
    sheet: 'Soukaku',
    name: 'SpecialAttackCoolingBento_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackCoolingBento_0_anomBuildup',
    },
  },
  SpecialAttackCoolingBento_1_dmg: {
    sheet: 'Soukaku',
    name: 'SpecialAttackCoolingBento_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackCoolingBento_1_dmg',
    },
  },
  SpecialAttackCoolingBento_1_daze: {
    sheet: 'Soukaku',
    name: 'SpecialAttackCoolingBento_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackCoolingBento_1_daze',
    },
  },
  SpecialAttackCoolingBento_1_anomBuildup: {
    sheet: 'Soukaku',
    name: 'SpecialAttackCoolingBento_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackCoolingBento_1_anomBuildup',
    },
  },
  EXSpecialAttackFanningMosquitoes_0_dmg: {
    sheet: 'Soukaku',
    name: 'EXSpecialAttackFanningMosquitoes_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackFanningMosquitoes_0_dmg',
    },
  },
  EXSpecialAttackFanningMosquitoes_0_daze: {
    sheet: 'Soukaku',
    name: 'EXSpecialAttackFanningMosquitoes_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackFanningMosquitoes_0_daze',
    },
  },
  EXSpecialAttackFanningMosquitoes_0_anomBuildup: {
    sheet: 'Soukaku',
    name: 'EXSpecialAttackFanningMosquitoes_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackFanningMosquitoes_0_anomBuildup',
    },
  },
  EXSpecialAttackFanningMosquitoes_1_dmg: {
    sheet: 'Soukaku',
    name: 'EXSpecialAttackFanningMosquitoes_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackFanningMosquitoes_1_dmg',
    },
  },
  EXSpecialAttackFanningMosquitoes_1_daze: {
    sheet: 'Soukaku',
    name: 'EXSpecialAttackFanningMosquitoes_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackFanningMosquitoes_1_daze',
    },
  },
  EXSpecialAttackFanningMosquitoes_1_anomBuildup: {
    sheet: 'Soukaku',
    name: 'EXSpecialAttackFanningMosquitoes_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackFanningMosquitoes_1_anomBuildup',
    },
  },
  SpecialAttackRally_0_dmg: {
    sheet: 'Soukaku',
    name: 'SpecialAttackRally_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackRally_0_dmg',
    },
  },
  SpecialAttackRally_0_daze: {
    sheet: 'Soukaku',
    name: 'SpecialAttackRally_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackRally_0_daze',
    },
  },
  SpecialAttackRally_0_anomBuildup: {
    sheet: 'Soukaku',
    name: 'SpecialAttackRally_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackRally_0_anomBuildup',
    },
  },
  SpecialAttackRally_1_dmg: {
    sheet: 'Soukaku',
    name: 'SpecialAttackRally_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackRally_1_dmg',
    },
  },
  SpecialAttackRally_1_daze: {
    sheet: 'Soukaku',
    name: 'SpecialAttackRally_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackRally_1_daze',
    },
  },
  SpecialAttackRally_1_anomBuildup: {
    sheet: 'Soukaku',
    name: 'SpecialAttackRally_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackRally_1_anomBuildup',
    },
  },
  SpecialAttackRally_2_dmg: {
    sheet: 'Soukaku',
    name: 'SpecialAttackRally_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackRally_2_dmg',
    },
  },
  SpecialAttackRally_2_daze: {
    sheet: 'Soukaku',
    name: 'SpecialAttackRally_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackRally_2_daze',
    },
  },
  SpecialAttackRally_2_anomBuildup: {
    sheet: 'Soukaku',
    name: 'SpecialAttackRally_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackRally_2_anomBuildup',
    },
  },
  ChainAttackPuddingSlash_0_dmg: {
    sheet: 'Soukaku',
    name: 'ChainAttackPuddingSlash_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackPuddingSlash_0_dmg',
    },
  },
  ChainAttackPuddingSlash_0_daze: {
    sheet: 'Soukaku',
    name: 'ChainAttackPuddingSlash_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackPuddingSlash_0_daze',
    },
  },
  ChainAttackPuddingSlash_0_anomBuildup: {
    sheet: 'Soukaku',
    name: 'ChainAttackPuddingSlash_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackPuddingSlash_0_anomBuildup',
    },
  },
  UltimateJumboPuddingSlash_0_dmg: {
    sheet: 'Soukaku',
    name: 'UltimateJumboPuddingSlash_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateJumboPuddingSlash_0_dmg',
    },
  },
  UltimateJumboPuddingSlash_0_daze: {
    sheet: 'Soukaku',
    name: 'UltimateJumboPuddingSlash_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateJumboPuddingSlash_0_daze',
    },
  },
  UltimateJumboPuddingSlash_0_anomBuildup: {
    sheet: 'Soukaku',
    name: 'UltimateJumboPuddingSlash_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateJumboPuddingSlash_0_anomBuildup',
    },
  },
  QuickAssistASetForTwo_0_dmg: {
    sheet: 'Soukaku',
    name: 'QuickAssistASetForTwo_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistASetForTwo_0_dmg',
    },
  },
  QuickAssistASetForTwo_0_daze: {
    sheet: 'Soukaku',
    name: 'QuickAssistASetForTwo_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistASetForTwo_0_daze',
    },
  },
  QuickAssistASetForTwo_0_anomBuildup: {
    sheet: 'Soukaku',
    name: 'QuickAssistASetForTwo_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistASetForTwo_0_anomBuildup',
    },
  },
  DefensiveAssistGuardingTactics_0_dmg: {
    sheet: 'Soukaku',
    name: 'DefensiveAssistGuardingTactics_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistGuardingTactics_0_dmg',
    },
  },
  DefensiveAssistGuardingTactics_0_daze: {
    sheet: 'Soukaku',
    name: 'DefensiveAssistGuardingTactics_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistGuardingTactics_0_daze',
    },
  },
  DefensiveAssistGuardingTactics_0_anomBuildup: {
    sheet: 'Soukaku',
    name: 'DefensiveAssistGuardingTactics_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistGuardingTactics_0_anomBuildup',
    },
  },
  DefensiveAssistGuardingTactics_1_dmg: {
    sheet: 'Soukaku',
    name: 'DefensiveAssistGuardingTactics_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistGuardingTactics_1_dmg',
    },
  },
  DefensiveAssistGuardingTactics_1_daze: {
    sheet: 'Soukaku',
    name: 'DefensiveAssistGuardingTactics_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistGuardingTactics_1_daze',
    },
  },
  DefensiveAssistGuardingTactics_1_anomBuildup: {
    sheet: 'Soukaku',
    name: 'DefensiveAssistGuardingTactics_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistGuardingTactics_1_anomBuildup',
    },
  },
  DefensiveAssistGuardingTactics_2_dmg: {
    sheet: 'Soukaku',
    name: 'DefensiveAssistGuardingTactics_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistGuardingTactics_2_dmg',
    },
  },
  DefensiveAssistGuardingTactics_2_daze: {
    sheet: 'Soukaku',
    name: 'DefensiveAssistGuardingTactics_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistGuardingTactics_2_daze',
    },
  },
  DefensiveAssistGuardingTactics_2_anomBuildup: {
    sheet: 'Soukaku',
    name: 'DefensiveAssistGuardingTactics_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistGuardingTactics_2_anomBuildup',
    },
  },
  AssistFollowUpSweepingStrike_0_dmg: {
    sheet: 'Soukaku',
    name: 'AssistFollowUpSweepingStrike_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpSweepingStrike_0_dmg',
    },
  },
  AssistFollowUpSweepingStrike_0_daze: {
    sheet: 'Soukaku',
    name: 'AssistFollowUpSweepingStrike_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpSweepingStrike_0_daze',
    },
  },
  AssistFollowUpSweepingStrike_0_anomBuildup: {
    sheet: 'Soukaku',
    name: 'AssistFollowUpSweepingStrike_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Soukaku',
      attribute: 'ice',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpSweepingStrike_0_anomBuildup',
    },
  },
} as const
