// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Alice',
    name: 'standardDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'standardDmgBase',
      sheet: 'Alice',
      attribute: 'physical',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Alice',
    name: 'anomalyDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_physical: {
    sheet: 'Alice',
    name: 'disorderDmgInst_physical',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'disorder',
      name: 'disorderDmgInst_physical',
    },
  },
  vortexDmgInst_physical: {
    sheet: 'Alice',
    name: 'vortexDmgInst_physical',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'vortex',
      name: 'vortexDmgInst_physical',
    },
  },
  abloomDmgInst: {
    sheet: 'Alice',
    name: 'abloomDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Alice',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Alice',
      attribute: 'physical',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Alice',
    name: 'dazeInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'dazeBuildupBase',
      sheet: 'Alice',
      attribute: 'physical',
      name: 'dazeInst',
    },
  },
  BasicAttackCelestialOverture_0: {
    sheet: 'Alice',
    name: 'BasicAttackCelestialOverture_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Alice',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackCelestialOverture_0',
    },
  },
  BasicAttackCelestialOverture_1: {
    sheet: 'Alice',
    name: 'BasicAttackCelestialOverture_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Alice',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackCelestialOverture_1',
    },
  },
  BasicAttackCelestialOverture_2: {
    sheet: 'Alice',
    name: 'BasicAttackCelestialOverture_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Alice',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackCelestialOverture_2',
    },
  },
  BasicAttackCelestialOverture_3: {
    sheet: 'Alice',
    name: 'BasicAttackCelestialOverture_3',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Alice',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackCelestialOverture_3',
    },
  },
  BasicAttackCelestialOverture_4: {
    sheet: 'Alice',
    name: 'BasicAttackCelestialOverture_4',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Alice',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackCelestialOverture_4',
    },
  },
  BasicAttackCelestialOverture_5: {
    sheet: 'Alice',
    name: 'BasicAttackCelestialOverture_5',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Alice',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackCelestialOverture_5',
    },
  },
  BasicAttackStarshineWaltz_0: {
    sheet: 'Alice',
    name: 'BasicAttackStarshineWaltz_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackStarshineWaltz_0',
    },
  },
  BasicAttackStarshineWaltz_1: {
    sheet: 'Alice',
    name: 'BasicAttackStarshineWaltz_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackStarshineWaltz_1',
    },
  },
  BasicAttackStarshineWaltz_2: {
    sheet: 'Alice',
    name: 'BasicAttackStarshineWaltz_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackStarshineWaltz_2',
    },
  },
  DashAttackBladeDancersGale_0: {
    sheet: 'Alice',
    name: 'DashAttackBladeDancersGale_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackBladeDancersGale_0',
    },
  },
  DodgeCounterCeremonyOfSwordlight_0: {
    sheet: 'Alice',
    name: 'DodgeCounterCeremonyOfSwordlight_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterCeremonyOfSwordlight_0',
    },
  },
  SpecialAttackPiercingDawn_0: {
    sheet: 'Alice',
    name: 'SpecialAttackPiercingDawn_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackPiercingDawn_0',
    },
  },
  EXSpecialAttackAuroraThrustNorthernCross_0: {
    sheet: 'Alice',
    name: 'EXSpecialAttackAuroraThrustNorthernCross_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackAuroraThrustNorthernCross_0',
    },
  },
  EXSpecialAttackAuroraThrustSouthernCross_0: {
    sheet: 'Alice',
    name: 'EXSpecialAttackAuroraThrustSouthernCross_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackAuroraThrustSouthernCross_0',
    },
  },
  ChainAttackStarfallIntermission_0: {
    sheet: 'Alice',
    name: 'ChainAttackStarfallIntermission_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackStarfallIntermission_0',
    },
  },
  UltimateStarfallFinale_0: {
    sheet: 'Alice',
    name: 'UltimateStarfallFinale_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateStarfallFinale_0',
    },
  },
  QuickAssistIntertwinedStab_0: {
    sheet: 'Alice',
    name: 'QuickAssistIntertwinedStab_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistIntertwinedStab_0',
    },
  },
  DefensiveAssistParryGuard_0: {
    sheet: 'Alice',
    name: 'DefensiveAssistParryGuard_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistParryGuard_0',
    },
  },
  DefensiveAssistParryGuard_1: {
    sheet: 'Alice',
    name: 'DefensiveAssistParryGuard_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistParryGuard_1',
    },
  },
  DefensiveAssistParryGuard_2: {
    sheet: 'Alice',
    name: 'DefensiveAssistParryGuard_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistParryGuard_2',
    },
  },
  AssistFollowUpCrossRiposte_0: {
    sheet: 'Alice',
    name: 'AssistFollowUpCrossRiposte_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpCrossRiposte_0',
    },
  },
  m6_dmg: {
    sheet: 'Alice',
    name: 'm6_dmg',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'standardDmgBase',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'elemental',
      name: 'm6_dmg',
    },
  },
} as const
