// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Alice',
    name: 'standardDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Alice',
      attribute: 'physical',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Alice',
    name: 'anomalyDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_physical: {
    sheet: 'Alice',
    name: 'disorderDmgInst_physical',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'disorder',
      name: 'disorderDmgInst_physical',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Alice',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Alice',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      name: 'dazeInst',
    },
  },
  BasicAttackCelestialOverture_0_dmg: {
    sheet: 'Alice',
    name: 'BasicAttackCelestialOverture_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Alice',
      damageType1: 'basic',
      attribute: 'physical',
      name: 'BasicAttackCelestialOverture_0_dmg',
    },
  },
  BasicAttackCelestialOverture_0_daze: {
    sheet: 'Alice',
    name: 'BasicAttackCelestialOverture_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Alice',
      damageType1: 'basic',
      attribute: 'physical',
      name: 'BasicAttackCelestialOverture_0_daze',
    },
  },
  BasicAttackCelestialOverture_0_anomBuildup: {
    sheet: 'Alice',
    name: 'BasicAttackCelestialOverture_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Alice',
      damageType1: 'basic',
      attribute: 'physical',
      name: 'BasicAttackCelestialOverture_0_anomBuildup',
    },
  },
  BasicAttackCelestialOverture_1_dmg: {
    sheet: 'Alice',
    name: 'BasicAttackCelestialOverture_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Alice',
      damageType1: 'basic',
      attribute: 'physical',
      name: 'BasicAttackCelestialOverture_1_dmg',
    },
  },
  BasicAttackCelestialOverture_1_daze: {
    sheet: 'Alice',
    name: 'BasicAttackCelestialOverture_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Alice',
      damageType1: 'basic',
      attribute: 'physical',
      name: 'BasicAttackCelestialOverture_1_daze',
    },
  },
  BasicAttackCelestialOverture_1_anomBuildup: {
    sheet: 'Alice',
    name: 'BasicAttackCelestialOverture_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Alice',
      damageType1: 'basic',
      attribute: 'physical',
      name: 'BasicAttackCelestialOverture_1_anomBuildup',
    },
  },
  BasicAttackCelestialOverture_2_dmg: {
    sheet: 'Alice',
    name: 'BasicAttackCelestialOverture_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Alice',
      damageType1: 'basic',
      attribute: 'physical',
      name: 'BasicAttackCelestialOverture_2_dmg',
    },
  },
  BasicAttackCelestialOverture_2_daze: {
    sheet: 'Alice',
    name: 'BasicAttackCelestialOverture_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Alice',
      damageType1: 'basic',
      attribute: 'physical',
      name: 'BasicAttackCelestialOverture_2_daze',
    },
  },
  BasicAttackCelestialOverture_2_anomBuildup: {
    sheet: 'Alice',
    name: 'BasicAttackCelestialOverture_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Alice',
      damageType1: 'basic',
      attribute: 'physical',
      name: 'BasicAttackCelestialOverture_2_anomBuildup',
    },
  },
  BasicAttackCelestialOverture_3_dmg: {
    sheet: 'Alice',
    name: 'BasicAttackCelestialOverture_3_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Alice',
      damageType1: 'basic',
      attribute: 'physical',
      name: 'BasicAttackCelestialOverture_3_dmg',
    },
  },
  BasicAttackCelestialOverture_3_daze: {
    sheet: 'Alice',
    name: 'BasicAttackCelestialOverture_3_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Alice',
      damageType1: 'basic',
      attribute: 'physical',
      name: 'BasicAttackCelestialOverture_3_daze',
    },
  },
  BasicAttackCelestialOverture_3_anomBuildup: {
    sheet: 'Alice',
    name: 'BasicAttackCelestialOverture_3_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Alice',
      damageType1: 'basic',
      attribute: 'physical',
      name: 'BasicAttackCelestialOverture_3_anomBuildup',
    },
  },
  BasicAttackCelestialOverture_4_dmg: {
    sheet: 'Alice',
    name: 'BasicAttackCelestialOverture_4_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Alice',
      damageType1: 'basic',
      attribute: 'physical',
      name: 'BasicAttackCelestialOverture_4_dmg',
    },
  },
  BasicAttackCelestialOverture_4_daze: {
    sheet: 'Alice',
    name: 'BasicAttackCelestialOverture_4_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Alice',
      damageType1: 'basic',
      attribute: 'physical',
      name: 'BasicAttackCelestialOverture_4_daze',
    },
  },
  BasicAttackCelestialOverture_4_anomBuildup: {
    sheet: 'Alice',
    name: 'BasicAttackCelestialOverture_4_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Alice',
      damageType1: 'basic',
      attribute: 'physical',
      name: 'BasicAttackCelestialOverture_4_anomBuildup',
    },
  },
  BasicAttackCelestialOverture_5_dmg: {
    sheet: 'Alice',
    name: 'BasicAttackCelestialOverture_5_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Alice',
      damageType1: 'basic',
      attribute: 'physical',
      name: 'BasicAttackCelestialOverture_5_dmg',
    },
  },
  BasicAttackCelestialOverture_5_daze: {
    sheet: 'Alice',
    name: 'BasicAttackCelestialOverture_5_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Alice',
      damageType1: 'basic',
      attribute: 'physical',
      name: 'BasicAttackCelestialOverture_5_daze',
    },
  },
  BasicAttackCelestialOverture_5_anomBuildup: {
    sheet: 'Alice',
    name: 'BasicAttackCelestialOverture_5_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Alice',
      damageType1: 'basic',
      attribute: 'physical',
      name: 'BasicAttackCelestialOverture_5_anomBuildup',
    },
  },
  BasicAttackStarshineWaltz_0_dmg: {
    sheet: 'Alice',
    name: 'BasicAttackStarshineWaltz_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackStarshineWaltz_0_dmg',
    },
  },
  BasicAttackStarshineWaltz_0_daze: {
    sheet: 'Alice',
    name: 'BasicAttackStarshineWaltz_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackStarshineWaltz_0_daze',
    },
  },
  BasicAttackStarshineWaltz_0_anomBuildup: {
    sheet: 'Alice',
    name: 'BasicAttackStarshineWaltz_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackStarshineWaltz_0_anomBuildup',
    },
  },
  BasicAttackStarshineWaltz_1_dmg: {
    sheet: 'Alice',
    name: 'BasicAttackStarshineWaltz_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackStarshineWaltz_1_dmg',
    },
  },
  BasicAttackStarshineWaltz_1_daze: {
    sheet: 'Alice',
    name: 'BasicAttackStarshineWaltz_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackStarshineWaltz_1_daze',
    },
  },
  BasicAttackStarshineWaltz_1_anomBuildup: {
    sheet: 'Alice',
    name: 'BasicAttackStarshineWaltz_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackStarshineWaltz_1_anomBuildup',
    },
  },
  BasicAttackStarshineWaltz_2_dmg: {
    sheet: 'Alice',
    name: 'BasicAttackStarshineWaltz_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackStarshineWaltz_2_dmg',
    },
  },
  BasicAttackStarshineWaltz_2_daze: {
    sheet: 'Alice',
    name: 'BasicAttackStarshineWaltz_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackStarshineWaltz_2_daze',
    },
  },
  BasicAttackStarshineWaltz_2_anomBuildup: {
    sheet: 'Alice',
    name: 'BasicAttackStarshineWaltz_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackStarshineWaltz_2_anomBuildup',
    },
  },
  DashAttackBladeDancersGale_0_dmg: {
    sheet: 'Alice',
    name: 'DashAttackBladeDancersGale_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackBladeDancersGale_0_dmg',
    },
  },
  DashAttackBladeDancersGale_0_daze: {
    sheet: 'Alice',
    name: 'DashAttackBladeDancersGale_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackBladeDancersGale_0_daze',
    },
  },
  DashAttackBladeDancersGale_0_anomBuildup: {
    sheet: 'Alice',
    name: 'DashAttackBladeDancersGale_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackBladeDancersGale_0_anomBuildup',
    },
  },
  DodgeCounterCeremonyOfSwordlight_0_dmg: {
    sheet: 'Alice',
    name: 'DodgeCounterCeremonyOfSwordlight_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterCeremonyOfSwordlight_0_dmg',
    },
  },
  DodgeCounterCeremonyOfSwordlight_0_daze: {
    sheet: 'Alice',
    name: 'DodgeCounterCeremonyOfSwordlight_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterCeremonyOfSwordlight_0_daze',
    },
  },
  DodgeCounterCeremonyOfSwordlight_0_anomBuildup: {
    sheet: 'Alice',
    name: 'DodgeCounterCeremonyOfSwordlight_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterCeremonyOfSwordlight_0_anomBuildup',
    },
  },
  SpecialAttackPiercingDawn_0_dmg: {
    sheet: 'Alice',
    name: 'SpecialAttackPiercingDawn_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackPiercingDawn_0_dmg',
    },
  },
  SpecialAttackPiercingDawn_0_daze: {
    sheet: 'Alice',
    name: 'SpecialAttackPiercingDawn_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackPiercingDawn_0_daze',
    },
  },
  SpecialAttackPiercingDawn_0_anomBuildup: {
    sheet: 'Alice',
    name: 'SpecialAttackPiercingDawn_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackPiercingDawn_0_anomBuildup',
    },
  },
  EXSpecialAttackAuroraThrustNorthernCross_0_dmg: {
    sheet: 'Alice',
    name: 'EXSpecialAttackAuroraThrustNorthernCross_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackAuroraThrustNorthernCross_0_dmg',
    },
  },
  EXSpecialAttackAuroraThrustNorthernCross_0_daze: {
    sheet: 'Alice',
    name: 'EXSpecialAttackAuroraThrustNorthernCross_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackAuroraThrustNorthernCross_0_daze',
    },
  },
  EXSpecialAttackAuroraThrustNorthernCross_0_anomBuildup: {
    sheet: 'Alice',
    name: 'EXSpecialAttackAuroraThrustNorthernCross_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackAuroraThrustNorthernCross_0_anomBuildup',
    },
  },
  EXSpecialAttackAuroraThrustSouthernCross_0_dmg: {
    sheet: 'Alice',
    name: 'EXSpecialAttackAuroraThrustSouthernCross_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackAuroraThrustSouthernCross_0_dmg',
    },
  },
  EXSpecialAttackAuroraThrustSouthernCross_0_daze: {
    sheet: 'Alice',
    name: 'EXSpecialAttackAuroraThrustSouthernCross_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackAuroraThrustSouthernCross_0_daze',
    },
  },
  EXSpecialAttackAuroraThrustSouthernCross_0_anomBuildup: {
    sheet: 'Alice',
    name: 'EXSpecialAttackAuroraThrustSouthernCross_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackAuroraThrustSouthernCross_0_anomBuildup',
    },
  },
  ChainAttackStarfallIntermission_0_dmg: {
    sheet: 'Alice',
    name: 'ChainAttackStarfallIntermission_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackStarfallIntermission_0_dmg',
    },
  },
  ChainAttackStarfallIntermission_0_daze: {
    sheet: 'Alice',
    name: 'ChainAttackStarfallIntermission_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackStarfallIntermission_0_daze',
    },
  },
  ChainAttackStarfallIntermission_0_anomBuildup: {
    sheet: 'Alice',
    name: 'ChainAttackStarfallIntermission_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackStarfallIntermission_0_anomBuildup',
    },
  },
  UltimateStarfallFinale_0_dmg: {
    sheet: 'Alice',
    name: 'UltimateStarfallFinale_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateStarfallFinale_0_dmg',
    },
  },
  UltimateStarfallFinale_0_daze: {
    sheet: 'Alice',
    name: 'UltimateStarfallFinale_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateStarfallFinale_0_daze',
    },
  },
  UltimateStarfallFinale_0_anomBuildup: {
    sheet: 'Alice',
    name: 'UltimateStarfallFinale_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateStarfallFinale_0_anomBuildup',
    },
  },
  QuickAssistIntertwinedStab_0_dmg: {
    sheet: 'Alice',
    name: 'QuickAssistIntertwinedStab_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistIntertwinedStab_0_dmg',
    },
  },
  QuickAssistIntertwinedStab_0_daze: {
    sheet: 'Alice',
    name: 'QuickAssistIntertwinedStab_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistIntertwinedStab_0_daze',
    },
  },
  QuickAssistIntertwinedStab_0_anomBuildup: {
    sheet: 'Alice',
    name: 'QuickAssistIntertwinedStab_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistIntertwinedStab_0_anomBuildup',
    },
  },
  DefensiveAssistParryGuard_0_dmg: {
    sheet: 'Alice',
    name: 'DefensiveAssistParryGuard_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistParryGuard_0_dmg',
    },
  },
  DefensiveAssistParryGuard_0_daze: {
    sheet: 'Alice',
    name: 'DefensiveAssistParryGuard_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistParryGuard_0_daze',
    },
  },
  DefensiveAssistParryGuard_0_anomBuildup: {
    sheet: 'Alice',
    name: 'DefensiveAssistParryGuard_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistParryGuard_0_anomBuildup',
    },
  },
  DefensiveAssistParryGuard_1_dmg: {
    sheet: 'Alice',
    name: 'DefensiveAssistParryGuard_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistParryGuard_1_dmg',
    },
  },
  DefensiveAssistParryGuard_1_daze: {
    sheet: 'Alice',
    name: 'DefensiveAssistParryGuard_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistParryGuard_1_daze',
    },
  },
  DefensiveAssistParryGuard_1_anomBuildup: {
    sheet: 'Alice',
    name: 'DefensiveAssistParryGuard_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistParryGuard_1_anomBuildup',
    },
  },
  DefensiveAssistParryGuard_2_dmg: {
    sheet: 'Alice',
    name: 'DefensiveAssistParryGuard_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistParryGuard_2_dmg',
    },
  },
  DefensiveAssistParryGuard_2_daze: {
    sheet: 'Alice',
    name: 'DefensiveAssistParryGuard_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistParryGuard_2_daze',
    },
  },
  DefensiveAssistParryGuard_2_anomBuildup: {
    sheet: 'Alice',
    name: 'DefensiveAssistParryGuard_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistParryGuard_2_anomBuildup',
    },
  },
  AssistFollowUpCrossRiposte_0_dmg: {
    sheet: 'Alice',
    name: 'AssistFollowUpCrossRiposte_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpCrossRiposte_0_dmg',
    },
  },
  AssistFollowUpCrossRiposte_0_daze: {
    sheet: 'Alice',
    name: 'AssistFollowUpCrossRiposte_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpCrossRiposte_0_daze',
    },
  },
  AssistFollowUpCrossRiposte_0_anomBuildup: {
    sheet: 'Alice',
    name: 'AssistFollowUpCrossRiposte_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpCrossRiposte_0_anomBuildup',
    },
  },
  m6_dmg: {
    sheet: 'Alice',
    name: 'm6_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'elemental',
      name: 'm6_dmg',
    },
  },
} as const
