// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Alice',
    name: 'standardDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Alice',
      attribute: 'physical',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Alice',
    name: 'anomalyDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_physical: {
    sheet: 'Alice',
    name: 'disorderDmgInst_physical',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'disorder',
      name: 'disorderDmgInst_physical',
    },
  },
  vortexDmgInst_physical: {
    sheet: 'Alice',
    name: 'vortexDmgInst_physical',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'vortex',
      name: 'vortexDmgInst_physical',
    },
  },
  abloomDmgInst: {
    sheet: 'Alice',
    name: 'abloomDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Alice',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Alice',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      name: 'dazeInst',
    },
  },
  'BasicAttackCelestialOverture_0:standardDmg': {
    sheet: 'Alice',
    name: 'BasicAttackCelestialOverture_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Alice',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackCelestialOverture_0',
    },
  },
  'BasicAttackCelestialOverture_0:dazeBuildup': {
    sheet: 'Alice',
    name: 'BasicAttackCelestialOverture_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Alice',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackCelestialOverture_0_daze',
    },
  },
  'BasicAttackCelestialOverture_0:anomBuildup': {
    sheet: 'Alice',
    name: 'BasicAttackCelestialOverture_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Alice',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackCelestialOverture_0_anomBuildup',
    },
  },
  'BasicAttackCelestialOverture_1:standardDmg': {
    sheet: 'Alice',
    name: 'BasicAttackCelestialOverture_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Alice',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackCelestialOverture_1_dmg',
    },
  },
  'BasicAttackCelestialOverture_1:dazeBuildup': {
    sheet: 'Alice',
    name: 'BasicAttackCelestialOverture_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Alice',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackCelestialOverture_1_daze',
    },
  },
  'BasicAttackCelestialOverture_1:anomBuildup': {
    sheet: 'Alice',
    name: 'BasicAttackCelestialOverture_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Alice',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackCelestialOverture_1_anomBuildup',
    },
  },
  'BasicAttackCelestialOverture_2:standardDmg': {
    sheet: 'Alice',
    name: 'BasicAttackCelestialOverture_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Alice',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackCelestialOverture_2_dmg',
    },
  },
  'BasicAttackCelestialOverture_2:dazeBuildup': {
    sheet: 'Alice',
    name: 'BasicAttackCelestialOverture_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Alice',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackCelestialOverture_2_daze',
    },
  },
  'BasicAttackCelestialOverture_2:anomBuildup': {
    sheet: 'Alice',
    name: 'BasicAttackCelestialOverture_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Alice',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackCelestialOverture_2_anomBuildup',
    },
  },
  'BasicAttackCelestialOverture_3:standardDmg': {
    sheet: 'Alice',
    name: 'BasicAttackCelestialOverture_3:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Alice',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackCelestialOverture_3_dmg',
    },
  },
  'BasicAttackCelestialOverture_3:dazeBuildup': {
    sheet: 'Alice',
    name: 'BasicAttackCelestialOverture_3:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Alice',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackCelestialOverture_3_daze',
    },
  },
  'BasicAttackCelestialOverture_3:anomBuildup': {
    sheet: 'Alice',
    name: 'BasicAttackCelestialOverture_3:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Alice',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackCelestialOverture_3_anomBuildup',
    },
  },
  'BasicAttackCelestialOverture_4:standardDmg': {
    sheet: 'Alice',
    name: 'BasicAttackCelestialOverture_4:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Alice',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackCelestialOverture_4_dmg',
    },
  },
  'BasicAttackCelestialOverture_4:dazeBuildup': {
    sheet: 'Alice',
    name: 'BasicAttackCelestialOverture_4:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Alice',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackCelestialOverture_4_daze',
    },
  },
  'BasicAttackCelestialOverture_4:anomBuildup': {
    sheet: 'Alice',
    name: 'BasicAttackCelestialOverture_4:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Alice',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackCelestialOverture_4_anomBuildup',
    },
  },
  'BasicAttackCelestialOverture_5:standardDmg': {
    sheet: 'Alice',
    name: 'BasicAttackCelestialOverture_5:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Alice',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackCelestialOverture_5_dmg',
    },
  },
  'BasicAttackCelestialOverture_5:dazeBuildup': {
    sheet: 'Alice',
    name: 'BasicAttackCelestialOverture_5:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Alice',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackCelestialOverture_5_daze',
    },
  },
  'BasicAttackCelestialOverture_5:anomBuildup': {
    sheet: 'Alice',
    name: 'BasicAttackCelestialOverture_5:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Alice',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackCelestialOverture_5_anomBuildup',
    },
  },
  'BasicAttackStarshineWaltz_0:standardDmg': {
    sheet: 'Alice',
    name: 'BasicAttackStarshineWaltz_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackStarshineWaltz_0_dmg',
    },
  },
  'BasicAttackStarshineWaltz_0:dazeBuildup': {
    sheet: 'Alice',
    name: 'BasicAttackStarshineWaltz_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackStarshineWaltz_0_daze',
    },
  },
  'BasicAttackStarshineWaltz_0:anomBuildup': {
    sheet: 'Alice',
    name: 'BasicAttackStarshineWaltz_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackStarshineWaltz_0_anomBuildup',
    },
  },
  'BasicAttackStarshineWaltz_1:standardDmg': {
    sheet: 'Alice',
    name: 'BasicAttackStarshineWaltz_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackStarshineWaltz_1_dmg',
    },
  },
  'BasicAttackStarshineWaltz_1:dazeBuildup': {
    sheet: 'Alice',
    name: 'BasicAttackStarshineWaltz_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackStarshineWaltz_1_daze',
    },
  },
  'BasicAttackStarshineWaltz_1:anomBuildup': {
    sheet: 'Alice',
    name: 'BasicAttackStarshineWaltz_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackStarshineWaltz_1_anomBuildup',
    },
  },
  'BasicAttackStarshineWaltz_2:standardDmg': {
    sheet: 'Alice',
    name: 'BasicAttackStarshineWaltz_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackStarshineWaltz_2_dmg',
    },
  },
  'BasicAttackStarshineWaltz_2:dazeBuildup': {
    sheet: 'Alice',
    name: 'BasicAttackStarshineWaltz_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackStarshineWaltz_2_daze',
    },
  },
  'BasicAttackStarshineWaltz_2:anomBuildup': {
    sheet: 'Alice',
    name: 'BasicAttackStarshineWaltz_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackStarshineWaltz_2_anomBuildup',
    },
  },
  'DashAttackBladeDancersGale_0:standardDmg': {
    sheet: 'Alice',
    name: 'DashAttackBladeDancersGale_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'dash',
      skillType1: 'dodgeSkill',
      name: 'DashAttackBladeDancersGale_0_dmg',
    },
  },
  'DashAttackBladeDancersGale_0:dazeBuildup': {
    sheet: 'Alice',
    name: 'DashAttackBladeDancersGale_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'dash',
      skillType1: 'dodgeSkill',
      name: 'DashAttackBladeDancersGale_0_daze',
    },
  },
  'DashAttackBladeDancersGale_0:anomBuildup': {
    sheet: 'Alice',
    name: 'DashAttackBladeDancersGale_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'dash',
      skillType1: 'dodgeSkill',
      name: 'DashAttackBladeDancersGale_0_anomBuildup',
    },
  },
  'DodgeCounterCeremonyOfSwordlight_0:standardDmg': {
    sheet: 'Alice',
    name: 'DodgeCounterCeremonyOfSwordlight_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType1: 'dodgeSkill',
      name: 'DodgeCounterCeremonyOfSwordlight_0_dmg',
    },
  },
  'DodgeCounterCeremonyOfSwordlight_0:dazeBuildup': {
    sheet: 'Alice',
    name: 'DodgeCounterCeremonyOfSwordlight_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType1: 'dodgeSkill',
      name: 'DodgeCounterCeremonyOfSwordlight_0_daze',
    },
  },
  'DodgeCounterCeremonyOfSwordlight_0:anomBuildup': {
    sheet: 'Alice',
    name: 'DodgeCounterCeremonyOfSwordlight_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType1: 'dodgeSkill',
      name: 'DodgeCounterCeremonyOfSwordlight_0_anomBuildup',
    },
  },
  'SpecialAttackPiercingDawn_0:standardDmg': {
    sheet: 'Alice',
    name: 'SpecialAttackPiercingDawn_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackPiercingDawn_0_dmg',
    },
  },
  'SpecialAttackPiercingDawn_0:dazeBuildup': {
    sheet: 'Alice',
    name: 'SpecialAttackPiercingDawn_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackPiercingDawn_0_daze',
    },
  },
  'SpecialAttackPiercingDawn_0:anomBuildup': {
    sheet: 'Alice',
    name: 'SpecialAttackPiercingDawn_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackPiercingDawn_0_anomBuildup',
    },
  },
  'EXSpecialAttackAuroraThrustNorthernCross_0:standardDmg': {
    sheet: 'Alice',
    name: 'EXSpecialAttackAuroraThrustNorthernCross_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackAuroraThrustNorthernCross_0_dmg',
    },
  },
  'EXSpecialAttackAuroraThrustNorthernCross_0:dazeBuildup': {
    sheet: 'Alice',
    name: 'EXSpecialAttackAuroraThrustNorthernCross_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackAuroraThrustNorthernCross_0_daze',
    },
  },
  'EXSpecialAttackAuroraThrustNorthernCross_0:anomBuildup': {
    sheet: 'Alice',
    name: 'EXSpecialAttackAuroraThrustNorthernCross_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackAuroraThrustNorthernCross_0_anomBuildup',
    },
  },
  'EXSpecialAttackAuroraThrustSouthernCross_0:standardDmg': {
    sheet: 'Alice',
    name: 'EXSpecialAttackAuroraThrustSouthernCross_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackAuroraThrustSouthernCross_0_dmg',
    },
  },
  'EXSpecialAttackAuroraThrustSouthernCross_0:dazeBuildup': {
    sheet: 'Alice',
    name: 'EXSpecialAttackAuroraThrustSouthernCross_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackAuroraThrustSouthernCross_0_daze',
    },
  },
  'EXSpecialAttackAuroraThrustSouthernCross_0:anomBuildup': {
    sheet: 'Alice',
    name: 'EXSpecialAttackAuroraThrustSouthernCross_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackAuroraThrustSouthernCross_0_anomBuildup',
    },
  },
  'ChainAttackStarfallIntermission_0:standardDmg': {
    sheet: 'Alice',
    name: 'ChainAttackStarfallIntermission_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'chain',
      skillType1: 'chainSkill',
      name: 'ChainAttackStarfallIntermission_0_dmg',
    },
  },
  'ChainAttackStarfallIntermission_0:dazeBuildup': {
    sheet: 'Alice',
    name: 'ChainAttackStarfallIntermission_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'chain',
      skillType1: 'chainSkill',
      name: 'ChainAttackStarfallIntermission_0_daze',
    },
  },
  'ChainAttackStarfallIntermission_0:anomBuildup': {
    sheet: 'Alice',
    name: 'ChainAttackStarfallIntermission_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'chain',
      skillType1: 'chainSkill',
      name: 'ChainAttackStarfallIntermission_0_anomBuildup',
    },
  },
  'UltimateStarfallFinale_0:standardDmg': {
    sheet: 'Alice',
    name: 'UltimateStarfallFinale_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'ult',
      skillType1: 'chainSkill',
      name: 'UltimateStarfallFinale_0_dmg',
    },
  },
  'UltimateStarfallFinale_0:dazeBuildup': {
    sheet: 'Alice',
    name: 'UltimateStarfallFinale_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'ult',
      skillType1: 'chainSkill',
      name: 'UltimateStarfallFinale_0_daze',
    },
  },
  'UltimateStarfallFinale_0:anomBuildup': {
    sheet: 'Alice',
    name: 'UltimateStarfallFinale_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'ult',
      skillType1: 'chainSkill',
      name: 'UltimateStarfallFinale_0_anomBuildup',
    },
  },
  'QuickAssistIntertwinedStab_0:standardDmg': {
    sheet: 'Alice',
    name: 'QuickAssistIntertwinedStab_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType1: 'assistSkill',
      name: 'QuickAssistIntertwinedStab_0_dmg',
    },
  },
  'QuickAssistIntertwinedStab_0:dazeBuildup': {
    sheet: 'Alice',
    name: 'QuickAssistIntertwinedStab_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType1: 'assistSkill',
      name: 'QuickAssistIntertwinedStab_0_daze',
    },
  },
  'QuickAssistIntertwinedStab_0:anomBuildup': {
    sheet: 'Alice',
    name: 'QuickAssistIntertwinedStab_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType1: 'assistSkill',
      name: 'QuickAssistIntertwinedStab_0_anomBuildup',
    },
  },
  'DefensiveAssistParryGuard_0:standardDmg': {
    sheet: 'Alice',
    name: 'DefensiveAssistParryGuard_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistParryGuard_0_dmg',
    },
  },
  'DefensiveAssistParryGuard_0:dazeBuildup': {
    sheet: 'Alice',
    name: 'DefensiveAssistParryGuard_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistParryGuard_0_daze',
    },
  },
  'DefensiveAssistParryGuard_0:anomBuildup': {
    sheet: 'Alice',
    name: 'DefensiveAssistParryGuard_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistParryGuard_0_anomBuildup',
    },
  },
  'DefensiveAssistParryGuard_1:standardDmg': {
    sheet: 'Alice',
    name: 'DefensiveAssistParryGuard_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistParryGuard_1_dmg',
    },
  },
  'DefensiveAssistParryGuard_1:dazeBuildup': {
    sheet: 'Alice',
    name: 'DefensiveAssistParryGuard_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistParryGuard_1_daze',
    },
  },
  'DefensiveAssistParryGuard_1:anomBuildup': {
    sheet: 'Alice',
    name: 'DefensiveAssistParryGuard_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistParryGuard_1_anomBuildup',
    },
  },
  'DefensiveAssistParryGuard_2:standardDmg': {
    sheet: 'Alice',
    name: 'DefensiveAssistParryGuard_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistParryGuard_2_dmg',
    },
  },
  'DefensiveAssistParryGuard_2:dazeBuildup': {
    sheet: 'Alice',
    name: 'DefensiveAssistParryGuard_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistParryGuard_2_daze',
    },
  },
  'DefensiveAssistParryGuard_2:anomBuildup': {
    sheet: 'Alice',
    name: 'DefensiveAssistParryGuard_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistParryGuard_2_anomBuildup',
    },
  },
  'AssistFollowUpCrossRiposte_0:standardDmg': {
    sheet: 'Alice',
    name: 'AssistFollowUpCrossRiposte_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType1: 'assistSkill',
      name: 'AssistFollowUpCrossRiposte_0_dmg',
    },
  },
  'AssistFollowUpCrossRiposte_0:dazeBuildup': {
    sheet: 'Alice',
    name: 'AssistFollowUpCrossRiposte_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType1: 'assistSkill',
      name: 'AssistFollowUpCrossRiposte_0_daze',
    },
  },
  'AssistFollowUpCrossRiposte_0:anomBuildup': {
    sheet: 'Alice',
    name: 'AssistFollowUpCrossRiposte_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType1: 'assistSkill',
      name: 'AssistFollowUpCrossRiposte_0_anomBuildup',
    },
  },
  m6_dmg: {
    sheet: 'Alice',
    name: 'm6_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Alice',
      attribute: 'physical',
      damageType1: 'elemental',
      name: 'm6_dmg',
    },
  },
} as const
