// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Norma',
    name: 'standardDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Norma',
      attribute: 'fire',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Norma',
    name: 'anomalyDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_fire: {
    sheet: 'Norma',
    name: 'disorderDmgInst_fire',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'disorder',
      name: 'disorderDmgInst_fire',
    },
  },
  vortexDmgInst_fire: {
    sheet: 'Norma',
    name: 'vortexDmgInst_fire',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'vortex',
      name: 'vortexDmgInst_fire',
    },
  },
  abloomDmgInst: {
    sheet: 'Norma',
    name: 'abloomDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Norma',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Norma',
      attribute: 'fire',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Norma',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Norma',
      attribute: 'fire',
      name: 'dazeInst',
    },
  },
  BasicAttackEngineeringInsurance_0_dmg: {
    sheet: 'Norma',
    name: 'BasicAttackEngineeringInsurance_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEngineeringInsurance_0_dmg',
    },
  },
  BasicAttackEngineeringInsurance_0_daze: {
    sheet: 'Norma',
    name: 'BasicAttackEngineeringInsurance_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEngineeringInsurance_0_daze',
    },
  },
  BasicAttackEngineeringInsurance_0_anomBuildup: {
    sheet: 'Norma',
    name: 'BasicAttackEngineeringInsurance_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEngineeringInsurance_0_anomBuildup',
    },
  },
  BasicAttackEngineeringInsurance_1_dmg: {
    sheet: 'Norma',
    name: 'BasicAttackEngineeringInsurance_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEngineeringInsurance_1_dmg',
    },
  },
  BasicAttackEngineeringInsurance_1_daze: {
    sheet: 'Norma',
    name: 'BasicAttackEngineeringInsurance_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEngineeringInsurance_1_daze',
    },
  },
  BasicAttackEngineeringInsurance_1_anomBuildup: {
    sheet: 'Norma',
    name: 'BasicAttackEngineeringInsurance_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEngineeringInsurance_1_anomBuildup',
    },
  },
  BasicAttackEngineeringInsurance_2_dmg: {
    sheet: 'Norma',
    name: 'BasicAttackEngineeringInsurance_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEngineeringInsurance_2_dmg',
    },
  },
  BasicAttackEngineeringInsurance_2_daze: {
    sheet: 'Norma',
    name: 'BasicAttackEngineeringInsurance_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEngineeringInsurance_2_daze',
    },
  },
  BasicAttackEngineeringInsurance_2_anomBuildup: {
    sheet: 'Norma',
    name: 'BasicAttackEngineeringInsurance_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEngineeringInsurance_2_anomBuildup',
    },
  },
  BasicAttackEngineeringInsurance_3_dmg: {
    sheet: 'Norma',
    name: 'BasicAttackEngineeringInsurance_3_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEngineeringInsurance_3_dmg',
    },
  },
  BasicAttackEngineeringInsurance_3_daze: {
    sheet: 'Norma',
    name: 'BasicAttackEngineeringInsurance_3_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEngineeringInsurance_3_daze',
    },
  },
  BasicAttackEngineeringInsurance_3_anomBuildup: {
    sheet: 'Norma',
    name: 'BasicAttackEngineeringInsurance_3_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEngineeringInsurance_3_anomBuildup',
    },
  },
  BasicAttackHatTrick_0_dmg: {
    sheet: 'Norma',
    name: 'BasicAttackHatTrick_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackHatTrick_0_dmg',
    },
  },
  BasicAttackHatTrick_0_daze: {
    sheet: 'Norma',
    name: 'BasicAttackHatTrick_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackHatTrick_0_daze',
    },
  },
  BasicAttackHatTrick_0_anomBuildup: {
    sheet: 'Norma',
    name: 'BasicAttackHatTrick_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackHatTrick_0_anomBuildup',
    },
  },
  DashAttackDeadlineRush_0_dmg: {
    sheet: 'Norma',
    name: 'DashAttackDeadlineRush_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackDeadlineRush_0_dmg',
    },
  },
  DashAttackDeadlineRush_0_daze: {
    sheet: 'Norma',
    name: 'DashAttackDeadlineRush_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackDeadlineRush_0_daze',
    },
  },
  DashAttackDeadlineRush_0_anomBuildup: {
    sheet: 'Norma',
    name: 'DashAttackDeadlineRush_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackDeadlineRush_0_anomBuildup',
    },
  },
  DodgeCounterComplianceTesting_0_dmg: {
    sheet: 'Norma',
    name: 'DodgeCounterComplianceTesting_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterComplianceTesting_0_dmg',
    },
  },
  DodgeCounterComplianceTesting_0_daze: {
    sheet: 'Norma',
    name: 'DodgeCounterComplianceTesting_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterComplianceTesting_0_daze',
    },
  },
  DodgeCounterComplianceTesting_0_anomBuildup: {
    sheet: 'Norma',
    name: 'DodgeCounterComplianceTesting_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterComplianceTesting_0_anomBuildup',
    },
  },
  SpecialAttackThermalShutdown_0_dmg: {
    sheet: 'Norma',
    name: 'SpecialAttackThermalShutdown_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackThermalShutdown_0_dmg',
    },
  },
  SpecialAttackThermalShutdown_0_daze: {
    sheet: 'Norma',
    name: 'SpecialAttackThermalShutdown_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackThermalShutdown_0_daze',
    },
  },
  SpecialAttackThermalShutdown_0_anomBuildup: {
    sheet: 'Norma',
    name: 'SpecialAttackThermalShutdown_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackThermalShutdown_0_anomBuildup',
    },
  },
  EXSpecialAttackEnNahBarrage_0_dmg: {
    sheet: 'Norma',
    name: 'EXSpecialAttackEnNahBarrage_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackEnNahBarrage_0_dmg',
    },
  },
  EXSpecialAttackEnNahBarrage_0_daze: {
    sheet: 'Norma',
    name: 'EXSpecialAttackEnNahBarrage_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackEnNahBarrage_0_daze',
    },
  },
  EXSpecialAttackEnNahBarrage_0_anomBuildup: {
    sheet: 'Norma',
    name: 'EXSpecialAttackEnNahBarrage_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackEnNahBarrage_0_anomBuildup',
    },
  },
  EXSpecialAttackEnNahBarrage_1_dmg: {
    sheet: 'Norma',
    name: 'EXSpecialAttackEnNahBarrage_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackEnNahBarrage_1_dmg',
    },
  },
  EXSpecialAttackEnNahBarrage_1_daze: {
    sheet: 'Norma',
    name: 'EXSpecialAttackEnNahBarrage_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackEnNahBarrage_1_daze',
    },
  },
  EXSpecialAttackEnNahBarrage_1_anomBuildup: {
    sheet: 'Norma',
    name: 'EXSpecialAttackEnNahBarrage_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackEnNahBarrage_1_anomBuildup',
    },
  },
  EXSpecialAttackEnNahBarrage_2_dmg: {
    sheet: 'Norma',
    name: 'EXSpecialAttackEnNahBarrage_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackEnNahBarrage_2_dmg',
    },
  },
  EXSpecialAttackEnNahBarrage_2_daze: {
    sheet: 'Norma',
    name: 'EXSpecialAttackEnNahBarrage_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackEnNahBarrage_2_daze',
    },
  },
  EXSpecialAttackEnNahBarrage_2_anomBuildup: {
    sheet: 'Norma',
    name: 'EXSpecialAttackEnNahBarrage_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackEnNahBarrage_2_anomBuildup',
    },
  },
  EXSpecialAttackEnNahBarrage_3_dmg: {
    sheet: 'Norma',
    name: 'EXSpecialAttackEnNahBarrage_3_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackEnNahBarrage_3_dmg',
    },
  },
  EXSpecialAttackEnNahBarrage_3_daze: {
    sheet: 'Norma',
    name: 'EXSpecialAttackEnNahBarrage_3_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackEnNahBarrage_3_daze',
    },
  },
  EXSpecialAttackEnNahBarrage_3_anomBuildup: {
    sheet: 'Norma',
    name: 'EXSpecialAttackEnNahBarrage_3_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackEnNahBarrage_3_anomBuildup',
    },
  },
  EXSpecialAttackEnNahBarrage_4_dmg: {
    sheet: 'Norma',
    name: 'EXSpecialAttackEnNahBarrage_4_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackEnNahBarrage_4_dmg',
    },
  },
  EXSpecialAttackEnNahBarrage_4_daze: {
    sheet: 'Norma',
    name: 'EXSpecialAttackEnNahBarrage_4_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackEnNahBarrage_4_daze',
    },
  },
  EXSpecialAttackEnNahBarrage_4_anomBuildup: {
    sheet: 'Norma',
    name: 'EXSpecialAttackEnNahBarrage_4_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackEnNahBarrage_4_anomBuildup',
    },
  },
  EXSpecialAttackEnNahBarrage_5_dmg: {
    sheet: 'Norma',
    name: 'EXSpecialAttackEnNahBarrage_5_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackEnNahBarrage_5_dmg',
    },
  },
  EXSpecialAttackEnNahBarrage_5_daze: {
    sheet: 'Norma',
    name: 'EXSpecialAttackEnNahBarrage_5_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackEnNahBarrage_5_daze',
    },
  },
  EXSpecialAttackEnNahBarrage_5_anomBuildup: {
    sheet: 'Norma',
    name: 'EXSpecialAttackEnNahBarrage_5_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackEnNahBarrage_5_anomBuildup',
    },
  },
  SpecialAttackTargetPractice_0_dmg: {
    sheet: 'Norma',
    name: 'SpecialAttackTargetPractice_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackTargetPractice_0_dmg',
    },
  },
  SpecialAttackTargetPractice_0_daze: {
    sheet: 'Norma',
    name: 'SpecialAttackTargetPractice_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackTargetPractice_0_daze',
    },
  },
  SpecialAttackTargetPractice_0_anomBuildup: {
    sheet: 'Norma',
    name: 'SpecialAttackTargetPractice_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackTargetPractice_0_anomBuildup',
    },
  },
  EXSpecialAttackExplosiveExperiment_0_dmg: {
    sheet: 'Norma',
    name: 'EXSpecialAttackExplosiveExperiment_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackExplosiveExperiment_0_dmg',
    },
  },
  EXSpecialAttackExplosiveExperiment_0_daze: {
    sheet: 'Norma',
    name: 'EXSpecialAttackExplosiveExperiment_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackExplosiveExperiment_0_daze',
    },
  },
  EXSpecialAttackExplosiveExperiment_0_anomBuildup: {
    sheet: 'Norma',
    name: 'EXSpecialAttackExplosiveExperiment_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackExplosiveExperiment_0_anomBuildup',
    },
  },
  EXSpecialAttackExplosiveExperiment_1_dmg: {
    sheet: 'Norma',
    name: 'EXSpecialAttackExplosiveExperiment_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackExplosiveExperiment_1_dmg',
    },
  },
  EXSpecialAttackExplosiveExperiment_1_daze: {
    sheet: 'Norma',
    name: 'EXSpecialAttackExplosiveExperiment_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackExplosiveExperiment_1_daze',
    },
  },
  EXSpecialAttackExplosiveExperiment_1_anomBuildup: {
    sheet: 'Norma',
    name: 'EXSpecialAttackExplosiveExperiment_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackExplosiveExperiment_1_anomBuildup',
    },
  },
  ChainAttackImpactDrill_0_dmg: {
    sheet: 'Norma',
    name: 'ChainAttackImpactDrill_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackImpactDrill_0_dmg',
    },
  },
  ChainAttackImpactDrill_0_daze: {
    sheet: 'Norma',
    name: 'ChainAttackImpactDrill_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackImpactDrill_0_daze',
    },
  },
  ChainAttackImpactDrill_0_anomBuildup: {
    sheet: 'Norma',
    name: 'ChainAttackImpactDrill_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackImpactDrill_0_anomBuildup',
    },
  },
  UltimateDoctrineOfSuperiorFirepower_0_dmg: {
    sheet: 'Norma',
    name: 'UltimateDoctrineOfSuperiorFirepower_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateDoctrineOfSuperiorFirepower_0_dmg',
    },
  },
  UltimateDoctrineOfSuperiorFirepower_0_daze: {
    sheet: 'Norma',
    name: 'UltimateDoctrineOfSuperiorFirepower_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateDoctrineOfSuperiorFirepower_0_daze',
    },
  },
  UltimateDoctrineOfSuperiorFirepower_0_anomBuildup: {
    sheet: 'Norma',
    name: 'UltimateDoctrineOfSuperiorFirepower_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateDoctrineOfSuperiorFirepower_0_anomBuildup',
    },
  },
  QuickAssistRoaringBackup_0_dmg: {
    sheet: 'Norma',
    name: 'QuickAssistRoaringBackup_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistRoaringBackup_0_dmg',
    },
  },
  QuickAssistRoaringBackup_0_daze: {
    sheet: 'Norma',
    name: 'QuickAssistRoaringBackup_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistRoaringBackup_0_daze',
    },
  },
  QuickAssistRoaringBackup_0_anomBuildup: {
    sheet: 'Norma',
    name: 'QuickAssistRoaringBackup_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistRoaringBackup_0_anomBuildup',
    },
  },
  DefensiveAssistTechnologicalBastion_0_dmg: {
    sheet: 'Norma',
    name: 'DefensiveAssistTechnologicalBastion_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistTechnologicalBastion_0_dmg',
    },
  },
  DefensiveAssistTechnologicalBastion_0_daze: {
    sheet: 'Norma',
    name: 'DefensiveAssistTechnologicalBastion_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistTechnologicalBastion_0_daze',
    },
  },
  DefensiveAssistTechnologicalBastion_0_anomBuildup: {
    sheet: 'Norma',
    name: 'DefensiveAssistTechnologicalBastion_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistTechnologicalBastion_0_anomBuildup',
    },
  },
  DefensiveAssistTechnologicalBastion_1_dmg: {
    sheet: 'Norma',
    name: 'DefensiveAssistTechnologicalBastion_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistTechnologicalBastion_1_dmg',
    },
  },
  DefensiveAssistTechnologicalBastion_1_daze: {
    sheet: 'Norma',
    name: 'DefensiveAssistTechnologicalBastion_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistTechnologicalBastion_1_daze',
    },
  },
  DefensiveAssistTechnologicalBastion_1_anomBuildup: {
    sheet: 'Norma',
    name: 'DefensiveAssistTechnologicalBastion_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistTechnologicalBastion_1_anomBuildup',
    },
  },
  DefensiveAssistTechnologicalBastion_2_dmg: {
    sheet: 'Norma',
    name: 'DefensiveAssistTechnologicalBastion_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistTechnologicalBastion_2_dmg',
    },
  },
  DefensiveAssistTechnologicalBastion_2_daze: {
    sheet: 'Norma',
    name: 'DefensiveAssistTechnologicalBastion_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistTechnologicalBastion_2_daze',
    },
  },
  DefensiveAssistTechnologicalBastion_2_anomBuildup: {
    sheet: 'Norma',
    name: 'DefensiveAssistTechnologicalBastion_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistTechnologicalBastion_2_anomBuildup',
    },
  },
  AssistFollowUpTechnologicalSuppression_0_dmg: {
    sheet: 'Norma',
    name: 'AssistFollowUpTechnologicalSuppression_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpTechnologicalSuppression_0_dmg',
    },
  },
  AssistFollowUpTechnologicalSuppression_0_daze: {
    sheet: 'Norma',
    name: 'AssistFollowUpTechnologicalSuppression_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpTechnologicalSuppression_0_daze',
    },
  },
  AssistFollowUpTechnologicalSuppression_0_anomBuildup: {
    sheet: 'Norma',
    name: 'AssistFollowUpTechnologicalSuppression_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Norma',
      attribute: 'fire',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpTechnologicalSuppression_0_anomBuildup',
    },
  },
} as const
