// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'AstraYao',
    name: 'standardDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'AstraYao',
      attribute: 'ether',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'AstraYao',
    name: 'anomalyDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'AstraYao',
      attribute: 'ether',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_ether: {
    sheet: 'AstraYao',
    name: 'disorderDmgInst_ether',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'AstraYao',
      attribute: 'ether',
      damageType1: 'disorder',
      name: 'disorderDmgInst_ether',
    },
  },
  vortexDmgInst_ether: {
    sheet: 'AstraYao',
    name: 'vortexDmgInst_ether',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'AstraYao',
      attribute: 'ether',
      damageType1: 'vortex',
      name: 'vortexDmgInst_ether',
    },
  },
  abloomDmgInst: {
    sheet: 'AstraYao',
    name: 'abloomDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'AstraYao',
      attribute: 'ether',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'AstraYao',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'AstraYao',
      attribute: 'ether',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'AstraYao',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'AstraYao',
      attribute: 'ether',
      name: 'dazeInst',
    },
  },
  'BasicAttackCapriccio_0:standardDmg': {
    sheet: 'AstraYao',
    name: 'BasicAttackCapriccio_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'AstraYao',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackCapriccio_0',
    },
  },
  'BasicAttackCapriccio_0:dazeBuildup': {
    sheet: 'AstraYao',
    name: 'BasicAttackCapriccio_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'AstraYao',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackCapriccio_0',
    },
  },
  'BasicAttackCapriccio_0:anomBuildup': {
    sheet: 'AstraYao',
    name: 'BasicAttackCapriccio_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'AstraYao',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackCapriccio_0',
    },
  },
  'BasicAttackCapriccio_1:standardDmg': {
    sheet: 'AstraYao',
    name: 'BasicAttackCapriccio_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'AstraYao',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackCapriccio_1',
    },
  },
  'BasicAttackCapriccio_1:dazeBuildup': {
    sheet: 'AstraYao',
    name: 'BasicAttackCapriccio_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'AstraYao',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackCapriccio_1',
    },
  },
  'BasicAttackCapriccio_1:anomBuildup': {
    sheet: 'AstraYao',
    name: 'BasicAttackCapriccio_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'AstraYao',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackCapriccio_1',
    },
  },
  'BasicAttackCapriccio_2:standardDmg': {
    sheet: 'AstraYao',
    name: 'BasicAttackCapriccio_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'AstraYao',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackCapriccio_2',
    },
  },
  'BasicAttackCapriccio_2:dazeBuildup': {
    sheet: 'AstraYao',
    name: 'BasicAttackCapriccio_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'AstraYao',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackCapriccio_2',
    },
  },
  'BasicAttackCapriccio_2:anomBuildup': {
    sheet: 'AstraYao',
    name: 'BasicAttackCapriccio_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'AstraYao',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackCapriccio_2',
    },
  },
  'BasicAttackCapriccio_3:standardDmg': {
    sheet: 'AstraYao',
    name: 'BasicAttackCapriccio_3:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'AstraYao',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackCapriccio_3',
    },
  },
  'BasicAttackCapriccio_3:dazeBuildup': {
    sheet: 'AstraYao',
    name: 'BasicAttackCapriccio_3:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'AstraYao',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackCapriccio_3',
    },
  },
  'BasicAttackCapriccio_3:anomBuildup': {
    sheet: 'AstraYao',
    name: 'BasicAttackCapriccio_3:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'AstraYao',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackCapriccio_3',
    },
  },
  'BasicAttackInterlude_0:standardDmg': {
    sheet: 'AstraYao',
    name: 'BasicAttackInterlude_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'AstraYao',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackInterlude_0',
    },
  },
  'BasicAttackInterlude_0:dazeBuildup': {
    sheet: 'AstraYao',
    name: 'BasicAttackInterlude_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'AstraYao',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackInterlude_0',
    },
  },
  'BasicAttackInterlude_0:anomBuildup': {
    sheet: 'AstraYao',
    name: 'BasicAttackInterlude_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'AstraYao',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackInterlude_0',
    },
  },
  'BasicAttackChorus_0:standardDmg': {
    sheet: 'AstraYao',
    name: 'BasicAttackChorus_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'AstraYao',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackChorus_0',
    },
  },
  'BasicAttackChorus_0:dazeBuildup': {
    sheet: 'AstraYao',
    name: 'BasicAttackChorus_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'AstraYao',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackChorus_0',
    },
  },
  'BasicAttackChorus_0:anomBuildup': {
    sheet: 'AstraYao',
    name: 'BasicAttackChorus_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'AstraYao',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackChorus_0',
    },
  },
  'BasicAttackFinale_0:standardDmg': {
    sheet: 'AstraYao',
    name: 'BasicAttackFinale_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'AstraYao',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFinale_0',
    },
  },
  'BasicAttackFinale_0:dazeBuildup': {
    sheet: 'AstraYao',
    name: 'BasicAttackFinale_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'AstraYao',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFinale_0',
    },
  },
  'BasicAttackFinale_0:anomBuildup': {
    sheet: 'AstraYao',
    name: 'BasicAttackFinale_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'AstraYao',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFinale_0',
    },
  },
  'DashAttackLunarEclipseMelody_0:standardDmg': {
    sheet: 'AstraYao',
    name: 'DashAttackLunarEclipseMelody_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'AstraYao',
      attribute: 'ether',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackLunarEclipseMelody_0',
    },
  },
  'DashAttackLunarEclipseMelody_0:dazeBuildup': {
    sheet: 'AstraYao',
    name: 'DashAttackLunarEclipseMelody_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'AstraYao',
      attribute: 'ether',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackLunarEclipseMelody_0',
    },
  },
  'DashAttackLunarEclipseMelody_0:anomBuildup': {
    sheet: 'AstraYao',
    name: 'DashAttackLunarEclipseMelody_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'AstraYao',
      attribute: 'ether',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackLunarEclipseMelody_0',
    },
  },
  'DodgeCounterUmbrellaWaltz_0:standardDmg': {
    sheet: 'AstraYao',
    name: 'DodgeCounterUmbrellaWaltz_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'AstraYao',
      attribute: 'ether',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterUmbrellaWaltz_0',
    },
  },
  'DodgeCounterUmbrellaWaltz_0:dazeBuildup': {
    sheet: 'AstraYao',
    name: 'DodgeCounterUmbrellaWaltz_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'AstraYao',
      attribute: 'ether',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterUmbrellaWaltz_0',
    },
  },
  'DodgeCounterUmbrellaWaltz_0:anomBuildup': {
    sheet: 'AstraYao',
    name: 'DodgeCounterUmbrellaWaltz_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'AstraYao',
      attribute: 'ether',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterUmbrellaWaltz_0',
    },
  },
  'SpecialAttackWindchimesOaths_0:standardDmg': {
    sheet: 'AstraYao',
    name: 'SpecialAttackWindchimesOaths_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'AstraYao',
      attribute: 'ether',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackWindchimesOaths_0',
    },
  },
  'SpecialAttackWindchimesOaths_0:dazeBuildup': {
    sheet: 'AstraYao',
    name: 'SpecialAttackWindchimesOaths_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'AstraYao',
      attribute: 'ether',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackWindchimesOaths_0',
    },
  },
  'SpecialAttackWindchimesOaths_0:anomBuildup': {
    sheet: 'AstraYao',
    name: 'SpecialAttackWindchimesOaths_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'AstraYao',
      attribute: 'ether',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackWindchimesOaths_0',
    },
  },
  'Chord_0:standardDmg': {
    sheet: 'AstraYao',
    name: 'Chord_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'AstraYao',
      attribute: 'ether',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'Chord_0',
    },
  },
  'Chord_0:dazeBuildup': {
    sheet: 'AstraYao',
    name: 'Chord_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'AstraYao',
      attribute: 'ether',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'Chord_0',
    },
  },
  'Chord_0:anomBuildup': {
    sheet: 'AstraYao',
    name: 'Chord_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'AstraYao',
      attribute: 'ether',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'Chord_0',
    },
  },
  'Chord_1:standardDmg': {
    sheet: 'AstraYao',
    name: 'Chord_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'AstraYao',
      attribute: 'ether',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'Chord_1',
    },
  },
  'Chord_1:dazeBuildup': {
    sheet: 'AstraYao',
    name: 'Chord_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'AstraYao',
      attribute: 'ether',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'Chord_1',
    },
  },
  'Chord_1:anomBuildup': {
    sheet: 'AstraYao',
    name: 'Chord_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'AstraYao',
      attribute: 'ether',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'Chord_1',
    },
  },
  'ChainAttackTipsyConcerto_0:standardDmg': {
    sheet: 'AstraYao',
    name: 'ChainAttackTipsyConcerto_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'AstraYao',
      attribute: 'ether',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackTipsyConcerto_0',
    },
  },
  'ChainAttackTipsyConcerto_0:dazeBuildup': {
    sheet: 'AstraYao',
    name: 'ChainAttackTipsyConcerto_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'AstraYao',
      attribute: 'ether',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackTipsyConcerto_0',
    },
  },
  'ChainAttackTipsyConcerto_0:anomBuildup': {
    sheet: 'AstraYao',
    name: 'ChainAttackTipsyConcerto_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'AstraYao',
      attribute: 'ether',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackTipsyConcerto_0',
    },
  },
  'UltimateFantasianSonata_0:standardDmg': {
    sheet: 'AstraYao',
    name: 'UltimateFantasianSonata_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'AstraYao',
      attribute: 'ether',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateFantasianSonata_0',
    },
  },
  'UltimateFantasianSonata_0:dazeBuildup': {
    sheet: 'AstraYao',
    name: 'UltimateFantasianSonata_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'AstraYao',
      attribute: 'ether',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateFantasianSonata_0',
    },
  },
  'UltimateFantasianSonata_0:anomBuildup': {
    sheet: 'AstraYao',
    name: 'UltimateFantasianSonata_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'AstraYao',
      attribute: 'ether',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateFantasianSonata_0',
    },
  },
  'QuickAssistOneLuminousSky_0:standardDmg': {
    sheet: 'AstraYao',
    name: 'QuickAssistOneLuminousSky_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'AstraYao',
      attribute: 'ether',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistOneLuminousSky_0',
    },
  },
  'QuickAssistOneLuminousSky_0:dazeBuildup': {
    sheet: 'AstraYao',
    name: 'QuickAssistOneLuminousSky_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'AstraYao',
      attribute: 'ether',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistOneLuminousSky_0',
    },
  },
  'QuickAssistOneLuminousSky_0:anomBuildup': {
    sheet: 'AstraYao',
    name: 'QuickAssistOneLuminousSky_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'AstraYao',
      attribute: 'ether',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistOneLuminousSky_0',
    },
  },
  'AssistFollowUpThreeLifetimesOfFate_0:standardDmg': {
    sheet: 'AstraYao',
    name: 'AssistFollowUpThreeLifetimesOfFate_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'AstraYao',
      attribute: 'ether',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpThreeLifetimesOfFate_0',
    },
  },
  'AssistFollowUpThreeLifetimesOfFate_0:dazeBuildup': {
    sheet: 'AstraYao',
    name: 'AssistFollowUpThreeLifetimesOfFate_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'AstraYao',
      attribute: 'ether',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpThreeLifetimesOfFate_0',
    },
  },
  'AssistFollowUpThreeLifetimesOfFate_0:anomBuildup': {
    sheet: 'AstraYao',
    name: 'AssistFollowUpThreeLifetimesOfFate_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'AstraYao',
      attribute: 'ether',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpThreeLifetimesOfFate_0',
    },
  },
  ultimate_heal: {
    sheet: 'AstraYao',
    name: 'ultimate_heal',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'heal',
      sheet: 'AstraYao',
      name: 'ultimate_heal',
    },
  },
} as const
