// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Zhao',
    name: 'standardDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'standardDmgBase',
      sheet: 'Zhao',
      attribute: 'ice',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Zhao',
    name: 'anomalyDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_ice: {
    sheet: 'Zhao',
    name: 'disorderDmgInst_ice',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'disorder',
      name: 'disorderDmgInst_ice',
    },
  },
  vortexDmgInst_ice: {
    sheet: 'Zhao',
    name: 'vortexDmgInst_ice',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'vortex',
      name: 'vortexDmgInst_ice',
    },
  },
  abloomDmgInst: {
    sheet: 'Zhao',
    name: 'abloomDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Zhao',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Zhao',
      attribute: 'ice',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Zhao',
    name: 'dazeInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'dazeBuildupBase',
      sheet: 'Zhao',
      attribute: 'ice',
      name: 'dazeInst',
    },
  },
  BasicAttackGlacialJudgment_0: {
    sheet: 'Zhao',
    name: 'BasicAttackGlacialJudgment_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackGlacialJudgment_0',
    },
  },
  BasicAttackGlacialJudgment_1: {
    sheet: 'Zhao',
    name: 'BasicAttackGlacialJudgment_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackGlacialJudgment_1',
    },
  },
  BasicAttackGlacialJudgment_2: {
    sheet: 'Zhao',
    name: 'BasicAttackGlacialJudgment_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackGlacialJudgment_2',
    },
  },
  BasicAttackGlacialJudgment_3: {
    sheet: 'Zhao',
    name: 'BasicAttackGlacialJudgment_3',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackGlacialJudgment_3',
    },
  },
  BasicAttackGlacialJudgment_4: {
    sheet: 'Zhao',
    name: 'BasicAttackGlacialJudgment_4',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackGlacialJudgment_4',
    },
  },
  BasicAttackGlacialJudgment_5: {
    sheet: 'Zhao',
    name: 'BasicAttackGlacialJudgment_5',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackGlacialJudgment_5',
    },
  },
  BasicAttackFinalVerdict_0: {
    sheet: 'Zhao',
    name: 'BasicAttackFinalVerdict_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFinalVerdict_0',
    },
  },
  DashAttackBouncingDash_0: {
    sheet: 'Zhao',
    name: 'DashAttackBouncingDash_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackBouncingDash_0',
    },
  },
  DodgeCounterSwiftBlink_0: {
    sheet: 'Zhao',
    name: 'DodgeCounterSwiftBlink_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterSwiftBlink_0',
    },
  },
  SpecialAttackShatterfrostSurge_0: {
    sheet: 'Zhao',
    name: 'SpecialAttackShatterfrostSurge_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackShatterfrostSurge_0',
    },
  },
  EXSpecialAttackFrostflowTundra_0: {
    sheet: 'Zhao',
    name: 'EXSpecialAttackFrostflowTundra_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackFrostflowTundra_0',
    },
  },
  ChainAttackTemporaryAlliance_0: {
    sheet: 'Zhao',
    name: 'ChainAttackTemporaryAlliance_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackTemporaryAlliance_0',
    },
  },
  UltimateBunnyBarrage_0: {
    sheet: 'Zhao',
    name: 'UltimateBunnyBarrage_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateBunnyBarrage_0',
    },
  },
  UltimateBunnyBarrage_1: {
    sheet: 'Zhao',
    name: 'UltimateBunnyBarrage_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateBunnyBarrage_1',
    },
  },
  EntrySkillBurstOfFrost_0: {
    sheet: 'Zhao',
    name: 'EntrySkillBurstOfFrost_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'entrySkill',
      skillType: 'assistSkill',
      name: 'EntrySkillBurstOfFrost_0',
    },
  },
  QuickAssistPatchTheGaps_0: {
    sheet: 'Zhao',
    name: 'QuickAssistPatchTheGaps_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistPatchTheGaps_0',
    },
  },
  DefensiveAssistFrostveilSuppression_0: {
    sheet: 'Zhao',
    name: 'DefensiveAssistFrostveilSuppression_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistFrostveilSuppression_0',
    },
  },
  DefensiveAssistFrostveilSuppression_1: {
    sheet: 'Zhao',
    name: 'DefensiveAssistFrostveilSuppression_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistFrostveilSuppression_1',
    },
  },
  DefensiveAssistFrostveilSuppression_2: {
    sheet: 'Zhao',
    name: 'DefensiveAssistFrostveilSuppression_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistFrostveilSuppression_2',
    },
  },
  AssistFollowUpFrostlightReflection_0: {
    sheet: 'Zhao',
    name: 'AssistFollowUpFrostlightReflection_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpFrostlightReflection_0',
    },
  },
} as const
