// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Zhao',
    name: 'standardDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Zhao',
      attribute: 'ice',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Zhao',
    name: 'anomalyDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_ice: {
    sheet: 'Zhao',
    name: 'disorderDmgInst_ice',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'disorder',
      name: 'disorderDmgInst_ice',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Zhao',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Zhao',
      attribute: 'ice',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Zhao',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Zhao',
      attribute: 'ice',
      name: 'dazeInst',
    },
  },
  BasicAttackGlacialJudgment_0_dmg: {
    sheet: 'Zhao',
    name: 'BasicAttackGlacialJudgment_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackGlacialJudgment_0_dmg',
    },
  },
  BasicAttackGlacialJudgment_0_daze: {
    sheet: 'Zhao',
    name: 'BasicAttackGlacialJudgment_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackGlacialJudgment_0_daze',
    },
  },
  BasicAttackGlacialJudgment_0_anomBuildup: {
    sheet: 'Zhao',
    name: 'BasicAttackGlacialJudgment_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackGlacialJudgment_0_anomBuildup',
    },
  },
  BasicAttackGlacialJudgment_1_dmg: {
    sheet: 'Zhao',
    name: 'BasicAttackGlacialJudgment_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackGlacialJudgment_1_dmg',
    },
  },
  BasicAttackGlacialJudgment_1_daze: {
    sheet: 'Zhao',
    name: 'BasicAttackGlacialJudgment_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackGlacialJudgment_1_daze',
    },
  },
  BasicAttackGlacialJudgment_1_anomBuildup: {
    sheet: 'Zhao',
    name: 'BasicAttackGlacialJudgment_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackGlacialJudgment_1_anomBuildup',
    },
  },
  BasicAttackGlacialJudgment_2_dmg: {
    sheet: 'Zhao',
    name: 'BasicAttackGlacialJudgment_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackGlacialJudgment_2_dmg',
    },
  },
  BasicAttackGlacialJudgment_2_daze: {
    sheet: 'Zhao',
    name: 'BasicAttackGlacialJudgment_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackGlacialJudgment_2_daze',
    },
  },
  BasicAttackGlacialJudgment_2_anomBuildup: {
    sheet: 'Zhao',
    name: 'BasicAttackGlacialJudgment_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackGlacialJudgment_2_anomBuildup',
    },
  },
  BasicAttackGlacialJudgment_3_dmg: {
    sheet: 'Zhao',
    name: 'BasicAttackGlacialJudgment_3_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackGlacialJudgment_3_dmg',
    },
  },
  BasicAttackGlacialJudgment_3_daze: {
    sheet: 'Zhao',
    name: 'BasicAttackGlacialJudgment_3_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackGlacialJudgment_3_daze',
    },
  },
  BasicAttackGlacialJudgment_3_anomBuildup: {
    sheet: 'Zhao',
    name: 'BasicAttackGlacialJudgment_3_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackGlacialJudgment_3_anomBuildup',
    },
  },
  BasicAttackGlacialJudgment_4_dmg: {
    sheet: 'Zhao',
    name: 'BasicAttackGlacialJudgment_4_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackGlacialJudgment_4_dmg',
    },
  },
  BasicAttackGlacialJudgment_4_daze: {
    sheet: 'Zhao',
    name: 'BasicAttackGlacialJudgment_4_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackGlacialJudgment_4_daze',
    },
  },
  BasicAttackGlacialJudgment_4_anomBuildup: {
    sheet: 'Zhao',
    name: 'BasicAttackGlacialJudgment_4_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackGlacialJudgment_4_anomBuildup',
    },
  },
  BasicAttackGlacialJudgment_5_dmg: {
    sheet: 'Zhao',
    name: 'BasicAttackGlacialJudgment_5_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackGlacialJudgment_5_dmg',
    },
  },
  BasicAttackGlacialJudgment_5_daze: {
    sheet: 'Zhao',
    name: 'BasicAttackGlacialJudgment_5_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackGlacialJudgment_5_daze',
    },
  },
  BasicAttackGlacialJudgment_5_anomBuildup: {
    sheet: 'Zhao',
    name: 'BasicAttackGlacialJudgment_5_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackGlacialJudgment_5_anomBuildup',
    },
  },
  BasicAttackFinalVerdict_0_dmg: {
    sheet: 'Zhao',
    name: 'BasicAttackFinalVerdict_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFinalVerdict_0_dmg',
    },
  },
  BasicAttackFinalVerdict_0_daze: {
    sheet: 'Zhao',
    name: 'BasicAttackFinalVerdict_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFinalVerdict_0_daze',
    },
  },
  BasicAttackFinalVerdict_0_anomBuildup: {
    sheet: 'Zhao',
    name: 'BasicAttackFinalVerdict_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFinalVerdict_0_anomBuildup',
    },
  },
  DashAttackBouncingDash_0_dmg: {
    sheet: 'Zhao',
    name: 'DashAttackBouncingDash_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackBouncingDash_0_dmg',
    },
  },
  DashAttackBouncingDash_0_daze: {
    sheet: 'Zhao',
    name: 'DashAttackBouncingDash_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackBouncingDash_0_daze',
    },
  },
  DashAttackBouncingDash_0_anomBuildup: {
    sheet: 'Zhao',
    name: 'DashAttackBouncingDash_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackBouncingDash_0_anomBuildup',
    },
  },
  DodgeCounterSwiftBlink_0_dmg: {
    sheet: 'Zhao',
    name: 'DodgeCounterSwiftBlink_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterSwiftBlink_0_dmg',
    },
  },
  DodgeCounterSwiftBlink_0_daze: {
    sheet: 'Zhao',
    name: 'DodgeCounterSwiftBlink_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterSwiftBlink_0_daze',
    },
  },
  DodgeCounterSwiftBlink_0_anomBuildup: {
    sheet: 'Zhao',
    name: 'DodgeCounterSwiftBlink_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterSwiftBlink_0_anomBuildup',
    },
  },
  SpecialAttackShatterfrostSurge_0_dmg: {
    sheet: 'Zhao',
    name: 'SpecialAttackShatterfrostSurge_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackShatterfrostSurge_0_dmg',
    },
  },
  SpecialAttackShatterfrostSurge_0_daze: {
    sheet: 'Zhao',
    name: 'SpecialAttackShatterfrostSurge_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackShatterfrostSurge_0_daze',
    },
  },
  SpecialAttackShatterfrostSurge_0_anomBuildup: {
    sheet: 'Zhao',
    name: 'SpecialAttackShatterfrostSurge_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackShatterfrostSurge_0_anomBuildup',
    },
  },
  EXSpecialAttackFrostflowTundra_0_dmg: {
    sheet: 'Zhao',
    name: 'EXSpecialAttackFrostflowTundra_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackFrostflowTundra_0_dmg',
    },
  },
  EXSpecialAttackFrostflowTundra_0_daze: {
    sheet: 'Zhao',
    name: 'EXSpecialAttackFrostflowTundra_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackFrostflowTundra_0_daze',
    },
  },
  EXSpecialAttackFrostflowTundra_0_anomBuildup: {
    sheet: 'Zhao',
    name: 'EXSpecialAttackFrostflowTundra_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackFrostflowTundra_0_anomBuildup',
    },
  },
  ChainAttackTemporaryAlliance_0_dmg: {
    sheet: 'Zhao',
    name: 'ChainAttackTemporaryAlliance_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackTemporaryAlliance_0_dmg',
    },
  },
  ChainAttackTemporaryAlliance_0_daze: {
    sheet: 'Zhao',
    name: 'ChainAttackTemporaryAlliance_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackTemporaryAlliance_0_daze',
    },
  },
  ChainAttackTemporaryAlliance_0_anomBuildup: {
    sheet: 'Zhao',
    name: 'ChainAttackTemporaryAlliance_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackTemporaryAlliance_0_anomBuildup',
    },
  },
  UltimateBunnyBarrage_0_dmg: {
    sheet: 'Zhao',
    name: 'UltimateBunnyBarrage_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateBunnyBarrage_0_dmg',
    },
  },
  UltimateBunnyBarrage_0_daze: {
    sheet: 'Zhao',
    name: 'UltimateBunnyBarrage_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateBunnyBarrage_0_daze',
    },
  },
  UltimateBunnyBarrage_0_anomBuildup: {
    sheet: 'Zhao',
    name: 'UltimateBunnyBarrage_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateBunnyBarrage_0_anomBuildup',
    },
  },
  UltimateBunnyBarrage_1_dmg: {
    sheet: 'Zhao',
    name: 'UltimateBunnyBarrage_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateBunnyBarrage_1_dmg',
    },
  },
  UltimateBunnyBarrage_1_daze: {
    sheet: 'Zhao',
    name: 'UltimateBunnyBarrage_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateBunnyBarrage_1_daze',
    },
  },
  UltimateBunnyBarrage_1_anomBuildup: {
    sheet: 'Zhao',
    name: 'UltimateBunnyBarrage_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateBunnyBarrage_1_anomBuildup',
    },
  },
  EntrySkillBurstOfFrost_0_dmg: {
    sheet: 'Zhao',
    name: 'EntrySkillBurstOfFrost_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'entrySkill',
      skillType: 'assistSkill',
      name: 'EntrySkillBurstOfFrost_0_dmg',
    },
  },
  EntrySkillBurstOfFrost_0_daze: {
    sheet: 'Zhao',
    name: 'EntrySkillBurstOfFrost_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'entrySkill',
      skillType: 'assistSkill',
      name: 'EntrySkillBurstOfFrost_0_daze',
    },
  },
  EntrySkillBurstOfFrost_0_anomBuildup: {
    sheet: 'Zhao',
    name: 'EntrySkillBurstOfFrost_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'entrySkill',
      skillType: 'assistSkill',
      name: 'EntrySkillBurstOfFrost_0_anomBuildup',
    },
  },
  QuickAssistPatchTheGaps_0_dmg: {
    sheet: 'Zhao',
    name: 'QuickAssistPatchTheGaps_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistPatchTheGaps_0_dmg',
    },
  },
  QuickAssistPatchTheGaps_0_daze: {
    sheet: 'Zhao',
    name: 'QuickAssistPatchTheGaps_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistPatchTheGaps_0_daze',
    },
  },
  QuickAssistPatchTheGaps_0_anomBuildup: {
    sheet: 'Zhao',
    name: 'QuickAssistPatchTheGaps_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistPatchTheGaps_0_anomBuildup',
    },
  },
  DefensiveAssistFrostveilSuppression_0_dmg: {
    sheet: 'Zhao',
    name: 'DefensiveAssistFrostveilSuppression_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistFrostveilSuppression_0_dmg',
    },
  },
  DefensiveAssistFrostveilSuppression_0_daze: {
    sheet: 'Zhao',
    name: 'DefensiveAssistFrostveilSuppression_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistFrostveilSuppression_0_daze',
    },
  },
  DefensiveAssistFrostveilSuppression_0_anomBuildup: {
    sheet: 'Zhao',
    name: 'DefensiveAssistFrostveilSuppression_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistFrostveilSuppression_0_anomBuildup',
    },
  },
  DefensiveAssistFrostveilSuppression_1_dmg: {
    sheet: 'Zhao',
    name: 'DefensiveAssistFrostveilSuppression_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistFrostveilSuppression_1_dmg',
    },
  },
  DefensiveAssistFrostveilSuppression_1_daze: {
    sheet: 'Zhao',
    name: 'DefensiveAssistFrostveilSuppression_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistFrostveilSuppression_1_daze',
    },
  },
  DefensiveAssistFrostveilSuppression_1_anomBuildup: {
    sheet: 'Zhao',
    name: 'DefensiveAssistFrostveilSuppression_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistFrostveilSuppression_1_anomBuildup',
    },
  },
  DefensiveAssistFrostveilSuppression_2_dmg: {
    sheet: 'Zhao',
    name: 'DefensiveAssistFrostveilSuppression_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistFrostveilSuppression_2_dmg',
    },
  },
  DefensiveAssistFrostveilSuppression_2_daze: {
    sheet: 'Zhao',
    name: 'DefensiveAssistFrostveilSuppression_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistFrostveilSuppression_2_daze',
    },
  },
  DefensiveAssistFrostveilSuppression_2_anomBuildup: {
    sheet: 'Zhao',
    name: 'DefensiveAssistFrostveilSuppression_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistFrostveilSuppression_2_anomBuildup',
    },
  },
  AssistFollowUpFrostlightReflection_0_dmg: {
    sheet: 'Zhao',
    name: 'AssistFollowUpFrostlightReflection_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpFrostlightReflection_0_dmg',
    },
  },
  AssistFollowUpFrostlightReflection_0_daze: {
    sheet: 'Zhao',
    name: 'AssistFollowUpFrostlightReflection_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpFrostlightReflection_0_daze',
    },
  },
  AssistFollowUpFrostlightReflection_0_anomBuildup: {
    sheet: 'Zhao',
    name: 'AssistFollowUpFrostlightReflection_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Zhao',
      attribute: 'ice',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpFrostlightReflection_0_anomBuildup',
    },
  },
} as const
