// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'NangongYu',
    name: 'standardDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'NangongYu',
      attribute: 'ether',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'NangongYu',
    name: 'anomalyDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_ether: {
    sheet: 'NangongYu',
    name: 'disorderDmgInst_ether',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'disorder',
      name: 'disorderDmgInst_ether',
    },
  },
  vortexDmgInst_ether: {
    sheet: 'NangongYu',
    name: 'vortexDmgInst_ether',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'vortex',
      name: 'vortexDmgInst_ether',
    },
  },
  abloomDmgInst: {
    sheet: 'NangongYu',
    name: 'abloomDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'NangongYu',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'NangongYu',
      attribute: 'ether',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'NangongYu',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'NangongYu',
      attribute: 'ether',
      name: 'dazeInst',
    },
  },
  BasicAttackShootingStarStep_0_dmg: {
    sheet: 'NangongYu',
    name: 'BasicAttackShootingStarStep_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackShootingStarStep_0_dmg',
    },
  },
  BasicAttackShootingStarStep_0_daze: {
    sheet: 'NangongYu',
    name: 'BasicAttackShootingStarStep_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackShootingStarStep_0_daze',
    },
  },
  BasicAttackShootingStarStep_0_anomBuildup: {
    sheet: 'NangongYu',
    name: 'BasicAttackShootingStarStep_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackShootingStarStep_0_anomBuildup',
    },
  },
  BasicAttackShootingStarStep_1_dmg: {
    sheet: 'NangongYu',
    name: 'BasicAttackShootingStarStep_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackShootingStarStep_1_dmg',
    },
  },
  BasicAttackShootingStarStep_1_daze: {
    sheet: 'NangongYu',
    name: 'BasicAttackShootingStarStep_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackShootingStarStep_1_daze',
    },
  },
  BasicAttackShootingStarStep_1_anomBuildup: {
    sheet: 'NangongYu',
    name: 'BasicAttackShootingStarStep_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackShootingStarStep_1_anomBuildup',
    },
  },
  BasicAttackShootingStarStep_2_dmg: {
    sheet: 'NangongYu',
    name: 'BasicAttackShootingStarStep_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackShootingStarStep_2_dmg',
    },
  },
  BasicAttackShootingStarStep_2_daze: {
    sheet: 'NangongYu',
    name: 'BasicAttackShootingStarStep_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackShootingStarStep_2_daze',
    },
  },
  BasicAttackShootingStarStep_2_anomBuildup: {
    sheet: 'NangongYu',
    name: 'BasicAttackShootingStarStep_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackShootingStarStep_2_anomBuildup',
    },
  },
  BasicAttackAdorableExplosiveImpact_0_dmg: {
    sheet: 'NangongYu',
    name: 'BasicAttackAdorableExplosiveImpact_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackAdorableExplosiveImpact_0_dmg',
    },
  },
  BasicAttackAdorableExplosiveImpact_0_daze: {
    sheet: 'NangongYu',
    name: 'BasicAttackAdorableExplosiveImpact_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackAdorableExplosiveImpact_0_daze',
    },
  },
  BasicAttackAdorableExplosiveImpact_0_anomBuildup: {
    sheet: 'NangongYu',
    name: 'BasicAttackAdorableExplosiveImpact_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackAdorableExplosiveImpact_0_anomBuildup',
    },
  },
  BasicAttackAdorableExplosiveImpact_1_dmg: {
    sheet: 'NangongYu',
    name: 'BasicAttackAdorableExplosiveImpact_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackAdorableExplosiveImpact_1_dmg',
    },
  },
  BasicAttackAdorableExplosiveImpact_1_daze: {
    sheet: 'NangongYu',
    name: 'BasicAttackAdorableExplosiveImpact_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackAdorableExplosiveImpact_1_daze',
    },
  },
  BasicAttackAdorableExplosiveImpact_1_anomBuildup: {
    sheet: 'NangongYu',
    name: 'BasicAttackAdorableExplosiveImpact_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackAdorableExplosiveImpact_1_anomBuildup',
    },
  },
  BasicAttackAdorableExplosiveImpact_2_dmg: {
    sheet: 'NangongYu',
    name: 'BasicAttackAdorableExplosiveImpact_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackAdorableExplosiveImpact_2_dmg',
    },
  },
  BasicAttackAdorableExplosiveImpact_2_daze: {
    sheet: 'NangongYu',
    name: 'BasicAttackAdorableExplosiveImpact_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackAdorableExplosiveImpact_2_daze',
    },
  },
  BasicAttackAdorableExplosiveImpact_2_anomBuildup: {
    sheet: 'NangongYu',
    name: 'BasicAttackAdorableExplosiveImpact_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackAdorableExplosiveImpact_2_anomBuildup',
    },
  },
  BasicAttackAdorableExplosiveImpact_3_dmg: {
    sheet: 'NangongYu',
    name: 'BasicAttackAdorableExplosiveImpact_3_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackAdorableExplosiveImpact_3_dmg',
    },
  },
  BasicAttackAdorableExplosiveImpact_3_daze: {
    sheet: 'NangongYu',
    name: 'BasicAttackAdorableExplosiveImpact_3_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackAdorableExplosiveImpact_3_daze',
    },
  },
  BasicAttackAdorableExplosiveImpact_3_anomBuildup: {
    sheet: 'NangongYu',
    name: 'BasicAttackAdorableExplosiveImpact_3_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackAdorableExplosiveImpact_3_anomBuildup',
    },
  },
  DashAttackSpinningMeteor_0_dmg: {
    sheet: 'NangongYu',
    name: 'DashAttackSpinningMeteor_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackSpinningMeteor_0_dmg',
    },
  },
  DashAttackSpinningMeteor_0_daze: {
    sheet: 'NangongYu',
    name: 'DashAttackSpinningMeteor_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackSpinningMeteor_0_daze',
    },
  },
  DashAttackSpinningMeteor_0_anomBuildup: {
    sheet: 'NangongYu',
    name: 'DashAttackSpinningMeteor_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackSpinningMeteor_0_anomBuildup',
    },
  },
  DodgeCounterAsteroidWaltz_0_dmg: {
    sheet: 'NangongYu',
    name: 'DodgeCounterAsteroidWaltz_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterAsteroidWaltz_0_dmg',
    },
  },
  DodgeCounterAsteroidWaltz_0_daze: {
    sheet: 'NangongYu',
    name: 'DodgeCounterAsteroidWaltz_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterAsteroidWaltz_0_daze',
    },
  },
  DodgeCounterAsteroidWaltz_0_anomBuildup: {
    sheet: 'NangongYu',
    name: 'DodgeCounterAsteroidWaltz_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterAsteroidWaltz_0_anomBuildup',
    },
  },
  SpecialAttackTheWeightOfLove_0_dmg: {
    sheet: 'NangongYu',
    name: 'SpecialAttackTheWeightOfLove_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackTheWeightOfLove_0_dmg',
    },
  },
  SpecialAttackTheWeightOfLove_0_daze: {
    sheet: 'NangongYu',
    name: 'SpecialAttackTheWeightOfLove_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackTheWeightOfLove_0_daze',
    },
  },
  SpecialAttackTheWeightOfLove_0_anomBuildup: {
    sheet: 'NangongYu',
    name: 'SpecialAttackTheWeightOfLove_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackTheWeightOfLove_0_anomBuildup',
    },
  },
  EXSpecialAttackTheUnbearableWeightOfLove_0_dmg: {
    sheet: 'NangongYu',
    name: 'EXSpecialAttackTheUnbearableWeightOfLove_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackTheUnbearableWeightOfLove_0_dmg',
    },
  },
  EXSpecialAttackTheUnbearableWeightOfLove_0_daze: {
    sheet: 'NangongYu',
    name: 'EXSpecialAttackTheUnbearableWeightOfLove_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackTheUnbearableWeightOfLove_0_daze',
    },
  },
  EXSpecialAttackTheUnbearableWeightOfLove_0_anomBuildup: {
    sheet: 'NangongYu',
    name: 'EXSpecialAttackTheUnbearableWeightOfLove_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackTheUnbearableWeightOfLove_0_anomBuildup',
    },
  },
  ChainAttackCometGravity_0_dmg: {
    sheet: 'NangongYu',
    name: 'ChainAttackCometGravity_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackCometGravity_0_dmg',
    },
  },
  ChainAttackCometGravity_0_daze: {
    sheet: 'NangongYu',
    name: 'ChainAttackCometGravity_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackCometGravity_0_daze',
    },
  },
  ChainAttackCometGravity_0_anomBuildup: {
    sheet: 'NangongYu',
    name: 'ChainAttackCometGravity_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackCometGravity_0_anomBuildup',
    },
  },
  UltimateMeteorShower_0_dmg: {
    sheet: 'NangongYu',
    name: 'UltimateMeteorShower_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateMeteorShower_0_dmg',
    },
  },
  UltimateMeteorShower_0_daze: {
    sheet: 'NangongYu',
    name: 'UltimateMeteorShower_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateMeteorShower_0_daze',
    },
  },
  UltimateMeteorShower_0_anomBuildup: {
    sheet: 'NangongYu',
    name: 'UltimateMeteorShower_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateMeteorShower_0_anomBuildup',
    },
  },
  QuickAssistEmergencySave_0_dmg: {
    sheet: 'NangongYu',
    name: 'QuickAssistEmergencySave_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistEmergencySave_0_dmg',
    },
  },
  QuickAssistEmergencySave_0_daze: {
    sheet: 'NangongYu',
    name: 'QuickAssistEmergencySave_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistEmergencySave_0_daze',
    },
  },
  QuickAssistEmergencySave_0_anomBuildup: {
    sheet: 'NangongYu',
    name: 'QuickAssistEmergencySave_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistEmergencySave_0_anomBuildup',
    },
  },
  DefensiveAssistPerfectedChoreography_0_dmg: {
    sheet: 'NangongYu',
    name: 'DefensiveAssistPerfectedChoreography_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistPerfectedChoreography_0_dmg',
    },
  },
  DefensiveAssistPerfectedChoreography_0_daze: {
    sheet: 'NangongYu',
    name: 'DefensiveAssistPerfectedChoreography_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistPerfectedChoreography_0_daze',
    },
  },
  DefensiveAssistPerfectedChoreography_0_anomBuildup: {
    sheet: 'NangongYu',
    name: 'DefensiveAssistPerfectedChoreography_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistPerfectedChoreography_0_anomBuildup',
    },
  },
  DefensiveAssistPerfectedChoreography_1_dmg: {
    sheet: 'NangongYu',
    name: 'DefensiveAssistPerfectedChoreography_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistPerfectedChoreography_1_dmg',
    },
  },
  DefensiveAssistPerfectedChoreography_1_daze: {
    sheet: 'NangongYu',
    name: 'DefensiveAssistPerfectedChoreography_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistPerfectedChoreography_1_daze',
    },
  },
  DefensiveAssistPerfectedChoreography_1_anomBuildup: {
    sheet: 'NangongYu',
    name: 'DefensiveAssistPerfectedChoreography_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistPerfectedChoreography_1_anomBuildup',
    },
  },
  DefensiveAssistPerfectedChoreography_2_dmg: {
    sheet: 'NangongYu',
    name: 'DefensiveAssistPerfectedChoreography_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistPerfectedChoreography_2_dmg',
    },
  },
  DefensiveAssistPerfectedChoreography_2_daze: {
    sheet: 'NangongYu',
    name: 'DefensiveAssistPerfectedChoreography_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistPerfectedChoreography_2_daze',
    },
  },
  DefensiveAssistPerfectedChoreography_2_anomBuildup: {
    sheet: 'NangongYu',
    name: 'DefensiveAssistPerfectedChoreography_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistPerfectedChoreography_2_anomBuildup',
    },
  },
  AssistFollowUpImprovisedPerformance_0_dmg: {
    sheet: 'NangongYu',
    name: 'AssistFollowUpImprovisedPerformance_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpImprovisedPerformance_0_dmg',
    },
  },
  AssistFollowUpImprovisedPerformance_0_daze: {
    sheet: 'NangongYu',
    name: 'AssistFollowUpImprovisedPerformance_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpImprovisedPerformance_0_daze',
    },
  },
  AssistFollowUpImprovisedPerformance_0_anomBuildup: {
    sheet: 'NangongYu',
    name: 'AssistFollowUpImprovisedPerformance_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpImprovisedPerformance_0_anomBuildup',
    },
  },
} as const
