// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'NangongYu',
    name: 'standardDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'standardDmgBase',
      sheet: 'NangongYu',
      attribute: 'ether',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'NangongYu',
    name: 'anomalyDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_ether: {
    sheet: 'NangongYu',
    name: 'disorderDmgInst_ether',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'disorder',
      name: 'disorderDmgInst_ether',
    },
  },
  vortexDmgInst_ether: {
    sheet: 'NangongYu',
    name: 'vortexDmgInst_ether',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'vortex',
      name: 'vortexDmgInst_ether',
    },
  },
  abloomDmgInst: {
    sheet: 'NangongYu',
    name: 'abloomDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'NangongYu',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'NangongYu',
      attribute: 'ether',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'NangongYu',
    name: 'dazeInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'dazeBuildupBase',
      sheet: 'NangongYu',
      attribute: 'ether',
      name: 'dazeInst',
    },
  },
  BasicAttackShootingStarStep_0: {
    sheet: 'NangongYu',
    name: 'BasicAttackShootingStarStep_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackShootingStarStep_0',
    },
  },
  BasicAttackShootingStarStep_1: {
    sheet: 'NangongYu',
    name: 'BasicAttackShootingStarStep_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackShootingStarStep_1',
    },
  },
  BasicAttackShootingStarStep_2: {
    sheet: 'NangongYu',
    name: 'BasicAttackShootingStarStep_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackShootingStarStep_2',
    },
  },
  BasicAttackAdorableExplosiveImpact_0: {
    sheet: 'NangongYu',
    name: 'BasicAttackAdorableExplosiveImpact_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackAdorableExplosiveImpact_0',
    },
  },
  BasicAttackAdorableExplosiveImpact_1: {
    sheet: 'NangongYu',
    name: 'BasicAttackAdorableExplosiveImpact_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackAdorableExplosiveImpact_1',
    },
  },
  BasicAttackAdorableExplosiveImpact_2: {
    sheet: 'NangongYu',
    name: 'BasicAttackAdorableExplosiveImpact_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackAdorableExplosiveImpact_2',
    },
  },
  BasicAttackAdorableExplosiveImpact_3: {
    sheet: 'NangongYu',
    name: 'BasicAttackAdorableExplosiveImpact_3',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackAdorableExplosiveImpact_3',
    },
  },
  DashAttackSpinningMeteor_0: {
    sheet: 'NangongYu',
    name: 'DashAttackSpinningMeteor_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackSpinningMeteor_0',
    },
  },
  DodgeCounterAsteroidWaltz_0: {
    sheet: 'NangongYu',
    name: 'DodgeCounterAsteroidWaltz_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterAsteroidWaltz_0',
    },
  },
  SpecialAttackTheWeightOfLove_0: {
    sheet: 'NangongYu',
    name: 'SpecialAttackTheWeightOfLove_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackTheWeightOfLove_0',
    },
  },
  EXSpecialAttackTheUnbearableWeightOfLove_0: {
    sheet: 'NangongYu',
    name: 'EXSpecialAttackTheUnbearableWeightOfLove_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackTheUnbearableWeightOfLove_0',
    },
  },
  ChainAttackCometGravity_0: {
    sheet: 'NangongYu',
    name: 'ChainAttackCometGravity_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackCometGravity_0',
    },
  },
  UltimateMeteorShower_0: {
    sheet: 'NangongYu',
    name: 'UltimateMeteorShower_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateMeteorShower_0',
    },
  },
  QuickAssistEmergencySave_0: {
    sheet: 'NangongYu',
    name: 'QuickAssistEmergencySave_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistEmergencySave_0',
    },
  },
  DefensiveAssistPerfectedChoreography_0: {
    sheet: 'NangongYu',
    name: 'DefensiveAssistPerfectedChoreography_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistPerfectedChoreography_0',
    },
  },
  DefensiveAssistPerfectedChoreography_1: {
    sheet: 'NangongYu',
    name: 'DefensiveAssistPerfectedChoreography_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistPerfectedChoreography_1',
    },
  },
  DefensiveAssistPerfectedChoreography_2: {
    sheet: 'NangongYu',
    name: 'DefensiveAssistPerfectedChoreography_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistPerfectedChoreography_2',
    },
  },
  AssistFollowUpImprovisedPerformance_0: {
    sheet: 'NangongYu',
    name: 'AssistFollowUpImprovisedPerformance_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'NangongYu',
      attribute: 'ether',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpImprovisedPerformance_0',
    },
  },
} as const
