// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Roxy',
    name: 'standardDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Roxy',
      attribute: 'wind',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Roxy',
    name: 'anomalyDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_wind: {
    sheet: 'Roxy',
    name: 'disorderDmgInst_wind',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'disorder',
      name: 'disorderDmgInst_wind',
    },
  },
  vortexDmgInst_electric: {
    sheet: 'Roxy',
    name: 'vortexDmgInst_electric',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Roxy',
      attribute: 'electric',
      damageType1: 'vortex',
      name: 'vortexDmgInst_electric',
    },
  },
  vortexDmgInst_fire: {
    sheet: 'Roxy',
    name: 'vortexDmgInst_fire',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Roxy',
      attribute: 'fire',
      damageType1: 'vortex',
      name: 'vortexDmgInst_fire',
    },
  },
  vortexDmgInst_ice: {
    sheet: 'Roxy',
    name: 'vortexDmgInst_ice',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Roxy',
      attribute: 'ice',
      damageType1: 'vortex',
      name: 'vortexDmgInst_ice',
    },
  },
  vortexDmgInst_physical: {
    sheet: 'Roxy',
    name: 'vortexDmgInst_physical',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Roxy',
      attribute: 'physical',
      damageType1: 'vortex',
      name: 'vortexDmgInst_physical',
    },
  },
  vortexDmgInst_ether: {
    sheet: 'Roxy',
    name: 'vortexDmgInst_ether',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Roxy',
      attribute: 'ether',
      damageType1: 'vortex',
      name: 'vortexDmgInst_ether',
    },
  },
  vortexDmgInst_frost: {
    sheet: 'Roxy',
    name: 'vortexDmgInst_frost',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Roxy',
      attribute: 'ice',
      damageType1: 'vortex',
      name: 'vortexDmgInst_frost',
    },
  },
  abloomDmgInst: {
    sheet: 'Roxy',
    name: 'abloomDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Roxy',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Roxy',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      name: 'dazeInst',
    },
  },
  'BasicAttackDoStayAWhile_0:standardDmg': {
    sheet: 'Roxy',
    name: 'BasicAttackDoStayAWhile_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackDoStayAWhile_0',
    },
  },
  'BasicAttackDoStayAWhile_0:dazeBuildup': {
    sheet: 'Roxy',
    name: 'BasicAttackDoStayAWhile_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackDoStayAWhile_0',
    },
  },
  'BasicAttackDoStayAWhile_0:anomBuildup': {
    sheet: 'Roxy',
    name: 'BasicAttackDoStayAWhile_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackDoStayAWhile_0',
    },
  },
  'BasicAttackDoStayAWhile_1:standardDmg': {
    sheet: 'Roxy',
    name: 'BasicAttackDoStayAWhile_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackDoStayAWhile_1',
    },
  },
  'BasicAttackDoStayAWhile_1:dazeBuildup': {
    sheet: 'Roxy',
    name: 'BasicAttackDoStayAWhile_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackDoStayAWhile_1',
    },
  },
  'BasicAttackDoStayAWhile_1:anomBuildup': {
    sheet: 'Roxy',
    name: 'BasicAttackDoStayAWhile_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackDoStayAWhile_1',
    },
  },
  'BasicAttackDoStayAWhile_2:standardDmg': {
    sheet: 'Roxy',
    name: 'BasicAttackDoStayAWhile_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackDoStayAWhile_2',
    },
  },
  'BasicAttackDoStayAWhile_2:dazeBuildup': {
    sheet: 'Roxy',
    name: 'BasicAttackDoStayAWhile_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackDoStayAWhile_2',
    },
  },
  'BasicAttackDoStayAWhile_2:anomBuildup': {
    sheet: 'Roxy',
    name: 'BasicAttackDoStayAWhile_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackDoStayAWhile_2',
    },
  },
  'BasicAttackDoStayAWhile_3:standardDmg': {
    sheet: 'Roxy',
    name: 'BasicAttackDoStayAWhile_3:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackDoStayAWhile_3',
    },
  },
  'BasicAttackDoStayAWhile_3:dazeBuildup': {
    sheet: 'Roxy',
    name: 'BasicAttackDoStayAWhile_3:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackDoStayAWhile_3',
    },
  },
  'BasicAttackDoStayAWhile_3:anomBuildup': {
    sheet: 'Roxy',
    name: 'BasicAttackDoStayAWhile_3:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackDoStayAWhile_3',
    },
  },
  'DashAttackForgiveMyRudeness_0:standardDmg': {
    sheet: 'Roxy',
    name: 'DashAttackForgiveMyRudeness_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackForgiveMyRudeness_0',
    },
  },
  'DashAttackForgiveMyRudeness_0:dazeBuildup': {
    sheet: 'Roxy',
    name: 'DashAttackForgiveMyRudeness_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackForgiveMyRudeness_0',
    },
  },
  'DashAttackForgiveMyRudeness_0:anomBuildup': {
    sheet: 'Roxy',
    name: 'DashAttackForgiveMyRudeness_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackForgiveMyRudeness_0',
    },
  },
  'DodgeCounterReturnedCourtesy_0:standardDmg': {
    sheet: 'Roxy',
    name: 'DodgeCounterReturnedCourtesy_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterReturnedCourtesy_0',
    },
  },
  'DodgeCounterReturnedCourtesy_0:dazeBuildup': {
    sheet: 'Roxy',
    name: 'DodgeCounterReturnedCourtesy_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterReturnedCourtesy_0',
    },
  },
  'DodgeCounterReturnedCourtesy_0:anomBuildup': {
    sheet: 'Roxy',
    name: 'DodgeCounterReturnedCourtesy_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterReturnedCourtesy_0',
    },
  },
  'SpecialAttackMuchObliged_0:standardDmg': {
    sheet: 'Roxy',
    name: 'SpecialAttackMuchObliged_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackMuchObliged_0',
    },
  },
  'SpecialAttackMuchObliged_0:dazeBuildup': {
    sheet: 'Roxy',
    name: 'SpecialAttackMuchObliged_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackMuchObliged_0',
    },
  },
  'SpecialAttackMuchObliged_0:anomBuildup': {
    sheet: 'Roxy',
    name: 'SpecialAttackMuchObliged_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackMuchObliged_0',
    },
  },
  'SpecialAttackForgiveMeForNotSeeingYouOff_0:standardDmg': {
    sheet: 'Roxy',
    name: 'SpecialAttackForgiveMeForNotSeeingYouOff_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackForgiveMeForNotSeeingYouOff_0',
    },
  },
  'SpecialAttackForgiveMeForNotSeeingYouOff_0:dazeBuildup': {
    sheet: 'Roxy',
    name: 'SpecialAttackForgiveMeForNotSeeingYouOff_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackForgiveMeForNotSeeingYouOff_0',
    },
  },
  'SpecialAttackForgiveMeForNotSeeingYouOff_0:anomBuildup': {
    sheet: 'Roxy',
    name: 'SpecialAttackForgiveMeForNotSeeingYouOff_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackForgiveMeForNotSeeingYouOff_0',
    },
  },
  'EXSpecialAttackDontCatchAChill_0:standardDmg': {
    sheet: 'Roxy',
    name: 'EXSpecialAttackDontCatchAChill_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackDontCatchAChill_0',
    },
  },
  'EXSpecialAttackDontCatchAChill_0:dazeBuildup': {
    sheet: 'Roxy',
    name: 'EXSpecialAttackDontCatchAChill_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackDontCatchAChill_0',
    },
  },
  'EXSpecialAttackDontCatchAChill_0:anomBuildup': {
    sheet: 'Roxy',
    name: 'EXSpecialAttackDontCatchAChill_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackDontCatchAChill_0',
    },
  },
  'EXSpecialAttackDontCatchAChill_1:standardDmg': {
    sheet: 'Roxy',
    name: 'EXSpecialAttackDontCatchAChill_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackDontCatchAChill_1',
    },
  },
  'EXSpecialAttackDontCatchAChill_1:dazeBuildup': {
    sheet: 'Roxy',
    name: 'EXSpecialAttackDontCatchAChill_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackDontCatchAChill_1',
    },
  },
  'EXSpecialAttackDontCatchAChill_1:anomBuildup': {
    sheet: 'Roxy',
    name: 'EXSpecialAttackDontCatchAChill_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackDontCatchAChill_1',
    },
  },
  'EXSpecialAttackKindlyRestInPeace_0:standardDmg': {
    sheet: 'Roxy',
    name: 'EXSpecialAttackKindlyRestInPeace_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackKindlyRestInPeace_0',
    },
  },
  'EXSpecialAttackKindlyRestInPeace_0:dazeBuildup': {
    sheet: 'Roxy',
    name: 'EXSpecialAttackKindlyRestInPeace_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackKindlyRestInPeace_0',
    },
  },
  'EXSpecialAttackKindlyRestInPeace_0:anomBuildup': {
    sheet: 'Roxy',
    name: 'EXSpecialAttackKindlyRestInPeace_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackKindlyRestInPeace_0',
    },
  },
  'EXSpecialAttackKindlyRestInPeace_1:standardDmg': {
    sheet: 'Roxy',
    name: 'EXSpecialAttackKindlyRestInPeace_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackKindlyRestInPeace_1',
    },
  },
  'EXSpecialAttackKindlyRestInPeace_1:dazeBuildup': {
    sheet: 'Roxy',
    name: 'EXSpecialAttackKindlyRestInPeace_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackKindlyRestInPeace_1',
    },
  },
  'EXSpecialAttackKindlyRestInPeace_1:anomBuildup': {
    sheet: 'Roxy',
    name: 'EXSpecialAttackKindlyRestInPeace_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackKindlyRestInPeace_1',
    },
  },
  'EyeOfTheStorm_0:standardDmg': {
    sheet: 'Roxy',
    name: 'EyeOfTheStorm_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EyeOfTheStorm_0',
    },
  },
  'EyeOfTheStorm_0:dazeBuildup': {
    sheet: 'Roxy',
    name: 'EyeOfTheStorm_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EyeOfTheStorm_0',
    },
  },
  'EyeOfTheStorm_0:anomBuildup': {
    sheet: 'Roxy',
    name: 'EyeOfTheStorm_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EyeOfTheStorm_0',
    },
  },
  'EyeOfTheStorm_1:standardDmg': {
    sheet: 'Roxy',
    name: 'EyeOfTheStorm_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EyeOfTheStorm_1',
    },
  },
  'EyeOfTheStorm_1:dazeBuildup': {
    sheet: 'Roxy',
    name: 'EyeOfTheStorm_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EyeOfTheStorm_1',
    },
  },
  'EyeOfTheStorm_1:anomBuildup': {
    sheet: 'Roxy',
    name: 'EyeOfTheStorm_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EyeOfTheStorm_1',
    },
  },
  'EyeOfTheStorm_2:standardDmg': {
    sheet: 'Roxy',
    name: 'EyeOfTheStorm_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'EyeOfTheStorm_2',
    },
  },
  'EyeOfTheStorm_2:dazeBuildup': {
    sheet: 'Roxy',
    name: 'EyeOfTheStorm_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'EyeOfTheStorm_2',
    },
  },
  'EyeOfTheStorm_2:anomBuildup': {
    sheet: 'Roxy',
    name: 'EyeOfTheStorm_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'EyeOfTheStorm_2',
    },
  },
  'ChainAttackGaleBurialGreatHammer_0:standardDmg': {
    sheet: 'Roxy',
    name: 'ChainAttackGaleBurialGreatHammer_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackGaleBurialGreatHammer_0',
    },
  },
  'ChainAttackGaleBurialGreatHammer_0:dazeBuildup': {
    sheet: 'Roxy',
    name: 'ChainAttackGaleBurialGreatHammer_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackGaleBurialGreatHammer_0',
    },
  },
  'ChainAttackGaleBurialGreatHammer_0:anomBuildup': {
    sheet: 'Roxy',
    name: 'ChainAttackGaleBurialGreatHammer_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackGaleBurialGreatHammer_0',
    },
  },
  'UltimateRequiemForTheNightBurial_0:standardDmg': {
    sheet: 'Roxy',
    name: 'UltimateRequiemForTheNightBurial_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateRequiemForTheNightBurial_0',
    },
  },
  'UltimateRequiemForTheNightBurial_0:dazeBuildup': {
    sheet: 'Roxy',
    name: 'UltimateRequiemForTheNightBurial_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateRequiemForTheNightBurial_0',
    },
  },
  'UltimateRequiemForTheNightBurial_0:anomBuildup': {
    sheet: 'Roxy',
    name: 'UltimateRequiemForTheNightBurial_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateRequiemForTheNightBurial_0',
    },
  },
  'AssistMoreOvertime_0:standardDmg': {
    sheet: 'Roxy',
    name: 'AssistMoreOvertime_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'basic',
      skillType: 'assistSkill',
      name: 'AssistMoreOvertime_0',
    },
  },
  'AssistMoreOvertime_0:dazeBuildup': {
    sheet: 'Roxy',
    name: 'AssistMoreOvertime_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'basic',
      skillType: 'assistSkill',
      name: 'AssistMoreOvertime_0',
    },
  },
  'AssistMoreOvertime_0:anomBuildup': {
    sheet: 'Roxy',
    name: 'AssistMoreOvertime_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'basic',
      skillType: 'assistSkill',
      name: 'AssistMoreOvertime_0',
    },
  },
  'AssistMoreOvertime_1:standardDmg': {
    sheet: 'Roxy',
    name: 'AssistMoreOvertime_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'basic',
      skillType: 'assistSkill',
      name: 'AssistMoreOvertime_1',
    },
  },
  'AssistMoreOvertime_1:dazeBuildup': {
    sheet: 'Roxy',
    name: 'AssistMoreOvertime_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'basic',
      skillType: 'assistSkill',
      name: 'AssistMoreOvertime_1',
    },
  },
  'AssistMoreOvertime_1:anomBuildup': {
    sheet: 'Roxy',
    name: 'AssistMoreOvertime_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'basic',
      skillType: 'assistSkill',
      name: 'AssistMoreOvertime_1',
    },
  },
  'QuickAssistAtYourService_0:standardDmg': {
    sheet: 'Roxy',
    name: 'QuickAssistAtYourService_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistAtYourService_0',
    },
  },
  'QuickAssistAtYourService_0:dazeBuildup': {
    sheet: 'Roxy',
    name: 'QuickAssistAtYourService_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistAtYourService_0',
    },
  },
  'QuickAssistAtYourService_0:anomBuildup': {
    sheet: 'Roxy',
    name: 'QuickAssistAtYourService_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistAtYourService_0',
    },
  },
  'DefensiveAssistAllowMeToAssist_0:standardDmg': {
    sheet: 'Roxy',
    name: 'DefensiveAssistAllowMeToAssist_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistAllowMeToAssist_0',
    },
  },
  'DefensiveAssistAllowMeToAssist_0:dazeBuildup': {
    sheet: 'Roxy',
    name: 'DefensiveAssistAllowMeToAssist_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistAllowMeToAssist_0',
    },
  },
  'DefensiveAssistAllowMeToAssist_0:anomBuildup': {
    sheet: 'Roxy',
    name: 'DefensiveAssistAllowMeToAssist_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistAllowMeToAssist_0',
    },
  },
  'DefensiveAssistAllowMeToAssist_1:standardDmg': {
    sheet: 'Roxy',
    name: 'DefensiveAssistAllowMeToAssist_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistAllowMeToAssist_1',
    },
  },
  'DefensiveAssistAllowMeToAssist_1:dazeBuildup': {
    sheet: 'Roxy',
    name: 'DefensiveAssistAllowMeToAssist_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistAllowMeToAssist_1',
    },
  },
  'DefensiveAssistAllowMeToAssist_1:anomBuildup': {
    sheet: 'Roxy',
    name: 'DefensiveAssistAllowMeToAssist_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistAllowMeToAssist_1',
    },
  },
  'DefensiveAssistAllowMeToAssist_2:standardDmg': {
    sheet: 'Roxy',
    name: 'DefensiveAssistAllowMeToAssist_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistAllowMeToAssist_2',
    },
  },
  'DefensiveAssistAllowMeToAssist_2:dazeBuildup': {
    sheet: 'Roxy',
    name: 'DefensiveAssistAllowMeToAssist_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistAllowMeToAssist_2',
    },
  },
  'DefensiveAssistAllowMeToAssist_2:anomBuildup': {
    sheet: 'Roxy',
    name: 'DefensiveAssistAllowMeToAssist_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistAllowMeToAssist_2',
    },
  },
  'AssistFollowUpMidnightCode_0:standardDmg': {
    sheet: 'Roxy',
    name: 'AssistFollowUpMidnightCode_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpMidnightCode_0',
    },
  },
  'AssistFollowUpMidnightCode_0:dazeBuildup': {
    sheet: 'Roxy',
    name: 'AssistFollowUpMidnightCode_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpMidnightCode_0',
    },
  },
  'AssistFollowUpMidnightCode_0:anomBuildup': {
    sheet: 'Roxy',
    name: 'AssistFollowUpMidnightCode_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Roxy',
      attribute: 'wind',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpMidnightCode_0',
    },
  },
} as const
