// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Burnice',
    name: 'standardDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Burnice',
      attribute: 'fire',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Burnice',
    name: 'anomalyDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_fire: {
    sheet: 'Burnice',
    name: 'disorderDmgInst_fire',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'disorder',
      name: 'disorderDmgInst_fire',
    },
  },
  vortexDmgInst_fire: {
    sheet: 'Burnice',
    name: 'vortexDmgInst_fire',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'vortex',
      name: 'vortexDmgInst_fire',
    },
  },
  abloomDmgInst: {
    sheet: 'Burnice',
    name: 'abloomDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Burnice',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Burnice',
      attribute: 'fire',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Burnice',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Burnice',
      attribute: 'fire',
      name: 'dazeInst',
    },
  },
  'BasicAttackDirectFlameBlend_0:standardDmg': {
    sheet: 'Burnice',
    name: 'BasicAttackDirectFlameBlend_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackDirectFlameBlend_0',
    },
  },
  'BasicAttackDirectFlameBlend_0:dazeBuildup': {
    sheet: 'Burnice',
    name: 'BasicAttackDirectFlameBlend_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackDirectFlameBlend_0',
    },
  },
  'BasicAttackDirectFlameBlend_0:anomBuildup': {
    sheet: 'Burnice',
    name: 'BasicAttackDirectFlameBlend_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackDirectFlameBlend_0',
    },
  },
  'BasicAttackDirectFlameBlend_1:standardDmg': {
    sheet: 'Burnice',
    name: 'BasicAttackDirectFlameBlend_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Burnice',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackDirectFlameBlend_1',
    },
  },
  'BasicAttackDirectFlameBlend_1:dazeBuildup': {
    sheet: 'Burnice',
    name: 'BasicAttackDirectFlameBlend_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Burnice',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackDirectFlameBlend_1',
    },
  },
  'BasicAttackDirectFlameBlend_1:anomBuildup': {
    sheet: 'Burnice',
    name: 'BasicAttackDirectFlameBlend_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Burnice',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackDirectFlameBlend_1',
    },
  },
  'BasicAttackDirectFlameBlend_2:standardDmg': {
    sheet: 'Burnice',
    name: 'BasicAttackDirectFlameBlend_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackDirectFlameBlend_2',
    },
  },
  'BasicAttackDirectFlameBlend_2:dazeBuildup': {
    sheet: 'Burnice',
    name: 'BasicAttackDirectFlameBlend_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackDirectFlameBlend_2',
    },
  },
  'BasicAttackDirectFlameBlend_2:anomBuildup': {
    sheet: 'Burnice',
    name: 'BasicAttackDirectFlameBlend_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackDirectFlameBlend_2',
    },
  },
  'BasicAttackDirectFlameBlend_3:standardDmg': {
    sheet: 'Burnice',
    name: 'BasicAttackDirectFlameBlend_3:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackDirectFlameBlend_3',
    },
  },
  'BasicAttackDirectFlameBlend_3:dazeBuildup': {
    sheet: 'Burnice',
    name: 'BasicAttackDirectFlameBlend_3:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackDirectFlameBlend_3',
    },
  },
  'BasicAttackDirectFlameBlend_3:anomBuildup': {
    sheet: 'Burnice',
    name: 'BasicAttackDirectFlameBlend_3:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackDirectFlameBlend_3',
    },
  },
  'BasicAttackDirectFlameBlend_4:standardDmg': {
    sheet: 'Burnice',
    name: 'BasicAttackDirectFlameBlend_4:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackDirectFlameBlend_4',
    },
  },
  'BasicAttackDirectFlameBlend_4:dazeBuildup': {
    sheet: 'Burnice',
    name: 'BasicAttackDirectFlameBlend_4:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackDirectFlameBlend_4',
    },
  },
  'BasicAttackDirectFlameBlend_4:anomBuildup': {
    sheet: 'Burnice',
    name: 'BasicAttackDirectFlameBlend_4:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackDirectFlameBlend_4',
    },
  },
  'BasicAttackMixedFlameBlend_0:standardDmg': {
    sheet: 'Burnice',
    name: 'BasicAttackMixedFlameBlend_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      skillType2: 'assistSkill',
      name: 'BasicAttackMixedFlameBlend_0',
    },
  },
  'BasicAttackMixedFlameBlend_0:dazeBuildup': {
    sheet: 'Burnice',
    name: 'BasicAttackMixedFlameBlend_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      skillType2: 'assistSkill',
      name: 'BasicAttackMixedFlameBlend_0',
    },
  },
  'BasicAttackMixedFlameBlend_0:anomBuildup': {
    sheet: 'Burnice',
    name: 'BasicAttackMixedFlameBlend_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      skillType2: 'assistSkill',
      name: 'BasicAttackMixedFlameBlend_0',
    },
  },
  'BasicAttackMixedFlameBlend_1:standardDmg': {
    sheet: 'Burnice',
    name: 'BasicAttackMixedFlameBlend_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      skillType2: 'assistSkill',
      name: 'BasicAttackMixedFlameBlend_1',
    },
  },
  'BasicAttackMixedFlameBlend_1:dazeBuildup': {
    sheet: 'Burnice',
    name: 'BasicAttackMixedFlameBlend_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      skillType2: 'assistSkill',
      name: 'BasicAttackMixedFlameBlend_1',
    },
  },
  'BasicAttackMixedFlameBlend_1:anomBuildup': {
    sheet: 'Burnice',
    name: 'BasicAttackMixedFlameBlend_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      skillType2: 'assistSkill',
      name: 'BasicAttackMixedFlameBlend_1',
    },
  },
  'DashAttackDangerousFermentation_0:standardDmg': {
    sheet: 'Burnice',
    name: 'DashAttackDangerousFermentation_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'dash',
      skillType1: 'dodgeSkill',
      name: 'DashAttackDangerousFermentation_0',
    },
  },
  'DashAttackDangerousFermentation_0:dazeBuildup': {
    sheet: 'Burnice',
    name: 'DashAttackDangerousFermentation_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'dash',
      skillType1: 'dodgeSkill',
      name: 'DashAttackDangerousFermentation_0',
    },
  },
  'DashAttackDangerousFermentation_0:anomBuildup': {
    sheet: 'Burnice',
    name: 'DashAttackDangerousFermentation_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'dash',
      skillType1: 'dodgeSkill',
      name: 'DashAttackDangerousFermentation_0',
    },
  },
  'DodgeCounterFlutteringSteps_0:standardDmg': {
    sheet: 'Burnice',
    name: 'DodgeCounterFlutteringSteps_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'dodgeCounter',
      skillType1: 'dodgeSkill',
      name: 'DodgeCounterFlutteringSteps_0',
    },
  },
  'DodgeCounterFlutteringSteps_0:dazeBuildup': {
    sheet: 'Burnice',
    name: 'DodgeCounterFlutteringSteps_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'dodgeCounter',
      skillType1: 'dodgeSkill',
      name: 'DodgeCounterFlutteringSteps_0',
    },
  },
  'DodgeCounterFlutteringSteps_0:anomBuildup': {
    sheet: 'Burnice',
    name: 'DodgeCounterFlutteringSteps_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'dodgeCounter',
      skillType1: 'dodgeSkill',
      name: 'DodgeCounterFlutteringSteps_0',
    },
  },
  'SpecialAttackIntenseHeatAgingMethod_0:standardDmg': {
    sheet: 'Burnice',
    name: 'SpecialAttackIntenseHeatAgingMethod_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackIntenseHeatAgingMethod_0',
    },
  },
  'SpecialAttackIntenseHeatAgingMethod_0:dazeBuildup': {
    sheet: 'Burnice',
    name: 'SpecialAttackIntenseHeatAgingMethod_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackIntenseHeatAgingMethod_0',
    },
  },
  'SpecialAttackIntenseHeatAgingMethod_0:anomBuildup': {
    sheet: 'Burnice',
    name: 'SpecialAttackIntenseHeatAgingMethod_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackIntenseHeatAgingMethod_0',
    },
  },
  'SpecialAttackIntenseHeatAgingMethod_1:standardDmg': {
    sheet: 'Burnice',
    name: 'SpecialAttackIntenseHeatAgingMethod_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackIntenseHeatAgingMethod_1',
    },
  },
  'SpecialAttackIntenseHeatAgingMethod_1:dazeBuildup': {
    sheet: 'Burnice',
    name: 'SpecialAttackIntenseHeatAgingMethod_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackIntenseHeatAgingMethod_1',
    },
  },
  'SpecialAttackIntenseHeatAgingMethod_1:anomBuildup': {
    sheet: 'Burnice',
    name: 'SpecialAttackIntenseHeatAgingMethod_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackIntenseHeatAgingMethod_1',
    },
  },
  'EXSpecialAttackIntenseHeatStirringMethod_0:standardDmg': {
    sheet: 'Burnice',
    name: 'EXSpecialAttackIntenseHeatStirringMethod_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackIntenseHeatStirringMethod_0',
    },
  },
  'EXSpecialAttackIntenseHeatStirringMethod_0:dazeBuildup': {
    sheet: 'Burnice',
    name: 'EXSpecialAttackIntenseHeatStirringMethod_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackIntenseHeatStirringMethod_0',
    },
  },
  'EXSpecialAttackIntenseHeatStirringMethod_0:anomBuildup': {
    sheet: 'Burnice',
    name: 'EXSpecialAttackIntenseHeatStirringMethod_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackIntenseHeatStirringMethod_0',
    },
  },
  'EXSpecialAttackIntenseHeatStirringMethod_1:standardDmg': {
    sheet: 'Burnice',
    name: 'EXSpecialAttackIntenseHeatStirringMethod_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackIntenseHeatStirringMethod_1',
    },
  },
  'EXSpecialAttackIntenseHeatStirringMethod_1:dazeBuildup': {
    sheet: 'Burnice',
    name: 'EXSpecialAttackIntenseHeatStirringMethod_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackIntenseHeatStirringMethod_1',
    },
  },
  'EXSpecialAttackIntenseHeatStirringMethod_1:anomBuildup': {
    sheet: 'Burnice',
    name: 'EXSpecialAttackIntenseHeatStirringMethod_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackIntenseHeatStirringMethod_1',
    },
  },
  'EXSpecialAttackIntenseHeatStirringMethodDoubleShot_0:standardDmg': {
    sheet: 'Burnice',
    name: 'EXSpecialAttackIntenseHeatStirringMethodDoubleShot_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackIntenseHeatStirringMethodDoubleShot_0',
    },
  },
  'EXSpecialAttackIntenseHeatStirringMethodDoubleShot_0:dazeBuildup': {
    sheet: 'Burnice',
    name: 'EXSpecialAttackIntenseHeatStirringMethodDoubleShot_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackIntenseHeatStirringMethodDoubleShot_0',
    },
  },
  'EXSpecialAttackIntenseHeatStirringMethodDoubleShot_0:anomBuildup': {
    sheet: 'Burnice',
    name: 'EXSpecialAttackIntenseHeatStirringMethodDoubleShot_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackIntenseHeatStirringMethodDoubleShot_0',
    },
  },
  'EXSpecialAttackIntenseHeatStirringMethodDoubleShot_1:standardDmg': {
    sheet: 'Burnice',
    name: 'EXSpecialAttackIntenseHeatStirringMethodDoubleShot_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackIntenseHeatStirringMethodDoubleShot_1',
    },
  },
  'EXSpecialAttackIntenseHeatStirringMethodDoubleShot_1:dazeBuildup': {
    sheet: 'Burnice',
    name: 'EXSpecialAttackIntenseHeatStirringMethodDoubleShot_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackIntenseHeatStirringMethodDoubleShot_1',
    },
  },
  'EXSpecialAttackIntenseHeatStirringMethodDoubleShot_1:anomBuildup': {
    sheet: 'Burnice',
    name: 'EXSpecialAttackIntenseHeatStirringMethodDoubleShot_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackIntenseHeatStirringMethodDoubleShot_1',
    },
  },
  'EXSpecialAttackIntenseHeatTossingMethod_0:standardDmg': {
    sheet: 'Burnice',
    name: 'EXSpecialAttackIntenseHeatTossingMethod_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackIntenseHeatTossingMethod_0',
    },
  },
  'EXSpecialAttackIntenseHeatTossingMethod_0:dazeBuildup': {
    sheet: 'Burnice',
    name: 'EXSpecialAttackIntenseHeatTossingMethod_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackIntenseHeatTossingMethod_0',
    },
  },
  'EXSpecialAttackIntenseHeatTossingMethod_0:anomBuildup': {
    sheet: 'Burnice',
    name: 'EXSpecialAttackIntenseHeatTossingMethod_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackIntenseHeatTossingMethod_0',
    },
  },
  'ChainAttackFuelFedFlame_0:standardDmg': {
    sheet: 'Burnice',
    name: 'ChainAttackFuelFedFlame_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'chain',
      skillType1: 'chainSkill',
      name: 'ChainAttackFuelFedFlame_0',
    },
  },
  'ChainAttackFuelFedFlame_0:dazeBuildup': {
    sheet: 'Burnice',
    name: 'ChainAttackFuelFedFlame_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'chain',
      skillType1: 'chainSkill',
      name: 'ChainAttackFuelFedFlame_0',
    },
  },
  'ChainAttackFuelFedFlame_0:anomBuildup': {
    sheet: 'Burnice',
    name: 'ChainAttackFuelFedFlame_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'chain',
      skillType1: 'chainSkill',
      name: 'ChainAttackFuelFedFlame_0',
    },
  },
  'UltimateGloriousInferno_0:standardDmg': {
    sheet: 'Burnice',
    name: 'UltimateGloriousInferno_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'ult',
      skillType1: 'chainSkill',
      name: 'UltimateGloriousInferno_0',
    },
  },
  'UltimateGloriousInferno_0:dazeBuildup': {
    sheet: 'Burnice',
    name: 'UltimateGloriousInferno_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'ult',
      skillType1: 'chainSkill',
      name: 'UltimateGloriousInferno_0',
    },
  },
  'UltimateGloriousInferno_0:anomBuildup': {
    sheet: 'Burnice',
    name: 'UltimateGloriousInferno_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'ult',
      skillType1: 'chainSkill',
      name: 'UltimateGloriousInferno_0',
    },
  },
  'QuickAssistEnergizingSpecialtyDrink_0:standardDmg': {
    sheet: 'Burnice',
    name: 'QuickAssistEnergizingSpecialtyDrink_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'quickAssist',
      skillType1: 'assistSkill',
      name: 'QuickAssistEnergizingSpecialtyDrink_0',
    },
  },
  'QuickAssistEnergizingSpecialtyDrink_0:dazeBuildup': {
    sheet: 'Burnice',
    name: 'QuickAssistEnergizingSpecialtyDrink_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'quickAssist',
      skillType1: 'assistSkill',
      name: 'QuickAssistEnergizingSpecialtyDrink_0',
    },
  },
  'QuickAssistEnergizingSpecialtyDrink_0:anomBuildup': {
    sheet: 'Burnice',
    name: 'QuickAssistEnergizingSpecialtyDrink_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'quickAssist',
      skillType1: 'assistSkill',
      name: 'QuickAssistEnergizingSpecialtyDrink_0',
    },
  },
  'DefensiveAssistSmokyCauldron_0:standardDmg': {
    sheet: 'Burnice',
    name: 'DefensiveAssistSmokyCauldron_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistSmokyCauldron_0',
    },
  },
  'DefensiveAssistSmokyCauldron_0:dazeBuildup': {
    sheet: 'Burnice',
    name: 'DefensiveAssistSmokyCauldron_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistSmokyCauldron_0',
    },
  },
  'DefensiveAssistSmokyCauldron_0:anomBuildup': {
    sheet: 'Burnice',
    name: 'DefensiveAssistSmokyCauldron_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistSmokyCauldron_0',
    },
  },
  'DefensiveAssistSmokyCauldron_1:standardDmg': {
    sheet: 'Burnice',
    name: 'DefensiveAssistSmokyCauldron_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistSmokyCauldron_1',
    },
  },
  'DefensiveAssistSmokyCauldron_1:dazeBuildup': {
    sheet: 'Burnice',
    name: 'DefensiveAssistSmokyCauldron_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistSmokyCauldron_1',
    },
  },
  'DefensiveAssistSmokyCauldron_1:anomBuildup': {
    sheet: 'Burnice',
    name: 'DefensiveAssistSmokyCauldron_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistSmokyCauldron_1',
    },
  },
  'DefensiveAssistSmokyCauldron_2:standardDmg': {
    sheet: 'Burnice',
    name: 'DefensiveAssistSmokyCauldron_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistSmokyCauldron_2',
    },
  },
  'DefensiveAssistSmokyCauldron_2:dazeBuildup': {
    sheet: 'Burnice',
    name: 'DefensiveAssistSmokyCauldron_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistSmokyCauldron_2',
    },
  },
  'DefensiveAssistSmokyCauldron_2:anomBuildup': {
    sheet: 'Burnice',
    name: 'DefensiveAssistSmokyCauldron_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistSmokyCauldron_2',
    },
  },
  'AssistFollowUpScorchingDew_0:standardDmg': {
    sheet: 'Burnice',
    name: 'AssistFollowUpScorchingDew_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'assistFollowUp',
      skillType1: 'assistSkill',
      name: 'AssistFollowUpScorchingDew_0',
    },
  },
  'AssistFollowUpScorchingDew_0:dazeBuildup': {
    sheet: 'Burnice',
    name: 'AssistFollowUpScorchingDew_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'assistFollowUp',
      skillType1: 'assistSkill',
      name: 'AssistFollowUpScorchingDew_0',
    },
  },
  'AssistFollowUpScorchingDew_0:anomBuildup': {
    sheet: 'Burnice',
    name: 'AssistFollowUpScorchingDew_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Burnice',
      attribute: 'fire',
      damageType1: 'assistFollowUp',
      skillType1: 'assistSkill',
      name: 'AssistFollowUpScorchingDew_0',
    },
  },
  core_afterburn_dmg: {
    sheet: 'Burnice',
    name: 'core_afterburn_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Burnice',
      attribute: 'fire',
      skillType1: 'assistSkill',
      name: 'core_afterburn_dmg',
    },
  },
  core_afterburn_anomBuildup: {
    sheet: 'Burnice',
    name: 'core_afterburn_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Burnice',
      attribute: 'fire',
      skillType1: 'assistSkill',
      name: 'core_afterburn_anomBuildup',
    },
  },
  m6_additional_afterburn_dmg: {
    sheet: 'Burnice',
    name: 'm6_additional_afterburn_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Burnice',
      attribute: 'fire',
      skillType1: 'assistSkill',
      name: 'm6_additional_afterburn_dmg',
    },
  },
} as const
