// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'YeShunguang',
    name: 'standardDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'YeShunguang',
      attribute: 'physical',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'YeShunguang',
    name: 'anomalyDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_physical: {
    sheet: 'YeShunguang',
    name: 'disorderDmgInst_physical',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'disorder',
      name: 'disorderDmgInst_physical',
    },
  },
  vortexDmgInst_physical: {
    sheet: 'YeShunguang',
    name: 'vortexDmgInst_physical',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'vortex',
      name: 'vortexDmgInst_physical',
    },
  },
  abloomDmgInst: {
    sheet: 'YeShunguang',
    name: 'abloomDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'YeShunguang',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'YeShunguang',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      name: 'dazeInst',
    },
  },
  'BasicAttackSwiftedge_0:standardDmg': {
    sheet: 'YeShunguang',
    name: 'BasicAttackSwiftedge_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSwiftedge_0',
    },
  },
  'BasicAttackSwiftedge_0:dazeBuildup': {
    sheet: 'YeShunguang',
    name: 'BasicAttackSwiftedge_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSwiftedge_0',
    },
  },
  'BasicAttackSwiftedge_0:anomBuildup': {
    sheet: 'YeShunguang',
    name: 'BasicAttackSwiftedge_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSwiftedge_0',
    },
  },
  'BasicAttackSwiftedge_1:standardDmg': {
    sheet: 'YeShunguang',
    name: 'BasicAttackSwiftedge_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSwiftedge_1',
    },
  },
  'BasicAttackSwiftedge_1:dazeBuildup': {
    sheet: 'YeShunguang',
    name: 'BasicAttackSwiftedge_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSwiftedge_1',
    },
  },
  'BasicAttackSwiftedge_1:anomBuildup': {
    sheet: 'YeShunguang',
    name: 'BasicAttackSwiftedge_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSwiftedge_1',
    },
  },
  'BasicAttackSwiftedge_2:standardDmg': {
    sheet: 'YeShunguang',
    name: 'BasicAttackSwiftedge_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSwiftedge_2',
    },
  },
  'BasicAttackSwiftedge_2:dazeBuildup': {
    sheet: 'YeShunguang',
    name: 'BasicAttackSwiftedge_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSwiftedge_2',
    },
  },
  'BasicAttackSwiftedge_2:anomBuildup': {
    sheet: 'YeShunguang',
    name: 'BasicAttackSwiftedge_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSwiftedge_2',
    },
  },
  'BasicAttackSwiftedge_3:standardDmg': {
    sheet: 'YeShunguang',
    name: 'BasicAttackSwiftedge_3:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSwiftedge_3',
    },
  },
  'BasicAttackSwiftedge_3:dazeBuildup': {
    sheet: 'YeShunguang',
    name: 'BasicAttackSwiftedge_3:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSwiftedge_3',
    },
  },
  'BasicAttackSwiftedge_3:anomBuildup': {
    sheet: 'YeShunguang',
    name: 'BasicAttackSwiftedge_3:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSwiftedge_3',
    },
  },
  'BasicAttackCloudstreamSwordWill_0:standardDmg': {
    sheet: 'YeShunguang',
    name: 'BasicAttackCloudstreamSwordWill_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackCloudstreamSwordWill_0',
    },
  },
  'BasicAttackCloudstreamSwordWill_0:dazeBuildup': {
    sheet: 'YeShunguang',
    name: 'BasicAttackCloudstreamSwordWill_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackCloudstreamSwordWill_0',
    },
  },
  'BasicAttackCloudstreamSwordWill_0:anomBuildup': {
    sheet: 'YeShunguang',
    name: 'BasicAttackCloudstreamSwordWill_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackCloudstreamSwordWill_0',
    },
  },
  'BasicAttackEnlightenedMindSplittingCurrents_0:standardDmg': {
    sheet: 'YeShunguang',
    name: 'BasicAttackEnlightenedMindSplittingCurrents_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEnlightenedMindSplittingCurrents_0',
    },
  },
  'BasicAttackEnlightenedMindSplittingCurrents_0:dazeBuildup': {
    sheet: 'YeShunguang',
    name: 'BasicAttackEnlightenedMindSplittingCurrents_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEnlightenedMindSplittingCurrents_0',
    },
  },
  'BasicAttackEnlightenedMindSplittingCurrents_0:anomBuildup': {
    sheet: 'YeShunguang',
    name: 'BasicAttackEnlightenedMindSplittingCurrents_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEnlightenedMindSplittingCurrents_0',
    },
  },
  'BasicAttackEnlightenedMindSplittingCurrents_1:standardDmg': {
    sheet: 'YeShunguang',
    name: 'BasicAttackEnlightenedMindSplittingCurrents_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEnlightenedMindSplittingCurrents_1',
    },
  },
  'BasicAttackEnlightenedMindSplittingCurrents_1:dazeBuildup': {
    sheet: 'YeShunguang',
    name: 'BasicAttackEnlightenedMindSplittingCurrents_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEnlightenedMindSplittingCurrents_1',
    },
  },
  'BasicAttackEnlightenedMindSplittingCurrents_1:anomBuildup': {
    sheet: 'YeShunguang',
    name: 'BasicAttackEnlightenedMindSplittingCurrents_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEnlightenedMindSplittingCurrents_1',
    },
  },
  'BasicAttackEnlightenedMindSplittingCurrents_2:standardDmg': {
    sheet: 'YeShunguang',
    name: 'BasicAttackEnlightenedMindSplittingCurrents_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEnlightenedMindSplittingCurrents_2',
    },
  },
  'BasicAttackEnlightenedMindSplittingCurrents_2:dazeBuildup': {
    sheet: 'YeShunguang',
    name: 'BasicAttackEnlightenedMindSplittingCurrents_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEnlightenedMindSplittingCurrents_2',
    },
  },
  'BasicAttackEnlightenedMindSplittingCurrents_2:anomBuildup': {
    sheet: 'YeShunguang',
    name: 'BasicAttackEnlightenedMindSplittingCurrents_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEnlightenedMindSplittingCurrents_2',
    },
  },
  'BasicAttackEnlightenedMindSkywardAscent_0:standardDmg': {
    sheet: 'YeShunguang',
    name: 'BasicAttackEnlightenedMindSkywardAscent_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEnlightenedMindSkywardAscent_0',
    },
  },
  'BasicAttackEnlightenedMindSkywardAscent_0:dazeBuildup': {
    sheet: 'YeShunguang',
    name: 'BasicAttackEnlightenedMindSkywardAscent_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEnlightenedMindSkywardAscent_0',
    },
  },
  'BasicAttackEnlightenedMindSkywardAscent_0:anomBuildup': {
    sheet: 'YeShunguang',
    name: 'BasicAttackEnlightenedMindSkywardAscent_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEnlightenedMindSkywardAscent_0',
    },
  },
  'BasicAttackEnlightenedMindSunderlightMaximum_0:standardDmg': {
    sheet: 'YeShunguang',
    name: 'BasicAttackEnlightenedMindSunderlightMaximum_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEnlightenedMindSunderlightMaximum_0',
    },
  },
  'BasicAttackEnlightenedMindSunderlightMaximum_0:dazeBuildup': {
    sheet: 'YeShunguang',
    name: 'BasicAttackEnlightenedMindSunderlightMaximum_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEnlightenedMindSunderlightMaximum_0',
    },
  },
  'BasicAttackEnlightenedMindSunderlightMaximum_0:anomBuildup': {
    sheet: 'YeShunguang',
    name: 'BasicAttackEnlightenedMindSunderlightMaximum_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEnlightenedMindSunderlightMaximum_0',
    },
  },
  'BasicAttackEnlightenedMindSunderlight_0:standardDmg': {
    sheet: 'YeShunguang',
    name: 'BasicAttackEnlightenedMindSunderlight_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEnlightenedMindSunderlight_0',
    },
  },
  'BasicAttackEnlightenedMindSunderlight_0:dazeBuildup': {
    sheet: 'YeShunguang',
    name: 'BasicAttackEnlightenedMindSunderlight_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEnlightenedMindSunderlight_0',
    },
  },
  'BasicAttackEnlightenedMindSunderlight_0:anomBuildup': {
    sheet: 'YeShunguang',
    name: 'BasicAttackEnlightenedMindSunderlight_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEnlightenedMindSunderlight_0',
    },
  },
  'BasicAttackEnlightenedMindSunderlight_1:standardDmg': {
    sheet: 'YeShunguang',
    name: 'BasicAttackEnlightenedMindSunderlight_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEnlightenedMindSunderlight_1',
    },
  },
  'BasicAttackEnlightenedMindSunderlight_1:dazeBuildup': {
    sheet: 'YeShunguang',
    name: 'BasicAttackEnlightenedMindSunderlight_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEnlightenedMindSunderlight_1',
    },
  },
  'BasicAttackEnlightenedMindSunderlight_1:anomBuildup': {
    sheet: 'YeShunguang',
    name: 'BasicAttackEnlightenedMindSunderlight_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEnlightenedMindSunderlight_1',
    },
  },
  'BasicAttackEnlightenedMindSunderlightAnnihilation_0:standardDmg': {
    sheet: 'YeShunguang',
    name: 'BasicAttackEnlightenedMindSunderlightAnnihilation_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEnlightenedMindSunderlightAnnihilation_0',
    },
  },
  'BasicAttackEnlightenedMindSunderlightAnnihilation_0:dazeBuildup': {
    sheet: 'YeShunguang',
    name: 'BasicAttackEnlightenedMindSunderlightAnnihilation_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEnlightenedMindSunderlightAnnihilation_0',
    },
  },
  'BasicAttackEnlightenedMindSunderlightAnnihilation_0:anomBuildup': {
    sheet: 'YeShunguang',
    name: 'BasicAttackEnlightenedMindSunderlightAnnihilation_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEnlightenedMindSunderlightAnnihilation_0',
    },
  },
  'BasicAttackEnlightenedMindSunderlightAnnihilation_1:standardDmg': {
    sheet: 'YeShunguang',
    name: 'BasicAttackEnlightenedMindSunderlightAnnihilation_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEnlightenedMindSunderlightAnnihilation_1',
    },
  },
  'BasicAttackEnlightenedMindSunderlightAnnihilation_1:dazeBuildup': {
    sheet: 'YeShunguang',
    name: 'BasicAttackEnlightenedMindSunderlightAnnihilation_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEnlightenedMindSunderlightAnnihilation_1',
    },
  },
  'BasicAttackEnlightenedMindSunderlightAnnihilation_1:anomBuildup': {
    sheet: 'YeShunguang',
    name: 'BasicAttackEnlightenedMindSunderlightAnnihilation_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEnlightenedMindSunderlightAnnihilation_1',
    },
  },
  'DashAttackPhantasmDash_0:standardDmg': {
    sheet: 'YeShunguang',
    name: 'DashAttackPhantasmDash_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackPhantasmDash_0',
    },
  },
  'DashAttackPhantasmDash_0:dazeBuildup': {
    sheet: 'YeShunguang',
    name: 'DashAttackPhantasmDash_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackPhantasmDash_0',
    },
  },
  'DashAttackPhantasmDash_0:anomBuildup': {
    sheet: 'YeShunguang',
    name: 'DashAttackPhantasmDash_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackPhantasmDash_0',
    },
  },
  'DodgeCounterSwallowStrike_0:standardDmg': {
    sheet: 'YeShunguang',
    name: 'DodgeCounterSwallowStrike_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterSwallowStrike_0',
    },
  },
  'DodgeCounterSwallowStrike_0:dazeBuildup': {
    sheet: 'YeShunguang',
    name: 'DodgeCounterSwallowStrike_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterSwallowStrike_0',
    },
  },
  'DodgeCounterSwallowStrike_0:anomBuildup': {
    sheet: 'YeShunguang',
    name: 'DodgeCounterSwallowStrike_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterSwallowStrike_0',
    },
  },
  'SpecialAttackGuidingTides_0:standardDmg': {
    sheet: 'YeShunguang',
    name: 'SpecialAttackGuidingTides_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackGuidingTides_0',
    },
  },
  'SpecialAttackGuidingTides_0:dazeBuildup': {
    sheet: 'YeShunguang',
    name: 'SpecialAttackGuidingTides_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackGuidingTides_0',
    },
  },
  'SpecialAttackGuidingTides_0:anomBuildup': {
    sheet: 'YeShunguang',
    name: 'SpecialAttackGuidingTides_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackGuidingTides_0',
    },
  },
  'SpecialAttackGuidingTides_1:standardDmg': {
    sheet: 'YeShunguang',
    name: 'SpecialAttackGuidingTides_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackGuidingTides_1',
    },
  },
  'SpecialAttackGuidingTides_1:dazeBuildup': {
    sheet: 'YeShunguang',
    name: 'SpecialAttackGuidingTides_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackGuidingTides_1',
    },
  },
  'SpecialAttackGuidingTides_1:anomBuildup': {
    sheet: 'YeShunguang',
    name: 'SpecialAttackGuidingTides_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackGuidingTides_1',
    },
  },
  'EXSpecialAttackGaleSuppression_0:standardDmg': {
    sheet: 'YeShunguang',
    name: 'EXSpecialAttackGaleSuppression_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackGaleSuppression_0',
    },
  },
  'EXSpecialAttackGaleSuppression_0:dazeBuildup': {
    sheet: 'YeShunguang',
    name: 'EXSpecialAttackGaleSuppression_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackGaleSuppression_0',
    },
  },
  'EXSpecialAttackGaleSuppression_0:anomBuildup': {
    sheet: 'YeShunguang',
    name: 'EXSpecialAttackGaleSuppression_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackGaleSuppression_0',
    },
  },
  'SpecialAttackEnlightenedMindCleanExit_0:standardDmg': {
    sheet: 'YeShunguang',
    name: 'SpecialAttackEnlightenedMindCleanExit_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackEnlightenedMindCleanExit_0',
    },
  },
  'SpecialAttackEnlightenedMindCleanExit_0:dazeBuildup': {
    sheet: 'YeShunguang',
    name: 'SpecialAttackEnlightenedMindCleanExit_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackEnlightenedMindCleanExit_0',
    },
  },
  'SpecialAttackEnlightenedMindCleanExit_0:anomBuildup': {
    sheet: 'YeShunguang',
    name: 'SpecialAttackEnlightenedMindCleanExit_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackEnlightenedMindCleanExit_0',
    },
  },
  'EXSpecialAttackEnlightenedMindSoaringLight_0:standardDmg': {
    sheet: 'YeShunguang',
    name: 'EXSpecialAttackEnlightenedMindSoaringLight_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackEnlightenedMindSoaringLight_0',
    },
  },
  'EXSpecialAttackEnlightenedMindSoaringLight_0:dazeBuildup': {
    sheet: 'YeShunguang',
    name: 'EXSpecialAttackEnlightenedMindSoaringLight_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackEnlightenedMindSoaringLight_0',
    },
  },
  'EXSpecialAttackEnlightenedMindSoaringLight_0:anomBuildup': {
    sheet: 'YeShunguang',
    name: 'EXSpecialAttackEnlightenedMindSoaringLight_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackEnlightenedMindSoaringLight_0',
    },
  },
  'EXSpecialAttackEnlightenedMindReturnToDust_0:standardDmg': {
    sheet: 'YeShunguang',
    name: 'EXSpecialAttackEnlightenedMindReturnToDust_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackEnlightenedMindReturnToDust_0',
    },
  },
  'EXSpecialAttackEnlightenedMindReturnToDust_0:dazeBuildup': {
    sheet: 'YeShunguang',
    name: 'EXSpecialAttackEnlightenedMindReturnToDust_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackEnlightenedMindReturnToDust_0',
    },
  },
  'EXSpecialAttackEnlightenedMindReturnToDust_0:anomBuildup': {
    sheet: 'YeShunguang',
    name: 'EXSpecialAttackEnlightenedMindReturnToDust_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackEnlightenedMindReturnToDust_0',
    },
  },
  'ChainAttackSmiteTheWicked_0:standardDmg': {
    sheet: 'YeShunguang',
    name: 'ChainAttackSmiteTheWicked_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackSmiteTheWicked_0',
    },
  },
  'ChainAttackSmiteTheWicked_0:dazeBuildup': {
    sheet: 'YeShunguang',
    name: 'ChainAttackSmiteTheWicked_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackSmiteTheWicked_0',
    },
  },
  'ChainAttackSmiteTheWicked_0:anomBuildup': {
    sheet: 'YeShunguang',
    name: 'ChainAttackSmiteTheWicked_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackSmiteTheWicked_0',
    },
  },
  'UltimateChasingStorms_0:standardDmg': {
    sheet: 'YeShunguang',
    name: 'UltimateChasingStorms_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateChasingStorms_0',
    },
  },
  'UltimateChasingStorms_0:dazeBuildup': {
    sheet: 'YeShunguang',
    name: 'UltimateChasingStorms_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateChasingStorms_0',
    },
  },
  'UltimateChasingStorms_0:anomBuildup': {
    sheet: 'YeShunguang',
    name: 'UltimateChasingStorms_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateChasingStorms_0',
    },
  },
  'ChainAttackEnlightenedMindLureThunder_0:standardDmg': {
    sheet: 'YeShunguang',
    name: 'ChainAttackEnlightenedMindLureThunder_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackEnlightenedMindLureThunder_0',
    },
  },
  'ChainAttackEnlightenedMindLureThunder_0:dazeBuildup': {
    sheet: 'YeShunguang',
    name: 'ChainAttackEnlightenedMindLureThunder_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackEnlightenedMindLureThunder_0',
    },
  },
  'ChainAttackEnlightenedMindLureThunder_0:anomBuildup': {
    sheet: 'YeShunguang',
    name: 'ChainAttackEnlightenedMindLureThunder_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackEnlightenedMindLureThunder_0',
    },
  },
  'UltimateCleavingHeavens_0:standardDmg': {
    sheet: 'YeShunguang',
    name: 'UltimateCleavingHeavens_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateCleavingHeavens_0',
    },
  },
  'UltimateCleavingHeavens_0:dazeBuildup': {
    sheet: 'YeShunguang',
    name: 'UltimateCleavingHeavens_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateCleavingHeavens_0',
    },
  },
  'UltimateCleavingHeavens_0:anomBuildup': {
    sheet: 'YeShunguang',
    name: 'UltimateCleavingHeavens_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateCleavingHeavens_0',
    },
  },
  'EntrySkillIlluminatingDarkness_0:standardDmg': {
    sheet: 'YeShunguang',
    name: 'EntrySkillIlluminatingDarkness_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'entrySkill',
      skillType: 'assistSkill',
      name: 'EntrySkillIlluminatingDarkness_0',
    },
  },
  'EntrySkillIlluminatingDarkness_0:dazeBuildup': {
    sheet: 'YeShunguang',
    name: 'EntrySkillIlluminatingDarkness_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'entrySkill',
      skillType: 'assistSkill',
      name: 'EntrySkillIlluminatingDarkness_0',
    },
  },
  'EntrySkillIlluminatingDarkness_0:anomBuildup': {
    sheet: 'YeShunguang',
    name: 'EntrySkillIlluminatingDarkness_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'entrySkill',
      skillType: 'assistSkill',
      name: 'EntrySkillIlluminatingDarkness_0',
    },
  },
  'QuickAssistSupportGuard_0:standardDmg': {
    sheet: 'YeShunguang',
    name: 'QuickAssistSupportGuard_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistSupportGuard_0',
    },
  },
  'QuickAssistSupportGuard_0:dazeBuildup': {
    sheet: 'YeShunguang',
    name: 'QuickAssistSupportGuard_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistSupportGuard_0',
    },
  },
  'QuickAssistSupportGuard_0:anomBuildup': {
    sheet: 'YeShunguang',
    name: 'QuickAssistSupportGuard_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistSupportGuard_0',
    },
  },
  'AssistFollowUpCeaseHostility_0:standardDmg': {
    sheet: 'YeShunguang',
    name: 'AssistFollowUpCeaseHostility_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpCeaseHostility_0',
    },
  },
  'AssistFollowUpCeaseHostility_0:dazeBuildup': {
    sheet: 'YeShunguang',
    name: 'AssistFollowUpCeaseHostility_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpCeaseHostility_0',
    },
  },
  'AssistFollowUpCeaseHostility_0:anomBuildup': {
    sheet: 'YeShunguang',
    name: 'AssistFollowUpCeaseHostility_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpCeaseHostility_0',
    },
  },
  'DefensiveAssistWhenIReturn_0:standardDmg': {
    sheet: 'YeShunguang',
    name: 'DefensiveAssistWhenIReturn_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistWhenIReturn_0',
    },
  },
  'DefensiveAssistWhenIReturn_0:dazeBuildup': {
    sheet: 'YeShunguang',
    name: 'DefensiveAssistWhenIReturn_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistWhenIReturn_0',
    },
  },
  'DefensiveAssistWhenIReturn_0:anomBuildup': {
    sheet: 'YeShunguang',
    name: 'DefensiveAssistWhenIReturn_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistWhenIReturn_0',
    },
  },
  'DefensiveAssistWhenIReturn_1:standardDmg': {
    sheet: 'YeShunguang',
    name: 'DefensiveAssistWhenIReturn_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistWhenIReturn_1',
    },
  },
  'DefensiveAssistWhenIReturn_1:dazeBuildup': {
    sheet: 'YeShunguang',
    name: 'DefensiveAssistWhenIReturn_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistWhenIReturn_1',
    },
  },
  'DefensiveAssistWhenIReturn_1:anomBuildup': {
    sheet: 'YeShunguang',
    name: 'DefensiveAssistWhenIReturn_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistWhenIReturn_1',
    },
  },
  'DefensiveAssistWhenIReturn_2:standardDmg': {
    sheet: 'YeShunguang',
    name: 'DefensiveAssistWhenIReturn_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistWhenIReturn_2',
    },
  },
  'DefensiveAssistWhenIReturn_2:dazeBuildup': {
    sheet: 'YeShunguang',
    name: 'DefensiveAssistWhenIReturn_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistWhenIReturn_2',
    },
  },
  'DefensiveAssistWhenIReturn_2:anomBuildup': {
    sheet: 'YeShunguang',
    name: 'DefensiveAssistWhenIReturn_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistWhenIReturn_2',
    },
  },
  'QuickAssistEnlightenedMindTacticalSupport_0:standardDmg': {
    sheet: 'YeShunguang',
    name: 'QuickAssistEnlightenedMindTacticalSupport_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistEnlightenedMindTacticalSupport_0',
    },
  },
  'QuickAssistEnlightenedMindTacticalSupport_0:dazeBuildup': {
    sheet: 'YeShunguang',
    name: 'QuickAssistEnlightenedMindTacticalSupport_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistEnlightenedMindTacticalSupport_0',
    },
  },
  'QuickAssistEnlightenedMindTacticalSupport_0:anomBuildup': {
    sheet: 'YeShunguang',
    name: 'QuickAssistEnlightenedMindTacticalSupport_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistEnlightenedMindTacticalSupport_0',
    },
  },
  'AssistFollowUpEnlightenedMindUnification_0:standardDmg': {
    sheet: 'YeShunguang',
    name: 'AssistFollowUpEnlightenedMindUnification_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpEnlightenedMindUnification_0',
    },
  },
  'AssistFollowUpEnlightenedMindUnification_0:dazeBuildup': {
    sheet: 'YeShunguang',
    name: 'AssistFollowUpEnlightenedMindUnification_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpEnlightenedMindUnification_0',
    },
  },
  'AssistFollowUpEnlightenedMindUnification_0:anomBuildup': {
    sheet: 'YeShunguang',
    name: 'AssistFollowUpEnlightenedMindUnification_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpEnlightenedMindUnification_0',
    },
  },
} as const
