// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'YeShunguang',
    name: 'standardDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'standardDmgBase',
      sheet: 'YeShunguang',
      attribute: 'physical',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'YeShunguang',
    name: 'anomalyDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_physical: {
    sheet: 'YeShunguang',
    name: 'disorderDmgInst_physical',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'disorder',
      name: 'disorderDmgInst_physical',
    },
  },
  vortexDmgInst_physical: {
    sheet: 'YeShunguang',
    name: 'vortexDmgInst_physical',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'vortex',
      name: 'vortexDmgInst_physical',
    },
  },
  abloomDmgInst: {
    sheet: 'YeShunguang',
    name: 'abloomDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'YeShunguang',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'YeShunguang',
      attribute: 'physical',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'YeShunguang',
    name: 'dazeInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'dazeBuildupBase',
      sheet: 'YeShunguang',
      attribute: 'physical',
      name: 'dazeInst',
    },
  },
  BasicAttackSwiftedge_0: {
    sheet: 'YeShunguang',
    name: 'BasicAttackSwiftedge_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSwiftedge_0',
    },
  },
  BasicAttackSwiftedge_1: {
    sheet: 'YeShunguang',
    name: 'BasicAttackSwiftedge_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSwiftedge_1',
    },
  },
  BasicAttackSwiftedge_2: {
    sheet: 'YeShunguang',
    name: 'BasicAttackSwiftedge_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSwiftedge_2',
    },
  },
  BasicAttackSwiftedge_3: {
    sheet: 'YeShunguang',
    name: 'BasicAttackSwiftedge_3',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackSwiftedge_3',
    },
  },
  BasicAttackCloudstreamSwordWill_0: {
    sheet: 'YeShunguang',
    name: 'BasicAttackCloudstreamSwordWill_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackCloudstreamSwordWill_0',
    },
  },
  BasicAttackEnlightenedMindSplittingCurrents_0: {
    sheet: 'YeShunguang',
    name: 'BasicAttackEnlightenedMindSplittingCurrents_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEnlightenedMindSplittingCurrents_0',
    },
  },
  BasicAttackEnlightenedMindSplittingCurrents_1: {
    sheet: 'YeShunguang',
    name: 'BasicAttackEnlightenedMindSplittingCurrents_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEnlightenedMindSplittingCurrents_1',
    },
  },
  BasicAttackEnlightenedMindSplittingCurrents_2: {
    sheet: 'YeShunguang',
    name: 'BasicAttackEnlightenedMindSplittingCurrents_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEnlightenedMindSplittingCurrents_2',
    },
  },
  BasicAttackEnlightenedMindSkywardAscent_0: {
    sheet: 'YeShunguang',
    name: 'BasicAttackEnlightenedMindSkywardAscent_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEnlightenedMindSkywardAscent_0',
    },
  },
  BasicAttackEnlightenedMindSunderlightMaximum_0: {
    sheet: 'YeShunguang',
    name: 'BasicAttackEnlightenedMindSunderlightMaximum_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEnlightenedMindSunderlightMaximum_0',
    },
  },
  BasicAttackEnlightenedMindSunderlight_0: {
    sheet: 'YeShunguang',
    name: 'BasicAttackEnlightenedMindSunderlight_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEnlightenedMindSunderlight_0',
    },
  },
  BasicAttackEnlightenedMindSunderlight_1: {
    sheet: 'YeShunguang',
    name: 'BasicAttackEnlightenedMindSunderlight_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEnlightenedMindSunderlight_1',
    },
  },
  BasicAttackEnlightenedMindSunderlightAnnihilation_0: {
    sheet: 'YeShunguang',
    name: 'BasicAttackEnlightenedMindSunderlightAnnihilation_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEnlightenedMindSunderlightAnnihilation_0',
    },
  },
  BasicAttackEnlightenedMindSunderlightAnnihilation_1: {
    sheet: 'YeShunguang',
    name: 'BasicAttackEnlightenedMindSunderlightAnnihilation_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackEnlightenedMindSunderlightAnnihilation_1',
    },
  },
  DashAttackPhantasmDash_0: {
    sheet: 'YeShunguang',
    name: 'DashAttackPhantasmDash_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackPhantasmDash_0',
    },
  },
  DodgeCounterSwallowStrike_0: {
    sheet: 'YeShunguang',
    name: 'DodgeCounterSwallowStrike_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterSwallowStrike_0',
    },
  },
  SpecialAttackGuidingTides_0: {
    sheet: 'YeShunguang',
    name: 'SpecialAttackGuidingTides_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackGuidingTides_0',
    },
  },
  SpecialAttackGuidingTides_1: {
    sheet: 'YeShunguang',
    name: 'SpecialAttackGuidingTides_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackGuidingTides_1',
    },
  },
  EXSpecialAttackGaleSuppression_0: {
    sheet: 'YeShunguang',
    name: 'EXSpecialAttackGaleSuppression_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackGaleSuppression_0',
    },
  },
  SpecialAttackEnlightenedMindCleanExit_0: {
    sheet: 'YeShunguang',
    name: 'SpecialAttackEnlightenedMindCleanExit_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackEnlightenedMindCleanExit_0',
    },
  },
  EXSpecialAttackEnlightenedMindSoaringLight_0: {
    sheet: 'YeShunguang',
    name: 'EXSpecialAttackEnlightenedMindSoaringLight_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackEnlightenedMindSoaringLight_0',
    },
  },
  EXSpecialAttackEnlightenedMindReturnToDust_0: {
    sheet: 'YeShunguang',
    name: 'EXSpecialAttackEnlightenedMindReturnToDust_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackEnlightenedMindReturnToDust_0',
    },
  },
  ChainAttackSmiteTheWicked_0: {
    sheet: 'YeShunguang',
    name: 'ChainAttackSmiteTheWicked_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackSmiteTheWicked_0',
    },
  },
  UltimateChasingStorms_0: {
    sheet: 'YeShunguang',
    name: 'UltimateChasingStorms_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateChasingStorms_0',
    },
  },
  ChainAttackEnlightenedMindLureThunder_0: {
    sheet: 'YeShunguang',
    name: 'ChainAttackEnlightenedMindLureThunder_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackEnlightenedMindLureThunder_0',
    },
  },
  UltimateCleavingHeavens_0: {
    sheet: 'YeShunguang',
    name: 'UltimateCleavingHeavens_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateCleavingHeavens_0',
    },
  },
  EntrySkillIlluminatingDarkness_0: {
    sheet: 'YeShunguang',
    name: 'EntrySkillIlluminatingDarkness_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'entrySkill',
      skillType: 'assistSkill',
      name: 'EntrySkillIlluminatingDarkness_0',
    },
  },
  QuickAssistSupportGuard_0: {
    sheet: 'YeShunguang',
    name: 'QuickAssistSupportGuard_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistSupportGuard_0',
    },
  },
  AssistFollowUpCeaseHostility_0: {
    sheet: 'YeShunguang',
    name: 'AssistFollowUpCeaseHostility_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpCeaseHostility_0',
    },
  },
  DefensiveAssistWhenIReturn_0: {
    sheet: 'YeShunguang',
    name: 'DefensiveAssistWhenIReturn_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistWhenIReturn_0',
    },
  },
  DefensiveAssistWhenIReturn_1: {
    sheet: 'YeShunguang',
    name: 'DefensiveAssistWhenIReturn_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistWhenIReturn_1',
    },
  },
  DefensiveAssistWhenIReturn_2: {
    sheet: 'YeShunguang',
    name: 'DefensiveAssistWhenIReturn_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistWhenIReturn_2',
    },
  },
  QuickAssistEnlightenedMindTacticalSupport_0: {
    sheet: 'YeShunguang',
    name: 'QuickAssistEnlightenedMindTacticalSupport_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistEnlightenedMindTacticalSupport_0',
    },
  },
  AssistFollowUpEnlightenedMindUnification_0: {
    sheet: 'YeShunguang',
    name: 'AssistFollowUpEnlightenedMindUnification_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'YeShunguang',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpEnlightenedMindUnification_0',
    },
  },
} as const
