// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Sunna',
    name: 'standardDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'standardDmgBase',
      sheet: 'Sunna',
      attribute: 'physical',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Sunna',
    name: 'anomalyDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_physical: {
    sheet: 'Sunna',
    name: 'disorderDmgInst_physical',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'disorder',
      name: 'disorderDmgInst_physical',
    },
  },
  vortexDmgInst_physical: {
    sheet: 'Sunna',
    name: 'vortexDmgInst_physical',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'vortex',
      name: 'vortexDmgInst_physical',
    },
  },
  abloomDmgInst: {
    sheet: 'Sunna',
    name: 'abloomDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Sunna',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Sunna',
      attribute: 'physical',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Sunna',
    name: 'dazeInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'dazeBuildupBase',
      sheet: 'Sunna',
      attribute: 'physical',
      name: 'dazeInst',
    },
  },
  BasicAttackMischiefMeteorHammer_0: {
    sheet: 'Sunna',
    name: 'BasicAttackMischiefMeteorHammer_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackMischiefMeteorHammer_0',
    },
  },
  BasicAttackMischiefMeteorHammer_1: {
    sheet: 'Sunna',
    name: 'BasicAttackMischiefMeteorHammer_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackMischiefMeteorHammer_1',
    },
  },
  BasicAttackMischiefMeteorHammer_2: {
    sheet: 'Sunna',
    name: 'BasicAttackMischiefMeteorHammer_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackMischiefMeteorHammer_2',
    },
  },
  BasicAttackMischiefMeteorHammer_3: {
    sheet: 'Sunna',
    name: 'BasicAttackMischiefMeteorHammer_3',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackMischiefMeteorHammer_3',
    },
  },
  BasicAttackNaughtyCatSpotted_0: {
    sheet: 'Sunna',
    name: 'BasicAttackNaughtyCatSpotted_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackNaughtyCatSpotted_0',
    },
  },
  DashAttackSkywardHammer_0: {
    sheet: 'Sunna',
    name: 'DashAttackSkywardHammer_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackSkywardHammer_0',
    },
  },
  DodgeCounterDelusionStrikeout_0: {
    sheet: 'Sunna',
    name: 'DodgeCounterDelusionStrikeout_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterDelusionStrikeout_0',
    },
  },
  SpecialAttackStarShooter_0: {
    sheet: 'Sunna',
    name: 'SpecialAttackStarShooter_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackStarShooter_0',
    },
  },
  EXSpecialAttackBubblegumBarrage_0: {
    sheet: 'Sunna',
    name: 'EXSpecialAttackBubblegumBarrage_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackBubblegumBarrage_0',
    },
  },
  EXSpecialAttackBubblegumBarrage_1: {
    sheet: 'Sunna',
    name: 'EXSpecialAttackBubblegumBarrage_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackBubblegumBarrage_1',
    },
  },
  EXSpecialAttackSpecialPhotographyTechnique_0: {
    sheet: 'Sunna',
    name: 'EXSpecialAttackSpecialPhotographyTechnique_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackSpecialPhotographyTechnique_0',
    },
  },
  EXSpecialAttackSpecialPhotographyTechnique_1: {
    sheet: 'Sunna',
    name: 'EXSpecialAttackSpecialPhotographyTechnique_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackSpecialPhotographyTechnique_1',
    },
  },
  ChainAttackDontMessWithTheCat_0: {
    sheet: 'Sunna',
    name: 'ChainAttackDontMessWithTheCat_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackDontMessWithTheCat_0',
    },
  },
  UltimateSmashItAll_0: {
    sheet: 'Sunna',
    name: 'UltimateSmashItAll_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateSmashItAll_0',
    },
  },
  QuickAssistSonicBeatdown_0: {
    sheet: 'Sunna',
    name: 'QuickAssistSonicBeatdown_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistSonicBeatdown_0',
    },
  },
  DefensiveAssistStageFright_0: {
    sheet: 'Sunna',
    name: 'DefensiveAssistStageFright_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistStageFright_0',
    },
  },
  DefensiveAssistStageFright_1: {
    sheet: 'Sunna',
    name: 'DefensiveAssistStageFright_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistStageFright_1',
    },
  },
  DefensiveAssistStageFright_2: {
    sheet: 'Sunna',
    name: 'DefensiveAssistStageFright_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistStageFright_2',
    },
  },
  AssistFollowUpJumpTraining_0: {
    sheet: 'Sunna',
    name: 'AssistFollowUpJumpTraining_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpJumpTraining_0',
    },
  },
  ult_heal: {
    sheet: 'Sunna',
    name: 'ult_heal',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'healBase',
      sheet: 'Sunna',
      name: 'ult_heal',
    },
  },
  core_anomaly_physical_dmg: {
    sheet: 'Sunna',
    name: 'core_anomaly_physical_dmg',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'standardDmgBase',
      sheet: 'Sunna',
      attribute: 'physical',
      name: 'core_anomaly_physical_dmg',
    },
  },
  core_attack_physical_dmg: {
    sheet: 'Sunna',
    name: 'core_attack_physical_dmg',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'standardDmgBase',
      sheet: 'Sunna',
      attribute: 'physical',
      name: 'core_attack_physical_dmg',
    },
  },
  testForm: {
    sheet: 'Sunna',
    name: 'testForm',
    tag: {
      et: 'display',
      qt: 'final',
      q: 'atk',
      sheet: 'Sunna',
      name: 'testForm',
    },
  },
  m6_dmg: {
    sheet: 'Sunna',
    name: 'm6_dmg',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'standardDmgBase',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'elemental',
      name: 'm6_dmg',
    },
  },
} as const
