// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Sunna',
    name: 'standardDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Sunna',
      attribute: 'physical',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Sunna',
    name: 'anomalyDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_physical: {
    sheet: 'Sunna',
    name: 'disorderDmgInst_physical',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'disorder',
      name: 'disorderDmgInst_physical',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Sunna',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Sunna',
      attribute: 'physical',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Sunna',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Sunna',
      attribute: 'physical',
      name: 'dazeInst',
    },
  },
  BasicAttackMischiefMeteorHammer_0_dmg: {
    sheet: 'Sunna',
    name: 'BasicAttackMischiefMeteorHammer_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackMischiefMeteorHammer_0_dmg',
    },
  },
  BasicAttackMischiefMeteorHammer_0_daze: {
    sheet: 'Sunna',
    name: 'BasicAttackMischiefMeteorHammer_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackMischiefMeteorHammer_0_daze',
    },
  },
  BasicAttackMischiefMeteorHammer_0_anomBuildup: {
    sheet: 'Sunna',
    name: 'BasicAttackMischiefMeteorHammer_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackMischiefMeteorHammer_0_anomBuildup',
    },
  },
  BasicAttackMischiefMeteorHammer_1_dmg: {
    sheet: 'Sunna',
    name: 'BasicAttackMischiefMeteorHammer_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackMischiefMeteorHammer_1_dmg',
    },
  },
  BasicAttackMischiefMeteorHammer_1_daze: {
    sheet: 'Sunna',
    name: 'BasicAttackMischiefMeteorHammer_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackMischiefMeteorHammer_1_daze',
    },
  },
  BasicAttackMischiefMeteorHammer_1_anomBuildup: {
    sheet: 'Sunna',
    name: 'BasicAttackMischiefMeteorHammer_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackMischiefMeteorHammer_1_anomBuildup',
    },
  },
  BasicAttackMischiefMeteorHammer_2_dmg: {
    sheet: 'Sunna',
    name: 'BasicAttackMischiefMeteorHammer_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackMischiefMeteorHammer_2_dmg',
    },
  },
  BasicAttackMischiefMeteorHammer_2_daze: {
    sheet: 'Sunna',
    name: 'BasicAttackMischiefMeteorHammer_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackMischiefMeteorHammer_2_daze',
    },
  },
  BasicAttackMischiefMeteorHammer_2_anomBuildup: {
    sheet: 'Sunna',
    name: 'BasicAttackMischiefMeteorHammer_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackMischiefMeteorHammer_2_anomBuildup',
    },
  },
  BasicAttackMischiefMeteorHammer_3_dmg: {
    sheet: 'Sunna',
    name: 'BasicAttackMischiefMeteorHammer_3_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackMischiefMeteorHammer_3_dmg',
    },
  },
  BasicAttackMischiefMeteorHammer_3_daze: {
    sheet: 'Sunna',
    name: 'BasicAttackMischiefMeteorHammer_3_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackMischiefMeteorHammer_3_daze',
    },
  },
  BasicAttackMischiefMeteorHammer_3_anomBuildup: {
    sheet: 'Sunna',
    name: 'BasicAttackMischiefMeteorHammer_3_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackMischiefMeteorHammer_3_anomBuildup',
    },
  },
  BasicAttackNaughtyCatSpotted_0_dmg: {
    sheet: 'Sunna',
    name: 'BasicAttackNaughtyCatSpotted_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackNaughtyCatSpotted_0_dmg',
    },
  },
  BasicAttackNaughtyCatSpotted_0_daze: {
    sheet: 'Sunna',
    name: 'BasicAttackNaughtyCatSpotted_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackNaughtyCatSpotted_0_daze',
    },
  },
  BasicAttackNaughtyCatSpotted_0_anomBuildup: {
    sheet: 'Sunna',
    name: 'BasicAttackNaughtyCatSpotted_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackNaughtyCatSpotted_0_anomBuildup',
    },
  },
  DashAttackSkywardHammer_0_dmg: {
    sheet: 'Sunna',
    name: 'DashAttackSkywardHammer_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackSkywardHammer_0_dmg',
    },
  },
  DashAttackSkywardHammer_0_daze: {
    sheet: 'Sunna',
    name: 'DashAttackSkywardHammer_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackSkywardHammer_0_daze',
    },
  },
  DashAttackSkywardHammer_0_anomBuildup: {
    sheet: 'Sunna',
    name: 'DashAttackSkywardHammer_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackSkywardHammer_0_anomBuildup',
    },
  },
  DodgeCounterDelusionStrikeout_0_dmg: {
    sheet: 'Sunna',
    name: 'DodgeCounterDelusionStrikeout_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterDelusionStrikeout_0_dmg',
    },
  },
  DodgeCounterDelusionStrikeout_0_daze: {
    sheet: 'Sunna',
    name: 'DodgeCounterDelusionStrikeout_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterDelusionStrikeout_0_daze',
    },
  },
  DodgeCounterDelusionStrikeout_0_anomBuildup: {
    sheet: 'Sunna',
    name: 'DodgeCounterDelusionStrikeout_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterDelusionStrikeout_0_anomBuildup',
    },
  },
  SpecialAttackStarShooter_0_dmg: {
    sheet: 'Sunna',
    name: 'SpecialAttackStarShooter_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackStarShooter_0_dmg',
    },
  },
  SpecialAttackStarShooter_0_daze: {
    sheet: 'Sunna',
    name: 'SpecialAttackStarShooter_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackStarShooter_0_daze',
    },
  },
  SpecialAttackStarShooter_0_anomBuildup: {
    sheet: 'Sunna',
    name: 'SpecialAttackStarShooter_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackStarShooter_0_anomBuildup',
    },
  },
  EXSpecialAttackBubblegumBarrage_0_dmg: {
    sheet: 'Sunna',
    name: 'EXSpecialAttackBubblegumBarrage_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackBubblegumBarrage_0_dmg',
    },
  },
  EXSpecialAttackBubblegumBarrage_0_daze: {
    sheet: 'Sunna',
    name: 'EXSpecialAttackBubblegumBarrage_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackBubblegumBarrage_0_daze',
    },
  },
  EXSpecialAttackBubblegumBarrage_0_anomBuildup: {
    sheet: 'Sunna',
    name: 'EXSpecialAttackBubblegumBarrage_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackBubblegumBarrage_0_anomBuildup',
    },
  },
  EXSpecialAttackBubblegumBarrage_1_dmg: {
    sheet: 'Sunna',
    name: 'EXSpecialAttackBubblegumBarrage_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackBubblegumBarrage_1_dmg',
    },
  },
  EXSpecialAttackBubblegumBarrage_1_daze: {
    sheet: 'Sunna',
    name: 'EXSpecialAttackBubblegumBarrage_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackBubblegumBarrage_1_daze',
    },
  },
  EXSpecialAttackBubblegumBarrage_1_anomBuildup: {
    sheet: 'Sunna',
    name: 'EXSpecialAttackBubblegumBarrage_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackBubblegumBarrage_1_anomBuildup',
    },
  },
  EXSpecialAttackSpecialPhotographyTechnique_0_dmg: {
    sheet: 'Sunna',
    name: 'EXSpecialAttackSpecialPhotographyTechnique_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackSpecialPhotographyTechnique_0_dmg',
    },
  },
  EXSpecialAttackSpecialPhotographyTechnique_0_daze: {
    sheet: 'Sunna',
    name: 'EXSpecialAttackSpecialPhotographyTechnique_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackSpecialPhotographyTechnique_0_daze',
    },
  },
  EXSpecialAttackSpecialPhotographyTechnique_0_anomBuildup: {
    sheet: 'Sunna',
    name: 'EXSpecialAttackSpecialPhotographyTechnique_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackSpecialPhotographyTechnique_0_anomBuildup',
    },
  },
  EXSpecialAttackSpecialPhotographyTechnique_1_dmg: {
    sheet: 'Sunna',
    name: 'EXSpecialAttackSpecialPhotographyTechnique_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackSpecialPhotographyTechnique_1_dmg',
    },
  },
  EXSpecialAttackSpecialPhotographyTechnique_1_daze: {
    sheet: 'Sunna',
    name: 'EXSpecialAttackSpecialPhotographyTechnique_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackSpecialPhotographyTechnique_1_daze',
    },
  },
  EXSpecialAttackSpecialPhotographyTechnique_1_anomBuildup: {
    sheet: 'Sunna',
    name: 'EXSpecialAttackSpecialPhotographyTechnique_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackSpecialPhotographyTechnique_1_anomBuildup',
    },
  },
  ChainAttackDontMessWithTheCat_0_dmg: {
    sheet: 'Sunna',
    name: 'ChainAttackDontMessWithTheCat_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackDontMessWithTheCat_0_dmg',
    },
  },
  ChainAttackDontMessWithTheCat_0_daze: {
    sheet: 'Sunna',
    name: 'ChainAttackDontMessWithTheCat_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackDontMessWithTheCat_0_daze',
    },
  },
  ChainAttackDontMessWithTheCat_0_anomBuildup: {
    sheet: 'Sunna',
    name: 'ChainAttackDontMessWithTheCat_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackDontMessWithTheCat_0_anomBuildup',
    },
  },
  UltimateSmashItAll_0_dmg: {
    sheet: 'Sunna',
    name: 'UltimateSmashItAll_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateSmashItAll_0_dmg',
    },
  },
  UltimateSmashItAll_0_daze: {
    sheet: 'Sunna',
    name: 'UltimateSmashItAll_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateSmashItAll_0_daze',
    },
  },
  UltimateSmashItAll_0_anomBuildup: {
    sheet: 'Sunna',
    name: 'UltimateSmashItAll_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateSmashItAll_0_anomBuildup',
    },
  },
  QuickAssistSonicBeatdown_0_dmg: {
    sheet: 'Sunna',
    name: 'QuickAssistSonicBeatdown_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistSonicBeatdown_0_dmg',
    },
  },
  QuickAssistSonicBeatdown_0_daze: {
    sheet: 'Sunna',
    name: 'QuickAssistSonicBeatdown_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistSonicBeatdown_0_daze',
    },
  },
  QuickAssistSonicBeatdown_0_anomBuildup: {
    sheet: 'Sunna',
    name: 'QuickAssistSonicBeatdown_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistSonicBeatdown_0_anomBuildup',
    },
  },
  DefensiveAssistStageFright_0_dmg: {
    sheet: 'Sunna',
    name: 'DefensiveAssistStageFright_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistStageFright_0_dmg',
    },
  },
  DefensiveAssistStageFright_0_daze: {
    sheet: 'Sunna',
    name: 'DefensiveAssistStageFright_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistStageFright_0_daze',
    },
  },
  DefensiveAssistStageFright_0_anomBuildup: {
    sheet: 'Sunna',
    name: 'DefensiveAssistStageFright_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistStageFright_0_anomBuildup',
    },
  },
  DefensiveAssistStageFright_1_dmg: {
    sheet: 'Sunna',
    name: 'DefensiveAssistStageFright_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistStageFright_1_dmg',
    },
  },
  DefensiveAssistStageFright_1_daze: {
    sheet: 'Sunna',
    name: 'DefensiveAssistStageFright_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistStageFright_1_daze',
    },
  },
  DefensiveAssistStageFright_1_anomBuildup: {
    sheet: 'Sunna',
    name: 'DefensiveAssistStageFright_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistStageFright_1_anomBuildup',
    },
  },
  DefensiveAssistStageFright_2_dmg: {
    sheet: 'Sunna',
    name: 'DefensiveAssistStageFright_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistStageFright_2_dmg',
    },
  },
  DefensiveAssistStageFright_2_daze: {
    sheet: 'Sunna',
    name: 'DefensiveAssistStageFright_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistStageFright_2_daze',
    },
  },
  DefensiveAssistStageFright_2_anomBuildup: {
    sheet: 'Sunna',
    name: 'DefensiveAssistStageFright_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistStageFright_2_anomBuildup',
    },
  },
  AssistFollowUpJumpTraining_0_dmg: {
    sheet: 'Sunna',
    name: 'AssistFollowUpJumpTraining_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpJumpTraining_0_dmg',
    },
  },
  AssistFollowUpJumpTraining_0_daze: {
    sheet: 'Sunna',
    name: 'AssistFollowUpJumpTraining_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpJumpTraining_0_daze',
    },
  },
  AssistFollowUpJumpTraining_0_anomBuildup: {
    sheet: 'Sunna',
    name: 'AssistFollowUpJumpTraining_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Sunna',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpJumpTraining_0_anomBuildup',
    },
  },
} as const
