// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Piper',
    name: 'standardDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Piper',
      attribute: 'physical',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Piper',
    name: 'anomalyDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Piper',
      attribute: 'physical',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_physical: {
    sheet: 'Piper',
    name: 'disorderDmgInst_physical',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Piper',
      attribute: 'physical',
      damageType1: 'disorder',
      name: 'disorderDmgInst_physical',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Piper',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Piper',
      attribute: 'physical',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Piper',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Piper',
      attribute: 'physical',
      name: 'dazeInst',
    },
  },
  BasicAttackLoadUpAndRollOut_0_dmg: {
    sheet: 'Piper',
    name: 'BasicAttackLoadUpAndRollOut_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Piper',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLoadUpAndRollOut_0_dmg',
    },
  },
  BasicAttackLoadUpAndRollOut_0_daze: {
    sheet: 'Piper',
    name: 'BasicAttackLoadUpAndRollOut_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Piper',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLoadUpAndRollOut_0_daze',
    },
  },
  BasicAttackLoadUpAndRollOut_0_anomBuildup: {
    sheet: 'Piper',
    name: 'BasicAttackLoadUpAndRollOut_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Piper',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLoadUpAndRollOut_0_anomBuildup',
    },
  },
  BasicAttackLoadUpAndRollOut_1_dmg: {
    sheet: 'Piper',
    name: 'BasicAttackLoadUpAndRollOut_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Piper',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLoadUpAndRollOut_1_dmg',
    },
  },
  BasicAttackLoadUpAndRollOut_1_daze: {
    sheet: 'Piper',
    name: 'BasicAttackLoadUpAndRollOut_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Piper',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLoadUpAndRollOut_1_daze',
    },
  },
  BasicAttackLoadUpAndRollOut_1_anomBuildup: {
    sheet: 'Piper',
    name: 'BasicAttackLoadUpAndRollOut_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Piper',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLoadUpAndRollOut_1_anomBuildup',
    },
  },
  BasicAttackLoadUpAndRollOut_2_dmg: {
    sheet: 'Piper',
    name: 'BasicAttackLoadUpAndRollOut_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Piper',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLoadUpAndRollOut_2_dmg',
    },
  },
  BasicAttackLoadUpAndRollOut_2_daze: {
    sheet: 'Piper',
    name: 'BasicAttackLoadUpAndRollOut_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Piper',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLoadUpAndRollOut_2_daze',
    },
  },
  BasicAttackLoadUpAndRollOut_2_anomBuildup: {
    sheet: 'Piper',
    name: 'BasicAttackLoadUpAndRollOut_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Piper',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLoadUpAndRollOut_2_anomBuildup',
    },
  },
  BasicAttackLoadUpAndRollOut_3_dmg: {
    sheet: 'Piper',
    name: 'BasicAttackLoadUpAndRollOut_3_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Piper',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLoadUpAndRollOut_3_dmg',
    },
  },
  BasicAttackLoadUpAndRollOut_3_daze: {
    sheet: 'Piper',
    name: 'BasicAttackLoadUpAndRollOut_3_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Piper',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLoadUpAndRollOut_3_daze',
    },
  },
  BasicAttackLoadUpAndRollOut_3_anomBuildup: {
    sheet: 'Piper',
    name: 'BasicAttackLoadUpAndRollOut_3_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Piper',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLoadUpAndRollOut_3_anomBuildup',
    },
  },
  DashAttackPedalToTheMetal_0_dmg: {
    sheet: 'Piper',
    name: 'DashAttackPedalToTheMetal_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Piper',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackPedalToTheMetal_0_dmg',
    },
  },
  DashAttackPedalToTheMetal_0_daze: {
    sheet: 'Piper',
    name: 'DashAttackPedalToTheMetal_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Piper',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackPedalToTheMetal_0_daze',
    },
  },
  DashAttackPedalToTheMetal_0_anomBuildup: {
    sheet: 'Piper',
    name: 'DashAttackPedalToTheMetal_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Piper',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackPedalToTheMetal_0_anomBuildup',
    },
  },
  DodgeCounterPowerDrift_0_dmg: {
    sheet: 'Piper',
    name: 'DodgeCounterPowerDrift_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Piper',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterPowerDrift_0_dmg',
    },
  },
  DodgeCounterPowerDrift_0_daze: {
    sheet: 'Piper',
    name: 'DodgeCounterPowerDrift_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Piper',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterPowerDrift_0_daze',
    },
  },
  DodgeCounterPowerDrift_0_anomBuildup: {
    sheet: 'Piper',
    name: 'DodgeCounterPowerDrift_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Piper',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterPowerDrift_0_anomBuildup',
    },
  },
  SpecialAttackTireSpin_0_dmg: {
    sheet: 'Piper',
    name: 'SpecialAttackTireSpin_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Piper',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackTireSpin_0_dmg',
    },
  },
  SpecialAttackTireSpin_0_daze: {
    sheet: 'Piper',
    name: 'SpecialAttackTireSpin_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Piper',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackTireSpin_0_daze',
    },
  },
  SpecialAttackTireSpin_0_anomBuildup: {
    sheet: 'Piper',
    name: 'SpecialAttackTireSpin_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Piper',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackTireSpin_0_anomBuildup',
    },
  },
  SpecialAttackOneTrillionTons_0_dmg: {
    sheet: 'Piper',
    name: 'SpecialAttackOneTrillionTons_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Piper',
      damageType1: 'special',
      attribute: 'physical',
      name: 'SpecialAttackOneTrillionTons_0_dmg',
    },
  },
  SpecialAttackOneTrillionTons_0_daze: {
    sheet: 'Piper',
    name: 'SpecialAttackOneTrillionTons_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Piper',
      damageType1: 'special',
      attribute: 'physical',
      name: 'SpecialAttackOneTrillionTons_0_daze',
    },
  },
  SpecialAttackOneTrillionTons_0_anomBuildup: {
    sheet: 'Piper',
    name: 'SpecialAttackOneTrillionTons_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Piper',
      damageType1: 'special',
      attribute: 'physical',
      name: 'SpecialAttackOneTrillionTons_0_anomBuildup',
    },
  },
  SpecialAttackOneTrillionTons_1_dmg: {
    sheet: 'Piper',
    name: 'SpecialAttackOneTrillionTons_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Piper',
      damageType1: 'special',
      attribute: 'physical',
      name: 'SpecialAttackOneTrillionTons_1_dmg',
    },
  },
  SpecialAttackOneTrillionTons_1_daze: {
    sheet: 'Piper',
    name: 'SpecialAttackOneTrillionTons_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Piper',
      damageType1: 'special',
      attribute: 'physical',
      name: 'SpecialAttackOneTrillionTons_1_daze',
    },
  },
  SpecialAttackOneTrillionTons_1_anomBuildup: {
    sheet: 'Piper',
    name: 'SpecialAttackOneTrillionTons_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Piper',
      damageType1: 'special',
      attribute: 'physical',
      name: 'SpecialAttackOneTrillionTons_1_anomBuildup',
    },
  },
  SpecialAttackOneTrillionTons_2_dmg: {
    sheet: 'Piper',
    name: 'SpecialAttackOneTrillionTons_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Piper',
      damageType1: 'special',
      attribute: 'physical',
      name: 'SpecialAttackOneTrillionTons_2_dmg',
    },
  },
  SpecialAttackOneTrillionTons_2_daze: {
    sheet: 'Piper',
    name: 'SpecialAttackOneTrillionTons_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Piper',
      damageType1: 'special',
      attribute: 'physical',
      name: 'SpecialAttackOneTrillionTons_2_daze',
    },
  },
  SpecialAttackOneTrillionTons_2_anomBuildup: {
    sheet: 'Piper',
    name: 'SpecialAttackOneTrillionTons_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Piper',
      damageType1: 'special',
      attribute: 'physical',
      name: 'SpecialAttackOneTrillionTons_2_anomBuildup',
    },
  },
  EXSpecialAttackEngineSpin_0_dmg: {
    sheet: 'Piper',
    name: 'EXSpecialAttackEngineSpin_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Piper',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackEngineSpin_0_dmg',
    },
  },
  EXSpecialAttackEngineSpin_0_daze: {
    sheet: 'Piper',
    name: 'EXSpecialAttackEngineSpin_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Piper',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackEngineSpin_0_daze',
    },
  },
  EXSpecialAttackEngineSpin_0_anomBuildup: {
    sheet: 'Piper',
    name: 'EXSpecialAttackEngineSpin_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Piper',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackEngineSpin_0_anomBuildup',
    },
  },
  EXSpecialAttackReallyHeavy_0_dmg: {
    sheet: 'Piper',
    name: 'EXSpecialAttackReallyHeavy_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Piper',
      damageType1: 'exSpecial',
      attribute: 'physical',
      name: 'EXSpecialAttackReallyHeavy_0_dmg',
    },
  },
  EXSpecialAttackReallyHeavy_0_daze: {
    sheet: 'Piper',
    name: 'EXSpecialAttackReallyHeavy_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Piper',
      damageType1: 'exSpecial',
      attribute: 'physical',
      name: 'EXSpecialAttackReallyHeavy_0_daze',
    },
  },
  EXSpecialAttackReallyHeavy_0_anomBuildup: {
    sheet: 'Piper',
    name: 'EXSpecialAttackReallyHeavy_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Piper',
      damageType1: 'exSpecial',
      attribute: 'physical',
      name: 'EXSpecialAttackReallyHeavy_0_anomBuildup',
    },
  },
  ChainAttackBuckleUp_0_dmg: {
    sheet: 'Piper',
    name: 'ChainAttackBuckleUp_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Piper',
      attribute: 'physical',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackBuckleUp_0_dmg',
    },
  },
  ChainAttackBuckleUp_0_daze: {
    sheet: 'Piper',
    name: 'ChainAttackBuckleUp_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Piper',
      attribute: 'physical',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackBuckleUp_0_daze',
    },
  },
  ChainAttackBuckleUp_0_anomBuildup: {
    sheet: 'Piper',
    name: 'ChainAttackBuckleUp_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Piper',
      attribute: 'physical',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackBuckleUp_0_anomBuildup',
    },
  },
  UltimateHoldOnTight_0_dmg: {
    sheet: 'Piper',
    name: 'UltimateHoldOnTight_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Piper',
      damageType1: 'ult',
      attribute: 'physical',
      name: 'UltimateHoldOnTight_0_dmg',
    },
  },
  UltimateHoldOnTight_0_daze: {
    sheet: 'Piper',
    name: 'UltimateHoldOnTight_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Piper',
      damageType1: 'ult',
      attribute: 'physical',
      name: 'UltimateHoldOnTight_0_daze',
    },
  },
  UltimateHoldOnTight_0_anomBuildup: {
    sheet: 'Piper',
    name: 'UltimateHoldOnTight_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Piper',
      damageType1: 'ult',
      attribute: 'physical',
      name: 'UltimateHoldOnTight_0_anomBuildup',
    },
  },
  QuickAssistBrakeTap_0_dmg: {
    sheet: 'Piper',
    name: 'QuickAssistBrakeTap_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Piper',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistBrakeTap_0_dmg',
    },
  },
  QuickAssistBrakeTap_0_daze: {
    sheet: 'Piper',
    name: 'QuickAssistBrakeTap_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Piper',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistBrakeTap_0_daze',
    },
  },
  QuickAssistBrakeTap_0_anomBuildup: {
    sheet: 'Piper',
    name: 'QuickAssistBrakeTap_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Piper',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistBrakeTap_0_anomBuildup',
    },
  },
  DefensiveAssistEmergencyBrake_0_dmg: {
    sheet: 'Piper',
    name: 'DefensiveAssistEmergencyBrake_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Piper',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistEmergencyBrake_0_dmg',
    },
  },
  DefensiveAssistEmergencyBrake_0_daze: {
    sheet: 'Piper',
    name: 'DefensiveAssistEmergencyBrake_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Piper',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistEmergencyBrake_0_daze',
    },
  },
  DefensiveAssistEmergencyBrake_0_anomBuildup: {
    sheet: 'Piper',
    name: 'DefensiveAssistEmergencyBrake_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Piper',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistEmergencyBrake_0_anomBuildup',
    },
  },
  DefensiveAssistEmergencyBrake_1_dmg: {
    sheet: 'Piper',
    name: 'DefensiveAssistEmergencyBrake_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Piper',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistEmergencyBrake_1_dmg',
    },
  },
  DefensiveAssistEmergencyBrake_1_daze: {
    sheet: 'Piper',
    name: 'DefensiveAssistEmergencyBrake_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Piper',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistEmergencyBrake_1_daze',
    },
  },
  DefensiveAssistEmergencyBrake_1_anomBuildup: {
    sheet: 'Piper',
    name: 'DefensiveAssistEmergencyBrake_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Piper',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistEmergencyBrake_1_anomBuildup',
    },
  },
  DefensiveAssistEmergencyBrake_2_dmg: {
    sheet: 'Piper',
    name: 'DefensiveAssistEmergencyBrake_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Piper',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistEmergencyBrake_2_dmg',
    },
  },
  DefensiveAssistEmergencyBrake_2_daze: {
    sheet: 'Piper',
    name: 'DefensiveAssistEmergencyBrake_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Piper',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistEmergencyBrake_2_daze',
    },
  },
  DefensiveAssistEmergencyBrake_2_anomBuildup: {
    sheet: 'Piper',
    name: 'DefensiveAssistEmergencyBrake_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Piper',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistEmergencyBrake_2_anomBuildup',
    },
  },
  AssistFollowUpOvertakingManeuver_0_dmg: {
    sheet: 'Piper',
    name: 'AssistFollowUpOvertakingManeuver_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Piper',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpOvertakingManeuver_0_dmg',
    },
  },
  AssistFollowUpOvertakingManeuver_0_daze: {
    sheet: 'Piper',
    name: 'AssistFollowUpOvertakingManeuver_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Piper',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpOvertakingManeuver_0_daze',
    },
  },
  AssistFollowUpOvertakingManeuver_0_anomBuildup: {
    sheet: 'Piper',
    name: 'AssistFollowUpOvertakingManeuver_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Piper',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpOvertakingManeuver_0_anomBuildup',
    },
  },
} as const
