// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'ZhuYuan',
    name: 'standardDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'standardDmgBase',
      sheet: 'ZhuYuan',
      attribute: 'ether',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'ZhuYuan',
    name: 'anomalyDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'ZhuYuan',
      attribute: 'ether',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_ether: {
    sheet: 'ZhuYuan',
    name: 'disorderDmgInst_ether',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'ZhuYuan',
      attribute: 'ether',
      damageType1: 'disorder',
      name: 'disorderDmgInst_ether',
    },
  },
  vortexDmgInst_ether: {
    sheet: 'ZhuYuan',
    name: 'vortexDmgInst_ether',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'ZhuYuan',
      attribute: 'ether',
      damageType1: 'vortex',
      name: 'vortexDmgInst_ether',
    },
  },
  abloomDmgInst: {
    sheet: 'ZhuYuan',
    name: 'abloomDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'ZhuYuan',
      attribute: 'ether',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'ZhuYuan',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'ZhuYuan',
      attribute: 'ether',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'ZhuYuan',
    name: 'dazeInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'dazeBuildupBase',
      sheet: 'ZhuYuan',
      attribute: 'ether',
      name: 'dazeInst',
    },
  },
  BasicAttackDontMove_0: {
    sheet: 'ZhuYuan',
    name: 'BasicAttackDontMove_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'ZhuYuan',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackDontMove_0',
    },
  },
  BasicAttackDontMove_1: {
    sheet: 'ZhuYuan',
    name: 'BasicAttackDontMove_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'ZhuYuan',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackDontMove_1',
    },
  },
  BasicAttackDontMove_2: {
    sheet: 'ZhuYuan',
    name: 'BasicAttackDontMove_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'ZhuYuan',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackDontMove_2',
    },
  },
  BasicAttackDontMove_3: {
    sheet: 'ZhuYuan',
    name: 'BasicAttackDontMove_3',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'ZhuYuan',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackDontMove_3',
    },
  },
  BasicAttackDontMove_4: {
    sheet: 'ZhuYuan',
    name: 'BasicAttackDontMove_4',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'ZhuYuan',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackDontMove_4',
    },
  },
  BasicAttackPleaseDoNotResist_0: {
    sheet: 'ZhuYuan',
    name: 'BasicAttackPleaseDoNotResist_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'ZhuYuan',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackPleaseDoNotResist_0',
    },
  },
  BasicAttackPleaseDoNotResist_1: {
    sheet: 'ZhuYuan',
    name: 'BasicAttackPleaseDoNotResist_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'ZhuYuan',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackPleaseDoNotResist_1',
    },
  },
  BasicAttackPleaseDoNotResist_2: {
    sheet: 'ZhuYuan',
    name: 'BasicAttackPleaseDoNotResist_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'ZhuYuan',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackPleaseDoNotResist_2',
    },
  },
  BasicAttackPleaseDoNotResist_3: {
    sheet: 'ZhuYuan',
    name: 'BasicAttackPleaseDoNotResist_3',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'ZhuYuan',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPleaseDoNotResist_3',
    },
  },
  BasicAttackPleaseDoNotResist_4: {
    sheet: 'ZhuYuan',
    name: 'BasicAttackPleaseDoNotResist_4',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'ZhuYuan',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPleaseDoNotResist_4',
    },
  },
  BasicAttackPleaseDoNotResist_5: {
    sheet: 'ZhuYuan',
    name: 'BasicAttackPleaseDoNotResist_5',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'ZhuYuan',
      attribute: 'ether',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackPleaseDoNotResist_5',
    },
  },
  DashAttackFirepowerOffensive_0: {
    sheet: 'ZhuYuan',
    name: 'DashAttackFirepowerOffensive_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'ZhuYuan',
      attribute: 'ether',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackFirepowerOffensive_0',
    },
  },
  DashAttackOverwhelmingFirepower_0: {
    sheet: 'ZhuYuan',
    name: 'DashAttackOverwhelmingFirepower_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'ZhuYuan',
      damageType1: 'dash',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttackOverwhelmingFirepower_0',
    },
  },
  DashAttackOverwhelmingFirepower_1: {
    sheet: 'ZhuYuan',
    name: 'DashAttackOverwhelmingFirepower_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'ZhuYuan',
      attribute: 'ether',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackOverwhelmingFirepower_1',
    },
  },
  DodgeCounterFireBlast_0: {
    sheet: 'ZhuYuan',
    name: 'DodgeCounterFireBlast_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'ZhuYuan',
      attribute: 'ether',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterFireBlast_0',
    },
  },
  SpecialAttackBuckshotBlast_0: {
    sheet: 'ZhuYuan',
    name: 'SpecialAttackBuckshotBlast_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'ZhuYuan',
      attribute: 'ether',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackBuckshotBlast_0',
    },
  },
  EXSpecialAttackFullBarrage_0: {
    sheet: 'ZhuYuan',
    name: 'EXSpecialAttackFullBarrage_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'ZhuYuan',
      attribute: 'ether',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackFullBarrage_0',
    },
  },
  ChainAttackEradicationMode_0: {
    sheet: 'ZhuYuan',
    name: 'ChainAttackEradicationMode_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'ZhuYuan',
      attribute: 'ether',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackEradicationMode_0',
    },
  },
  UltimateMaxEradicationMode_0: {
    sheet: 'ZhuYuan',
    name: 'UltimateMaxEradicationMode_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'ZhuYuan',
      attribute: 'ether',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateMaxEradicationMode_0',
    },
  },
  QuickAssistCoveringShot_0: {
    sheet: 'ZhuYuan',
    name: 'QuickAssistCoveringShot_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'ZhuYuan',
      attribute: 'ether',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistCoveringShot_0',
    },
  },
  AssistFollowUpDefensiveCounter_0: {
    sheet: 'ZhuYuan',
    name: 'AssistFollowUpDefensiveCounter_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'ZhuYuan',
      attribute: 'ether',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpDefensiveCounter_0',
    },
  },
  m6_ether_afterglow: {
    sheet: 'ZhuYuan',
    name: 'm6_ether_afterglow',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'standardDmgBase',
      sheet: 'ZhuYuan',
      attribute: 'ether',
      damageType1: 'elemental',
      name: 'm6_ether_afterglow',
    },
  },
} as const
