// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'PanYinhu',
    name: 'standardDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'standardDmgBase',
      sheet: 'PanYinhu',
      attribute: 'physical',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'PanYinhu',
    name: 'anomalyDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_physical: {
    sheet: 'PanYinhu',
    name: 'disorderDmgInst_physical',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'disorder',
      name: 'disorderDmgInst_physical',
    },
  },
  vortexDmgInst_physical: {
    sheet: 'PanYinhu',
    name: 'vortexDmgInst_physical',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'vortex',
      name: 'vortexDmgInst_physical',
    },
  },
  abloomDmgInst: {
    sheet: 'PanYinhu',
    name: 'abloomDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'PanYinhu',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'PanYinhu',
      attribute: 'physical',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'PanYinhu',
    name: 'dazeInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'dazeBuildupBase',
      sheet: 'PanYinhu',
      attribute: 'physical',
      name: 'dazeInst',
    },
  },
  BasicAttackUnyieldingStrikes_0: {
    sheet: 'PanYinhu',
    name: 'BasicAttackUnyieldingStrikes_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackUnyieldingStrikes_0',
    },
  },
  BasicAttackUnyieldingStrikes_1: {
    sheet: 'PanYinhu',
    name: 'BasicAttackUnyieldingStrikes_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackUnyieldingStrikes_1',
    },
  },
  BasicAttackUnyieldingStrikes_2: {
    sheet: 'PanYinhu',
    name: 'BasicAttackUnyieldingStrikes_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackUnyieldingStrikes_2',
    },
  },
  BasicAttackUnyieldingStrikes_3: {
    sheet: 'PanYinhu',
    name: 'BasicAttackUnyieldingStrikes_3',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackUnyieldingStrikes_3',
    },
  },
  DashAttackSizzlingOilSupreme_0: {
    sheet: 'PanYinhu',
    name: 'DashAttackSizzlingOilSupreme_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackSizzlingOilSupreme_0',
    },
  },
  DodgeCounterMovingMountainsAndSeas_0: {
    sheet: 'PanYinhu',
    name: 'DodgeCounterMovingMountainsAndSeas_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterMovingMountainsAndSeas_0',
    },
  },
  SpecialAttackSonicPressurePointStrike_0: {
    sheet: 'PanYinhu',
    name: 'SpecialAttackSonicPressurePointStrike_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackSonicPressurePointStrike_0',
    },
  },
  SpecialAttackTouchOfDeath_0: {
    sheet: 'PanYinhu',
    name: 'SpecialAttackTouchOfDeath_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackTouchOfDeath_0',
    },
  },
  SpecialAttackTouchOfDeath_1: {
    sheet: 'PanYinhu',
    name: 'SpecialAttackTouchOfDeath_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackTouchOfDeath_1',
    },
  },
  SpecialAttackTouchOfDeath_2: {
    sheet: 'PanYinhu',
    name: 'SpecialAttackTouchOfDeath_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackTouchOfDeath_2',
    },
  },
  EXSpecialAttackMountainousPulseStrike_0: {
    sheet: 'PanYinhu',
    name: 'EXSpecialAttackMountainousPulseStrike_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackMountainousPulseStrike_0',
    },
  },
  ChainAttackAnointedWithWokSteam_0: {
    sheet: 'PanYinhu',
    name: 'ChainAttackAnointedWithWokSteam_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackAnointedWithWokSteam_0',
    },
  },
  UltimateAFeastFitForAnEmperor_0: {
    sheet: 'PanYinhu',
    name: 'UltimateAFeastFitForAnEmperor_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateAFeastFitForAnEmperor_0',
    },
  },
  QuickAssistLiftYourGazeToGoodFortune_0: {
    sheet: 'PanYinhu',
    name: 'QuickAssistLiftYourGazeToGoodFortune_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistLiftYourGazeToGoodFortune_0',
    },
  },
  DefensiveAssistIntimidatingPresence_0: {
    sheet: 'PanYinhu',
    name: 'DefensiveAssistIntimidatingPresence_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistIntimidatingPresence_0',
    },
  },
  DefensiveAssistIntimidatingPresence_1: {
    sheet: 'PanYinhu',
    name: 'DefensiveAssistIntimidatingPresence_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistIntimidatingPresence_1',
    },
  },
  DefensiveAssistIntimidatingPresence_2: {
    sheet: 'PanYinhu',
    name: 'DefensiveAssistIntimidatingPresence_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistIntimidatingPresence_2',
    },
  },
  AssistFollowUpRideTheMomentum_0: {
    sheet: 'PanYinhu',
    name: 'AssistFollowUpRideTheMomentum_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpRideTheMomentum_0',
    },
  },
  ultimate_heal: {
    sheet: 'PanYinhu',
    name: 'ultimate_heal',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'healBase',
      sheet: 'PanYinhu',
      name: 'ultimate_heal',
    },
  },
  ultimate_healOverTime: {
    sheet: 'PanYinhu',
    name: 'ultimate_healOverTime',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'healBase',
      sheet: 'PanYinhu',
      name: 'ultimate_healOverTime',
    },
  },
  m4_heal: {
    sheet: 'PanYinhu',
    name: 'm4_heal',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'healBase',
      sheet: 'PanYinhu',
      name: 'm4_heal',
    },
  },
} as const
