// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'PanYinhu',
    name: 'standardDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'PanYinhu',
      attribute: 'physical',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'PanYinhu',
    name: 'anomalyDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_physical: {
    sheet: 'PanYinhu',
    name: 'disorderDmgInst_physical',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'disorder',
      name: 'disorderDmgInst_physical',
    },
  },
  anomalyBuildupInst: {
    sheet: 'PanYinhu',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'PanYinhu',
      attribute: 'physical',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'PanYinhu',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'PanYinhu',
      attribute: 'physical',
      name: 'dazeInst',
    },
  },
  BasicAttackUnyieldingStrikes_0_dmg: {
    sheet: 'PanYinhu',
    name: 'BasicAttackUnyieldingStrikes_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackUnyieldingStrikes_0_dmg',
    },
  },
  BasicAttackUnyieldingStrikes_0_daze: {
    sheet: 'PanYinhu',
    name: 'BasicAttackUnyieldingStrikes_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackUnyieldingStrikes_0_daze',
    },
  },
  BasicAttackUnyieldingStrikes_0_anomBuildup: {
    sheet: 'PanYinhu',
    name: 'BasicAttackUnyieldingStrikes_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackUnyieldingStrikes_0_anomBuildup',
    },
  },
  BasicAttackUnyieldingStrikes_1_dmg: {
    sheet: 'PanYinhu',
    name: 'BasicAttackUnyieldingStrikes_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackUnyieldingStrikes_1_dmg',
    },
  },
  BasicAttackUnyieldingStrikes_1_daze: {
    sheet: 'PanYinhu',
    name: 'BasicAttackUnyieldingStrikes_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackUnyieldingStrikes_1_daze',
    },
  },
  BasicAttackUnyieldingStrikes_1_anomBuildup: {
    sheet: 'PanYinhu',
    name: 'BasicAttackUnyieldingStrikes_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackUnyieldingStrikes_1_anomBuildup',
    },
  },
  BasicAttackUnyieldingStrikes_2_dmg: {
    sheet: 'PanYinhu',
    name: 'BasicAttackUnyieldingStrikes_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackUnyieldingStrikes_2_dmg',
    },
  },
  BasicAttackUnyieldingStrikes_2_daze: {
    sheet: 'PanYinhu',
    name: 'BasicAttackUnyieldingStrikes_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackUnyieldingStrikes_2_daze',
    },
  },
  BasicAttackUnyieldingStrikes_2_anomBuildup: {
    sheet: 'PanYinhu',
    name: 'BasicAttackUnyieldingStrikes_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackUnyieldingStrikes_2_anomBuildup',
    },
  },
  BasicAttackUnyieldingStrikes_3_dmg: {
    sheet: 'PanYinhu',
    name: 'BasicAttackUnyieldingStrikes_3_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackUnyieldingStrikes_3_dmg',
    },
  },
  BasicAttackUnyieldingStrikes_3_daze: {
    sheet: 'PanYinhu',
    name: 'BasicAttackUnyieldingStrikes_3_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackUnyieldingStrikes_3_daze',
    },
  },
  BasicAttackUnyieldingStrikes_3_anomBuildup: {
    sheet: 'PanYinhu',
    name: 'BasicAttackUnyieldingStrikes_3_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackUnyieldingStrikes_3_anomBuildup',
    },
  },
  DashAttackSizzlingOilSupreme_0_dmg: {
    sheet: 'PanYinhu',
    name: 'DashAttackSizzlingOilSupreme_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackSizzlingOilSupreme_0_dmg',
    },
  },
  DashAttackSizzlingOilSupreme_0_daze: {
    sheet: 'PanYinhu',
    name: 'DashAttackSizzlingOilSupreme_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackSizzlingOilSupreme_0_daze',
    },
  },
  DashAttackSizzlingOilSupreme_0_anomBuildup: {
    sheet: 'PanYinhu',
    name: 'DashAttackSizzlingOilSupreme_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackSizzlingOilSupreme_0_anomBuildup',
    },
  },
  DodgeCounterMovingMountainsAndSeas_0_dmg: {
    sheet: 'PanYinhu',
    name: 'DodgeCounterMovingMountainsAndSeas_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterMovingMountainsAndSeas_0_dmg',
    },
  },
  DodgeCounterMovingMountainsAndSeas_0_daze: {
    sheet: 'PanYinhu',
    name: 'DodgeCounterMovingMountainsAndSeas_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterMovingMountainsAndSeas_0_daze',
    },
  },
  DodgeCounterMovingMountainsAndSeas_0_anomBuildup: {
    sheet: 'PanYinhu',
    name: 'DodgeCounterMovingMountainsAndSeas_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterMovingMountainsAndSeas_0_anomBuildup',
    },
  },
  SpecialAttackSonicPressurePointStrike_0_dmg: {
    sheet: 'PanYinhu',
    name: 'SpecialAttackSonicPressurePointStrike_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackSonicPressurePointStrike_0_dmg',
    },
  },
  SpecialAttackSonicPressurePointStrike_0_daze: {
    sheet: 'PanYinhu',
    name: 'SpecialAttackSonicPressurePointStrike_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackSonicPressurePointStrike_0_daze',
    },
  },
  SpecialAttackSonicPressurePointStrike_0_anomBuildup: {
    sheet: 'PanYinhu',
    name: 'SpecialAttackSonicPressurePointStrike_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackSonicPressurePointStrike_0_anomBuildup',
    },
  },
  SpecialAttackTouchOfDeath_0_dmg: {
    sheet: 'PanYinhu',
    name: 'SpecialAttackTouchOfDeath_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackTouchOfDeath_0_dmg',
    },
  },
  SpecialAttackTouchOfDeath_0_daze: {
    sheet: 'PanYinhu',
    name: 'SpecialAttackTouchOfDeath_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackTouchOfDeath_0_daze',
    },
  },
  SpecialAttackTouchOfDeath_0_anomBuildup: {
    sheet: 'PanYinhu',
    name: 'SpecialAttackTouchOfDeath_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackTouchOfDeath_0_anomBuildup',
    },
  },
  SpecialAttackTouchOfDeath_1_dmg: {
    sheet: 'PanYinhu',
    name: 'SpecialAttackTouchOfDeath_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackTouchOfDeath_1_dmg',
    },
  },
  SpecialAttackTouchOfDeath_1_daze: {
    sheet: 'PanYinhu',
    name: 'SpecialAttackTouchOfDeath_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackTouchOfDeath_1_daze',
    },
  },
  SpecialAttackTouchOfDeath_1_anomBuildup: {
    sheet: 'PanYinhu',
    name: 'SpecialAttackTouchOfDeath_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackTouchOfDeath_1_anomBuildup',
    },
  },
  SpecialAttackTouchOfDeath_2_dmg: {
    sheet: 'PanYinhu',
    name: 'SpecialAttackTouchOfDeath_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackTouchOfDeath_2_dmg',
    },
  },
  SpecialAttackTouchOfDeath_2_daze: {
    sheet: 'PanYinhu',
    name: 'SpecialAttackTouchOfDeath_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackTouchOfDeath_2_daze',
    },
  },
  SpecialAttackTouchOfDeath_2_anomBuildup: {
    sheet: 'PanYinhu',
    name: 'SpecialAttackTouchOfDeath_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackTouchOfDeath_2_anomBuildup',
    },
  },
  EXSpecialAttackMountainousPulseStrike_0_dmg: {
    sheet: 'PanYinhu',
    name: 'EXSpecialAttackMountainousPulseStrike_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackMountainousPulseStrike_0_dmg',
    },
  },
  EXSpecialAttackMountainousPulseStrike_0_daze: {
    sheet: 'PanYinhu',
    name: 'EXSpecialAttackMountainousPulseStrike_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackMountainousPulseStrike_0_daze',
    },
  },
  EXSpecialAttackMountainousPulseStrike_0_anomBuildup: {
    sheet: 'PanYinhu',
    name: 'EXSpecialAttackMountainousPulseStrike_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackMountainousPulseStrike_0_anomBuildup',
    },
  },
  ChainAttackAnointedWithWokSteam_0_dmg: {
    sheet: 'PanYinhu',
    name: 'ChainAttackAnointedWithWokSteam_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackAnointedWithWokSteam_0_dmg',
    },
  },
  ChainAttackAnointedWithWokSteam_0_daze: {
    sheet: 'PanYinhu',
    name: 'ChainAttackAnointedWithWokSteam_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackAnointedWithWokSteam_0_daze',
    },
  },
  ChainAttackAnointedWithWokSteam_0_anomBuildup: {
    sheet: 'PanYinhu',
    name: 'ChainAttackAnointedWithWokSteam_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackAnointedWithWokSteam_0_anomBuildup',
    },
  },
  UltimateAFeastFitForAnEmperor_0_dmg: {
    sheet: 'PanYinhu',
    name: 'UltimateAFeastFitForAnEmperor_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateAFeastFitForAnEmperor_0_dmg',
    },
  },
  UltimateAFeastFitForAnEmperor_0_daze: {
    sheet: 'PanYinhu',
    name: 'UltimateAFeastFitForAnEmperor_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateAFeastFitForAnEmperor_0_daze',
    },
  },
  UltimateAFeastFitForAnEmperor_0_anomBuildup: {
    sheet: 'PanYinhu',
    name: 'UltimateAFeastFitForAnEmperor_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateAFeastFitForAnEmperor_0_anomBuildup',
    },
  },
  QuickAssistLiftYourGazeToGoodFortune_0_dmg: {
    sheet: 'PanYinhu',
    name: 'QuickAssistLiftYourGazeToGoodFortune_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistLiftYourGazeToGoodFortune_0_dmg',
    },
  },
  QuickAssistLiftYourGazeToGoodFortune_0_daze: {
    sheet: 'PanYinhu',
    name: 'QuickAssistLiftYourGazeToGoodFortune_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistLiftYourGazeToGoodFortune_0_daze',
    },
  },
  QuickAssistLiftYourGazeToGoodFortune_0_anomBuildup: {
    sheet: 'PanYinhu',
    name: 'QuickAssistLiftYourGazeToGoodFortune_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistLiftYourGazeToGoodFortune_0_anomBuildup',
    },
  },
  DefensiveAssistIntimidatingPresence_0_dmg: {
    sheet: 'PanYinhu',
    name: 'DefensiveAssistIntimidatingPresence_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistIntimidatingPresence_0_dmg',
    },
  },
  DefensiveAssistIntimidatingPresence_0_daze: {
    sheet: 'PanYinhu',
    name: 'DefensiveAssistIntimidatingPresence_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistIntimidatingPresence_0_daze',
    },
  },
  DefensiveAssistIntimidatingPresence_0_anomBuildup: {
    sheet: 'PanYinhu',
    name: 'DefensiveAssistIntimidatingPresence_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistIntimidatingPresence_0_anomBuildup',
    },
  },
  DefensiveAssistIntimidatingPresence_1_dmg: {
    sheet: 'PanYinhu',
    name: 'DefensiveAssistIntimidatingPresence_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistIntimidatingPresence_1_dmg',
    },
  },
  DefensiveAssistIntimidatingPresence_1_daze: {
    sheet: 'PanYinhu',
    name: 'DefensiveAssistIntimidatingPresence_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistIntimidatingPresence_1_daze',
    },
  },
  DefensiveAssistIntimidatingPresence_1_anomBuildup: {
    sheet: 'PanYinhu',
    name: 'DefensiveAssistIntimidatingPresence_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistIntimidatingPresence_1_anomBuildup',
    },
  },
  DefensiveAssistIntimidatingPresence_2_dmg: {
    sheet: 'PanYinhu',
    name: 'DefensiveAssistIntimidatingPresence_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistIntimidatingPresence_2_dmg',
    },
  },
  DefensiveAssistIntimidatingPresence_2_daze: {
    sheet: 'PanYinhu',
    name: 'DefensiveAssistIntimidatingPresence_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistIntimidatingPresence_2_daze',
    },
  },
  DefensiveAssistIntimidatingPresence_2_anomBuildup: {
    sheet: 'PanYinhu',
    name: 'DefensiveAssistIntimidatingPresence_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistIntimidatingPresence_2_anomBuildup',
    },
  },
  AssistFollowUpRideTheMomentum_0_dmg: {
    sheet: 'PanYinhu',
    name: 'AssistFollowUpRideTheMomentum_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpRideTheMomentum_0_dmg',
    },
  },
  AssistFollowUpRideTheMomentum_0_daze: {
    sheet: 'PanYinhu',
    name: 'AssistFollowUpRideTheMomentum_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpRideTheMomentum_0_daze',
    },
  },
  AssistFollowUpRideTheMomentum_0_anomBuildup: {
    sheet: 'PanYinhu',
    name: 'AssistFollowUpRideTheMomentum_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'PanYinhu',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpRideTheMomentum_0_anomBuildup',
    },
  },
  ultimate_heal: {
    sheet: 'PanYinhu',
    name: 'ultimate_heal',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'heal',
      sheet: 'PanYinhu',
      name: 'ultimate_heal',
    },
  },
  ultimate_healOverTime: {
    sheet: 'PanYinhu',
    name: 'ultimate_healOverTime',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'heal',
      sheet: 'PanYinhu',
      name: 'ultimate_healOverTime',
    },
  },
  m4_heal: {
    sheet: 'PanYinhu',
    name: 'm4_heal',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'heal',
      sheet: 'PanYinhu',
      name: 'm4_heal',
    },
  },
} as const
