// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Ellen',
    name: 'standardDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ellen',
      attribute: 'ice',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Ellen',
    name: 'anomalyDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_ice: {
    sheet: 'Ellen',
    name: 'disorderDmgInst_ice',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'disorder',
      name: 'disorderDmgInst_ice',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Ellen',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ellen',
      attribute: 'ice',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Ellen',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ellen',
      attribute: 'ice',
      name: 'dazeInst',
    },
  },
  BasicAttackSawTeethTrimming_0_dmg: {
    sheet: 'Ellen',
    name: 'BasicAttackSawTeethTrimming_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ellen',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackSawTeethTrimming_0_dmg',
    },
  },
  BasicAttackSawTeethTrimming_0_daze: {
    sheet: 'Ellen',
    name: 'BasicAttackSawTeethTrimming_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ellen',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackSawTeethTrimming_0_daze',
    },
  },
  BasicAttackSawTeethTrimming_0_anomBuildup: {
    sheet: 'Ellen',
    name: 'BasicAttackSawTeethTrimming_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ellen',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackSawTeethTrimming_0_anomBuildup',
    },
  },
  BasicAttackSawTeethTrimming_1_dmg: {
    sheet: 'Ellen',
    name: 'BasicAttackSawTeethTrimming_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ellen',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackSawTeethTrimming_1_dmg',
    },
  },
  BasicAttackSawTeethTrimming_1_daze: {
    sheet: 'Ellen',
    name: 'BasicAttackSawTeethTrimming_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ellen',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackSawTeethTrimming_1_daze',
    },
  },
  BasicAttackSawTeethTrimming_1_anomBuildup: {
    sheet: 'Ellen',
    name: 'BasicAttackSawTeethTrimming_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ellen',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackSawTeethTrimming_1_anomBuildup',
    },
  },
  BasicAttackSawTeethTrimming_2_dmg: {
    sheet: 'Ellen',
    name: 'BasicAttackSawTeethTrimming_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ellen',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackSawTeethTrimming_2_dmg',
    },
  },
  BasicAttackSawTeethTrimming_2_daze: {
    sheet: 'Ellen',
    name: 'BasicAttackSawTeethTrimming_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ellen',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackSawTeethTrimming_2_daze',
    },
  },
  BasicAttackSawTeethTrimming_2_anomBuildup: {
    sheet: 'Ellen',
    name: 'BasicAttackSawTeethTrimming_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ellen',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackSawTeethTrimming_2_anomBuildup',
    },
  },
  BasicAttackFlashFreezeTrimming_0_dmg: {
    sheet: 'Ellen',
    name: 'BasicAttackFlashFreezeTrimming_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFlashFreezeTrimming_0_dmg',
    },
  },
  BasicAttackFlashFreezeTrimming_0_daze: {
    sheet: 'Ellen',
    name: 'BasicAttackFlashFreezeTrimming_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFlashFreezeTrimming_0_daze',
    },
  },
  BasicAttackFlashFreezeTrimming_0_anomBuildup: {
    sheet: 'Ellen',
    name: 'BasicAttackFlashFreezeTrimming_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFlashFreezeTrimming_0_anomBuildup',
    },
  },
  BasicAttackFlashFreezeTrimming_1_dmg: {
    sheet: 'Ellen',
    name: 'BasicAttackFlashFreezeTrimming_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFlashFreezeTrimming_1_dmg',
    },
  },
  BasicAttackFlashFreezeTrimming_1_daze: {
    sheet: 'Ellen',
    name: 'BasicAttackFlashFreezeTrimming_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFlashFreezeTrimming_1_daze',
    },
  },
  BasicAttackFlashFreezeTrimming_1_anomBuildup: {
    sheet: 'Ellen',
    name: 'BasicAttackFlashFreezeTrimming_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFlashFreezeTrimming_1_anomBuildup',
    },
  },
  BasicAttackFlashFreezeTrimming_2_dmg: {
    sheet: 'Ellen',
    name: 'BasicAttackFlashFreezeTrimming_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFlashFreezeTrimming_2_dmg',
    },
  },
  BasicAttackFlashFreezeTrimming_2_daze: {
    sheet: 'Ellen',
    name: 'BasicAttackFlashFreezeTrimming_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFlashFreezeTrimming_2_daze',
    },
  },
  BasicAttackFlashFreezeTrimming_2_anomBuildup: {
    sheet: 'Ellen',
    name: 'BasicAttackFlashFreezeTrimming_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackFlashFreezeTrimming_2_anomBuildup',
    },
  },
  BasicAttackGlacialBladeWave_0_dmg: {
    sheet: 'Ellen',
    name: 'BasicAttackGlacialBladeWave_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackGlacialBladeWave_0_dmg',
    },
  },
  BasicAttackGlacialBladeWave_0_daze: {
    sheet: 'Ellen',
    name: 'BasicAttackGlacialBladeWave_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackGlacialBladeWave_0_daze',
    },
  },
  BasicAttackGlacialBladeWave_0_anomBuildup: {
    sheet: 'Ellen',
    name: 'BasicAttackGlacialBladeWave_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackGlacialBladeWave_0_anomBuildup',
    },
  },
  BasicAttackGlacialBladeWave_1_dmg: {
    sheet: 'Ellen',
    name: 'BasicAttackGlacialBladeWave_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackGlacialBladeWave_1_dmg',
    },
  },
  BasicAttackGlacialBladeWave_1_daze: {
    sheet: 'Ellen',
    name: 'BasicAttackGlacialBladeWave_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackGlacialBladeWave_1_daze',
    },
  },
  BasicAttackGlacialBladeWave_1_anomBuildup: {
    sheet: 'Ellen',
    name: 'BasicAttackGlacialBladeWave_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackGlacialBladeWave_1_anomBuildup',
    },
  },
  BasicAttackIcyBlade_0_dmg: {
    sheet: 'Ellen',
    name: 'BasicAttackIcyBlade_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackIcyBlade_0_dmg',
    },
  },
  BasicAttackIcyBlade_0_daze: {
    sheet: 'Ellen',
    name: 'BasicAttackIcyBlade_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackIcyBlade_0_daze',
    },
  },
  BasicAttackIcyBlade_0_anomBuildup: {
    sheet: 'Ellen',
    name: 'BasicAttackIcyBlade_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackIcyBlade_0_anomBuildup',
    },
  },
  BasicAttackIcyBlade_1_dmg: {
    sheet: 'Ellen',
    name: 'BasicAttackIcyBlade_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackIcyBlade_1_dmg',
    },
  },
  BasicAttackIcyBlade_1_daze: {
    sheet: 'Ellen',
    name: 'BasicAttackIcyBlade_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackIcyBlade_1_daze',
    },
  },
  BasicAttackIcyBlade_1_anomBuildup: {
    sheet: 'Ellen',
    name: 'BasicAttackIcyBlade_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackIcyBlade_1_anomBuildup',
    },
  },
  DashAttackArcticAmbush_0_dmg: {
    sheet: 'Ellen',
    name: 'DashAttackArcticAmbush_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackArcticAmbush_0_dmg',
    },
  },
  DashAttackArcticAmbush_0_daze: {
    sheet: 'Ellen',
    name: 'DashAttackArcticAmbush_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackArcticAmbush_0_daze',
    },
  },
  DashAttackArcticAmbush_0_anomBuildup: {
    sheet: 'Ellen',
    name: 'DashAttackArcticAmbush_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackArcticAmbush_0_anomBuildup',
    },
  },
  DashAttackArcticAmbush_1_dmg: {
    sheet: 'Ellen',
    name: 'DashAttackArcticAmbush_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackArcticAmbush_1_dmg',
    },
  },
  DashAttackArcticAmbush_1_daze: {
    sheet: 'Ellen',
    name: 'DashAttackArcticAmbush_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackArcticAmbush_1_daze',
    },
  },
  DashAttackArcticAmbush_1_anomBuildup: {
    sheet: 'Ellen',
    name: 'DashAttackArcticAmbush_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackArcticAmbush_1_anomBuildup',
    },
  },
  DashAttackArcticAmbush_2_dmg: {
    sheet: 'Ellen',
    name: 'DashAttackArcticAmbush_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackArcticAmbush_2_dmg',
    },
  },
  DashAttackArcticAmbush_2_daze: {
    sheet: 'Ellen',
    name: 'DashAttackArcticAmbush_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackArcticAmbush_2_daze',
    },
  },
  DashAttackArcticAmbush_2_anomBuildup: {
    sheet: 'Ellen',
    name: 'DashAttackArcticAmbush_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackArcticAmbush_2_anomBuildup',
    },
  },
  DashAttackMonstrousWave_0_dmg: {
    sheet: 'Ellen',
    name: 'DashAttackMonstrousWave_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ellen',
      damageType1: 'dash',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttackMonstrousWave_0_dmg',
    },
  },
  DashAttackMonstrousWave_0_daze: {
    sheet: 'Ellen',
    name: 'DashAttackMonstrousWave_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ellen',
      damageType1: 'dash',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttackMonstrousWave_0_daze',
    },
  },
  DashAttackMonstrousWave_0_anomBuildup: {
    sheet: 'Ellen',
    name: 'DashAttackMonstrousWave_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ellen',
      damageType1: 'dash',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttackMonstrousWave_0_anomBuildup',
    },
  },
  DashAttackColdSnap_0_dmg: {
    sheet: 'Ellen',
    name: 'DashAttackColdSnap_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackColdSnap_0_dmg',
    },
  },
  DashAttackColdSnap_0_daze: {
    sheet: 'Ellen',
    name: 'DashAttackColdSnap_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackColdSnap_0_daze',
    },
  },
  DashAttackColdSnap_0_anomBuildup: {
    sheet: 'Ellen',
    name: 'DashAttackColdSnap_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackColdSnap_0_anomBuildup',
    },
  },
  DodgeCounterReefRock_0_dmg: {
    sheet: 'Ellen',
    name: 'DodgeCounterReefRock_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterReefRock_0_dmg',
    },
  },
  DodgeCounterReefRock_0_daze: {
    sheet: 'Ellen',
    name: 'DodgeCounterReefRock_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterReefRock_0_daze',
    },
  },
  DodgeCounterReefRock_0_anomBuildup: {
    sheet: 'Ellen',
    name: 'DodgeCounterReefRock_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterReefRock_0_anomBuildup',
    },
  },
  SpecialAttackDrift_0_dmg: {
    sheet: 'Ellen',
    name: 'SpecialAttackDrift_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackDrift_0_dmg',
    },
  },
  SpecialAttackDrift_0_daze: {
    sheet: 'Ellen',
    name: 'SpecialAttackDrift_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackDrift_0_daze',
    },
  },
  SpecialAttackDrift_0_anomBuildup: {
    sheet: 'Ellen',
    name: 'SpecialAttackDrift_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackDrift_0_anomBuildup',
    },
  },
  EXSpecialAttackTailSwipe_0_dmg: {
    sheet: 'Ellen',
    name: 'EXSpecialAttackTailSwipe_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackTailSwipe_0_dmg',
    },
  },
  EXSpecialAttackTailSwipe_0_daze: {
    sheet: 'Ellen',
    name: 'EXSpecialAttackTailSwipe_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackTailSwipe_0_daze',
    },
  },
  EXSpecialAttackTailSwipe_0_anomBuildup: {
    sheet: 'Ellen',
    name: 'EXSpecialAttackTailSwipe_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackTailSwipe_0_anomBuildup',
    },
  },
  EXSpecialAttackSharknami_0_dmg: {
    sheet: 'Ellen',
    name: 'EXSpecialAttackSharknami_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackSharknami_0_dmg',
    },
  },
  EXSpecialAttackSharknami_0_daze: {
    sheet: 'Ellen',
    name: 'EXSpecialAttackSharknami_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackSharknami_0_daze',
    },
  },
  EXSpecialAttackSharknami_0_anomBuildup: {
    sheet: 'Ellen',
    name: 'EXSpecialAttackSharknami_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackSharknami_0_anomBuildup',
    },
  },
  ChainAttackAvalanche_0_dmg: {
    sheet: 'Ellen',
    name: 'ChainAttackAvalanche_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackAvalanche_0_dmg',
    },
  },
  ChainAttackAvalanche_0_daze: {
    sheet: 'Ellen',
    name: 'ChainAttackAvalanche_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackAvalanche_0_daze',
    },
  },
  ChainAttackAvalanche_0_anomBuildup: {
    sheet: 'Ellen',
    name: 'ChainAttackAvalanche_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackAvalanche_0_anomBuildup',
    },
  },
  UltimateEndlessWinter_0_dmg: {
    sheet: 'Ellen',
    name: 'UltimateEndlessWinter_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateEndlessWinter_0_dmg',
    },
  },
  UltimateEndlessWinter_0_daze: {
    sheet: 'Ellen',
    name: 'UltimateEndlessWinter_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateEndlessWinter_0_daze',
    },
  },
  UltimateEndlessWinter_0_anomBuildup: {
    sheet: 'Ellen',
    name: 'UltimateEndlessWinter_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateEndlessWinter_0_anomBuildup',
    },
  },
  QuickAssistSharkSentinel_0_dmg: {
    sheet: 'Ellen',
    name: 'QuickAssistSharkSentinel_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistSharkSentinel_0_dmg',
    },
  },
  QuickAssistSharkSentinel_0_daze: {
    sheet: 'Ellen',
    name: 'QuickAssistSharkSentinel_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistSharkSentinel_0_daze',
    },
  },
  QuickAssistSharkSentinel_0_anomBuildup: {
    sheet: 'Ellen',
    name: 'QuickAssistSharkSentinel_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistSharkSentinel_0_anomBuildup',
    },
  },
  DefensiveAssistWavefrontImpact_0_dmg: {
    sheet: 'Ellen',
    name: 'DefensiveAssistWavefrontImpact_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistWavefrontImpact_0_dmg',
    },
  },
  DefensiveAssistWavefrontImpact_0_daze: {
    sheet: 'Ellen',
    name: 'DefensiveAssistWavefrontImpact_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistWavefrontImpact_0_daze',
    },
  },
  DefensiveAssistWavefrontImpact_0_anomBuildup: {
    sheet: 'Ellen',
    name: 'DefensiveAssistWavefrontImpact_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistWavefrontImpact_0_anomBuildup',
    },
  },
  DefensiveAssistWavefrontImpact_1_dmg: {
    sheet: 'Ellen',
    name: 'DefensiveAssistWavefrontImpact_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistWavefrontImpact_1_dmg',
    },
  },
  DefensiveAssistWavefrontImpact_1_daze: {
    sheet: 'Ellen',
    name: 'DefensiveAssistWavefrontImpact_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistWavefrontImpact_1_daze',
    },
  },
  DefensiveAssistWavefrontImpact_1_anomBuildup: {
    sheet: 'Ellen',
    name: 'DefensiveAssistWavefrontImpact_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistWavefrontImpact_1_anomBuildup',
    },
  },
  DefensiveAssistWavefrontImpact_2_dmg: {
    sheet: 'Ellen',
    name: 'DefensiveAssistWavefrontImpact_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistWavefrontImpact_2_dmg',
    },
  },
  DefensiveAssistWavefrontImpact_2_daze: {
    sheet: 'Ellen',
    name: 'DefensiveAssistWavefrontImpact_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistWavefrontImpact_2_daze',
    },
  },
  DefensiveAssistWavefrontImpact_2_anomBuildup: {
    sheet: 'Ellen',
    name: 'DefensiveAssistWavefrontImpact_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistWavefrontImpact_2_anomBuildup',
    },
  },
  AssistFollowUpSharkCruiser_0_dmg: {
    sheet: 'Ellen',
    name: 'AssistFollowUpSharkCruiser_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpSharkCruiser_0_dmg',
    },
  },
  AssistFollowUpSharkCruiser_0_daze: {
    sheet: 'Ellen',
    name: 'AssistFollowUpSharkCruiser_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpSharkCruiser_0_daze',
    },
  },
  AssistFollowUpSharkCruiser_0_anomBuildup: {
    sheet: 'Ellen',
    name: 'AssistFollowUpSharkCruiser_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Ellen',
      attribute: 'ice',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpSharkCruiser_0_anomBuildup',
    },
  },
} as const
