// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Dialyn',
    name: 'standardDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'standardDmgBase',
      sheet: 'Dialyn',
      attribute: 'physical',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Dialyn',
    name: 'anomalyDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Dialyn',
      attribute: 'physical',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_physical: {
    sheet: 'Dialyn',
    name: 'disorderDmgInst_physical',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Dialyn',
      attribute: 'physical',
      damageType1: 'disorder',
      name: 'disorderDmgInst_physical',
    },
  },
  vortexDmgInst_physical: {
    sheet: 'Dialyn',
    name: 'vortexDmgInst_physical',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Dialyn',
      attribute: 'physical',
      damageType1: 'vortex',
      name: 'vortexDmgInst_physical',
    },
  },
  abloomDmgInst: {
    sheet: 'Dialyn',
    name: 'abloomDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Dialyn',
      attribute: 'physical',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Dialyn',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Dialyn',
      attribute: 'physical',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Dialyn',
    name: 'dazeInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'dazeBuildupBase',
      sheet: 'Dialyn',
      attribute: 'physical',
      name: 'dazeInst',
    },
  },
  BasicAttackHappyToBeOfService_0: {
    sheet: 'Dialyn',
    name: 'BasicAttackHappyToBeOfService_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Dialyn',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackHappyToBeOfService_0',
    },
  },
  BasicAttackHappyToBeOfService_1: {
    sheet: 'Dialyn',
    name: 'BasicAttackHappyToBeOfService_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Dialyn',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackHappyToBeOfService_1',
    },
  },
  BasicAttackHappyToBeOfService_2: {
    sheet: 'Dialyn',
    name: 'BasicAttackHappyToBeOfService_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Dialyn',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackHappyToBeOfService_2',
    },
  },
  BasicAttackHappyToBeOfService_3: {
    sheet: 'Dialyn',
    name: 'BasicAttackHappyToBeOfService_3',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Dialyn',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackHappyToBeOfService_3',
    },
  },
  BasicAttackRockPaperScissors_0: {
    sheet: 'Dialyn',
    name: 'BasicAttackRockPaperScissors_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Dialyn',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackRockPaperScissors_0',
    },
  },
  BasicAttackRockPaperScissors_1: {
    sheet: 'Dialyn',
    name: 'BasicAttackRockPaperScissors_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Dialyn',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackRockPaperScissors_1',
    },
  },
  BasicAttackRockPaperScissors_2: {
    sheet: 'Dialyn',
    name: 'BasicAttackRockPaperScissors_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Dialyn',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackRockPaperScissors_2',
    },
  },
  BasicAttackRockPaperScissors_3: {
    sheet: 'Dialyn',
    name: 'BasicAttackRockPaperScissors_3',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Dialyn',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackRockPaperScissors_3',
    },
  },
  DashAttackSuddenCall_0: {
    sheet: 'Dialyn',
    name: 'DashAttackSuddenCall_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Dialyn',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackSuddenCall_0',
    },
  },
  DodgeCounterNumberUnavailable_0: {
    sheet: 'Dialyn',
    name: 'DodgeCounterNumberUnavailable_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Dialyn',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterNumberUnavailable_0',
    },
  },
  EXSpecialAttackGetLost_0: {
    sheet: 'Dialyn',
    name: 'EXSpecialAttackGetLost_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Dialyn',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackGetLost_0',
    },
  },
  SpecialAttackWelcomeGesture_0: {
    sheet: 'Dialyn',
    name: 'SpecialAttackWelcomeGesture_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Dialyn',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackWelcomeGesture_0',
    },
  },
  EXSpecialAttackRock_0: {
    sheet: 'Dialyn',
    name: 'EXSpecialAttackRock_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Dialyn',
      damageType1: 'exSpecial',
      attribute: 'physical',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackRock_0',
    },
  },
  EXSpecialAttackScissors_0: {
    sheet: 'Dialyn',
    name: 'EXSpecialAttackScissors_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Dialyn',
      damageType1: 'exSpecial',
      attribute: 'physical',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackScissors_0',
    },
  },
  EXSpecialAttackPaper_0: {
    sheet: 'Dialyn',
    name: 'EXSpecialAttackPaper_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Dialyn',
      damageType1: 'exSpecial',
      attribute: 'physical',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackPaper_0',
    },
  },
  ChainAttackWelcomeMat_0: {
    sheet: 'Dialyn',
    name: 'ChainAttackWelcomeMat_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Dialyn',
      attribute: 'physical',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackWelcomeMat_0',
    },
  },
  UltimateServiceStoppedForNumberDialed_0: {
    sheet: 'Dialyn',
    name: 'UltimateServiceStoppedForNumberDialed_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Dialyn',
      attribute: 'physical',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateServiceStoppedForNumberDialed_0',
    },
  },
  QuickAssistForwardCall_0: {
    sheet: 'Dialyn',
    name: 'QuickAssistForwardCall_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Dialyn',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistForwardCall_0',
    },
  },
  DefensiveAssistDeclineCall_0: {
    sheet: 'Dialyn',
    name: 'DefensiveAssistDeclineCall_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Dialyn',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistDeclineCall_0',
    },
  },
  DefensiveAssistDeclineCall_1: {
    sheet: 'Dialyn',
    name: 'DefensiveAssistDeclineCall_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Dialyn',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistDeclineCall_1',
    },
  },
  DefensiveAssistDeclineCall_2: {
    sheet: 'Dialyn',
    name: 'DefensiveAssistDeclineCall_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Dialyn',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistDeclineCall_2',
    },
  },
  AssistFollowUpBacktoBackCalls_0: {
    sheet: 'Dialyn',
    name: 'AssistFollowUpBacktoBackCalls_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Dialyn',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpBacktoBackCalls_0',
    },
  },
  m6_dmg: {
    sheet: 'Dialyn',
    name: 'm6_dmg',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'standardDmgBase',
      sheet: 'Dialyn',
      attribute: 'physical',
      damageType1: 'exSpecial',
      name: 'm6_dmg',
    },
  },
} as const
