// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Lighter',
    name: 'standardDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lighter',
      attribute: 'fire',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Lighter',
    name: 'anomalyDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_fire: {
    sheet: 'Lighter',
    name: 'disorderDmgInst_fire',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'disorder',
      name: 'disorderDmgInst_fire',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Lighter',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Lighter',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      name: 'dazeInst',
    },
  },
  BasicAttackLFormThunderingFist_0_dmg: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lighter',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_0_dmg',
    },
  },
  BasicAttackLFormThunderingFist_0_daze: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lighter',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_0_daze',
    },
  },
  BasicAttackLFormThunderingFist_0_anomBuildup: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lighter',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_0_anomBuildup',
    },
  },
  BasicAttackLFormThunderingFist_1_dmg: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lighter',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_1_dmg',
    },
  },
  BasicAttackLFormThunderingFist_1_daze: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lighter',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_1_daze',
    },
  },
  BasicAttackLFormThunderingFist_1_anomBuildup: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lighter',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_1_anomBuildup',
    },
  },
  BasicAttackLFormThunderingFist_2_dmg: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lighter',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_2_dmg',
    },
  },
  BasicAttackLFormThunderingFist_2_daze: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lighter',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_2_daze',
    },
  },
  BasicAttackLFormThunderingFist_2_anomBuildup: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lighter',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_2_anomBuildup',
    },
  },
  BasicAttackLFormThunderingFist_3_dmg: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_3_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_3_dmg',
    },
  },
  BasicAttackLFormThunderingFist_3_daze: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_3_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_3_daze',
    },
  },
  BasicAttackLFormThunderingFist_3_anomBuildup: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_3_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_3_anomBuildup',
    },
  },
  BasicAttackLFormThunderingFist_4_dmg: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_4_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_4_dmg',
    },
  },
  BasicAttackLFormThunderingFist_4_daze: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_4_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_4_daze',
    },
  },
  BasicAttackLFormThunderingFist_4_anomBuildup: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_4_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_4_anomBuildup',
    },
  },
  BasicAttackLFormThunderingFist_5_dmg: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_5_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_5_dmg',
    },
  },
  BasicAttackLFormThunderingFist_5_daze: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_5_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_5_daze',
    },
  },
  BasicAttackLFormThunderingFist_5_anomBuildup: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_5_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_5_anomBuildup',
    },
  },
  BasicAttackLFormThunderingFist_6_dmg: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_6_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_6_dmg',
    },
  },
  BasicAttackLFormThunderingFist_6_daze: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_6_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_6_daze',
    },
  },
  BasicAttackLFormThunderingFist_6_anomBuildup: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_6_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_6_anomBuildup',
    },
  },
  BasicAttackLFormThunderingFist_7_dmg: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_7_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_7_dmg',
    },
  },
  BasicAttackLFormThunderingFist_7_daze: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_7_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_7_daze',
    },
  },
  BasicAttackLFormThunderingFist_7_anomBuildup: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_7_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_7_anomBuildup',
    },
  },
  BasicAttackLFormThunderingFist_8_dmg: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_8_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_8_dmg',
    },
  },
  BasicAttackLFormThunderingFist_8_daze: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_8_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_8_daze',
    },
  },
  BasicAttackLFormThunderingFist_8_anomBuildup: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_8_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_8_anomBuildup',
    },
  },
  BasicAttackLFormThunderingFist_9_dmg: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_9_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_9_dmg',
    },
  },
  BasicAttackLFormThunderingFist_9_daze: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_9_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_9_daze',
    },
  },
  BasicAttackLFormThunderingFist_9_anomBuildup: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_9_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_9_anomBuildup',
    },
  },
  BasicAttackLFormThunderingFist_10_dmg: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_10_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_10_dmg',
    },
  },
  BasicAttackLFormThunderingFist_10_daze: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_10_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_10_daze',
    },
  },
  BasicAttackLFormThunderingFist_10_anomBuildup: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_10_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_10_anomBuildup',
    },
  },
  BasicAttackLFormThunderingFist_11_dmg: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_11_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_11_dmg',
    },
  },
  BasicAttackLFormThunderingFist_11_daze: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_11_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_11_daze',
    },
  },
  BasicAttackLFormThunderingFist_11_anomBuildup: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_11_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_11_anomBuildup',
    },
  },
  BasicAttackLFormThunderingFist_12_dmg: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_12_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_12_dmg',
    },
  },
  BasicAttackLFormThunderingFist_12_daze: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_12_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_12_daze',
    },
  },
  BasicAttackLFormThunderingFist_12_anomBuildup: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_12_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_12_anomBuildup',
    },
  },
  BasicAttackLFormThunderingFist_13_dmg: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_13_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_13_dmg',
    },
  },
  BasicAttackLFormThunderingFist_13_daze: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_13_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_13_daze',
    },
  },
  BasicAttackLFormThunderingFist_13_anomBuildup: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_13_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_13_anomBuildup',
    },
  },
  BasicAttackLFormThunderingFist_14_dmg: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_14_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_14_dmg',
    },
  },
  BasicAttackLFormThunderingFist_14_daze: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_14_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_14_daze',
    },
  },
  BasicAttackLFormThunderingFist_14_anomBuildup: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_14_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_14_anomBuildup',
    },
  },
  BasicAttackLFormThunderingFist_15_dmg: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_15_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_15_dmg',
    },
  },
  BasicAttackLFormThunderingFist_15_daze: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_15_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_15_daze',
    },
  },
  BasicAttackLFormThunderingFist_15_anomBuildup: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_15_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_15_anomBuildup',
    },
  },
  DashAttackChargingSlam_0_dmg: {
    sheet: 'Lighter',
    name: 'DashAttackChargingSlam_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lighter',
      damageType1: 'dash',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttackChargingSlam_0_dmg',
    },
  },
  DashAttackChargingSlam_0_daze: {
    sheet: 'Lighter',
    name: 'DashAttackChargingSlam_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lighter',
      damageType1: 'dash',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttackChargingSlam_0_daze',
    },
  },
  DashAttackChargingSlam_0_anomBuildup: {
    sheet: 'Lighter',
    name: 'DashAttackChargingSlam_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lighter',
      damageType1: 'dash',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttackChargingSlam_0_anomBuildup',
    },
  },
  DodgeCounterBlazingFlash_0_dmg: {
    sheet: 'Lighter',
    name: 'DodgeCounterBlazingFlash_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterBlazingFlash_0_dmg',
    },
  },
  DodgeCounterBlazingFlash_0_daze: {
    sheet: 'Lighter',
    name: 'DodgeCounterBlazingFlash_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterBlazingFlash_0_daze',
    },
  },
  DodgeCounterBlazingFlash_0_anomBuildup: {
    sheet: 'Lighter',
    name: 'DodgeCounterBlazingFlash_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterBlazingFlash_0_anomBuildup',
    },
  },
  SpecialAttackVFormSunriseUppercut_0_dmg: {
    sheet: 'Lighter',
    name: 'SpecialAttackVFormSunriseUppercut_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackVFormSunriseUppercut_0_dmg',
    },
  },
  SpecialAttackVFormSunriseUppercut_0_daze: {
    sheet: 'Lighter',
    name: 'SpecialAttackVFormSunriseUppercut_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackVFormSunriseUppercut_0_daze',
    },
  },
  SpecialAttackVFormSunriseUppercut_0_anomBuildup: {
    sheet: 'Lighter',
    name: 'SpecialAttackVFormSunriseUppercut_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackVFormSunriseUppercut_0_anomBuildup',
    },
  },
  EXSpecialAttackVFormSunriseUppercutFullDistance_0_dmg: {
    sheet: 'Lighter',
    name: 'EXSpecialAttackVFormSunriseUppercutFullDistance_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackVFormSunriseUppercutFullDistance_0_dmg',
    },
  },
  EXSpecialAttackVFormSunriseUppercutFullDistance_0_daze: {
    sheet: 'Lighter',
    name: 'EXSpecialAttackVFormSunriseUppercutFullDistance_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackVFormSunriseUppercutFullDistance_0_daze',
    },
  },
  EXSpecialAttackVFormSunriseUppercutFullDistance_0_anomBuildup: {
    sheet: 'Lighter',
    name: 'EXSpecialAttackVFormSunriseUppercutFullDistance_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackVFormSunriseUppercutFullDistance_0_anomBuildup',
    },
  },
  EXSpecialAttackVFormSunriseUppercutFullDistance_1_dmg: {
    sheet: 'Lighter',
    name: 'EXSpecialAttackVFormSunriseUppercutFullDistance_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackVFormSunriseUppercutFullDistance_1_dmg',
    },
  },
  EXSpecialAttackVFormSunriseUppercutFullDistance_1_daze: {
    sheet: 'Lighter',
    name: 'EXSpecialAttackVFormSunriseUppercutFullDistance_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackVFormSunriseUppercutFullDistance_1_daze',
    },
  },
  EXSpecialAttackVFormSunriseUppercutFullDistance_1_anomBuildup: {
    sheet: 'Lighter',
    name: 'EXSpecialAttackVFormSunriseUppercutFullDistance_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackVFormSunriseUppercutFullDistance_1_anomBuildup',
    },
  },
  ChainAttackVFormScorchingSun_0_dmg: {
    sheet: 'Lighter',
    name: 'ChainAttackVFormScorchingSun_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackVFormScorchingSun_0_dmg',
    },
  },
  ChainAttackVFormScorchingSun_0_daze: {
    sheet: 'Lighter',
    name: 'ChainAttackVFormScorchingSun_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackVFormScorchingSun_0_daze',
    },
  },
  ChainAttackVFormScorchingSun_0_anomBuildup: {
    sheet: 'Lighter',
    name: 'ChainAttackVFormScorchingSun_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackVFormScorchingSun_0_anomBuildup',
    },
  },
  UltimateWFormCrownedInferno_0_dmg: {
    sheet: 'Lighter',
    name: 'UltimateWFormCrownedInferno_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateWFormCrownedInferno_0_dmg',
    },
  },
  UltimateWFormCrownedInferno_0_daze: {
    sheet: 'Lighter',
    name: 'UltimateWFormCrownedInferno_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateWFormCrownedInferno_0_daze',
    },
  },
  UltimateWFormCrownedInferno_0_anomBuildup: {
    sheet: 'Lighter',
    name: 'UltimateWFormCrownedInferno_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateWFormCrownedInferno_0_anomBuildup',
    },
  },
  QuickAssistBlazingFlashGuard_0_dmg: {
    sheet: 'Lighter',
    name: 'QuickAssistBlazingFlashGuard_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistBlazingFlashGuard_0_dmg',
    },
  },
  QuickAssistBlazingFlashGuard_0_daze: {
    sheet: 'Lighter',
    name: 'QuickAssistBlazingFlashGuard_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistBlazingFlashGuard_0_daze',
    },
  },
  QuickAssistBlazingFlashGuard_0_anomBuildup: {
    sheet: 'Lighter',
    name: 'QuickAssistBlazingFlashGuard_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistBlazingFlashGuard_0_anomBuildup',
    },
  },
  DefensiveAssistSwiftBreak_0_dmg: {
    sheet: 'Lighter',
    name: 'DefensiveAssistSwiftBreak_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistSwiftBreak_0_dmg',
    },
  },
  DefensiveAssistSwiftBreak_0_daze: {
    sheet: 'Lighter',
    name: 'DefensiveAssistSwiftBreak_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistSwiftBreak_0_daze',
    },
  },
  DefensiveAssistSwiftBreak_0_anomBuildup: {
    sheet: 'Lighter',
    name: 'DefensiveAssistSwiftBreak_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistSwiftBreak_0_anomBuildup',
    },
  },
  DefensiveAssistSwiftBreak_1_dmg: {
    sheet: 'Lighter',
    name: 'DefensiveAssistSwiftBreak_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistSwiftBreak_1_dmg',
    },
  },
  DefensiveAssistSwiftBreak_1_daze: {
    sheet: 'Lighter',
    name: 'DefensiveAssistSwiftBreak_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistSwiftBreak_1_daze',
    },
  },
  DefensiveAssistSwiftBreak_1_anomBuildup: {
    sheet: 'Lighter',
    name: 'DefensiveAssistSwiftBreak_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistSwiftBreak_1_anomBuildup',
    },
  },
  DefensiveAssistSwiftBreak_2_dmg: {
    sheet: 'Lighter',
    name: 'DefensiveAssistSwiftBreak_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistSwiftBreak_2_dmg',
    },
  },
  DefensiveAssistSwiftBreak_2_daze: {
    sheet: 'Lighter',
    name: 'DefensiveAssistSwiftBreak_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistSwiftBreak_2_daze',
    },
  },
  DefensiveAssistSwiftBreak_2_anomBuildup: {
    sheet: 'Lighter',
    name: 'DefensiveAssistSwiftBreak_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistSwiftBreak_2_anomBuildup',
    },
  },
  AssistFollowUpChargingSlamStab_0_dmg: {
    sheet: 'Lighter',
    name: 'AssistFollowUpChargingSlamStab_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpChargingSlamStab_0_dmg',
    },
  },
  AssistFollowUpChargingSlamStab_0_daze: {
    sheet: 'Lighter',
    name: 'AssistFollowUpChargingSlamStab_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpChargingSlamStab_0_daze',
    },
  },
  AssistFollowUpChargingSlamStab_0_anomBuildup: {
    sheet: 'Lighter',
    name: 'AssistFollowUpChargingSlamStab_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpChargingSlamStab_0_anomBuildup',
    },
  },
  m6_blazing_impact_dmg: {
    sheet: 'Lighter',
    name: 'm6_blazing_impact_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'elemental',
      name: 'm6_blazing_impact_dmg',
    },
  },
} as const
