// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Lighter',
    name: 'standardDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'standardDmgBase',
      sheet: 'Lighter',
      attribute: 'fire',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Lighter',
    name: 'anomalyDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_fire: {
    sheet: 'Lighter',
    name: 'disorderDmgInst_fire',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'disorder',
      name: 'disorderDmgInst_fire',
    },
  },
  vortexDmgInst_fire: {
    sheet: 'Lighter',
    name: 'vortexDmgInst_fire',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'vortex',
      name: 'vortexDmgInst_fire',
    },
  },
  abloomDmgInst: {
    sheet: 'Lighter',
    name: 'abloomDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Lighter',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lighter',
      attribute: 'fire',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Lighter',
    name: 'dazeInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'dazeBuildupBase',
      sheet: 'Lighter',
      attribute: 'fire',
      name: 'dazeInst',
    },
  },
  BasicAttackLFormThunderingFist_0: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lighter',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_0',
    },
  },
  BasicAttackLFormThunderingFist_1: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lighter',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_1',
    },
  },
  BasicAttackLFormThunderingFist_2: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lighter',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_2',
    },
  },
  BasicAttackLFormThunderingFist_3: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_3',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_3',
    },
  },
  BasicAttackLFormThunderingFist_4: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_4',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_4',
    },
  },
  BasicAttackLFormThunderingFist_5: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_5',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_5',
    },
  },
  BasicAttackLFormThunderingFist_6: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_6',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_6',
    },
  },
  BasicAttackLFormThunderingFist_7: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_7',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_7',
    },
  },
  BasicAttackLFormThunderingFist_8: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_8',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_8',
    },
  },
  BasicAttackLFormThunderingFist_9: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_9',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_9',
    },
  },
  BasicAttackLFormThunderingFist_10: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_10',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_10',
    },
  },
  BasicAttackLFormThunderingFist_11: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_11',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_11',
    },
  },
  BasicAttackLFormThunderingFist_12: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_12',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_12',
    },
  },
  BasicAttackLFormThunderingFist_13: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_13',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_13',
    },
  },
  BasicAttackLFormThunderingFist_14: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_14',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_14',
    },
  },
  BasicAttackLFormThunderingFist_15: {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_15',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_15',
    },
  },
  DashAttackChargingSlam_0: {
    sheet: 'Lighter',
    name: 'DashAttackChargingSlam_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lighter',
      damageType1: 'dash',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttackChargingSlam_0',
    },
  },
  DodgeCounterBlazingFlash_0: {
    sheet: 'Lighter',
    name: 'DodgeCounterBlazingFlash_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterBlazingFlash_0',
    },
  },
  SpecialAttackVFormSunriseUppercut_0: {
    sheet: 'Lighter',
    name: 'SpecialAttackVFormSunriseUppercut_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackVFormSunriseUppercut_0',
    },
  },
  EXSpecialAttackVFormSunriseUppercutFullDistance_0: {
    sheet: 'Lighter',
    name: 'EXSpecialAttackVFormSunriseUppercutFullDistance_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackVFormSunriseUppercutFullDistance_0',
    },
  },
  EXSpecialAttackVFormSunriseUppercutFullDistance_1: {
    sheet: 'Lighter',
    name: 'EXSpecialAttackVFormSunriseUppercutFullDistance_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackVFormSunriseUppercutFullDistance_1',
    },
  },
  ChainAttackVFormScorchingSun_0: {
    sheet: 'Lighter',
    name: 'ChainAttackVFormScorchingSun_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackVFormScorchingSun_0',
    },
  },
  UltimateWFormCrownedInferno_0: {
    sheet: 'Lighter',
    name: 'UltimateWFormCrownedInferno_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateWFormCrownedInferno_0',
    },
  },
  QuickAssistBlazingFlashGuard_0: {
    sheet: 'Lighter',
    name: 'QuickAssistBlazingFlashGuard_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistBlazingFlashGuard_0',
    },
  },
  DefensiveAssistSwiftBreak_0: {
    sheet: 'Lighter',
    name: 'DefensiveAssistSwiftBreak_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistSwiftBreak_0',
    },
  },
  DefensiveAssistSwiftBreak_1: {
    sheet: 'Lighter',
    name: 'DefensiveAssistSwiftBreak_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistSwiftBreak_1',
    },
  },
  DefensiveAssistSwiftBreak_2: {
    sheet: 'Lighter',
    name: 'DefensiveAssistSwiftBreak_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistSwiftBreak_2',
    },
  },
  AssistFollowUpChargingSlamStab_0: {
    sheet: 'Lighter',
    name: 'AssistFollowUpChargingSlamStab_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpChargingSlamStab_0',
    },
  },
  m6_blazing_impact_dmg: {
    sheet: 'Lighter',
    name: 'm6_blazing_impact_dmg',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'standardDmgBase',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'elemental',
      name: 'm6_blazing_impact_dmg',
    },
  },
} as const
