// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Lighter',
    name: 'standardDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lighter',
      attribute: 'fire',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Lighter',
    name: 'anomalyDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_fire: {
    sheet: 'Lighter',
    name: 'disorderDmgInst_fire',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'disorder',
      name: 'disorderDmgInst_fire',
    },
  },
  vortexDmgInst_fire: {
    sheet: 'Lighter',
    name: 'vortexDmgInst_fire',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'vortex',
      name: 'vortexDmgInst_fire',
    },
  },
  abloomDmgInst: {
    sheet: 'Lighter',
    name: 'abloomDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Lighter',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Lighter',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      name: 'dazeInst',
    },
  },
  'BasicAttackLFormThunderingFist_0:standardDmg': {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lighter',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_0',
    },
  },
  'BasicAttackLFormThunderingFist_0:dazeBuildup': {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lighter',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_0',
    },
  },
  'BasicAttackLFormThunderingFist_0:anomBuildup': {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lighter',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_0',
    },
  },
  'BasicAttackLFormThunderingFist_1:standardDmg': {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lighter',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_1',
    },
  },
  'BasicAttackLFormThunderingFist_1:dazeBuildup': {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lighter',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_1',
    },
  },
  'BasicAttackLFormThunderingFist_1:anomBuildup': {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lighter',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_1',
    },
  },
  'BasicAttackLFormThunderingFist_2:standardDmg': {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lighter',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_2',
    },
  },
  'BasicAttackLFormThunderingFist_2:dazeBuildup': {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lighter',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_2',
    },
  },
  'BasicAttackLFormThunderingFist_2:anomBuildup': {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lighter',
      damageType1: 'basic',
      attribute: 'physical',
      skillType1: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_2',
    },
  },
  'BasicAttackLFormThunderingFist_3:standardDmg': {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_3:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_3',
    },
  },
  'BasicAttackLFormThunderingFist_3:dazeBuildup': {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_3:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_3',
    },
  },
  'BasicAttackLFormThunderingFist_3:anomBuildup': {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_3:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_3',
    },
  },
  'BasicAttackLFormThunderingFist_4:standardDmg': {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_4:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_4',
    },
  },
  'BasicAttackLFormThunderingFist_4:dazeBuildup': {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_4:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_4',
    },
  },
  'BasicAttackLFormThunderingFist_4:anomBuildup': {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_4:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_4',
    },
  },
  'BasicAttackLFormThunderingFist_5:standardDmg': {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_5:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_5',
    },
  },
  'BasicAttackLFormThunderingFist_5:dazeBuildup': {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_5:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_5',
    },
  },
  'BasicAttackLFormThunderingFist_5:anomBuildup': {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_5:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_5',
    },
  },
  'BasicAttackLFormThunderingFist_6:standardDmg': {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_6:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_6',
    },
  },
  'BasicAttackLFormThunderingFist_6:dazeBuildup': {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_6:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_6',
    },
  },
  'BasicAttackLFormThunderingFist_6:anomBuildup': {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_6:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_6',
    },
  },
  'BasicAttackLFormThunderingFist_7:standardDmg': {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_7:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_7',
    },
  },
  'BasicAttackLFormThunderingFist_7:dazeBuildup': {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_7:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_7',
    },
  },
  'BasicAttackLFormThunderingFist_7:anomBuildup': {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_7:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_7',
    },
  },
  'BasicAttackLFormThunderingFist_8:standardDmg': {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_8:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_8',
    },
  },
  'BasicAttackLFormThunderingFist_8:dazeBuildup': {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_8:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_8',
    },
  },
  'BasicAttackLFormThunderingFist_8:anomBuildup': {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_8:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_8',
    },
  },
  'BasicAttackLFormThunderingFist_9:standardDmg': {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_9:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_9',
    },
  },
  'BasicAttackLFormThunderingFist_9:dazeBuildup': {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_9:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_9',
    },
  },
  'BasicAttackLFormThunderingFist_9:anomBuildup': {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_9:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_9',
    },
  },
  'BasicAttackLFormThunderingFist_10:standardDmg': {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_10:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_10',
    },
  },
  'BasicAttackLFormThunderingFist_10:dazeBuildup': {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_10:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_10',
    },
  },
  'BasicAttackLFormThunderingFist_10:anomBuildup': {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_10:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_10',
    },
  },
  'BasicAttackLFormThunderingFist_11:standardDmg': {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_11:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_11',
    },
  },
  'BasicAttackLFormThunderingFist_11:dazeBuildup': {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_11:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_11',
    },
  },
  'BasicAttackLFormThunderingFist_11:anomBuildup': {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_11:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_11',
    },
  },
  'BasicAttackLFormThunderingFist_12:standardDmg': {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_12:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_12',
    },
  },
  'BasicAttackLFormThunderingFist_12:dazeBuildup': {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_12:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_12',
    },
  },
  'BasicAttackLFormThunderingFist_12:anomBuildup': {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_12:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_12',
    },
  },
  'BasicAttackLFormThunderingFist_13:standardDmg': {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_13:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_13',
    },
  },
  'BasicAttackLFormThunderingFist_13:dazeBuildup': {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_13:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_13',
    },
  },
  'BasicAttackLFormThunderingFist_13:anomBuildup': {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_13:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_13',
    },
  },
  'BasicAttackLFormThunderingFist_14:standardDmg': {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_14:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_14',
    },
  },
  'BasicAttackLFormThunderingFist_14:dazeBuildup': {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_14:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_14',
    },
  },
  'BasicAttackLFormThunderingFist_14:anomBuildup': {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_14:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_14',
    },
  },
  'BasicAttackLFormThunderingFist_15:standardDmg': {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_15:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_15',
    },
  },
  'BasicAttackLFormThunderingFist_15:dazeBuildup': {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_15:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_15',
    },
  },
  'BasicAttackLFormThunderingFist_15:anomBuildup': {
    sheet: 'Lighter',
    name: 'BasicAttackLFormThunderingFist_15:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'basic',
      skillType1: 'basicSkill',
      name: 'BasicAttackLFormThunderingFist_15',
    },
  },
  'DashAttackChargingSlam_0:standardDmg': {
    sheet: 'Lighter',
    name: 'DashAttackChargingSlam_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lighter',
      damageType1: 'dash',
      attribute: 'physical',
      skillType1: 'dodgeSkill',
      name: 'DashAttackChargingSlam_0',
    },
  },
  'DashAttackChargingSlam_0:dazeBuildup': {
    sheet: 'Lighter',
    name: 'DashAttackChargingSlam_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lighter',
      damageType1: 'dash',
      attribute: 'physical',
      skillType1: 'dodgeSkill',
      name: 'DashAttackChargingSlam_0',
    },
  },
  'DashAttackChargingSlam_0:anomBuildup': {
    sheet: 'Lighter',
    name: 'DashAttackChargingSlam_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lighter',
      damageType1: 'dash',
      attribute: 'physical',
      skillType1: 'dodgeSkill',
      name: 'DashAttackChargingSlam_0',
    },
  },
  'DodgeCounterBlazingFlash_0:standardDmg': {
    sheet: 'Lighter',
    name: 'DodgeCounterBlazingFlash_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'dodgeCounter',
      skillType1: 'dodgeSkill',
      name: 'DodgeCounterBlazingFlash_0',
    },
  },
  'DodgeCounterBlazingFlash_0:dazeBuildup': {
    sheet: 'Lighter',
    name: 'DodgeCounterBlazingFlash_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'dodgeCounter',
      skillType1: 'dodgeSkill',
      name: 'DodgeCounterBlazingFlash_0',
    },
  },
  'DodgeCounterBlazingFlash_0:anomBuildup': {
    sheet: 'Lighter',
    name: 'DodgeCounterBlazingFlash_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'dodgeCounter',
      skillType1: 'dodgeSkill',
      name: 'DodgeCounterBlazingFlash_0',
    },
  },
  'SpecialAttackVFormSunriseUppercut_0:standardDmg': {
    sheet: 'Lighter',
    name: 'SpecialAttackVFormSunriseUppercut_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackVFormSunriseUppercut_0',
    },
  },
  'SpecialAttackVFormSunriseUppercut_0:dazeBuildup': {
    sheet: 'Lighter',
    name: 'SpecialAttackVFormSunriseUppercut_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackVFormSunriseUppercut_0',
    },
  },
  'SpecialAttackVFormSunriseUppercut_0:anomBuildup': {
    sheet: 'Lighter',
    name: 'SpecialAttackVFormSunriseUppercut_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'special',
      skillType1: 'specialSkill',
      name: 'SpecialAttackVFormSunriseUppercut_0',
    },
  },
  'EXSpecialAttackVFormSunriseUppercutFullDistance_0:standardDmg': {
    sheet: 'Lighter',
    name: 'EXSpecialAttackVFormSunriseUppercutFullDistance_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackVFormSunriseUppercutFullDistance_0',
    },
  },
  'EXSpecialAttackVFormSunriseUppercutFullDistance_0:dazeBuildup': {
    sheet: 'Lighter',
    name: 'EXSpecialAttackVFormSunriseUppercutFullDistance_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackVFormSunriseUppercutFullDistance_0',
    },
  },
  'EXSpecialAttackVFormSunriseUppercutFullDistance_0:anomBuildup': {
    sheet: 'Lighter',
    name: 'EXSpecialAttackVFormSunriseUppercutFullDistance_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackVFormSunriseUppercutFullDistance_0',
    },
  },
  'EXSpecialAttackVFormSunriseUppercutFullDistance_1:standardDmg': {
    sheet: 'Lighter',
    name: 'EXSpecialAttackVFormSunriseUppercutFullDistance_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackVFormSunriseUppercutFullDistance_1',
    },
  },
  'EXSpecialAttackVFormSunriseUppercutFullDistance_1:dazeBuildup': {
    sheet: 'Lighter',
    name: 'EXSpecialAttackVFormSunriseUppercutFullDistance_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackVFormSunriseUppercutFullDistance_1',
    },
  },
  'EXSpecialAttackVFormSunriseUppercutFullDistance_1:anomBuildup': {
    sheet: 'Lighter',
    name: 'EXSpecialAttackVFormSunriseUppercutFullDistance_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'exSpecial',
      skillType1: 'specialSkill',
      name: 'EXSpecialAttackVFormSunriseUppercutFullDistance_1',
    },
  },
  'ChainAttackVFormScorchingSun_0:standardDmg': {
    sheet: 'Lighter',
    name: 'ChainAttackVFormScorchingSun_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'chain',
      skillType1: 'chainSkill',
      name: 'ChainAttackVFormScorchingSun_0',
    },
  },
  'ChainAttackVFormScorchingSun_0:dazeBuildup': {
    sheet: 'Lighter',
    name: 'ChainAttackVFormScorchingSun_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'chain',
      skillType1: 'chainSkill',
      name: 'ChainAttackVFormScorchingSun_0',
    },
  },
  'ChainAttackVFormScorchingSun_0:anomBuildup': {
    sheet: 'Lighter',
    name: 'ChainAttackVFormScorchingSun_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'chain',
      skillType1: 'chainSkill',
      name: 'ChainAttackVFormScorchingSun_0',
    },
  },
  'UltimateWFormCrownedInferno_0:standardDmg': {
    sheet: 'Lighter',
    name: 'UltimateWFormCrownedInferno_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'ult',
      skillType1: 'chainSkill',
      name: 'UltimateWFormCrownedInferno_0',
    },
  },
  'UltimateWFormCrownedInferno_0:dazeBuildup': {
    sheet: 'Lighter',
    name: 'UltimateWFormCrownedInferno_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'ult',
      skillType1: 'chainSkill',
      name: 'UltimateWFormCrownedInferno_0',
    },
  },
  'UltimateWFormCrownedInferno_0:anomBuildup': {
    sheet: 'Lighter',
    name: 'UltimateWFormCrownedInferno_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'ult',
      skillType1: 'chainSkill',
      name: 'UltimateWFormCrownedInferno_0',
    },
  },
  'QuickAssistBlazingFlashGuard_0:standardDmg': {
    sheet: 'Lighter',
    name: 'QuickAssistBlazingFlashGuard_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'quickAssist',
      skillType1: 'assistSkill',
      name: 'QuickAssistBlazingFlashGuard_0',
    },
  },
  'QuickAssistBlazingFlashGuard_0:dazeBuildup': {
    sheet: 'Lighter',
    name: 'QuickAssistBlazingFlashGuard_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'quickAssist',
      skillType1: 'assistSkill',
      name: 'QuickAssistBlazingFlashGuard_0',
    },
  },
  'QuickAssistBlazingFlashGuard_0:anomBuildup': {
    sheet: 'Lighter',
    name: 'QuickAssistBlazingFlashGuard_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'quickAssist',
      skillType1: 'assistSkill',
      name: 'QuickAssistBlazingFlashGuard_0',
    },
  },
  'DefensiveAssistSwiftBreak_0:standardDmg': {
    sheet: 'Lighter',
    name: 'DefensiveAssistSwiftBreak_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistSwiftBreak_0',
    },
  },
  'DefensiveAssistSwiftBreak_0:dazeBuildup': {
    sheet: 'Lighter',
    name: 'DefensiveAssistSwiftBreak_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistSwiftBreak_0',
    },
  },
  'DefensiveAssistSwiftBreak_0:anomBuildup': {
    sheet: 'Lighter',
    name: 'DefensiveAssistSwiftBreak_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistSwiftBreak_0',
    },
  },
  'DefensiveAssistSwiftBreak_1:standardDmg': {
    sheet: 'Lighter',
    name: 'DefensiveAssistSwiftBreak_1:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistSwiftBreak_1',
    },
  },
  'DefensiveAssistSwiftBreak_1:dazeBuildup': {
    sheet: 'Lighter',
    name: 'DefensiveAssistSwiftBreak_1:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistSwiftBreak_1',
    },
  },
  'DefensiveAssistSwiftBreak_1:anomBuildup': {
    sheet: 'Lighter',
    name: 'DefensiveAssistSwiftBreak_1:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistSwiftBreak_1',
    },
  },
  'DefensiveAssistSwiftBreak_2:standardDmg': {
    sheet: 'Lighter',
    name: 'DefensiveAssistSwiftBreak_2:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistSwiftBreak_2',
    },
  },
  'DefensiveAssistSwiftBreak_2:dazeBuildup': {
    sheet: 'Lighter',
    name: 'DefensiveAssistSwiftBreak_2:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistSwiftBreak_2',
    },
  },
  'DefensiveAssistSwiftBreak_2:anomBuildup': {
    sheet: 'Lighter',
    name: 'DefensiveAssistSwiftBreak_2:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'defensiveAssist',
      skillType1: 'assistSkill',
      name: 'DefensiveAssistSwiftBreak_2',
    },
  },
  'AssistFollowUpChargingSlamStab_0:standardDmg': {
    sheet: 'Lighter',
    name: 'AssistFollowUpChargingSlamStab_0:standardDmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'assistFollowUp',
      skillType1: 'assistSkill',
      name: 'AssistFollowUpChargingSlamStab_0',
    },
  },
  'AssistFollowUpChargingSlamStab_0:dazeBuildup': {
    sheet: 'Lighter',
    name: 'AssistFollowUpChargingSlamStab_0:dazeBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'assistFollowUp',
      skillType1: 'assistSkill',
      name: 'AssistFollowUpChargingSlamStab_0',
    },
  },
  'AssistFollowUpChargingSlamStab_0:anomBuildup': {
    sheet: 'Lighter',
    name: 'AssistFollowUpChargingSlamStab_0:anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'assistFollowUp',
      skillType1: 'assistSkill',
      name: 'AssistFollowUpChargingSlamStab_0',
    },
  },
  m6_blazing_impact_dmg: {
    sheet: 'Lighter',
    name: 'm6_blazing_impact_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Lighter',
      attribute: 'fire',
      damageType1: 'elemental',
      name: 'm6_blazing_impact_dmg',
    },
  },
} as const
