// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Seth',
    name: 'standardDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Seth',
      attribute: 'electric',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Seth',
    name: 'anomalyDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_electric: {
    sheet: 'Seth',
    name: 'disorderDmgInst_electric',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'disorder',
      name: 'disorderDmgInst_electric',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Seth',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Seth',
      attribute: 'electric',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Seth',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Seth',
      attribute: 'electric',
      name: 'dazeInst',
    },
  },
  BasicAttackLightningStrike_0_dmg: {
    sheet: 'Seth',
    name: 'BasicAttackLightningStrike_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Seth',
      damageType1: 'basic',
      attribute: 'physical',
      name: 'BasicAttackLightningStrike_0_dmg',
    },
  },
  BasicAttackLightningStrike_0_daze: {
    sheet: 'Seth',
    name: 'BasicAttackLightningStrike_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Seth',
      damageType1: 'basic',
      attribute: 'physical',
      name: 'BasicAttackLightningStrike_0_daze',
    },
  },
  BasicAttackLightningStrike_0_anomBuildup: {
    sheet: 'Seth',
    name: 'BasicAttackLightningStrike_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Seth',
      damageType1: 'basic',
      attribute: 'physical',
      name: 'BasicAttackLightningStrike_0_anomBuildup',
    },
  },
  BasicAttackLightningStrike_1_dmg: {
    sheet: 'Seth',
    name: 'BasicAttackLightningStrike_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Seth',
      damageType1: 'basic',
      attribute: 'physical',
      name: 'BasicAttackLightningStrike_1_dmg',
    },
  },
  BasicAttackLightningStrike_1_daze: {
    sheet: 'Seth',
    name: 'BasicAttackLightningStrike_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Seth',
      damageType1: 'basic',
      attribute: 'physical',
      name: 'BasicAttackLightningStrike_1_daze',
    },
  },
  BasicAttackLightningStrike_1_anomBuildup: {
    sheet: 'Seth',
    name: 'BasicAttackLightningStrike_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Seth',
      damageType1: 'basic',
      attribute: 'physical',
      name: 'BasicAttackLightningStrike_1_anomBuildup',
    },
  },
  BasicAttackLightningStrike_2_dmg: {
    sheet: 'Seth',
    name: 'BasicAttackLightningStrike_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Seth',
      damageType1: 'basic',
      attribute: 'physical',
      name: 'BasicAttackLightningStrike_2_dmg',
    },
  },
  BasicAttackLightningStrike_2_daze: {
    sheet: 'Seth',
    name: 'BasicAttackLightningStrike_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Seth',
      damageType1: 'basic',
      attribute: 'physical',
      name: 'BasicAttackLightningStrike_2_daze',
    },
  },
  BasicAttackLightningStrike_2_anomBuildup: {
    sheet: 'Seth',
    name: 'BasicAttackLightningStrike_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Seth',
      damageType1: 'basic',
      attribute: 'physical',
      name: 'BasicAttackLightningStrike_2_anomBuildup',
    },
  },
  BasicAttackLightningStrike_3_dmg: {
    sheet: 'Seth',
    name: 'BasicAttackLightningStrike_3_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLightningStrike_3_dmg',
    },
  },
  BasicAttackLightningStrike_3_daze: {
    sheet: 'Seth',
    name: 'BasicAttackLightningStrike_3_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLightningStrike_3_daze',
    },
  },
  BasicAttackLightningStrike_3_anomBuildup: {
    sheet: 'Seth',
    name: 'BasicAttackLightningStrike_3_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLightningStrike_3_anomBuildup',
    },
  },
  BasicAttackLightningStrikeElectrified_0_dmg: {
    sheet: 'Seth',
    name: 'BasicAttackLightningStrikeElectrified_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'basic',
      name: 'BasicAttackLightningStrikeElectrified_0_dmg',
    },
  },
  BasicAttackLightningStrikeElectrified_0_daze: {
    sheet: 'Seth',
    name: 'BasicAttackLightningStrikeElectrified_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'basic',
      name: 'BasicAttackLightningStrikeElectrified_0_daze',
    },
  },
  BasicAttackLightningStrikeElectrified_0_anomBuildup: {
    sheet: 'Seth',
    name: 'BasicAttackLightningStrikeElectrified_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'basic',
      name: 'BasicAttackLightningStrikeElectrified_0_anomBuildup',
    },
  },
  BasicAttackLightningStrikeElectrified_1_dmg: {
    sheet: 'Seth',
    name: 'BasicAttackLightningStrikeElectrified_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'basic',
      name: 'BasicAttackLightningStrikeElectrified_1_dmg',
    },
  },
  BasicAttackLightningStrikeElectrified_1_daze: {
    sheet: 'Seth',
    name: 'BasicAttackLightningStrikeElectrified_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'basic',
      name: 'BasicAttackLightningStrikeElectrified_1_daze',
    },
  },
  BasicAttackLightningStrikeElectrified_1_anomBuildup: {
    sheet: 'Seth',
    name: 'BasicAttackLightningStrikeElectrified_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'basic',
      name: 'BasicAttackLightningStrikeElectrified_1_anomBuildup',
    },
  },
  DashAttackThunderAssault_0_dmg: {
    sheet: 'Seth',
    name: 'DashAttackThunderAssault_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Seth',
      damageType1: 'dash',
      attribute: 'physical',
      name: 'DashAttackThunderAssault_0_dmg',
    },
  },
  DashAttackThunderAssault_0_daze: {
    sheet: 'Seth',
    name: 'DashAttackThunderAssault_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Seth',
      damageType1: 'dash',
      attribute: 'physical',
      name: 'DashAttackThunderAssault_0_daze',
    },
  },
  DashAttackThunderAssault_0_anomBuildup: {
    sheet: 'Seth',
    name: 'DashAttackThunderAssault_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Seth',
      damageType1: 'dash',
      attribute: 'physical',
      name: 'DashAttackThunderAssault_0_anomBuildup',
    },
  },
  DodgeCounterRetreatToAdvance_0_dmg: {
    sheet: 'Seth',
    name: 'DodgeCounterRetreatToAdvance_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterRetreatToAdvance_0_dmg',
    },
  },
  DodgeCounterRetreatToAdvance_0_daze: {
    sheet: 'Seth',
    name: 'DodgeCounterRetreatToAdvance_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterRetreatToAdvance_0_daze',
    },
  },
  DodgeCounterRetreatToAdvance_0_anomBuildup: {
    sheet: 'Seth',
    name: 'DodgeCounterRetreatToAdvance_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterRetreatToAdvance_0_anomBuildup',
    },
  },
  SpecialAttackThunderShieldRush_0_dmg: {
    sheet: 'Seth',
    name: 'SpecialAttackThunderShieldRush_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackThunderShieldRush_0_dmg',
    },
  },
  SpecialAttackThunderShieldRush_0_daze: {
    sheet: 'Seth',
    name: 'SpecialAttackThunderShieldRush_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackThunderShieldRush_0_daze',
    },
  },
  SpecialAttackThunderShieldRush_0_anomBuildup: {
    sheet: 'Seth',
    name: 'SpecialAttackThunderShieldRush_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackThunderShieldRush_0_anomBuildup',
    },
  },
  EXSpecialAttackThunderShieldRushHighVoltage_0_dmg: {
    sheet: 'Seth',
    name: 'EXSpecialAttackThunderShieldRushHighVoltage_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackThunderShieldRushHighVoltage_0_dmg',
    },
  },
  EXSpecialAttackThunderShieldRushHighVoltage_0_daze: {
    sheet: 'Seth',
    name: 'EXSpecialAttackThunderShieldRushHighVoltage_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackThunderShieldRushHighVoltage_0_daze',
    },
  },
  EXSpecialAttackThunderShieldRushHighVoltage_0_anomBuildup: {
    sheet: 'Seth',
    name: 'EXSpecialAttackThunderShieldRushHighVoltage_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackThunderShieldRushHighVoltage_0_anomBuildup',
    },
  },
  EXSpecialAttackThunderShieldRushHighVoltage_1_dmg: {
    sheet: 'Seth',
    name: 'EXSpecialAttackThunderShieldRushHighVoltage_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackThunderShieldRushHighVoltage_1_dmg',
    },
  },
  EXSpecialAttackThunderShieldRushHighVoltage_1_daze: {
    sheet: 'Seth',
    name: 'EXSpecialAttackThunderShieldRushHighVoltage_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackThunderShieldRushHighVoltage_1_daze',
    },
  },
  EXSpecialAttackThunderShieldRushHighVoltage_1_anomBuildup: {
    sheet: 'Seth',
    name: 'EXSpecialAttackThunderShieldRushHighVoltage_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackThunderShieldRushHighVoltage_1_anomBuildup',
    },
  },
  ChainAttackFinalJudgment_0_dmg: {
    sheet: 'Seth',
    name: 'ChainAttackFinalJudgment_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackFinalJudgment_0_dmg',
    },
  },
  ChainAttackFinalJudgment_0_daze: {
    sheet: 'Seth',
    name: 'ChainAttackFinalJudgment_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackFinalJudgment_0_daze',
    },
  },
  ChainAttackFinalJudgment_0_anomBuildup: {
    sheet: 'Seth',
    name: 'ChainAttackFinalJudgment_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackFinalJudgment_0_anomBuildup',
    },
  },
  UltimateJusticePrevails_0_dmg: {
    sheet: 'Seth',
    name: 'UltimateJusticePrevails_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateJusticePrevails_0_dmg',
    },
  },
  UltimateJusticePrevails_0_daze: {
    sheet: 'Seth',
    name: 'UltimateJusticePrevails_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateJusticePrevails_0_daze',
    },
  },
  UltimateJusticePrevails_0_anomBuildup: {
    sheet: 'Seth',
    name: 'UltimateJusticePrevails_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateJusticePrevails_0_anomBuildup',
    },
  },
  QuickAssistArmedSupport_0_dmg: {
    sheet: 'Seth',
    name: 'QuickAssistArmedSupport_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistArmedSupport_0_dmg',
    },
  },
  QuickAssistArmedSupport_0_daze: {
    sheet: 'Seth',
    name: 'QuickAssistArmedSupport_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistArmedSupport_0_daze',
    },
  },
  QuickAssistArmedSupport_0_anomBuildup: {
    sheet: 'Seth',
    name: 'QuickAssistArmedSupport_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistArmedSupport_0_anomBuildup',
    },
  },
  DefensiveAssistThundershield_0_dmg: {
    sheet: 'Seth',
    name: 'DefensiveAssistThundershield_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      name: 'DefensiveAssistThundershield_0_dmg',
    },
  },
  DefensiveAssistThundershield_0_daze: {
    sheet: 'Seth',
    name: 'DefensiveAssistThundershield_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      name: 'DefensiveAssistThundershield_0_daze',
    },
  },
  DefensiveAssistThundershield_0_anomBuildup: {
    sheet: 'Seth',
    name: 'DefensiveAssistThundershield_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      name: 'DefensiveAssistThundershield_0_anomBuildup',
    },
  },
  DefensiveAssistThundershield_1_dmg: {
    sheet: 'Seth',
    name: 'DefensiveAssistThundershield_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      name: 'DefensiveAssistThundershield_1_dmg',
    },
  },
  DefensiveAssistThundershield_1_daze: {
    sheet: 'Seth',
    name: 'DefensiveAssistThundershield_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      name: 'DefensiveAssistThundershield_1_daze',
    },
  },
  DefensiveAssistThundershield_1_anomBuildup: {
    sheet: 'Seth',
    name: 'DefensiveAssistThundershield_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      name: 'DefensiveAssistThundershield_1_anomBuildup',
    },
  },
  DefensiveAssistThundershield_2_dmg: {
    sheet: 'Seth',
    name: 'DefensiveAssistThundershield_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      name: 'DefensiveAssistThundershield_2_dmg',
    },
  },
  DefensiveAssistThundershield_2_daze: {
    sheet: 'Seth',
    name: 'DefensiveAssistThundershield_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      name: 'DefensiveAssistThundershield_2_daze',
    },
  },
  DefensiveAssistThundershield_2_anomBuildup: {
    sheet: 'Seth',
    name: 'DefensiveAssistThundershield_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      name: 'DefensiveAssistThundershield_2_anomBuildup',
    },
  },
  AssistFollowUpPublicSecurityRuling_0_dmg: {
    sheet: 'Seth',
    name: 'AssistFollowUpPublicSecurityRuling_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpPublicSecurityRuling_0_dmg',
    },
  },
  AssistFollowUpPublicSecurityRuling_0_daze: {
    sheet: 'Seth',
    name: 'AssistFollowUpPublicSecurityRuling_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpPublicSecurityRuling_0_daze',
    },
  },
  AssistFollowUpPublicSecurityRuling_0_anomBuildup: {
    sheet: 'Seth',
    name: 'AssistFollowUpPublicSecurityRuling_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpPublicSecurityRuling_0_anomBuildup',
    },
  },
  core_shield: {
    sheet: 'Seth',
    name: 'core_shield',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'shield',
      sheet: 'Seth',
      name: 'core_shield',
    },
  },
  m6_dmg: {
    sheet: 'Seth',
    name: 'm6_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Seth',
      damageType1: 'elemental',
      name: 'm6_dmg',
    },
  },
} as const
