// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Seth',
    name: 'standardDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'standardDmgBase',
      sheet: 'Seth',
      attribute: 'electric',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Seth',
    name: 'anomalyDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_electric: {
    sheet: 'Seth',
    name: 'disorderDmgInst_electric',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'disorder',
      name: 'disorderDmgInst_electric',
    },
  },
  vortexDmgInst_electric: {
    sheet: 'Seth',
    name: 'vortexDmgInst_electric',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'vortex',
      name: 'vortexDmgInst_electric',
    },
  },
  abloomDmgInst: {
    sheet: 'Seth',
    name: 'abloomDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Seth',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Seth',
      attribute: 'electric',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Seth',
    name: 'dazeInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'dazeBuildupBase',
      sheet: 'Seth',
      attribute: 'electric',
      name: 'dazeInst',
    },
  },
  BasicAttackLightningStrike_0: {
    sheet: 'Seth',
    name: 'BasicAttackLightningStrike_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Seth',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackLightningStrike_0',
    },
  },
  BasicAttackLightningStrike_1: {
    sheet: 'Seth',
    name: 'BasicAttackLightningStrike_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Seth',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackLightningStrike_1',
    },
  },
  BasicAttackLightningStrike_2: {
    sheet: 'Seth',
    name: 'BasicAttackLightningStrike_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Seth',
      damageType1: 'basic',
      attribute: 'physical',
      skillType: 'basicSkill',
      name: 'BasicAttackLightningStrike_2',
    },
  },
  BasicAttackLightningStrike_3: {
    sheet: 'Seth',
    name: 'BasicAttackLightningStrike_3',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLightningStrike_3',
    },
  },
  BasicAttackLightningStrikeElectrified_0: {
    sheet: 'Seth',
    name: 'BasicAttackLightningStrikeElectrified_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLightningStrikeElectrified_0',
    },
  },
  BasicAttackLightningStrikeElectrified_1: {
    sheet: 'Seth',
    name: 'BasicAttackLightningStrikeElectrified_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackLightningStrikeElectrified_1',
    },
  },
  DashAttackThunderAssault_0: {
    sheet: 'Seth',
    name: 'DashAttackThunderAssault_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Seth',
      damageType1: 'dash',
      attribute: 'physical',
      skillType: 'dodgeSkill',
      name: 'DashAttackThunderAssault_0',
    },
  },
  DodgeCounterRetreatToAdvance_0: {
    sheet: 'Seth',
    name: 'DodgeCounterRetreatToAdvance_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterRetreatToAdvance_0',
    },
  },
  SpecialAttackThunderShieldRush_0: {
    sheet: 'Seth',
    name: 'SpecialAttackThunderShieldRush_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackThunderShieldRush_0',
    },
  },
  EXSpecialAttackThunderShieldRushHighVoltage_0: {
    sheet: 'Seth',
    name: 'EXSpecialAttackThunderShieldRushHighVoltage_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackThunderShieldRushHighVoltage_0',
    },
  },
  EXSpecialAttackThunderShieldRushHighVoltage_1: {
    sheet: 'Seth',
    name: 'EXSpecialAttackThunderShieldRushHighVoltage_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackThunderShieldRushHighVoltage_1',
    },
  },
  ChainAttackFinalJudgment_0: {
    sheet: 'Seth',
    name: 'ChainAttackFinalJudgment_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackFinalJudgment_0',
    },
  },
  UltimateJusticePrevails_0: {
    sheet: 'Seth',
    name: 'UltimateJusticePrevails_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateJusticePrevails_0',
    },
  },
  QuickAssistArmedSupport_0: {
    sheet: 'Seth',
    name: 'QuickAssistArmedSupport_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistArmedSupport_0',
    },
  },
  DefensiveAssistThundershield_0: {
    sheet: 'Seth',
    name: 'DefensiveAssistThundershield_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistThundershield_0',
    },
  },
  DefensiveAssistThundershield_1: {
    sheet: 'Seth',
    name: 'DefensiveAssistThundershield_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistThundershield_1',
    },
  },
  DefensiveAssistThundershield_2: {
    sheet: 'Seth',
    name: 'DefensiveAssistThundershield_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistThundershield_2',
    },
  },
  AssistFollowUpPublicSecurityRuling_0: {
    sheet: 'Seth',
    name: 'AssistFollowUpPublicSecurityRuling_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Seth',
      attribute: 'electric',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpPublicSecurityRuling_0',
    },
  },
  core_shield: {
    sheet: 'Seth',
    name: 'core_shield',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'shieldBase',
      sheet: 'Seth',
      name: 'core_shield',
    },
  },
  m6_dmg: {
    sheet: 'Seth',
    name: 'm6_dmg',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'standardDmgBase',
      sheet: 'Seth',
      damageType1: 'elemental',
      name: 'm6_dmg',
    },
  },
} as const
