// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Nekomata',
    name: 'standardDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'standardDmgBase',
      sheet: 'Nekomata',
      attribute: 'physical',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Nekomata',
    name: 'anomalyDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_physical: {
    sheet: 'Nekomata',
    name: 'disorderDmgInst_physical',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'disorder',
      name: 'disorderDmgInst_physical',
    },
  },
  vortexDmgInst_physical: {
    sheet: 'Nekomata',
    name: 'vortexDmgInst_physical',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'vortex',
      name: 'vortexDmgInst_physical',
    },
  },
  abloomDmgInst: {
    sheet: 'Nekomata',
    name: 'abloomDmgInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomalyDmgBase',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'anomaly',
      damageType2: 'abloom',
      name: 'abloomDmgInst',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Nekomata',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Nekomata',
      attribute: 'physical',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Nekomata',
    name: 'dazeInst',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'dazeBuildupBase',
      sheet: 'Nekomata',
      attribute: 'physical',
      name: 'dazeInst',
    },
  },
  BasicAttackKittySlash_0: {
    sheet: 'Nekomata',
    name: 'BasicAttackKittySlash_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackKittySlash_0',
    },
  },
  BasicAttackKittySlash_1: {
    sheet: 'Nekomata',
    name: 'BasicAttackKittySlash_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackKittySlash_1',
    },
  },
  BasicAttackKittySlash_2: {
    sheet: 'Nekomata',
    name: 'BasicAttackKittySlash_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackKittySlash_2',
    },
  },
  BasicAttackKittySlash_3: {
    sheet: 'Nekomata',
    name: 'BasicAttackKittySlash_3',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackKittySlash_3',
    },
  },
  BasicAttackKittySlash_4: {
    sheet: 'Nekomata',
    name: 'BasicAttackKittySlash_4',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackKittySlash_4',
    },
  },
  BasicAttackCrimsonBlade_0: {
    sheet: 'Nekomata',
    name: 'BasicAttackCrimsonBlade_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackCrimsonBlade_0',
    },
  },
  DashAttackOverHere_0: {
    sheet: 'Nekomata',
    name: 'DashAttackOverHere_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackOverHere_0',
    },
  },
  DodgeCounterPhantomClaws_0: {
    sheet: 'Nekomata',
    name: 'DodgeCounterPhantomClaws_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterPhantomClaws_0',
    },
  },
  SpecialAttackSurpriseAttack_0: {
    sheet: 'Nekomata',
    name: 'SpecialAttackSurpriseAttack_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackSurpriseAttack_0',
    },
  },
  EXSpecialAttackSuperSurpriseAttack_0: {
    sheet: 'Nekomata',
    name: 'EXSpecialAttackSuperSurpriseAttack_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackSuperSurpriseAttack_0',
    },
  },
  ChainAttackClawSwipe_0: {
    sheet: 'Nekomata',
    name: 'ChainAttackClawSwipe_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackClawSwipe_0',
    },
  },
  UltimateClawSmash_0: {
    sheet: 'Nekomata',
    name: 'UltimateClawSmash_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateClawSmash_0',
    },
  },
  QuickAssistCatsPaw_0: {
    sheet: 'Nekomata',
    name: 'QuickAssistCatsPaw_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistCatsPaw_0',
    },
  },
  DefensiveAssistDesperateDefense_0: {
    sheet: 'Nekomata',
    name: 'DefensiveAssistDesperateDefense_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistDesperateDefense_0',
    },
  },
  DefensiveAssistDesperateDefense_1: {
    sheet: 'Nekomata',
    name: 'DefensiveAssistDesperateDefense_1',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistDesperateDefense_1',
    },
  },
  DefensiveAssistDesperateDefense_2: {
    sheet: 'Nekomata',
    name: 'DefensiveAssistDesperateDefense_2',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistDesperateDefense_2',
    },
  },
  AssistFollowUpShadowStrike_0: {
    sheet: 'Nekomata',
    name: 'AssistFollowUpShadowStrike_0',
    tag: {
      et: 'display',
      qt: 'formula',
      q: 'anomBuildupBase',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpShadowStrike_0',
    },
  },
} as const
