// WARNING: Generated file, do not modify
export const formulas = {
  standardDmgInst: {
    sheet: 'Nekomata',
    name: 'standardDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Nekomata',
      attribute: 'physical',
      name: 'standardDmgInst',
    },
  },
  anomalyDmgInst: {
    sheet: 'Nekomata',
    name: 'anomalyDmgInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'anomaly',
      name: 'anomalyDmgInst',
    },
  },
  disorderDmgInst_physical: {
    sheet: 'Nekomata',
    name: 'disorderDmgInst_physical',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomalyDmg',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'disorder',
      name: 'disorderDmgInst_physical',
    },
  },
  anomalyBuildupInst: {
    sheet: 'Nekomata',
    name: 'anomalyBuildupInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Nekomata',
      attribute: 'physical',
      name: 'anomalyBuildupInst',
    },
  },
  dazeInst: {
    sheet: 'Nekomata',
    name: 'dazeInst',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Nekomata',
      attribute: 'physical',
      name: 'dazeInst',
    },
  },
  BasicAttackKittySlash_0_dmg: {
    sheet: 'Nekomata',
    name: 'BasicAttackKittySlash_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackKittySlash_0_dmg',
    },
  },
  BasicAttackKittySlash_0_daze: {
    sheet: 'Nekomata',
    name: 'BasicAttackKittySlash_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackKittySlash_0_daze',
    },
  },
  BasicAttackKittySlash_0_anomBuildup: {
    sheet: 'Nekomata',
    name: 'BasicAttackKittySlash_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackKittySlash_0_anomBuildup',
    },
  },
  BasicAttackKittySlash_1_dmg: {
    sheet: 'Nekomata',
    name: 'BasicAttackKittySlash_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackKittySlash_1_dmg',
    },
  },
  BasicAttackKittySlash_1_daze: {
    sheet: 'Nekomata',
    name: 'BasicAttackKittySlash_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackKittySlash_1_daze',
    },
  },
  BasicAttackKittySlash_1_anomBuildup: {
    sheet: 'Nekomata',
    name: 'BasicAttackKittySlash_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackKittySlash_1_anomBuildup',
    },
  },
  BasicAttackKittySlash_2_dmg: {
    sheet: 'Nekomata',
    name: 'BasicAttackKittySlash_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackKittySlash_2_dmg',
    },
  },
  BasicAttackKittySlash_2_daze: {
    sheet: 'Nekomata',
    name: 'BasicAttackKittySlash_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackKittySlash_2_daze',
    },
  },
  BasicAttackKittySlash_2_anomBuildup: {
    sheet: 'Nekomata',
    name: 'BasicAttackKittySlash_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackKittySlash_2_anomBuildup',
    },
  },
  BasicAttackKittySlash_3_dmg: {
    sheet: 'Nekomata',
    name: 'BasicAttackKittySlash_3_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackKittySlash_3_dmg',
    },
  },
  BasicAttackKittySlash_3_daze: {
    sheet: 'Nekomata',
    name: 'BasicAttackKittySlash_3_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackKittySlash_3_daze',
    },
  },
  BasicAttackKittySlash_3_anomBuildup: {
    sheet: 'Nekomata',
    name: 'BasicAttackKittySlash_3_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackKittySlash_3_anomBuildup',
    },
  },
  BasicAttackKittySlash_4_dmg: {
    sheet: 'Nekomata',
    name: 'BasicAttackKittySlash_4_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackKittySlash_4_dmg',
    },
  },
  BasicAttackKittySlash_4_daze: {
    sheet: 'Nekomata',
    name: 'BasicAttackKittySlash_4_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackKittySlash_4_daze',
    },
  },
  BasicAttackKittySlash_4_anomBuildup: {
    sheet: 'Nekomata',
    name: 'BasicAttackKittySlash_4_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackKittySlash_4_anomBuildup',
    },
  },
  BasicAttackCrimsonBlade_0_dmg: {
    sheet: 'Nekomata',
    name: 'BasicAttackCrimsonBlade_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackCrimsonBlade_0_dmg',
    },
  },
  BasicAttackCrimsonBlade_0_daze: {
    sheet: 'Nekomata',
    name: 'BasicAttackCrimsonBlade_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackCrimsonBlade_0_daze',
    },
  },
  BasicAttackCrimsonBlade_0_anomBuildup: {
    sheet: 'Nekomata',
    name: 'BasicAttackCrimsonBlade_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'basic',
      skillType: 'basicSkill',
      name: 'BasicAttackCrimsonBlade_0_anomBuildup',
    },
  },
  DashAttackOverHere_0_dmg: {
    sheet: 'Nekomata',
    name: 'DashAttackOverHere_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackOverHere_0_dmg',
    },
  },
  DashAttackOverHere_0_daze: {
    sheet: 'Nekomata',
    name: 'DashAttackOverHere_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackOverHere_0_daze',
    },
  },
  DashAttackOverHere_0_anomBuildup: {
    sheet: 'Nekomata',
    name: 'DashAttackOverHere_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'dash',
      skillType: 'dodgeSkill',
      name: 'DashAttackOverHere_0_anomBuildup',
    },
  },
  DodgeCounterPhantomClaws_0_dmg: {
    sheet: 'Nekomata',
    name: 'DodgeCounterPhantomClaws_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterPhantomClaws_0_dmg',
    },
  },
  DodgeCounterPhantomClaws_0_daze: {
    sheet: 'Nekomata',
    name: 'DodgeCounterPhantomClaws_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterPhantomClaws_0_daze',
    },
  },
  DodgeCounterPhantomClaws_0_anomBuildup: {
    sheet: 'Nekomata',
    name: 'DodgeCounterPhantomClaws_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'dodgeCounter',
      skillType: 'dodgeSkill',
      name: 'DodgeCounterPhantomClaws_0_anomBuildup',
    },
  },
  SpecialAttackSurpriseAttack_0_dmg: {
    sheet: 'Nekomata',
    name: 'SpecialAttackSurpriseAttack_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackSurpriseAttack_0_dmg',
    },
  },
  SpecialAttackSurpriseAttack_0_daze: {
    sheet: 'Nekomata',
    name: 'SpecialAttackSurpriseAttack_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackSurpriseAttack_0_daze',
    },
  },
  SpecialAttackSurpriseAttack_0_anomBuildup: {
    sheet: 'Nekomata',
    name: 'SpecialAttackSurpriseAttack_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'special',
      skillType: 'specialSkill',
      name: 'SpecialAttackSurpriseAttack_0_anomBuildup',
    },
  },
  EXSpecialAttackSuperSurpriseAttack_0_dmg: {
    sheet: 'Nekomata',
    name: 'EXSpecialAttackSuperSurpriseAttack_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackSuperSurpriseAttack_0_dmg',
    },
  },
  EXSpecialAttackSuperSurpriseAttack_0_daze: {
    sheet: 'Nekomata',
    name: 'EXSpecialAttackSuperSurpriseAttack_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackSuperSurpriseAttack_0_daze',
    },
  },
  EXSpecialAttackSuperSurpriseAttack_0_anomBuildup: {
    sheet: 'Nekomata',
    name: 'EXSpecialAttackSuperSurpriseAttack_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'exSpecial',
      skillType: 'specialSkill',
      name: 'EXSpecialAttackSuperSurpriseAttack_0_anomBuildup',
    },
  },
  ChainAttackClawSwipe_0_dmg: {
    sheet: 'Nekomata',
    name: 'ChainAttackClawSwipe_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackClawSwipe_0_dmg',
    },
  },
  ChainAttackClawSwipe_0_daze: {
    sheet: 'Nekomata',
    name: 'ChainAttackClawSwipe_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackClawSwipe_0_daze',
    },
  },
  ChainAttackClawSwipe_0_anomBuildup: {
    sheet: 'Nekomata',
    name: 'ChainAttackClawSwipe_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'chain',
      skillType: 'chainSkill',
      name: 'ChainAttackClawSwipe_0_anomBuildup',
    },
  },
  UltimateClawSmash_0_dmg: {
    sheet: 'Nekomata',
    name: 'UltimateClawSmash_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateClawSmash_0_dmg',
    },
  },
  UltimateClawSmash_0_daze: {
    sheet: 'Nekomata',
    name: 'UltimateClawSmash_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateClawSmash_0_daze',
    },
  },
  UltimateClawSmash_0_anomBuildup: {
    sheet: 'Nekomata',
    name: 'UltimateClawSmash_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'ult',
      skillType: 'chainSkill',
      name: 'UltimateClawSmash_0_anomBuildup',
    },
  },
  QuickAssistCatsPaw_0_dmg: {
    sheet: 'Nekomata',
    name: 'QuickAssistCatsPaw_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistCatsPaw_0_dmg',
    },
  },
  QuickAssistCatsPaw_0_daze: {
    sheet: 'Nekomata',
    name: 'QuickAssistCatsPaw_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistCatsPaw_0_daze',
    },
  },
  QuickAssistCatsPaw_0_anomBuildup: {
    sheet: 'Nekomata',
    name: 'QuickAssistCatsPaw_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'quickAssist',
      skillType: 'assistSkill',
      name: 'QuickAssistCatsPaw_0_anomBuildup',
    },
  },
  DefensiveAssistDesperateDefense_0_dmg: {
    sheet: 'Nekomata',
    name: 'DefensiveAssistDesperateDefense_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistDesperateDefense_0_dmg',
    },
  },
  DefensiveAssistDesperateDefense_0_daze: {
    sheet: 'Nekomata',
    name: 'DefensiveAssistDesperateDefense_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistDesperateDefense_0_daze',
    },
  },
  DefensiveAssistDesperateDefense_0_anomBuildup: {
    sheet: 'Nekomata',
    name: 'DefensiveAssistDesperateDefense_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistDesperateDefense_0_anomBuildup',
    },
  },
  DefensiveAssistDesperateDefense_1_dmg: {
    sheet: 'Nekomata',
    name: 'DefensiveAssistDesperateDefense_1_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistDesperateDefense_1_dmg',
    },
  },
  DefensiveAssistDesperateDefense_1_daze: {
    sheet: 'Nekomata',
    name: 'DefensiveAssistDesperateDefense_1_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistDesperateDefense_1_daze',
    },
  },
  DefensiveAssistDesperateDefense_1_anomBuildup: {
    sheet: 'Nekomata',
    name: 'DefensiveAssistDesperateDefense_1_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistDesperateDefense_1_anomBuildup',
    },
  },
  DefensiveAssistDesperateDefense_2_dmg: {
    sheet: 'Nekomata',
    name: 'DefensiveAssistDesperateDefense_2_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistDesperateDefense_2_dmg',
    },
  },
  DefensiveAssistDesperateDefense_2_daze: {
    sheet: 'Nekomata',
    name: 'DefensiveAssistDesperateDefense_2_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistDesperateDefense_2_daze',
    },
  },
  DefensiveAssistDesperateDefense_2_anomBuildup: {
    sheet: 'Nekomata',
    name: 'DefensiveAssistDesperateDefense_2_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'defensiveAssist',
      skillType: 'assistSkill',
      name: 'DefensiveAssistDesperateDefense_2_anomBuildup',
    },
  },
  AssistFollowUpShadowStrike_0_dmg: {
    sheet: 'Nekomata',
    name: 'AssistFollowUpShadowStrike_0_dmg',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'standardDmg',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpShadowStrike_0_dmg',
    },
  },
  AssistFollowUpShadowStrike_0_daze: {
    sheet: 'Nekomata',
    name: 'AssistFollowUpShadowStrike_0_daze',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'dazeBuildup',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpShadowStrike_0_daze',
    },
  },
  AssistFollowUpShadowStrike_0_anomBuildup: {
    sheet: 'Nekomata',
    name: 'AssistFollowUpShadowStrike_0_anomBuildup',
    tag: {
      et: 'own',
      qt: 'formula',
      q: 'anomBuildup',
      sheet: 'Nekomata',
      attribute: 'physical',
      damageType1: 'assistFollowUp',
      skillType: 'assistSkill',
      name: 'AssistFollowUpShadowStrike_0_anomBuildup',
    },
  },
} as const
