name: New Beta ZO Release

on:
  push:
    branches:
      - master

# Only allow the most recent run of beta release to complete, if multiple are queued.
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  call-build-frontend:
    uses: ./.github/workflows/build-frontend.yml
    with:
      frontend_name: 'zzz-frontend'
      deployment_name: 'beta'
      show_dev_components: true
