name: New ZO Release

on:
  workflow_dispatch:

jobs:
  call-build-frontend:
    uses: ./.github/workflows/build-frontend.yml
    with:
      frontend_name: 'zzz-frontend'
      deployment_name: '.'
      repo_name: ${{ vars.ZO_REPO}}
      repo_deploy_secret_name: 'ZO_REPO_SSH_KEY'
      show_dev_components: false
      nested_deployments: false
